### PR TITLE
Fix failsafe autodisarm issues

### LINKED ISSUE #778: Disable disarming when failsafe is activated as a flight mode
When RC receiver only supports setting channel values on failsafe the only way to engage failsafe procedure is to configure `FAILSAFE` box mode.

The problem is that if one uses switch arming, the machine will disarm on failsafe if proper channel is not set to `ARM`. This is, however, unsafe, because it will make the machine actually arm when you turn off the TX.

Proposed fix - retain arming state when failsafe is enabled via `FAILSAFE` box mode. This way on failsafe maching won't arm or disarm and failsafe procedure will be correctly executed.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #778, #786

### CODE REVIEW

**Comment by digitalentity** [comment]
@oleost @DzikuVx @martinbudden I'd like to hear your thoughts on this one. Should we introduce new "flavours" for some targets w/o softserial but with I2C on different pins freing up Flex ports to be Serial-only?

**Comment by oleost** [comment]
@digitalentity Got to do some testing.
1. Its does not fix #786 , I didn't try with "failsafe_throttle_low_delay" set to zero, as the default 100 should be 10 seconds which are reasonable and I only cut my throttle 1s before turning of TX.
2. After I turn on the radio after an failsafe event and regain controll of my airplane it refuses to disarm at all.  I had to pull battery out to get it to disarm.

https://drive.google.com/open?id=0B-yHzNtOXxbERkUwVHJuS3czVDA log 42 and 43

**Comment by digitalentity** [comment]
@oleost issue found and fixed. Should work as intended now.

If you are interested - it's the "stage 2 guard time" that was causing trouble. Basically during that time you have FAILSAFE mode enables and ARM disabled, **but** actual failsafe is waiting for guard time to pass so normal disarm happens and **after** that failsafe kicks in. This is fixed now.

**Comment by oleost** [comment]
Will test today. 

OFC I'm interested 👍 Trying to learn to code a bit myself.
Currently I wrote a simple water script for my arduino that water my plants based on moisture. And going trough a Learn C++ by Sololearn. And planning to maybe move forward going trough "This is CS50 2014"

**Comment by oleost** [comment]
@digitalentity Can confirm Im allowed to disarm now.

Still #786 is not working.
https://drive.google.com/open?id=0B-yHzNtOXxbERkUwVHJuS3czVDA log44 with throttle and are allowed to disarm. log45 is when I throttle down right before turning of TX and it does not work.

Seems like the "failsafe_throttle_low_delay" is not working as intended.

**Comment by digitalentity** [comment]
Hmm... How is failsafe configured on your receiver? Is it PPM or SBUS? Can
you also upload a dump of your setup?

**Comment by oleost** [comment]
@digitalentity Dump is in same folder as logs. But here is an pastebin link aswell. http://pastebin.com/Lfg8BWcY

I have and FrSky XSR, so its SBUS and set to "no pulses"

**Comment by digitalentity** [comment]
Might be SBus related. Will check, thanks.

**Comment by oleost** [comment]
Okey. No thank you :)

**Comment by digitalentity** [comment]
@oleost how LOG45 is not working? I see RTH correctly activating when you turn off your TX and trying to reach the return altitude.

**Comment by digitalentity** [comment]
Also did tests with PPM (D4R-II) and S.BUS (X4R) receivers - no issues at all

What's tested:
No pulses failsafe + non-zero throttle = failsafe activation, no disarm
No pulses failsafe + short zero throttle = failsafe activation, no disarm
"FAILSAFE" flight mode activation + non-zero throttle = failsafe activation, no disarm
"FAILSAFE" flight mode activation + short zero throttle = failsafe activation, no disarm

**Comment by oleost** [comment]
@digitalentity Hmm, LOG45 is working here. I tried opening it directly from my google disk.

Anyway, made two videos showing, first one shows the log in blackbox viewer.
Secound one shows when I activate failsafe. (This time inside, but all the other times have been outside) 

https://www.youtube.com/watch?v=vSu6vC18jhI

2 video is currently uploading. Will repost when its done.

**Comment by oleost** [comment]
Hmm this is wierd. Currently I working 12 hours shift, so got limited time testing out.

Also in my airplane its solderered everything together. So I would need to unsolder to try with other RX.

**Comment by oleost** [comment]
https://youtu.be/iro74Clhk3c

**Comment by oleost** [comment]
Here is log 45 reuploaded [LOG00045.TXT](https://github.com/iNavFlight/inav/files/587192/LOG00045.TXT)

**Comment by digitalentity** [comment]
Failsafe actually activates, but throttle is held at 0% holding motor_stop activated.
Motor stop must be ignored when failsafe is active.
Fixed

**Comment by oleost** [comment]
@digitalentity Got to do an quick test outside today. 

Can confirm it working as intended now based on two small test. (One with throttle applied and one without)

Regarding the other log where I was indoor and failsafe didnt go off at all, Im unsure whats happends there. And since I'm working 12 hours shift this weekend I have not had any time to look more into it.

**Comment by digitalentity** [comment]
Great! I'll do more testing with PPM receivers and merge.

**Comment by digitalentity** [comment]
Looks like all working as expected. Merging.

**Comment by mooiweertje** [comment]
I've had my wing disarming a few times when I was in RXLOSS/failsave/RTH. Today it disarmed for no obvious reason, probably RXLOSS/failsave/RTH, and and it fell out of the sky.
I think INav in this state is not save to fly and needs to be fixed before any download is permitted.

**Comment by teckel12** [comment]
@mooiweertje What version of INAV? Got logs?

**Comment by mooiweertje** [comment]
No logs since the model is lost. I've seen this issue on version 2.1 and 2.2. You can reproduce it by flying with low power RC output and make it RXLOSS/failsave/RTH repeatedly. My two wings will disarm within ten times for sure. The last time it happend was the first time RXLOSS that flight so I'm a bit worried now.

**Comment by teckel12** [comment]
@mooiweertje I've simulated Rx signal loss. In certain edge cases with 2.1 and previous it could fail. I submitted an issue on this which was fixed in 2.2.  If you can duplicate this, submit logs. If it happened with 2.1 or previous, it's possible it was fixed in 2.2.

**Comment by teckel12** [comment]
@mooiweertje Also, this is a 2.5 year old issue concerning a very old version of INAV.  Create a new issue and supply logs if your able to duplicate. For me, RTH issues have been resolved in 2.2.

**Comment by mooiweertje** [comment]
The wing I have lost yesterday was running 2.2. I will create a new issue but I will not try to reproduce since losing one wing is enough for one week.
Besides this issue I noticed more problems in the past. For instance with a quad that at RTH sometimes the quad doesn't reach the necessary height it just hangs in the air until the battery is dead.

**Comment by teckel12** [comment]
@mooiweertje A quad that hangs in the air during RTH is almost always due to magnetic interference. I'm not aware of any software issues that would cause this. But again, if it happens, supply settings, logs, and the hardware being used and someone can either identify your problem or isolate a bug (which I'm unaware exists as RTH always works for me).

**Comment by mooiweertje** [comment]
It was configured to climb to 60 meter before returning. It didn't reach 60 meter and stuck at 58 meter.

**Comment by teckel12** [comment]
@mooiweertje Black box evidence of this would allow investigation. Without evidence, it's speculation at best. Do the bare minimum of due diligence, this is **YOUR** responsibility.

**Comment by giacomo892** [comment]
@mooiweertje issue with RTH stuck at climb phase has been solved ages ago

**Comment by mooiweertje** [comment]
Why don't you close this issue?

**Comment by teckel12** [comment]
@mooiweertje An issue being open or closed doesn't always mean it's fixed or not. Reviewing 3 year old issues to confirm resolved state just isn't high on anyone's list.

Keep in mind that this is a not a commercial product with a paid staff. It's all volunteers who typically do what they're interests are. 

In the case of this issue, I believe it's fairly clear that this issue was resolved, there's a pull request linked as evidence.

**Comment by jfmrod** [comment]
This is a bit off topic but, quad hanging in the air could also be too low P value (and no I) on the altimeter preventing it from reaching the target altitude. It may make sense to have a nonzero I as default

**Pull request merged**
