### PR TITLE
Hardware failure detection and warning

### LINKED ISSUE #650: Clear indication of compass failure
A number of compass-related issues appear recently. In case it happens in the field, there is no clear indication to the pilot that some navigational features (including emergency RTH) may not work.

For GPS and BARO we may observe telemetry and OSD reports. But there's no such thing for MAG.

What would be the best indication method:
- re-using some telemetry fields (e.g. GPS related)?
- led-strip error indication?
- audible alert (buzzer)?
- arm-block (sufficient only for boot-time failure)?
- all the above?

### PR DESCRIPTION
**Pull request by digitalentity**
Continuation of #731. Fixes #650.

Added new generic ledstrip warning: HW_ERROR (BLUE-BLACK)
HW_ERROR warning set on compass failure (on init or in runtime)

Things to do:

- [x] ~~Create failure detection for all available sensors (GYRO, ACC, BARO, MAG, SONAR, GPS)~~
- [x] Make a way to indicate sensor failure for machines w/o ledstrip
- [x] Report sensor health via telemetry and MSP
- [x] ~~Configurator support for clearly indicating the failure~~
- [x] Block ARMing if one of configured sensor fails
- [x] Make sensor selection explicit (no autodetection)
- [x] Support sensor hardware selection via MSP

### CODE REVIEW

**Comment by digitalentity** [comment]
Explisit sensor selection functional, also human-readable names for `*_hardware` settings:
image

**Comment by digitalentity** [comment]
Hardware failures will be indicated by short constant beeping.

**Comment by digitalentity** [comment]
@DzikuVx, @stronnag, @martinbudden what's your oppinion on https://github.com/iNavFlight/inav/pull/744/commits/d1af0d8e06da237bd7b42fadcf6898c207e81541?

**Comment by martinbudden** [comment]
Looks good to me.

**Comment by stronnag** [comment]
Looks good. Mwp updates and testing to follow.

**Comment by digitalentity** [comment]
@DzikuVx we need support for MSP_SENSOR_CONFIG and MSP_SET_SENSOR_CONFIG (as in Betaflight). Can you spend some of your time on configurator support for this? Also, polling and reading MSP_SENSOR_STATUS would be good.

**Comment by DzikuVx** [comment]
@digitalentity I will be able to go back to INAV somewhere around next week and this will be next on my list, 3rd in total :)

**Comment by stronnag** [comment]
By setting an 'isHealthy()' rather than an 'isBroken()' bit in MSP and LTM, we have now created a backwards compatibility / iNav version dependency in every CGS and OSD that wishes to check this status. May cause some usability issues for old firmware and "updated but not checking version" of 3rd party s/ware.

**Comment by stronnag** [comment]
We only send out X FRAME when the HDOP changes (mea culpa). Either we should also check if the hardware status has changed as well, or send unconditionally. I don't mind which we do (minor complication in iNav v. bandwidth).

**Comment by digitalentity** [comment]
@stronnag agreed. The legacy firmwares will set the bit to "0", so we should set is as `isBroken()`. I'll also send X-frames at 1Hz explicitly - not so much bandwidth to save.

**Comment by stronnag** [comment]
Bench tested for MSP and LTM. No issues. Now supported in mwp :) alerts issued as expected on disconnection / connection of sensors.

**Comment by stronnag** [comment]
Flight tested. Works perfectly (no hardware failures, and no alarms :). 

Please consider merging this.

**Comment by stronnag** [comment]
And just FYI, this is now documented in  https://github.com/iNavFlight/inav/wiki/Lightweight-Telemetry-(LTM) and Bart has agreed to support it in ezgui (it is already in mwp).

**Comment by digitalentity** [comment]
Configurator support done in https://github.com/iNavFlight/inav-configurator/pull/79

**Comment by digitalentity** [comment]
Yay! Configurator support done for sensor status reporting - works nicely:
image

**Comment by digitalentity** [comment]
Support for managing disabled/enabled sensors and setting the hardware via GUI is still required - https://github.com/iNavFlight/inav-configurator/issues/77

**Pull request merged**
