### PR TITLE
Split some tasks out of mw.c into fc_tasks.c

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
Ah, more cleanups! I like cleanups!

**Comment by martinbudden** [comment]
@digitalentity , @stronnag , this is a simple code rearrangement so should not cause any problems. But could one of you independently test before this is merged? Thanks.

**Comment by DzikuVx** [comment]
Reminder to myself: #421

**Comment by stronnag** [comment]
Flight tested, manual and nav modes (SPRF3)

**Pull request merged**
