### PR TITLE
Initial support for flock

### PR DESCRIPTION
**Pull request by fiam**
Flock allows a vehicle to receive and store information about other
vehicles around it. This is just the initial implementation which
receives the flock messages in Raven's format and stores their
information, position, speed and heading. No OSD support yet.

Depends on #4116

### CODE REVIEW

**Comment by wx4cb** [comment]
any  link to more info on flock, sounds interesting

**Comment by fiam** [comment]
There’s no documentation for now, other than the code here and in Raven. Once things settle down a bit, I’ll document how to build the hardware.

**Comment by Pairan** [comment]
Could this be the foundation for #3626 ?

**Comment by fiam** [comment]
That’s one of the goals

**Comment by Rusty105** [comment]
@fiam 
Good morning, I am working on something similar for Ardupilot, so planes flying in tandem can find each other to meetup in flight. I am only in the early stages, but hopefully will have some rudimentary functionality by summer ( I am slow at coding). I just stumbled on iNAV Radar and Raven, and I thought some interoperability would be good. Obviously the code on either side of the radio link is going to be different, but I was hoping to share the same radio link specs so users of iNAV, Raven, and Ardupilot could fly together. Do you know exactly what is in the data packet that flock is using? I tried combing through the iNAV Radar code and the Raven LRS code, but not finding any documentation on this. The only place I see 'Flock' mentioned is this branch.
Thanks!
Rusty

**Comment by Pairan** [comment]
@Rusty105 you might want to look here #4558 ... ;)

**Comment by Rusty105** [comment]
@Pairan, Thanks. I  have looked through that and it has mostly the data after the radio receives  it and sends it to the flight controller. I am still looking for what, and in what format, that data is sent from radio to radio.
Thanks!

**Comment by wx4cb** [comment]
@Rusty105 you want to find what it is "over the air"? I would assume you would have to talk to the manufacturers of the radio devices as that's something that would not be controlled by the inav (or ground station s/w) dev teams.

I know for example with XBEE, the radios we use at work use standard serial data encapsulated in a xbee packet frame. so although the data we're sending is plain text for the most part (in a certain format of course), when you try and sniff that data, it's actually been packetised by the radio hardware itself.

**Comment by Rusty105** [comment]
@wx4cb, nothing that complicated, actually your 2nd paragraph hits the nail on the head. I am, going to use basically the same radio chip, so the two radios will do all the 'heavy lifting' I just need the format of what is sent to the radio.
For example, I figure at a minimum it would have callsign of plane, lat, lon, alt, heading, speed. But in what order, and what data type was it before it got sent to the radio.
Something like this (image is not mine)
https://user-images.githubusercontent.com/15231822/52176197-8d9ac000-27af-11e9-858a-a8c203304b80.png

**Comment by wx4cb** [comment]
are you trying to "sniff" the packets while in the air? usually those radios are used with something like mavlink or LTM - both of which are publically available. in fact they're in the inav wiki. I'm using msp and mavlink right now, but will be switching over to ltm as it's less bandwidth over the crossfire

**Comment by Rusty105** [comment]
no, no in air sniffing, as no one near me has iNAV radar

**Comment by fiam** [comment]
@Rusty105 @wx4cb I've created a repository to host the flock specification, a reference library and a minimal board design with an F0 and an SX1278 module at https://github.com/RavenLRS/Flock

Hardware is complete, protocol is in progress and reference implementation is not done yet, but feel free to open issues and send pull requests.

**Comment by Rusty105** [comment]
@fiam  Thanks, I'll post questions and issues over there.

Rusty

**Pull request closed without merging**
