### PR TITLE
Kalman experiment for attitude computation

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by junwoo091400** [comment]
Nice. I've been learning how to use Kalman Filters lately(in Matlab). And I don't see exactly **'what' state(vector) you are estimating(Noob) :(**
i.e. "out, bias" in filter struct

p.s.) ince the Quaternions are already in the codebase, maybe using a quaternion-based kalman filter might be feasible?

**Comment by mbrunnen** [comment]
You mean altitude?

**Comment by DzikuVx** [comment]
OK, we can assume it does not work this way: https://youtu.be/j2a9bEbBxEg

**Comment by UpMostBeast** [comment]
Hey. I think I have an idea as to why the filter doesn't work. As far as I can tell, the filter uses gyro rates to update the new euler angles. I think you might need to convert the gyro rates to euler angle rates to integrate and calculate the right change in euler angles and get the new ones. Using gyro rates may be contributing to the attitude bar being farther off when the quad is tilted away from horizontal since the euler rates and gyro rates are almost identical when the quadcopter is oriented close to level, but they become different the farther the quadcopter is oriented away from being level.

**Pull request closed without merging**
