### PR TITLE
Generic RCDevice support first submission

### PR DESCRIPTION
**Pull request by azolyoung**
Hi,

This PR contains the following features:
- New Protocol for RunCam device(for now, it's for Split and FPV cam)
- Also including Power Button Toggle\Wifi-Button Toggle\Change Mode
- 5 Key OSD cable simulation

I have to thank some guys here, because they have helped a lot with this PR implementation to make these codes better then before: @martinbudden(Martin), @fishpepper(Simon), @ledvinap(Peter), @McGiverGim(Miguel Angel), @DanNixon(Dan), @mikeller(Michael) , 

Thanks

### CODE REVIEW

**Comment by digitalentity** [comment]
@fiam can you have a look at this PR? I'd like to get it into 1.8 as well. Looks like it doesn't touch much except RCSplit support.

**Comment by fiam** [comment]
@digitalentity Sure, will look at it later today.

**Review by fiam — APPROVED** [review]
I'm just slightly concerned by the extra 60 bytes of BSS and the use a global variable as a guard in `cmsUpdate()`. However, I can address those issues once I have the hardware to do bench testing. This is good to go in 1.8.

**Comment by digitalentity** [comment]
Merged. Will go to 1.8. Thanks @azolyoung

**Comment by azolyoung** [comment]
Thanks for your works!

**Comment by OhmEye** [comment]
Quick question before I use a runcam micro swift 3, I skimmed the code but didn't notice anything preventing camera control while armed so I hope I just missed it. I'd just like to confirm that the runcam device stick commands only work while disarmed, there's no risk of the device menu popping up while actually flying, right? :) I haven't seen that explicitly mentioned anywhere.

**Pull request merged**
