### PR TITLE
[IMU] Use bell curve to  calculate accelerometer weight in IMU

### PR DESCRIPTION
**Pull request by digitalentity**
Usage of Bell curve instead of hard cut will help with horizon drift in some cases on multicopters.

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]
code LGTM, practical impact? Will have to test. maybe around weekend

**Comment by digitalentity** [comment]
Some AIO boards with VTX onboard suffer greatly from temperature-induced accelerometer drift.

Currently we only accept 25% off on acc^2, which gave IMU only around 12% tolerance to accelerometer zero point drift which caused severe horizon drift on those boards when accelerometer drifted beyond that threshold. This PR pushes sigma up to 33% and also accepts virtually any acceleration value with attenuated weight.

It may also make sense to enable `acc_ignore_rate` usage on multicopters. They are not aerodynamic, but rapid rotations introduce unwanted centrifugal forces if accelerometer chip is not exactly in the CoG of the UAV.

**Comment by avsaase** [comment]
What happens if the measured acceleration is less than 1G, for example when staring a dive? Looking at https://github.com/iNavFlight/inav/blob/3ad5d03dfafb983c0306a3910553efc180014173/src/main/common/maths.c#L505-L508 it seems that `sqrtf(accMagnitudeSq)` cannot be smaller than 1.

In general this PR leaves a lot of weight on the accelerometer even when G-forces are very high and thus likely not aligned with the gravity vector. Will that not make the horizon drift worse?

**Comment by digitalentity** [comment]
Setting `acc_ignore_rate` will effectively disable accelerometer when the aerodynamic forces on the airplane add in significant centrifugal force. This PR allows faster horizon recovery when entering a stable flight (especially when accelerometer have drifted and doesn't read exactly 1G when not accelerating - I noticed this happening with significant changes in ambient temperature)

**Comment by avsaase** [comment]
Slow (or complete lack of) horizon drift recovery is exactly why I am looking into this. I attributed this to a too low setting of `acc_ignore_rate` in turbulent conditions so that the accelerometer is never trusted, but maybe it was accelerometer drift instead. I was going to experiment with smaller `curveWidth` and higher `acc_ignore_rate` settings and see if that is more robust. If it is I'll open a PR that makes `curveWidth` configurable via the CLI.

**Comment by avsaase** [comment]
If accelerometer readings drift due to temperature changes, wouldn't it be better to detrend the accelerometer with something like an HP filter? 

The reason I ask is that I think it makes a lot more sense to do accelerometer invalidation based on measured G-forces than based on rotation rates, especially on fixed wing aircraft. With airplanes we rarely accelerate straight up of down so any reading too far from 1G means there have to be some centrifugal forces. Rotation around the roll axis on the other hand does not generate centrifugal forces (assuming the fc is exactly on the axis of rotation), so it seems unnecessary to invalidate the accelerometer based on such rotation.

**Comment by digitalentity** [comment]
> If accelerometer readings drift due to temperature changes, wouldn't it be better to detrend the accelerometer with something like a HP filter?

Pull requests to improve the logic are welcome :smiley: 

> The reason I ask is that I think it makes a lot more sense to do accelerometer invalidation based on measured G-forces than based on rotation rates.

You can't trust the acceleration in a turn - that's the point. Doing a banked turn with descending at the same time is very likely to yield exactly 1G or very close to it. The rotation rate is the only thing that would indicate presence of centrifugal forces. Just 0.17G of lateral acceleration (1.015G total acceleration) is already a 10deg banking which is a lot.

> Rotation around the roll axis on the other hand does not generate centrifugal forces (assuming the fc is exactly on the axis of rotation)

This is a fair point, however we don't experience roll rotation for prolonged periods that often anyway. During a turn we usually experience a mix of yaw and pitch rotation.

**Comment by avsaase** [comment]
Sorry, I thought I had a clever idea to help further mitigate this issue, but it's not going to work unfortunately. I didn't realize that 10 degree bank angles create this little lateral acceleration. This makes invalidating the accelerometer based on G-forces is basically useless because you have to set very tight thresholds around 1G, but then you basically always invalidate the accelerometer if there is turbulence or the accelerometer is a little off.

I'm afraid any mitigation of this type will always be a balancing act between not trusting the accelerometer when we should, and trusting the accelerometer when we shouldn't.

**Pull request merged**
