### PR TITLE
Support WP LAND

### PR DESCRIPTION
**Pull request by stronnag**
Initial cut, tested on FW. Don't merge until PH TIMED is merged.

### CODE REVIEW

**Comment by stronnag** [comment]
Addresses #5467

**Comment by stronnag** [comment]
requires retesting on FW and testing on MR

**Comment by FabianSchwartau** [comment]
I guess I need the current mwp for that? Maybe I can test that in a few minutes on my MR.

**Comment by stronnag** [comment]
> I guess I need the current mwp for that? Maybe I can test that in a few minutes on my MR.

Yes, needs latest dev mwp to upload JUMP to iNav FCs. Thanks for the test offer, you might try PH TIME and JUMP (if you have time), see if I got the merge right.

**Comment by FabianSchwartau** [comment]
Is there anything else strange in the current development branch? My drone is heavily overshooting/oscillating in gps hold. Basically beyond control.

**Comment by stronnag** [comment]
There's been a load of filter stuff, but nothing else significant in NAV; LAND doesn't touch PH.

**Comment by FabianSchwartau** [comment]
yeah, but I also updated to the current dev from a week ago or so. So there is some change that makes that... any quick adive while I am still in the field?

**Comment by stronnag** [comment]
Alot can happen in a week. Nothing more to advise.

**Comment by FabianSchwartau** [comment]
OK, could not figure it out. It's getting dark. Will test that again in a few days maybe.

**Comment by stronnag** [comment]
Tested 2020-03-20 on FW and MR. Note that #5449 does NOT fix navigation modes; all nav modes (WP, PH, RTH etc) are affected by severe oscillations.

**Comment by FabianSchwartau** [comment]
Ohh ok, so this is a known issue (by now)? Have not had time to test this further due to weather and other obvious problems in the world...
However, what I just saw I forgot to mention: The landing WP worked for me basically, just very shaky.

**Comment by stronnag** [comment]
I'll create a new PR with sample BBL for the shaky nav modes, once I've merged the CLI updates for wp p2,p3 and pushed a new multi-jump (embedded, re-entrant, saving properly JUMPs) PR

**Comment by FabianSchwartau** [comment]
BBL?

**Comment by stronnag** [comment]
> BBL?

BlackBox Log

**Comment by peteoz** [comment]
once iNav 2.5 RC is released, would all these new navigation modes be available (POSHOLD_TIME, JUMP, LAND) ?

it seems the issue that was holding back everything was fixed https://github.com/iNavFlight/inav/issues/5516

**Comment by stronnag** [comment]
> once iNav 2.5 RC is released, would all these new navigation modes be available (POSHOLD_TIME, JUMP, LAND) ?
> 
> it seems the issue that was holding back everything was fixed #5516

The dev branch currently supports all these modes (#5516) was fixed a while ago, so the imminent RC will also provide these functions.

**Pull request merged**
