### PR TITLE
Full Smartaudio 2.1 and VTX tables support, Port from Betaflight

### PR DESCRIPTION
**Pull request by Scavanger**
The goal was Smartaudio 2.1 support, but this only make sense with vtx tables.
VTX tables affects all supported vtx.

See betaflight wiki for details. https://github.com/betaflight/betaflight/wiki/VTX-tables

Tested with:
- TBS Unify PRO32 HV (Smartaudio 2.1)
- TBS Unify Pro 5G8 HV Race (Smartaudio 2.0)
- IRC Tramp
- Furious FPV Stealth Long Range 2.4 Ghz
 
Relevant issues:
#5037 
#4855

### CODE REVIEW

**Comment by DzikuVx** [comment]
@Scavanger is there any chance you could separate somehow SA2.1 from vtxtable ? Even if SA2.1 would have to be set by a CLI switch or something

**Comment by Scavanger** [comment]
@DzikuVx You don't like VTX tables? ;) 
This would be hard, SA 2.1 in betaflight is heavenly linked with vtx tabels, especially the power values, almost every smartaudio device das different power values.

**Comment by Jetrell** [comment]
@Scavanger Thanks for this work. This will be much appreciated for us SA2.1 user.  
 I noticed that you integrated - `ADJUSTMENT_VTX_POWER_LEVEL`. Has it been tested? I would hate to lose it with this addition :-( 
 Its one of the things that the BF devs didn't want to implement. But its a great addition, with its Global Function.

@DzikuVx I understand your concerns with the tables. I too thought the same when they were first added to BF. But now find the tables more versatile.
The initial problem occurred in BF, because users didn't know where to find the tables for the Nighty firmware,  to past them into the CLI.  
So as long as iNav provides these tables, all should be fine.

**Comment by digitalentity** [comment]
@Scavanger thanks for putting this all together!

I'm all in for SA2.1, but VTX tables need further discussion. Can you fork out just SA2.1 part so we can get it merged ASAP?

**Comment by Scavanger** [comment]
OK.
I will fork the SA 2.1 part out.

But since SA 2.1 works with individual dB power settings instead of a fixed index, we need to let the user sets the power levels.

I suggest a CLI command like:

sa21_power

Example for TBS Unify 32 pro:
sa21_power levels 4
sa21_power values 14 20 26 30
sa21_power labels 25 100 400 1W

**Comment by digitalentity** [comment]
No need to overcomplicate things. I suggest we reuse a hardcoded SmartAudio table here https://github.com/iNavFlight/inav/blob/master/src/main/io/vtx_smartaudio.c#L114-L119

**Comment by Scavanger** [comment]
Unfortunately hardcoded tabels will not work for 2.1. The dBi values are send directly to the vtx (Smartaudio 2.0 sends only an index) , and every VTX has individuall settings.

For example this are the values in dBi for TBS Unify pro 32:
14 20 26 30

TBS Unify Evo:
14 20 26 29

**Comment by digitalentity** [comment]
How do we figure out those values? Does the VTX report them back?
What does the VTX do if we send a value that VTX doesn't support?

**Comment by Scavanger** [comment]
Yes, the VTX can send the supported power values in dBi.
When you send the wrong value, the vtx won't change the power setting. 

I think it's possible to implement an "auto config" feature, and the power level settings are stored in the config to avoid unnecessary queries.
Makes it sense to set optional power labels by the user, like 25 100..., instead of the values in dBi or the index?

**Comment by digitalentity** [comment]
If SA2.1 device will report it's power levels back - we should be able to detect that at run-time, stick with power levels in the config and generate labels on the fly. That would be more user-friendly than having to define the VTX config manually (especially when the docs for VTX are obscure or missing)

**Comment by digitalentity** [comment]
I've started working on protocol-agnostic VTX settings, might get it done in a week if I'm lucky. Then the UI-related stuff would be up to the VTX  driver to decide and SA2.1 will come in quite handy to fill the data with real values.

**Comment by digitalentity** [comment]
@Scavanger PTAL at #5461

CMS/OSD now doesn't care about actual power levels, VTX driver can generate capabilities at run time and populate them with data it got from the VTX to display accurate information in the OSD

It's still old SA driver, no full SA2.1 support

**Comment by peteoz** [comment]
ok, I just came across a weird issue today on UNIFY PRO32 NANO where I'm unable to set full power via SmartAudio. power levels 1&2 (25mW and 100mW) work OK but power level 3 (400mW) won't stick, changing channels via SA works fine.
this VTx has only 3 power levels (25, 100 & 400mW) so I'm wondering if this is same issue or something else.
I understand on VTXs with 5 power levels we may not be able to get the last power level, but why on VTX with only 3 power levels we can use the max power ?
is this related issue ?

**Comment by wx4cb** [comment]
is the unify evo in this list? i have SA enabled in the flight controller and when i go to the stats tab in the osd i can see data there, but i'm assuming that this would be the reason why i can't change channels etc? if not, "help" :D

**Comment by DzikuVx** [comment]
@Scavanger do you think you could implement the missing bits for SA2.1? We need power levels for SA2.1 right? I hope with the changes did by @digitalentity it should be simpler than before

**Comment by Scavanger** [comment]
@DzikuVx Yes! #5713

**Comment by lossUAVes** [comment]
I have problems with Rush Tiny Tank Vtx.
There is a .json archive with vtx tables.

{
    "description": "Betaflight VTX Config file",
    "version": "1.0",
    "vtx_table": {
        "bands_list": [
            {
                "name": "BAND_A  ",
                "letter": "A",
                "is_factory_band": true,
                "frequencies": [
                    5865,
                    5845,
                    5825,
                    5805,
                    5785,
                    5765,
                    5745,
                    5725
                ]
            },
            {
                "name": "BAND_B  ",
                "letter": "B",
                "is_factory_band": true,
                "frequencies": [
                    5733,
                    5752,
                    5771,
                    5790,
                    5999,
                    5828,
                    5847,
                    5866
                ]
            },
            {
                "name": "BAND_E  ",
                "letter": "E",
                "is_factory_band": true,
                "frequencies": [
                    5705,
                    5685,
                    5665,
                    5645,
                    5885,
                    5905,
                    5925,
                    5945
                ]
            },
            {
                "name": "AIRWAVE ",
                "letter": "F",
                "is_factory_band": true,
                "frequencies": [
                    5740,
                    5760,
                    5780,
                    5800,
                    5820,
                    5840,
                    5860,
                    5880
                ]
            },
            {
                "name": "RACEBAND",
                "letter": "R",
                "is_factory_band": true,
                "frequencies": [
                    5658,
                    5695,
                    5732,
                    5769,
                    5806,
                    5843,
                    5880,
                    5917
                ]
            },
            {
                "name": "LOWRACE ",
                "letter": "L",
                "is_factory_band": true,
                "frequencies": [
                    5362,
                    5399,
                    5436,
                    5473,
                    5510,
                    5547,
                    5584,
                    5621
                ]
            }
        ],
        "powerlevels_list": [
            {
                "value": 0,
                "label": "25 "
            },
            {
                "value": 1,
                "label": "100"
            },
            {
                "value": 2,
                "label": "200"
            },
            {
                "value": 3,
                "label": "MAX"
            }
        ]
    }
}

**Comment by DzikuVx** [comment]
I think we can close this one. Thanks @Scavanger for the effort

**Pull request closed without merging**
