### PR TITLE
System message variable display time + setting option

### LINKED ISSUE #6725: System Message display time option ?
Wondering if there's interest in an option to set the System Message cycle display time. Currently this is fixed at 1 second which seems a bit short if several messages are popping up. Option would allow up to 5s perhaps.

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/6725.

Provides setting for system message display time when multiple messages present. Also incrementally increases message display time for messages longer than 15 characters. Will double display time for messages 30 characters long. Variable time only works when armed.

### CODE REVIEW

**Comment by breadoven** [comment]
Tested in flight and works as expected. With a 25 character message as the longest message being displayed a setting time of 1000ms was increased to 1666ms.

**Comment by avsaase** [comment]
What is the display time of the shortest message?

**Comment by breadoven** [comment]
The display time for all messages, regardless of length, increases when one of the messages is > 15 characters. If no message is > 15 characters then display time is fixed at the setting display time (default 1000ms, same as current time). The setting has a minimum limit of 500ms. This change doesn't vary the display time per message as was suggested in the linked Issue simply because it's not easy to do given the way the message cycling is set up overall, So this is a compromise solution.

**Comment by Jetrell** [comment]
@breadoven @DzikuVx  Any chance of this being merged? Given the ever increasing number of System Messages and their length, with little time to read and comprehend what just flashed before our eyes.

**Comment by breadoven** [comment]
Didn't think there was that much interest in this given it's a compromise and maybe not much of an issue for most people anyway. Still it does work so could be merged once updated to fix the conflicts.

**Review by DzikuVx — APPROVED** [review]

**Pull request merged**
