### PR TITLE
Failsafe system rework (Stage 1)

### PR DESCRIPTION
**Pull request by digitalentity**
This is a stage 1 of refactoring failsafe system. I believe we can have it in 1.6 as it's mostly about removing *Failsafe Stage 1*.

- [x] Deprecate `FEATURE_FAILSAFE`; Make failsafe system always active
- [x] Deprecate and remove `rxfail`; This now defaults to RPY center; T hold, AUX hold
- [ ] Create different channel behaviors on signal loss (depending on flight mode). Is this necessary?
- [x] Create a `NO ACTION` failsafe procedure to keep flying on failsafe
- [x] Make sure `RTH` failsafe procedure enforces ANGLE even if RTH didn't engage
- [x] Add a fixed wing LAND procedure

### CODE REVIEW

**Comment by digitalentity** [comment]
This makes quite a bit of a change to failsafe handling. It needs to be carefully tested.

**Comment by rb1205** [comment]
So this mean that, in the case of a RC link loss, failsafe stage 2 kicks immediately in, even for a blackout of a second or so?

**Comment by digitalentity** [comment]
@rb1205 no. Failsafe timeout still applies. This PR makes failsafe more user-friendly by removing configurable pre-Stage2 behavior. Now the term `failsafe` will only be applicable to actual procedure of handling lengthy RC loss.

**Comment by rb1205** [comment]
So a non-configurable, universal pre-failsafe procedure? With a configurable timeout to switch to the "real" failsafe I guess? Sounds good, but it has to be smart to account for all the different configurations and scenarios, and be failure resistant.  Some things that come to my mind:

- Engage AltHold if valid altitude sensor is available, else either apply nav_mc_hover_thr/nav_fw_cruise_thr or hold last good throttle.
- If engaging AltHold be aware of nav_use_midthr_for_althold
- For multicopters: engage PosHold if GPS and compass are available, calibrated and with a good GPS fix, else engage level mode if accelerometers are available, else go straight to failsafe (and crash, I guess)
- Go straight to failsafe if pre-failsafe has been triggered more than x times in y seconds (to protect against twitchy RC link or hw failure that make the signal comes back every seconds or so for for an instant preventing the actual failsafe from kicking in)
- Consider activating blackbox if it wasn't, for debugging purposes.
- Add beep and led indicator for this condition

**Comment by digitalentity** [comment]
It seems people want failsafe which is very simple to configure. Current system is flexible but over-complicated, this is going to something much much simpler. We'll probably lose some flexibility on the way...

**Comment by rb1205** [comment]
I think there's a reason if stage 1 was introduced in the first place... When flying "sporty" it's really critical to get things done right and quick when the RC link goes out, or else you get crashes/flyaways. If that's the route we're going to, then make at least the timeout configurable so it can be set to 0 for those who want to minimize the time passed without guidance.

**Comment by digitalentity** [comment]
The reason Stage 1 was introduced is to be able to set channels to certain values between rx loss and stage 2 kicking in - nothing more. Also, IIRC, initial timeout for stage 1 was ridiculously large - something about 1 second.

Please bear in mind that this PR is one of many that will completely reshape the failsafe system.

**Comment by rb1205** [comment]
OK, I'll wait to see and try the final version then 😃 

Thanks for your work!

**Comment by digitalentity** [comment]
Pre-failsafe procedure is short - 500ms by default. It should be dumb enough to be bullet-proof. Center RPY and hold Throttle is the safest thing. Machine might be able to fly through the signall loss and recover control. In such case there won't be (much) change in drone speed and altitude which is good from pilot's perspective.

If rx loss is longer than that - failsafe procedure will kick in and take over.

**Comment by martinbudden** [comment]
@digitalentity , I think we should have two options for pre-failsafe:

1. Center RPY and hold throttle (as you suggest)
2. Hold RPY and hold throttle. For short glitches the aircraft just keeps doing what it was doing. Pilots would probably want to set delay a bit lower (200ms, say) if using this option.

Option 2 is more applicable to racing/freestyle, but I don't think we should do anything to exclude race/freestyle pilots from using iNav.

**Comment by digitalentity** [comment]
@martinbudden agreed. I'm starting on phase 2 of refactoring - no change in logic, just code rearrangements for better modularity.

**Comment by oleost** [comment]
https://github.com/iNavFlight/inav/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20failsafe%20

Lots of failsafe related issues or feature request that could probably get merged together or looked at the same time

**Comment by digitalentity** [comment]
@oleost I've closed some. At the moment my goal is to make failsafe system easy to understand (code-wise). After this cleanup happens we can look at extending it.

**Pull request merged**
