### PR TITLE
OLED Display status page

### PR DESCRIPTION
**Pull request by DzikuVx**
CF inherited OLED Display support had a flaw that was making its real life usage very hard: it was trying to display all available data. Even data that has little usage in real life. Do I really need raw gyro? Or RX sticks position? If there was something useful like MAG heading or battery level, it was cycling every 5 seconds and you would have to wait another 20 or 30 seconds to see it again.

This is why I got rid of most of the display pages and combined useful data into one screen that stays on all the time UAV is not armed. It shows:
- RX status (channel width within borders)
- Battery voltage if available
- Remaining battery current is current monitoring available
- GPS status: 
  - Number of sats
  - Fix: No/2D/3D
  - HDOP
  - Lat/Lon
- Heading if MAG available
- Altitude (relative) if BARO available

Additional benefit is that code running OLED display has been reduced in size by approx. 800 bytes. 

Since it depends on `gpsSol.hdop` has to be merged into `gps-remove-svinfo` or into `master` after dependency has been merged there (#84).

New display page looks like this:
display

### CODE REVIEW

**Comment by DzikuVx** [comment]
@digitalentity please edit this pull request to point to 'gps-remove-svinfo' not master. My bad

**Comment by digitalentity** [comment]
@DzikuVx 
Thanks! Thanks! Thank you so much!!!
The crappy multi-page OLED was bugging me for ages but I never got the time to clean it up!

**Comment by digitalentity** [comment]
Do you think it's possible to include https://github.com/cleanflight/cleanflight/pull/1294 as well? And make it configurable per-target? This way on a F3-based boards we can have some more eye-candy.

**Comment by DzikuVx** [comment]
Everything is possible :) I will take a look at that, but can not promise any timeframe. If success, I will make a new pull request

**Comment by digitalentity** [comment]
Great! I'll pull this to a separate branch, rebase on master and merge along with gps-remove-svinfo.

**Comment by digitalentity** [comment]
Ok, I did the same mistake :smile: 
See #127 for properly based PR.

**Comment by digitalentity** [comment]
I'm going to modify the PR, cleanup it further and remove page cycling code alltogether.

**Pull request closed without merging**
