### PR TITLE
Move PG copy into PG macros

### PR DESCRIPTION
**Pull request by martinbudden**
Saves 960 bytes of ROM on CC3D.

### CODE REVIEW

**Comment by digitalentity** [comment]
Wow! @martinbudden why did you keep this ace up your sleeve?

**Comment by martinbudden** [comment]
Actually, I can't claim credit. @hydra made this change in betaflight. As soon as I saw it, I realised that was how I should have done it in the first place. But sometimes when writing code you get going down one path and don't see the better paths...

Anyway, have only just now had a bit of time to move it over to iNav.

**Comment by giacomo892** [comment]
With this we can remove all the defines @DzikuVx is putting in https://github.com/iNavFlight/inav/pull/1732 since we save a lot of space here and having FW landing on F1 :) Kudos @martinbudden

**Comment by stronnag** [comment]
I flashed development + this diff on SP-EVO. Restored prior diff. Seems to  have been applied in the configurator.

**However** `diff` or `dump` just locks up the FC. `get` works. I maybe won't fly this just yet.
btw `diff` and `dump` work in βF.

**Comment by martinbudden** [comment]
@stronnag , code updated.

**Comment by martinbudden** [comment]
@digitalentity , if you are short of ROM for 1.7.1 , I'm now reasonably confident about this PR.

**Comment by hydra** [comment]
Yeah, this change gives a really good flash saving result and you have less code to maintain too.  +1 for merging this ASAP.

**Comment by digitalentity** [comment]
@martinbudden @hydra agreed. Merging!

**Comment by stronnag** [comment]
There is an issue with the restoration of profies. I have profile 1 as non-default, 2 and 3 are default.
If I configure with:

````
defaults noreboot
...


# profile
profile 1

set mc_p_pitch = 110
set mc_i_pitch = 20
set mc_d_pitch = 52
set mc_p_roll = 110
set mc_i_roll = 20
set mc_d_roll = 52
set mc_p_yaw = 75
set mc_i_yaw = 20
set mc_p_level = 12
set dterm_notch_hz = 125
set dterm_notch_cutoff = 90
set rate_accel_limit_yaw = 200
set roll_rate = 55
set pitch_rate = 48

# save configuration
save
````
then a subsequent `diff` (note I didn't set profiles 2 and 3).
````
# profile
profile 1

set mc_p_pitch = 110
set mc_i_pitch = 20
set mc_d_pitch = 52
set mc_p_roll = 110
set mc_i_roll = 20
set mc_d_roll = 52
set mc_p_yaw = 75
set mc_i_yaw = 20
set mc_p_level = 12
set dterm_notch_hz = 125
set dterm_notch_cutoff = 90
set rate_accel_limit_yaw = 200
set roll_rate = 55
set pitch_rate = 48

# profile
profile 2

set mc_p_pitch = 110
set mc_i_pitch = 20
set mc_d_pitch = 52
set mc_p_roll = 110
set mc_i_roll = 20
set mc_d_roll = 52
set mc_p_yaw = 75
set mc_i_yaw = 20
set mc_p_level = 12
set dterm_notch_hz = 125
set dterm_notch_cutoff = 90
set rate_accel_limit_yaw = 200

# profile
profile 3

set mc_p_pitch = 110
set mc_i_pitch = 20
set mc_d_pitch = 52
set mc_p_roll = 110
set mc_i_roll = 20
set mc_d_roll = 52
set mc_p_yaw = 75
set mc_i_yaw = 20
set mc_p_level = 12
set dterm_notch_hz = 125
set dterm_notch_cutoff = 90
set rate_accel_limit_yaw = 200

# restore original profile selection
profile 1
````

**Pull request merged**
