### PR TITLE
Add a BF4.3 Compatible restricted OSD implementation.

### PR DESCRIPTION
**Pull request by mmosca**
Add an OSD mode that would do a best effort to map INAV characters to BF characters.
If a character is not supported by BF4.3, it will be replaced by a question mark '?'.

This should provide a better user experience than random characters on screen when the VRX only supports BF (dji) while making it clear what is missing.

Impact on flash space was fairly small (0.04% difference on initial build)

This has been confirmed to work on different combinations of O3, G2, V2 and Vista/AU running O3 firmware.

Functionality can also be tested with rooted AU/Vista + Googles V2 by replacing the INAV font used by fpv.wtf with the BetaFlight font. 

Compatibility mode can be enabled on the CLI by:
set osd_video_system = BF43COMPAT

There is also a pull request (iNavFlight/inav-configurator#1671) for the configurator to allowing it to be setup as a normal MSP OSD device and selecting BF43COMPAT video format on the OSD tab.

### CODE REVIEW

**Comment by DzikuVx** [comment]
Ah, @mmosca just read your comment. Please add a heartbeat in this PR so we have one PR that resolves the O3 compat

**Comment by roroid** [comment]
@mmosca Yep...you are the man that INAV needs.:-)
A big thank you from my side.
IMG_1570
IMG_1572

**Comment by mmosca** [comment]
@roroid What hardware did you use? O3 unit? G2 googles?

**Comment by roroid** [comment]
> @roroid What hardware did you use? O3 unit? G2 googles?

o3 and rooted google v2.
to start the osd, i needed to go to osd configurator and then the magic happened :)

**Comment by MadRC** [comment]
I can test this on any thing that needs it

**Comment by roroid** [comment]
@mmosca i downloaded your branch directly about 40min ago. It's having also that commit.

**Comment by mmosca** [comment]
Given we have confirmation of both Googles 2 and O3 and Vista running the "O3" firmware working, I think we can at least consider this as a working implementation.

I did not need to spoof the fc type to get it to work and it should be simple to add more character maps.

@MrD-RC , maybe you can have a look and make sure my mapping is complete enough.

The configurator changes are also ready.

**Comment by shannonbaker** [comment]
The decimal place number glyphs that are used by INAV (to conserve OSD real estate) are why you are seeing the [?] used. Effectively a single glyph with built in [half] decimal point will need to be broken out into 2 distinct glyphs, the number and a decimal point, noting it will need to accommodate a pre and post decimal point logic. The pic shows what this looks like in INAV (and ARDU) from the font file. Betaflight does not display numbers with decimal places this way, with a decimal place occupying it's own cell spacing.
319811630_1505678469943898_5443152772591055213_n

**Comment by mmosca** [comment]
> The decimal place number glyphs that are used by INAV (to conserve OSD real estate) are why you are seeing the [?] used for numbers with decimal places. Effectively a single glyph with built in [half] decimal point will need to be broken out into 2 distinct glyphs, the number and a decimal point, noting it will need to accommodate a pre and post decimal point logic. The pic shows what this looks like in INAV (and ARDU) from the font file. Betaflight does not display numbers with decimal places this way, with a decimal place occupying it's own cell spacing.

Good catch, I will have a look at this one but I don't see an easy way to fix this with the simple mapping strategy used here.

Mapping those characters to the numbers without the decimal point would be confusing. 
And changing the formatting to use 3 glyphs requires changes to the formatting of the OSD items. (And expanding the glyphs at the last second is very likely to introduce osd visual breaking bugs)

I may be able to look into the formatting early next year, but I hope this gets the ball rolling.

**Comment by mmosca** [comment]
@shannonbaker  I gave it a shot. I don't think it is perfect. Needs more testing

**Comment by OlivierC-FR** [comment]
Awesome work, progress yay! :)

**Comment by mmosca** [comment]
> 
> 
> Awesome work, progress yay! :)

Olivier, what hardware did you use?
O3 + googles2, or O3 + googles V2 ?

I am trying to keep track of the tested scenarios.

**Comment by mmosca** [comment]
@DzikuVx can you approve the workflows again? I have updated the documentation, so it should go green next time it runs.

**Comment by mmosca** [comment]
@DzikuVx I added an extra documentation file to hopefully provide a place we can direct questions about fixing DJI's code or what the limitations of this change are.

Can you have a look and provide feedback if the tone/message contained is ok?

Otherwise, I consider this functionality complete. If new mappings are suggested we can either include in the PR if it has not been merged, or easily open another one.

**Comment by OlivierC-FR** [comment]
> Olivier, what hardware did you use? O3 + googles2, or O3 + googles V2 ?

O3, V2, Matek F722SE

**Comment by erstec** [comment]
@mmosca thank you for contribution!

To keep code constant readable, let me be little bit "C style grammar nazi" for this time :)

It would be very nice if you consider to format your code.
What I noticed: if/while etc. should be followed by space, curly brace on same line for everything except function definitions and etc.

It's not about right and wrong, but more about being consisten witth surrounded code.

https://github.com/iNavFlight/inav/blob/master/docs/development/Development.md
Docs states this is K&R Style, but I see it more like Google one, whatever.

And, thank you again!

**Comment by mmosca** [comment]
> @mmosca thank you for contribution!
> 
> To keep code constant readable, let me be little bit "C style grammar nazi" for this time :)
> 
> It would be very nice if you consider to format your code. What I noticed: if/while etc. should be followed by space, curly brace on same line for everything except function definitions and etc.
> 
> It's not about right and wrong, but more about being consisten witth surrounded code.
> 
> https://github.com/iNavFlight/inav/blob/master/docs/development/Development.md Docs states this is K&R Style, but I see it more like Google one, whatever.
> 
> And, thank you again!

I believe it is done now. 

I fixed the curly braces in my changes (and a bonus one) and renamed the mapping function to match the style as well.

**Comment by shannonbaker** [comment]
> Shouldn't it be mi/h? Metric symbol for mile is "mi". Now it's a bit weird:
> 
> mph -> mile per hour mp/h -> mile per per hour ;)
> 
> If we express imperial speed in metric way (with "/" for per) IMHO we should skip the "p" for "per".
> 
> image

I think you'll find a number of inconsistencies when you compare BF font set to DJI font set...

**Comment by mmosca** [comment]
> Shouldn't it be mi/h? Metric symbol for mile is "mi". Now it's a bit weird:
> 
> mph -> mile per hour mp/h -> mile per per hour ;)
> 
> If we express imperial speed in metric way (with "/" for per) IMHO we should skip the "p" for "per".
> 
> image

Unfortunately, the font is on DJI's side and we can't change it. (If we could, we probably wouldn't need most of the code in this pull request)

**Comment by robertrypula** [comment]
@shannonbaker Yeah true. At least "km/h" is correct ;) For some reason "kph" kills my eyes. This is sooo non metric ;)

**Comment by mmosca** [comment]
For completeness and to get it docummented in a place that is easier to find than discord. :)

According to SNEAKY_FPV, on fpv.wtf discord, there are problems in DJI's font even with BF:

"I also note the following differences between standard BF and G2.  Pink circles from left to right should be displaying: Speed symbol, distance travelled, [blank]?, KM, MI.   DJI in their 'infinite wisdom'..... have replaced them as below.  So even BF is messed up on G2 when as user wants to show any of the pink elements. "
dji_bf_font_issues

**Comment by MrD-RC** [comment]
> Shouldn't it be mi/h? Metric symbol for mile is "mi". Now it's a bit weird:
> 
> 
> 
> mph -> mile per hour
> 
> mp/h -> mile per per hour ;)
> 
> 
> 
> If we express imperial speed in metric way (with "/" for per) IMHO we should skip the "p" for "per".
> 
> 
> 
> image
> 
> 

No, because the metric standard does not define the symbols for imperial measurement. 

Miles per hour always is, and will be, mph. Nowhere that uses miles per hour writes is at Mi/h. If any changes were to happen, it would just be to remove the **/**, as you are right in that it is not necessary.

**Comment by robertrypula** [comment]
> Just stick to your kph, and all is well 😉

@MrD-RC Eye killer! :D
Yep, you are right with miles per hour. The **only** correct way is to always write it as "mph". I just expressed myself wrong in my first post - if they picked the the version with "/" they should use mi/h but in general it's wrong anyway. It should be **mph** (not mi/h, not mp/h). So to summarize if DJI is listening (I bet not) the only correct way to display speed is:

- km/h 
- mph

**Comment by DzikuVx** [comment]
@mmosca @MrD-RC are we ready with the changes? I see @mmosca that you say you done but I'd love to get a confirmation on that.
If yes, let's merge it !

**Review by DzikuVx — APPROVED** [review]

**Comment by OlivierC-FR** [comment]
> @mmosca @MrD-RC are we ready with the changes? I see @mmosca that you say you done but I'd love to get a confirmation on that. If yes, let's merge it !

As is it does not work, theres issues with chars and numbers and this dam dot splitting. Unless we're we're talking about extra code/fix from elsewhere or to come ?

**Comment by mmosca** [comment]
> > @mmosca @MrD-RC are we ready with the changes? I see @mmosca that you say you done but I'd love to get a confirmation on that. If yes, let's merge it !
> 
> As is it does not work, theres issues with chars and numbers and this dam dot splitting. Unless we're we're talking about extra code/fix from elsewhere or to come ?

@DzikuVx I am ready to merge.
@OlivierC-FR I have addressed the decimal dot issue. The changes were in the formatting side of things. We just don't use the split decimal when writing decimal numbers in BF43COMPAT mode.

**Comment by DzikuVx** [comment]
In that case awesome! Thanks a lot @mmosca

**Comment by OlivierC-FR** [comment]
> @OlivierC-FR I have addressed the decimal dot issue. The changes were in the formatting side of things. We just don't use the split decimal when writing decimal numbers in BF43COMPAT mode.
Ok my bad, apologises, I didn't see the last commit, great job ! Flashing right now

**Comment by OlivierC-FR** [comment]
> > > @mmosca  I have addressed the decimal dot issue. The changes were in the formatting side of things. We just don't use the split decimal when writing decimal numbers in BF43COMPAT mode.
Ok my bad, apologises, I didn't see the last commit, great job ! Flashing right now

**Comment by llambkin** [comment]
Flashed this last night, and got something to show on the OSD :) waiting patiently for improved character mapping 👍

**Comment by mmosca** [comment]
> Flashed this last night, and got something to show on the OSD :) waiting patiently for improved character mapping 👍

We are limited by whatever characters are available on the DJI side, so not much more we can do.

If I did miss any characters in the mapping, just open an issue with what INAV character should be mapped to what BF character and I will try to address it as quickly as possible. 

You can also try to flash #8634 as there were some changes to make sure we display full voltage digits and should be closer to what the final INAV 6.0 will look like.

**Comment by llambkin** [comment]
Thanks Marcelo,

I downloaded my hex directly from here: http://seyrsnys.myzen.co.uk/inav_dev/ <http://seyrsnys.myzen.co.uk/inav_dev/> which was from the 16th of Dec as I don’t have a build server setup. Are you able to send me a hex for a Mateksys H743.


-Liam Lambkin
Director
Rockett Technologies
M - 0423 039 331
F - www.facebook.com/rocketttech <http://www.facebook.com/rocketttech>

**Comment by mmosca** [comment]
> Thanks Marcelo, I downloaded my hex directly from here: http://seyrsnys.myzen.co.uk/inav_dev/ <http://seyrsnys.myzen.co.uk/inav_dev/> which was from the 16th of Dec as I don’t have a build server setup. Are you able to send me a hex for a Mateksys H743.

You can download that from the pull request checks.

Just go to
https://github.com/iNavFlight/inav/actions/runs/3720001999

and scroll down to artifacts. That zip file should have the firmware you are looking for.

**Comment by llambkin** [comment]
> > Thanks Marcelo, I downloaded my hex directly from here: http://seyrsnys.myzen.co.uk/inav_dev/ http://seyrsnys.myzen.co.uk/inav_dev/ which was from the 16th of Dec as I don’t have a build server setup. Are you able to send me a hex for a Mateksys H743.
> 
> You can download that from the pull request checks.
> 
> Just go to https://github.com/iNavFlight/inav/actions/runs/3720001999
> 
> and scroll down to artifacts. That zip file should have the firmware you are looking for.

Thankyou heaps Marcelo! I have flashed and the battery voltage now displays correctly :)

**Comment by llambkin** [comment]
Here is a video of what it looks like on Goggles 2. It seems the Kph and the throttle percent symbols are missing. No big deal, WAAAAY better than nothing. Thanks Marcelo :)
https://nextcloud.rockett-tech.com.au/s/cnYsdr6wqP9EqD5

**Comment by brousselle** [comment]
I also have a DVR i wanted to post, but yours also show the same issues: 
- the heading arrow to home point does not point in the right direction.
- the aircraft lipo voltage is at 0.0 V in the DJI OSD. It was displaying correctly with inav 5.
- I am not sure this is related to this, but i also noticed that i do not have anymore the GPS sats, lat, lon in the telemetry data back to my tango2 (do you also have the same issue ? )

Thanks Marcello for your work ! glad this is happening.

**Comment by MrD-RC** [comment]
I noticed the arrows on the BetaFlight font go the other way to INAV. If you check out the arrow changes in osd_symbols.h around line 325 in this branch (https://github.com/iNavFlight/inav/compare/master...MrD_Add-defines-for-the-BF-OSD-charset). You'll see how I set them so that they would be correct for INAV.

**Comment by bonny002** [comment]
I configured the option (MSP Display and Betaflight Comp) and I see the OSD. When I reboot the FC, I see no OSD any more. Google V2 and Air Unit o3. Both latest firmware.

**Comment by brousselle** [comment]
I also noticed the same behavior, but i was wondering if it was a hardware problem on my side but not with the vista:
- Matek F405 WSE, Google 2, O3: i have to plug the battery first, and then in the CLI: set osd_video_system = BF43COMPAT
and save in order to have the OSD to display. (i triple checked that osd_video_system has not changed between each reboot).
unplug the lipo and plug a new one: osd is gone until you redo the cli command.

- Matek F405 WSE, google 2, caddx vista (latest firmware): OSD stays after each reboot. 

Please note i have tried the exact same "diff" setup on both planes.

**Comment by mmosca** [comment]
> I noticed the arrows on the BetaFlight font go the other way to INAV. If you check out the arrow changes in osd_symbols.h around line 325 in this branch ([master...MrD_Add-defines-for-the-BF-OSD-charset](https://github.com/iNavFlight/inav/compare/master...MrD_Add-defines-for-the-BF-OSD-charset)). You'll see how I set them so that they would be correct for INAV.

Mr-D, can you open an issue and tag me into it? I will be away for a few weeks but I can look into it as soon as I am back.

**Comment by mmosca** [comment]
> Here is a video of what it looks like on Goggles 2. It seems the Kph and the throttle percent symbols are missing. No big deal, WAAAAY better than nothing. Thanks Marcelo :)

I added a pull request to map it and a few others that are similar:

#8641

**Comment by mmosca** [comment]
> > I noticed the arrows on the BetaFlight font go the other way to INAV. If you check out the arrow changes in osd_symbols.h around line 325 in this branch ([master...MrD_Add-defines-for-the-BF-OSD-charset](https://github.com/iNavFlight/inav/compare/master...MrD_Add-defines-for-the-BF-OSD-charset)). You'll see how I set them so that they would be correct for INAV.
> 
> Mr-D, can you open an issue and tag me into it? I will be away for a few weeks but I can look into it as soon as I am back.

@MrD-RC  I have updated #8641 to include the arrow changes as well, but I won't be able to test it until early january.

**Comment by BlueFishUK** [comment]
I attach some test results based upon the nightly build of 04/01/2023, you can see the actual in flight behaviour in this video.

https://youtu.be/lem8YkYMeJ4 The flight footage of the OSD starts at 06:10

Thank you for the great work, I will be happy to assist with any testing or feedback

[DJI O3 Inav Betaflight OSD Compatibility Test.pdf](https://github.com/iNavFlight/inav/files/10366754/DJI.O3.Inav.Betaflight.OSD.Compatibility.Test.pdf)

**Comment by gabrielflow** [comment]
Hello. I have no gyro,accel,mag,baro,etc with this fw. Please anyone can help me? speedybee f7 v3
thank you
image

**Comment by MrD-RC** [comment]
> Hello. I have no gyro,accel,mag,baro,etc with this fw. Please anyone can help me? speedybee f7 v3
> 
> thank you
> 
> image
> 
> 

Please check on Discord for advice. This is likely a setup issue and not related to this PR. If you believe there is an issue, please create an issue specifically for your problem. Don't just tack issues on pull requests.

**Pull request merged**
