### PR TITLE
Get home position via MSP

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by stronnag** [comment]
Nice, can you please bump the MSP API version so we can test for API availability?

**Comment by stronnag** [comment]
```
%% fc_msp.c 
./src/main/fc/fc_msp.c: In function 'mspFcProcessOutCommand':
./src/main/fc/fc_msp.c:292:17: warning: unused variable 'home' [-Wunused-variable]
  292 |     fpVector3_t home;
      |                 ^~~~
```

**Comment by stronnag** [comment]
It would perhaps be more useful if this API followed the encoding of the LTM 'O' frame, which conventionally encodes the home data as lat,lon,alt. Reusing the LTM 'O' frame payload would also make life much easier for 3rd party tools that support both MSP and LTM (so we waste a byte with the useless OSD status ... but commonality trumps that).
```
    sbufWriteU32(dst, GPS_home.lat);
    sbufWriteU32(dst, GPS_home.lon);
    sbufWriteU32(dst, GPS_home.alt);
    sbufWriteU8(dst, 1);                 // OSD always ON
    sbufWriteU8(dst, STATE(GPS_FIX_HOME) ? 1 : 0);
```

**Comment by wx4cb** [comment]
couldn't you repurpose the "extra byte" for say whether this is the first arm or not? so a 1 for first arm, 0 for not.

as in the LTM frame the state is "always" true, then most software would probably just ignore that element anyway.

**Comment by DzikuVx** [comment]
@stronnag @wx4cb changes applied, how about now?

**Comment by stronnag** [comment]
I'm still confused by the positional information:
* Unless I'm doing something really stupid, it returns small, varying  integer values, I was expecting latitude, longitude as degs* 1E7 and alt in cm, as the other positional APIs (e.g. O frame above).

**Comment by digitalentity** [comment]
That's getting home position in [cm] in local coordinates.
For GPS home position you can fetch MSP_WP #0

**Comment by DzikuVx** [comment]
interesting, apparently no need for a new MSP frame :)

**Comment by digitalentity** [comment]
Yep, so this PR is not necessary :smile:

**Comment by DzikuVx** [comment]
then closing

**Pull request closed without merging**
