### PR TITLE
Bump navConfig PG that was forgotten in #9220

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by breadoven** [comment]
Is this required given it was 3 in 6.1.1 so has already been bumped to 4 for release 7.0 ?

**Comment by DzikuVx** [comment]
I have problem when flashing `master` builds. It's safer to update it every time

**Comment by DzikuVx** [comment]
Not required, just nice to have

**Comment by breadoven** [comment]
OK. I'm just remembering that you're limited to 32, or is it only 16, bumps before having to loop around to 0 again. I guess I always do a full chip erase when flashing so never have problems ... other than killing the flash more quickly perhaps.

**Comment by DzikuVx** [comment]
I would not worry about flash wear. It should last 10,000 cycles at least. And I still have the same development board from 2017 I think. No idea how many times I flashed it already

**Pull request merged**
