### PR TITLE
RPM filters

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested this today. Hangs randomly after booting on my OMNIBUSF4, not sure why.

**Comment by DzikuVx** [comment]
@digitalentity interesting. Tested on 2 different F7's and there were no problems even when ESCD were not providing telemetry.
Care to send a diff?

**Comment by digitalentity** [comment]
Default settings, flashing with full erase. First boot - it randomly hangs once in a while (about 1% of reboots). Digging deeper

**Comment by digitalentity** [comment]
Ok, I probably need a new debugging board. Can't reproduce the issue any more...

**Comment by whoim2** [comment]
If need, im may test rpm-filtering on f4

**Pull request merged**
