### PR TITLE
Initial port of support for multiple types of rangefinder to iNav - for review

### PR DESCRIPTION
**Pull request by martinbudden**
This is just an initial port for review. The cleanflight version works and is tested, but I haven't tested this on iNav. In particular there have been some changes in the sonar initialisation in cleanflight and this might cause a minor problem.

Anyway, let me know what you think, and if you like it I can spend some time testing it.

I've included the framework and the SRF10 rangefinder driver - this is included under a build flag.

I've built it for both NAZE and CC3D (although for CC3D I had to undefine some of the telemetry to get it to fit).

By the way, I've made some submissions to clean flight that have reduced ROM usage, and will make some more in future.

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden can you please rebase this against latest?

**Comment by martinbudden** [comment]
@digitalentity , rebased. Not sure if the PR got updated properly. Let me know if there are any problems.

Remember I've only tested this in Cleanflight, I haven't tested it in iNav, so there could be problems.

**Comment by digitalentity** [comment]
Thanks! Will test in a few days. Scheduling for 1.1 as 1.1 is going to have better sonar support.

**Comment by digitalentity** [comment]
Superseded by #149

**Pull request closed without merging**
