### PR TITLE
FlySky ibus telemetry

### PR DESCRIPTION
**Pull request by DzikuVx**
It is a port of cleanflight#1723 as requested in #253.
Since I have no FlySky devices ATM, no idea if it works. Should... 

Enabled on F3 targets, disabled on F1 targets

To enable use CLI

`serial 1 256 115200 57600 115200 115200`

Command above enables iBus Telemetry on UART2

### CODE REVIEW

**Comment by bk79** [comment]
@DzikuVx  if you can rebase it I can test on spf3 deluxe, spf3 revo and sparky

**Comment by DzikuVx** [comment]
@bk79 I will rebase but it will probably require some work since MAVLink has been added

**Comment by DzikuVx** [comment]
@bk79 rebased, enabled on target > 128kB of flash.
It compiles, no idea if works. ibus telemetry povider uses bit 9 so serial function `512` enables it

**Comment by bk79** [comment]
Thanks i'll test it today or tomorrow

Il 29/ago/2016 16:22, "Paweł Spychalski" notifications@github.com ha
scritto:

**Comment by bk79** [comment]
It compiles i'll try downloading to the board as soon as i can

Il 29/ago/2016 16:29, "luciano palermo" luciano.luca.palermo@gmail.com ha
scritto:

**Comment by bk79** [comment]
set it to 512 on serial 2 where I also have rxserial Ibus and it works but setting serialrx disable it and viceversa

**Comment by stronnag** [comment]
The values are a bit mask. Assuming you can have both active, set the value to the sum of the individual components (e.g. 512 + 64), 576.

**Comment by bk79** [comment]
Ok i'll test it again tomorrow but i guess it works if it's only that i'll
have a flight in the next days or at most in the weekend it's a pity we can
only read 3 values of which only voltage is usefullvfor multirotors..it
could be usefull to eventually switch temperature and rpm for altitude and
gps position by simply using those two channels with some other data

Il 29/ago/2016 22:47, "stronnag" notifications@github.com ha scritto:

**Comment by bk79** [comment]
@DzikuVx I had a look at code did you try using address higher than 3?

**Comment by DzikuVx** [comment]
@bk79 I'm not the author of it. I only ported code from Cleanflight I'm affraid.

**Comment by bk79** [comment]
@DzikuVx doesn't work on sparky flight 1.1 after recent fix, probably something wrong with uart2

**Comment by bk79** [comment]
On sparky 576 combination is not working when i save it goes back to 0, i
don't know if it related to the new fix Martin has done. Still have to test
on spf3

Il 03/set/2016 15:29, "Paweł Spychalski" notifications@github.com ha
scritto:

**Comment by bk79** [comment]
@DzikuVx  did you have the chance to have a look at the code? I'm unable to set any serial with both rx and tx on sparky, when setting 576 it sets back to 0 probably it's not allowed so far to enable both

**Comment by DzikuVx** [comment]
@bk79 Is it only SPARKY? I do not have either sparky or FlySky radio so my options are rather limited here.
Either way maybe tomrrow I will take a look

**Comment by bk79** [comment]
Actually yes i tried on spf3 and it works but not the serial rx+telemetry
ibus but that is something i've corrected already on telemetry.h you forgot
to add the allowed rx+telemetry mask  and so far only ltm and mavlink are
allowed. On sparky no matter what uart i select i have no output if select
any other telemetry it works..even if you don't have the flysky doesn"t
matter connecting a serial usb converter and opening the com port related
you should see transmission

Il 05/set/2016 19:46, "Paweł Spychalski" notifications@github.com ha
scritto:

**Comment by bk79** [comment]
Try rebasing again it will make it simpler for me to test again with the
ficx for sparky already on

Il 05/set/2016 21:33, "luciano palermo" luciano.luca.palermo@gmail.com ha
scritto:

**Comment by bk79** [comment]
@DzikuVx just a little update on sparky no go in any case I can only use serial ibus rx, on SPF3 deluxe I can set serial ibus rx or ibus telemetry but not together. even setting #define TELEMETRY_SHAREABLE_PORT_FUNCTIONS_MASK (FUNCTION_TELEMETRY_FRSKY | FUNCTION_TELEMETRY_LTM |FUNCTION_TELEMETRY_IBUS) so to be able to have 576 combination in serial it will only work ibus serial rx, if I try to set rx to one uart and telemetry to another port it won't work anyway. The strange thing is that both mavlink and ltm work, on sparky and on spf3

**Comment by bk79** [comment]
@DzikuVx the port cannot be shared, by itself the  protocol is bidirectional (half duplex) on 1 wire at least reading the doc and the code, so giving a dedicated serial port only it works on SPF3, still i don't understand why on sparky it doesn't work even if I set a dedicated port to it

**Comment by DzikuVx** [comment]
On sparky I will not help, sorry, do not own one. With sharing maybe

**Comment by DzikuVx** [comment]
I've rebased against latest master, maybe this will fix ibus since there were some fixes for that target if I remember correctly. @bk79 could you please check if ibus is working now?

**Comment by bk79** [comment]
@DzikuVx  now it works also on sparky, but the overall problem is still there, you can't share the same port with rx serial only one or the other will work

**Comment by DzikuVx** [comment]
@bk79 you might want to check latest version from this branch. IBUS is now allowed to share serial port with serial RX

**Comment by bk79** [comment]
I've already had a try modifiying that line and it doesn't work the problem
is hardware not software fisically stm32f3 uses internally rx on the tx pin
if required, since the protocol is bidirectional this will prevent or
telemetry or rx to work so (otherwise we could make two uart out of one
port)

Il 07/set/2016 21:05, "Paweł Spychalski" notifications@github.com ha
scritto:

**Comment by DzikuVx** [comment]
OK, in that case I'm reverting last commit since we can not fix the problem after all

**Comment by bk79** [comment]
Yes, you can also merge it looks stable, even if i think something like
frsky telemetry could be done in order to switch from msp to ibus

Il 07/set/2016 21:24, "Paweł Spychalski" notifications@github.com ha
scritto:

**Comment by DzikuVx** [comment]
iBus ATM is sharable with MSP. Should switch from MSP to iBus on ARM

OK, I'm removing "Testing required" flag and adding Ready to Merge

**Comment by inode-** [comment]
The IBUS telemetry is also in the master branch? I'm trying to get it working with official release 1.6 but I'm unable to setup it correctly.

**Pull request merged**
