### PR TITLE
Waypoint hold time feature

### PR DESCRIPTION
**Pull request by FabianSchwartau**
This should enable waypoint hold time type so the drone (fw are probably not supported) will hold the position of the waypoint for the given amount of time. As discussed in https://github.com/iNavFlight/inav/issues/154 p1 is the time to wait in seconds and p2 is the speed for action type 0x03 (which is hold time type).
This code is not tested in the field! I only did some simulations using fake gps. So BE CAREFUL!
This should partially fulfill https://github.com/iNavFlight/inav/issues/154.

### CODE REVIEW

**Comment by FabianSchwartau** [comment]
Sorry guys... I hate git. I don't know why there are a ton of commits in this pull request. How can I delete this request?

**Comment by stronnag** [comment]
You made the PR against master, not development. @fiam fixed it for you.

**Comment by FabianSchwartau** [comment]
That looks much better, but I actually only wanted to commit 5aa5f573f703d19ebef33158cdc728015e0d6db5, not the other 5 one.
Especially the first one is already in master, the others are just me trying to blow up git. Don't know why those are in there.

**Comment by stronnag** [comment]
Next time, create a separate branch in your repo for each new feature.

**Comment by FabianSchwartau** [comment]
I did so, then I blew everything up trying to rebase that to development branch while also updating that branch from the original repo. After that I deleted the branch and created a new one, but for some reason all the old stuff is still in there. Please bare with me, I am not a software expert and I hate git because of things I don't understand.

**Comment by FabianSchwartau** [comment]
The diff looks fine. Also the MAG3110 patch is not included, as it is probably already in the development branch. So that looks good, although the request looks a bit messy.

**Comment by stronnag** [comment]
exactly, git is your friend, you just don't realise that yet ....

**Comment by hali9** [comment]
@Jacky2k 
I see that you are trying to do a very nice thing, but maybe you will look at https://github.com/iNavFlight/inav/pull/4784. Although it doesn't implement POSHOLD TIME, it only uses the p2 parameter, but it is tested on a multi-copter and on an airplane.
I also see that that `NAV_WP_ACTION_HOLD_TIME `is the same as `NAV_WP_ACTION_WAYPOINT  `but with time in p1 and speed in p2.
This will also not work for the aircraft - need change loiter condition in calculateVirtualPositionTarget_FW.

**Comment by FabianSchwartau** [comment]
Well, I guess it is using only p2, because you don't need speed when you are holding your positon?
Why do you say it does not implement POSHOLD TIME? It seems to me that it does.

**Comment by hali9** [comment]
> Well, I guess it is using only p2, because you don't need speed when you are holding your positon?

In theory You are right, but in Your PR: NAV_WP_ACTION_WAYPOINT use speed from p1 and NAV_WP_ACTION_HOLD_TIME use speed from p2:
```
if(posControl.waypointList[posControl.activeWaypointIndex].action == NAV_WP_ACTION_WAYPOINT)
    wpSpecificSpeed = posControl.waypointList[posControl.activeWaypointIndex].p1;
else
    wpSpecificSpeed = posControl.waypointList[posControl.activeWaypointIndex].p2;
```
So when we have:
```
Lp type lon lat p1 p2
1  WP   10  20  50 0
2  HOLD 30  40  60 0
```
copter will fly to point (10,20) with speed 50
and then fly to point (30,40) with speed 0 (p2 overwrited by `max_auto_speed` because it is smaller from 50cm/s) and wait 60 seconds.

So as You see NAV_WP_ACTION_HOLD_TIME dont mean wait p1 seconds, but fly to point and wait p1 seconds (and use p2 speed).

> Why do you say it does not implement POSHOLD TIME? It seems to me that it does.

In my PR I don't implement POSHOLD TIME. Only use p2 for time to wait.

I came to similar conclusions https://github.com/iNavFlight/inav/pull/4784#issuecomment-498220880 as You did https://github.com/iNavFlight/inav/issues/154#issuecomment-583862382

p2 is the best for wait time, even if protocol was broken.

In fact how many third-party applications supports POSHOLD TIME ?

**Comment by FabianSchwartau** [comment]
OK, so we basically agree. You just decided to break compatibility in favour of a nice structure. I don't know how many apps are out there that already have this implemented and would have to change that. But if you break compatibility anyway, I would ditch the POSHOLD TIME feature and just add the time in p2 of normal WAYPOINT.
Edit: I would prefer not to break compatibility, simply because there are other FW that we will not be able to "force" changing that. And to avoid additional work for others, I prefer my suggested soution: Swapping p1/p2 for POSHOLD TIME.

**Comment by FabianSchwartau** [comment]
> This will also not work for the aircraft - need change loiter condition in calculateVirtualPositionTarget_FW.

OK, I don't have any experience with fw. Buy looking at the code I would guess that the plane will normally directly fly to each way point no matter what. If it is the last wp, it will loiter. Does that mean it will fly in a circle around the wp? So if there is a poshold wp, the plane should also loiter? I would say it should only do that if the time to wait is at least half the time the plane would take for a full circle?
How would a fw currently behave if the desired position stays at the wp it just passed?

**Comment by stronnag** [comment]
This breaks legacy apps by introducing a new MW state `MW_NAV_STATE_WP_HOLD_TIME`, moving everything else down. Just use extant `   MW_NAV_STATE_HOLD_TIMED` or you break MSP and LTM and anything that uses them (GCS, MW OSD etc.)

**Comment by FabianSchwartau** [comment]
OK, I guess there is just a miss understanding. Those names are just names. Are we talking about action 0x03? That is what I implemented. As I found a bunch of names for that it is a bit confusing.

**Comment by stronnag** [comment]
> Those names are just names. Are we talking about action 0x03? That is what I implemented. As I found a bunch of names for that it is a bit confusing.

It's not "just names" it defines a set of states used by numerous 3rd party applications. You've broken all these by adding a new value in the middle. So everything is after 3 if "off by one".

**Comment by FabianSchwartau** [comment]
Ohh now I see what you mean. Yeah, that is probably wrong, but I just have to remove that define and replace it with MW_NAV_STATE_HOLD_TIMED in my changes.

**Comment by FabianSchwartau** [comment]
... And I should refractor a few things. That is exactly the question I asked in https://github.com/iNavFlight/inav/issues/154 but no one answered. Will do that tomorrow.

**Comment by stronnag** [comment]
Until you'd published a valid development branch and people can review code, you were unlikely to get answers. Anyway, I've fixed it here, and added @hali9's FW loiter change, so maybe it'll fly tomorrow.

**Comment by FabianSchwartau** [comment]
With "here" you mean in your local repo? Cannot see anything in this pull request.

**Comment by stronnag** [comment]
> With "here" you mean in your local repo? Cannot see anything in this pull request.

Here as in "chez stronnag"

**Comment by FabianSchwartau** [comment]
Where ever that is :P
I wish you good luck tomorrow.

**Comment by stronnag** [comment]
I flew my locally updated version of the PR, in about 20-25 knots SW wind, so the PH circles were not pretty, but it worked as advertised. 

Local mods: 
* Fix up MW states as described above
* Implement @hali9's FW loiter changes

image
 
mwp (via LTM) voice announced "PosHold Timed" at  WP5. Just like MultiWii, only better.

**Comment by FabianSchwartau** [comment]
Wow, nice.
I will test that probably tomorrow with my quad. Can you send me a diff of your changes? Then I don't have to do it again and if you already tested it, it is less likely that I will do bad things. I will then add it to my pull request.

**Comment by stronnag** [comment]
> Wow, nice.
> I will test that probably tomorrow with my quad. Can you send me a diff of your changes? Then I don't have to do it again and if you already tested it, it is less likely that I will do bad things. I will then add it to my pull request.

I'll so something like that; as my build was merged onto @giacomo892's WP JUMP work (which doesn't, yet), it won't a diff, but it'll be obvious, as the FW specific changes are self-contained.

**Comment by stronnag** [comment]
This should do it, line numbers will be off in `navigation.c`.

[ph-fix.diff.txt](https://github.com/iNavFlight/inav/files/4193632/ph-fix.diff.txt)

(ignore the .txt; it's a diff, GH is stupid)

**Comment by stronnag** [comment]
Ping me when you've finished cleaning it up, I can try it again 2020-02-14 as long as the forecast's not lying.

**Comment by stronnag** [comment]
FYI, mwp log replay ... https://youtu.be/wavinsHQL1s

**Comment by FabianSchwartau** [comment]
Before I start cleaning up the code: Is that feature supposed to be called POSHOLD TIME or POSHOLD TIMED?

**Comment by FabianSchwartau** [comment]
@stronnag ping
I basically just applied your patch. Simulation sill works for me.

**Comment by stronnag** [comment]
> @stronnag ping
> I basically just applied your patch. Simulation sill works for me.

Excellent, my fault if I crash and burn tomorrow :)

**Comment by FabianSchwartau** [comment]
I will probably test it tomorrow if the weather forecast is right.
Can someone provide some thought on how to proceed with the combination of this PR with https://github.com/iNavFlight/inav/pull/4784? Currently they are not 100% compatible, a few things are implemented in both in slightly different ways and so on. How is the common procedure here? Will we wait until one of the patches makes it into development and the other one will have to rebase and correct things? Or should we just merge one of the PR into the other and drop the first one?

**Comment by stronnag** [comment]
Flew the last merge on FW, no problems.

**Comment by FabianSchwartau** [comment]
Same for me (Edit: using an X-Quad). Worked exactly as expected.
Is there anything else I need to do to get this into the master/next release? One thing is the missing documentation in doc/Navigation.mk. I will do that now.

**Comment by stronnag** [comment]
> Is there anything else I need to do to get this into the master/next release? 

Resolve conflicts as they arise.

**Comment by FabianSchwartau** [comment]
Ohh, yes. Is there a way to get notified about such a problem? I did not get a mail. Would be nice.
Did the merge. Did not push yet, I would like to test it first, but its raining all day.

**Comment by stronnag** [comment]
> Ohh, yes. Is there a way to get notified about such a problem? I did not get a mail. Would be nice.
> Did the merge. Did not push yet, I would like to test it first, but its raining all day.

I don't think there is a way to get automagic conflict notifications. As `navigation.c` is getting a lot of attention this cycle, there may be a few more on the way to merging.

**Comment by FabianSchwartau** [comment]
Yeah, just from my side there are three pull request which don't like each other without some little changes here and there ;)

**Comment by FabianSchwartau** [comment]
This may take longer than expected. I was able to test my merge, but I am unable to push it into my repo. I HATE GIT! Maybe someone can help me:
On the jacky2k_waypoint_hold_feature branch I did a "git pull", nothing to do, so I am good to go. So I do "git fetch upstream" and "git merge upstream/development". He complains about merge conflict and I solve them using meld. I do a "git add src/main/navigation/navigation.c" to mark the file for the commit, followed by a "git push origin jacky2k_waypoint_hold_feature", which fails with

>  ! [rejected]            jacky2k_waypoint_hold_feature -> jacky2k_waypoint_hold_feature (non-fast-forward)
error: failed to push some refs to 'git@github.com:Jacky2k/inav.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.

A git pull says everything is up to date. Don't know what to do :(

**Comment by FabianSchwartau** [comment]
OK, I think I got it, but I will have to test that again...

**Comment by giacomo892** [comment]
@Jacky2k rebasing your branch on development and manually fixing the conflicts should do the trick

**Comment by FabianSchwartau** [comment]
I learned that rebasing is not a good idea when working together with other people/pull request as it requires a force push. So I did a merge (what git pull does in the background as far as I understand). However, I had to do a reset --hard, for unknown reason. As the merge looked quite a bit different then, I would like to test it first. But as there is just half an hour of daylight after I get home from work, I can do only one iteration per day ;)

**Comment by FabianSchwartau** [comment]
I think I finally got it :)

**Comment by stronnag** [comment]
Just in time to do it again! Once these simple matters are resolved, this can be merged as well.

**Comment by FabianSchwartau** [comment]
Wow, this is more work than I expected :P 
I may be able to do that tomorrow.

**Comment by FabianSchwartau** [comment]
Wow, who said to me that there is plenty of checking to prevent bad code a drone to crash?
I have proven you wrong! ;)
And I think I need your help guys, maybe someone has a good idea. The following happened:
I tested my waypoint hold stuff after doing the merge and everything worked fine. During merge I saw that the jump feature was also merged. So I updated mwp (current development branch) and created a mission including hold and jump. The drone flew to the hold point, waited there. After the time was over, it did nothing, although it should jump to a previous waypoint. The CLI said "PREPARING FOR NEXT WAYPOINT", but nothing happened. So I turned off waypoint mode - nothing happened. It was still showing "PREPARING FOR NEXT WAYPOINT". The drone was just hovering there, holding its position. After thinking for a bit, I came to the conclusion that the only way to get it back down would be to wait until the battery is empty, which would result in a crash I guessed, disarming it or to flip the failsafe switch (I was happy to have it, as I though removing it from the remote...). Failsafe was configured as RTH. So I flipped the switch and my heart jumped as I realized that the drone just turned off its props and fell like a stone. It was "only" 10m, so I was not fast enough to hit the roll/pitch stick to exit FS. The drone crashed legs forward into the ground. Two legs, two props broken and it sounds a bit different now (after replacing the props). And there was one more thing that concerned me quite a bit: Disarming did not worked! It was lying at the ground and still spinning the props at idle, while arm switch was off!
And as usually, the balckbox was full, so no recording. After a quick repair, I decided to do exactly the same mission again, but at an altitude of 3m and erasing the blackbox flash first. It happened exactly the same. So I got a recording.
I looked at the diff of my current local branch against the development branch and could not find a problem. Can someone make some sense from that? Below is the git diff, the mission, the blackbox and the cli diff.
[crash_prep_wp_failsafe_failed.zip](https://github.com/iNavFlight/inav/files/4268079/crash_prep_wp_failsafe_failed.zip)

**Comment by stronnag** [comment]
Welcome to our world, "Broken toys 'r' us". And commiserations on the damage. One reason why I like testing stuff on FW (vice MR);  they tend to glide rather than plummet like "[un mouton anglo-français](https://www.dailymotion.com/video/x2v9uxz)". I intend to test JUMP + PHT on Monday, and I'll try a similar mission [WP WP PH JUMP RTH](https://youtu.be/1M85uL8QkZM
); in theory it should work.

Unfortunately the log is unreadable.

**Comment by FabianSchwartau** [comment]
Yeah I noticed that my logs are never readable when the flash runs full. Is that normal? I guess that something went horribly wrong in the fc and the log also stopped.

**Comment by FabianSchwartau** [comment]
I just figured out that this is not my fault. It also happens when my patch is not applied. So the current development branch is broken. For some reason the he goes into NAV_STATE_WAYPOINT_PRE_ACTION, processes the jump waypoint, returns with NAV_FSM_EVENT_NONE to reprocess this state with the new (next) waypoint, but the according function navOnEnteringState_NAV_STATE_WAYPOINT_PRE_ACTION is never called again.

**Comment by stronnag** [comment]
Unless anyone objects, I'll give this one final test on FW on Monday, then merge it.

**Comment by FabianSchwartau** [comment]
Just for the record: The problem above has been fixed by https://github.com/iNavFlight/inav/pull/5460.
I committed my merge of of current development branch and tested it in the field.

**Comment by peteoz** [comment]
please consider "LAND" WP type, or simply "land" option at last WP just as if it was RTH WP, as explained here : https://github.com/iNavFlight/inav/issues/5467

**Comment by FabianSchwartau** [comment]
Sounds like a good idea, but does this have anything to do with the hold feature? Like this is a completely different type of waypoint. So, I am willing to (help) implement that, but I don't see that I need to change this PR. Right?

**Comment by peteoz** [comment]
you are correct, this has likely nothing to do with the hold feature other than the fact that it's just another MSP/mw-nav compatible WP type.
but since "wait for RTH waypoint" was previously discussed in relation to "land=0/land=1" I thought I may mention it here  in case that any new WP types with landing option would need to be implemented same way.
Previously discussed here :  
 https://github.com/iNavFlight/inav/pull/4784#issuecomment-498220880

**Comment by stronnag** [comment]
Tested again on FW, merge time ...

**Comment by FabianSchwartau** [comment]
Nice, thanks a lot for all your support!
Edit: Is there a rough release plan for 2.5?

**Pull request merged**
