### PR TITLE
BLHeli 4way interface support

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by DzikuVx** [comment]
@digitalentity it this latest from Betaflight with SimonK bootloader?

**Comment by digitalentity** [comment]
@DzikuVx this is even newer - with some cleanups @4712 and @Hydra did in the according PR to Cleanflight.
Verified to work with SimonK bootloader.

**Comment by 4712** [comment]
@digitalentity my pr is already merged in [betaflight 2.6.1](https://github.com/borisbstyle/betaflight/pull/332) since 10 days...

**Comment by digitalentity** [comment]
@4712 sorry, must have missed the notification in lots of incoming emails :)
I'm using this code in INAV for a while now, I think this will be merged very soon! 
Thanks for the great feature!

**Comment by 4712** [comment]
Thanks!
No problem, I just wanted to say: it's already tested in BF and it is the same code as in the current CF pr.

**Comment by digitalentity** [comment]
Great! So I'll merge this ASAP. I may still have to do some cleanups - this is a direct port from CF's PR I might have accidentally pulled over some excess code.

**Pull request merged**
