### PR TITLE
Nav Emergency landing code fixes and refactor

### PR DESCRIPTION
**Pull request by breadoven**
Fixes Nav emergency landing function during normal RTH and WP navigation which currently doesn't appear to work (only seems to work during Failsafe). Code improved to simplify structure, fix bugs and add in missing checks related to Emergency landing sensor failures, The changes are configured to cancel the Emergency Landing if failed sensors become available again allowing RTH or WP to be re-enabled if still selected. The exception is if landing is detected in which case the Emergency Landing remains active regardless of sensor status (although this is moot since Emergency Landing detection is TODO).

Timeout enabled on `NAV_STATE_WAYPOINT_FINISHED` to ensure Emergency Landing can activate which currently it can't do with no timeout set. Minor issue is `clearJumpCounters()` will now execute repeatedly. Is `clearJumpCounters()` necessary ? Seems the Jump counters get reset anyway when a WP mission restarts so perhaps they don't need clearing at the end of a mission.

`canActivatePosHold ` removed from `selectNavEventFromBoxModeInput` RTH and WP initialisation since `canActivateNavigation `already provides more stringent Nav requirement checks making `canActivatePosHold` redundant.

Other minor changes to simplify RTH/WP Nav code.

Tested on the ground with simulated RTH and WP missions and works as expected. Bit difficult to check in flight other than for false triggers I guess.

### CODE REVIEW

**Comment by rts18** [comment]
@breadoven Good fix :+1: . A feature thats often over looked, until its needed. Then users hope it works.

**Comment by breadoven** [comment]
> @breadoven Good fix 👍 . A feature thats often over looked, until its needed. Then users hope it works.

I was a bit surprised it doesn't appear to actually work. Have you ever tested it ? Easy enough on a MR with the props removed, kill the GPS signal in RTH and see what happens, should drop out to Nav idle based on my testing.

**Comment by rts18** [comment]
I haven't tried your changes. Although I have tested this feature a couple of times in the past.

The first time was a ground simulation, by blocking the GPS with the motors spinning in RTH.
This gave mixed results, with the motors reacting differently in each trial.  It left me to assume, the nav code uses both accelerometer and barometer to determine if the craft was in motion.

The second test was in flight, by using pinio to turn off GPS power in RTH. 
The quad descended much faster than expected and was obviously blown by the wind.
The test was also inconclusive. With no logs, it was hard to say whether it just dropped with motors idling, or it tried to arrest its fall.

**Comment by breadoven** [comment]
If it's working it should show "Emergency Landing" in the OSD system message. It didn't when I tried it originally. Think part of the message flashed up briefly once but then nothing, Nav had switched to Idle. In your case I'd have thought it would have just reverted to whatever mode was set that didn't require GPS, with altitude control decided by the throttle position.

**Pull request merged**
