### PR TITLE
Modify URL's to be INAV specific continuation of #285

### PR DESCRIPTION
**Pull request by dan557**
Continuation of #285 
Clean up of original pull request #285 
Change URL's to be INAV specific
Remove any sections that INAV doesn't have such as Travis-Ci and YouTube

### CODE REVIEW

**Comment by digitalentity** [comment]
@dan557 is it ready to merge or you are still cleaning up the README?

**Comment by dan557** [comment]
Ready for merge

**Comment by digitalentity** [comment]
Thanks!

**Comment by stronnag** [comment]
Please reinstate #inavflight

**Pull request merged**
