### PR TITLE
Fix reversed yaw

### LINKED ISSUE #293: RC Yaw is reversed in current master
Some change between 4db8d9c and 19887ef causes RC Yaw to be reversed (at least for PPM).

This is somewhat disconcerting and probably not intended.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #293.

### CODE REVIEW

**Comment by martinbudden** [comment]
This is the wrong fix. The correct fix is to re-introduce the -1 multiplier. The lookup itself should be "policy free". The lookup function should do just that - look things up, it should not make any presumptions on how that lookup is used.

The -1 multiplier is a result of the way the motors are arranged, and certainly rclookup should not know anything about that.

**Comment by digitalentity** [comment]
@martinbudden good point. Changing.

**Comment by digitalentity** [comment]
Just came to me, maybe this should be solved at mixer level to avoid
magical multiplication by -1 ?

**Comment by martinbudden** [comment]
In Cleanflight the code is:

```
rcCommand[axis] = rcLookupYaw(tmp) * -rcControlsConfig()->yaw_control_direction;
```

That is the yaw control directon is configurable. iNav assumes a value of -1.

I don't think this needs to be configurable, but it is in Cleanflight and I'd rather not change this in the mixers in iNav, because then iNav would have different mix tables from Cleanflight and betaflight.

**Comment by digitalentity** [comment]
Good point, as usual. I'm packing for a return trip home, can you please
finish the fix?

**Comment by DzikuVx** [comment]
It was agreed to remove yaw_control_direction in #200

**Comment by martinbudden** [comment]
Closing this so that new fix can be submitted.

**Pull request closed without merging**
