### PR TITLE
Sonar initialisation cleanup - part 3

### PR DESCRIPTION
**Pull request by martinbudden**
@digitalentity , here's part 3 of the sonar initialisation cleanup. It's not quite ready for merge, but I thought I'd make a PR so you can have a look at it.

One of the things I've done is done some renaming from "sonar" to "rangefinder" in the expectation that other types of rangefinder will be supported in future (I'm interested in implementing a LIDAR rangefinder at some point in the future).

One other thing, there is a case to move the GPS code from the `io` directory to the `sensors` directory, and to move the GPS initialisation into `sensors/initialisation.c` - what's your view on that?

### CODE REVIEW

**Comment by digitalentity** [comment]
I'm traveling, do I'll review oh a few days once I get to my laptop.

I  like the idea about moving GPS to sensors directory - it's a sensor
anyway.

**Comment by martinbudden** [comment]
@digitalentity , I'm happy for this to be merged now, if you think it is ok.

This completes the cleanup of sonar initialisation.

**Comment by digitalentity** [comment]
@martinbudden looks good so far, but I'm not able to test it yet. Please give me a few days to review :smile:

**Comment by martinbudden** [comment]
@digitalentity , no worries - there's not a rush on for this one.

If you find any problems, let me know and I will fix them.

BTW, I've been bringing over some minor features and bug fixes from Cleanflight. The one that might catch you off guard is the CC3D PPM fix, this has moved the PPM input to PWM6 (it was PWM1). I don't know if you are running any CC3D quads with a PPM receiver.

**Comment by digitalentity** [comment]
@martinbudden sorry, I forgot about this PR. Can you rebase?

**Comment by martinbudden** [comment]
@digitalentity , rebased and ready for merge.

**Comment by digitalentity** [comment]
Merged, thanks! Now we can start improving sonar support in INAV.

**Pull request merged**
