### PR TITLE
Wait WP WPRTH RTH

### PR DESCRIPTION
**Pull request by hali9**
Implement feauture from https://github.com/iNavFlight/inav/issues/4123
Also work for waypont and "RTH waypoint".
Tested on quad250 and airplane.

### CODE REVIEW

**Comment by stronnag** [comment]
Just an FYI: MSP already defines a timed PH waypoint type (which is already supported by third party planners) https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages

**Comment by hali9** [comment]
Yes. MSP defines 8 enum, and inav implement only 2.
Also POSHOLD_UNLIM is not implement, although it is possible to achieve in inav.
If POSHOLD_TIME will implement, then one waypoint will need two records, one for WAYPOINT, the other for POSHOLD_TIME, because parameter 1 is with conflict (WAYPOINT is speed, POSHOLD_TIME is seconds).
Also it is impossible to implement wait for "RTH waypoint" so we will need 3 records ?
```
RTH Land=0
POSHOLD_TIME seconds 
RTH Land=1   (or LAND ?)
```
It is not possible to use POSHOLD_TIME in this case because we do not know the home point coordinates and there are required. So we would have to break this rule (setting lat=0, lon=0, alt=0 ?) where zero means stay where you are.
Also descending (climbing) during wait in "RTH waypoint". Inav does not have implement altitude. RTH have only one parameter: LAND. But even if this will be done;
```
RTH Land=0, alt //first descend/climb
POSHOLD_TIME seconds //then wait
RTH Land=1   (or LAND ?)
```
or
```
POSHOLD_TIME seconds //first wait
RTH Land=0, alt //then descend/climb
RTH Land=1   (or LAND ?)
```
But there is no option for descend/climb and wait at this same time

Besides, it does not break the MSP, only extends it uses unused parameters.

**Comment by stronnag** [comment]
Indeed, it's a legacy mess. The proposed solution is fine.

**Comment by junwoo091400** [comment]
What good does waypoimt wait feature bring? Providing some 'buffer time' before it switches states prematurely?

**Comment by shellixyz** [comment]
> What good does waypoimt wait feature bring? Providing some 'buffer time' before it switches states prematurely?

The idea is to give you time to fix the issue before a potentially bad landing depending on the place (near high obstacles for example) when you're using land on FS and you have an issue with the TX

**Comment by junwoo091400** [comment]
> > What good does waypoimt wait feature bring? Providing some 'buffer time' before it switches states prematurely?
> 
> The idea is to give you time to fix the issue before a potentially bad landing depending on the place (near high obstacles for example) when you're using land on FS and you have an issue with the TX

Ahhhh so it is for failsafe purpose primarily

**Comment by hali9** [comment]
> > What good does waypoimt wait feature bring? Providing some 'buffer time' before it switches states prematurely?
> 
> The idea is to give you time to fix the issue before a potentially bad landing depending on the place (near high obstacles for example) when you're using land on FS and you have an issue with the TX

Yes it work for normal RTH (time is seting by CLI `nav_rth_home_wait`)

In addition, it is possible to set time to wait for each waypoint (including when last waypoint is RTH).

**Pull request closed without merging**
