### PR TITLE
Added state NAV_STATE_WAYPOINT_HOVER_ABOVE_HOME

### PR DESCRIPTION
**Pull request by Airwide**
This is a pull request to fix issue #4828.

I've tested it successfully on an AR Wing with a MATEKSYS F405 Wing.

It would be great if someone else could validate the functionality on a multicopter.

### CODE REVIEW

**Comment by Airwide** [comment]
@peteoz -  I've implemented what you suggested in issue #4828. Can you test on a MR?

@stronnag - I know you work a lot with wp missions. Do you have time to review this pull request and possibly even test it on a MR?

**Comment by Airwide** [comment]
@DzikuVx - WDYT?

**Comment by stronnag** [comment]
> @stronnag - I know you work a lot with wp missions. Do you have time to review this pull request and possibly even test it on a MR?

I should be able to test it in the coming week

**Comment by DzikuVx** [comment]
Over here I'm not qualified to say what I think :) @digitalentity ?

**Comment by Airwide** [comment]
@stronnag - Did you manage to test this PR on a MR? Thanks!

**Comment by stronnag** [comment]
Sorry, no I didn't (and not likely to for at least the next 3 weeks)

**Comment by Airwide** [comment]
@stronnag No worries! I managed to test the PR with my new Pirx Seven drone today. The test was successful and it works as expected. See the transition to Hovering in the screenshot below.

Screenshot 2020-11-24 at 10 51 33

Do you think we need additional tests before this PR can be merged?

**Comment by stronnag** [comment]
@Airwide if you'd please fix the merge conflict (mea culpa), I'll merge it.

**Pull request merged**
