### PR TITLE
Fix RX Serial Enumeration

### LINKED ISSUE #8190: Rx Link Loss with current master build
Updated my custom firmware yesterday with the master version and now no Rx link on 2 boards that have been flashed, HGLRCF722 and FLYWOOF411 targets. The ELRS Rx seems to bind (LED steady) and there's basic telemetry but otherwise no Rx link. INAV is in Failsafe with the RX LINK system message showing. Status in the CLI doesn't tell you any more. Serial port and Receiver setting are as before. Another board that hasn't been updated works fine so it's not the transmitter. The working board was last updated from master on the 28/6/22 so the problem is caused by something from that date. The next commit showing in the history after that master update is related to https://github.com/iNavFlight/inav/pull/8176.

I've not changed anything related to the Rx in my custom changes so it would appear to be something in the current master. I noticed there are various changes to Rx related stuff. Any idea what's broken here or is there some settings that needs updating ?

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
From the count of number 4 jumped to number 7. 

Closes https://github.com/iNavFlight/inav/issues/8190 After @Jetrell confirming that this was the problem

### CODE REVIEW

**Comment by Jetrell** [comment]
@JulioCesarMatias CRSF now works again with this fix.

**Comment by JulioCesarMatias** [comment]
> @JulioCesarMatias CRSF now works again with this fix.

Thanks for the test, I opened this PR really wondering if this would fix the problem... But I wasn't sure why I don't have the Hardware to test

**Comment by JulioCesarMatias** [comment]
Closes https://github.com/iNavFlight/inav/issues/8190

**Comment by robustini** [comment]
Yes! Fix the problem here, thanks @JulioCesarMatias!
I believe merge is imperative... :P

**Review by DzikuVx — APPROVED** [review]

**Comment by breadoven** [comment]
Ah I noticed the enum but thought it shouldn't matter. Just tested again with the broken firmware and it works if you set the serialrx_provider to SBUS_FAST, i.e. 2 settings above CRSF. So the settings table for serialrx_provider in settings.yaml was changed by deleting the 2 Rx providers which messed up the enum numbering alignment when the enum kept the originally numbering.

Also it seems the enum reference in the yaml settings tables is for reference only since adding it for the serialrx_provider table changes nothing. Is this correct ?

**Pull request merged**
