### PR TITLE
Unify reboot sequence across all use-cases

### LINKED ISSUE #3642: 2.0 RC4 Arming issue after CMS save reboot
After save & reboot from CMS, motors do not spin after arming.  However stat will still appear during disarm.

In 1.9.x, CMS save & reboot produce ESC last startup tone, but in 2.0 RC4, they are gone.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #3642

### CODE REVIEW

**Comment by giacomo892** [comment]
Tried to test this out. Getting some warning @digitalentity 
image

**Comment by giacomo892** [comment]
Adding #include "drivers/system.h"  to fc_core.c fixes all the warning.

Tested and it working with 32bit ESCs

**Comment by lo4wai** [comment]
I can confirm it works too!  Thanks!

**Comment by digitalentity** [comment]
@giacomo892 fixed.

**Pull request merged**
