### PR TITLE
Smartport on STM32F4 with external inverters

### PR DESCRIPTION
**Pull request by DzikuVx**
This PR introduces `smartport_uart_unidir` setting, that when set to `ON`, puts associated UART is `UNIDIR` mode.

This is required when external inverter is used between S.Port receiver and FC without inverters (F1 and F4). Schematics for such inverter are in docs. Tested on Flip32F4 and X4RSB.

### CODE REVIEW

**Comment by HaseebNain** [comment]
Has this been confirmed working on any other F4? I attempted this with a SPARKY2 board with an external inversion circuit but did not see any Telemetry information on the receiver.

**Comment by DzikuVx** [comment]
@HaseebNain This is target independent and should work on any F4 and F1 target

**Comment by HaseebNain** [comment]
Odd, is there anything else besides having to enable the inversion through CLI? I didn't see any new #defines needing to be mentioned in the target.

**Comment by Linjieqiang** [comment]
image
@DzikuVx Can this circuit work for Smartport on F4 MCU?Looking forward to your answer.

**Comment by DzikuVx** [comment]
@Linjieqiang as a matter of fact I'm not sure. In theory, it should. But if you look at what is happening at FC side then TX is low. Then, 2Y goes high and I see no way SmartPort end can drive 1B low. 

If you taka a look [here](https://quadmeup.com/smartport-inverter-for-f4-flight-controllers/) (this is proven working) when TX is low, Smartport side gets high, but there is 46kOhm pullup that allows SmartPort side to force low on mosfet side and drive RX high.

I support the only way to check is to build such a device and test it. I think I saw this diagram somewhere

**Comment by Linjieqiang** [comment]
Yeah.I found it in the betaflight project but I am also not sure this circult working well.But I will have a try.

**Pull request merged**
