### PR TITLE
agh msc revisited - update MSC patches

### PR DESCRIPTION
**Pull request by stronnag**
This experimental branch updates @fiam 's agh_msc branch for 2.4 dev. 

For all of my 33 test BBL files, sizes from 8400 bytes to 109MB, the files copied by MSC and directly (extract SD card to card reader) are identical.

There are no significant / functional changes to the original branch, so either improvements / fixes  in the SD handling have fixed prior issues, or the earlier testing methods that created file on the SD card using direct OS drivers was unsound as now we appear (early days) to be able to "eat our own dog food").

### CODE REVIEW

**Comment by stronnag** [comment]
Couple of other points:

* It's seriously slow (typically 340 kBs vice 15.5MBs for a card reader), still probably quicker than dismantling / reassembling the plane in some cases.
* Tested on Linux only
* None of the syslog errors seen in https://github.com/iNavFlight/inav/issues/1336#issuecomment-459790819 have been seen against this branch (so far ...)

**Comment by stronnag** [comment]
And I know it's not compiling on F7 ....

**Comment by fiam** [comment]
Good idea to bring this up again and great work making it up to date and testing everything. Just took a peek at the travis log and the F7 build error seems a matter of a missing include (mscCheckBoot() seems to be called from usbd_desc.c before its declaration is found)

**Comment by stronnag** [comment]
> Good idea to bring this up again and great work making it up to date and testing everything. Just took a peek at the travis log and the F7 build error seems a matter of a missing include (mscCheckBoot() seems to be called from usbd_desc.c before its declaration is found)

It should compile now, however the way the `USBD_Device` is currently declared F4 v. F7 seems like it could be rationalised.

**Comment by stronnag** [comment]
Current Status:

- Read / write / delete for sd card tested ok on Linux, Windows 7 and Windows 10 on several FC.
- Internal flash mounts, but is not yet useful. This will ~probably become a new issue / PR~ be fixed shortly, so internal flash can also be read via MSC.

**Comment by fiam** [comment]
@stronnag Tested this PR on macOS with an OMNIBUSF4PRO. Total success.

- Put an SDCard in an USB reader, hashed a bunch of files (from 10MB to ~500MB)
- Put that card into the FC, enabled MSC mode and got the same hashes
- Generated 5 50MB random files into /tmp and hashed them
- Copied them into the card via MSC. Umounted and mounted to force the FS cache to clear. Hashed them again via MSC and got the same hashes.
- Pulled the card out of the FC and into the USB card reader. Hashed those random files again and got the same results.

Great work!

**Comment by stronnag** [comment]
Thanks for testing on macOS. 
Other than addressing any review comments that may arise, I think this is done.  I'm not convinced that the internal flash 'informational' virtual files (`autorun.inf`, `icon.ico` ) are much use; a modern Windows will probably ignore them, otoh we're not short of flash on F4/F7.

**Comment by fiam** [comment]
My pleasure! Forgot to mention, another thing that always happened the first time I implemented this was that renaming the drive 3-4 times ended up generating a drive name full random characters. Tested renaming the drive like 10 times with this PR and it worked fine. I guess it’s good to go!

**Review by fiam — APPROVED** [review]

**Comment by zoran-grujic** [comment]
New FC by SpeedyBee F405 WING APP has inaccessible SD. So it would be really great if logs would be downloadable...

**Pull request merged**
