### PR TITLE
Added rangefinder "GY-US42(v2) Ultrasonic Range Sensor"

### PR DESCRIPTION
**Pull request by emtrax-ltd**
Add the ultrasonic range sensor GY-US42 as a new rangefinder to inav.

Because of the sensor's i2c trigger write command (only point to the register and restart), there was the need to patch the Method "drivers/bus_ic2_hal.c-> i2cWriteBuffer(...)" for passing through null values to HAL_I2C_Master_Transmit (raw access).

The module and this software change was successfully testet with inav 3.0.0 (master) and the modified target "matekf405se" for the matek f405 wing. 

This rebased pull request replaces the old one #5698

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
what is the maximum reliable altitude you have achieved with it?

**Comment by JulioCesarMatias** [comment]
adding an average filter seems to me to be interesting

**Comment by DzikuVx** [comment]
@emtrax-ltd build if failing on several targets, please fix

**Comment by emtrax-ltd** [comment]
> @emtrax-ltd build if failing on several targets, please fix

fixed!

**Comment by JulioCesarMatias** [comment]
add V2 after US42?

**Comment by emtrax-ltd** [comment]
> add V2 after US42?

not necessary -> v1 and v2 are compatible - "v1" is no longer available on the market ... "v2", because i
 tested with this version

**Comment by emtrax-ltd** [comment]
> what is the maximum reliable altitude you have achieved with it?

specs says 5m@3.3v or 7m@5v -> so 5m is the limit because i2c runs at 3.3v ... BUT i limited it to 4m because ardupilot also recommends this as maximum.

**Comment by JulioCesarMatias** [comment]
> > qual é a altitude máxima confiável que você alcançou com ele?
> 
> as especificações dizem [5m@3.3v](mailto:5m@3.3v) ou 7m @ 5v -> então 5m é o limite porque o i2c funciona a 3,3v ... MAS eu limitei a 4m porque o ardupilot também recomenda isso como máximo.

for multirotors I think it's cool, but for the wing not much, because the altitude is very low, who knows in the future iNav may work with, for example, the Benewake TF02

**Review by DzikuVx — APPROVED** [review]

**Pull request merged**
