### PR TITLE
Delete unused 'angleAtMin' and 'angleAtMax'.

### PR DESCRIPTION
**Pull request by Linjieqiang**
catch up with https://github.com/cleanflight/cleanflight/pull/2676

### CODE REVIEW

**Comment by Linjieqiang** [comment]
It's ready to merge it.@digitalentity

**Comment by digitalentity** [comment]
Does somebody remember what angleAtMin and angleAtMax were intended to do?

**Comment by oleost** [comment]
I believe it was to correct for geometry of servo traveling an make it more accurate somehow. But I have an hard time finding it.

**Comment by digitalentity** [comment]
Hm... seems not a bad idea at all. However we have people used to set things up without angles. I guess this is an acceptable cleanup.

**Pull request merged**
