### PR TITLE
Nav launch abort improvements

### PR DESCRIPTION
**Pull request by breadoven**
Adds the ability to abort nav launch when the throttle stick is set above the low position but less than the nav launch idle throttle setting. This should help to prevent situations such as https://github.com/iNavFlight/inav/issues/7512.

Shouldn't be a safety issue because the throttle can't jump to a higher setting than the launch idle throttle setting when the launch is aborted.

Change also allows the sticks to be used to abort a switch launch rather than having to use the switch only. Not obvious why this wasn't possible before. If there is a good reason for it then this part of the change can be removed.

### CODE REVIEW

**Comment by breadoven** [comment]
Any objections to merging this change @DzikuVx @avsaase ? Or is it of dubious benefit given what it's trying to resolve ?

**Comment by DzikuVx** [comment]
@breadoven it's time to merge this thing. Could you please resolve conflicts?

**Comment by Jetrell** [comment]
@breadoven I was testing this today. And I found a situation where this was a problem.
If the pilot accidentally knocks the disarms switch in flight, with either the throttle low, or lowers it later.  The FC will obviously disarm.
If `Permanently enable autolaunch` is active.  Then as soon as the pilot re-arms the FC, it will restart autolaunch and require the throttle to be in the specific window, for it to override the launch mode.

>
>Remembering to lower the throttle instead to regain control when in panic mode is counter intuitive.

This could be a big issue if the pilot is in a panic, and about to hit something, and needs more throttle instantly.. The first instinct is to give it full throttle, and forget it has to be between low and launch idle throttle, to get it to override.

Whats your take on this?

**Comment by breadoven** [comment]
Surely this is the way it's always worked. Whatever happens you always have to lower the throttle to rearm regardless of auto launch being enabled. If you move the sticks whilst throttle is still low auto launch will immediately cancel. The only difference this change makes is if you have launch idle throttle set the launch will be cancelled if the throttle is between low and the launch idle setting making it easier to cancel launch because the throttle doesn't need to be fully low. The change isn't intended to help with in flight disarms just the situation where you're using significant launch idle throttle, the launch isn't detected and the pilot forgets to lower the throttle to cancel the launch using the sticks allowing control to be regained.

**Comment by MrD-RC** [comment]
If override extra arming safety is active (programming) what happens? That should allow arming with the throttle in any position. That how it currently works (4.1). Though if launch is permanently enabled, it still needs to be exited.

**Comment by Jetrell** [comment]
I do have `nav_extra_arming_safety = OFF`.  Although I haven't tested it in every possible combination of settings.

The part that stands out between 4.1 and this feature... Is ... Before when the throttle was at zero, and the FC was rearmed. The ROLL stick could be moved with the _throttle back at low_ to override autolaunch.  _This allowed for an all in one defeating of auto launch and rearm_, then full throttle could be applied instantly.
Now it has to be in a specific range, which may be a narrow band if the auto launch idle throttle is only set low. e.g. 1200uS ... It requires a more conscious efforts for the pilot find that point, and watch the OSD, to ensure it did override auto launch.

**Comment by Jetrell** [comment]
Your right... It should be almost the same! 
I'll have to go out flying again after work, to be sure. I just remember that it wouldn't rearm in flight yesterday after this situation.. It took three attempts, and luckily I had a good amount of altitude.
And I was running the same settings, as with 4.1.

**Comment by Jetrell** [comment]
Thanks for the reply guys.
Long story short, after systematically chasing down the error. Which was causing **everything** to run slow... Even causing Dshot to reboot the ESC, after rearming in flight. (I'm surprised it even flew)
 _It turned out to be a faulty data logging card!_ Which was steeling task scheduling time.  
Interesting that this is an F765 FC, which are experiencing issues with some microSD card types.


As for this feature, it works well... Although the throttle window margin will vary depending on gap between _min_command_ and launch idle throttle..  Some users set it low (1200uS) and others higher (1650uS).

Thanks for you work on this PR @breadoven

**Pull request merged**
