### PR TITLE
FuriousFPV WingF4 initial support

### PR DESCRIPTION
**Pull request by MJ666**

### CODE REVIEW

**Comment by fiam** [comment]
@MJ666 Where can we get some info about this FC? A Google search turns up nothing useful.

**Comment by MJ666** [comment]
FuriousFPV will release this FC quite soon. Likely during next two moths. This FC is specily desined for flying wings. I help to get the FuriousFPV FC's supported by the firmware. Did this for BF already.

**Review by digitalentity — CHANGES_REQUESTED** [review]
@MJ666 looks good so far. Please add a README.md so we could know more about this FC

**Comment by MJ666** [comment]
Added readme file.

**Comment by digitalentity** [comment]
On hold until some feedback from vendor.

**Comment by MJ666** [comment]
What additional feedback is needed? Anything missing for the readme file?

**Comment by digitalentity** [comment]
I've asked FuriousFPV if they are willing to donate hardware to some of active INAV developers. I would be fine with a "NO", but I got nothing. Both of my emails were completely ignored.

I guess they are not very interested in getting their boards supported by INAV. No offence to you @MJ666 - you did a great job writing the code, but I believe we deserve at least some responce from FuriousFPV.

**Review by digitalentity — APPROVED** [review]

**Comment by digitalentity** [comment]
Moving this to 1.9 milestone

**Comment by MJ666** [comment]
The code came from FuriousFPV directly. It was tested by them on there prototype boards. I will follow up with my contact at FuriousFPV why your emails get unanswered. I have helped them to get their targets merged to Betaflight and also did some improvements there. The same I want to do here with iNav. I have some of their boards but not a WingF4 yet.

**Comment by digitalentity** [comment]
@MJ666 thanks! Please keep me posted.

**Comment by furiousfpv** [comment]
@digitalentity Hi, can you send email to toan@furiousfpv.com , i didnot see your email.

**Comment by digitalentity** [comment]
@furiousfpv just sent you an email, thanks for getting back to us.

**Comment by digitalentity** [comment]
@MJ666 @furiousfpv I'm merging this PR into 1.8

**Pull request merged**
