### PR TITLE
Turn assistant - turn on parallel to ground plane

### PR DESCRIPTION
**Pull request by digitalentity**
This PR introduces a new flight mode TURN ASSIST that makes copter do Yaw turns on parallel to the ground plane regardless of tilt.

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested this in both ANGLE and RATE - works perfect.

In RATE mode it makes a perfect yaw-stick only turn and maintains attitude. There is slight drift due to not instant response of PID control, but still much easier to pilot for a RATE-mode beginner like myself.

In ANGLE mode it also maked yaw turns much smoother and completely pirouette-less. This is expected as TURN ASSIST introduces feed-forward control in pitch/roll and maintains attitude naturally and without delay making it easier for self-leveling controller.

**Comment by stronnag** [comment]
damn you, I didn't have any out of tree patches. This I must try ....

**Comment by sppnk** [comment]
Does this work in airplanes?

**Comment by digitalentity** [comment]
@stronnag 
I have a strong feeling that TURN_ASSISTANT can be enabled and applied explicitly in ANGLE/HORIZON mode as it makes yaw so much smoother.

@sppnk 
I don't see shy it shouldn't work for classic airplanes, however airplane flight dynamics is a little different and this PR wouldn't do much good anyway. It shouldn't hurt though - I belive it's safe to try it. It wouldn't do a banked turn though, just assist in maintaining current pitch and roll.

**Comment by digitalentity** [comment]
Flew this again today in both angle mode and rate mode. Simply amazing experience. I'm enabling this logic for ANGLE/HORIZON mode explicitly (for MRs only for now, until somebody verifies the code for FWs).
This code should be able to make it into 1.2

**Comment by stronnag** [comment]
I can't say I really liked it in horizon on fast, banked turns. I shall persevere. Maybe it will grow on me.

**Comment by digitalentity** [comment]
@stronnag, what whas the effect you didn't like?

**Comment by stronnag** [comment]
I can't really put my finger on it -- just didn't feel right. I was more concerned with testing out 50+ WP missions at the time. I will try again.

Thank you for reverting the commit; I think that it the best thing until we have some more testing done.

**Comment by oleost** [comment]
@digitalentity hi.

Could you provide a description on how turn assist is ?

I already made an short description in the [overview ](https://github.com/iNavFlight/inav/wiki/Flight-modes) of flight modes `TURN ASSIST	Makes copter do Yaw turns on parallel to the ground plane regardless of tilt`

But could need a better one for this page https://github.com/iNavFlight/inav/wiki/Modes

**Pull request merged**
