### PR TITLE
Matek F405 : add PWM and Servo section to Board documentation

### PR DESCRIPTION
**Pull request by stronnag**
Add information from https://github.com/iNavFlight/inav/issues/2160 in order not to answering the same question again.

### CODE REVIEW

**Comment by digitalentity** [comment]
@stronnag are you going to add anything else to this PR or it can be merged?

**Comment by Pairan** [comment]
@stronnag Ws2812 work well on fixed wing while wired to S5! 

ah, and maybe the note on UART3 should be pointed ONLY to F405 AIO as the F405 OSD doesn't have  the two other pads.

**Comment by stronnag** [comment]
I think it's done now (just clarified the LED wording). It can be merged as soon as Travis is done.

**Comment by Pairan** [comment]
okay :)

**Pull request merged**
