### PR TITLE
Fix non-working IBUS receiver w/o telemetry

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by hali9** [comment]
The idea is to get rx, telemetry, rx and telemetry on this same pin of uart without disconecting/conecting wire on FC.
When exactly this error occurs. 
Can I please diff log ?

**Comment by digitalentity** [comment]
When I don't want telemetry I connect receiver as I normally would - to RX pin - this is how people have it connected on existing setups. Using BIDIR breaks compatibility with existing setups.

**Comment by hali9** [comment]
So You can confirm that it is work on TX pin.
And change it for backward compatybility.

**Comment by digitalentity** [comment]
I didn't test BIDIR, but I don't expect issues.

**Comment by hali9** [comment]
Hmm. I tested it wery well, using software FS-i6:
10ch_Mavlink_MOD_i6_Programmer_V1
_updater_02_19_11_20.zip
fix_updater_03_16_21_33
fix_updater_03_16_21_33_1
with old FS-ia6b and new FS-ia6b (1.6 version).
I fly with it many times.
This is latest wersion what I use to fly currenlty: https://github.com/hali9/inav/tree/combine-ibus-2.
Also tested failsafe when disconnecting wire from FC or RX or telemetry using direct connection and connect by resistor/diode.
I consider that better is using only pin TX than continuous interruption and connection when changing settings. Especially because it often leads to broken connectors.

I also described it in Telemetry.md:
A. For use only IBUS RX connect directly Flysky IBUS-SERVO to FC-UART-TX. In configurator set RX on selected port, set receiver mode to RX_SERIAL and Receiver provider to IBUS.

And in Rx.md

>      
     _______
    /       \                                              /------------\
    | STM32 |-->UART TX-->[Bi-directional @ 115200 baud]-->| Flysky RX  |
    |  uC   |-  UART RX--x[not connected]                  | IBUS-Servo |
    \_______/                                              \------------/

**Comment by digitalentity** [comment]
You have 3 possible use-cases:

1. Existing setup where only IBUS Receiver is used (no telemetry). IBUS Receiver is connected to RX pin.
1. Existing setup where IBUS Receiver is connected to RX pin of one UART and telemetry is connected to another UART.
1. New setup where IBUS sharing is used.

Without this fix first two use-cases will force user to re-wire his setup when upgrading INAV. This is a bad idea.

**Comment by hali9** [comment]
Two month ago ibus telemetry not work on inav: https://github.com/iNavFlight/inav/issues/1190

Your case 1: repin to TX - Once and never again (can use receiver, telemetry and both)
Your case 2: use uart when is connected telemetry it is TX pin (can use receiver, telemetry and both), Uart when is connected IBUS receiver now is free to use.
Your case 3: Noting

My case:
1. Using PPM.
2. Using PPM and telemetry on uart tx.
3. Using IBUS receiver only (Your case 1), I use uart tx.
4. Using IBUS receiver and telemetry both on uart tx.
5. Using IBUS receiver on one uart rx and telemetry on second uart tx (cannot use - I do not have so many ports).

**Comment by digitalentity** [comment]
There are **existing** setups with IBUS receiver connected to RX pin, I'm not going to break compatibility with setups that are working on previos versions unless absolutely necessary.

**Comment by hali9** [comment]
Ok. I give up.
I will not impose anything on anyone.
Thank you for your time.

Follow to this change need update doc.

**Comment by digitalentity** [comment]
@hali9 see https://github.com/iNavFlight/inav/pull/1498 - you'll have the option to get what you want (receiver on TX pin)

**Comment by hali9** [comment]
Look good.
I dont have FS-ia6 (only ia6b).
But I will test it when it will be merge.

**Pull request merged**
