### PR TITLE
Blackbox header modification to save FLASH space.

### PR DESCRIPTION
**Pull request by giacomo892**
Expecialy for F1 target saving 56bytes is not bad at all.

### CODE REVIEW

**Comment by martinbudden** [comment]
I believe that the blackbox viewer software checks the header, so this modification would not work.

**Comment by giacomo892** [comment]
@martinbudden  I've tried it with the viewer and it works. If you want to try just open a random BB TXT file and remove the header, even completely. The files opens perfectly.

**Comment by stronnag** [comment]
Please do not do this:

* Breaks blackbox_decode (and any tools that depend on it).
````
blackbox_decode bblog_2017-05-31182951.TXT 
Couldn't find the header of a flight log in the file 'bblog_2017-05-31182951.TXT', is this the right kind of file?
````
* Somewhat disrespectful to the effort @thenickdude out into blackbox development

**Comment by giacomo892** [comment]
It's very strange. I'll test better tomorrow. 
And of course I don't want to lack of respect to any one. But we can write his name is the comments. Still saving some precious bytes

**Comment by martinbudden** [comment]
There are two points here:
1. If we change the header then we potentially break tools that read blackbox files, and also may make things difficult if we wish to introduce version 3 of the blackbox files.
2. We are removing attribution to the author of blackbox.

I am not in favour of this change.

**Comment by giacomo892** [comment]
Hi! I've done a new pull request hearing suggestions from you all while still saving some bytes.

I've done many other tests an beside the fact I now agree that we need to left some header my tools are able to decode blackbox files without any header in them.

I'm using:

blackbox_decode 
Blackbox flight log decoder by Nicholas Sherlock (Apr  4 2017 10:53:08)

If you pick one random TXT and remove the first two lines header it decodes properly without any sort of issue. @stronnag why are you having this issue?

**Comment by digitalentity** [comment]
In general I'm not in favor of modifying header signature strings. 3-rd party tools may use it to detect blackbox log start and changing this potentially creates incompatibility without giving us much benefit (a few bytes probably doesn't worth it)

**Comment by stronnag** [comment]
So for your proposed changes, random file (you may however recognise the file from https://github.com/stronnag/mwptools/issues/23):
````
$ blackbox_decode
Blackbox flight log decoder by Nicholas Sherlock (Apr  6 2017 20:18:43)
$ perl -pi.bak  -e 's/Blackbox flight data recorder by Nicholas Sherlock/INAV Blackbox/g;' LOG00364.TXT 
$ blackbox_decode LOG00364.TXT
Couldn't find the header of a flight log in the file 'LOG00364.TXT', is this the right kind of file?
$ cp LOG00364.TXT.bak LOG00364.TXT
$ perl -pi.bak  -e 's/Blackbox flight data recorder by Nicholas Sherlock/BB recorder by N. Sherlock/g;' LOG00364.TXT 
$ blackbox_decode LOG00364.TXT
Couldn't find the header of a flight log in the file 'LOG00364.TXT', is this the right kind of file?
$ head -n 2 LOG00364.TXT
H Product:BB recorder by N. Sherlock
H Data version:2
````
You may also care to look at how the `bb-split.rb` tool that rescues your otherwise broken file works (hint: it looks for well known header values).

**Comment by giacomo892** [comment]
Ok. Let's close this. 

blackbox_decode on ubuntu 16.10 and BB explorer on any platform worked well with modified header.

Tried now blackbox_decode and Mint 17 and give your error. Don't really know what to think since the version is really the same.

**Pull request closed without merging**
