### PR TITLE
Version update to 1.7.2

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by stronnag** [comment]
Tested on quads and tricopter (the timer stuff, rather that a 1 bit change in the version number).

**Comment by giacomo892** [comment]
I'll test this on my test quad (F1 ofc) this weekend.

What should I focus on? Motor outputs and serial ports basically? If something is wrong with timer code basically a motor could stop suddently? Or what was changed is timers allocation on various outputs?

**Comment by digitalentity** [comment]
@giacomo892 motor/servo outputs, softserial, ledstrip, pwm/ppm inputs - all this uses timers and could be affected by timer mapping change.

If something is wrong - it won't function right from the start.

**Comment by giacomo892** [comment]
tested NAZE F1 target. At least on QUADX setup all is working as expected. Thanks!

**Comment by stronnag** [comment]
More interesting is the detail:
* RX (serial, PPM)
* use of soft serial
* ESC technology (pwm, one shot)

**Comment by giacomo892** [comment]
Very sorry. Here you are 
PPM input working. I suppose also serial input works since serial ports are working correctly.
Serial is working with telemetry (LTM + MSP)
Softserial is working (at least 1)
ESC: PWM 400Hz old school esc.

**Comment by stronnag** [comment]
Thanks, that confirms options not previously tested (PPM, PWM ESCs).

**Pull request merged**
