### PR TITLE
Support for SPRacingF4NEO

### PR DESCRIPTION
**Pull request by Manawyrm**
I have added support for the SPRacingF4NEO. 
Tested in a quadcopter, GPS works, I2C baro&mag work, SmartPort telemetry works, ADCs for voltage and current work. 

This can be merged now. I'll get the VTX to run properly in another pull request, but thats another larger change.

### CODE REVIEW

**Comment by kabturek** [comment]
F4 doesnt have inverters (and doesn't support software inversion like f3) does spff4neo has inversion circuits on uart5 for s.port ? (its not a simple sbus inverter)

**Comment by Manawyrm** [comment]
@kabturek It works with Cleanflight, so it's most likely not a hardware issue.
I have looked at the UART TX pin with a scope, and there's no data there at all, so I'm most likely missing something like a pin configuration or something with the UARTs...

**Comment by kabturek** [comment]
oh thats interesting! didnt know the board supports direct s.port telemetry.

**Comment by Manawyrm** [comment]
The board is supplied with a cable that you can directly plugin to a FrSky XSR receiver. It's really quite nice. Telemetry and SBUS just work out of the box usually. Thats exactly what I want to have for iNav too :-)

**Comment by Manawyrm** [comment]
I have updated the source code and the tests are now passing. The hardware is working nicely. 
What needs to be done next?

**Comment by digitalentity** [comment]
@Manawyrm In which order should I review and merge this PR and #2471 ?

**Comment by Manawyrm** [comment]
They should be independent. I tried #2471 together with the SPRacingF3NEO board (which is already supported) and it also worked fine.

I'd say to merge this pull request first because it has no dependencies to other code...

**Comment by digitalentity** [comment]
@Manawyrm can you please rebase?

**Comment by Manawyrm** [comment]
Sorry, that this took so long :(

Is this still important for the 1.9 release? or just the 2.0? 
I'd then make sure to very quickly rebase this.

**Comment by sklempert** [comment]
@Manawyrm Since I am currently using a copter based on your changes and the newest development tree, I've created a new pull request #2799 which should save you work here.

**Comment by Manawyrm** [comment]
Thank you very much. I'll close this old pull request.
I have subscribed to the new PR if any questions are open.

**Pull request closed without merging**
