### PR TITLE
Add OSD support for AFNG F7 Horus30 boards

### PR DESCRIPTION
**Pull request by MJ666**
Enable SPI Flash for AFNG F7 Osiris20 boards

### CODE REVIEW

**Comment by MJ666** [comment]
Rebased.

**Comment by MJ666** [comment]
Why moving this to 2.1? This will only affect the AFNG F7 target and adds support for two new boards in this series. One (AFNG F7 Horus30) is already released and the second (AFNG F7 Osiris20) is just in testing and will likely released soon also.

**Comment by fiam** [comment]
@MJ666 This PR had no milestone set. At the time when were about to make the first RC, it had pending conflicts, that's why I set to 2.1. If no one objects, I guess we could merge it for 2.0.

**Comment by MJ666** [comment]
Rebased again.

**Pull request merged**
