### PR TITLE
Airplane launch mode

### PR DESCRIPTION
**Pull request by digitalentity**
As discussed in https://github.com/iNavFlight/inav/issues/655
Will require https://github.com/iNavFlight/inav/pull/658 to be merged first to free up some flash on F1 targets.

Bench tested. Should be safe to flight test. Sequence of operation:
1. Set switch to `NAV LAUNCH` mode prior to arming (note that it won't actually enable until arming)
2. Arm, motor should start spinning at `min_throttle`
3. Verify that motor and control surfaces don't respond to stick motion.
4. Put throttle stick to desired post-launch throttle value
5. Throw the airplane
6. Motors will start at pre-configured `nav_fw_launch_thr` (default 1700) after `nav_fw_launch_motor_delay` (500ms)
7. Launch sequence will finish when pilot switch off the `NAV LAUNCH` mode or move the right stick

Tasks to complete:
- [x] Acceleration-based launch detection + safety tilt limit (45 deg)
- [x] Bungee launch handling (motor stop)
- [x] Visual/buzzer indication of launch mode
- [x] Automatic finishing the launch procedure
- [x] Failsafe compatibility

### CODE REVIEW

**Comment by oleost** [comment]
You already have bungee mode since with adjustable pre launch you can just set nav_fw_launch_thr = 1000

**Comment by oleost** [comment]
Also noticed one other problem. With my taranis and x8r I easily loose connection when the radio and reciever is very close to each other. 

This happenes often when I pick up the plane, so noticed the failsafe aborted the launch mode.

**Comment by digitalentity** [comment]
Actually setting throttle to 1000 won't stop the motors, motor mixer will clip it to min_throttle (1150 default). We need a way to override it for launch.

**Comment by oleost** [comment]
Hmm,  my did not spin. But that's probably because I have min throttle set to 1025.

**Comment by digitalentity** [comment]
I have an idea of refactoring the signalling from navigation to flight control, but that's probably going to be an independent change.

**Comment by oleost** [comment]
@digitalentity Got to do some more testing today, looks like your fix is working, both using right stick, and lowering throttle all the way down disable NAV launch.

Here is blackbox log, video(of 2 part of log and 3 part of log) and cli dump if your intereseted.
Again my prop do not spin up, so its possible to do bungee if you want.

https://drive.google.com/open?id=0B-yHzNtOXxbEWGRObmYwbkpXWXc

When Taranis says "Armed" its the NAV launch thats activated. Im using the auto arm feature so i gets armed when I throttle up.

**Comment by oleost** [comment]
Also not sure if the motor are starting soon enough, but that test will come when you think its ready to to flight test.

An the last attempt (Video marked with 3) it goes alot sideways, I did throw it with the wind, not against so the ailerons did not have much authority.

**Comment by digitalentity** [comment]
In general behaviour is looking good. I've also done a hundred of bench-tests of the code and it looks like it's behaving as expected now. I think it should be safe to flight-test it.

Probably default motor start delay should be much smaller. Half a second is definitely too much, the airplane doesn't have a chance to gain speed and stabilise. What delay do you suggest? 

Relevant CLI parameters:

| Name | Default value | Description |
| --- | --- | --- |
| nav_fw_launch_accel | 1864 = 1.9G | Forward acceleration [cm/s/s] to consider a possible launch |
| nav_fw_launch_detect_time | 40 | Acceleration should be higher than the threshold for this much time to consider it a launch |
| nav_fw_launch_thr | 1700 | Launch throttle |
| nav_fw_launch_motor_delay | 500 | Delay between detecting a launch and starting motors [ms] |
| fw_launch_climb_angle | 10 | Climb angle to maintain during launch [deg] |

Thoughs:
1. Should we set default `nav_fw_launch_thr` to full throttle?
2. Motor start delay should probably be smaller for throw launch. Maybe zero?
   3, Is 10 deg climb too much or too low? I don't have much experience with airplanes to decide.

**Comment by oleost** [comment]
1. Think I'm going to try with 1700-1800 is in throttle.  My plane is best to launch around there. 
2. I think I'm going to set it to zero since my prop is on top away from my hand. But for bungee launching 0.5 is probably fine. 

Okey.  Then I will do an proper test when I get a chance.

**Comment by digitalentity** [comment]
Thanks! Please let me know how it goes. It's not only about perfecting the logic, it's also about finding parameters that will work on most aircrafts.

**Comment by oleost** [comment]
Success!
Tried NAV launch with 100 in delay and 1800 in throttle.

Did have NAV laucnh enabled while walking from car to throw site, so it was a little test that also confirming no false launch.

Video and blackbox log:

https://youtu.be/zQkepdZhuH4

https://drive.google.com/open?id=0B-yHzNtOXxbEX3kzM2RDT3c4dXc

Only thing was RTH was weak with some turns, and the PIDs did feel right, looked more unstabile than its usually is. But I'm not sure. Its been awhile since I flown this airplane. Didnt get a chance to take another test flight without NAV launch as I had to go home.

But does it look like the PIDs are working like regular after I takeoff? (I never manually disabled NAV launch)

**Comment by digitalentity** [comment]
@oleost amazing! I'll update defaults for 100ms motor delay (it's definitely better than 500ms).
EDIT: Can I share the video on Russian INAV thread?

**Comment by oleost** [comment]
@digitalentity Yes of course.

**Comment by oleost** [comment]
@digitalentity So got to do an test today, first with failsafe = RTH.

I hand threw plane with NAV LAUNCH, and it detected launch. I walked a couple of meters and then turned off the TX while still the plane being in launch state. Instead of contuine trying to climb it stopped motor. Also even after I turned on TX again I could not give it any throttle.

Blackbox LOG (The last one) and CLI DUMP
https://drive.google.com/open?id=0B-yHzNtOXxbEX3kzM2RDT3c4dXc

Also noticing the flightmodes says AUTOTUNE ? Have NAV LAUNCH taken autotune old place?

**Comment by digitalentity** [comment]
@oleost thanks, failsafe compatibility has to be dealt with. I think failsafe in LAUNCH mode should simply abort and disarm, there's no point in executing RTH or anything else. What do you think?

**Comment by digitalentity** [comment]
Multiple tests of launch mode on a light (250g) 80cm flying wing - 100% success rate. I even showed off for a few launches and put my TX on the ground while throwing the airplane. Everyone was pretty amazed when I revealed that it's a 9$ CC3D controller doing the launch :smile:

**Comment by oleost** [comment]
@digitalentity I actually did the first try with the transmitter om the ground as you can see from the video 👍

**Comment by oleost** [comment]
@digitalentity Regarding failsafe, I thought about it, not sure what's best. 

If we implement the timers we talked about I agreed that that's probably the best solution. Else it can be in  launch mode pretty far away, and then I rather have RTH kick in

**Comment by digitalentity** [comment]
I don't want to make launch mode too complicated and dependant on GPS/barometer whatever. Let's make a configurable timeout after launch detection (default 5-10 sec) and disable launch mode after that.

**Comment by oleost** [comment]
Great.

Then I can just launch with NAV LAUNCH and RTH enabled so after timeout it will go to RTH

**Comment by digitalentity** [comment]
Not really, Enabled RTH will prevent you from arming.

EDIT: We can, however, allow arming with RTH+LAUNCH mode is enabled.

**Comment by digitalentity** [comment]
As a matter of fact we can allow LAUNCH + RTH and LAUNCH + WP to start automatic mission after launch.

**Comment by oleost** [comment]
Geniusly.

**Comment by digitalentity** [comment]
Did more testing today. Launching a flying wing probably required lower accel threshold - when throwing the airgraft by the wing tip launch mode doesn't always detect a launch. 1.9G forward accel is quite a lot actually, we might want to consider analysing jerk as well...

**Comment by oleost** [comment]
I'm having an Z84 wing on the way. Can do a couple of logs of throwing it if you don't already have it.

**Comment by digitalentity** [comment]
I hope to finish the Z84 by end of this week:

img_20161009_204715

It will be driven by new Air3 FC by MWC and powered by 1500mAh 4S lipo. No FPV before flight-testing, but will eventually have 5.8G FPV. Planned AUW 370g w/o FPV.

**Comment by oleost** [comment]
@digitalentity what nav_fw_launch_accel did you use on your wing? 

Or did the default value work for you?

**Comment by digitalentity** [comment]
@oleost I had to set motor delay to 150ms to keep my fingers safe. Also lowered `nav_fw_launch_accel` to 1863

**Comment by oleost** [comment]
Ok thank you. 

Will try that on my wing and easy trainer as well. 

Looking at my log really quickly the other that,  didn't look like it was above 1.6g while walking around it plane. So we can probably lower the default value to example 1800-1850.

**Comment by digitalentity** [comment]
@oleost new code also limits launch angle to 45 deg, you can drop the airplane tail down and launch won't be detected even if acceleration was over 2g

Also, default PIDs are way over the top for Z-84. Here's what I have now:

```
set gyro_sync = ON
set gyro_sync_denom = 1

set gyro_lpf = 42HZ
set gyro_soft_lpf_hz = 40
set acc_soft_lpf_hz = 15
set dterm_lpf_hz = 30

set nav_fw_launch_accel = 1716
set nav_fw_launch_detect_time = 40
set nav_fw_launch_thr = 1500
set nav_fw_launch_motor_delay = 150
set naw_fw_launch_timeout = 5000
set naw_fw_launch_climb_angle = 10

set p_pitch = 20
set i_pitch = 30
set d_pitch = 15
set p_roll = 25
set i_roll = 30
set d_roll = 15
set p_yaw = 0
set i_yaw = 0
set d_yaw = 0
set p_level = 20
set i_level = 5
set d_level = 75
set max_angle_inclination_rll = 600
set max_angle_inclination_pit = 450

set rc_expo = 40
set tpa_rate = 33
set tpa_breakpoint = 1300
```

**Comment by oleost** [comment]
@digitalentity Could you rebase this? Planning to test this on my spracing f3 mini.

**Comment by digitalentity** [comment]
@oleost rebased. I suggest you also merge #685, tune your PIDs for cruise throttle set the following:

```
set tpa_rate=10 (or any other non-zero number)
set tpa_breakpoint=<cruise_throttle>
```

Really improves handling at wider range of throttle positions. I guess release 1.4 will have to have airspeed sensor support.

**Comment by oleost** [comment]
@digitalentity yes, already  did that

**Comment by digitalentity** [comment]
@oleost I've fixed a few bugs in TPA code today, bench-tested and verified to work properly. I didn't flight-tested anything yet - heavy rain and no humidity protection for electronics yet.

**Comment by oleost** [comment]
@digitalentity Does it care which accelerometer axis the G ar detected on?

Anyway, did a test with my wing today. With the way I launch the wing (holding end of wing and slinging it) it does not detect launch at 1.7g. Looks Like I must below 1.4g.

So set it do 1.35 for now.

The way I have it now is that launch mode is always on, so I just going to hold the wing, arm it and then throw it.
No point in walking around with it armed and in launch mode.  Also 1.35g should be low enough to not go of while just laying on bench and being moved carefully around.

**Comment by digitalentity** [comment]
@oleost it only cares in acceleration in X (forward) direction. I figure when you sling the wing by the wingtip acceleration is much smaller. I think 1.35 should still be safe - you are not expected to move the armed wing aroung anyway,

EDIT: Moreover, launch detection also cares that airplane is more or less level (45 deg margin), so even if you set it to 0.9g it still won't go off by gravity alone.

**Comment by oleost** [comment]
@digitalentity I may think its the 45deg margin that is causing me issues. Tried today I Im still having trouble slinging it.

The lat time in Log 9 I threw it normally. The rest of the times I had to just give it a good spin in my hands without throwing it, so it would arm and start. And then I just slinged it to take off.

https://drive.google.com/open?id=0B-yHzNtOXxbEZGt1RHAycnR4M0E

And sorry for the mess of the logs, but I really dont have to have so many more failed attempts as Im starting to scratch up the airplane.

**Comment by gbine** [comment]
I'd like to start testing this branch, but I cannot figure out how you are setting the mode to NAV LAUNCH.
iNav Configurator doesn't appear to support this mode (it is quite likely that I"ve missed something there), and I've searched the RC Group, and found nothing. 
I did dig into the code (where I discovered the mode is 20) and  tried  aux 1 20 1 1500 2100 in the cli but the cli just ignores it (doesn't save it or even display it before saving)

I would very much appreciate you folks sharing just how you are setting this mode.

**Comment by oleost** [comment]
iNav configurator shows this mode. 

Are you sure that you have downloaded and build this branch?

**Comment by gbine** [comment]
@oleost , Thanks for stating what I should have checked before posting.  I re-cloned the main branch, merged the airplane-launch-detector branch, and updated my configurator (has been a while), and it is now there. 

Now for the weather to co-operate .....

**Comment by gbine** [comment]
Five perfect launches of my SlowStik !  👍  Nice work everyone.  
CC3D with SBuS and Neo6M GPS.  Seems there is still some life left in those older controllers.
All defaults except accelerate is at 1.0 and motor at 1300
Time to try it on my 6ft Calypso powered glider.

**Comment by oleost** [comment]
@digitalentity Great now that 1.3 is out is time to think about this.

Regarding the last check is this pull request. " Failsafe compatibility "

Is there something that needs checked?
If so, if you could rebase / fix conflicts I can help out testing with some testing.

**Comment by digitalentity** [comment]
@oleost rebased. Fixed failsafe. Now if failsafe is triggered during launch idle stage airplane will disarm instead of trying to execute failsafe procedure.

**Comment by gbine** [comment]
Hey folks, a failsafe question..  instead of dis-arming and having the plane come down totally uncontrolled, how about setting it to one of the stabilize modes and killing/disabling the throttle thus allowing it to have its unscheduled landing a little bit softer?  May save some carnage.
Or at least the option to set it to 'land' in the CLI while keeping the default of simply disarm?
You could even take this a little further and while in stab mode, and control the descent angle to the same as the climb out angle, or even add a variable to support this, and possible a future LAND mode ;-)

A little off topic.....
Are there templates for building drivers?  I am very interested in an airspeed/pitot sensor.  I have an analog one the I use on my pixhawk, and would like to see it in use on iNav.  I know that there are only a couple of analog inputs, so I will pick up the digital one if needed, but either way I'd like to take a 'shot' at coding this.
 I think it is the next major fixed wing enhancement that will have a significant benefit for us.

**Comment by digitalentity** [comment]
@gbine emergency landing for airplanes is something we need - see #91. "Disarm on failsafe" is related to pre-launch when motor is stopped or idle. After launch it should be normal failsafe procedure.

**Pull request merged**
