### PR TITLE
Support for Hardware In The Loop simulator in X-Plane 11

### PR DESCRIPTION
**Pull request by RomanLut**
Support for HITL in X-Plane 11: https://github.com/RomanLut/INAV-X-Plane-HITL

~24 bytes of RAM and ~2600 bytes of flash.

### CODE REVIEW

**Comment by sensei-hacker** [comment]
It would be awesome to be able to use Inav in the sim.

**Comment by b14ckyy** [comment]
Fantastic Work! As it is raining today I will give it a try right now. 
One question. the guide says that loop time and FPS are not synced and full simulation can cause IMU discrepancies. Would it help to set the loop time to 60Hz as well as the Sim? Or loop time to something with an integer ratio like 120 or 180Hz?

**Comment by b14ckyy** [comment]
So with a constant vsynced X-Plane at 60fps and default 1000Hz loop time everything works as expected with the full simulated sensors on. I was able to compare default settings AHI drift with my updated settings and see a clear difference the same way as in real craft. 
All in all it works really well.

**Comment by JulioCesarMatias** [comment]
I had tried this before, and I liked it... But, it would be interesting if we could test multirotors too, how can we do that?

**Comment by b14ckyy** [comment]
@JulioCesarMatias I guess someone has to create a Multirotor model. We also need more plane models. The wing works fine but is not maintained anymore and has weird arodynamics. Lot of yaw wiggle. And had to adjust the control surface throws to get some reasonable rates and FF values. But autotune works well. 

The Plane Maker works with tons of shortcut names of variables and a lot of parameters that have to be adjusted but I will try to work myself into it. Maybe I am able to create some craft.

**Comment by MrD-RC** [comment]
Hmmm, how soon can we get this in master!!! @DzikuVx ok with you?

**Comment by RomanLut** [comment]
> Fantastic Work! As it is raining today I will give it a try right now. One question. the guide says that loop time and FPS are not synced and full simulation can cause IMU discrepancies. Would it help to set the loop time to 60Hz as well as the Sim? Or loop time to something with an integer ratio like 120 or 180Hz?

Well situation can be enchanced but will never will be replacement to the real world. 

In real flight, FC is sampling and integrating sensors with high frequency. Each sample is correct(noisy) value.

In simulator, FC is reading constant values which were passed with the last update from simulator. Theese are not values which will be used by simulator to calculate next attitude. In active ACRO flight errors accumulate quickly producing completely broken horizon. I have seen situation where horizon was rotating like a fan, not able to converge :)

Theoretically it could be possible calculate sensor values in FC in a way that they integrate to the next attitude passed from simulator. However at this point it gets too complicated. 

I think current implementation is Ok already to test math, signs and scales, to check ideas like this https://github.com/iNavFlight/inav/pull/4371

and perfect for checking issues not realted to IMU like this https://github.com/iNavFlight/inav/pull/8228

**Comment by RomanLut** [comment]
> I had tried this before, and I liked it... But, it would be interesting if we could test multirotors too, how can we do that?

X-Plane airflow simulation is not good for qudcopters, and for small planes too unfortunatelly :(
Aslo note that sensors update rate can not be faster than X-plane FPS.

Anyway, if someone wants to try it, here is some information:
https://github.com/RomanLut/INAV-X-Plane-HITL/issues/7

**Comment by RomanLut** [comment]
> The wing works fine but is not maintained anymore and has weird arodynamics. Lot of yaw wiggle. And had to adjust the control surface throws to get some reasonable rates and FF values. But autotune works well.

Unfortunatelly X-Plane physics simulation was not designed for small planes. The author of "fpv surfwing" had to do some tweaking to make it flight Ok. This is the best RC plane model I was able to find. I was not able to find any freeware classic RC plane models.

You may try FX-61
[FX-61.zip](https://github.com/iNavFlight/inav/files/9227010/FX-61.zip)

**Comment by b14ckyy** [comment]
@RomanLut I tried the FX-61. It is unfortunately completely broken. AHI is all over the place when enabling sensors and altitude and speed show insane numbers. like 1000kph+ in the osd xD

there is also this fixed wing drone thing with inverted V-Tail but there the controls are messed up. Might be fixable though

**Comment by b14ckyy** [comment]
@RomanLut Do you think the Firmware Side is in a state ready to merge? I talked to @MrD-RC and he agreed that we should merge the PR into the master for 6.0 asap, to simplify testing of new features. 

from my intensive testing the last 2 days with a few hours of virtual flight time, it works very well.

**Comment by RomanLut** [comment]
Yes firmware side is ready. And I think I will not be adding more features to plugin too. 

I was testing it for 2 weeks on Windows and [sevrugin](https://github.com/sevrugin) was testing it on linux.

**Comment by b14ckyy** [comment]
The only things I miss are Airspeed sensor simulation and maybe lidar for AGL altitude measurements to test more programming stuff. Although lidar is a bit far-fetched, do you think Airspeed is possible? maybe with a later release?

**Comment by RomanLut** [comment]
1)  I did not add airspeed sensor because INAV does not use it. I can add if we have some features to test.
If you just want to see some numbers on OSD, you can choose VIRTUAL  airspeed sensor. It will display ground speed + wind estimator speed. Beware that VIRTUAL airspeed sensor code is not included on 411 and 722 by default - you will not be able to arm).  Add #define USE_PITOT_VIRTUAL.

2) Adding lidar(rangefinder) is possible - it is possible to query terrain elevation in plugin. Not possible to query Scenery height though. However, I do not know how lidar should function. Do we have use case for lidar? I would need complete description for the task.

**Comment by RomanLut** [comment]
I have a question what is https://github.com/iNavFlight/inav/blob/master/src/main/flight/hil.h?

Is this some obsolete code?

**Comment by JulioCesarMatias** [comment]
> 1. I did not add airspeed sensor because INAV does not use it. I can add if we have some features to test.
>    If you just want to see some numbers on OSD, you can choose VIRTUAL  airspeed sensor. It will display ground speed + wind estimator speed. Beware that VIRTUAL airspeed sensor code is not included on 411 and 722 by default - you will not be able to arm).  Add #define USE_PITOT_VIRTUAL.
> 2. Adding lidar(rangefinder) is possible - it is possible to query terrain elevation in plugin. Not possible to query Scenery height though. However, I do not know how lidar should function. Do we have use case for lidar? I would need complete description for the task.

Leave the Real Pitot Tube data available on the MSP, leave it in a commented line, it will be useful in the future!

This PR is really good, but not being able to test multirotors is really bad.

**Comment by JulioCesarMatias** [comment]
> I have a question what is https://github.com/iNavFlight/inav/blob/master/src/main/flight/hil.h?
> 
> Is this some obsolete code?

yes, obsolete

**Comment by RomanLut** [comment]
Ok, I implemented pitot emulation and added to PR.
I will release new plugin tomorrow.

**Comment by JulioCesarMatias** [comment]
I think we should include this in the release note

**Comment by b14ckyy** [comment]
Pitot tube is helpful in the future indeed but also currently as I am working on a logic function program to have a throttle loop control based on airspeed. I  hesitated to do that on a real plane initially due to risk of stall with bad settings but with the HITL this would be easy peasy to test and adjust. So I can have a baseline for an airspeed controlled throttle program. 

Lidar is also availale in programming and can be used to make a autoland program that is more reliable than the current system. Although this has low priority as it would still be a blind landing currently until short before touchdown. 

So Pitot is the most important one from my point of view and would be a great addition.

**Comment by MrD-RC** [comment]
Following on from @JulioCesarMatias comment on release notes. I also think a small md file in the docs folder with setup instructions would be handy.

**Comment by RomanLut** [comment]
Released plugin v1.0 with Pipot simulation https://github.com/RomanLut/INAV-X-Plane-HITL/blob/main/README.md#pitot

**Comment by JulioCesarMatias** [comment]
> Following on from @JulioCesarMatias comment on release notes. I also think a small md file in the docs folder with setup instructions would be handy.

Oh yeah! A document with all the necessary instructions is perfect!

**Comment by b14ckyy** [comment]
I just found a little issue. If Compass is disabled in INAV (set to NONE) it is still emulated by the plugin when connected. I can see it active when I shut down X-Plane and connect with the configurator without reboot. 

Pitot works great btw! Now I can play with that as well.

**Comment by RomanLut** [comment]
> I just found a little issue. If Compass is disabled in INAV (set to NONE) it is still emulated by the plugin when connected. I can see it active when I shut down X-Plane and connect with the configurator without reboot.

Fixed, this was configurator display issue only.

**Comment by b14ckyy** [comment]
@RomanLut I played around a bit with the Telemetry viewer app, and something catches my attention. 
In the telemetry even with compass disabled, INAV still knows the true heading of the craft. But without compass in reality INAV uses the course heading only and does not know the nose orientation. This makes it impossible to simulate plane behavior in strong headwinds with no compass installed. 

is it possible to change the plugin so INAV only receives course heading instead of true heading if compass is disabled? Like in reality?

**Comment by RomanLut** [comment]
Updated plugin. GPS data contains ground course heading now.
Disable compass, set Attitude to "estimation" => inav will estimate yaw from ground course heading.
In "Attitude: set from x-plane" attitude yaw is set to true heading.

**Comment by breadoven** [comment]
Didn't really appreciate what this did but now I've got it working it is indeed an awesome bit of work, Will make testing changes so much easier and risk free. Can finally test all those emergency/failsafe functions properly not worrying about it ending in a crash.

**Comment by b14ckyy** [comment]
@RomanLut I think we all can't thank you enough for this! It gets even more impressive if you compare a real flight with a simulated one and it is basically identical 
image

**Comment by JulioCesarMatias** [comment]
@MrD-RC @b14ckyy Do we have anything else to add here? Or is this *Ready To Merge*?

**Comment by MrD-RC** [comment]
The docs on @RomanLut 's repo are great. So if the .md pointed at those, it would be great. 

The only other thing I'd like to see is the ability to define the preset options. It's a bit of a pain having to turn off the VTx simulator every time. But it's only a minor annoyance on an excellent feature.

**Comment by b14ckyy** [comment]
> @MrD-RC @b14ckyy Do we have anything else to add here? Or is this _Ready To Merge_?

i used it nearly every day since 2 weeks now and since your last change with the heading, I miss nothing. (I guess course heading instead of plane hatting with X-Plane pure attitude mode is not possible anyway). 
So for me this is 100% usable and easy to set up. 
When this is merged I will get a X-Plane license end of the month after my holidays and start working with the Plane Maker. This tool is a Usability disaster but I guess the only thing we have to make planes.

**Comment by JulioCesarMatias** [comment]
> The docs on @RomanLut 's repo are great. So if the .md pointed at those, it would be fine.
> 
> The only other thing I'd like to see is the ability to define the preset options. It's a bit of a pain having to turn off the VTx simulator every time. But it's only a minor annoyance on an excellent feature.

@RomanLut what can you do for the VTX?

**Comment by b14ckyy** [comment]
The Simulator Default settings are on the plugin side. So That can be maintained later. For the INAV code side I guess its fine to merge.

**Comment by JulioCesarMatias** [comment]
Something is broken with the Acc/Gyro used in AHRS. When I use "Attitude" type "Estimated from sensors", my aircraft goes crazy, and can't maintain Attitude correctly. So the only option left is to use the Attitude estimate made by XPlane. What can you say about it @RomanLut ?

**Comment by RomanLut** [comment]
> Something is broken with the Acc/Gyro used in AHRS. When I use "Attitude" type "Estimated from sensors", my aircraft goes crazy, and can't maintain Attitude correctly. So the only option left is to use the Attitude estimate made by XPlane. What can you say about it @RomanLut ?

In real flight, FC is sampling and integrating sensor values with high frequency(400Hz?). Each sample is correct(noisy) value.
In simulator, FC is reading constant values which were passed with the last update from simulator(60Hz?). 
When plane is accelerating or turning, AH is estimated from Angular speed values only. Errors accumulate quickly producing horizon drift. I do not know how to improve it.

**Comment by RomanLut** [comment]
Added documentation.

**Comment by b14ckyy** [comment]
@JulioCesarMatias 
to be able to use the Sensor estimation, you have to make sure your FPS stays absolute consistent. 
Reduce graphic settings and enable VSYNC. If your monitor has 60Hz then make sure the Sim runs at constant 60fps with no fps fluctuations. 

the fluctuations in FPS and therefore inconsistent sensor data will fuck up the position estimator isntantly. Even a short stutter can be enough. 

And from ground always launch with X-Plane attitude first and only switch to sensor estimation after being airborne. The collision system witht he ground is unstable and messes with the Pos Estimator as well.

**Comment by JulioCesarMatias** [comment]
There should be a way to synchronize the XPlane with the PID task?

**Comment by RomanLut** [comment]
> The Simulator Default settings are on the plugin side. So That can be maintained later. For the INAV code side I guess its fine to merge.

Updated plugin is preserving menu selections now.

**Comment by MrD-RC** [comment]
Legend!

**Pull request merged**
