### PR TITLE
add aocodarcf722mini target variant

### PR DESCRIPTION
**Pull request by dlt2018**
add aocodarcf722mini target

### CODE REVIEW

**Comment by AlksSAV** [comment]
The servo outputs do not work, only the motors.

**Comment by dlt2018** [comment]
hello AlksSAV,  you have tested the old board, There are some conflicts in timer and DMA, so i repalced PB3 and PA15 with PC8 and PC9. it can work as motor and servo.

> The servo outputs do not work, only the motors.

**Comment by AlksSAV** [comment]
> hello AlksSAV,  you have tested the old board, There are some conflicts in timer and DMA, so i repalced PB3 and PA15 with PC8 and PC9. it can work as motor and servo.
> 
> 
> 
> > The servo outputs do not work, only the motors.
> 
> 
> 
> 

Do you have a ready-made firmware file?

**Comment by DzikuVx** [comment]
Please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

As this is a new target, this PR will not be merged if all the conditions from this document are not met

**Comment by Ultraexpert** [comment]
Ok looks like we need to send some hardware to the core developer.

**Comment by sensei-hacker** [comment]
FYI I have flight tested this with no problems.

Hopefully Mark has followed:
https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by Ultraexpert** [comment]
Just tested new firmware for 6.0rc3 and doesn't work for me at all. No motor response or servos.

**Comment by sensei-hacker** [comment]
@Ultraexpert  If you want to head over to the INAV Discord I'd be glad to give you a hand getting it working for you.

**Pull request closed without merging**
