### PR TITLE
Nav course hold yaw stick control improvement for fixed wing

### PR DESCRIPTION
**Pull request by breadoven**
Fixes an issue when using the yaw stick to alter course during Nav course hold on fixed wing where the plane reverses the turn direction during adjustment. This is caused by the desired course adjusting faster than the plane can turn until the heading error gets close to 180 degrees causing a turn reversal. PR fixes this by limiting the max allowed heading error. Limiting the heading error to the demanded turn rate works well, not only preventing the turn reversal but also making adjustment more proportional to yaw stick movement. 

Change also sets the desired course to the current course over ground and also resets the position controller when adjustment is finished. This helps to prevent course adjustment overshoot when the yaw stick is released so the new course aligns better with the direction the plane was pointing when the yaw stick was released.

Tested OK on HITL but needs more testing for different plane types . Also needs testing on multirotor.

### CODE REVIEW

**Comment by Jetrell** [comment]
I haven't flown with a rudder yaw controlled plane for a while.. I like the control twin tractor prop planes provide, from using differential thrust. Both for manual stick control and navigation `nav_use_fw_yaw_control`.
But I'll give this a try when we get some good weather.

I generally fly in Cruise more than Course Hold.. I assume it should work the same for both ?

I've always noticed the yaw stick input in Cruise mode is very sluggish, compared to Acro, regardless of `nav_cruise_yaw_rate`.
But the effect that shows up much worse in Cruise mode, compared to Acro or WP crosswind tracking.. Is adverse roll coupling when stick differential yaw is applied.
The Angle based stabilization doesn't re-level the roll axis after the yaw stick is released.. I always forget to look at the logs. And wasn't sure if the effect is derived from bad WindEstimation VELNED and TURNRATE logic feeding into the AHRS. Making it think the Yaw offset was caused by the wind, instead of a stick command, and causing horizon drift.

**Comment by breadoven** [comment]
> I haven't flown with a rudder yaw controlled plane for a while.. I like the control twin tractor prop planes provide, from using differential thrust. Both for manual stick control and navigation `nav_use_fw_yaw_control`. But I'll give this a try when we get some good weather.
> 
> I generally fly in Cruise more than Course Hold.. I assume it should work the same for both ?

Cruise is just Course hold with Altitude hold also enabled so this works for both. And it doesn't need a rudder controlled plane. The yaw stick just demands a course change which uses roll mainly to change direction, with turn assistance if rudder is available.

> I've always noticed the yaw stick input in Cruise mode is very sluggish, compared to Acro, regardless of `nav_cruise_yaw_rate`. But the effect that shows up much worse in Cruise mode, compared to Acro or WP crosswind tracking.. Is adverse roll coupling when stick differential yaw is applied. The Angle based stabilization doesn't re-level the roll axis after the yaw stick is released.. I always forget to look at the logs. And wasn't sure if the effect is derived from bad WindEstimation VELNED and TURNRATE logic feeding into the AHRS. Making it think the Yaw offset was caused by the wind, instead of a stick command, and causing horizon drift.

I quite like the yaw stick control from a smoothness point of view ... once it actually starts to react. But as you say it's sluggish initially (it then over reacts once it gets going). It's also sluggish to stop the turn when you release the yaw stick causing it to over turn making it difficult to judge when you need to stop turning in order to end up pointing in the direction you want. This change makes the over control problem much better.

The reason the roll axis doesn't doesn't level after the Yaw stick is released appears to be because of the PID controller. It takes a long time to unwind after the course adjustment ends. I noticed that the position controller is reset after adjusting using the Roll stick which results in a much quicker return to level flight after the Roll stick is released. If you do the same after using the Yaw stick for adjustment you get to same quick return to level flight. Makes it much easier to release the stick when you're pointing where you want to go and actually end up heading in that direction. Seems to work much better testing in HITL. The plane actually responds to the Yaw stick movements as you'd expect rather than feeling disconnected.

**Comment by breadoven** [comment]
Did you get to test this @Jetrell ?

**Comment by breadoven** [comment]
Flight tested this recently on fixed wing and it's a big improvement on before. Also tested on multirotor OK so should be good to merge.

**Comment by Jetrell** [comment]
No sorry. The weather has been that miserable, I haven't flown in over a month.

**Comment by Jetrell** [comment]
> Flight tested this recently on fixed wing and it's a big improvement on before. Also tested on multirotor OK so should be good to merge.

I agree. Its a big improvement. VERY nice fix.. 
Thinking back, I can't remember a time when it did correctly work like it does now.

**Pull request merged**
