### PR TITLE
Match F745 and F745NANO motor pins to BF target

### LINKED ISSUE #9899: [Target Bug] FlywooF745Nano - Wrong Motor Resource.
## Current Behavior

- Critical: The motor on pin C09 is not the correct pin for the FC to ESC stack connector - making this target useless.
- Nice to have: All of the motors have the wrong assignment, which also makes it annoying.

## Steps to Reproduce

1. Flash the FlywooF745nano target on an F745 nano FC
2. Test Motors
3. Motor on pin C09 does not spin because it is actually on pin E09 (see below)

cli motor resources from iNav:
B00: MOTOR3 OUT
B01: MOTOR1 OUT
**C09: MOTOR2 OUT <- Wrong pin**
E11: MOTOR4 OUT

## Expected behavior
All motors should spin

## Suggested solution(s)

1. Correct the motor resources to the following pins (as confirmed in the working BF target and tested by me):

resource MOTOR 1 B00
resource MOTOR 2 B01
**resource MOTOR 3 E09 <- the motor on C09 needs to be on E09**  (perhaps this was a typo?)
resource MOTOR 4 E11

## Additional context
For reference, here is the correct resource assignments from BF:
resource BEEPER 1 D15
resource MOTOR 1 B00
resource MOTOR 2 B01
resource MOTOR 3 E09
resource MOTOR 4 E11
resource MOTOR 5 C09
resource MOTOR 6 A03
resource MOTOR 7 B04
resource MOTOR 8 B05
resource LED_STRIP 1 D12
resource SERIAL_TX 1 A09
resource SERIAL_TX 2 D05
resource SERIAL_TX 3 D08
resource SERIAL_TX 4 A00
resource SERIAL_TX 5 C12
resource SERIAL_TX 6 C06
resource SERIAL_TX 7 E08
resource SERIAL_RX 1 A10
resource SERIAL_RX 2 D06
resource SERIAL_RX 3 D09
resource SERIAL_RX 4 A01
resource SERIAL_RX 5 D02
resource SERIAL_RX 6 C07
resource SERIAL_RX 7 E07
resource I2C_SCL 1 B06
resource I2C_SCL 2 B10
resource I2C_SDA 1 B07
resource I2C_SDA 2 B11
resource LED 1 A02
resource SPI_SCK 1 A05
resource SPI_SCK 2 B13
resource SPI_SCK 4 E02
resource SPI_SDI 1 A06
resource SPI_SDI 2 B14
resource SPI_SDI 4 E05
resource SPI_SDO 1 A07
resource SPI_SDO 2 B15
resource SPI_SDO 4 E06
resource ADC_BATT 1 C03
resource ADC_RSSI 1 C05
resource ADC_CURR 1 C02
resource PINIO 1 C00
resource FLASH_CS 1 A04
resource OSD_CS 1 B12
resource GYRO_EXTI 1 E01
resource GYRO_CS 1 E04
resource USB_DETECT 1 A08

---

- FC Board name and vendor:
- INAV version string:
version
INAV/FLYWOOF745NANO 7.1.0 Mar 27 2024 / 13:03:13 (59a6ee61)
GCC-10.3.1 20210824 (release)

### PR DESCRIPTION
**Pull request by mmosca**
INAV was using same motor pins for both variants.

This PR matches motor pins to BF.
Fixes #9899 

I don't own this fc, so can't verify the fix.

### CODE REVIEW

**Comment by wernerterreb** [comment]
Actually I was playing with this myself last night and  managed to get the motor assignment correct.   When I go to Outputs and spin the motors now, it is the correct motors that spin for all four.   But my pin assignment looks very differnt to what you committed:

Here is what I used:
This will work on a FlyWoo Explorer LR that has a FLYWOOF745NANO board.

Add this to the file /src/main/target/FLYWOOF745/target.c:

timerHardware_t timerHardware[] = {

   DEF_TIM(TIM8, CH2N, PB0,  TIM_USE_OUTPUT_AUTO,    0, 0),  // M1 , TCH_TMR8_CH2N       
   DEF_TIM(TIM8, CH3N, PB1,  TIM_USE_OUTPUT_AUTO,    0, 0),  // M2 , TCH_TMR8_CH3N       
   DEF_TIM(TIM1, CH1, PE9,   TIM_USE_OUTPUT_AUTO,    0, 1),  // M3 , TCH_TMR1_CH1DMA2_ST1        
   DEF_TIM(TIM1, CH2, PE11,  TIM_USE_OUTPUT_AUTO,    0, 1),  // M4 , TCH_TMR1_CH2

**Comment by wterreb** [comment]
Further feedback..   I tested with your settings as well, and your motor mapping is also correct and the correct motors spin as expected.   

I will definitely do  test flight with this.    Thank you very much for this commit.    

By the way I am the same user as @wernerterreb  above....  just logged in with a different account now.

**Comment by mmosca** [comment]
> Further feedback.. I tested with your settings as well, and your motor mapping is also correct and the correct motors spin as expected.
> 
> I will definitely do test flight with this. Thank you very much for this commit.
> 
> By the way I am the same user as @wernerterreb above.... just logged in with a different account now.

If you get all sensors and uarts working, it should fly correctly now as well.

The change was only to the motor outputs and will be included in 7.1.1 once it comes out.

**Comment by wernerterreb** [comment]
@mmosca thank you very much.  Yeah I still need to sort out the magnetometer, but everything else seems to be working well now.   I will be doing some test flying over the weekend.

**Comment by wernerterreb** [comment]
And I can confirm now it flies perfectly with these changes.

**Comment by wterreb** [comment]
https://www.youtube.com/watch?v=OQNL2s2Giak

**Comment by ramiss** [comment]
I just installed a fresh 7.1.2 stable and Motor 2 is not working just as before? Was this merged into master?

**Comment by ramiss** [comment]
Just learned this is in 8.0 pre-release. thanks all!

**Comment by ramiss** [comment]
Tested and confirmed fixed in nightly 8.0.0.
Thank you all!

**Pull request merged**
