### PR TITLE
Different approach to position controller logic

### PR DESCRIPTION
**Pull request by digitalentity**
Remove jerk limiting. Apply position control expo curve differently - should allow more aggressive tuning of position controller while having it smoother in "hold".

### CODE REVIEW

**Comment by digitalentity** [comment]
Should greatly improve deceleration performance. Testers welcome.

**Comment by oleost** [comment]
Is this a continuations of #254  ?

**Comment by digitalentity** [comment]
Not really, it's a re-thinking how position controller functions.

**Comment by oleost** [comment]
But aims at improving the same thing?

**Comment by digitalentity** [comment]
Yes and no. This PR includes some change to the position control math itself, but the most important part is a separate stage for deceleration (when releasing the sticks or activating PosHold).

**Comment by oleost** [comment]
Ok, good news

**Comment by digitalentity** [comment]
I tested the first part of the code and did notice some improvement, but the second part (deceleration) was not tested yet.

**Comment by stronnag** [comment]
There's some flight logs at  http://seyrsnys.myzen.co.uk/de-pos-contr-mods/ (420mm quad)
`# INAV/OMNIBUS 1.6.3 Apr 11 2017 / 12:50:26 (ee38924a)`

| Log  | Purpose |
| ------- | ------------- |
|   [LOG0006.TXT](http://seyrsnys.myzen.co.uk/de-pos-contr-mods/LOG00006.TXT) | High speed RTH entry |
| [LOG0007.TXT](http://seyrsnys.myzen.co.uk/de-pos-contr-mods/LOG00007.TXT) | High speed PH entry (c. 12 m/s) |
| [LOG0008.TXT](http://seyrsnys.myzen.co.uk/de-pos-contr-mods/LOG00008.TXT) | Waypoints |
| [LOG0009.TXT](http://seyrsnys.myzen.co.uk/de-pos-contr-mods/LOG00009.TXT) | PH and RTH (???) |
| [LOG0011.TXT](http://seyrsnys.myzen.co.uk/de-pos-contr-mods/LOG00011.TXT) | PH and RTH (preset notch) |

No notch filters on the initial set of logs; I'm become doubtful that notch filters really help navigation modes. Visually at least, they seem more prone to encourage toilet-bowling; or may be it's an illusion (or I need to actually tune them rather than just taking the preset defaults).

**Comment by stronnag** [comment]
Flew this branch on the precious tricopter today. Works well for me (WP, PH, RTH).

**Comment by digitalentity** [comment]
Thanks @stronnag. I have some oddities with this PR, I'll put it on hold for a while until I test it more and figure out if it's related to the code or the machine.

**Comment by stronnag** [comment]
Anything in particular? I intend to fly it again later today (on the 250mm this time).

**Comment by digitalentity** [comment]
I have a feeling that it's more prone to fall into toilet-bowling, but I'm not sure.

**Comment by digitalentity** [comment]
Previous version was rock solid when doing multiple rapid yaw rotations in PosHold. This version on the same settings looses hold of position and starts to do circles. I did the tests on different days though - might be something external.

**Pull request closed without merging**
