### PR TITLE
add DSHOT settings to cli documentation

### PR DESCRIPTION
**Pull request by Kurtoid**

### CODE REVIEW

**Comment by Kurtoid** [comment]
Keep the {150,300,600} style list or list out all of the DSHOT150,DSHOT300 etc variants?

**Comment by DzikuVx** [comment]
@Kurtoid I think a full list would be more understandable

**Comment by Kurtoid** [comment]
Also, is there a way to prevent a travis rebuild for a small documentation update?

**Review by DzikuVx — APPROVED** [review]

**Comment by DzikuVx** [comment]
Thanks a lot

**Pull request merged**
