### PR TITLE
h7: enable swd pins

### PR DESCRIPTION
**Pull request by bkleiner**

### CODE REVIEW

**Comment by 0crap** [comment]
I hate it when the description field is left empty.

Can you please explain why this is needed?
(I'm using an expensive MATEKH743 flight controller.)

**Comment by bkleiner** [comment]
it prevents the swd pins from having their functionality overwritten and if you don't know what that is or why it might be useful, this change will be of no consequence to you.

**Comment by 0crap** [comment]
Thx.
If it is of no consequence I try to grab from the description, because I'm not a coder.
(But main devs also often leave the description empty, so I understand why others don't take the effort.)

**Comment by bkleiner** [comment]
well that is a bit of a "depends", for simple changes without any user impact quite often the title and the commit messages are plenty for other developers to understand whats being changed. i would only repeat myself in the description.

**Pull request merged**
