### PR TITLE
H743 6m6s

### PR DESCRIPTION
**Pull request by stronnag**
Following discussion in #7245, it appears that a 6 motor / 6 servo target for MatekH743 would be a good option for both MR and FW.

Awaiting FW servo testing  via #7245 (don't merge).

### CODE REVIEW

**Comment by DzikuVx** [comment]
@stronnag I wonder if we can't just assign MOTOR | SERVO on S7 and S8. Then extra target would not be required

**Comment by stronnag** [comment]
I did wonder about the best way to make this more flexible. 10+2 either way seemed a bit restrictive for such a powerful FC.

* I also dislike adding new targets for "variations on a theme"
* I rejected your suggestion as it would violate the unwritten "don't mix motors and servos on the same timer"

But I have no firm view on this, it's more for the the compiler challenged. 

Maybe we will get some more views on what users would actually find useful (the initial requirement was FW, 4M, 5S).

**Comment by stronnag** [comment]
My prediction: we will end up with 10+2/2+10, 4+8/8+4, 6+6 options once users discover the potential of the hardware.

**Comment by MATEKSYS** [comment]
I don't think it's necessary to add a variation for very few applications.  2 motors PWM outputs are enough for 4 motors Airplane.

**Comment by stronnag** [comment]
The user's specific requirement was for four motors, but as you wish.
I'll  close this.

**Comment by salukikev** [comment]
> I don't think it's necessary to add a variation for very few applications. 2 motors PWM outputs are enough for 4 motors Airplane.

Just wanted to chime in here that my MR build would definitely benefit from (at least) 6 motor outputs, and the more PWM servo outputs the better.  6 would be great!

**Pull request closed without merging**
