### PR TITLE
Port Betaflight FPV camera tilt compensation for ACRO mode

### PR DESCRIPTION
**Pull request by digitalentity**
#3028

### CODE REVIEW

**Comment by fiam** [comment]
Can we merge this one for 2.0?

**Comment by digitalentity** [comment]
Yes, but I'll have to rebase first

**Comment by putimir** [comment]
Hi, do you plan to merge this into final 2.0.0 release? Thanks

**Comment by digitalentity** [comment]
Nobody actually tested it.

**Comment by ABLomas** [comment]
If only testing is required - no prob., i can do this. Or this needs something more before integration into mainline?

**Comment by digitalentity** [comment]
@ABLomas it was never tested. If it will work properly - it could be merged

**Comment by ABLomas** [comment]
If someone could make OMNIBUS F4 hex - i can test it ASAP!

**Comment by digitalentity** [comment]
Here you are [inav_2.1.0_OMNIBUSF4.zip](https://github.com/iNavFlight/inav/files/2707572/inav_2.1.0_OMNIBUSF4.zip)

**Comment by ABLomas** [comment]
Tested fpv_angle_mix today - 25° mix, using hex i got on Telegram (incl. dshot).
I think it's working properly.
I betaflight i can put that mix on switch, so it's easy to show difference using video, here it's fixed (i think it's ok - not much use from fpv_angle_mix on switch). I did not noticed "additional roll" using 180° turns.
It's raining and bad weather overall so i tested in forest at low speed. I think i can re-test with 45° angle at higher speeds in next weekend, but so far - at least it flies and does not add any unexpected effects (yaw jumping is incredible after betaflight, but all that antigravity stuff, yaw_d damping on BF is doing good job, AFAIK nothing that available on INAV so i will just need to re-train my fingers a bit - yaw jumps are probably unrelated to fpv_angle_mix).

**Comment by ABLomas** [comment]
After another testing i would like to add note, that i think there is something wrong with mixing.
Aircraft is controllable (i flew **19km** in forest, avoiding branches, so everything is fine with control), i did not noticed any side-effects, but yaw-roll mixing is not correct, i think. There is strange drift to side from yaw, which is not noticeable in BF.
Too bad, rain started and i could not finish all tests, i hope that i can retry at weekend and describe issue together with video.
Also code could stay even in release, as there seems to be just minor issue with scaling or calculations and won't break flying (if there is, at all - maybe this is related to different tunning on BF/INAV - requires testing in a lot of open space).

**Comment by ABLomas** [comment]
I repeated test in open space, incl. inverted S and so on.
No issues, everything seems to work well. My previous comment about scaling was probably caused by slightly misaligned camera.
This time i did not noticed any difference from BF fpv_angle_mix, everything works well and fine.

Thanks for this important feature! =)

**Comment by digitalentity** [comment]
Yep, I've tested it as well. If set up according to actual camera uptilt - no issues, very smooth and natural flying. We should have ported this thing long ago 😄

**Pull request merged**
