### PR TITLE
Remove mid_rc setting

### PR DESCRIPTION
**Pull request by digitalentity**
Solves https://github.com/iNavFlight/inav/issues/3313
@DzikuVx @fiam @shellixyz @stronnag ?

### CODE REVIEW

**Comment by shellixyz** [comment]
Looking good to me I don't see any case where changing `mid_rc` could be useful. All radios have stick center value at 1500µs right ?

**Comment by digitalentity** [comment]
Not all radios produce valus in [1000;2000] range with 1500 mid (i.e. Spektrum), but we have `rxrange` to account for that.

**Comment by fiam** [comment]
We need to remove it from the configurator too.

**Comment by stronnag** [comment]
and here ... or mark unused
```
%% sbus_channels.c 
./src/main/rx/sbus_channels.c: In function 'sbusChannelsInit':
./src/main/rx/sbus_channels.c:87:41: warning: unused parameter 'rxConfig' [-Wunused-parameter]
 void sbusChannelsInit(const rxConfig_t *rxConfig, rxRuntimeConfig_t *rxRuntimeConfig)
                       ~~~~~~~~~~~~~~~~~~^~~~~~~~
```

**Comment by NeilGaede** [comment]
mid_rc is still needed as a reference when using use_midthr_for althold = 1. Needs to be changed to use mid_rc, not mid_thr since that is an expo weighting center value.

**Comment by digitalentity** [comment]
Using throttle expo center as a zero point for althold makes more sense
than using some arbitrary number. Please adjust your throttle expo center
and you'll solve your issue.

**Comment by MRC3742** [comment]
@digitalentity This issue seems to be related to this PR. While building in Linux Mint from current development branch I am encountering the following error midway through the build that terminates the process. 

%% rc_modes.c 
%% runtime_config.c 
%% settings.c 
In file included from ./src/main/fc/settings.c:11:0:
./src/main/fc/settings_generated.c:751:85: error: 'rxConfig_t {aka struct rxConfig_s}' has no member named 'midrc'
  { {115, 38, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {62, 64}, offsetof(rxConfig_t, midrc) },
                                                                                     ^~~~~~~~~~~~~~~~~~
Makefile:337: recipe for target 'obj/main/SPRACINGF3EVO/fc/settings.o' failed
make: *** [obj/main/SPRACINGF3EVO/fc/settings.o] Error 1


Commenting out line 751 in file ./src/main/fc/settings_generated.c "// { {115, 38, 0, 0, 0}, VAR_UINT16 | MASTER_VALUE, .config.minmax.indexes = {62, 64}, offsetof(rxConfig_t, midrc) },"
will let the build complete successfully. Could this have been overlooked  when removing the mid_rc setting? or is there something wrong in the way I am building it?

**Comment by stronnag** [comment]
It's the way you're building it. Development builds fine. It's more likely due to that fact that the location of the generated files has changed, and you have an old file lying around. 

Running:
```
find . -iname settings_generated.[ch] -delete 
```
will probably resolve the situation.

**Comment by MRC3742** [comment]
@ stonnag You are correct. Removing that file allows the build to complete with no errors. Thank You!

**Pull request merged**
