### PR TITLE
Rename NAV CRUISE mode to NAV COURSE HOLD

### PR DESCRIPTION
**Pull request by shellixyz**
Suggested by Matey HV

CRUISE 2D -> COURSE HOLD, displayed on the OSD as "CRSH"
CRUISE 3D -> simply CRUISE, displayed on the OSD as "CRUZ"

More logical

### CODE REVIEW

**Comment by snaewe** [comment]
Am I the only one ready 'CRSH' as CRASH ? Just wondering...

**Comment by Mateyhv** [comment]
Lol, yes thats not doing a very optimistic abbreviation :-). I would rather stick with CRS for course and CRZ for cruise.

**Comment by shellixyz** [comment]
We have voted, it will be CRSH for course hold (old cruise 2D) and CRUZ for cruise mode (old cruise 3D)

**Comment by MrD-RC** [comment]
I have to say that when I read this comment page, I thought it was a good idea. It sounded like in configurator someone can either activate Course Hold or Cruise. That made perfect sense.

However, looking at the code, it looks like the box mode has just been renamed. I really don't think this works, especially to people new to iNav. 
Cruise + Alt Hold = 3D Cruise made sense. You are taking a Cruise mode, and adding a lock to it to make it 3D.
Course Hold + Alt Hold = Cruise make no sense at all. There is no continuity between the mode names. I think this will really just confuse people. Especially new pilots.

Personally, I saw no problem with Cruise and 3D Cruise. Course Hold and Cruise does make more technical sense, so I'm totally fine with the renaming. But I think they should be two separate box modes, to be clear to users.

**Comment by shellixyz** [comment]
Cruise doesn't really make sense if it doesn't manage the throttle as it is just holding course. In aviation cruise is used to denote course hold + throttle control / alt hold. I guess we could create a new cruise mode which is just course hold + alt hold but then there will be two ways to do the same thing. It is just dead code. But maybe it is worth it as it might be less confusing for some users, no sure.

**Comment by avsaase** [comment]
@shellixyz I think that would be the most straightforward solution to any confusion.

**Comment by MrD-RC** [comment]
@shellixyz I do think that would be the best solution, even if it means a little duplicated functionality.

**Pull request merged**
