### PR TITLE
Incremental PID-controller for velocity

### PR DESCRIPTION
**Pull request by theArchLadder**
Just to be clear here, i didn't want to show this ugly mess yet, @digitalentity demanded me to show it!
@digitalentity wrote on RCGroups:

> I need to have a look at your code :smiley: 

The change in the code is very simple, but makes a big difference in reality. Perhaps a little bit trickier to tune but, at least in my experience, it seems to be more accurate and can brake hard without being nervous in poshold. Could be tons of drawbacks that i have not discovered yet though.

It works more like if inav would fly in rate mode, than in angle mode. I can write more about my experience with this if you guys are interested.

Not ready to be merge and will not be ready for master branch for a long time, if ever. We could have a dev branch for this if anyone is interested to play around with it though.

### CODE REVIEW

**Comment by theArchLadder** [comment]
This is what stopping performance can look like with this code:
https://www.youtube.com/watch?v=_JnKicprt1s

**Comment by theArchLadder** [comment]
And this is what poshold looked like today with the same tuning as that stopping video:
https://www.youtube.com/watch?v=U4hAxSl03-U
Smooth and accurate, the controller will react on a noisy gps reading though. I guess this incremental pid-controller actually does what it's told... The old controller just got nervous/jittery/oscillations with agressive tune.

Not sure if this should be called a bug or a feature though, perhaps we shouldn't tell it to do something that we don't want it to do :stuck_out_tongue_winking_eye:

**Comment by theArchLadder** [comment]
Is there any interest in this?

I also tried incremental thingy on althold today, and so far it feels like a big improvement, it actually does what it's told now, and i can activate althold while falling and it will catch it in a very short distance, and `nav_mc_hover_thr` does not seem to be needed.

**Comment by oleost** [comment]
I'm guessing a lot of people are interested in this, your video looks awesome!

Sadly I don't have an GPS enabled quad now to help out with testing. But the GPS is on the way in the mail.

**Comment by digitalentity** [comment]
Hi, very interesting code! You basically changed the acceleration limitation without respect to velocity error.
I'm amazed to see the result of this simple change. Keep up the good work! Will test this more and get it into 1.2 (hopefully)

**Comment by digitalentity** [comment]
You may also want to make incremental PID controller more generic and wrap it into pidApply3 function :)

**Comment by theArchLadder** [comment]
Thanks guys! Just what i needed to hear :smile: 

The limit-thingy is a solution for stopping with zero target velocity, imagine the copter going 2000cm/s north and 500cm/s east, without this limit it would try to stop as fast as possible in both directions, so the velocity to east would stop, but it would still have a big velocity to north, that looks strange, it doesn't brake in a straight path without that limit thingy.

As for pidApply3, it's not really needed, i have not changed the pid-controller. Perhaps it's wrong to call it a "incremental pid-controller", i guess it's more of a "pid-controller used in a incremental way"
The "incremental" change is super simple, the only thing i needed to do on the althold throttle controller was just adding a plus sign like so:

```
posControl.rcAdjustment[THROTTLE] = navPidApply2(stuff);
posControl.rcAdjustment[THROTTLE] += navPidApply2(stuff);
```

And some stuff to make the reset work. Horizontal controller was similar, just made in a constrain function.

I guess one could say that we are asking the pid-controller "how far should the roll/pitch stick be moved from center position?" but the pid-controller answers "this is how far the stick should be moved from the previous position".
Making it incremental = asking the right question IMHO.

For example, lets say we have a target velocity ramp that says "brake with 10 degree bank until waypoint is reached".
The old controller could reach that 10 degree bank, but in that case there will no longer be any velocity error and the controller will go back to having the copter leveled! Old controller needs a velocity error to give any bank angle, but we don't want any velocity error!
The incremental way will simply hold that 10 degree bank if there is no velocity error.

**Comment by gurkenfolie** [comment]
i will gladly test it if you need some testing!
is it possible now?

**Comment by theArchLadder** [comment]
@gurkenfolie I fixed the merge conflicts for you so at least you should be able to build it. Be very careful flying it though, i have tested it myself but this is still very much in development. Position hold will probably be a little nervous for now.

Use posr_p and posr_d values of around 10 or so, posr_i can be 0 and it will still fight the wind.
Oh, and don't activate poshold while on the ground and be carefull when doing RTH landings, your copter might tip over. It has worked for me, but still... Like i said, this is very much in development!

**Comment by theArchLadder** [comment]
There is a new settings here called `nav_mc_rate_limit` that sets a rate limit for navigation, unit is deg/s. 90 is sort of like inav was before, higher values can be useful for tuning.

**Comment by gurkenfolie** [comment]
thank you. how do i build it? this was your last advice, but with the command git branch -r i dont see this remote branch (or how is it called?):

Open a terminal in your inav directory.
Make sure you are on your master branch: git checkout master
Update your local master with the master on github: git pull
Create your own branch: git branch gurkenfolie
Switch to the branch: git checkout gurkenfolie
List all remote branches git branch -r
Pull in the stuff talked about here to your local branch: git pull origin theArchLadder-landing-detector-avg-thr
Then you just have to run make as usual

**Comment by theArchLadder** [comment]
@gurkenfolie Ah yes this is on my own fork of inav. Perhaps google "git add remote" will help you out, i have to leave for work now so i can't find a solution for you, sorry.

**Comment by gurkenfolie** [comment]
thanks, i will google and try :)

edit: added your remote git https://github.com/theArchLadder/inav.git, worked so far. how do i get the new files? git pull https://github.com/theArchLadder/inav.git says  \* branch            HEAD       -> FETCH_HEAD
Already up-to-date.

edit2: `git pull https://github.com/theArchLadder/inav.git incremental-pids` did the job.

sorry for my noob questions.

**Comment by theArchLadder** [comment]
@gurkenfolie No need to apologize for the "noob" questions :)
Please share your experience when you have flight tested this!

**Comment by digitalentity** [comment]
I feel that incremental PID can be made a more generic option. Not much time to review and explore the option, rescheduling for 1.3, sorry :smiley:

**Comment by gurkenfolie** [comment]
[LOG00173.TXT](https://github.com/iNavFlight/inav/files/357766/LOG00173.TXT)
[LOG00172.TXT](https://github.com/iNavFlight/inav/files/357768/LOG00172.TXT)

tried it, the quad started massive backtracking and some kind of toilet bowling when releasing the stick. i will test it further tomorrow and will do recalibration of mag.

**Comment by theArchLadder** [comment]
@gurkenfolie Try with posr_i=0 and perhaps lower pos_p a bit... Oh, and use a higher LEVEL P so it's more responsive in angle mode.

If you want to tune posr_p and posr_d, use pos_p=0 and tune until you have nice stopping performance.

**Comment by carlonb** [comment]
Any news? I'm interested, it's a very nice improvement

**Comment by carlonb** [comment]
Any news, It's a very nice improvement.
Thanks

**Comment by theArchLadder** [comment]
@carlonb Work has been a bit crazy for me so i haven't had much time over for inav sadly. I have spent the little time i have on other RC stuff but i'm starting to miss messing around with inav so i might resume this project at some point,  but don't hold your breath!

**Comment by carlonb** [comment]
Ok, archladder,
I will wait, when f/w ready I can help you testing it.

**Comment by oleost** [comment]
People who was interested in this may want to have a look at #1543 and help out testing.

@carlonb

**Pull request closed without merging**
