### PR TITLE
Add support for multiple OSD layouts

### PR DESCRIPTION
**Pull request by fiam**
Support 3 alternate layouts controllable via RC channels. Lots of supporting changes in MSP, OSD, CMS and CLI required.

Configurator PR at https://github.com/iNavFlight/inav-configurator/pull/392

### CODE REVIEW

**Comment by fiam** [comment]
Just added CLI support and rebased on top of development

**Comment by fiam** [comment]
+2084 FLASH
+536 RAM

**Comment by digitalentity** [comment]
@fiam is this ready for merge?

**Comment by fiam** [comment]
It’s working and bench tested, I would like to improve the osd_layout command a bit, to allow printing a layout instead of just setting it. There are also a few typos in the code.

I won’t be able to work on this until the end of the next week, but I guess we’re not in a rush to merge it.

**Comment by fiam** [comment]
I've added another commit which makes `osd_layout` more usable.   It now accepts the following inputs:

    - osd_layout: Prints all layouts
    - osd_layout <layout>: Prints just the given layout
    - osd_layout <layout> <item>: Prints just the given item
    - osd_layout <layout> <item> <col> <row>: Sets the item position
        without changing its visbility.

This should be now ready to merge.

**Review by digitalentity — APPROVED** [review]
Ok to merge :+1:

**Pull request merged**
