### PR TITLE
Support for multiple types of rangefinder to iNav

### PR DESCRIPTION
**Pull request by digitalentity**
Initial support done. Some more work required to make this cleaner and configurable from CLI similar to gyro/accel/mag/baro sensors.

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden 
What do you think about treating sonar like any other sensor? Autodetect it in initialisation.c and act accordingly?

**Comment by martinbudden** [comment]
@digitalentity , yes, I think that is the correct way to do it. In fact I had written code to do the auto detection in `initialisation.c`, but changed it back since I thought it was probably too much to do all in one pull request.

**Comment by digitalentity** [comment]
I'm going to merge this. Will you continue the refactoring?

**Comment by martinbudden** [comment]
Yes, no problem. Once it is merged in I'll do some further refactoring.

**Pull request merged**
