### PR TITLE
Port of FIR2 second stage gyro filter from Betaflight

### PR DESCRIPTION
**Pull request by DzikuVx**
Port of famous Stage2 FIR (not) Kalman from Betaflight. I'm not completely sure I got dT right since BF and us use different things in filters, but will test over the weekend in my racer

### CODE REVIEW

**Review by digitalentity — COMMENTED** [review]
Seems ok to me

**Comment by DzikuVx** [comment]
Not happy with current results, plus found a bug. But did not smoked the motors, so it's not that bad after all

**Comment by DzikuVx** [comment]
Flight tested again after fixes. Quite happy with results. Disabled by default so I assume we can merge it back. Ultimately this might replace Notches and make tuning much simpler

**Comment by digitalentity** [comment]
Not sure if it will replace notches - they are better in cutting out a relatively narrow band noise.

**Review by digitalentity — APPROVED** [review]

**Comment by DzikuVx** [comment]
Perhaps, but it does nice job 

stage2 raw

stage2 filter 2

stage2 filter 3

**Pull request merged**
