### PR TITLE
Add ADC input for analog air speed sensor support

### PR DESCRIPTION
**Pull request by Linjieqiang**
Add analog airspeed adc support.See https://github.com/iNavFlight/inav/issues/1423

### CODE REVIEW

**Comment by Linjieqiang** [comment]
@sambas Can you provide some help about adding airspeed in INAV?I have to admit that I am not a good code monkey but I love fixwing and INAV.

**Comment by digitalentity** [comment]
I suggest we split the BIG task of adding airspeed to a few smaller one  -you just done the first one - add ADC input for analog airspeed sensors. 
Some of the remaining tasks are already done in PITOT driver- I'll create a new device to read and calibrate for analog airspeed sensor.
Adjust parameters based on airspeed is both easy and hard - it will also have to be done in baby steps, but don't worry we'll get it working.

Do you have any particular target that have 4 ADC inputs?

**Comment by Linjieqiang** [comment]
@digitalentity 
1.Nice.I use current monitor adc for my analog airspeed sensor.As you say,I will split the big task and welcome you join in.I currently am reading the Arduplane source about airspeed.I want to see it implement in INAV 1.7 version.
2.Also,I am making a new fc with STM32F407 100pins.It will support 4 ADC inputs and CAN 
bus.
3.Calibrating airspeed sensor maybe use these code about ekf. https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Airspeed/Airspeed_Calibration.cpp

**Comment by Linjieqiang** [comment]
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Airspeed/Airspeed_Calibration.cpp Calibrating airspeed sensor maybe use these code about ekf.

**Comment by digitalentity** [comment]
@Linjieqiang cool! Will it be possible to get a few of those new FCs?

**Comment by Linjieqiang** [comment]
My old fishDrone fc board will be abandoned.How can I talk with you ?Google Email?I want to chat you on gitter.Let me share something about this fc info and I also want to listen your advises.Thanks for your great work again.@digitalentity

**Pull request merged**
