### PR TITLE
Add the MS5611 barometer for IFLIGHTF7_TWING

### PR DESCRIPTION
**Pull request by YI-BOYANG**
I have an IFLIGHTF7_TWING flight control and an ms5611 barometer, but when I connected ms5611 to FC, it was not detected. When I checked the definition of IFLIGHTF7_TWING, I found that ms5611 was missing.

I just added a line of code and compiled the test, and I was able to use ms5611 normally.
image
image

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
This barometer already came soldered on the FC (placed by the manufacturer), or did you put it as an external barometer?

**Comment by YI-BOYANG** [comment]
> 这个气压计已经焊接在 FC 上（由制造商放置），还是你把它当作外部气压计？
aa55aa62b644b975ecc98ddad7dbbdd
Because the FC comes with a bmp280 barometer, its performance is not as good as the ms5611. So I can use ms5611 as an external barometer, which only needs to be connected to SDA and SCL on FC.

**Comment by YI-BOYANG** [comment]
> This barometer already came soldered on the FC (placed by the manufacturer), or did you put it as an external barometer?

Because the FC comes with a bmp280 barometer, its performance is not as good as the ms5611. So I can use ms5611 as an external barometer, which only needs to be connected to SDA and SCL on FC.
aa55aa62b644b975ecc98ddad7dbbdd

**Comment by JulioCesarMatias** [comment]
as the barometer was not added by the manufacturer during production, so I don't know if this PR will be approved... Let's see what Pawel thinks about it

**Pull request closed without merging**
