### PR TITLE
Protocol-independent GPS stack for iNav

### PR DESCRIPTION
**Pull request by digitalentity**
Continuation of #66

### CODE REVIEW

**Comment by sambas** [comment]
Merged this to my nav branch, not sure if I messed the merge or what happened. Things I found.
- tested with nazagps
- gps mag doesn't get detected, had to force it in gpsMagDetect. Is gps feature available when mag is initialized? edit2: found it, hasCompass is false
- gps altitude now in centimeters, old was in meters. telemetry and log tools need fixing
- wasn't able to get Poshold working it always entered in toiletbowl effect. Heading seems to be ok.
  log: https://www.dropbox.com/s/pih57g71zxt73kc/blackbox_log_2016-01-01_145159.TXT?dl=0
  config: https://www.dropbox.com/s/zubgdipga9y8irw/112016v2.txt?dl=0

Found bug in nazagps velned, forced to be always not valid.
new log https://www.dropbox.com/s/l3tltz7uqtmhmyq/blackbox_log_2016-01-01_162706.TXT?dl=0

**Comment by digitalentity** [comment]
@sambas 
Thanks for testing! I've given you write access to inav repo, feel free to push fixes to this PR.

**Comment by digitalentity** [comment]
@sambas did you have a chance to test the latest code?

**Comment by sambas** [comment]
Not yet, I can bench test it and try flying it next weekend.

**Comment by digitalentity** [comment]
I'm very interested in testing with NAZA GPS. UBLOX and I2C-NAV seems to be working fine.
Be advised that I've rebased this PR to latest iNav master.

**Comment by sambas** [comment]
Both ublox and nazagps benchtested and working. Trying to fly tomorrow

**Comment by stronnag** [comment]
Flew eb2c86f1e181c1bde13441b3e895d7705ec79e65 with ublox M8N today. Recognised and v7 init applied.

**Comment by stronnag** [comment]
For info, the latest mwptools contains updated ublox test programs (ublox-cli), which use the inav init data. Using my oldest Neo 6M device (with version aware firmware), I get the following version response times:

38400 baud: Version info after 0.024s
57600 baud: Version info after 0.016s

i.e. baud rate dependent, at 9600 baud, somewhat less consistent:
Version info after 0.237s
Version info after 0.263s
Version info after 0.438s <=== ***\* maybe my machine was busy ?

So I think the GPS version init timeout (0.25s) is adequate for _most_ cases, but may fail for 9600 occasionally.

**Comment by digitalentity** [comment]
@stronnag, @sambas 
Do you think it's safe to merge this branch now?

**Comment by stronnag** [comment]
Yes, with the caveat that you may wish to revise the auto_baud behaviour (either make it the same as CF or have ON as the default).  At least it must be mentioned in the release note (that most people seem to avoid reading).

**Comment by sambas** [comment]
Flight tested, good to go

**Comment by digitalentity** [comment]
I'm going to review the ublox autobaud code to be closer to original CF semantics. Should make autobaud work faster.

**Comment by digitalentity** [comment]
@sambas
I wonder if we need the NAVX5 message in `ubloxInit6` sequnece? It is not present in `ubloxInit` data.

EDIT: Neither APM not PixHawk uses NAVX5 message.

**Comment by digitalentity** [comment]
Ok, NAVX5 disabled, autobaud semantics changed to be more CF-like. Bench tested with Neo-6M in Ublox binary and NMEA modes. All working fine. Need to test I2C-NAV (will do today) and NAZA (@Sambas, I need your help with this one).

**Comment by sambas** [comment]
No issues with nazagps at bench

**Comment by digitalentity** [comment]
Looks like the new autoconfig is not working with some modules. Any ideas how to counteract this? Use configurable dynamic model?

**Comment by sambas** [comment]
Would be interesting to collect gps and firmware version data from units that have problems. Ublox says PVT message is supported "u-blox 7 firmware version 1.00". Makes me think some chinese manufacturers have used some engineering samples or similar in their units.
edit. Both my neo7 and m8n have ublox stickers on them.

**Comment by digitalentity** [comment]
@sambas may be we should check for sw version as well?

**Comment by digitalentity** [comment]
The code is working and I'm merging it following these rules:
1. Make it work first
2. Improve it later

**Pull request merged**
