### PR TITLE
Add BETAFLIGHTF3 target support

### PR DESCRIPTION
**Pull request by shellixyz**
- Based on CF/BF target definition
- Linked issue: #1389 
- Untested, need feedback, I do not own this board.
- LED STRIP feature doesn't work

### CODE REVIEW

**Comment by shellixyz** [comment]
This PR depends on #2512

**Comment by digitalentity** [comment]
@shellixyz did you have a chance to test this PR?

**Comment by shellixyz** [comment]
@digitalentity Unfortunately I can't test this because I do not own this board. People interested by this target should try and report their findings. Looking at #1389 and #2511 five people were interested. I asked for feedback there but nobody chimed in yet.

@tonysmartantzoulatos @gregorg @brkdwn @airiclenz @miginv Could you give this PR a try ? I can build a firmware image for you if you need.

**Comment by tonysmartantzoulatos** [comment]
Sorry i replied to an older post but i am a newbie here. An image would be appreciated for me to test hopefully during the weekend.

**Comment by shellixyz** [comment]
@tonysmartantzoulatos Here it is: [inav_1.8.1_BETAFLIGHTF3.hex](https://drive.google.com/file/d/1PnfgoV7ghDu6372URFQohzMpAErRoDz8/view?usp=sharing)

**Comment by tonysmartantzoulatos** [comment]
@shellixyz i already download and tried to flash locally. Flashed everything and after that the Win7 says, usb device not recognized. Reflash with Beta on DFU mode and the device works again.

After Inav Flash i get 2 slow and (i thnk) 4 fast blinks

**Comment by shellixyz** [comment]
I made some changes, please could you try this one:
[inav_1.8.1_BETAFLIGHTF3.hex](https://drive.google.com/open?id=1UCc3vO-2W1Bf7Zm5QsOcdN023TOLRCDQ)

**Comment by tonysmartantzoulatos** [comment]
Same flashing sequence and still board not recognized after flash. Either i am doing something very wrong or this sequence means its not finding something its looking for. 2 slow 3 fast

**Comment by shellixyz** [comment]
@tonysmartantzoulatos I think the problem comes from the ACC/GYRO initialization. Please try this updated version: [inav_1.8.1_BETAFLIGHTF3.hex](https://drive.google.com/open?id=1UIfvoyoSctKwOaALsLpv46ZKEnaABBbf)

**Comment by alenpokos** [comment]
Thx for the effort. Tried flashing and changing some configuration from last hex file. So far everything looked ok. I will try to wire it with wing electronics in the next day or two.

**Comment by maymayday90** [comment]
No GPS available in Ports tab? Can't enable my connected GPS it seems. Just flashed your hex from a day ago. @shellixyz 

edit: nevermind, see that it's a UI change, was looking at older videos of the configurator that had a different column for GPS. Working for me! Will be doing a full setup on a Goblin, thanks for the hex file!

**Comment by shellixyz** [comment]
@maymayday90 I don't see how your GPS problem could be linked to this target in particular. Don't you have a GPS option in the sensors column drop-down menu in the ports tab ?

**Comment by shellixyz** [comment]
@maymayday90 Great ! Remember to be careful because this build is based on the development branch.

**Comment by maymayday90** [comment]
@shellixyz ah true, what are the chances you could build a hex for 1.8 stable? 😄 Not looking to lose my long range setup on beta code (though I will be putting one of these on a bashing wing as well, so can always run tests on it).

**Comment by shellixyz** [comment]
@maymayday90 I understand. Here you go: [inav_1.8.0_BETAFLIGHTF3.hex](https://drive.google.com/open?id=1nlBl0uu-WoJJOfI-JGDIO9Ab8w9cuXQV).

**Comment by shellixyz** [comment]
The branch linked to this PR has been updated with the last changes including reenabled SPEKTRUM support. Updated build, same as last dev one with SPEKTRUM support: [inav_1.8.1_BETAFLIGHTF3.hex](https://drive.google.com/open?id=1jJF1Q37xIRQOE3EqlCwxb0aZHD55ue3M)

**Comment by maymayday90** [comment]
@shellixyz worked great today, RTH etc tested and working. Thanks again!

**Comment by digitalentity** [comment]
Great. Merging then!

**Comment by SlipstreamFPV** [comment]
Output 5 and 6 should be put onto pin A09 and A10 rather than soft serial 1 Tx Rx. Otherwise this board can't be used with a regular fixed wing.

**Pull request merged**
