### PR TITLE
SKYSTARSF405HD: add support for BMI270 used on newer boards

### PR DESCRIPTION
**Pull request by shellixyz**

### CODE REVIEW

**Comment by erstec** [comment]
Why we need to add it once again?
https://github.com/iNavFlight/inav/pull/8087

**Comment by shellixyz** [comment]
Looks like it had been merged in the wrong branch so it wasn't in the master branch

**Comment by erstec** [comment]
> Looks like it had been merged in the wrong branch so it wasn't in the master branch

It was merged to release 5.0.0 branch, exactly as it should be and will appear in master after 5.0.0 release

**Comment by shellixyz** [comment]
That's not how things work AFAIK. Stuff is merged in master then when it is time for a release the release commit is tagged

**Comment by erstec** [comment]
> That's not how things work AFAIK. Stuff is merged in master then when it is time for a release the release commit is tagged

I believe @DzikuVx decided to make this different way.

**Comment by shellixyz** [comment]
Well technically if this was going to be in 5.0 but merged after the 5.0rc was released I guess it should indeed be merged in the 5.0 branch. I didn't know 5.0rc had been released. I haven't followed the development closely lately. So I guess I can close this

**Pull request closed without merging**
