### PR TITLE
MATEK F411SE Duplex Soft Serial 1

### PR DESCRIPTION
**Pull request by thedoble**
I wanted to use GPS, Crossfire, DJI FPV OSD, and LED on my F411SE board.

Mr. D's CH6 target gave me enough information to re-arrange the soft serials so that SS1 is now duplex - TX on ST1 and RX on CH6.

I use DJI FPV on the softserial since its probably the least important compared to xfire and GPS.

I don't really understand the contents of the target.c file so if someone can check that it would be appreciated.

### CODE REVIEW

**Review by geoffsim — COMMENTED** [review]
The timerHardware table should not need changing unless you are moving timers around or are adding new timers to i/o pins. The soft serial code does not care about the flags in the table.

**Comment by JulioCesarMatias** [comment]
This unfortunately did not appear for you

Captura de tela 2022-01-25 204803

**Comment by geoffsim** [comment]
> This unfortunately did not appear for you
> 
> Captura de tela 2022-01-25 204803

I didn’t understand that?

**Comment by joelamoule** [comment]
Hi, i got the same request. I modify all the files and compiled new target. You can contact me to test it

**Pull request closed without merging**
