### PR TITLE
SmartPort (S.Port) telemetry enhancements, cleanup, and documentation

### PR DESCRIPTION
**Pull request by teckel12**
- New `smartport_fuel_percent` variable (if set to `ON`) along with `battery_capacity` variable sends SmartPort telemetry `Fuel` as available battery percentage (defaults to `OFF` to be consistent with previous releases).  See documentation for details.
- Added GPS accuracy to unused hundreds digit of `Tmp2` SmartPort telemetry identifier (0 = lowest to 9 = highest accuracy).  Typical minimum GPS 3D lock `Tmp2` value is now `3906` (GPS locked, GPS home fix, highest HDOP accuracy, 6 satellites).  See documentation for details.
- Added failsafe mode indicator to ten thousands column of `Tmp1` SmartPort telemetry identifier (+4 = failsafe mode).  See documentation for details.
- Folded Cleanflight SmartPort telemetry logic with iNav SmartPort telemetry info.
- Incorporated MSP over SmartPort, should be ready for PID tuning over Taranis (like in Betaflight).
- Constrained number of satellites to 0-99 range to avoid potential rollover into hundreds position of `Tmp2`.
- Prevent second to last digit overflow of `Tmp1` from multiple flight modes.
- Cleaned up code to follow coding style guidelines as per iNav documentation.

### CODE REVIEW

**Comment by digitalentity** [comment]
@teckel12 great job! I see you also added in MSP over S.Port - we can finally have configuration menus on Taranis :+1:

**Comment by digitalentity** [comment]
@teckel12 please give me a ping when this is ready to be merged.

**Comment by teckel12** [comment]
@digitalentity Still working on it.  Will let you know when I've worked out any kinks.  I figure I'll add the code for PID tuning over Taranis (like in Betaflight) in a different branch.

**Comment by teckel12** [comment]
I'll do some final testing on it this evening and let you know if I believe it's good to merge.

**Comment by teckel12** [comment]
@digitalentity Ping!  I'm happy with it and it's ready to be merged.  I'm already working on the PID telemetry over S.Port.

**Comment by teckel12** [comment]
@digitalentity It seems that much has changed with `fc/cli.c`.  Not sure about `telemetry/smartport.c`.  It doesn't allow me to see the merge conflicts, so I can't tell what has changed to fix them.

**Comment by digitalentity** [comment]
@teckel12 sorry missed your ping from a week ago. Will resolve conflicts and merge.
Now we have CLI parameters automatically generated from a `settings.yaml` file, CLI code now doesn't have to maintain the list.

**Comment by digitalentity** [comment]
Superseded by https://github.com/iNavFlight/inav/pull/2050

**Pull request closed without merging**
