### PR TITLE
Update Building in Windows / link to latest GCC

### PR DESCRIPTION
**Pull request by Schalonsus**
added link to the latest GCC and removed advise to use GCC 4.9

### CODE REVIEW

**Review by fiam — APPROVED** [review]

**Comment by fiam** [comment]
@Schalonsus How difficult would be writing a script for Windows that downloads and install a given GCC version? Maybe we could keep the version number on a shared file and have specific scripts for Windows/Unix to download the version mentioned in that file.

**Comment by stronnag** [comment]
On Linux it's called a package manager and needs no interference from iNav, thank you.

**Comment by fiam** [comment]
@stronnag It can still be useful for users who just want to compile the firmware once. In fact, we do have such a script for running travis builds.

**Comment by stronnag** [comment]
No it's not, it just encourages hard to diagnose breakage (e.g. incompatible compiler and newlib). Travis is not an ordinary end user.

**Pull request merged**
