### PR TITLE
Don't do home reset if in failsafe mode

### PR DESCRIPTION
**Pull request by teckel12**

### CODE REVIEW

**Comment by digitalentity** [comment]
Good improvement. If receiver failsafe is misconfigured and will accidentally activate "HOME RESET" unpleasant things may happen.

**Comment by digitalentity** [comment]
@teckel12 can you rebase?

**Comment by teckel12** [comment]
@digitalentity Will do.

**Comment by teckel12** [comment]
@digitalentity Should be ready to go.  Was in a huge hurry over the holiday and I'm going out of town so I just made it work.

**Pull request merged**
