### PR TITLE
Homing crossairs and OSD tweaks

### PR DESCRIPTION
**Pull request by OlivierC-FR**
**7 crosshairs :** (default one, + aircraft, and 5 new)

  
  

**Homing arrows :**

Will show the home point relative to the crosshair. 
Helps to find the home point, easier to read than the arrow-to-home, and also works in pitch.
Vertical arrows will only show if the home is inside a 150° angle in front of the aircraft, so it does not show when moving away the home point, that's normal.
Must be enabled in the onscreen menu : _OSD > Settings > Homing = ON_

Focus can be set to narrow, medium or large, it sets how accurate the homing is, default is medium.
_OSD > Settings > Crosshair focus_

**Adjustable FPV camera angle :**

FPV camera angle in degrees can be adjusted in case it is not at 0°/flight controller
This is the angle in tilt between the flight controller and the FPV camera.
Positive is camera pointing up (quads usually), negative is camera pointing down (planes).
It's important that the camera angle is set to the correct angle, without this the arrows won't lead to the exact home point.
_OSD > Settings > Camera uptilt_

**Adjustable crosshair offset :**

That's to move the crosshair and AHI and side scrollbars from -2 to +2 lines in height.
This setting is not required for the homing feature, it's just in case someone wants to raise or lower the center of the HUD.
_OSD > Settings > Horizon offset_

**Optional small numbers :** (REMOVED SO IT FITS ON F3)

To display the RSSI and 3D speed values in small numbers right below the crosshair.
In the CLI:  set osd_smallnumbers = ON

**Require a compatible font**, such as Vision 1, 2, 3 or 4 : 
https://www.dropbox.com/s/68aahlp14akhdn6/visions.zip?dl=1

Demos : 
https://drive.google.com/file/d/1Tc2tFNoNwtt-K-PIVtH60v8NIi6gzLa5/view
https://drive.google.com/file/d/1UhvYoeSkixDL1DGpGEP6hXTMGAzqsaPk/view
https://drive.google.com/file/d/1o8km_VBiy3DOX-ArPqQqvVSgQZhVRSQ8/view

### CODE REVIEW

**Comment by OlivierC-FR** [comment]
This should help understand how the homing arrows work, horizontally, for focus = narrow, medium and wide : 

smartch

Vertically : 

smartch_v

**Comment by wx4cb** [comment]
dang dude... that is awesome... can't wait... would love to test it. any chance I can get a hex for the 405-wing? I have a MT to maiden tomorrow.

**Comment by OlivierC-FR** [comment]
For testing purposes, all targets, based on Inav 2.1.RC2 + some of my other OSD tweaks : 
https://www.dropbox.com/s/q91vmunc5ieqjqg/inav.20190205.zip?dl=1

**Comment by wx4cb** [comment]
awesome.. thnx.. will test it tomorrow.

**Comment by wx4cb** [comment]
ok just put it on loaded the vision 3 font and the type 3 cross-hair and homing is medium.  I have 7 sats in the house and when i arm and walk away from where I armed it I don't see any change in the cross-hair. how far away do i have to be from the arming point?

**Comment by OlivierC-FR** [comment]
You must have a valid GPS fix, and armed, so it saves the home point, then if you move the quad it will appear.
After only few meters away the home it should work, did you set "ON" on the "Homing" line ?

**Comment by wx4cb** [comment]
I did.  But ill look tomorrow when im out flying. Was testing at home

**Comment by wx4cb** [comment]
@OlivierC-FR All i can say is WOW..... I had it on narrow mode just to test it and it works absolutely AWESOME. i didnt even need to look down at my home arrow at all other than to verify that it was working right. which it was.

I even had the slope indicator on and that worked great (not sure if that was your work or not). I'll upload the dvr later on.

**Comment by OlivierC-FR** [comment]
Good news, and thanks for testing !
Slope indicator is also a mod I made yes.
I'm very interested in seeing your DVR, I never actually had the time to test the narrow setting :) 

> 
> 
> @OlivierC-FR All i can say is WOW..... I had it on narrow mode just to test it and it works absolutely AWESOME. i didnt even need to look down at my home arrow at all other than to verify that it was working right. which it was.
> 
> I even had the slope indicator on and that worked great (not sure if that was your work or not). I'll upload the dvr later on.

**Comment by wx4cb** [comment]
@OlivierC-FR yea it was pretty good.... here's the whole 10 minute flight: https://www.youtube.com/watch?v=-mehDQuTGi0

**Comment by wx4cb** [comment]
the other thing I wanted to ask was the horizon offset. that's to move the crosshair up/down on the osd right?

**Comment by OlivierC-FR** [comment]
Yes, it's only moving the crosshair up or down on the screen.
Aswell as the zero-tilt for the artificial horizon indicator, and the side scrolling lines

Looks like this mini Talon is flying well, even at the first flight !

Side note, I see you do not have the newest font version in your DVR, the bars above the directional arrows are now gone, and I changed some of the crosshairs.
Altho, that's just cosmetic details.

https://www.dropbox.com/s/68aahlp14akhdn6/visions.zip?dl=1

> 
> 
> the other thing I wanted to ask was the horizon offset. that's to move the crosshair up/down on the osd right?

**Comment by wx4cb** [comment]
just tried it on my S1100 which has an F405 wing in it - the other was an F35 lightning. and it works great. being able to move the crosshair down allows me to put it right on the horizon when level (1 click).

This is working great. Never thought i'd use it so much :D

**Comment by wx4cb** [comment]
@OlivierC-FR  works great. put it on the s1100 harrier and managed to get the small numbers working.

One thing that would be nice is is it possible to have RSSI and altitude instead of RSSI and speed as the small numbers. maybe make them configurable?

As far as the "Up" arrow, you would unlikely see if on mine because i live in florida and there are no hills here :D

@shellixyz @digitalentity this works great so if it's not already in there would be nice to add it to the release ❤️ ❤️ ❤️ 
vlcsnap-2019-02-08-11h37m06s237

**Comment by OlivierC-FR** [comment]
About the Up arrows, if the camera uptilt angle is set for the plane, you should see the arrows going up, say you're like 2kms away, and pointing right at you with the crossair, if you dive, the up arrows will show, telling you the line toward home is "above". Hills not needed ! That's quite a flat country you have there, makes me almost uncomfortable ;)
> 
> 
> @OlivierC-FR works great. put it on the s1100 harrier and managed to get the small numbers working.
> 
> One thing that would be nice is is it possible to have RSSI and altitude instead of RSSI and speed as the small numbers. maybe make them configurable?
> 
> As far as the "Up" arrow, you would unlikely see if on mine because i live in florida and there are no hills here :D
> 
> @shellixyz @digitalentity this works great so if it's not already in there would be nice to add it to the release ❤️ ❤️ ❤️
> vlcsnap-2019-02-08-11h37m06s237

**Comment by wx4cb** [comment]
@OlivierC-FR I see what you mean.... yea my camera is pretty much dead straight so no "tilt".

One thing i was thinking of yesterday as I went and did more flying. with the small numbers suggestion i had. how about this....>

mah     ALT
----\/-----
----/\-----
RSSI   SPEED

that to me would be perfect. those are really all what would be needed. now of course if it was conflgurable so you could have different things in the places that would be better :D but having those right there would help us old farts with poor eyesight that have to strain to look at the edges of the goggles - hence why the big-ass font. you could get rid of half of the things in the osd :D 

but all in all.. that's just cosmetic thoughts.... it works great. just lake Maccy-ds.... i'm loving it :D

**Comment by teckel12** [comment]
@wx4cb @OlivierC-FR Traditionally on a glass cockpit display, the altitude is on the right and the speed on the left. So keeping the original design for those two I believe makes the most logical sense.

But, adding RSSI and some kind of battery indicator above the crosshairs seems like a good idea. My vote would be to show fuel percentage, which would work both with and without a current sensor. But not everyone specifies their battery capacity so maybe just show mAh if there's a current sensor and cell voltage otherwise?

**Comment by wx4cb** [comment]
@teckel12  all the glass cockpits i've flown ASI is left and alt is right.  as far as as the crosshairs, i generally go by voltage (< 14.8 sustained is time to get the nod for the sod) but either way voltage/mah works

For example, this is the garmin that's usually in newer cessnas and dolphins (verified this with an FS  embry riddle plane)
image

Standard boeing/airbus PFD
image

**Comment by teckel12** [comment]
@wx4cb My bad, reversed my left and right :smile: fixed my reply. I guess my point is that those should be in their traditional locations, and if other values are added, they shouldn't move the standardized ones.

**Comment by wx4cb** [comment]
@teckel12 no worry i do that all the time. and yes... we should standardise on the "regular standard" :D

**Comment by wx4cb** [comment]
@OlivierC-FR here in the PR

```
if (osdConfig()->smallnumbers) {
            uint16_t smallnum[2]
                  // RSSI bottom-left
            uint16_t crh_rssi = osdConvertRSSI();
            osdFormatSmallNumber(smallnum, crh_rssi);
            displayWriteChar(osdDisplayPort, elemPosX-2, elemPosY+1, smallnum[0]);
            displayWriteChar(osdDisplayPort, elemPosX-1, elemPosY+1, smallnum[1]);

// 3D speed bottom-right
            uint16_t crh_3dspeed = osdConvertVelocityToUnit(osdGet3DSpeed());  
            osdFormatSmallNumber(smallnum, crh_3dspeed);
            displayWriteChar(osdDisplayPort, elemPosX+1, elemPosY+1, smallnum[0]);
            displayWriteChar(osdDisplayPort, elemPosX+2, elemPosY+1, smallnum[1]);
           }
```

i was thinking about something like this (NOTE Not sure what the variable would be but:

           // Distance to home Top Left
             uint16_t crh_DtH= DISTANCE_TO_HOME_FUNCTION
            osdFormatSmallNumber(smallnum, crh_DtH);
            displayWriteChar(osdDisplayPort, elemPosX-2, elemPosY-1, smallnum[0]);
            displayWriteChar(osdDisplayPort, elemPosX-1, elemPosY-1, smallnum[1]);

            // Current Altitude Top right
            uint16_t crh_MyAltitude = ALT_RETURN_FUNCTION
            osdFormatSmallNumber(smallnum, crh_MyAltitude);
            displayWriteChar(osdDisplayPort, elemPosX+1, elemPosY-1, smallnum[0]);
            displayWriteChar(osdDisplayPort, elemPosX+2, elemPosY-1, smallnum[1]);


The other thing I would suggest to save code space is to combine them into a 8 byte array going top left to bottom right for the data and then a corresponding one for their positions. for example:

```
smallnum[0] = DtH major
smallnum[1] = DtH minor
smallnum[2] = ALT major
smallnum[3] = ALT minor
smallnum[4] = RSSI major
smallnum[5] = RSSI minor
smallnum[6] = SPEED major
smallnum[7] = SPEED minor
```

**Comment by OlivierC-FR** [comment]
The thing is, for now small numbers can only be between 0 and 209 !
It does not support higher values, for distance, altitude etc, would require a lot more chars in the OSD font.
That's partly why I went for only RSSI and speed :)

**Comment by wx4cb** [comment]
> The thing is, for now small numbers can only be between 0 and 209 !
> It does not support higher values, for distance, altitude etc, would require a lot more chars in the OSD font.
> That's partly why I went for only RSSI and speed :)

i'm guessing that because of you need a separate character block in the font for the small numbers? so there's 2 1's 2 2's 2 3's etc ?

**Comment by OlivierC-FR** [comment]
It combines numbers like that, could be tweaked to display more, maybe by steps of 20 or 50, but that would quicky consume all the free slots in the font : 

vision4

**Comment by wx4cb** [comment]
i see h ow you're doing it, but couldn't you  just use one cell and call each respective number? that way you would just need 20 slots, one for numbers on the left and one for numbers on the right? or maybe 30 slots for numbers with a blank on either side?

if that makes sense. that would be the better way of doing it

**Comment by OlivierC-FR** [comment]
Closing, outdated, being replaced by the "Hud", work in progress

**Pull request closed without merging**
