### PR TITLE
updated cli.md for acc_*, baro_* and mag_hardware

### PR DESCRIPTION
**Pull request by oleost**
Have not updated pitot yet.

I see that pitot_hardware is listed in cli. But in latest development target there is no pitot_hardware cli?

```
# dump

# version
# INAV/SPRACINGF3 1.5.0 Dec 14 2016 / 18:35:17 (eeaa20a)
# pflags
# Persistent config flags: 0x00000000
# dump master

# get _hardware
acc_hardware = AUTO
Allowed values: NONE, AUTO, ADXL345, MPU6050, MMA845x, BMA280, LSM303DLHC, MPU6000, MPU6500, MPU9250, FAKE

baro_hardware = NONE
Allowed values: NONE, BMP085, MS5611, BMP280, FAKE

mag_hardware = NONE
Allowed values: NONE, HMC5883, AK8975, MAG_GPS, MAG_MAG3110, MAG_AK8963, FAKE


# get pitot
Invalid name

# set pitot_hardware
Invalid name

# 
```

### CODE REVIEW

**Comment by digitalentity** [comment]
Pitot is only supported on very few FCs at the moment: AIRBOTF4, ANYFC, OMNIBUSF4, REVO

**Comment by oleost** [comment]
@digitalentity @sambas Can one of you do a get pitot_hardware on latest development with default setting?

Then I can update that part of cli aswell.

(Tried it on my AirbotF4, and there is no pitot in CLI there either)

```
# status
System Uptime: 52 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), System load: 0.00
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=NONE, SONAR=NONE, GPS=NONE
Stack size: 2048, Stack address: 0x10010000
Cycle Time: 2002, I2C Errors: 0, config size: 1688

# get pitot
Invalid name

# dump

# version
# INAV/AIRBOTF4 1.5.0 Dec 15 2016 / 10:30:44 (3bc1a14)
# pflags
# Persistent config flags: 0x00000000
# dump master
```

**Comment by digitalentity** [comment]
@oleost 

```
# set pitot
pitot_hardware = NONE
Allowed values: NONE, MS4525, FAKE

pitot_use_median_filter = ON
Allowed values: OFF, ON

pitot_noise_lpf =  0.600
Allowed range: 0 - 1

pitot_scale =  1.000
Allowed range: 0 - 100
```

**Comment by oleost** [comment]
@digitalentity Should be updated now. Probably ready to merge

**Pull request merged**
