### PR TITLE
Switch MatekF405TE to use burst DMA

### PR DESCRIPTION
**Pull request by DzikuVx**
@MATEKSYS can you confirm DSHOT is working now? I'm not sure where I put the hardware to test

### CODE REVIEW

**Comment by MATEKSYS** [comment]
DSHOT is working.
seems you add dshot burst in a wrong target file.
should be MATEKF405TE, rather than MATEKF411TE

**Comment by DzikuVx** [comment]
Now it should be fine. If you confirm DSHOT is not working with 405TE we can merge immediately

**Comment by MATEKSYS** [comment]
I have tested it yesterday,  8 motors all working with DSHOT burst.

**Comment by rmaia3d** [comment]
Since I already have a Matek F405 mini-TE in hand, I hooked S1 to S4 outputs to an oscilloscope and ran some tests:

This is the "vanilla" Inav 6.1.1 output, DSHOT 300 at 0% and 50% throttle:
Ch1 is S1, yellow line
Ch2 is S2, cyan line
Ch3 is S3, magenta line
Ch4 is S4, blue line
IMG_2728
IMG_2730

**Comment by rmaia3d** [comment]
This is after applying the changes in this PR (same setup as above):

IMG_2731
IMG_2732

As can be seen, not much difference other than the channel groupings seem more aligned between themselves.

What draws the attention is the fact that S3 (Ch3, magenta line) is mirrored with regards to the other ones. This didn't change between before DMA burst and after.

So, even though the motor may be running on S3, did anyone actually test it to verify the correct throttle input is being recognized?

**Comment by rmaia3d** [comment]
For reference, here is the Betaflight 4.4.2 output on the same board, same setup (DSHOT 300) and also at 0 and 50% throttle. Note how S3 (magenta) isn't mirrored, it's exactly the same as the others.

IMG_2733
IMG_2734

**Pull request merged**
