### PR TITLE
gcc 8 support

### PR DESCRIPTION
**Pull request by stronnag**
Initial  and trivial changes to compile with gcc 8. 

* Compiles and bench tests OK
* Small reduction in code size

**TODO**

Resolve function pointer warnings mainly related to `PG_REGISTER_ARRAY_WITH_RESET_FN` and `PG_REGISTER_WITH_RESET_FN`

### CODE REVIEW

**Comment by stronnag** [comment]
Flys OK (MATEKF405, Omnibus F3)

**Comment by stronnag** [comment]
The last two commits are somewhat ugly and expedient.

1. Accept it
2.  Reject it, and have three ugly warnings
3. Propose a better solution, possibly involving a union of acceptable function pointer types for cms functions.

Views on the best solution are appreciated.

**Comment by digitalentity** [comment]
@stronnag I'm all in for option 3 - a union (possibly unnamed) with acceptable pointer types.

**Comment by stronnag** [comment]
OK, better to do it the right way.

**Comment by digitalentity** [comment]
@stronnag will you do it as a part of this PR?

**Comment by stronnag** [comment]
On May 7, 2018 6:24:57 AM UTC, Konstantin Sharlaimov <notifications@github.com> wrote:
>@stronnag will you do it as a part of this PR?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNavFlight/inav/pull/3172#issuecomment-386969322

Yes

**Comment by stronnag** [comment]
This now compiles cleanly on GCC 8.1 without any cheating `#pragma`.
Sadly, it removes the some highly inventive use of casts, and as a side effect mitigates GET_ID cast.
As I don't have any CMS related gadgets, this is untested.  

I'm now going to sit in a dark room and drink vodka.

**Comment by stronnag** [comment]
This now compiles cleanly on GCC 7.3 and GCC 8.1

**Review by digitalentity — APPROVED** [review]

**Pull request merged**
