### PR TITLE
Prepend USE_ prefix to CPP directives for enabling features

### PR DESCRIPTION
**Pull request by fiam**
Prepended to: 'ACC', 'GYRO', 'BARO', 'MAG', 'LED_STRIP',
'SPEKTRUM_BIND', 'SERIAL_RX', 'BLACKBOX', 'GPS', 'GPS_PROTO_UBLOX',
'TELEMETRY', 'TELEMETRY_LTM', 'TELEMETRY_FRSKY', 'CMS',
'GPS_PROTO_NMEA', 'GPS_PROTO_I2C_NAV', 'GPS_PROTO_NAZA',
'GPS_PROTO_UBLOX_NEO7PLUS', 'GPS_PROTO_MTK', 'TELEMETRY_HOTT',
'TELEMETRY_IBUS', 'TELEMETRY_MAVLINK', 'TELEMETRY_SMARTPORT',
'TELEMETRY_CRSF', 'PWM_DRIVER_PCA9685', 'PITOT', 'OSD',

Replaced by using the following Python script, which replaces `ifdef FOO`, `define FOO`, `undef FOO` and `defined(FOO)`. Please, add a comment if you think some usages might have been missed by replacing these patterns.

```py
#!/usr/bin/python

import os
import re

REPLS = [
 'ACC',
 'GYRO',
 'BARO',
 'MAG',
 'LED_STRIP',
 'SPEKTRUM_BIND',
 'SERIAL_RX',
 'BLACKBOX',
 'GPS',
 'GPS_PROTO_UBLOX',
 'TELEMETRY',
 'TELEMETRY_LTM',
 'TELEMETRY_FRSKY',
 'CMS',
 'GPS_PROTO_NMEA',
 'GPS_PROTO_I2C_NAV',
 'GPS_PROTO_NAZA',
 'GPS_PROTO_UBLOX_NEO7PLUS',
 'GPS_PROTO_MTK',
 'TELEMETRY_HOTT',
 'TELEMETRY_IBUS',
 'TELEMETRY_MAVLINK',
 'TELEMETRY_SMARTPORT',
 'TELEMETRY_CRSF',
 'PWM_DRIVER_PCA9685',
 'PITOT',
 'OSD',
]

PATTERNS = {
    'define {0}(\W|$)': 'define USE_{0}\\1',
    'undef {0}(\W|$)': 'undef USE_{0}\\1',
    'ifdef {0}(\W|$)': 'ifdef USE_{0}\\1',
    'defined\\({0}\\)(\W|$)': 'defined(USE_{0})\\1',
}

def replace_in_files(root):
    def visit(arg, dirname, names):
        for n in names:
            p = os.path.join(dirname, n)
            if os.path.isfile(p):
                with open(p) as f:
                    data = f.read()
                new_data = data
                for r in REPLS:
                    for k, v in PATTERNS.items():
                        pattern = k.format(r)
                        repl = v.format(r)
                        new_data = re.sub(pattern, repl, new_data)
                if new_data != data:
                    with open(p, 'w') as f:
                        f.write(new_data)


    os.path.walk(root, visit, None)


replace_in_files('src')

```

Also, the following conditionals don't have the `USE_` prefix and are up for discussion. I'm not sure if they should be left as is or changed to the `USE_FOO` format:

- NAV
- FIXED_WING_LANDING
- AUTOTUNE_FIXED_WING
- ASYNC_GYRO_PROCESSING
- BOOTLOG
- BOOTLOG_DESCRIPTIONS
- STATS
- DASHBOARD_ARMED_BITMAP
- NAV_AUTO_MAG_DECLINATION
- NAV_GPS_GLITCH_DETECTION
- NAV_NON_VOLATILE_WAYPOINT_STORAGE

### CODE REVIEW

**Comment by digitalentity** [comment]
Good stuff @fiam 

Regarding the remaining defines:

I think we should change the following:

NAV -> `USE_NAV`
FIXED_WING_LANDING -> `NAV_FIXED_WING_LANDING`
ASYNC_GYRO_PROCESSING -> `USE_ASYNC_GYRO_PROCESSING`
BOOTLOG -> `USE_BOOTLOG`
STATS -> `USE_STATS`

Idea is that a certain "system" should prepended by `USE_`, while subcomponents and parameters related to this system should be prepended with the system define.

Similar thing we have for sensors:
```
#define USE_GYRO
#define USE_GYRO_MPU6500
#define MPU6500_SPI_BUS BUS_SPI1
```

**Comment by fiam** [comment]
Just added the new renames and rebased on top the development (there was a conflict in the REVO target). Should we add the python script in the tools directory for the future or does leaving it in a comment here suffice?

**Comment by digitalentity** [comment]
I think we could add the script just in case we need it in future

**Review by digitalentity — DISMISSED** [review]

**Comment by fiam** [comment]
Forgot to make the script correctly rename all conditionals in the `settings.yaml` file. Should be working fine now.

**Review by digitalentity — APPROVED** [review]

**Pull request merged**
