### PR TITLE
Limit Iterm on FW depending on stick position

### PR DESCRIPTION
**Pull request by DzikuVx**
It's not that simple to tune a FW for sharp turns especially when requested rates are close to the hardware limit. Too much or not enough FF leads to bounce-back or even follow-up when stick is released.

adnotacja 2018-11-18 190857

adnotacja 2018-11-18 191138

Limit in this PR depends on a stick position, not the fact if output is saturated like in case of MR controller since it's harder to determine if any servo is actually at a limit or not.

Experimental, not tested yet

### CODE REVIEW

**Comment by digitalentity** [comment]
Idea is to keep ITERM active when stick is not moving or moving slow and limit ITERM when stick deflection is high? Nice.

I would, however, act on `rateSetpoint`, not on stick position.

**Comment by DzikuVx** [comment]
@digitalentity this was my original goal, but I quickly realized that in case of too high rates that airplane can not reach, this would lead nowhere. The limit would trigger too soon or too late. On majority of planes this is not a case, but small agile race or freestyle wing can be affected.

**Comment by digitalentity** [comment]
@DzikuVx if rates are set properly, stick deflection or rateSetpoint won't make a difference.

**Comment by DzikuVx** [comment]
As long as set correctly yes. It's hard to guess the max rates and getting them from blackbox and manu mode is quite complex. Lets see it this will be a working and simplified solution

**Comment by digitalentity** [comment]
Then we should probably limit it to ACRO mode only. In ANGLE or automatic modes the `rateSetpoint` is disconnected from the stick and this logic won't make sense anyway.

**Comment by DzikuVx** [comment]
Good idea with limit to acro actually. I will make that happen

**Comment by DzikuVx** [comment]
@digitalentity now it should work only in Acro. Did not tested yet tho ;)

**Comment by digitalentity** [comment]
Looks good. Would be interesting to know how it behaves in testing

**Comment by DzikuVx** [comment]
@digitalentity flight tested. Works quite nice. Wing was stoping very nicely at the ends of sharp turns and rolls. No more bounceback or follow due to misbehaving Iterm. Even when roll rate was somehow 30% above max rate of the wing
Unfortunately there is no BB log since either SD card is broken on development on Omnibus F7 (again) or I misconfigured something.

Either way, I think it's working so either merge for 2.1 or we keep it for next release

**Review by digitalentity — APPROVED** [review]

**Comment by digitalentity** [comment]
Let's merge it

**Pull request merged**
