### PR TITLE
Navigation mods and SURFACE mode playground

### PR DESCRIPTION
**Pull request by digitalentity**
- Deprecate `POSHOLD_2D`
- `POSHOLD` box now implies `ALTHOLD`
- Initial cut on `SURFACE` modifier for navigation modes

### CODE REVIEW

**Comment by DzikuVx** [comment]
Finally!

**Comment by digitalentity** [comment]
As discussed on Slack, SURFACE modifier is checked only when activating ALTHOLD/POSHOLD mode - if enabled, it will change the behavior of navigation system and force it to use AGL postion for all modes except RTH and WP.

**Comment by digitalentity** [comment]
Tested. Works very well with new MSP rangefinder

**Comment by sparrow082** [comment]
What is the current recommended hardware for this setup?

**Comment by georgekucher** [comment]
Hi @digitalentity,
I think it doesn't work for me.
I fly Matek F722 f/w: 2.1 and US-100 sonar (connected via Arduino).
Althold and Surface modes were enabled at the same time. But still my  copter was able to land.
Please help. What am I doing wrong? I have logs, configs and video if needed.
Thanks in advance!

**Pull request merged**
