### PR TITLE
Adding altitude / sea (from GPS MSL)

### PR DESCRIPTION
**Pull request by OlivierC-FR**
In the Cli :
osd_layout 0 87 5 5 V

### CODE REVIEW

**Review by fiam — APPROVED** [review]

**Comment by digitalentity** [comment]
Do we have corresponding PR for configurator?

**Comment by OlivierC-FR** [comment]
I do not, I never managed to build the configurator on my PC, so tbh I didnt even try to do the corresponding PR.

**Comment by fiam** [comment]
I can take care of the configurator side. @OlivierC-FR wouldn't it be better if we could prepend a symbol to MSL altitude to tell them apart?

**Comment by OlivierC-FR** [comment]
> 
> 
> I can take care of the configurator side. @OlivierC-FR wouldn't it be better if we could prepend a symbol to MSL altitude to tell them apart?

I thought of this, but... to save a char and also, same as with the 3D speed, pilots using these will know who's who. Since altitude/sea is always the greater of the 2. Unless you fly below sea level, not too many places in the world. But I can make a new icon if you want, no prob.

**Comment by fiam** [comment]
Configurator PR https://github.com/iNavFlight/inav-configurator/pull/631

**Pull request merged**
