### PR TITLE
Moved target specific code out of pwm_mapping.c and timer.c into target files

### PR DESCRIPTION
**Pull request by martinbudden**
@digitalentity this is ready to merge in.

### CODE REVIEW

**Comment by digitalentity** [comment]
Thanks! This should add adding new targets more simple

**Comment by digitalentity** [comment]
pwm_mapping.c still has lots of target-specific #ifdefs (specifically pwmInit), but this can be cleaned up later.

**Comment by martinbudden** [comment]
@digitalentity , yes, still lots of target-specific stuff in `pwm_mapping.c`, but we're making progress.

I'm in the process of tidy up the `Makefile` so that it can be easily compared with the betaflight makefile - that will help a lot with the F4 support.

**Comment by digitalentity** [comment]
@martinbudden great! Thanks for looking into this.

**Pull request merged**
