### PR TITLE
add target RADIOLINKF722

### PR DESCRIPTION
**Pull request by radiolinkW**

### CODE REVIEW

**Comment by MrD-RC** [comment]
Are you currently working with any devs?

There is a policy for adding new hardware to INAV. https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by radiolinkW** [comment]
I have contacted mosca on discord and have sent 4 samples to two developers for testing @MrD-RC

**Comment by mmosca** [comment]
* [ ] Flash firmware
 * [ ] Calibrate
 * [ ] Orientation matches
 * [ ] Gyro working
 * [ ] Accel working
 * [ ] Baro working
 * [ ] Mag working (i2c)
 * [ ] Voltage correct
 * [ ] Current correct
 * [ ] UART1
 * [ ] UART2
 * [ ] UART3
 * [ ] UART4
 * [ ] UART5
 * [ ] Camera working
 * [ ] Video Out working
 * [ ] OSD working
 * [ ] LEDs working
 * [ ] Buzzer working
 * [ ] Motor/Servo outputs
 * [ ] Blackbox

**Comment by mmosca** [comment]
Motors work, but DSHOT does not work on motor 6. Needs to be set to different protocol.

**Pull request merged**
