### PR TITLE
Fix motor and beeper fc.V1

### PR DESCRIPTION
**Pull request by ted-rcnet**

### CODE REVIEW

**Comment by digitalentity** [comment]
@ted-rcnet ready to merge yet?

**Comment by ted-rcnet** [comment]
Hi,
No, I still have a problem with hardware revision ;)
Thanks

**Comment by digitalentity** [comment]
@ted-rcnet ok. Please let me know when it's ready.

**Comment by ted-rcnet** [comment]
Hi Konstantin,
is ready to merge
thanks

**Comment by ted-rcnet** [comment]
UP

**Pull request merged**
