### PR TITLE
OSD AHI pitch interval redraw option

### PR DESCRIPTION
**Pull request by breadoven**
Provides an option to draw the AHI at set pitch intervals throughout the full pitch range. The interval can be set from 1 to 30 degrees with the option disabled when set to 0. Default value is 10 degrees.

The AHI is drawn normally until pitch exceeds the set pitch interval after which it is drawn with the ends offset. The offset increases with increasing pitch and changes direction between climb and descent. The offset doesn't work for roll angles > 45 degrees simply because it becomes too distorted to be much use.

https://www.youtube.com/watch?v=h_iYlMv_4OA

### CODE REVIEW

**Comment by shellixyz** [comment]
Cool idea

**Comment by b14ckyy** [comment]
Is there a reason why this was never merged? :O

**Comment by breadoven** [comment]
> Is there a reason why this was never merged? :O

No reason really. Wasn't sure there was that much interest in it so it got overlooked I guess. Have you tried it ? I did notice occasional momentary ghosting of the horizon elements but otherwise it works as expected. Could be merged if required as is.

**Comment by b14ckyy** [comment]
As I understand the feature is optional right? if you resolve the conflicts I'd be happy to test it in flight.
I really like it and I can ask in the community if they want that too.

**Comment by b14ckyy** [comment]
Yep people seem to like it so far, based on the first comments :D 
I will load it on my Dart 250G and test on analog. 2 of my 6.0 Test pilots will test it on DJI WTF.os. Walksnail and HDZero TBD later.

**Comment by b14ckyy** [comment]
Tested analog today and looks good so far. https://youtu.be/8673w1ZInW4
But I suggest turning it off by default and make it an opt in feature. also adding a recommended value of 20 as a starting point as 10 is too narrow for each redraw. It does not use the full available AHI area and loops at too small angles already. 

waiting for the Digital pilots to test. 

One thing I am checking now is, that after flashing the artefact build to my F411-WSE I got MSP issues. 2 Packet errors per second and very slow MSP data transfer. F405SE does not seem to be affected. Will test another F411 and give feedback. Maybe something went wrong during rebase?

**Comment by breadoven** [comment]
Was there any final conclusion on merging this or not ?

**Comment by b14ckyy** [comment]
No feedback from the digital pilots yet because they had not much flight time recently but see no point why it would not work. 
With the feature off by default I think it can be merged and during next test release we will know if it works there as well.

**Pull request merged**
