### PR TITLE
Add EPE sanity check on GPS data for pos/vel/accBias corrections

### PR DESCRIPTION
**Pull request by digitalentity**
Bug reported on RCG:
>Today j update my quad 250, SPRACINGF3,with INAV 1.6 RC1, after 3 minutes and 28 secondes the quad fall on ground , motor on minimum 1070. j dont understand what append. Before j have the INAV 1.5.1 and j flight many time with no problem. J have BB but it s difficult for know what problem.

According to logs it a GPS glitch that messed up accelerometer bias correction and caused position estimator to go crazy.

### CODE REVIEW

**Comment by stronnag** [comment]
flashed, time to go flying ...

**Comment by digitalentity** [comment]
@stronnag please use latest commit - be2097e7043bb63675d8e6fe1b72007129a71932

**Comment by digitalentity** [comment]
Use caution - I might have introduced other bugs (more than I have already fixed)

**Comment by stronnag** [comment]
That's what I have.

**Comment by digitalentity** [comment]
Great! Good luck!

**Comment by stronnag** [comment]
On 18 February 2017 13:29:46 GMT+00:00, Konstantin Sharlaimov <notifications@github.com> wrote:
>Great! Good luck!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNavFlight/inav/pull/1302#issuecomment-280845673

Barrage of sensor lost alerts. I hope I will have some interesting Logs when I finish here.

**Comment by stronnag** [comment]
I'm not sure what was happening here (maybe the GPS is failing). Anyway, there are some logs at http://seyrsnys.myzen.co.uk/pos-est-accbias-protection/

* LOG00001.TXT : Mission flight, no problems;
* LOG00004.TXT : Brief PH, a few seconds in the craft lurches rapidly away from position. I know what this means (https://github.com/iNavFlight/inav/issues/431) and bail out of PH. Fortunately, I can just remember how to land manually (rarely do that on this machine, RTH is too convenient);
* LOG00006.TXT : Free flight, constant sensor failure alerts in the CGS. Unfortunately, mwp did not log XFRAME; a defect now corrected.

After LOG00006, the machine was left disarmed but powered on for about 15 minutes, with polled MSP into mwp; no further sensor failure alerts were reported. 

I was somewhat unprepared for this, not having a development branch hex with me that could be flashed to verify that is was not a local hardware fault or a failing GPS constellation. Tomorrow I shall attempt to do better.

For the record, this was the precious (600mm) tricopter (SP EVO, http://www.banggood.com/Ublox-NEO-M8N-Flight-Controller-GPS-with-Protective-Shell-for-PIX-PX4-Pixhawk-p-1005394.html GPS (non-Galileo capable M8N))

The missing logs (2,3 --- 5 has no useful content) are available on request. No sensor alerts in #.2, successful mission in #.3, followed by free flight with multiple sensor alerts.

**Comment by digitalentity** [comment]
@stronnag thanks for testing. 
In LOG00004.TXT there are two cases when GPS stopped reporting data and machine continued using intertial navigation only - which was apparently not enough to cover the huge 3.5sec gap in GPS data. As this PR touches nothing related to GPS hardware and considering perfect flight in LOG00001.TXT my best guess here is hardware issue.

**Comment by stronnag** [comment]
That's my conclusion as well. I'll try it again today, having reworked the GPS connectors, and on a different machine.

**Comment by stronnag** [comment]
Flew for 45 minutes (3 lipos) on the 600m tricopter after rewiring the GPS, and around 30 minutes on the 250mm quad. No problems at all. OTOH, the sensor loss altering was working magnificently yesterday.

**Comment by digitalentity** [comment]
Great! Merging then.

**Pull request merged**
