### PR TITLE
Debug trace facilities

### PR DESCRIPTION
**Pull request by digitalentity**
Requires manually assigned serial port (function mask 32768). Will output traces at 921600 baud rate.

### CODE REVIEW

**Comment by digitalentity** [comment]
I wonder if we can merge this as-is. @DzikuVx @fiam @stronnag @martinbudden what do you think?

**Comment by fiam** [comment]
Looks good to me. I can add the MSPv2 shared tracing one this is merged.

**Review by fiam — APPROVED** [review]

**Comment by digitalentity** [comment]
Added some examples. Tested, ready to merge.

**Comment by digitalentity** [comment]
image

**Pull request merged**
