### PR TITLE
IPF: Add yaw operand to go with pitch and roll

### PR DESCRIPTION
**Pull request by sensei-hacker**
The programming framework has flight:pitch and flight:roll.
This PR adds yaw to round out the options.

A matching PR for Configurator will be submitted also.

Tested in HITL and will be tested today in flight.

### CODE REVIEW

**Review by DzikuVx — CHANGES_REQUESTED** [review]
PLease update the Programming Framework Docs

**Comment by sensei-hacker** [comment]
Docs have been updated.

**Comment by DzikuVx** [comment]
@sensei-hacker please resolve conflicts

**Comment by sensei-hacker** [comment]
Conflicts have been resolved.  Also added the mixer profile items to the docs, to keep things aligned.

**Pull request merged**
