### PR TITLE
Landing detector: replace mc_min_fly_throttle with average throttle

### PR DESCRIPTION
**Pull request by digitalentity**
This is to continue work started in #249.

### CODE REVIEW

**Comment by theArchLadder** [comment]
Wow, first of all, thanks for giving me access to the inav repo! Feels like such an achievement! :smiley: 
Nice cleanup you did there, thanks!

I will try and come up with something to either replace or fix `hasHadSomeVelocity`, let me know if you have any ideas...

**Comment by theArchLadder** [comment]
hasHadSomeVelocity created corner-cases, rth activated on the ground for example, they where a pain to deal with, so i replaced it:
The first second or so is the most critical and imho has the highest risk of false-positive, so I added a new rule, the landing detector cannot pass before 1 second has elapsed. The average throttle waits until 1 second has passed before it starts to record, this will allow the throttle to stabilize before we start checking.

I have done some quick test flights and it looks good

**Comment by theArchLadder** [comment]
New setting added: `nav_mc_auto_disarm_delay` This is how many milliseconds all the tests has to be passed in a row before disarming. Default is 2000 (2 seconds).

I need help with a better name though! There already is a settings called `auto_disarm_delay`. I guess something with some of these words in it: auto_disarm landing_disarm safety timer timeout delay

Is it a timer, timeout or delay? I don't really understand the difference in this context tbh

**Comment by stronnag** [comment]
There's some otherwise uninspiring logs at http://seyrsnys.myzen.co.uk/inav-pr256/. All landings automated, started at 2000ms, then 1000ms, finally 500ms (hardly touched the grass before disarm). I suspect it could go lower, 2000ms is very conservative.

**Comment by theArchLadder** [comment]
@stronnag Big thanks again! Those logs turned out to be more interesting than i expected. Good news is that all flights would have been fine even without the timer.

Some highlights (writing this down mostly so i can remember :wink: ), each event only happened a single time in all those flights.
- Vertical speed went below 25 while in the air for 800ms or so, Looks like this is because your nav_land_slowdown_minalt and maxalt are only 2.5 meters apart and the velocity controller doesn't do a great job on that steep velocity ramp. isAtMinimalThrust still saved you here though.
- isAtMinmialThrust passed for 200ms or so, but this was with targetVel=-200 and vel=-180 or so, i have also seen that high descent speed can make the throttle a bit unstable, not really a problem though. But i will do some fine-tuning on this just to be safe.
- The vertical speed went above 25 while the copter was on ground, this made touchdown-to-disarm time go from 2 to 6 seconds.

**Comment by theArchLadder** [comment]
@gurkenfolie Would you like to test fly this? You said you needed help with git and how to build this, i'm no expert on git either but this is how i would do it:
1. Open a terminal in your inav directory.
2. Make sure you are on your master branch: **`git checkout master`**
3. Update your local master with the master on github: **`git pull`**
4. Create your own branch: **`git branch gurkenfolie`** 
5. Switch to the branch: **`git checkout gurkenfolie`**
6. List all remote branches **`git branch -r`**
7. Pull in the stuff talked about here to your local branch:
   **`git pull origin theArchLadder-landing-detector-avg-thr`**
8. Then you just have to run **`make`** as usual.

You can reduce the setting called `nav_mc_auto_disarm_delay` to as low as 100ms to get that "instant disarm", but please understand that using a lower time on this increases the risk of your copter disarming in the air. Post a blackbox log for me to review before you reduce this setting, or if you like to live dangerosly, just go for it :stuck_out_tongue_winking_eye: You have been warned though!

EDIT: Remember to turn `nav_disarm_on_landing` on.

**Comment by stronnag** [comment]
There's yet more similarly dull logs logs at http://seyrsnys.myzen.co.uk/inav-pr256/. All landings with 500ms delay (instant enough for me).
1168/1 - 'near' RTH from 30m
1169/1 - 'distant RTH from 16m
1171/1 - 'near' RTH from 34m

Settings (CLI dump) in tri_nav_m8n_fp.txt

**Comment by theArchLadder** [comment]
@stronnag Thanks! All of those performed great :+1:

**Comment by stronnag** [comment]
Yes, I've very impressed with it. I'd like to try it on a windy day, but that doesn't look likely in the short term.

**Comment by gurkenfolie** [comment]
thx @thearchladder, it was really helpful, i compiled the hex and tomorrow i will test it on my 250 and will provide the blackbox log.

**Comment by stronnag** [comment]
Flew multiple flights with 500ms delay today. Boringly successful. I can't do manual landings any more.

**Comment by gurkenfolie** [comment]
[blackbox_log_2016-06-06_113339.TXT](https://github.com/iNavFlight/inav/files/300128/blackbox_log_2016-06-06_113339.TXT)

here the blackbox log. first log is with 500ms, second one with 200ms, third and fourth one with 100ms. 
one thing i noticed is when flying a little bit longer, it took more time to disarm when landed. 
as for now i can only provide up to 2mb log, i´m still waiting for my external logging device.

nice work so far!

**Comment by theArchLadder** [comment]
@gurkenfolie Thanks!
- 1/4: The vertical velocity hardly changed once you where on the ground, strange.
- 2/4 and 3/4: Looked like it bounced on landing, what kind of surface did you land on?

Could you please also give the specs of your copter, and a cli dump?

**Comment by gurkenfolie** [comment]
[5.6. test.txt](https://github.com/iNavFlight/inav/files/300923/5.6.test.txt)
here is my cli dump. my copter is a 260 x (almost h) quad, 1806 motors, 5045x3 DAL propellers, running on 3s, battery mounted under the quad. this is an old picture, now its running on a naze32 with bmp280.
dsc08990

i landed on concrete, and yes, the quad bounced a little bit, i think it is because it landed on the battery (no standoffs for landing). first landing was on 3-5cm grass.

**Comment by theArchLadder** [comment]
@gurkenfolie Thanks again, the biggest problem for you seems to be that your FC thinks the vertical speed is over 25 after it has landed.
isAtMinminalThrust does fail with all those bounces, it would be nice to somehow get rid of those bounces, but not sure how. I have not done any landings on hard surfaces, perhaps a lower landing speed is needed... I will do some testing.

**Comment by gurkenfolie** [comment]
i will do some rth landings on concrete and grass from different altitudes. it seems that the higher the altitude is where the quad starts to descend, the slower the landing speed is (this was the previous inav behaviour, i dont know if this is still the behauviour with your code changes). i will post the log later.

**Comment by theArchLadder** [comment]
It has changed but that was before this pull request. It should behave similar with defaults though.

Looks like you have changed these settings:
`set nav_land_slowdown_minalt = 150`, default: 500
`set nav_land_slowdown_maxalt = 500`, default: 2000
Vertical speed ramps from 200cm/s at nav_land_slowdown_maxalt to 50cm/s at nav_land_slowdown_minalt.

EDIT: It would actually be better for me if you used a longer nav_mc_auto_disarm_delay so i can see what happens after touchdown, 1000-2000ms would be nice for debugging purposes.

**Comment by gurkenfolie** [comment]
yes, i changed it because my nav_rth_altitude is at 500cm (i´m flying in a park, 20m is way too high). before this setting, the quad sometimes hit the ground really hard during rth landing. this was on stock inav 1.1.  
i will set mc_auto_disarm_delay to 1000ms.

**Comment by theArchLadder** [comment]
If you use default settings your quad should descend with -50cm/s from 500cm. Your change makes it descend faster.

**Comment by gurkenfolie** [comment]
yes, i wanted it to descend faster, but only to the set nav_land_slowdown_minalt value (150cm). 10 second descend from 5 meter is too long in my opinion (for my little 260 quad, for bigger quads it might be suitable).  

it shouldnt make a difference to the speed which the quad has when it lands on the ground (because the quad powers up to slow down descend - 150cm should be sufficient for this, especially on a small quad)?

**Comment by theArchLadder** [comment]
I agree that it takes to long with default settings, the thing is that the baro can drift several meters, so when your quad may think it is 4 meters over ground when in fact it's just 1 meter over ground. The current altitude controller is not that accurate either.

**Comment by gurkenfolie** [comment]
[blackbox_log_2016-06-07_145129.TXT](https://github.com/iNavFlight/inav/files/302643/blackbox_log_2016-06-07_145129.TXT)
 1/11 1000ms
2/11 1000ms
3/11 -
4/11 200ms
5/11 200ms
6/11-
7/11 200ms, min_alt max_alt default (500/2000), quad started ascending when rth was triggered
8/11 -
9 /11 -
10/11 1000ms, min_alt max_alt default (500/2000)

landing alwas on concrete (except one landing on grass, the quad didnt land on the concrete but 80cm away on grass, dont remember which landing). the quads bounce is maximum 5cm. takes sometimes 3-4 seconds to disarm. the grass landing immediately disarmed, no bounce.
i will provide some logs with only grass landings later/tomorrow.

**Comment by bk79** [comment]
Just my two cents...when the ground is touched the accelerometer should
read a spike in the read value that then gets stable to 9.8 in module  now
unless you have a very really soft landing in any case we should be able to
read the spike in the acceleration reading..is it possible to read a log of
when the landing happens to defineva threshold for the event?
Il 07/giu/2016 15:03, "theArchLadder" notifications@github.com ha scritto:

**Comment by DaleKramer** [comment]
I do want to take advantage of this latest and interesting algorithm to detect landing.  I believe it would allow me to land on a sideslope that is  almost at the tip over angle of my multicraft.  

I just do not want the landing detector to DisArm my multicraft after landing.  I just want it to slowly set the throttle the FC sees to min_command until I move the throttle stick again or I disarm in the manner I normally disarm.  

Also, I think that once a landing is detected it still needs to spool down at a user settable rate to min_command  (based on each individual multicraft physical characteristics), that way the craft could settle on a side slope smoothly.   

And, I think that at any point of the landing, including after it has been sitting on the ground for a while, I should be able to takeoff again just by increasing my throttle.  This helps prevent an incorrect landing detection while I am flying from causing a crash.

Just my wish list :)

**Comment by gurkenfolie** [comment]
does this work with inav 1.2?

**Comment by theArchLadder** [comment]
@bk79 I think that's a bad idea, the acceleration spike while doing a slow soft landing in grass will be very small and if we tune it to detect that i think we will have a big risk of false-positives (disarm in air).

@DaleKramer Set `nav_disarm_on_landing = OFF` and you will sort of have what you want. The altitude controller will slow down the motors when the copter is sitting on the ground. This PR is about auto-disarm.

@gurkenfolie I have not tested it lately but i see no problems.

@digitalentity How would you like to continue from here? As you know my time for inav is very limited these days. This has been flight tested by multiple people and seems to work fine, do you think this is ready to be merged? `nav_mc_auto_disarm_delay` needs a better name though. And maybe we should have a OR condition that checks if throttle is at min_throttle+1, but it seems to work fine anyway... I really wish i had more time for inav!

**Comment by bk79** [comment]
@theArchLadder i'll soon be able to make some trends to let you know what
could be an acceptable threshold in any case unless you are at 0 vertical
speed and perfectly flat surface the spike is there
Il 08/lug/2016 09:18, "theArchLadder" notifications@github.com ha scritto:

**Comment by theArchLadder** [comment]
@bk79 Perhaps it could work, sure, but what would be the benefit over the approach we are using now? To me it just seems more risky without any real benefit.

**Comment by bk79** [comment]
It should be in AND with the actual logic in order to increase safety not
to replace it
Il 08/lug/2016 09:25, "theArchLadder" notifications@github.com ha scritto:

**Comment by stronnag** [comment]
Please can we just have this PR included in master. Unlike some recent pulls, it has been extensively tested and works really well (heavily tested on multiple vehicles over the last 5+ weeks) .

I would prefer that the well tested extant functionality was included 'as is' and any further optimisations tested on the post-1.2 development branch.

**Comment by digitalentity** [comment]
@stronnag merged

**Comment by theArchLadder** [comment]
@digitalentity Nice. Perhaps `nav_mc_landing_disarm_delay` would be a better name for the setting? It's confusing to have both `nav_mc_auto_disarm_delay` and the failsafe setting `auto_disarm_delay`

**Pull request merged**
