### PR TITLE
Allow ANDing of multiple channel ranges in mode activation conditions

### PR DESCRIPTION
**Pull request by digitalentity**
Continuation and improvement of #258

### CODE REVIEW

**Comment by digitalentity** [comment]
Moved  `modeActivationOperator` to profile (to be close together with `modeActivationConditions`).

**Comment by digitalentity** [comment]
@iforce2d can you please review this?

**Comment by digitalentity** [comment]
Tested and working

**Comment by iforce2d** [comment]
I looked over this yesterday and forgot to reply, sorry! From looking at the code it seemed fine.

**Comment by digitalentity** [comment]
@iforce2d no problem, I just tested it in flight and merged - it's working fine! Thanks, now those who don't have a 8+ channel TX have another option.

**Comment by iforce2d** [comment]
I tested this today, it works fine. Thanks!

**Pull request merged**
