### PR TITLE
aligned KAKUTEH7WING target with manufacturer docs

### PR DESCRIPTION
**Pull request by paul-fornage**
Super simple fix for [this issue](https://github.com/iNavFlight/inav/issues/9635).

!! This risks breaking older builds that attached sensors to the FC in accordance with the iNav target and not the manufacturer docs !!

The Kakute H743 Wing target in iNav lists the Pitot sensor as being on I2C bus 1, but HolyBro says to use I2C bus 2.

[Manufacturer Manual](https://cdn.shopify.com/s/files/1/0604/5905/7341/files/Holybro_KakuteH743-Wing_Manual_v1.0_C.pdf?v=1693393206) says I2C bus 1 is just for compass, and other peripherals should use I2C bus 2.

Also the wiring diagram uses I2C bus 2:
image

This PR just changed the pitot, rangefinder, and external temp sensors to I2C bus 2

### CODE REVIEW

**Comment by sensei-hacker** [comment]
Paul, I believe you said you tested this with a pitot in the external i2c plug, labeled i2c 2. Correct?

Note - the key line in the manual is probably:
3x I2C (I2C1 and I2C2 for external devices , I2C4 for onboard sensors )

**Comment by vincentpoont2** [comment]
@DzikuVx Our I2C1 is designed to be use with our GPS+Compass, so I think it make sense to make this change.

**Comment by mmosca** [comment]
Can we add a remark to what sensors go in which i2c bus/plug to docs/boards/KAKUTEH7WING.md ?

**Comment by paulwrath1223** [comment]
> Can we add a remark to what sensors go in which i2c bus/plug to docs/boards/KAKUTEH7WING.md ?

There currently isn't a doc file for this board. I don't mind making one, now that I have the board and know the system better than I wanted to, but should I put it in a separate PR?

**Pull request merged**
