### PR TITLE
Add STM32 lib files

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden why this PR is necessary? Why merging such a huge PR without discussion and even without a description?

**Comment by martinbudden** [comment]
It's part of PR https://github.com/iNavFlight/inav/pull/2225 - conversion to using the betaflight make system. These lib files are required for that.

You're right though, I shouldn't have merged this without discussion. I thought it harmless because it doesn't actually effect anything. I apologise.

To my defence, we did agree to move to the betaflight build system (with particular reference to speeding up the travis builds) in a slack discussion.

**Comment by digitalentity** [comment]
@martinbudden we should eventually clean up the libs - there is much redundancy there. I also suggest that migration to Betaflight's build system is postponed until 1.9

**Comment by stronnag** [comment]
It's highly intrusive if it's the bf make system. Breaks platforms with package managers providing a validated cross compiler.

**Comment by digitalentity** [comment]
For the record. I'm highly against any PR that will download and install a toolchain different from one present in the OS. Makefile may veify if the toolchain of recommended version in present in the system and warn user about possible issues.

**Comment by martinbudden** [comment]
This is a bit more controversial than I thought. OK, let's postpone until 1.9 and that will give us time to discuss it properly. In my view bf make system offers (at least) the following:

1) Faster travis build time
2) Having the same (or nearly thesame) system as betaflight reduces maintenance
3) Makes it easier to pick up betaflight build optimisations (eg STM32 low-level libraries, F7 build options etc)

**Comment by fiam** [comment]
I  general PRs shouldn't be merged without, at least, discussing it with someone else. I don't it's OK to merge your own stuff without giving the rest of the contributors a chance to look for potential problems. In fact, if you check my PRs I very rarely merge them myself and I believe everyone should try to do the same (not that I would demand that, but it would be nice).

Now, regarding this specific PR. Adding 2600 files and 2M lines of code is not harmless. That's a freaking 135MB patch going into the git history, which means now everyone who clones the repo has to download and keep it stored locally. My `.git` directory went from 118MB to 167MB just after pulling from the development branch: a 40% increase! Looking only at the sheer size of the change, this is something that needs to be throroughtly discussed. At it has to be a good reason to import so much stuff in the repo (much of it in duplicated files in this case).

Let me be clear: I appreciate your  efforts bridging the gap between Betaflight and INAV. Having the codebases as close as each other as possible allows easier "cross pollination" by just moving patches around. This way, INAV can take advantage of improvements and fixes done in Betaflight as well as the other way around.

However, this doesn't mean we should blindly merge changes in without discussing them first. In this specific instance, I'd prefer to see a PR which implements the whole migration and it's merged into development at once. There's no reason to merge some files first, then some others, etc... I'm sure you get the idea.

Finally, regarding the code itself: I'd like to see some deduplication. I know disk space is cheap these days, but that's no excuse for wasting it. There are a bunch of duplicated folders for each MCU family that should be put into the repo just once. You can use include paths or symlinks, that's up to you, but having the same file in 5 different places to simplify make rules is just a poor practice.

**Comment by martinbudden** [comment]
My apologies again. I made a mistake here. It won't happen again.

**Comment by fiam** [comment]
@martinbudden No need to apologise. We all make mistakes, it's human nature.

Now, regarding the migration to the ßF build system. Would you mind opening an issue so we can discuss it? It seems there's a bunch of messy stuff in there. For example, headers are pulled from `./lib/main/STM32Fx/Drivers/CMSIS/DSP_Lib` but the code in .c files is compiled from `lib/main/DSP_Lib/`. I'd rather see issues like this fixed first in ßF and then the build system imported into INAV.

**Comment by digitalentity** [comment]
@martinbudden no need to apologise. The only mistake I see is merging this without a discussion - quite a minor one though.

My few thoughts on moving to BF build system:
1. It should not install any compilers or any other software. Environment that's pre-installed on the system should be used.
2. It should avoid code duplication and pulling it unused libraries - i.e. DSP Lib & BSP packages are not used in INAV - why wasting space for them?
3. I'd like to have it as a bunch of PRs against a separate branch. Once it's stable and clean - squash and merge to development. This way won't pollute the history.

**Pull request merged**
