### PR TITLE
Fix for attitude drift with async gyro processing

### PR DESCRIPTION
**Pull request by digitalentity**
Bug Introduced by #421 
Discovered by @stronnag - https://github.com/iNavFlight/inav/pull/421#issuecomment-258627700

### CODE REVIEW

**Comment by digitalentity** [comment]
Bench-tested with all `async_mode` values. No issues with attitude drift.

**Comment by stronnag** [comment]
Excellent, I'll fly this later today.

**Comment by digitalentity** [comment]
@stronnag cool, thanks!
If we ever meet, remind me to buy you a beer :smiley:

**Comment by DzikuVx** [comment]
and one from me :)

**Comment by stronnag** [comment]
Flight tested (all async modes). All flyable, some better than others in levelling / nav modes. Analysis and logs to follow.

**Comment by stronnag** [comment]
**Async Mode Test**

All tests in horizon mode with navigation features enabled.

```
# INAV/SPRACINGF3 1.4.0 Nov  6 2016 / 11:06:36 (cf23e87)
```

Log: http://seyrsnys.myzen.co.uk/2016-11-06/async-modes_2016-11-06.TXT

| Index | Settings | Effect | Log Replay |
| --- | --- | --- | --- |
|  | gyro_sync_denom=8 gyro_lpf=256HZ |  |  |
| 1 | async_mode = NONE | Just like 1.3. No drift, stable PH, accurate WP. Disarm instantly on landing | https://vimeo.com/190454410 |
| 2 | async_mode = GYRO | Similar. No drift, stable PH, accurate WP. Failed to disarm on landing | https://vimeo.com/190454926 |
| 3 | async_mode = GYRO | Disarms on landing this time | https://vimeo.com/190455110 |
| 4 | async_mode = ALL | Flyable, noticeable oscillations on PH and auto land. Disarms on landing | https://vimeo.com/190455568 |
| 5 | async_mode = GYRO | Disarms on landing eventually | https://vimeo.com/190456025 |
|  | gyro_sync_denom=1 gyro_lpf=188HZ |  |  |
| 6 | async_mode = GYRO | Smooth,instant disarm on landing | https://vimeo.com/190456582 |
| 7 | async_mode = GYRO | Smooth,instant disarm on landing | https://vimeo.com/190456730 |
| 8 | async_mode = GYRO | Smooth,instant disarm on landing | https://vimeo.com/190457250 |
| 9 | async_mode = GYRO | Smooth,instant disarm on landing | https://vimeo.com/190457661 |

So it looks like:

```
async_mode = GYRO
gyro_sync_denom = 1
gyro_lpf = 188HZ
```

is the clear favourite for best all around self-levelling / nav modes performance _on this frame_. The more precious vehicles will have to wait until next weekend for a test (unless we introduce something else dangerous in the meantime ....).

**Comment by DzikuVx** [comment]
That more less confirms that keeping ACC and ATTI with PID loop is the best for nav purposes.

**Comment by digitalentity** [comment]
@stronnag thanks for testing, very thorough report, as usual!
@DzikuVx, here are my thoughts on slight degradation of performance with reduced ACC/ATTI rates:
1. Acceleration in Earth frame is calculated from attitude
2. Position estimation is done based on acceleration in EF and it's done at 50Hz rate.

Theoretically navigation performance shouldn't decrease if we keep ACC/ATTI running at 50Hz rate of higher. However we need to account for this:
1. PID loop calculates self-leveling based on attitude and does so at 500-1000Hz rate

If attitude doesn't change (updated at low rate) self-leveling error doesn't decrease and PID loop continues to push the machine trying to reach the target angles and is very likely to overshoot causing oscillations in navigation modes that are very dependent on tight control over attitude.

The effect is probably less noticable on tiny machines with little inertia and a lot of power.

There's also a phase difference between ACC/ATTI updates and navigation updates, in worst case navigation might be looking at data that's 20ms old bringing overall position estimation delay to 40ms which is quite a lot.

Bottomline: there is room for improvement, but not much. Probably #768 should be our next target - make everything synchronised to gyro updates and to each other.

**Comment by stronnag** [comment]
I flew this on my larger, heavier (420mm) quad 

```
# INAV/SPRACINGF3 1.4.0 Nov 10 2016 / 18:49:44 (ec8d3ea)
set gyro_sync = ON
set gyro_sync_denom = 8
set async_mode = GYRO
set motor_pwm_rate = 2000
set gyro_lpf = 256HZ
```

No adverse affects observed (nav and self level performance OK). Unfortunately, the logs are corrupt.

**Comment by DzikuVx** [comment]
Great to hear it @stronnag

**Comment by digitalentity** [comment]
Happy to hear! Thanks @stronnag

**Pull request merged**
