### PR TITLE
Add support for ICM42605 and ICM42688P IMUs

### PR DESCRIPTION
**Pull request by digitalentity**
This is an almost direct port of https://github.com/betaflight/betaflight/pull/9316 and https://github.com/betaflight/betaflight/pull/10706.

Those are indeed very interesting gyros with a lot of hardware capabilities we currently not use, like configureable order of the DLPF - chip defaults to 2'nd order on both gyro and accel. Switching to 3'rd order may improve noise rejection.

Not tested yet

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested on MATEKF765SE target with ICM42605 gyro. Works. ICM42688-P untested, but should work also.

**Review by DzikuVx — APPROVED** [review]

**Comment by digitalentity** [comment]
Tested with ICM42688-P as well

**Comment by MATEKSYS** [comment]
Thanks. ICM42605 and ICM42688-P both work normal.

**Comment by digitalentity** [comment]
Ok, this should be final. Configurator support also needed

**Comment by hydra** [comment]
@digitalentity Enjoy my code! 😄

**Pull request merged**
