### PR TITLE
SDCard & I2C bugfixes

### LINKED ISSUE #507: INAV 1.2-RC2 does not log to SD on SP-EVO
Initial report on RCG: Originally Posted by chuckstarck 
Using SP Racing EVO, SD board on bottom of controller.
1.2 RC
I've cleared and formatted the card, then after a flight I get a scrambled FAT and windows wants the card formatted, that's over and over.
So decided to put a couple files on the card first, that worked one time, got a BB file, not useful but got a file.
It writes "LOGS" and "FREESPACE" and leaves the .jpg file there but there is nothing in the LOGS folder
Is this working for anyone?
It worked with 1.1 and CF but now with 1.2, just driving me nutz along with having a very hard time getting the PID"s nailed down. I can't even find the nails to do it.
If I could get BB to work, then perhaps I could get some help with the wobble/wobble/wiggle/wiggle.

thanks in advance

### PR DESCRIPTION
**Pull request by digitalentity**
1. Fix uninitialised I2C usage on F3
2. Fix incorrect SPI pullup init when using SDCard
3. Fix DMA clock not being enabled for SDCard
4. Fix Blackbox deleting the file after finishing the log

Closes #507

### CODE REVIEW

**Comment by digitalentity** [comment]
If anybody has an EVO it would be great if you can test this PR so I can merge it.

**Comment by martinbudden** [comment]
@digitalentity , @hydra is sending me an EVO, so I'll be able to test this when it arrives.

**Comment by hydra** [comment]
@martinbudden sorry, i sent you an SPRACINGF3, not an EVO.  Perhaps there was a miscommunication.  I mentioned I had a box of repaired ACRO and DELUXE boards and sent you one from that.  If you like I can send you a prototype F3 EVO board though, I have a few of those that are fine for development purposes.

**Comment by martinbudden** [comment]
@hydra , no worries. Thankfully the problem we were having with the SPRACINGF3 has been solves, as you know it was finally diagnosed as a GPS startup timing problem. But the SPRACINGF3 will be used for further testing.

A prototype F3 EVO would certainly come in useful for testing in future. I'm very conscious that I'm only able to test on a handful of the available targets so anything that enables me to test on more targets is most welcome. Thanks.

**Pull request merged**
