### PR TITLE
SITL: implemented built-in serial receivers support in SITL, implemented FC proxy mode, updated SITL docs

### PR DESCRIPTION
**Pull request by RomanLut**
- Implemeneted built-in host's serial port mapping for serial receiver in SITL (ser2tcp is not needed anymore)
- Implemented mode where any inav/betaflight FC with receiver attached can be used as proxy to connect RC Controller to SITL
- Updated SITL docs https://github.com/RomanLut/inav/blob/submit-serial-receiver/docs/SITL/SITL.md

Requires Configurator changes https://github.com/iNavFlight/inav-configurator/pull/1849

Tested under 

**Windows**
- SBUS receiver connected throught inverter to CH340 USB-to-serial
- ELRS receiver connected to  CH340 USB-to-serial
- Inav 7.0 flight controller with ELRS receiver attached
- Inav 7.0 flight controller with SBUS receiver attached
- Betaflight 4.3 AIO FC with Frsky receiver

**Linux (Arch, aarch64, riscv64, x86_64; Alpine ia32)**
- CRSF (ELRS) via pl2303 (FTDI clone)
- IBUS via CP2102
- FC Proxy (Sbus RX/TX)

**FreeBSD (x64_64)**
- IBUS via CP2102
- CRSF (ELRS) via pl2303 (FDTI clone)

**MacOS (x64_86 kvm/qemu)**
- IBUS via CP2102

Please see https://github.com/RomanLut/inav/blob/submit-serial-receiver/docs/SITL/SITL.md for changes.

### CODE REVIEW

**Review by stronnag — CHANGES_REQUESTED** [review]
NAK: This will not (does not) work in Linux, nor will it work in MacOS.

**Comment by stronnag** [comment]
1. It does work in FreeBSD, as you can just but the baud rate into the termios structure.
2. For Linux, you must use `termios2` / `BOTHER` to use non-standard rates (e.g. 400k, 100k). This uses the naive baud rate (vice `B_*` constants).
3. For MacOS, you need to use the `IOSSIOSPEED,` `ioctl` for non-srandard baud rates.

Working example in https://github.com/stronnag/bbl2kml/tree/master/tools/ser2tcp/eg_c or I can make a PR to your repo (let me know if you'd prefer that option).

**Comment by RomanLut** [comment]
> I can make a PR to your repo (let me know if you'd prefer that option).

This is what I actually was hoping for. I am not Linux/MasOs user and will not be able to test it. Please make a PR.

**Comment by stronnag** [comment]
> > I can make a PR to your repo (let me know if you'd prefer that option).
> 
> This is what I actually was hoping for. I am not Linux/MasOs user and will not be able to test it. Please make a PR.

OK, I'll try and get something done this weekend.

**Comment by RomanLut** [comment]
> Is it intentional that both the serial device node (` dev/cuaU0`) and TCP `[::]:5762` are connected to `UART3` below?

Yes, why not? User can use TCP Port or COM port without changing configuration, both will work.

**Comment by RomanLut** [comment]
> OK, I'll try and get something done this weekend.

Merged pull request https://github.com/RomanLut/inav/pull/12 to branch RomanLut:submit-serial-receiver.
Retested on Windows  with SBUS receiver and INAV FC Proxy - all works.

**Review by stronnag — APPROVED** [review]
I'm content. Nice to get rid of the external serial bridge for physical RX.

**Comment by stronnag** [comment]
@DzikuVx apropos testing, in addition to @RomanLut 's Windows testing:
# Test Status

## Linux (Arch, aarch64, riscv64, x86_64; Alpine ia32)

### CRSF (ELRS)

via `pl2303` (FTDI clone)

```
$ ./inav_7.0.0_SITL --path ~/sitl-eeproms/crsf-eeprom.bin --serialuart=3 --serialport /dev/ttyUSB0 --baudrate 400000
INAV 7.0.0 SITL (5a785a44)
[SYSTEM] Init...
[SIM] No interface specified. Configurator only.
[SERIALPROXY] Connected /dev/ttyUSB0 to UART3
[EEPROM] Loaded '/home/jrh/sitl-eeproms/crsf-eeprom.bin' (32768 of 32768 bytes)
[SOCKET] Bind TCP [::]:5760 to UART1
[SOCKET] Bind TCP [::]:5761 to UART2
[SOCKET] Bind TCP [::]:5762 to UART3
[SOCKET] [::1]:40896 connected to UART1
[SOCKET] [::1]:40896 disconnected from UART1
```

### IBUS

via `CP2102`

```
$ ./inav_7.0.0_SITL --path ~/sitl-eeproms/ibus-eeprom.bin --serialuart=3 --serialport /dev/ttyUSB0 --baudrate 115200
INAV 7.0.0 SITL (5a785a44)
[SYSTEM] Init...
[SIM] No interface specified. Configurator only.
[SERIALPROXY] Connected /dev/ttyUSB0 to UART3
[EEPROM] Loaded '/home/jrh/sitl-eeproms/ibus-eeprom.bin' (32768 of 32768 bytes)
[SOCKET] Bind TCP [::]:5760 to UART1
[SOCKET] Bind TCP [::]:5761 to UART2
[SOCKET] Bind TCP [::]:5762 to UART3
[SOCKET] [::1]:37446 connected to UART1
[SOCKET] [::1]:37446 disconnected from UART1
```

### FC Proxy (Sbus TX)

```
$ ./inav_7.0.0_SITL --path ~/sitl-eeproms/sim-eeprom.bin --serialport /dev/ttyACM0 --fcproxy
INAV 7.0.0 SITL (5a785a44)
[SYSTEM] Init...
[SIM] No interface specified. Configurator only.
[SERIALPROXY] Using proxy flight controller on /dev/ttyACM0
[EEPROM] Loaded '/home/jrh/sitl-eeproms/sim-eeprom.bin' (32768 of 32768 bytes)
[SOCKET] Bind TCP [::]:5760 to UART1
[SOCKET] Bind TCP [::]:5761 to UART2
[SERIALPROXY] Requesting RX config from proxy FC...
[SERIALPROXY] Setting RX config on proxy FC...
```

Correct movement of sticks etc. seen in Configurator.

## FreeBSD (x64_64)

### IBUS

via `CP2102`

```
$ ./inav_7.0.0_SITL --path ~/sitl-eeproms/ibus-eeprom.bin --serialuart=3 --serialport /dev/cuaU0 --baudrate 115200
INAV 7.0.0 SITL (5a785a44)
[SYSTEM] Init...
[SIM] No interface specified. Configurator only.
[SERIALPROXY] Connected /dev/cuaU0 to UART3
[EEPROM] Loaded '/home/jrh/sitl-eeproms/ibus-eeprom.bin' (32768 of 32768 bytes)
[SOCKET] Bind TCP [::]:5760 to UART1
[SOCKET] Bind TCP [::]:5761 to UART2
[SOCKET] Bind TCP [::]:5762 to UART3
[SOCKET] [xxxx:xxxx:xxxx:0:18b0:85ff:zzzz:zzzz]:36908 connected to UART1
[SOCKET] [xxxx:xxxx:xxxx:0:18b0:85ff:zzzz:zzzz]:36908 disconnected from UART1
```

### CRSF (ELRS)

via `pl2303` (FDTI clone)

```
./inav_7.0.0_SITL --path ~/sitl-eeproms/crsf-eeprom.bin --serialuart=3 --serialport /dev/cuaU0 --baudrate 400000
INAV 7.0.0 SITL (5a785a44)
[SYSTEM] Init...
[SIM] No interface specified. Configurator only.
[SERIALPROXY] Connected /dev/cuaU0 to UART3
[EEPROM] Loaded '/home/jrh/sitl-eeproms/crsf-eeprom.bin' (32768 of 32768 bytes)
[SOCKET] Bind TCP [::]:5760 to UART1
[SOCKET] Bind TCP [::]:5761 to UART2
[SOCKET] Bind TCP [::]:5762 to UART3
[SOCKET] [xxxx:xxxx:xxxx:0:18b0:85ff:zzzz:zzzz]:59058 connected to UART1
[SOCKET] [xxxx:xxxx:xxxx:0:18b0:85ff:zzzz:zzzz]:59058 disconnected from UART1
```

Correct movement of sticks etc. seen in Configurator.

## MacOS (x64_86 kvm/qemu)

### IBUS

via `CP2102`

```
$ ./inav_7.0.0_SITL --path ~/sitl-eeproms/ibus-eeprom.bin --serialuart=3 --serialport /dev/cu.usbserial-0001 --baudrate 115200
INAV 7.0.0 SITL (5a785a44)
[SYSTEM] Init...
[SIM] No interface specified. Configurator only.
[SERIALPROXY] Connected /dev/cu.usbserial-0001 to UART3
[EEPROM] Loaded '/Users/jrh/sitl-eeproms/ibus-eeprom.bin' (32768 of 32768 bytes)
[SOCKET] Bind TCP [::]:5760 to UART1
[SOCKET] Bind TCP [::]:5761 to UART2
[SOCKET] Bind TCP [::]:5762 to UART3
[SOCKET] [::ffff:172.31.0.244]:51594 connected to UART1
[SOCKET] [::ffff:172.31.0.244]:51594 disconnected from UART1
```
Correct movement of sticks etc. seen in Configurator.

CRSF not tested as environment does support pl2303/400000 baud (however, `stty` reports correct tty settings after `SITL` started with ` --serialuart=3 --serialport /dev/cu.usbserial-5D20 --baudrate 400000`

```
$ stty < /dev/cu.usbserial-5D20
speed 400000 baud;
lflags: -icanon -isig -iexten -echo
iflags: -icrnl -ixon -ixany -imaxbel -brkint
oflags: -opost -onlcr -oxtabs
cflags: cs8 -parenb clocal
min
0
```

**Comment by RobertoD91** [comment]
Just wanted to say thanks for writing:
> Please note that 100000(SBUS) and 420000(CRSF) are non-standart baud rates which may not be supported by some USB-to-serial adapters. FDTI and CH340 should work. CP2102/9 does not work.

It saved me from a big headache.

**Comment by stronnag** [comment]
Retested on Linux ... time to merge.

**Pull request merged**
