### PR TITLE
Added idle interrupt callback to UART driver (Needed for Spektrum SRXL2 support)

### PR DESCRIPTION
**Pull request by MiguelFAlvarez**
This enables the UART Idle interrupt option, and adds a serialIdleCallbackPtr option for the UART driver. This change is needed in order for SRXL2 to work. Will make a pull request for that once this is approved.

### CODE REVIEW

**Comment by digitalentity** [comment]
I'm concerned about possible portability issues if a platform doesn't support idle interrupt and also race condition issues. Interrupts arrive asynchronously from the scheduler and should be handled in as little time as possible.

If there is absolutely no way to avoid the  interrupt, I advise that you set the `volatile` flag in the IRQ handler and poll for it in the RX code.

**Comment by MiguelFAlvarez** [comment]
> I'm concerned about possible portability issues if a platform doesn't support idle interrupt and also race condition issues. Interrupts arrive asynchronously from the scheduler and should be handled in as little time as possible.
> 
> If there is absolutely no way to avoid the interrupt, I advise that you set the `volatile` flag in the IRQ handler and poll for it in the RX code.

It might help to have a sneak peak at what the idle callback in SRXL2 looks like.

```
static void srxl2DataReceive(uint16_t character, void *data)
{
    UNUSED(data);

    lastReceiveTimestamp = microsISR();

    //If the buffer len is not reset for whatever reason, disable reception
    if (readBufferPtr->len > 0 || readBufferIdx >= SRXL2_MAX_PACKET_LENGTH) {
        readBufferIdx = 0;
        globalResult = RX_FRAME_DROPPED;
    }
    else {
        readBufferPtr->packet.raw[readBufferIdx] = character;
        readBufferIdx++;
    }
}

static void srxl2Idle()
{
    if(transmittingTelemetry) { // Transmitting telemetry triggers idle interrupt as well. We dont want to change buffers then
        transmittingTelemetry = false;
    }
    else if(readBufferIdx == 0) { // Packet was invalid
        readBufferPtr->len = 0;
    }
    else {
        lastIdleTimestamp = microsISR();
        //Swap read and process buffer pointers
        if(processBufferPtr == &readBuffer[0]) {
            processBufferPtr = &readBuffer[1];
            readBufferPtr = &readBuffer[0];
        } else {
            processBufferPtr = &readBuffer[0];
            readBufferPtr = &readBuffer[1];
        }
        processBufferPtr->len = readBufferIdx;
    }

    readBufferIdx = 0;
}
```

`srxl2DataReceive` is the individual byte reception callback, similar to how most of the other protocols get their data, and `srxl2Idle` is our idle callback. The idle interrupt switches the buffers, and indicates one of them is ready to be processed. The actual protocol processing still happens in the rcFrameStatusFn, so the ISR is fairly quick.

I agree in terms of portability, as not every platform has a built in idle interrupt feature for the UART, but there are ways around this. This just happens to be the simplest way to handle it.

**Comment by digitalentity** [comment]
I would prefer the protocol to not use byte callback either.

This is not safe since we don't do any blocking. `rcFrameStatusFn` is called at every scheduler iteration, so polling the status is going to be quicker (and also will allow our scheduler to account for the time correctly).

Can you add a new serial API call to check if the port is idle and do buffer switching in the `rcFrameStatusFn` ?

**Comment by MiguelFAlvarez** [comment]
The byte callback is used this way because that's how all the other serial protocols use it. 
I could add idle checking in the `rcFrameStatusFn`, but it'll mean delaying the protocol implementation for a while, as we'll have to do testing again.
I was hoping to have this match what has been merged to betaflight a few months ago. Probably shouldn't have assumed that what they approved would be fine to implement here.

**Comment by digitalentity** [comment]
@DzikuVx @fiam I need a second oppiniton here. Is it worth adding another interrupt callback or should we rather go for polling idle? WDYT?

**Comment by DzikuVx** [comment]
Another callback seems like too tight protocol-hardware integration. Personally I would prefer to have it as a poll

**Comment by digitalentity** [comment]
Also, `rcFrameStatusFn` is called each scheduler iteration to check on RX driver status and check if full RC task should be executed. There is very little benefit of doing anything via a callback, IMO that marginal benefit doesn't justify for bypassing the scheduler and creating a tight coupling between HW and RX driver

**Comment by fiam** [comment]
@digitalentity We already have a problem with the amount of interrupts generated when an uart transfers a significant amount data, even at 115kbps. I'd prefer to not enable additional interrupts unless it's absolutely necessary.

@MiguelFAlvarez It seems to me that the you could switch to a polling approach with not that many changes. Instead of calling `srxl2Idle()` from the interrupt, can't you check for the IDLE flag in the in `rcFrameStatusFn()` callback and trigger `srxl2Idle()` from there?

**Comment by MiguelFAlvarez** [comment]
Ok noted, I'll drop this PR and modify the SRXL2 code to use polling to determine if the packet is complete.

**Pull request closed without merging**
