### PR TITLE
Non-volatile storage for waypoint missions

### PR DESCRIPTION
**Pull request by digitalentity**
Mission is stored in configuration memory as `PG_WAYPOINT_MISSION_STORAGE` parameter group. All `NAV_MAX_WAYPOINTS` is saved.

Stick combos to save/load missions:
To save currently uploaded mission: `THR_LO + YAW_CE + PIT_HI + ROL_LO`
To load mission from EEPROM: `THR_LO + YAW_CE + PIT_HI + ROL_HI`

Not supported on F1 targets due to lack of enough EEPROM space.

- [x] Non-volatile waypoint storage (EEPROM-based)
- [x] Stick combos to load/store missions
- [x] MSP API to load/store missions

Addresses #79

### CODE REVIEW

**Comment by digitalentity** [comment]
By coincidence #79 was opened on 8 Feb 2016 and is exactly 1 year old now.

**Comment by digitalentity** [comment]
@DzikuVx @martinbudden @stronnag @oleost do you think we can get this into 1.6? This is a very much desired feature and it's very self-contained.

**Comment by martinbudden** [comment]
I see no reason this shouldn't go into 1.6. As you say it is self-contained and we still have several weeks for testing.

**Comment by digitalentity** [comment]
@stronnag @eziosoft - you might want to have new MSP commands implemented in **mwp** and **EzGUI**

**Comment by stronnag** [comment]
~~Indeed, the version with the menu options greyed out was committed yesterday. It will be done for the weekend.~~

Done. Tested. Working across reboots.

**Pull request merged**
