### PR TITLE
Add support for OSD map mode

### PR DESCRIPTION
**Pull request by fiam**
Draws the home centered, while the craft moves around. There are
2 available maps: one with the North pointing up and another one
with the takeoff direction pointing up.

Maps support arbitrary elements over them, as long as it doesn't
overlap the home at the center nor the direction indicator at the
top right nor the scale indicator at the bottom left (all of them
are fixed size). This allows users to customize how their maps
look with additional info that they might find useful (e.g. altitude
or distance to home).

Configurator PR at https://github.com/iNavFlight/inav-configurator/pull/432

### CODE REVIEW

**Comment by gmacfpv** [comment]
This is looking good, however having the aircraft as the fixed position I feel works so much better. Can you set it so that it is centred on aircraft and the home position moves in relation to the aircraft?

**Comment by fiam** [comment]
@gmacfpv that will be radar mode. It will follow shortly after this one is merged.

**Comment by fiam** [comment]
Missing part in this one (which I'm not sure if we should fix in this PR or in another one) is saving the actual take off direction on FW without a compass, since it's incorrect right now.

**Comment by fiam** [comment]
Rebased, should be ready to merge.

**Pull request merged**
