### PR TITLE
RTH waypoint + landing

### PR DESCRIPTION
**Pull request by digitalentity**
Initial implementation of #61

### CODE REVIEW

**Comment by digitalentity** [comment]
@stronnag, @DzikuVx can you review and if possible test a mission with RTH+land?

**Comment by stronnag** [comment]
On 22 July 2016 13:20:45 BST, Konstantin Sharlaimov notifications@github.com wrote:

> @stronnag, @DzikuVx can you review and if possible test a mission with
> RTH+land?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/iNavFlight/inav/pull/366#issuecomment-234529338

I will gladly test on Saturday.

**Comment by digitalentity** [comment]
@stronnag please bear in mind that the code is highly experimental and untested (even on the bench).

**Comment by DzikuVx** [comment]
@digitalentity unfortunately, it is impossible. Burned FC in GPS equipped quad. Waiting for a new one. ETA: 2 weeks

**Comment by digitalentity** [comment]
@DzikuVx sorry to hear. I'd greatly appreciate if you review the code and try spotting any bugs.

**Comment by DzikuVx** [comment]
That will do

**Comment by stronnag** [comment]
Flight tested (twice). Working. I'll link a log later.

**Comment by stronnag** [comment]
There is a log at http://seyrsnys.myzen.co.uk/inav-wp-rth/LOG00262.TXT. Index 1 is with RTH p1=0 (so landing invoked manually), index 2 is with p1=1 (automagic landing). The machine auto-disarmed promptly in both cases.

There were no LTM landing status messages in the second case; either work in progress or an omission in mwp (to be investigated).

I guess no decision has been made on both P1 values (bitmask, rotate to arm direction, rotate to reciprocal arm direction), so I didn't even try these.

Looking good so far!

**Comment by digitalentity** [comment]
@stronnag thanks!
Re-implemented WP-RTH-Landing in a more proper way - now it's a specific state in the navigation stage machine. Now it costs 72 extra bytes of memory, but it's now easier to understand and extend if necessary.

**Comment by stronnag** [comment]
The 72 bytes were well spent! Extensively tested. Working well. I think this can be merged.

**Comment by digitalentity** [comment]
@stronnag great, merged! If there are bugs we'll solve them after 1.2 is released.

**Comment by stronnag** [comment]
It's not failed me in perhaps 12 attempts. I'm content.

**Comment by digitalentity** [comment]
I just though about one bug - landing procedure is not defined for a fixed-wing aircraft, normal RTH on a FW does not invoke landing, while WP-RTH will enter a multirotor landing procedure even on a fixed wing. Opened #378 to track the issue.

**Pull request merged**
