### PR TITLE
[GPS] Fix message rate for newer ublox devices and add some extra debugging features

### PR DESCRIPTION
**Pull request by mmosca**
UBLOX and UBLOX7 are now the same thing.

Fix the message configuration on m10 devices.

Also, add extra gps info to status output.

```
GPS: HW Version: UBLOX10 Proto: 34.09 Baud: 115200
  SATS: 0
  HDOP:  99.990
  EPH :  99.990 m
  EPV :  99.990 m
  GNSS Capabilities:
    GNSS Provider active/default
    GPS 1/1
    Galileo 1/1
    BeiDou 1/1
    Glonass 0/0
    Max concurrent: 3
```

Add gpssats cli command

```
# gpssats
UBLOX Satelites
satelite: 3:20
sigId: 0 (BeiDou B1I D1)
signal strength: 0 dbHz
quality: 1 (Searching signal...)
signal flags: 0x01
signal: Healthy
```

TODO:
* [x] Check with M10 Bench
  * [x] M10 initialization
* [x] Check with M9 Bench
  * [x] M9 initialization
* [x] Check with M8 Bench
  * [x] M8 initialization
* [x] Check with M10 with lock
* [x] Check with M9 with lock
* [x] Check with M8 with lock
* [x] Parse older NAV_SAT messages in addition to NAV_SIG

Bonus changes:
showdebug on cli

### CODE REVIEW

**Comment by mmosca** [comment]
As a bonus, also add showdebug cli command:
```
# showdebug
Debug fields: [GPS (23)]
debug[0] = 2119
debug[1] = 2141
debug[2] = 0
debug[3] = 0
debug[4] = 0
debug[5] = 0
debug[6] = 0
debug[7] = 42
```

**Comment by mmosca** [comment]
M8 does not support NAV_SIG.

So I will add NAV_SAT as a fallback and try to make the setup more resilient to random hardware / software combinations.

**Comment by mmosca** [comment]
Current showdebug items for debug_mode = GPS

```
0: MSG_PVT count
1: MSG_SAT count
2: NAV_SIG count
3: NAV-SAT numSvs
4: NAV-SIG numSvs
5: flags.pvt
6: flags.sat
7: flags.sig
```

**Comment by mmosca** [comment]
Cool. Very useful. I will have a loot. I am not 100% sure I am parsing all the satelite fields correctly, specially coming from older messages.

The one that didn't read the version, probably needs initializing of the satelites array to get rid of false entries.

**Comment by stronnag** [comment]
> Cool. Very useful. I will have a loot. I am not 100% sure I am parsing all the satelite fields correctly, specially coming from older messages.
> 
> The one that didn't read the version, probably needs initializing of the satelites array to get rid of false entries.

The older model only has SW and HW version strings, no extended version with the protocol version.

**Comment by mmosca** [comment]
> > Cool. Very useful. I will have a loot. I am not 100% sure I am parsing all the satelite fields correctly, specially coming from older messages.
> > The one that didn't read the version, probably needs initializing of the satelites array to get rid of false entries.
> 
> The older model only has SW and HW version strings, no extended version with the protocol version.

I should have fixed the reporting now.

Can you check if there are any regressions on m8 hardware?

I may eventually add some of this info to the configurator as well

**Comment by stronnag** [comment]
## Old M8 (v2 firmware).

### Info
```
gps_provider = UBLOX

# status
INAV/WINGFC 8.0.0 Jul  4 2024 / 16:45:16 (7677abeb)
GCC-14.1.0
...
GPS: HW Version: UBLOX8 Proto: 15.00 Baud: 115200
  SATS: 0
  HDOP:  99.990
  EPH :  99.990 m
  EPV :  99.990 m
  GNSS Capabilities:
    GNSS Provider active/default
    GPS 1/1
    BeiDou 0/0
    Glonass 1/1
    Max concurrent: 2
```

## CLI

```
# gpssats
UBLOX Satelites
satelite[2]: 0:9
sigId: 0 (GPS L1C/A)
signal strength: 31 dbHz
quality: 3 (Signal detected but unusable)
signal flags: 0x01
signal: Healthy

satelite[3]: 1:136
sigId: 0 (SBAS L1C/A)
signal strength: 34 dbHz
quality: 2 (Signal acquired)
signal flags: 0x00
signal: Unknown (0x0)
```

## `ublox-cli --pass --no-init`
```
SVINFO: Channels 4
Chn	ID	used	healthy	quality
  3	G6	-	-	7
  0	G9	-	-	7
  2	G20	-	Y	1
  1	SBAS136	-	-	6
```

## Ancient Neo6M

### Info

```
GPS: HW Version: Unknown Proto: 0.00 Baud: 115200
  SATS: 0
  HDOP:  99.990
  EPH :  99.990 m
  EPV :  99.990 m
  GNSS Capabilities:
    GNSS Provider active/default
    GPS 1/1
    Max concurrent: 0
```

### CLI

I don't think this really works with 64 satellites ...

```
# gpssats
UBLOX Satelites
satelite[1]: 0:0
sigId: 0 (GPS L1C/A)
signal strength: 0 dbHz
quality: 0 (No signal)
signal flags: 0x00
signal: Unknown (0x0)

... cut for brevity ...

satelite[64]: 0:0
sigId: 0 (GPS L1C/A)
signal strength: 0 dbHz
quality: 0 (No signal)
signal flags: 0x00
signal: Unknown (0x0)
```

I would not oppose dropping Neo6 and earlier.

**Comment by mmosca** [comment]
I have a plan for that. the 64 is an arbitrary number I picked. Can easily be changed.

Regarding m6, I do have a plan for that.

There are currently 3 main categories of gps in the ublox code:

1) Pre-historic things, like this m6
2) Things with software > 15.01 and < 23.01 M8 and possibly M7
3) Things with software >= 23.01 m10

I was planning on suggesting deprecating anything before 15.01

You may be bale to use use it, but we will drop the auto config and you need to make sure it can output NAV_PVT and  NAV_SIT or NAV_SAT.

Lots of code we can remove in that case

**Pull request merged**
