### PR TITLE
Swing-launch detection

### PR DESCRIPTION
**Pull request by digitalentity**
Solves #847

### CODE REVIEW

**Comment by digitalentity** [comment]
This is very experimental code. One more parameter - `nav_fw_launch_velocity` to define approximate velocity to use as a threshold. As in previos code - GPS is not used so this is suitable for ANY airplane.

**Comment by oleost** [comment]
@digitalentity Just to make it clear, it now watches both velocity and forward acceleration. And if any of those two are true it detects an launch?

And regarding that 45 degree limit, you dont think that may become an issue? 
(Because when you hold airplane by wing tip, its almost 90degress, and while you swing and before stabliation have the plane leveled there can be some angle at it)

**Comment by digitalentity** [comment]
@oleost yes. It will now detect launch if any of the checks passes.

**Comment by oleost** [comment]
@digitalentity did you see my edited post?

**Comment by digitalentity** [comment]
@oleost no I didn't. 45 deg limit is only used for throw. For swing detection it's watching yaw rotation rate (should be above 100deg/s) and sideways cetrifuglal acceleration (both should yield forward velocity above the threshold) without any limitation on angle.

**Comment by oleost** [comment]
Great!

I have gotten it prepared and when I get time I will to both this and baro test.

**Comment by oleost** [comment]
@digitalentity Did test today with just "dry" throwing wing outside. Seems like its working as intended 👍 

Have it loaded on my wing so next time I go fly I will test aswell. But I tihnk it safe to merge to development.

**Comment by oleost** [comment]
Found two issues. 

Missing updated cli and wrongly named "naw_fw_launch_climb_angle" and "naw_fw_launch_timeout"

nav_fw_launch_velocity = 300
Allowed range: 100 - 10000

nav_fw_launch_accel = 1700
Allowed range: 1000 - 20000

nav_fw_launch_detect_time = 40
Allowed range: 10 - 1000

nav_fw_launch_thr = 1600
Allowed range: 1000 - 2000

nav_fw_launch_motor_delay = 3000
Allowed range: 0 - 5000

naw_fw_launch_timeout = 8000
Allowed range: 0 - 60000

naw_fw_launch_climb_angle = 20
Allowed range: 5 - 45

Its written with a "w" instead of "v"

I can get cli.md updated.

**Comment by digitalentity** [comment]
@oleost fixed both.

**Comment by oleost** [comment]
@digitalentity Great thank you.

**Comment by digitalentity** [comment]
@oleost I've merged this as-is. I believe table-test is good enough.

**Pull request merged**
