### PR TITLE
Add pilot logo to OSD

### PR DESCRIPTION
**Pull request by MrD-RC**
This change adds the ability to have a pilot logo on the boot and arm screen and a smaller version that can be displayed anywhere on the OSD. This change also adds a different arming screen for HD systems, to include the logo.

The large pilot logo is HD only. The small logo also works on analogue. The large pilot logo would work on analogue. Only the MAX7456 chip seems to corrupt the last 33 characters seem to get corrupted on power loss. If anyone has any ideas on how this could be fixed. I'm open to suggestions.

While making this change I also cleaned up the arming screen a little. If there is space, stats are also shown on the arming screen now, if enabled.

Requires Configurator: https://github.com/iNavFlight/inav-configurator/pull/1835

### New settings:
**osd_arm_screen_display_time** The amount of time the arming screen is displayed.
**osd_inav_to_pilot_logo_spacing** The spacing between two logos. This can be used to have no space, so the original INAV logo and Pilot Logo can be combined in to a larger logo.
**osd_use_pilot_logo** Enable to use the large pilot logo.

### Examples
**Combined pilot logo on HD arming screen**
image

**HD Arming screen with pilot logo enabled**
image

**Example of issue with analogue font**
Logo shown after installing the font, but before power loss (removing USB or battery)
image

Logo shown after power loss
image

### CODE REVIEW

**Comment by MrD-RC** [comment]
@mmosca @stronnag I'm getting issues with the Mac SITL checks.

**Comment by mmosca** [comment]
I ca. Have a look later today. []s,Marcelo Bezerra ***@***.***>On 1 Oct 2023, at 11:28, Darren Lines ***@***.***> wrote:﻿
@mmosca @stronnag I'm getting issues with the Mac SITL checks.

**Comment by stronnag** [comment]
`floorf` maybe.

**Comment by stronnag** [comment]
> `floorf` maybe.

```
logoColOffset = floorf((osdDisplayPort->cols - SYM_LOGO_WIDTH) / 2.0f);
```
fixes the issue in my (albeit old) MacOS VM

**Comment by MrD-RC** [comment]
Thanks @stronnag

**Pull request merged**
