### PR TITLE
Failsafe Emergency Landing change

### LINKED ISSUE #7340: [copter][failsafe] land with baro
## Current Behavior
Currently there is one automated failsafe mode - RTH which requires GPS and defining points. Many drones do not use GPS.
Second option is to set throttle to constant value. When changing drone weight, value has to be recalibrated.
Third to just stop the motors. This leads to crash.

## Desired Behavior
Why there is no option to automatically land with barometer? It seems to be quite reasonable option to me. I've tried to modify flight height with throttle stick in ALTHOLD mode and it caused smooth landing. I know baros are error prone, but software can deal with it I suppose.
Enabling alt landing mode should cause decreasing value of set altitude. At some point it will stay on the ground. Then there could be some timeout on measured altitude value not decreasing or just waiting for pilot action.

## Suggested Solution
Add "alt landing" mode which could be set as failsafe action.

## Who does this impact? Who is this for?
At least copters users. Automatic land feature would help beginners to not crash their machines in critical situations.

## Additional context
I remember using the toy drone "UGO Zephir 2.0 UDR-1358", it had automatic start and automatic land features.

### PR DESCRIPTION
**Pull request by breadoven**
Changes failsafe Landing procedure (`SET-THR`) to use Emergency Landing if NAV is defined. Otherwise it will use the current method of a fixed throttle setting.

Emergency Landing on a multirotor uses a controlled descent rate if altitude sensors are available otherwise it falls back to using the Failsafe fixed throttle setting. Controlled descent rate would be possible on a fixed wing through https://github.com/iNavFlight/inav/pull/7364.

If for some reason Emergency Landing stops unexpectedly Failsafe Landing will fall back to the failsafe `DROP` procedure.

Failsafe procedure `SET-THR` has been renamed to `LAND `given it no longer makes sense for Emergency Landing and LAND is consistent with the Configurator Failsafe settings anyway.

Closes https://github.com/iNavFlight/inav/issues/7340.

Tested on both fixed wing and multirotor and seems to work as expected using Failsafe mode.

Failsafe.md needs updating if this change is merged.

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]
@breadoven could you update the Failsafemd as well?

**Comment by breadoven** [comment]
> @breadoven could you update the Failsafemd as well?

OK, I'll get that done.

**Comment by DzikuVx** [comment]
@breadoven please resolve conflict and we will merge

**Comment by rts18** [comment]
@breadoven Great work on this. This feature is ideal for flying at different sites, when its not desirable to have a quad Drop on concrete or have it fly up into a tree branch when climbing to RTH altitude.

Would you consider adding the ability to change this feature on the run, under the Adjustments tab or Logic conditions? 
I am aware that it would have to be selected before a FS occurred. 

This would give more flexibility of flight locations within a session, without the need to land and plug into a PC. 

It may also be useful for a Fixed Wing, if the model is low on battery and can't make it home.  By switching the FS procedure from RTH to LAND within the flight.

**Pull request merged**
