### PR TITLE
Flysky IBUS telemetry not work properly

### PR DESCRIPTION
**Pull request by hali9**

### CODE REVIEW

**Comment by oleost** [comment]
Hi. Please do merge into development branch and not master @hali9

**Comment by DzikuVx** [comment]
OK, handled that and PR now goes against `development`
Thank you @hali9

**Comment by digitalentity** [comment]
Need to test if this breaks other telemetries if enabled together with IBUS

**Comment by digitalentity** [comment]
Seems that everything's good. Merging.

**Pull request merged**
