### PR TITLE
Drop support for NAZA GPS

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by digitalentity** [comment]
Yay! Finally!

**Review by digitalentity — APPROVED** [review]

**Review by JulioCesarMatias — APPROVED** [review]

**Comment by intelligentpotato** [comment]
May I know what was the reason to drop support for NAZA GPS?

**Comment by Henrik985** [comment]
> May I know what was the reason to drop support for NAZA GPS?

I managed to reactivate NAZA GPS (GPS & MAG) in iNav 7.1.1 via custom FW build.

Which target is needed?

**Comment by Henrik985** [comment]
max. filesize is 25MB - so I upload all targets with DJI NAZA GPS/MAG supported custom FW.
Use CLI with "set gps_provider = NAZA" and use the configurator-tab to select compass with GPSMAG.
Tested on target FLYWOOF411 and OMNIBUSF4V3.

**Target 1-40**

(https://github.com/iNavFlight/inav/files/15446651/1-40.zip)

**Comment by Henrik985** [comment]
max. filesize is 25MB - so I upload all targets with DJI NAZA GPS/MAG supported custom FW.
Use CLI with "set gps_provider = NAZA" and use the configurator-tab to select compass with GPSMAG.
Tested on target FLYWOOF411 and OMNIBUSF4V3.

**Target 41-80**

(https://github.com/iNavFlight/inav/files/15446689/41-80.zip)

**Comment by Henrik985** [comment]
max. filesize is 25MB - so I upload all targets with DJI NAZA GPS/MAG supported custom FW.
Use CLI with "set gps_provider = NAZA" and use the configurator-tab to select compass with GPSMAG.
Tested on target FLYWOOF411 and OMNIBUSF4V3.

**Target 81-120**

(https://github.com/iNavFlight/inav/files/15446693/81-120.zip)

**Comment by Henrik985** [comment]
max. filesize is 25MB - so I upload all targets with DJI NAZA GPS/MAG supported custom FW.
Use CLI with "set gps_provider = NAZA" and use the configurator-tab to select compass with GPSMAG.
Tested on target FLYWOOF411 and OMNIBUSF4V3.

**Target 121-160**

(https://github.com/iNavFlight/inav/files/15446696/121-160.zip)

**Comment by Henrik985** [comment]
max. filesize is 25MB - so I upload all targets with DJI NAZA GPS/MAG supported custom FW.
Use CLI with "set gps_provider = NAZA" and use the configurator-tab to select compass with GPSMAG.
Tested on target FLYWOOF411 and OMNIBUSF4V3.

**Target 161-176**

(https://github.com/iNavFlight/inav/files/15446731/161-176.zip)

**Pull request merged**
