### PR TITLE
Get time from NazaGPS

### PR DESCRIPTION
**Pull request by sambas**
So far I haven't found way to tell if clock is between 16:00-23:59 or 0:00-7:59 as hour is reported as 0-7 in both cases.

### CODE REVIEW

**Comment by digitalentity** [comment]
Merged. Looks like weird time reporting is a limitation of NAZA protocol.

**Comment by giacomo892** [comment]
@sambas I did some testing some days ago trying to hack NAZA code to get time. I did something similar to what you did but it wasn't working. Mine was a cloned unit.

Have you tried it or just did the code for it?

**Comment by sambas** [comment]
yes, tried with one cloned device

**Comment by giacomo892** [comment]
Oh. Thanks.. Somehow strange. Mine code looks like yours but wasn't working when I tested it.

**Pull request merged**
