### PR TITLE
New target: IFlight Succex-E F7 Mini

### PR DESCRIPTION
**Pull request by clodzeischi**
Reason: no target for Sx-E F7 Mini.
How: duplicated F7 TwinG, removed second gyro, verified pin mappings against Betaflight board definition for F7 Mini.
Tested: uploaded code into the board. Did not fly yet.

### CODE REVIEW

**Comment by ckming102** [comment]
Did you check if the baro works? Seems like it was an issue for the F4 and F7 on Betaflight. [https://github.com/betaflight/betaflight/issues/9604]

**Comment by voxtelnismo** [comment]
Yes, my baro is definitely providing a reading. Pressure seems to work fine, but the altitude reading has a significant steady oscillation (goes up and down in a sin-wave fashion every 5-6 seconds). Now the PID controller seems to mostly care about z velocity, so I imagine it shouldn't be a deal breaker. Maybe we can submit a feature request to implement EKF as the position estimator? ;)

**Comment by ckming102** [comment]
Ahhhh, I see. I have the older model with the BMP280, and it is definitely not working with Betaflight. 

I don't know much about Extended Kalman Filters, but 5-6 secs. is a very slow frequency. EKF might be overkill. Could it be that  something else is wrong causing a slow sensor drift.

**Comment by fanedi** [comment]
there's a target on iflight site .. but working only with INAV 3.1.0 !

**Comment by G9xy** [comment]
> there's a target on iFlight site .. but working only with INAV 3.1.0 !

I am confused about version, at this moment there is not yet published version of INAV 3.1.0. - is this only iFlight internal versioning number or they have access to future INAV 3.1.0 codebase? Can someone elaborate this versioning matter?

**Comment by voxtelnismo** [comment]
> > there's a target on iFlight site .. but working only with INAV 3.1.0 !
> 
> I am confused about version, at this moment there is not yet published version of INAV 3.1.0. - is this only iFlight internal versioning number or they have access to future INAV 3.1.0 codebase? Can someone elaborate this versioning matter?

Current master is 3.1.0

**Comment by Odin263** [comment]
image
Is that really correct?
See betaflight:
image

**Comment by voxtelnismo** [comment]
@Odin263 
That shouldn't play a huge role. Timers 9/2 and 5/4 are both available and both have resolution to handle PPM input.

**Comment by Odin263** [comment]
I have also created a target for this FC that I have been using for a long time. When comparing with these files, no relevant differences can be seen. Everything is recognized (Baro DPS310, GPS, compass, ...) and works properly. However, the temperature sensor should be deleted in the target.h, as it causes I2C errors and apparently has not been used in INAV since F3 processor.
image
I would advocate the merging!

**Comment by haslinghuis** [comment]
As Betaflight member I have no jurisdiction here or whatever. But I'd like to intervene here as a video is suggesting to do it yourself which is helping shortly but never in the long run.

So please consider merging the suggested target after verifying.

image

**Comment by haslinghuis** [comment]
@Linjieqiang are you able to provide samples to Inav for this to happen?

**Comment by shellixyz** [comment]
The temperature sensors can be used with any FC. The "I2C errors" are just the peripherals trying to be discovered but not responding since not connected. Please keep the temperature stuff in the target

**Pull request closed without merging**
