### PR TITLE
PixRacer SBUS Support

### PR DESCRIPTION
**Pull request by olibye**
Here's my first PR to this project. I'm happy to make any changes required to get this in.
I've test flown my RoboCat 270 an original R14 PixRacer

### CODE REVIEW

**Comment by digitalentity** [comment]
Looks fine to me.

**Comment by martinbudden** [comment]
@digitalentity , @olibye , I think it is better to avoid introducing a `config.c` file if possible. This change can be done without the need for `config.c` by adding the lines:

```
#define SERIALRX_PROVIDER       SERIALRX_SBUS
#define SERIALRX_UART           SERIAL_PORT_USART6
```

to `target.h`


@digitalentity - I think you merged this to quickly.
@olibye , can you do another PR that gets rid of the `confif.c` file and adds the above changes to `target.h` (test it of course)?

**Comment by digitalentity** [comment]
Good point. I indeed merged this too early. @olibye can you do what @martinbudden is suggesting?

**Comment by olibye** [comment]
Yes happy to do this. I had it like this originally but was unsure if it would support both PPM and SBUS in the same binary.

**Pull request merged**
