### PR TITLE
Waypoint multi-mission in flight mission change

### LINKED ISSUE #8301: New feature request: Change missions in flight
## Current Behavior
Actually since iNav 4.xx it is possible to have more than one mission recorded in the FC. 
But, for example, to change from mission 1 to mission 2 the only way to stop flying, is un-arm and use the OSD menu to select the second mission.

## Desired Behavior
* Change missions in flight

## Suggested Solution
* Have the possibility to change in flight the mission number
* Have the possibility to change mission from a button on the TX
* (Optional) See on the OSD the mission selected before activating it
* (Optional) Put a name on a mission number that can be seen on the OSD in case the wrong mission is selected

## Who does this impact? Who is this for?
All users who wants to have planned missions with multiple possibilities (e.g. depending on the real situation like having a plan A and B in case the wind is too strong in a direction).
For example, for a fixed wing, with this feature it will possible to manage during the flight the 1. mission itself and 2. prepare for landing 
If there is any mission cancellation, the user should activate another specific Mission to prepare for landing, the goal is to put the plane in the good direction, good altitude to prepare for a manual landing. Also it should interesting to prepare several pre-landing mission, to anticipate to the wind orientation new.

## Additional context
in my home there is a long rectangular area that take time for the fixed wing to be in the correct orientation (like a large road), only 2 possibilities depending on the wind:
image

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/8301.

Allows WP multi-missions to be changed in flight using new mission change mode. With mode active the required mission index can be selected by cycling through missions using the WP mode switch. Selected mission is loaded when mission change mode is switched off. Mission index can also be changed through addition of a new Mission Index adjustment function which should be useful for DJI users unable to use the normal OSD mission related fields.

PR also improves function of multi-missions by keeping waypoint mission array intact on arming rather than overwriting the start of the array with the selected mission as happens currently (this requires eeprom reload when disarmed to restore the mission array).

Not flight tested yet but works as expected using the HITL Sim.

### CODE REVIEW

**Comment by b14ckyy** [comment]
Tested today but found 2 major problems. 

1: When submitting the Missions to INAV via Configurator without rebooting, Mission index is stuck at M0 and does not allow me to switch. Therefore it runs all missions in a row. The only way the switching works is, to store the missions into EEPROM, then reboot and load missions from EEPROM. Therefore I cannot live upload multi missions in flight and then select them. 

2. All my flight modes are on a single channel. So if I fly in Cruise mode to give up control and take my time to select the WP mission, every time I flick the `NAV WP` mode switch, this is the only mode applied and cruise is disabled. Therefore the craft switches into `ACRO ` for that moment. Would it be possible to "freeze" the last mode as long as `MISSION CHANGE` + `NAV WP` is active to prevent this? Otherwise people will be forced to waste a RC channel for safety reasons. Especially on Quads where switching from `POSHOLD` to `ACRO` by accident could be fatal.

**Comment by breadoven** [comment]
> Tested today but found 2 major problems.
> 
> 1. When submitting the Missions to INAV via Configurator without rebooting, Mission index is stuck at M0 and does not allow me to switch. Therefore it runs all missions in a row. The only way the switching works is, to store the missions into EEPROM, then reboot and load missions from EEPROM. Therefore I cannot live upload multi missions in flight and then select them.

That may be the case but multi missions was really only intended as a means of having access to more than a single mission loaded from eeprom. There doesn't seem much point in using it if you have the ability to upload missions in flight because you can use the upload itself as the means to change missions as required.

> 2. All my flight modes are on a single channel. So if I fly in Cruise mode to give up control and take my time to select the WP mission, every time I flick the `NAV WP` mode switch, this is the only mode applied and cruise is disabled. Therefore the craft switches into `ACRO ` for that moment. Would it be possible to "freeze" the last mode as long as `MISSION CHANGE` + `NAV WP` is active to prevent this? Otherwise people will be forced to waste a RC channel for safety reasons. Especially on Quads where switching from `POSHOLD` to `ACRO` by accident could be fatal.

I guess it's always problematic trying to accommodate all possibilities here, too many modes for not enough channels, I'm not sure what the ideal solution is. Remember there is also the possibility to change mission index in flight using Adjustments which is actually easier than toggling the WP mode switch..

**Comment by b14ckyy** [comment]
To point 1: 
Ok I get that. The only issue I see is, that even if I upload a mission on the ground into EEPROM, I am forced to reboot and reload to make the switch work. 

To point 2: 
I could mitigate this problem by either adding `LOITER`/`POSHOLD` to the `MISSION CHANGE` range as I think these have higher priority than `NAV WP`? 
Alternatively a Logic condition could help as well that reads the current mode channel position, stores it into a GV and then overrides the mode channel with that value as soon as `MISSION CHANGE` + `NAV WP` is active. But this results in a 2% chance if still switching and maybe locking the plane in that mode afterwards. Need to test that out. 
Or generally locking the FM as soon as `MISSION CHANGE` is enabled but this could by accident lock the craft also in the current flight mode if the pilot does not realize. 

I guess forcing POSHOLD would be the safest option. It would also make the most sense as a general way the feature works. what else should the craft do while selecting a mission?

**Comment by breadoven** [comment]
I just set up `MISSION CHANGE` active together with `POSHOLD `which is the easiest way so long as `POSHOLD` and `WP `modes are on different channels. `WP `has priority over `POSHOLD`, but is inhibited when `MISSION CHANGE` is active.

**Pull request merged**
