### PR TITLE
display updates

### PR DESCRIPTION
**Pull request by tednv**
adding new inav display armed page, cleaning up documentation and images, adding amazon link to yellow & blue i2c display used for armed image

### CODE REVIEW

**Comment by tednv** [comment]
this will work with a monochrome display as well, but the yellow and blue looks way better

**Comment by tednv** [comment]
I tested this on an F3 target, NAZE still bombs with default build but even after I get it built by disabling some features I'm getting no display output. I'm pretty sure this has nothing to do with this change, I tried a pre-built image without any changes and getting same behavior

**Comment by digitalentity** [comment]
@tednv what's the status of this PR? We have a conflict regarding stick positions.

**Comment by tednv** [comment]
I had these in separate PR+branch, not sure why it's conflicting trying to sort it out now

**Comment by digitalentity** [comment]
Most likely is that you based your updates on master branch while it should
be development branch.

On Mar 25, 2017 3:59 PM, "tednv" <notifications@github.com> wrote:

I had these in separate PR+branch, not sure why it's conflicting trying to
sort it out now

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/pull/1424#issuecomment-289191453>, or mute
the thread

**Comment by tednv** [comment]
thank you for the tip, fixing

**Comment by tednv** [comment]
when I try to do a pr based on development branch it shows 98 changed files with recent updates, is that ok?

**Comment by tednv** [comment]
added cleaned up branch based on development branch #1457

**Pull request closed without merging**
