### PR TITLE
Quaternion-based attitude controller

### PR DESCRIPTION
**Pull request by digitalentity**
This is to implement #734

### CODE REVIEW

**Comment by digitalentity** [comment]
@HaukeRa please note that this is based on development which may be unsafe to fly until @martinbudden finishes conversion to PGs.

**Comment by fiam** [comment]
@digitalentity Can we get this resolved and merged? Even if it's not clear at this point if something else will use the quaternions, the code looks cleaner than the current one. Just moving the q1, q2, q3 and q4 globals into a global struct instead is a nice readability improvement.

**Comment by digitalentity** [comment]
@fiam we can have some of this code merged - better quaterion representation and some quaternion math functions. Regarding the attitude controller itself - we need to understand how to handle yaw axis which is almost always rate.

**Comment by HaukeRa** [comment]
I think it needs to be decided if rate control from the UAV's reference frame is really needed for inav.

Many of the control input problems are solved by only using angle mode, limiting to 180°.

But I'm open for discussion as I don't know that inav users expect.

**Comment by digitalentity** [comment]
@HaukeRa yaw in body frame is the main reason why this is not merged yet. INAV could be used in acro mode (and in fact is used in ACRO mode for some 3D airplanes) - those flying acro need full decoupling of yaw/roll/pitch.

For ANGLE/HORIZON mode it's best to have yaw contol in Earth frame but we need to consider that in HORIZON UAV could be upside down and that HORIZON transitions from ANGLE to ACRO at certain point.

**Comment by digitalentity** [comment]
@HaukeRa is it possible to take the existing orientation quaternion and build a new one replacing roll and pitch angles but keeping original yaw?

**Comment by HaukeRa** [comment]
@digitalentity there is nothing like pitch and roll which can directly be replaced in a quaternion representation.

But an idea came into my mind:
The orientation quaternion always represents the intended orientation (actually the difference between body and reference frame) of the UAV. So the actual task is to map the stick inputs into a reasonable setpoint.

But nothing prevents us from using the stick inputs to modify the setpoint rate-based. It would probably be necessary to limit the error (i.e. clamp the setpoint to differ at maximum 45° over all axes to the actual current orientation). That way you have a rate control while the PID actually does attitude control

**Comment by digitalentity** [comment]
@HaukeRa yes, this idea came to me also. It's possible, but has a flaw - ANGLE controller will be always active meaning PID will always be trying to maintain attiude correcting for every slightest motion. This creates some jitter even when you don't intend to change attitude.

Opposed to this - rate control without self-leveling is very smooth even when it drifts.

**Comment by HaukeRa** [comment]
In that case, you don't need the Quaternion PID controller at all, because it runs on top of the angle PID controller.

Otherwise, one could implement deadband or other unlinear control at small errors

**Comment by digitalentity** [comment]
Will be re-implemented after #2894 is merged

**Pull request closed without merging**
