### PR TITLE
[All Platforms]Rename PIFF to PIDFF and PID to PIDCD

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
To use in 3.0

### CODE REVIEW

**Review by DzikuVx — CHANGES_REQUESTED** [review]
@JulioCesarMatias please rebase your commit on top of `release_3.0.0` branch. We already have content in `master` that should not go into 3.0

**Comment by avsaase** [comment]
Didn't we discuss this in the past and decided against changing everything? If we do change it anyway, then the multirotor controller should be called `PIDCD`, since we now have the control derivative term.

**Comment by JulioCesarMatias** [comment]
> Didn't we discuss this in the past and decided against changing everything? If we do change it anyway, then the multirotor controller should be called `PIDCD`, since we now have the control derivative term.

i agree

**Comment by JulioCesarMatias** [comment]
@DzikuVx I never did a rebase, would the correct rebase command here be `git rebase -i release_3.0.0 ~ 1` ?

**Comment by DzikuVx** [comment]
let's just move it to 3.1, that will be better I think. Less troubles :)

**Comment by JulioCesarMatias** [comment]
in https://github.com/iNavFlight/inav/blob/master/docs/PID%20tuning.md#tpa-and-tpa-breakpoint the ´AlexYork.net´ link is broken

**Comment by JulioCesarMatias** [comment]
in https://github.com/iNavFlight/inav/blob/master/docs/PID%20tuning.md#tpa-and-tpa-breakpoint the ´AlexYork.net´ link is broken

**Comment by JulioCesarMatias** [comment]
in https://github.com/iNavFlight/inav/blob/master/docs/PID%20tuning.md#tpa-and-tpa-breakpoint the ´AlexYork.net´ link is broken

**Pull request closed without merging**
