### PR TITLE
Change to STM32 faster processing operations

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
The STM32 can handle multiplication faster than division.

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]

**Comment by JulioCesarMatias** [comment]
I think this should always be done when there is a function in the loop. In Setup it is not so necessary, as it runs only once in the machine cycle. The compiler should do this alone, but unfortunately it doesn't.

117882663-ea21a980-b2ed-11eb-95e9-dffb792ddb0f

**Comment by avsaase** [comment]
Does this really make a meaningful difference? If it does we should make this change in many other places as well.

**Comment by JulioCesarMatias** [comment]
> Does this really make a meaningful difference? If it does we should make this change in many other places as well.

This PR is just a door to change the other divisions. The optimization reduces the machine cycle, but I don't know how much, it is necessary to measure the machine cycle after the optimizations to get the result. But I think this should always be done going forward. I'm not an excellent programmer, but I try to contribute with my little knowledge.

**Comment by harry1453** [comment]
Optimizations like this should really be sorted out by the compiler.. I know it's a generic ARM compiler, not one specific for STM32, but cmon

**Comment by rmaia3d** [comment]
Not only the amount the divisions affects the overall final speed, but also the compiler used, it's optimization settings and if the FPU is used or not (though that should be pretty much obvious). What can be easily missed, though, is that all literals must be defined as floats as well, otherwise they're treated as doubles and everything else around it gets promoted. Even though some F7/H7 FPU's can handle doubles, [this document from ST](https://www.st.com/resource/en/application_note/dm00047230-floating-point-unit-demonstration-on-stm32-microcontrollers-stmicroelectronics.pdf) shows that it's slower than pure floats. On F4, which the FPU is float (single precision) only, the doubles are treated entirely by software, as if no FPU was present... Yuck!

I've ran some tests comparing these differences (and also division vs multiplication) across different compilers and with different optimization levels. Here are the results I got:

Timings_v11_20210615

From the table, it's possible to see that swapping one division by a multiplication did indeed improve speed for almost every compiler combination, except the gcc included with ST's CubeIDE under -Ofast (for a reason I wasn't able to determine yet).

**Comment by harry1453** [comment]
The point about doubles not making any use of the FPU is interesting. Doubles are in use throughout the project.

However... POITROAE. What's the motivation for this? Especially when things like switching PID/Battery profiles takes upwards of a second, why is this being focused on?

**Comment by DzikuVx** [comment]
let me drop a few notes over here gents.
What the compiler does with the code depends on the compiler and its options. You optimize for size with `-Ofast` and compiler will optimize for speed. You optimize for size with `-Os` and it will not convert anything that is not size related.

INAV is too big to compile everything with `-Ofast` and for some files we do have to use `-Os`. This is why, in perfect world it would be awesome to let compiler to handle that. But we do not live in a perfect world ;)


So, @JulioCesarMatias thank you very much for this contribution and we will take it and merge it :) It does not hurt anyone and it's super nice that someone thinks about performance!

**Comment by rmaia3d** [comment]
> The point about doubles not making any use of the FPU is interesting. Doubles are in use throughout the project.
> 
> However... POITROAE. What's the motivation for this? Especially when things like switching PID/Battery profiles takes upwards of a second, why is this being focused on?

Yes, I was surprised also. Analyzing the produced code (assembly) from those tests, when doubles are involved, the compiler simply does not generate of the FPU specific instructions and instead create calls to the double math functions from the linked libraries. That means everything is handled in software only, without ever touching the FPU (even if it's enabled both in the actual MCU registers and the compiler/linker flags). I haven't tested yet, but probably for the Cortex-M7 cores, with double precision FPU, the compiler will then not "ignore" the FPU, but even so, it's does not seem to be fast as floats. So, with performance in mind, doubles should really only be used where the actual extra precision is needed and only if a double-precision FPU is present. Otherwise, floats are the fastest option.

With that said, yes, this does not need to be everywhere in the code. IMO, just the "hot path" should have extra attention to this, basically the GNC loop and associated tasks (filters, etc). Startup functions or other "non-critical" routines, where a few extra microseconds won't really matter, are just fine without squeezing the last bit of performance from the clock cycles... ;-)

**Comment by rmaia3d** [comment]
> let me drop a few notes over here gents.
> What the compiler does with the code depends on the compiler and its options. You optimize for size with `-Ofast` and compiler will optimize for speed. You optimize for size with `-Os` and it will not convert anything that is not size related.
> 
> INAV is too big to compile everything with `-Ofast` and for some files we do have to use `-Os`. This is why, in perfect world it would be awesome to let compiler to handle that. But we do not live in a perfect world ;)
> 
> So, @JulioCesarMatias thank you very much for this contribution and we will take it and merge it :) It does not hurt anyone and it's super nice that someone thinks about performance!

Just a few words about the compiler flags, -Os does not mean the compiler only optimizes for size and nothing else. Both from clang and gcc manuals, -Os means basically "same as O2, but with the few optimizations that could increase code size (speed-size tradeoff) turned off". Meaning, it does also optimize for speed, just the priority becomes size. Where speed would come at a detriment of size, it chooses size. Some IDEs even call Os "Level 2 balanced". Clang offers -Oz which goes a little bit more aggressive on size reduction, but it's still O2 at a general level, just with even more emphasis on code size. 

And -Ofast is the most aggressive of optimizations for speed, it's O3 plus more aggressive stuff, disregarding even some language standards in order to produce the fastest possible code, without any concern if the size actually increases (but this doesn't mean the code size will always be larger, it's just that when faced with a choice between speed and size, the compiler will choose max speed).

https://clang.llvm.org/docs/CommandGuide/clang.html  (Look under Code Generation Options)

https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html

**Pull request merged**
