### PR TITLE
RTH: Fix slow RTH when home is reset

### PR DESCRIPTION
**Pull request by digitalentity**
A fix for #245. Please review and comment.

Now home altitude is not reset in some cases (one case is being within `nav_min_rth_distance` to previous home position).

### CODE REVIEW

**Comment by theArchLadder** [comment]
Just did a quick test flight. Descent velocity looks correct now. :+1: 

But i think i found a new problem when RTH is activated within min_rth_distance:
- Heading is changed to launch heading when activated from rate mode
- Heading is not changed when activated from poshold

**Comment by digitalentity** [comment]
@theArchLadder 
This shouldn't happen. Heading is reset to current heading regardless of mode. Do you have a log of both attempts?

**Comment by theArchLadder** [comment]
@digitalentity I don't, i will try to make a log for you later today as long as the weather stays okay.

**Comment by stronnag** [comment]
In my tests, it has been consistent. Heading is NOT reset to landing heading for both proximity cases (only for 'distant' RTH case).

**Comment by digitalentity** [comment]
@theArchLadder please try to confirm your glitch. If it's a bug we need to fix it before merging this PR.

**Comment by theArchLadder** [comment]
@digitalentity Sorry, i have been a bit busy today. I will try and make a log for you as soon as i can.

**Comment by digitalentity** [comment]
@theArchLadder No problem, take your time :smile:

**Comment by theArchLadder** [comment]
@digitalentity Well what could be more important than inav :wink: 
Just did a quick test flight now (disarm between every step):
1. take of in rate mode, turn 90 degrees, activate RTH, heading changes back 90 degrees.
2. same thing again
3. activate poshold and turn 90 degrees, RTH does not change heading
4. take of in rate mode again, turn 90 degrees, RTH does not change heading now!

So it seems like it has something to do with if poshold/any nav has been activated...?
BBLog on the way.

**Comment by digitalentity** [comment]
Yes, blackbox would be very helpful! Thanks!

**Comment by theArchLadder** [comment]
@digitalentity 
https://www.dropbox.com/s/j6rghhos438scy0/blackbox_log_2016-05-28_181526_RTH-heading-bug?dl=0

**Comment by digitalentity** [comment]
Thanks! Will take a crack at it tomorrow.

**Comment by theArchLadder** [comment]
Launch was always heading north, RTH activation was always heading west... As long as i didn't forget it on any of the flights ;)

**Comment by theArchLadder** [comment]
Dammit, looks like i was wrong again!
Heading is changed to north (not launch heading) when RTH is activated, this is true for every RTH activation until poshold has been active once, after that the heading is no longer changed.

**Comment by stronnag** [comment]
Not my experience, as you can see from the logs posted for the disarm patch --- but OTOH, my RTH switch always goes via PH, even if it's momentary. Interesting ...

**Comment by theArchLadder** [comment]
@stronnag Yes that is interesting! I tried just flipping the poshold switch on and off, that was enough to stop the heading changes... Sounds like a problem with some initialization thingy

**Comment by theArchLadder** [comment]
@digitalentity Let me know if i can put some navDebug[] somewhere to help narrow it down.

**Comment by digitalentity** [comment]
@theArchLadder ok, it should be fixed now.

**Comment by digitalentity** [comment]
@theArchLadder, @stronnag did you have a chance to test the latest commit to this branch?

**Comment by stronnag** [comment]
I flew it (only one pack, due to rain) on Sunday evening. No adverse affects (as my RTH switch goes via PH the problem has always been masked for me).

**Comment by digitalentity** [comment]
I'll wait for @theArchLadder then as he was the one having this issue.

**Comment by theArchLadder** [comment]
@digitalentity Sorry for not responding, i have been busy. I did a short test flight just now though and it seems to work as it should :+1:

**Pull request merged**
