### PR TITLE
Increase max MSP port count to 3

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by DzikuVx** [comment]
@digitalentity will F1 be able to handle that?

**Comment by digitalentity** [comment]
@DzikuVx Yes, F1 has enough memory and performance penalty is negligible if traffic is low.

**Comment by rb1205** [comment]
If that's the case, then why MSP is limited to 2 ports in the first place?

**Comment by digitalentity** [comment]
@rb1205 hard to tell. Probably nobody expected we'll need more than two. One for PC connection, the other for OSD if necessary. Originaly it was only one MSP port allowed.

**Pull request merged**
