### PR TITLE
Add min and max airspeed alarms

### PR DESCRIPTION
**Pull request by igor-eremyashev**
Maintaining and keeping an eye on airspeed is crucial for fixed wings, so low and high airspeed alarms would be very helpful. For now I'm still waiting for airspeed sensor to test it, so it would be great if anyone could try it out.
Related issue: #5923

### CODE REVIEW

**Comment by DzikuVx** [comment]
Why closed? Seems to be quite useful

**Comment by igor-eremyashev** [comment]
> Why closed? Seems to be quite useful
Sorry about that, noticed I used wrong github account to commit changes - fixed it

**Comment by igor-eremyashev** [comment]
@Kernelscr1 That would be awesome! I didn't get a chance to try it myself yet.

**Comment by Kernelscr1** [comment]
@igor-eremyashev I need help to compile this branch. How can we solve this problem? Can we chat in telegram?

**Comment by igor-eremyashev** [comment]
@Kernelscr1 Sure, how can I find you on telegram?

**Comment by Kernelscr1** [comment]
@igor-eremyashev acetheranger

**Comment by igor-eremyashev** [comment]
@Kernelscr1 I can't find you, please use the [`link`](https://t.me/mov_eax_ebx) to reach out to me

**Pull request merged**
