### PR TITLE
Changed arming procedure for fixedwing

### PR DESCRIPTION
**Pull request by digitalentity**
Continuation of #358, #310.

### CODE REVIEW

**Comment by oleost** [comment]
Ah, see you added CLI option.

Will compile and test both on multirotor and fixedwing as soon as I get the time.

**Comment by oleost** [comment]
@digitalentity Hi, with fixed_wing_auto_arm turned on and motor stop it wont arm at all, not with rudder or with throttle

**Comment by oleost** [comment]
Tried making a new pull request to this one, but Im not very familiar with github yet so I could not get everything synced up.

Got it working again, this time with the cli command. I kept all the work you have done, but kept my original rc_controls.c, with just the new cli value added.

http://pastebin.com/3jKFeLYe

**Comment by digitalentity** [comment]
@oleost looks like I have missed a test for ARMed state when blocking disarming - this resulted if blocking arming as well. Fixed based on your code, thanks!

**Comment by oleost** [comment]
Great, will do some testing when I get off work, both on airplane and quad.

**Comment by oleost** [comment]
@digitalentity I benchtested this on both my airplane and my quad. Seems to works as intended. Should be ready for merge. Unless you want more people to test. 

@sppnk

**Comment by sppnk** [comment]
thks for this. I will test asap.

**Comment by oleost** [comment]
@sppnk Got  to test it?

**Comment by sppnk** [comment]
Not tested yet, and sorry for the delay, but this is going to be the solution to accidents like my last fly-away (I got the plane dissarmed in-flight because of a faulty rx antenna soldering, and the RTH was never reached -recovered 1km far thanks to openlrsng beacon and video signal-). 

With this PR that kind of problems will dissapear, and I don't guess it could cause other type of risks. 

Improving security. Good.

**Comment by oleost** [comment]
@digitalentity should this get merged into development?

**Comment by digitalentity** [comment]
@oleost it was not flight-tested yet or at least nobody reported if it works as intended. If you flight-tested it - I can merge.

**Comment by oleost** [comment]
Not flight tested, only bench tested on both an airplane and multirotor. 

Maybe rebase and then I can do a flight test if you  want.

**Comment by digitalentity** [comment]
Rebased

**Comment by sppnk** [comment]
great, you are amazing !!

**Comment by oleost** [comment]
@digitalentity Had a test flight today, it worked as expected.

Also did a quick bench test with my quad setup, no issue there either.

I however had an failed RTH after a couple of succesfull tests, also a successfull test after. Unsure why, but it should not be related to this, I am however compiling with gcc v6.2.0

Link to cli dump and black box log https://drive.google.com/open?id=0B-yHzNtOXxbEU1BiSnFacGtBTmM

Its 4/4 log and around 2:50 I believe the failed one is.

It just climbed and then contuined straight. I could not let i go any further to see if it was going to turn as I was flying without fpv.

After the failed RTH I tried a new one and let it circle a couple of times over home.

@stronnag Maybe you could make an mwptools video? I had some issues setting it up again.

**Comment by stronnag** [comment]
https://vimeo.com/184735195 for your viewing pleasure. What happened to that RTH?

Good LOS catch at 300m out.

**Comment by oleost** [comment]
Thank you stronnag. 

Looking at the video its climbs slow the last meters up to the RTH altitude of 50m. Maybe if I waited a couple of seconds more it would have turned. Probably just that.

**Comment by oleost** [comment]
Altrough in real life it felt like it was done climbing for a much longer perioed than the log shows.

In flight it looked like it climbed quickly to wanted height, and then just contuined forward.

Wondering is it possible to see the baro value compared to the GPS height value?

**Comment by stronnag** [comment]
On some of my multi-rotors, occasionally on RTH it will appear just to say stationary at for about 30 seconds, maybe hunting for altitude (though it has always turn to home). Maybe 1 time in every 10. At least it's not 300m out and flying to China.

**Comment by oleost** [comment]
Remember this is fixed wing, so it will need to climb and the turn. 

Guess I just have to keep this firmware on and do addional testing as soon as the weather permits. 

Only thing I can think of is that maybe it should start to turn home when its lets say 10% within target RTH altitude. As probably when getting closer to the target altitude the PID controllers do less.

**Comment by oleost** [comment]
@digitalentity Anymore you want me to do before merging it ?

I believe its ready.

**Comment by digitalentity** [comment]
@oleost thanks for testing, merged. Docs and wiki require updating for a new CLI parameter

**Pull request merged**
