### PR TITLE
[CI] CI updates

### PR DESCRIPTION
**Pull request by fiam**
- [CI] Trigger CI on PR only
- [CI] Use actions/cache to cache the ARM toolchain

### CODE REVIEW

**Comment by digitalentity** [comment]
Will it re-run the tests for new commits made to an already open PR?

**Comment by fiam** [comment]
> Will it re-run the tests for new commits made to an already open PR?

It will. I've tested it in my personal fork.

**Review by digitalentity — APPROVED** [review]
LGTM

**Comment by fiam** [comment]
@digitalentity I've added some changes in the makefiles to retrieve the current firmware version via `make print_version`. PTAL

**Review by digitalentity — APPROVED** [review]
Still LGTM :)

**Comment by fiam** [comment]
Thanks! Merging, then :-)

**Pull request merged**
