### PR TITLE
Add new target DALRCF722DUAL and add DALRCF405 board description

### PR DESCRIPTION
**Pull request by nyway**
Add new target DALRCF722DUAL and add DALRCF405 board description
about DALRCF722 detal here:
http://www.dalrcmodel.com/DALRC/plus/view.php?aid=188

### CODE REVIEW

**Review by shellixyz — CHANGES_REQUESTED** [review]
Could you please convert the timer definitions in `target.c` to the new style. Example: https://github.com/iNavFlight/inav/blob/development/src/main/target/MATEKF722/target.c

Otherwise LGTM.

**Comment by nyway** [comment]
@shellixyz 
Sure,this style looks clearer.
I've tested,so far so good.

**Review by shellixyz — CHANGES_REQUESTED** [review]
Looking good. Could you please rebase your branch on the development branch and it is going to be good to merge.

**Comment by nyway** [comment]
@shellixyz 
Sorry I'm not familiar with this.How should i operate?

**Comment by nyway** [comment]
How about i close this pull request then fork development branch to my repository and open a new pull request?

**Pull request closed without merging**
