### PR TITLE
MAVLink telemetry implementation for INAV

### PR DESCRIPTION
**Pull request by digitalentity**
MAVLink telemetry made possible on SPRACINGF3 and SPARKY targets.

### CODE REVIEW

**Comment by olexs** [comment]
What's the status on this PR? I've seen that Mavlink is now merged in CF 1.13 RC1. Would be great to also have it in INAV, for those of us with OSDs that don't talk MSP or LTM :)

**Comment by stronnag** [comment]
It is targeted for v1.2. If you download the diff (see below), it applies to current master and builds for F3 targets.

**Comment by oleost** [comment]
I have an build from 24.06.2016 and I cant seems to find a way to enable MAVLink?

In the dropdown menu mavlink is not mentioned.

This is on SPRACINGF3

Build Im using https://drive.google.com/open?id=0B-yHzNtOXxbESUFlaWxsYVFHYWM

**Comment by stronnag** [comment]
You have to set the function code in the CLI
256 for MAV
257 for MSP + MAV
`serial n 257 etc`

**Comment by skaman82** [comment]
This should be in the GUI

**Comment by sppnk** [comment]
Could be done a minimal set of MAVLink telemetry (one-way downlink, not polling) for F1 targets? Lets say, only GPScoords, RSSI, Vbat, HDOP/numsats, distance to home and heading to home. 

For now, although Frsky has been removed from F1's I am compiling my own version for naze and CC3d enabling it and it fits, so I can have Frsky telemetry in my 9x transmitter. 

As there are many people with 9x/9XR transmiters, modded for telemetry, a very simple set of MAVLink should be nice for this radios (with mavlink version firmware, of course).

**Comment by digitalentity** [comment]
@skaman82 @oleost check for INAV 1.2.0 was faulty in Configurator, fixed.

**Comment by oleost** [comment]
@digitalentity Thanks, can confirm its showing up and working in configurator.

**Comment by stronnag** [comment]
@sppnk, you can build F1 (NAZE) for MAVLink with gcc 6.1 (it will not build with gcc 4.9).

**Comment by sppnk** [comment]
@stronnag, thanks. I have built NAZE and CC3D targets (also including Frsky telemetry) and it fits nicely in both FCs. Great. 

Hopefully I will test soon Tower apk telemetry and er9x MAVLink in my 9x transmiter.

Good job.

PD: my gcc -dumpversion gives this: 5.3.1. Is it ok or can give problems?

**Pull request merged**
