### PR TITLE
Microsisr syntax fix

### PR DESCRIPTION
**Pull request by yarreg**
https://repl.it/@yarreg/iNavFlightinavpull4803

### CODE REVIEW

**Review by digitalentity — COMMENTED** [review]
Data source for `ms` is `sysTickUptime` which is `timeMs_t` (which is unsigned 32-bit int), so this typecast is unnecessary. If it overflows here, we'll overflow the `sysTickUptime` 1 millisecond later anyway.

However, overflow of `sysTickUptime` millisecond counter will only occur after 49.7 days, so we're probably safe regardless. At least I can't imagine somebody flying for over a month.

**Comment by yarreg** [comment]
@digitalentity thanks for reply. 
As you can see, such code is just confusing. Usually, when there is such a cast is expected that value might exceed uint32_t.

>> At least I can't imagine somebody flying for a month.

Can swim :)

**Comment by yarreg** [comment]
Please check now

**Comment by yarreg** [comment]
Please check now.

**Pull request closed without merging**
