### PR TITLE
Add proper % RSSI for CRSF [0..99%]

### PR DESCRIPTION
**Pull request by OptimusTi**
Using signal strength instead of LQ for % RSSI [0..99]. This will allow users to use regular RSSI and regular alarm setting.

Scale based on vendor specs and LoRa numbers. I recommend setting your RSSI alarm % to 30% (-100 dBm).

- No channel injection needed.
- Adds % RSSI to disarm page too.
- Allows crsf users to use RSSI in programming logic conditions.
- Shows % RSSI in the Setup/Info tab of the configurator.

### CODE REVIEW

**Comment by avsaase** [comment]
I suggest to first linearize the dBm value so that the RSSI in 0-99% scale can be interpreted as an indication of the available range compared to the current distance. I'm also a little suspicious about the -130dBm sensitivity TBS reports. Perhaps -115dBm for the minimum would be more realistic except in completely noise-free environments. Alternatively, the range could be configurable by the user but I don't think that's necessary.

**Comment by OptimusTi** [comment]
The proposed scale was used to keep as close to what's the expected link budget in lora systems. I agree with the -130 dBm (or Semtech's -137 in paper claim) but this keeps the numbers in line without cooking them.

**Comment by avsaase** [comment]
In my opinion, a percentage should be used to denote a fraction of a total. The question now is, what total are we talking about? In this context I think maximum range is a logical choice.

**Comment by OptimusTi** [comment]
Based on LoRa documentation, I think I should change the minimum to -120. This still aligns with what's I'd expect. 20% signal at -102dBm is reasonable and everybody is happy.

**Comment by Jetrell** [comment]
Hopefully this should allow LQ and SNR to work in the logic conditions?  Last time I tried, I couldn't get it to work.

**Comment by OptimusTi** [comment]
This just changed "regular" inav RSSI from LQ, that was injected to channel 17, to use signal strength.

Too many videos showing LQ twice if you know what I mean...

**Comment by OptimusTi** [comment]
> Hopefully this should allow LQ and SNR to work in the logic conditions?  Last time I tried, I couldn't get it to work. 

LQ and SNR in Logic conditions? Eeeew! Hey, it's your model. 😁 

I'll take a look...

**Comment by avsaase** [comment]
Okay, let's merge this. This putting stuff on a channel business makes no sense anyway.

**Pull request merged**
