### PR TITLE
Omnibus F4 pro wiring diagrams by skaman82

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by skaman82** [comment]
RX setup image is missing

**Comment by DzikuVx** [comment]
and fixed

**Comment by skaman82** [comment]
Great, good to go!

**Review by digitalentity — APPROVED** [review]

**Review by digitalentity — APPROVED** [review]

**Comment by jflyper** [comment]
The new softserial (#2346) handles half duplex on TX pad; we no longer need to use RX pad.

**Comment by vavisimo** [comment]
Guys i think there is an error on the JST port where PWM outputs are (J11) , somewhere it tells GND-5v- PWM3- PWM4- PWM2- PWM1

on the pictures it sais GND-5v- PWM1- PWM2- PWM3- PWM4

which one is the rigt one?

**Pull request merged**
