### PR TITLE
[GPS] Change autobaud logic for UBX protocol to send baud change command in bulk

### LINKED ISSUE #4178: 2.1.0 RC1 delayed GPS acknowledgement time
**Target** -    _**Omnibus F4 Pro**_
**GPS module -**     _**Matek SAM M8Q + 5883**_
**Firmware version** -    _**Inav 2.1.0 RC1**_

This was confirmed by the configurator and a stop watch.
Both these tests were confirmed with both firmware's uses both and alternate 2.0.0 and 2.1.0 configurators. _Not just with the configurator designed for its firmware._ I wanted to be sure were the problem was.

**Inav 2.0.1 operation -**
When the flight controller is initialised and power.  
The GPS will take 3 seconds to get acknowledgement from the flight controller. 
Then 1.5 seconds to hookup and start transferring data.
It received 4 timeouts.

2 0 1 gps timeouts

**Inav 2.1.0 operation -**
When the flight controller is initialised and power.  
The GPS will take 10 seconds to get acknowledgement from the flight controller. 
Then 43.5 seconds to hookup and start transferring data.
It received 24 timeouts.

2 1 0 gps timeouts

I ran these tests 3 times. Back and fort between flashes. And 6 times times total, between both configurators.
And the inav to GPS acknowledgement time was precisely 10sec, and precisely 43.5 sec before inav would acknowledge the data.
That sounds too precise to me, to just be chance.

These are the only DIFF settings for Ports and GPS config. For repo.

serial 0 64 115200 38400 0 115200
serial 5 2 115200 115200 0 115200

set gps_provider = UBLOX7

### PR DESCRIPTION
**Pull request by digitalentity**
Change autobaud behavior on UBLOX/UBLOX7 protocols. Intended to fix #4178

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested on https://inavflight.com/shop/s/bg/1225211 and https://inavflight.com/shop/s/ae/32509281424

**Comment by ghost** [comment]
Thank you Konstantin, for your efforts. 
When RC2 is released, we'll give it a go with the SAM M8Q and report back.

**Comment by digitalentity** [comment]
@kardon18 I can give you a hex to test if you tell me which target you need

**Comment by ghost** [comment]
> 
> 
> @kardon18 I can give you a hex to test if you tell me which target you need

Sure - Omnibus F4 Pro

**Comment by digitalentity** [comment]
Here you are [inav_2.1.0_OMNIBUSF4PRO.hex.zip](https://github.com/iNavFlight/inav/files/2751946/inav_2.1.0_OMNIBUSF4PRO.hex.zip)

**Comment by ghost** [comment]
You did good :+1:  
Its faster and better than before !!
Soon as I power the quad and click connect on the configurator, the GPS icon is BLUE.
It has NO timeouts at all now.
Frequency is still at 10hz 95% of the time and 9.9hz the other 5%.  So it all looks good.

Thank you

**Comment by leeph** [comment]
Hi guys - any chance I could test this on MATEKF722SE target please? The GPS behaviour is somewhat impeding a test build of mine and it'd be really useful to remove this unwanted behaviour.

Many thanks in anticipation :)

**Comment by kardon18** [comment]
@leeph 
It was found the bug was related to the Matek SAM-M8Q GPS module.
_The fix was included in RC2._ 
I have tried RC2 it with another FC that I'm using a NON compass, Matek SAM M8Q with. And it also has no problems now.

I was under the impression that you were using the Matek SAM M8Q + Compass as well, from your post on the issue ?

**Comment by ghost** [comment]
@leeph
It was found the bug was related to the Matek SAM-M8Q GPS module.
The fix was included in RC2.
I have tried RC2 with another FC that I'm using a NON compass, Matek SAM M8Q with. And it also has no problems now.

I was under the impression that you were using the Matek SAM M8Q + Compass as well, from your post on the issue ?

**Comment by leeph** [comment]
Yes that's correct - I didn't realise RC2 had just been released. Flashing now, many thanks.

**Comment by kardon18** [comment]
Hi Konstantin. I loaded RC3 today. 
And have found this delayed response of the Matek SAM MQ8, both with and without Mag, is back again.
Not sure if something was merged, that has affected it again.
The delay is not as bad as the original 45 seconds. But its still around 25 seconds, before the flight controller will recognize the GPS. As can be seen from the 7 timeouts.

capture

**Comment by ghost** [comment]
Hi Konstantin. I loaded RC3 today. 
And have found this delayed response of the Matek SAM MQ8, both with and without Mag, is back again.
Not sure if something was merged, that has affected it again.
The delay is not as bad as the original 45 seconds, before this fix. 
But its still around 25 seconds, before the flight controller will recognize the GPS. As can be seen from the timeouts.

capture

I have rolled it back to RC2, which had the fix. And there was no delay. 
So it does appear to be related to a merge that has affected this in RC3.

**Comment by digitalentity** [comment]
Interesting, didn't notice anything in my tests. Will test again.

**Comment by kardon18** [comment]
> 
> 
> Interesting, didn't notice anything in my tests. Will test again.

I decided to do a bit more testing around this matter.
I re-flashed RC3 again. And did not load my setting from RC2 this time. And I found the results were mixed. 
It would have a delay of 15 to 25 second every few cycles of the Configurator and FC, and get many TIMEOUTS.
While other times the GPS and FC would start talking within 10 seconds and only get 4 TIMEOUTS. 
And not get any communication errors in the field, according to the OSD, when it had a Sat lock, and I did a power cycle reboot.

I also tested RC3 firmware with RC2 configurator (just to be sure). And the result were the same with both configurators.

It most certainly isn't as fast and consistent as it was with the fix in this PR. When it had zero TIMEOUTS, and instant communication between the two.

**Comment by ghost** [comment]
> 
> 
> Interesting, didn't notice anything in my tests. Will test again.

I decided to do a bit more testing around this matter.
I re-flashed RC3 again. And did not load my setting from RC2 this time. And I found the results were mixed. 
It would have a delay of 15 to 25 second every few cycles of the Configurator and FC, and get many TIMEOUTS.
capture


While other times the GPS and FC would start talking within 10 seconds and only get 4 TIMEOUTS. 
And not get any communication errors in the field, according to the OSD, when it had a Sat lock, and I did a power cycle reboot.
capture
I also tested RC3 firmware with RC2 configurator (just to be sure). And the result were the same with both configurators.

It isn't as fast and consistent as it was with the fix in this PR. When it had zero TIMEOUTS, and instant communication between the two.
BUT, it isn't as bad as it was before you wrote this fix.

**Comment by ghost** [comment]
> 
> 
> Interesting, didn't notice anything in my tests. Will test again.

Any word Konstantin? Did you get around to doing other tests with the SAM M8Q, to confirm or deny the issue is back with RC3?

**Comment by digitalentity** [comment]
I was unable to reproduce on two modules I have here. Test on SAM M8Q still pending.

**Comment by kardon18** [comment]
> 
> 
> I was unable to reproduce on two modules I have here. Test on SAM M8Q still pending.

 When you say pending. Do you mean Matek has one coming in the mail for you?

Something else I found with the SAM M8Q. 
It will run at 5.0Hz occasional when its connected, according to the GPS statistics. And continue to do so until the FC and GPS is rebooted.
I always use Ublox7, so it should be 10Hz.

**Comment by ghost** [comment]
> 
> 
> I was unable to reproduce on two modules I have here. Test on SAM M8Q still pending.

 When you say pending. Do you mean Matek has one coming in the mail for you?

Something else I found with the SAM M8Q. 
It will run at 5.0Hz occasionally when its connected, according to the GPS statistics. And continue to do so until the FC and GPS is rebooted.
I always use Ublox7, so it should be 10Hz.

**Comment by digitalentity** [comment]
This is odd. On my random Chinese M8N it works flawlessly, on Matek SAM-M8Q it takes a while until it configures correctly.

I'll try figuring out why this is happening, but this is not a blocking bug for 2.1

**Pull request merged**
