### PR TITLE
New MSPV2 messages small changes

### PR DESCRIPTION
**Pull request by shellixyz**
Best merged before 1.9 release

### CODE REVIEW

**Comment by fiam** [comment]
@shellixyz I'm not sure about these. The removed bytes seem to break compatibility, don't they?

**Comment by shellixyz** [comment]
@fiam They are not because it is new messages not present in any release: MSP2_INAV_ANALOG, MSP2_INAV_MISC and MSP2_INAV_SET_MISC.

**Comment by fiam** [comment]
@shellixyz Thanks for the clarification. I hadn't realised they were the new messages.

**Comment by digitalentity** [comment]
@shellixyz I'm going to merge this into 1.9, but I've already merged https://github.com/iNavFlight/inav-configurator/pull/328. Can you make a new PR into Configurator to accompany this changes?

**Comment by shellixyz** [comment]
@digitalentity Sure I already prepared the PR

**Pull request merged**
