### PR TITLE
Add support HDZero 30x16 mode

### PR DESCRIPTION
**Pull request by geoffsim**
Add HD 30x16 HD Zero mode to the latest MSP OSD driver code.
Remove statistics code as it was only useful during development.
Add code to allow OSD menus to function correctly.

Configurator Caveat:
The generalisation of the MSP OSD code has meant that the FC will need rebooting after selecting a new OSD video format as there is no current way to notify the OSD driver code of a video mode change after initialisation.

### CODE REVIEW

**Comment by geoffsim** [comment]
@jeffhendrix can you please try these changes before I formalise the PR. Note the caveats. If you need a hex file, let me know for what FC.

**Comment by jeffhendrix** [comment]
I don't have HDZero goggles (just DJI)

**Comment by geoffsim** [comment]
It would be good if you could just make sure I have not caused a problem with the DJI MSP OSD. The HDZero stuff is working fine now.

Geoff

**Comment by DzikuVx** [comment]
@geoffsim is this the PR that fixes problems you mentioned in the email?

**Comment by geoffsim** [comment]
@DzikuVx yes. I have moved it to ready for review and will retest when it is merged.

**Pull request merged**
