### PR TITLE
Time overflow issues

### PR DESCRIPTION
**Pull request by digitalentity**
- Fix micros() returning gibberish after crossing the 32-bit boundary
- Optimisation to async gyro

### CODE REVIEW

**Comment by digitalentity** [comment]
@oleost @DzikuVx would be great if you could also test this with and without async gyro.

**Comment by sppnk** [comment]
Will this fix the limit for CC3D? I am flying close to the 60 min time, thanks to packs of 18650 batteries. Thx.

**Comment by digitalentity** [comment]
@sppnk unfortunately no, only 64-bit time targets (F4-F7) are affected by the bug. F1s still use 32-bit time which will still overflow at 1h15m.

**Comment by sppnk** [comment]
Are there any plans to fix the F1 targets? thx

**Comment by digitalentity** [comment]
Technically we can support 64-bit time on F1 boards, but that will come at expense of something - flash space isn't unlimited :disappointed:

**Comment by digitalentity** [comment]
Tested on EVO and REVO in sync and async gyro modes for 2 hours. No issues. Merging.

**Comment by sppnk** [comment]
Ok, thx @digitalentity , but I am not sure if F3 has the same problem or should I go to F4? (the wiki is not clear -you said F4-F7 boards, but the wiki says different-)

**Comment by digitalentity** [comment]
My typo. I ment F3-F7. Only F1s are getting more and more limited in features.

**Comment by sppnk** [comment]
good.

**Pull request merged**
