### PR TITLE
Add LPS25HB driver for the new Airbot NXT board

### PR DESCRIPTION
**Pull request by robert-b**
ready for review.

### CODE REVIEW

**Comment by digitalentity** [comment]
Thanks! Looks ok to me. Will test on my boards and merge.

**Comment by robert-b** [comment]
There is at least one problem.
the output data rate is 25hz - i cannot get the scheduler working with such a slow update rate.
you may have a look - i just hurried up to complete the driver.

**Comment by digitalentity** [comment]
Ok, noted. Will fix that.

**Comment by robert-b** [comment]
ohh, the new baro needs an entry in the gui as well.

**Comment by digitalentity** [comment]
Doesn't look like valid baro readings to me. Needs debugging. Do you have datasheet for this sensor?

image

**Comment by digitalentity** [comment]
Superceded by https://github.com/iNavFlight/inav/pull/3192

**Pull request closed without merging**
