### PR TITLE
Fix rc yaw command.

### PR DESCRIPTION
**Pull request by martinbudden**
@DzikuVx , @digitalentity : Here's my proposed fix.

@DzikuVx - I'm really busy this weekend and don't really have time to do any of this, so this is untested. Can you test and if it is OK merge in? (I think it is important to get the code back into a flyable state).

### CODE REVIEW

**Comment by stronnag** [comment]
Successfully hover tested in the garden (yaw is correct again).

I will test this fully later today

**Comment by DzikuVx** [comment]
@martinbudden @stronnag I'm without possibility to flight test. I will try pseudo benching since I should have one old FC somewhere around.

Edit:
Nope, no bench testing either, no radio around.

**Comment by stronnag** [comment]
Flight tested, manual (LOS/Horizon and navigation modes (RTH, PH, WP Missions). Yaw works as expected again. 

Rate changes took a little while to get back to a comfortable state. It would be helpful to document the change and approximate translation between old and new rates in the wiki and eventally the release notes.

**Comment by DzikuVx** [comment]
I will prepare equation to translate old to new. 
Default 200dps is old 0 (more less)

**Comment by stronnag** [comment]
Thanks, I think that will be very useful.

**Comment by DzikuVx** [comment]
@stronnag [Rates conversion](https://github.com/iNavFlight/inav/wiki/Rate-conversion-for-INAV-1.2)

**Comment by stronnag** [comment]
Excellent. I ended up with 10% by experiment / observation.

**Pull request merged**
