### PR TITLE
Require ACC calibration only if ACC might be used during flight

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by DzikuVx** [comment]
@breadoven @stronnag @MrD-RC WDYT?

**Comment by stronnag** [comment]
Can't say I have any firm view either way, but tend towards being sceptical of the benefit. 
Sure, for people who only **ever** fly in acro and **never** failsafe it saves a minor setup inconvenience, however for what is I suspect the majority of users, there's little benefit and possibly an increased support burden for the project.
* "Yesterday I tested in acro"
* "Today I couldn't arm and so could not fly"
* " .... and I'm going to totally fail to report that last night I enabled F/S RTH"

**Comment by breadoven** [comment]
Isn't this related to people have problems powering up on something moving ... seem to remember it was a boat rocking in the swell ?

**Comment by stronnag** [comment]
In which case ignore me.

**Comment by breadoven** [comment]
Ah, now that I check the boat thing was gyro related https://github.com/iNavFlight/inav/pull/7624/files.

**Comment by MrD-RC** [comment]
I thought that there was already a workaround merged for pilots who fly from boats?  

I can see the benefits: 
- the CLI parameter is not needed to be changed when you fly from a boat
- there is no danger of not turning it back on after the boat day is finished with

The only issue that I can see is in the future, something that requires ACC not being added to the list. Currently there is no danger of that being overlooked. 

It’s just a question of which takes priority. Knowing that acc will not potentially be ignored in the future when needed. Or the rare pilot that flies from a boat has less setup required. Personally l, I would rather the former take priority.

**Pull request merged**
