### PR TITLE
Fixed wing Nav altitude control fix

### LINKED ISSUE #5734: [2.4-5.0RC2]Linear Descent RTH causes rapid climb at home point
## Current Behavior
With RTH set to AT LEAST LINEAR DESCENT and arriving altitude is much higher than Home Altitude, it causes a rapid climb for some time. 

## Steps to Reproduce
1. Activate RTH with AT LEAST LINEAR DESCENT active and RTH Altitude set to 100m and rth_home_altitude set to 30m
2. Fly at a high altitude but relative near the home point. For example 200 Altitude and 200m away
3. hit RTH
4. Wait till plane arrives
5. At a descent rate of max 5m/s it should arrive at about 170m
RESULT: Plane suddenly climbs when home point is reached

## Expected behavior
RTH should start the home loiter and continue the descent till it reaches rth_home_altitude

## Suggested solution(s)
Maybe a bug? Not tested if it is fixed in 2.5 RC-1

## Additional context
I have seen the exact same behavior on 2 planes yesterday. One flight showed a 300m climb before the descent started. Both on 2.4. Dart 250G with Matek F411WSE and AR Wing with Matek F405SE. I can share a log of both flights (Blackbox for AR Wing and OpenTX log for 250G) but need to share it private due to obvious reasons. Also FPV recording available if needed. 

Update: Might need a much higher altitude to test as mentioned above. As I said for obvious reasons I can't attach logs here. 

---
Dart 250G Dump: 
[INAV_2.4.0_cli_Serenity_20200515_192143.txt](https://github.com/iNavFlight/inav/files/4636002/INAV_2.4.0_cli_Serenity_20200515_192143.txt)

AR Wing Dump: 
[INAV_2.4.0_cli_Miranda_20200515_192422.txt](https://github.com/iNavFlight/inav/files/4636010/INAV_2.4.0_cli_Miranda_20200515_192422.txt)

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/5734#issuecomment-1328944982.

Resolves an old FIXME. Fix ensures target altitude doesn't start to track actual altitude if the actual altitude starts moving in the opposite direction to the desired target altitude by greater than the set 5 meter threshold. Avoids a potential altitude run away.

HITL tested OK but still needs flight testing.

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]

**Comment by bakwc** [comment]
Thanks for the fix! I was testing RTH on my wing and was very surprised when it started climbing instead of descending.

**Comment by b14ckyy** [comment]
I just found that this seems to cause a nasty side effect. At least I guess that this PR causes an issue as it is the only one changing althold behavior. 

in my test build in the HITL it seems to cause trouble changing altitude in 3D Cruise mode. If the current vertical speed is positive just minimal by a few cm/s, it is not possible to descent in Cruise mode, pushing pitch forward. 
Opposite happens if vertical speed is slightly negative, this prevents to climb by pulling back on pitch. 

so if the ALTHOLD PID controller is doing just tiny corrections, either climb or descent is blocked.

**Comment by b14ckyy** [comment]
For reference. I pulled the Master at commit [fd682f4](https://github.com/iNavFlight/inav/commit/fd682f4362a5f76a46a5cae09782b4d7d1effc3c) and then merged these PRs to my test build: https://github.com/b14ckyy/inav/pulls?q=is%3Apr+is%3Aclosed

**Comment by breadoven** [comment]
> I just found that this seems to cause a nasty side effect. At least I guess that this PR causes an issue as it is the only one changing althold behavior.
> 
> in my test build in the HITL it seems to cause trouble changing altitude in 3D Cruise mode. If the current vertical speed is positive just minimal by a few cm/s, it is not possible to descent in Cruise mode, pushing pitch forward. Opposite happens if vertical speed is slightly negative, this prevents to climb by pulling back on pitch.
> 
> so if the ALTHOLD PID controller is doing just tiny corrections, either climb or descent is blocked.

I checked this again using the HITL sim and I can't replicate this. Were you using full pitch stick movements ? What auto climb rate setting were you using (I was using 2m/s).

If the desired climb and actual climb directions oppose each other then the desired target Z position is held and set to actual Z position + an offset (= auto climb rate) so the target Z position is in the desired direction of movement. The altitude controller should correct the error between desired and actual and move the altitude in the desired direction in this case. E.g. if you're at 100m and climbing and you demand a descent the target desired Z would be set and held at 95m if the auto climb setting was 5m/s. Target desired Z will be held until the actual Z position starts reducing, i.e. desired and actual Z start moving in the same direction. Maybe this is caused by setting differences, maybe PIDS, although it's hard to see why that should affect things. Ultimately, if there is an error between desired Z and actual Z position the altitude controller should correct this error if it's working correctly. You should be able check what's happening by looking at actual Z and desired Z position in the logs.

**Pull request merged**
