### PR TITLE
Add MatekF405TE target

### PR DESCRIPTION
**Pull request by MATEKSYS**
MCU: STM32F405RGT6
IMU: ICM42605
Baro: SPL06 / DPS310
Blackbox: flash 16M / SD card
12x PWM outputs
6x UARTs
2x PINIO
4x ADC

### CODE REVIEW

**Comment by Jetrell** [comment]
@DzikuVx Any chance of having this merged soon and added to 4.1? Due to the board now being available. 
Thanks

**Comment by FNNCFPV** [comment]
My FC isnt communicating with the esc, I can't get motors to spin at all. I'm using Inav 4.1.0, my ESC is using BLHeliS an iflight 35am 4in1 esc. I know this flight controller has issues with INav as stated in the important tips tab on Matek website it states "INAV - Known issues: INAV firmware, S3, S5,S7 DSHOT not working because of unknown DMA bug, pls use ONESHOT or MULTISHOT for now." I have tried using all esc protocols to 0 success. I flashed betaflight just to make sure that I'm not making any user errors on my end and sure enough dShot600 worked just fine. I'm not sure if I need to use an older version of the configurator. I spoke with an iNav developer and they referred me to get in touch with you guys the manufacturer. There are a couple of people on the github having this issue but there isn't an answer on how to fix it.

When I plug in the battery I only hear do do do... I don't hear the final two fc beeps, blheli isn't finding it when I plug in USB also. I went ahead and tried the calibration you mentioned and watched a couple videos on how to calibrate it also just in case I wasn't missing anything and sure enough when I lowered master slider to lowest point; no esc beeps.

**Comment by mulfo44** [comment]
Same issue here.

**Comment by FNNCFPV** [comment]
> Same issue here.

I found a solution. I flashed betaflight to the fc to establish communication with esc using dshot600, I then flashed my esc using BLHeliS to an older firmware that had multishot next to the name. I then flashed iNav back into my fc from then my esc was communicating using multishot. You'll just need to calibrate your motors. Hope it helps let me know if you have any questions.

**Comment by MrD-RC** [comment]
That’s not really a solution. It’s a work-around. The solution would be for the target to work without issues.

**Comment by MATEKSYS** [comment]
> That’s not really a solution. It’s a work-around. The solution would be for the target to work without issues.

The target works fine,  Probabbly his ESC with previous firmware don't support oneshot/multishot protocol, only Dshot protocol available.

I assume there is bug in INAV to support normal DMA on timer "N".   BF supports it,  so S3 on TIM1_CH3N (DMA2,6,6) works fine with Dshot with BF firmware.

**Comment by MATEKSYS** [comment]
Move to new PR https://github.com/iNavFlight/inav/pull/7924

**Comment by marcusmcelroy** [comment]
Just installed this FC (coming from BF like I suspect many will be). Not having DSHOT on S3 is rather annoying. I agree with @MrD-RC that @MATEKSYS recommendation to revert to oneshot/ multishot is not a good solution for users of this flight controller.

On this..

> I assume there is bug in INAV to support normal DMA on timer "N". BF supports it, so S3 on TIM1_CH3N (DMA2,6,6) works fine with Dshot with BF firmware.

I'm no expect, but I've tried using both AF1 and AF3 (both use CH3N) on PB15, with the various combinations of DMA request maps, but I can't figure out how to get DSHOT working on S3, nor can I work out where the DMA conflict is.

So, has anyone been able to confirm a bug in the DMA code, or can anyone suggest a reason for this issue?

**Comment by MrD-RC** [comment]
This has been sorted. The target is in iNav 5.0 when that is released.

**Comment by marcusmcelroy** [comment]
Thanks @MrD-RC. I know that the MatekF405TE target has been merged into release_5.0.0, but DSHOT on S3 doesn't work. I'm running 5.0.0-RC1.

**Pull request closed without merging**
