### PR TITLE
Remove caching of dT value from pt1FilterApply4

### LINKED ISSUE #611: PH yaw highly unstable in 1.2.1
I really didn't intend to discover another mag issue. I tested 737c7d0 for horizon mode, in so doing I found that PH no longer works. The heading changes by c. 60° in 2 minutes (https://vimeo.com/183033739) with significant toilet-bowling.

In comparison, 1.2.0 is utterly stable (https://vimeo.com/183033738) is almost the same location and orientation.

Alas, the internal flash was full (mea culpa, so I can have the fun of repeating this experiment and getting bb logs).

Note this is the one of my 3 iNav machines that is not affected by #586.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #611

### CODE REVIEW

**Comment by stronnag** [comment]
deleted ... wrong issue

**Comment by DzikuVx** [comment]
@digitalentity is it possible that this caching of dT was also affecting D-term filtering in PID rate controller?

**Comment by digitalentity** [comment]
Yes, I believe it's likely.
Probably the dT for the first very first PID loop is very big since it's
probably measured since zero (power-up) and accounts for all boot up
sequence.

**Comment by DzikuVx** [comment]
That would somehow explain very big D-Term oscillations I've observed on yesterday logs. Maybe  like they are not really 30Hz oscillations but an effect of aliasing (low recording speed)

**Pull request merged**
