### PR TITLE
Get setting default values from settings.yaml

### PR DESCRIPTION
**Pull request by shellixyz**
I checked the default are the same as before, nothing has changed

### CODE REVIEW

**Comment by stronnag** [comment]
Arch Linux :-(

$ arm-none-eabi-gcc -dumpversion
10.2.0
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

```
/home/jrh/Projects/fc/inav/src/utils/settings.rb:893:in `block in validate_default_values': Member pinio_box1 default value has an invalid type, integer or symbol expected (RuntimeError)
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:665:in `yield'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:665:in `block (3 levels) in foreach_enabled_member'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:663:in `each'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:663:in `block (2 levels) in foreach_enabled_member'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:661:in `each'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:661:in `block in foreach_enabled_member'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:671:in `each'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:671:in `each'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:671:in `foreach_enabled_member'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:873:in `validate_default_values'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:306:in `write_files'
	from /home/jrh/Projects/fc/inav/src/utils/settings.rb:1099:in `<main>'
```

**Comment by stronnag** [comment]
Above error seems target dependent, in this case MATEKF765

**Comment by stronnag** [comment]
Interesting that we now get linker warnings on some (non -Os?) platforms:
```
[jrh@eeyore]$ ninja MATEKF405
[362/363] Linking C executable bin/MATEKF405.elf
In function 'sbufWriteData',
    inlined from 'mspFcProcessOutCommand' at ../src/main/fc/fc_msp.c:397:9:
../src/main/common/streambuf.c:71:5: warning: 'memcpy' reading 8 bytes from a region of size 1 [-Wstringop-overflow=]
   71 |     memcpy(dst->ptr, data, len);
      |     ^
Memory region         Used Size  Region Size  %age Used
           FLASH:      498068 B       896 KB     54.29%
    FLASH_CONFIG:          0 GB       128 KB      0.00%
             RAM:       88556 B       128 KB     67.56%
             CCM:       16116 B        64 KB     24.59%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
       MEMORY_B1:          0 GB         0 GB
[363/363] cd /home/jrh/Projects/fc/inav/ninja/sr.../Projects/fc/inav/ninja/inav_2.7.0_MATEKF405.hex
[jrh@eeyore]$ ninja MATEKF722
[362/363] Linking C executable bin/MATEKF722.elf
Memory region         Used Size  Region Size  %age Used
        ITCM_RAM:        6112 B        16 KB     37.30%
      ITCM_FLASH:          0 GB        16 KB      0.00%
ITCM_FLASH_CONFIG:          0 GB        16 KB      0.00%
     ITCM_FLASH1:          0 GB       480 KB      0.00%
           FLASH:         836 B        16 KB      5.10%
    FLASH_CONFIG:          0 GB        16 KB      0.00%
          FLASH1:      402580 B       480 KB     81.91%
             TCM:       16120 B        64 KB     24.60%
             RAM:       79400 B       192 KB   
```

**Comment by stronnag** [comment]
More  interesting, shortGitRevsion not passed to the FC
```
$ cliterm 
open /dev/ttyACM0

Entering CLI Mode, type 'exit' to return, or 'help'

# version
# INAV/WINGFC 2.7.0 Feb 14 2021 / 19:18:55 ()
# GCC-10.2.0

```

**Comment by stronnag** [comment]
And if I build the same target with `-DCMAKE_BUILD_TYPE=MinSizeRel`, then the board appears to lock up when attempting to connect to the CLI.

Seems like we still have some issues here.

**Comment by shellixyz** [comment]
> Interesting that we now get linker warnings on some (non -Os?) platforms:
> 
> ```
> [jrh@eeyore]$ ninja MATEKF405
> [362/363] Linking C executable bin/MATEKF405.elf
> In function 'sbufWriteData',
>     inlined from 'mspFcProcessOutCommand' at ../src/main/fc/fc_msp.c:397:9:
> ../src/main/common/streambuf.c:71:5: warning: 'memcpy' reading 8 bytes from a region of size 1 [-Wstringop-overflow=]
>    71 |     memcpy(dst->ptr, data, len);
>       |     ^
> Memory region         Used Size  Region Size  %age Used
>            FLASH:      498068 B       896 KB     54.29%
>     FLASH_CONFIG:          0 GB       128 KB      0.00%
>              RAM:       88556 B       128 KB     67.56%
>              CCM:       16116 B        64 KB     24.59%
>      BACKUP_SRAM:          0 GB         4 KB      0.00%
>        MEMORY_B1:          0 GB         0 GB
> [363/363] cd /home/jrh/Projects/fc/inav/ninja/sr.../Projects/fc/inav/ninja/inav_2.7.0_MATEKF405.hex
> [jrh@eeyore]$ ninja MATEKF722
> [362/363] Linking C executable bin/MATEKF722.elf
> Memory region         Used Size  Region Size  %age Used
>         ITCM_RAM:        6112 B        16 KB     37.30%
>       ITCM_FLASH:          0 GB        16 KB      0.00%
> ITCM_FLASH_CONFIG:          0 GB        16 KB      0.00%
>      ITCM_FLASH1:          0 GB       480 KB      0.00%
>            FLASH:         836 B        16 KB      5.10%
>     FLASH_CONFIG:          0 GB        16 KB      0.00%
>           FLASH1:      402580 B       480 KB     81.91%
>              TCM:       16120 B        64 KB     24.60%
>              RAM:       79400 B       192 KB   
> ```

Strange, I don't see this warning

**Comment by stronnag** [comment]
Also seeing strange `SETTINGFAIL` errors, even after full erase flash and `defaults`.
```
Arming disabled flags: COMPASS ACC HWFAIL RX CLI SETTINGFAIL
### ERROR: Invalid setting: sim_transmit_flags
```
```
# get sim_transmit_flags
sim_transmit_flags = 2
Allowed range: 0 - 0
```

**Comment by stronnag** [comment]
> Strange, I don't see this warning
> 
> EDIT: This seems to be related to your `shortGitRevsion` issue

Indeed, with gcc 9.3 I don't get any build warnings relating to `shortGitRevsion`, however `shortGitRevsion`  is still blank at runtime.
```
# version
# INAV/WINGFC 2.7.0 Feb 14 2021 / 20:29:43 ()
# GCC-9.3.1 20200408 (release)
```

**Comment by stronnag** [comment]
Some more research / comments; not sure how relevant.

* GCC reserves all identifiers starting with _ etc, "*In addition to the names documented in this manual, reserved names include all external identifiers (global functions and variables) that begin with an underscore (‘_’) and all identifiers regardless of use that begin with either two underscores or an underscore followed by a capital letter are reserved names. This is so that the library and header files can define functions, variables, and macros for internal purposes without risk of conflict with names in user programs.*"
* We suppress conversion warnings in many places.
* A simple test without warning supression:

```
$ arm-none-eabi-gcc -Wall -c -D __REVISION__="1234" revtest.c 
revtest.c: In function 'main':
<command-line>: warning: initialization of 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
revtest.c:5:18: note: in expansion of macro '__REVISION__'
    5 |      char *rev = __REVISION__;
$ cat revtest.c
#include <stdio.h>

int main()
{
     char *rev = __REVISION__;
     printf("rev = %s\n", rev);
     return 0;
}
```

**Comment by stronnag** [comment]
(erroneous comment deleted)

**Comment by stronnag** [comment]
@shellixyz finally got to the bottom of the `shortGitRevsion` problem. Some change to the build generator is causing the provision of the git revision to fail:
```
# This PR
-D__REVISION__=""
```
```
# Master
-D__REVISION__="15321e9c"
```

**Comment by stronnag** [comment]
> @shellixyz finally got to the bottom of the `shortGitRevsion` problem. Some change to the build generator is causing the provision of the git revision to fail:
> 
> ```
> # This PR
> -D__REVISION__=""
> ```
> 
> ```
> # Master
> -D__REVISION__="15321e9c"
> ```

This appear to be due to the reordering of CMakeList.txt, such that `include(main)` which sets `${GIT_REV}` is now done __before__ the call to `include(GetGitRevisionDescription)`.

**Comment by stronnag** [comment]
Looking good.

**Comment by giacomo892** [comment]
Great work! Thanks

**Pull request merged**
