### PR TITLE
OSD Nav Messages Update

### PR DESCRIPTION
**Pull request by breadoven**
System messages updated:

RTH climb phase added.
To WP message, WP number countdown added plus total number of WPs (To WP x / total WPs).
WP Hold, countdown timer added.

Don't know why settings.yaml is listed, it wasn't changed.

### CODE REVIEW

**Comment by stronnag** [comment]
`settings.yaml` is listed because unwanted white space was appended to line 2114.  Please revert.

**Comment by breadoven** [comment]
Ah sorry about that Stronnag, still trying to understand the workings of Github.  Think that whitespace got left over from something else when I was trying to clean up my master.

**Comment by DzikuVx** [comment]
@digitalentity could you please take a look?

**Review by digitalentity — APPROVED** [review]
Looks good to me!

**Comment by digitalentity** [comment]
If nobody has objections, I'd like to merge this to 2.6

**Pull request merged**
