### PR TITLE
As requested in #3223 S5 is no longer used for FW servos

### PR DESCRIPTION
**Pull request by DzikuVx**
#3223

I do not have a target so could anyone test it please? @MATEKSYS

### CODE REVIEW

**Comment by MATEKSYS** [comment]
It is OK. Thank you.

This is target.c in 1.9.0. works fine according to our arrangement.

**Comment by MATEKSYS** [comment]
Probably S5 definition was changed since this PR https://github.com/iNavFlight/inav/pull/2954

**Comment by Riffer** [comment]
I want to use a Matek 405 mini in a fixed wing. Afaik instead of S5 I use S6 now?
What's left for S5 now? Can it be used for led or as soft serial for VTX?

**Comment by MATEKSYS** [comment]
@Riffer S5 is for 2812LED by default with INAV firmware
http://www.mateksys.com/?p=4466

**Comment by MATEKSYS** [comment]
TIM_USE_LED was changed back to PB6 in development branch.  
https://github.com/iNavFlight/inav/blob/development/src/main/target/MATEKF405/target.c#L44

It is right in master branch. 
https://github.com/iNavFlight/inav/blob/master/src/main/target/MATEKF405/target.c#L36

**Comment by DzikuVx** [comment]
@MATEKSYS please take a look at #3910

**Comment by digitalentity** [comment]
That was probably accidental during massive timer refactoring. My bad. @DzikuVx thanks for fixing.

**Pull request merged**
