### PR TITLE
Option to display altitude in OSD with decimal digit

### PR DESCRIPTION
**Pull request by rmaia3d**
- Adds the option to display the altitude, in the OSD fields, with a decimal digit if within the defined "window". The window can be defined via the CLI, both the negative and positive thresholds, outside of which the display reverts to no decimal digit.

- By default, the thresholds would be -10meters (1000 centimeters in actual CLI values) and +20 meters (2000 centimeters in CLI). Negative threshold is entered as positive value in CLI, the code then converts this value to negative only when needed.

- CLI variables added: 
  - osd_alt_decimal_neg_threshold
  - osd_alt_decimal_pos_threshold

- If both thresholds are set to 0, the option is disabled. That is, no decimal digit is displayed on the altitude fields.

### CODE REVIEW

**Comment by fiam** [comment]
I think this would be easier to implement with a couple of settings that defined the number of digits and decimals in the altitude indicator. If you display 4 digits, you could show 2 decimals up to 99.99 and -9.99.

**Comment by rmaia3d** [comment]
Yes, you got a point there! It indeed would be easier and make more sense. I will look into it!

**Comment by teckel12** [comment]
@rmaia3d Shouldn't we also do this for imperial and not just metric?

**Comment by rmaia3d** [comment]
> @rmaia3d Shouldn't we also do this for imperial and not just metric?

True! That would make a lot of sense. In fact, I did some "housecleaning" on my own account repo and didn't realize they were also updated here. Disregard these last commits, as they are not final yet.

Once I make the final changes and commit them, I'll post here letting you know. :-)

**Comment by rmaia3d** [comment]
I've just pushed the commit with the latest changes, according to all your suggestions. 

Did away with the threshold thing, replacing by settings for both the number of decimal digits and the total number of digits. Also works for imperial units.

**Comment by rmaia3d** [comment]
Just a reminder that the latest changes have already been added, as the commit 130b3af.

**Pull request closed without merging**
