### PR TITLE
Fixed wing soaring mode

### PR DESCRIPTION
**Pull request by breadoven**
Provides a "Soaring" mode for fixed wing. Intended to be used with power off so aimed at sailplanes/motor gliders.

Mode is active when Position Hold or Heading Hold modes are enabled. Disables altitude control and allows Angle mode to "free float" in pitch within a deadband set using option `nav_fw_soaring_pitch_deadband`, The deadband operates above and below the level datum. The motor can be switched off using option `nav_fw_soaring_motor_stop `when mode is active.

PR also fixes redundant logic in fc_msp_box.c related to `feature(FEATURE_GPS)`.

Works as intended when tested in flight on a conventional T tail. Not yet flight tested on a flying wing.

### CODE REVIEW

**Comment by DzikuVx** [comment]
Wo ho ho... now this is AWESOME!

**Comment by Mateyhv** [comment]
Interesting idea. Shouldn't it be separate mode from Pos hold and Course hold? Can be that I am not undestanding it properly, the way I see it is as an Angle mode with a dead band around center pitch where the pitch axis is not corrected by the Angle mode. In this way it can be a separate mode that can be overimposed to Pos and Course holds like it was done with Alt hold.

**Comment by breadoven** [comment]
It's an accessory mode that provides automated direction control in a straight line (Course hold or Cruise) or circling (Poshold) whilst overriding the altitude control and Angle limitations which normally prevent these modes from allowing a plane to soar freely. Ideally with Poshold it should drift with the lift so it can follow thermals but that's a whole different thing in itself.

There is a function in Inav already that cancels Nav mode altitude control when the motor is stopped by setting the throttle low but that won't work if `nav_overrides_motor_stop `is set to `ALL_NAV`, the setting you'd most likely prefer when not soaring.

**Comment by MrD-RC** [comment]
@breadoven just noticed that this isn't in configurator. I just thought to look, to add the soaring mode to the mode ordering. Is it intended to be a mode modifier like althold and airmode? If so, would you like me to add it seeing as I've already started the code for the ordering?

**Pull request merged**
