### PR TITLE
Prevent unexpected takeoff in RTH LANDED state.

### LINKED ISSUE #4382: Quad took off after RTH landing.
What happened:
- RTH completed and the quad safely landed (OSD was displaying LANDING and then LANDED)
- just after that the motors slowly started to increase power
- eventually the machine took off!

See very last part of this video: https://www.dropbox.com/s/t3l10ct934hfjzn/PICT0018.AVI?dl=0
And the corresponding log: https://www.dropbox.com/s/r3dg3kyz6czdq6m/LOG00012.TXT?dl=0
Diff: https://www.dropbox.com/s/i99es7vh5zgut9z/diff.txt?dl=0

I think it is nothing new. I remember I was observing increasing motor power previously but it's first time when it actually made the machine take off!

Looking at the log is seems the RTH is commanding min throttle (1050). Some stabilization code must still operate and increase the motor rates. As a safely manner I think it should be blocked after entering the LANDED stage, which was detected correctly.

### PR DESCRIPTION
**Pull request by krzysztofmatula**
This should fix #4382.
Not tested yet.

### CODE REVIEW

**Review by digitalentity — DISMISSED** [review]
LGTM. Not pretty but will do the job

**Comment by krzysztofmatula** [comment]
@digitalentity, tested this today and it seems it does not help... Will look at the logs later.
I think we should also disable the pos and alt controller when landed. Can it be done with the navigation state machine flags?

**Comment by digitalentity** [comment]
The thing is that navigation state machine is executed at very low frequency and PID still has time to wind up. We will need to enable ANTI_WINDUP state when landed

**Comment by krzysztofmatula** [comment]
Not sure if the navigation handling frequency matters here. The motor rate increase rather slowly (very slowly) when landed. But, when attempted to turn the machine by hand the reaction was immediate and violent. I think as the LANDED state is final the POS and YAW controllers could just be disabled. The ALT controller could stay I think.

Btw, do fixed wings ever reach NAV_STATE_RTH_FINISHING and NAV_STATE_RTH_FINISHED or this is MR specific?

**Comment by krzysztofmatula** [comment]
Verified and it works well for me now :)

**Pull request merged**
