### PR TITLE
Enable airplane setups for Sparky board

### PR DESCRIPTION
**Pull request by digitalentity**
Intended to fix https://github.com/iNavFlight/inav/issues/1426
@denrom can you please test this?

### CODE REVIEW

**Comment by denrom** [comment]
Sorry for the moment I can not test

**Comment by digitalentity** [comment]
No worries, take your time.

**Comment by digitalentity** [comment]
@denrom I'm merging this. Feel free to open a bug if it doesn't work.

**Comment by denrom** [comment]
Thanks! Changes work with Flying wing, Airplane and Custom airplane configurations.

**Comment by digitalentity** [comment]
Thanks for testing!

**Pull request merged**
