### PR TITLE
Release INAV 1.8

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by teckel12** [comment]
@digitalentity #2354 and #2356 could be added to v1.8 too. Both are minor and without merge conflict.

**Comment by digitalentity** [comment]
@teckel12 both PRs merged, thanks

**Review by teckel12 — APPROVED** [review]
Non-overlapping positions, nice.

**Review by teckel12 — APPROVED** [review]
Nice! Would have been a support nightmare otherwise. I'll probably tweak the target docs too.

**Comment by digitalentity** [comment]
@teckel12 thanks! I keep forgetting about the docs :laughing:

**Review by teckel12 — APPROVED** [review]
:thumbs-up:

**Review by teckel12 — APPROVED** [review]

**Comment by digitalentity** [comment]
Merging, building and publishing soon.

**Pull request merged**
