### PR TITLE
Add GEPRCF405 and GEPRCF722 targets

### PR DESCRIPTION
**Pull request by YI-BOYANG**
These two targets are used for GEP-F405-HD(v2) and GEP-F722-HD(v2) flight control of GEPRC.

### CODE REVIEW

**Comment by YI-BOYANG** [comment]
image
There is a problem in the GEPRCF722 target: there is a function designed on the FC that can control the vsw pad output 9v voltage through the pinio. It can be controlled normally in Betaflight, but it is not effective in INAV. I am not sure what causes this.

**Comment by breadoven** [comment]
@DzikuVx what was the problem with this Pawel ? Completely buggered up my Github Desktop App after merging from upstream master. Flagged these files as changed, whitespace only, but you couldn't discard the changes, stash them or anything else on one branch. Another branch miraculously fixed itself and seems to be OK now after merging from master again which pulled in your fix. Did these files have some odd line ending such as just a CR (Mac format ?) ?

**Comment by stronnag** [comment]
It would seem like these came from a mis-configured repo. I found the easiest way to fix was:

```
#!/bin/sh

# Set correct value for your OS; for FreeBSD, Linux and MacOS it's "input"
# See https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
AUTOCRLF=input
OS=$(uname -s)
case $OS in
  *CYGWIN_NT*)
    AUTOCRLF=true
    ;;
esac
git config --global core.autocrlf $AUTOCRLF
git rm --cached -r .
# Repeat `git reset --hard` as many tines as necessary; eventually git will get the message
git reset --hard
git reset --hard
git reset --hard
git reset --hard
git status
```

As I needed to fix it on at least 6 machines, it was worth scripting it.

**Comment by breadoven** [comment]
Strange problem. On one branch I managed to discard the change on a single file after a few attempts, which stayed discarded. The other changes disappeared after trying various things, stashing, deleting stash, rebooting PC ... no idea what fixed the problem in the end, all very random. On another branch nothing worked, but since I don't use it for anything I just committed the changes and they disappeared and have stayed that way.

**Pull request merged**
