### PR TITLE
updating with current display behavior

### PR DESCRIPTION
**Pull request by tednv**
https://github.com/iNavFlight/inav/pull/127

### CODE REVIEW

**Review by digitalentity — APPROVED** [review]

**Comment by digitalentity** [comment]
@tednv Is this ready to be merged?

**Comment by tednv** [comment]
yeah g2g

**Comment by tednv** [comment]
g2g, will update transmitter shortcuts cheat sheet too

**Comment by digitalentity** [comment]
Why did you close it?

**Comment by tednv** [comment]
my bad, had problem with git desktop

**Comment by tednv** [comment]
Leave a comment

**Comment by digitalentity** [comment]
Damn, merged to master :(

**Comment by tednv** [comment]
no its good, thanks for merging

**Pull request merged**
