### PR TITLE
gyro reentrant2 - allow gyro SPI CS pin to be set at runtime

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by martinbudden** [comment]
@digitalentity , can you have a look at this?

Once this is in I think dual-gyro support should be reasonably straightforward and should be able to be done with just changes to `sensors/gyro.c` and `target.h`.

**Comment by digitalentity** [comment]
Let's put this on hold until it's better tested. I don't think we'll change any accgyro driver code in 1.6 so this should be safe to postpone.

**Comment by martinbudden** [comment]
I'm happy to leave this on hold until 1.7. However, when you have a chance can you review it? I'd like to get your comments.

**Comment by digitalentity** [comment]
Will do in a few days.

**Comment by martinbudden** [comment]
Withdrawn, to be replaced by a new PR which follows betaflight PR https://github.com/betaflight/betaflight/pull/2586

**Pull request closed without merging**
