### PR TITLE
Split box code out of MSP

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Review by digitalentity — APPROVED** [review]

**Comment by fiam** [comment]
All functions moved to `fc_msp_box.c` had a single caller in `fc_msp.c` so they were inlined. Now that they're in a separate `.c` file the compiler is not able to inline them anymore, increasing both flash usage and making the calls a bit slower.

This makes me think that there was a reason to move this code around, probably to expose it to other callers. In that case, I think a PR which also included the new callers and/or mentioning its future usage in the commit description would be a good thing.

Otherwise this looks like a change for the bad without any reason.

**Comment by digitalentity** [comment]
@fiam LTO support in ld is smart enough to inline functions that have only one reference. Having box-related code in a separate file is cleaner. Keeping code well structured and in relatively small files is always a good idea - easier to maintain

**Comment by oleost** [comment]
https://github.com/iNavFlight/inav/wiki/Flight-modes Need  updating in regards to the "Camera Control" flight modes.

**Comment by digitalentity** [comment]
@oleost those are really camera-specific. We probably need a wiki page about configuring those mode for at least RunCam Split/Split2 cameras

**Pull request merged**
