### PR TITLE
Version 1.5

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by stronnag** [comment]
FYI. Flight tested ed7f767 on SPRF3 and EVO.
No issues / regression on SPRF3
On Evo, rather strange behaviour (loss of sense of level, inability to autoland etc) that looked like memory corruption (see 36fb05f).

**Comment by digitalentity** [comment]
@stronnag interesting. ed7f767 doesn't have new i2c code yet. Quite possibly a different bug.

**Comment by digitalentity** [comment]
@stronnag bug fixed. Fortunately not a memory corruption issue but rather a accelerometer scaling issue which caused accelerometer readings to be ignored when calculating orientation in space and consequenctly in level drift and poor overall performance.

**Comment by stronnag** [comment]
cc121438 flight tested (PH, RTH, WP and manual) on SP-EVO. Superb. All last week's regressions have been fixed.

**Comment by digitalentity** [comment]
@stronnag great! With Configurator support for OSD almost ready we can probably release RC1 very soon.

**Comment by stronnag** [comment]
da610895c flight tested on  SPRF3EVO / Tri (+localy merged #946). Flawless PH, RTH, WP and manual flight; wholly configured from #946 'diff all'.

**Comment by digitalentity** [comment]
RC2 is building

**Comment by digitalentity** [comment]
Looks like we're ready for release. 
I'll wait for a few more days just in case any more minor bugs are found and release 1.5

**Comment by stronnag** [comment]
So no cli-diff :(

**Comment by digitalentity** [comment]
@stronnag I was under the impression that it's not ready yet, otherwise I would have probably merged it into 1.5-RC2. Now it's probably too late to merge it in, but we'll probably merge it first thing after 1.5

**Comment by stronnag** [comment]
OK.  I've been using it merged into development for a week or so now without any problems. Early in the post 1.5 cycle would be good, before it needs another rebase.

**Comment by martinbudden** [comment]
Yes, it would be good to merge this in as the first PR after 1.5 is released.

**Comment by oleost** [comment]
Why not release RC3 now?

And if nothing else is found release final version without any changes?

**Comment by digitalentity** [comment]
I don't want to have too much RC's. The only fixes since RC2 are failsafe (bug manifests only in a very specific scenario) and hardware failure beeping until GPS is configured.

**Comment by martinbudden** [comment]
I don't think we should worry too much about the number of RCs. I believe Linux regularly has 6 or 7, and betaflight 3.0 had 14.

**Comment by digitalentity** [comment]
True. Making the RC3 now :smile:

**Comment by stronnag** [comment]
fc04a075 flight tested (SPEvo, tricopter). Mix of free flight, WP, PH, RTH. No issues.

**Pull request merged**
