### PR TITLE
Fix UART inverter on MAMBAF405 target

### PR DESCRIPTION
**Pull request by digitalentity**
Fix for #4927

### CODE REVIEW

**Comment by digitalentity** [comment]
Firmware for testing
[inav_2.2.2_MAMBAF405.zip](https://github.com/iNavFlight/inav/files/3389662/inav_2.2.2_MAMBAF405.zip)

**Review by DzikuVx — APPROVED** [review]

**Comment by datamann** [comment]
Tested the firmware linked above and SBUS works but softserial/smartport on PPM pad does not work. Pleas note that I have just tried to build from development på SBUS did not work.

**Comment by datamann** [comment]
Correction!
Softserial/Smartport on ppm pad does work.

**Comment by datamann** [comment]
Is this target a clone from betaflight? When I tried the FuryF4OSD from BF the quad skyrocketed when I armed the quad, the same thing happend with this build. Do not have props on on the bench when you arm!

**Comment by datamann** [comment]
Just disregard my last comment! Have no idea why that happend...
I have been flying with this firmware today and it works great :-)

**Comment by s2kaka** [comment]
I cannot calibration my compass in this firmware too.
Here is my diff all:

`

# version
# INAV/MAMBAF405 2.2.2 Jul 14 2019 / 11:08:38 (26d166eca)
# GCC-8.2.1 20181213 (release) [gcc-8-branch revision 267074]

# reset configuration to default settings
defaults noreboot

# resources

# mixer
mmix 0  1.000 -1.000  1.000 -1.000
mmix 1  1.000 -1.000 -1.000  1.000
mmix 2  1.000  1.000  1.000  1.000
mmix 3  1.000  1.000 -1.000 -1.000

# servo mix

# servo

# logic

# feature
feature GPS
feature RSSI_ADC
feature PWM_OUTPUT_ENABLE

# beeper

# map

# serial
serial 2 2048 115200 115200 0 115200
serial 5 2 115200 57600 0 115200

# led

# color

# mode_color

# aux
aux 0 0 0 1700 2100
aux 1 1 3 900 1300
aux 2 2 3 1300 1700
aux 3 9 1 1700 2100
aux 4 8 2 1700 2100
aux 5 11 5 1700 2100

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout
osd_layout 0 0 1 1 V
osd_layout 0 1 24 5 H
osd_layout 0 2 0 0 V
osd_layout 0 4 8 6 H
osd_layout 0 7 13 11 V
osd_layout 0 9 0 10 V
osd_layout 0 11 1 12 V
osd_layout 0 12 0 11 V
osd_layout 0 13 0 2 V
osd_layout 0 14 4 1 V
osd_layout 0 15 14 2 V
osd_layout 0 20 16 11 H
osd_layout 0 21 19 12 H
osd_layout 0 22 13 1 V
osd_layout 0 23 14 1 V
osd_layout 0 28 23 12 V
osd_layout 0 30 2 10 V
osd_layout 0 32 24 1 V
osd_layout 0 35 5 11 V
osd_layout 0 38 14 1 H
osd_layout 0 40 23 11 V
osd_layout 0 54 24 1 H
osd_layout 0 85 23 5 H
osd_layout 0 96 8 1 V
osd_layout 0 97 8 12 V

# master
set looptime = 250
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 90
set gyro_stage2_lowpass_hz = 175
set acc_hardware = MPU6000
set acczero_x = 44
set acczero_y = -11
set acczero_z = 83
set accgain_x = 4058
set accgain_y = 4075
set accgain_z = 4068
set mag_hardware = HMC5883
set magzero_x = -53
set magzero_y = -109
set magzero_z = 29
set baro_hardware = NONE
set pitot_hardware = NONE
set rx_min_usec = 1015
set motor_pwm_rate = 4000
set motor_pwm_protocol = MULTISHOT
set failsafe_procedure = RTH
set model_preview_type = 3
set gps_sbas_mode = AUTO
set nav_extra_arming_safety = OFF
set osd_video_system = NTSC
set osd_rssi_alarm = 40
set osd_time_alarm = 15
set osd_alt_alarm = 50
set vtx_low_power_disarm = ON

# profile
profile 1

set mc_p_pitch = 45
set mc_i_pitch = 35
set mc_d_pitch = 24
set mc_i_roll = 35
set mc_d_roll = 24
set dterm_lpf_hz = 75
set yaw_lpf_hz = 0
set rc_yaw_expo = 70
set roll_rate = 60
set pitch_rate = 60
set yaw_rate = 50

# profile
profile 2


# profile
profile 3


# battery_profile
battery_profile 1


# battery_profile
battery_profile 2


# battery_profile
battery_profile 3


# restore original profile selection
profile 1
battery_profile 1

# save configuration
save`

**Comment by naice** [comment]
Are the UARTS working for SmartAudio? I can't seem to get the UARTS working.

**Pull request merged**
