### PR TITLE
Autolaunch - Added a smooth end launch feature and code refactor

### PR DESCRIPTION
**Pull request by dragnea**
This refactor brings a **new feature** that facilitates a **smooth transition** of throttle and pitch angle, between the launch state and the subsequent flight mode. Instead of the sudden and brutal transition that usually happens...
Added the setting in the CLI commands:
- **nav_fw_launch_end_time**
	default = 2000 (ms)
	min = 0 - disabled
	max = 5000 (ms)

The behavior is identical with the previous version but now, the total launch time is nav_fw_launch_timeout + nav_fw_launch_end_time, just to ensure that the nav_fw_launch_end_time is not shorting the proposed launch time

With this new feature, I re-implemented the code, using a state machine, similar to navigation...

The code was tested during the development, directly on a wing, also tested at the field
Please follow the video and listed how the launch ends:
https://www.youtube.com/watch?v=Lh1rxddKeyU

Also, I've included and tested this feature in the same time with this one: https://github.com/iNavFlight/inav/pull/5951

Please, let me know if there are other things to bring or change here.
Thank you!
Mihai Dragnea

### CODE REVIEW

**Comment by avs2** [comment]
Does this apply when auto launch ends normally, or also when you interrupt to take manual control before that?

**Comment by dragnea** [comment]
> Does this apply when auto launch ends normally, or also when you interrupt to take manual control before that?

There are 3 cases when the smooth end it happens: isLaunchMaxAltitudeReached, areSticksMoved, launchTimeout

**Comment by dragnea** [comment]
Hello @digitalentity 
I've added the branch with https://github.com/iNavFlight/inav/pull/6285 implementation and added the smooth end transition in the CMS as "END TRANSITION TIME", so it's ready to merge. The new code is tested dozen of times on 2 of my wings over 4 months, also Mark Hoffman tested it on his wing (@b14ckyy if I'm not mistaken).
Thanks!

**Comment by digitalentity** [comment]
@dragnea thanks, merging!

**Pull request merged**
