### PR TITLE
Ignore tasks.json and use tabs in C files

### PR DESCRIPTION
**Pull request by MrD-RC**
Added ignore flags for
- .vscode\tasks.json
- .vscode\c_cpp_properties.json

Changed settings.json to use tabs, not spaces for C file types.

### CODE REVIEW

**Comment by mmosca** [comment]
I am on the camp of spaces as a good compromise, but the original pr with the rules was meant for discussion.

I am ok either way, and other editors can be setup to match.

Mixing tabs and spaces on the other hand is bad and leads to things being formatted wrong, specially when tabs are configured to be displayed as anything but 8 spaces.

**Comment by stronnag** [comment]
[Dev docs](https://github.com/iNavFlight/inav/blob/master/docs/development/Development.md) links to [this style guide]( https://github.com/multiwii/baseflight/wiki/CodingStyle) which mandates 4 spaces.

**Comment by MrD-RC** [comment]
Has that changed? I always thought it was the opposite.

**Comment by stronnag** [comment]
No it's always been 4 spaces, no hard tabs.  The style guide item was last updated 2017-07-04.

**Comment by mmosca** [comment]
I create the pr that set spaces as default because of #9173

**Comment by MrD-RC** [comment]
OK, I've corrected the PR to remove the tab part. Shame, I've always hated spaces for indents. Ah well, the other parts can be merged. The constant want to update the tasks.json file is a bit annoying.

**Comment by mmosca** [comment]
> OK, I've corrected the PR to remove the tab part. Shame, I've always hated spaces for indents. Ah well, the other parts can be merged. The constant want to update the tasks.json file is a bit annoying.

So did I, but that fight was lost a looong time ago. :(
These days spaces are the norm, specially now that python and yaml are so popular... 1 tab, counts as 1 space for the indentation in those...

**Review by mmosca — APPROVED** [review]

**Comment by MrD-RC** [comment]
One more thing to make me hate Python 🤣 Just use proper structure!!!

**Pull request merged**
