### PR TITLE
More detailed RX link status on OSD

### PR DESCRIPTION
**Pull request by expipiplus1**
This information is sent over the CRSF serial connection since firmware 2.93

CRSF is currently the only protocol for which this is implemented, but any other protocol should be able to write into the `rxLinkStatistics_t` struct `rxLinkStatistics` exported from `rx.h`.

Reopened from https://github.com/iNavFlight/inav/pull/4517

### CODE REVIEW

**Comment by expipiplus1** [comment]
Pairs nicely with https://github.com/iNavFlight/inav-configurator/pull/725

**Comment by pitts-mo** [comment]
Thanks @expipiplus1 :-)
Can Crossfire Micro TX power level indications be easily added to include 25,100,250 ?
-p

more info:
Forgive me if I misunderstand pre-existing code at lines 61&62 of  src/main/rx/crsf.c ...
// The power levels represented by uplinkTXPower above in mW
const uint16_t crsfPowerStates[] = {0, 10, 25, 100, 500, 1000, 2000};

If uplinkTXPower values of different TX type conflict I wonder if we can get TX type from crsf data or add a setting to select the valid power levels of the TX type.

-updated for minor wording corrections -p

**Comment by atomiclama** [comment]
Any reason why this went quiet? If I start it up again will there be any interest?

**Comment by expipiplus1** [comment]
@atomiclama Probably because I've not been flying for a while, I'd be happy to help if you want to add @pitts-mo's suggestions

FWIW this was working very well for all my test flights with it.

**Comment by atomiclama** [comment]
@expipiplus1 Hi Joe, I've merged your branch into my repo clone and have made some changes, just slimming it down a bit. Trying to get some interest over on FB for others to test as I don't have CRSF. I run a custom RX that uses the CRSF protocol. Once a few people are happy with it I'll try and get a PR sorted. Nice to know you are still active in the hobby. I just assumed as this PR went quiet you had lost interest / moved on so I started it up again.
Cheers

**Comment by expipiplus1** [comment]
Cool,

What RX are you using just out of interest?

Can't make any promises about when I could test this (especially outdoors
at the moment). Please give me a ping if I've not got to this in a few
weeks and you need another tester.

**Comment by atomiclama** [comment]
@expipiplus1 It's a custom RX based on 2x LoRa SX1262 chips for diversity and / or dual channel operation. Bit on hold at the mo as I build up a test quad platform that will return home when the link goes *%^"£ ;-)

**Comment by 007hacky007** [comment]
This pull request is really nice! I would say it's essential as this info is already available in the betaflight osd quite a while.

Any reason why this is closed and not merged? I have CRSF and I'm happy to test it if needed.

**Comment by atomiclama** [comment]
@007hacky007 I've merged these changes into my fork and done some builds for people to test out if they wish: -
https://github.com/atomiclama/inav/releases

Please give them a go and give feedback. Was some interest over on iNav FB group but gone quiet.
Not getting much flight time at the mo so not much testing going on but it is working well.

**Comment by 007hacky007** [comment]
@atomiclama just building new wing which I would like to set up on Inav 2.5.0. Are you willing to create build based on 2.5.0, please? 

Also is there any chance merging this into the master? For instance if I test it and say it works, can someone push it onto the master? I can't see any reason not to have this feature in Inav. Seems essential for me - there are lots of CRSF users surely and LQ is recommended indicator and power level is very useful for long range flights.

**Comment by atomiclama** [comment]
@007hacky007 Yes I can do a build for you based on V2.5.0 once I work out if this is now on master or development branch.
Which target do you need? It's a pain to build all targets.

I've been flying it for some time now and it's fine. I've had absolutely no feedback so not done anything with it at all. Limited time and all that. I need some feedback or response from people otherwise I loose interest and wander off on my own ;-)

**Comment by 007hacky007** [comment]
@atomiclama target `MATEKF411SE` please. 

Hopefully feedback from me will help to get this to the master for everyone :) 

I believe there are lot of people wanting this feature, but they are not used to contribute on github... As said before, everyone talks about LQ in the betaflight community and ironically iNav is much more used for long range where watching your RC link is much more needed and iNav at the same time does not have this yet officially.

**Comment by atomiclama** [comment]
@007hacky007 here you go: -
https://github.com/atomiclama/inav/releases/tag/ls2

Just twigged that the version has been bumped to 2.6 But it's basically 2.5 with a couple of commits. So pretty much the same.

Can you come over to the FB iNav group to discuss this?

**Comment by OptimusTi** [comment]
Hello guys, I played with your code and added a SNR Warning and 2RSS to make it work like the TBS Fpvision OSD. I have posted videos on various Inav FB but no interest or feedback! I can’t  believe how people don’t understand how to use Crossfire osd info.

**Comment by atomiclama** [comment]
@OptimusTi nice one, I'm currently not flying iNav and have no spare time so this has just stalled for me. Maybe sometime in the future I'll finish it off or feel free to do with as you wish.

**Comment by OptimusTi** [comment]
Thanks. I'll keep testing. Looking into keeping just the SNR alarm and the RSSI like you have it but using a couple of symbols to indicate the current antenna. I also made a "CRSF RX" sub menu but that still needs work. Cheers!

**Comment by raffxj** [comment]
hi. can anyone build me a hex for matek F722se ? would like to test the LQ and rssi dbm. thanks

**Comment by OptimusTi** [comment]
> @atomiclama , how do I flash this version 2.6? my configurator is the most recent. wish to try this on my longe range quad.
> 
> using matek F722 SE
> 
> thanks

did you get the hex file for the F722SE?

**Comment by raffxj** [comment]
@atomiclama yes ive downloaded it, along with a few other hex for different FCs.

**Comment by OptimusTi** [comment]
Good! 
I made some changes to this and added a couple of things, font. But it looks like there's no interest in the Inav community and the Devs hate TBS. 2.5.2 just dropped. I'll see if I can adapt my changes to the new version. If not, I'll wait until 2.6  Cheers!

    On Monday, August 3, 2020, 06:48:29 PM EDT, raffxj <notifications@github.com> wrote:  
 
 


@atomiclama yes ive downloaded it, along with a few other hex for different FCs.

**Comment by raffxj** [comment]
@atomiclama 

well I dont hate TBS.. but they create the best parts for our RC hobby use.  the only TBS product I have here is the unify pro 32 vtx. one hell of a vtx. and regarding inav w LQ and dBm osd support, I dont own crossfire. I have here expressLRS (using R9M module + R9 mini rx).

I fly iNav for my longe range quads >1km distance. would not want any other. imav 2.5 DOES support crsf protocol.. but YET the osd. 

R9 has a crappy rssi. I like the LQ and dBm better. gives me peace of mind while flying. 😄

**Pull request closed without merging**
