### PR TITLE
add TBS_LUCID_H7 

### PR DESCRIPTION
**Pull request by bkleiner**

### CODE REVIEW

**Comment by mmosca** [comment]
For tracking progress
# TBS_LUCID_H7
 * [ ] Flash firmware
 * [ ] Calibrate
 * [ ] Orientation matches
 * [ ] Gyro working
 * [ ] Accel working
 * [ ] Baro working
 * [ ] Mag working (i2c)
 * [ ] Voltage correct
 * [ ] Current correct
 * [ ] UART1
 * [ ] UART2
 * [ ] UART3
 * [ ] UART4
 * [ ] UART5
 * [ ] UART6
 * [ ] UART7
 * [ ] Camera working
 * [ ] Video Out working
 * [ ] OSD working
 * [ ] LEDs working
 * [ ] Buzzer working
 * [ ] Motor/Servo outputs
 * [ ] Blackbox

**Comment by mmosca** [comment]
@bkleiner Is uart 7 used for esc telemetry?

**Comment by bkleiner** [comment]
> @bkleiner Is uart 7 used for esc telemetry?

uart7 is a spare, exposed on the bottom.
uart8 is used for the esc telemetry. 

we have already updated the manual with all the assigments:
https://www.team-blacksheep.com/media/files/tbs-lucid-manual.pdf

**Comment by mmosca** [comment]
> > @bkleiner Is uart 7 used for esc telemetry?
> 
> uart7 is a spare, exposed on the bottom. uart8 is used for the esc telemetry.
> 
> we have already updated the manual with all the assigments: https://www.team-blacksheep.com/media/files/tbs-lucid-manual.pdf

Btw, there is an error in the manual. Camera 2 input is listed twice in the legends: 
image

**Comment by mmosca** [comment]
Everything looks to be ok so far.
I did run into some issues.

* FC does not connect to configurator if sd card is inserted.
* I don't have hardware to test the buzzer, but don't think this is a show a stopper.
* I am having issues with the analog camera switch, but I am not sure if the issue is my camera being dead or the camera switch. Will check my hardware later. OSD shows up correctly.

**Comment by bkleiner** [comment]
updated the default rx uart

**Comment by mmosca** [comment]
Looks like my analog vtx is dead. :(

So can't confirm if the behavior I saw on the analog cam switch is ok or not. But we can fix it later.

**Pull request merged**
