### PR TITLE
Add GPS bearing to S.Port/F.Port telemetry

### PR DESCRIPTION
**Pull request by teckel12**
S.Port & F.Port telemetry's `Hdg` sensor is actually the model's orientation.  This PR adds a new sensor `0450` which is the GPS heading.  The heading along with the model's orientation (yaw) can be used to calculate the flight path vector (FPV).

Instead of confusing existing scripts that are expecting the `Hdg` sensor to be yaw, the existing `Hdg` sensor was left as-is (albeit technically incorrect as it's not the heading, but the model's orientation).

Anyway, this just adds the GPS heading telemetry sensor so the flight path vector can be calculated on S.Port & F.Port telemetry (it's already possible on Crossfire via the `Yaw` and `Hdg` sensors)

### CODE REVIEW

**Review by DzikuVx — CHANGES_REQUESTED** [review]
@teckel12 could you rebase changes on `development` and squash changes? Thos PR looks quite messy with a lot of commits that bring no active changesets

**Comment by teckel12** [comment]
@DzikuVx I agree it's messy, caused by the development branch no longer being able to be compiled on Windows.

**Comment by teckel12** [comment]
@DzikuVx I believe I did the rebased/squash, but it still doesn't look right here.

**Comment by DzikuVx** [comment]
I will fix it if you do not mind

**Comment by DzikuVx** [comment]
@teckel12 please check #5011

**Comment by teckel12** [comment]
@DzikuVx That's fine, I was just going to open a new PR as that seemed like the least trouble. Thanks.

**Pull request closed without merging**
