### PR TITLE
PID: Use full stick in ANGLE/HORIZON

### PR DESCRIPTION
**Pull request by digitalentity**
Currently formula for targetAngle is this:
`targetAngle = 2 * rcCommand`
this is latter constrained to `max_inclination` therefore if your max_inclination is set to something smaller than 100 deg you won't be using full stick in ANGLE mode.

This PR changes the logic in such way that full stick deflection will result in `max_inclination`.

### CODE REVIEW

**Comment by DzikuVx** [comment]
Outstanding, I wanted to do this after my vacation

**Comment by digitalentity** [comment]
My primary motivation was to lower stick sensitivity for beginners. I gave my quad (max_inclination=45, expo=70) to a friend and he was unable to fly it because half stick deflection was already close to 45 deg.

**Comment by DaleKramer** [comment]
Does this not relate to my last post in #272 ?

**Comment by digitalentity** [comment]
@DaleKramer yes it's basically the same logic. I need to test the logic in HORIZON mode as well before I merge this.

**Comment by digitalentity** [comment]
I've tried flying HORIZON with new stick scaling and it's too aggressive. As an experiment I've ported Rattitude code from LibrePilot to see if it makes the behavior more pilot-friendly. Yet to be tested.

**Comment by DaleKramer** [comment]
If I fly at 80 degree angle mode and it is too aggressive with the 80 degree attained at full stick travel, could I not just add expo on my transmitter to calm it down?

**Comment by digitalentity** [comment]
@DaleKramer, in general you shouldn't have any expo or trim on your TX - everything should be done on FC's end. HORIZON is a different mode then ANGLE - it allows to transition to rate mode after certain point in stick travel.

**Comment by digitalentity** [comment]
All, I've tested this today and it behaves perfect in Horizon mode. Any objections against merging this?

**Comment by stronnag** [comment]
I was going to test this, but it does not build under gcc 6.1.1

```
./src/main/flight/pid.c: In function 'pidLevel':
./src/main/flight/pid.c:269:25: error: assignment of read-only variable 'angleRateTarget'
         angleRateTarget = pt1FilterApply4(&pidState->angleFilterState, angleRateTarget, pidProfile->I8[PIDLEVEL], dT);
                         ^
make: *** [Makefile:664: obj/main/NAZE/flight/pid.o] Error 1
```

I will remove the 'const' and see what happens.

**Comment by stronnag** [comment]
I flew it today in horizon, rolls, flips and navigation functions (WP, RTH, PH). No issues.

**Comment by digitalentity** [comment]
@martinbudden do you think its safe to merge features that are not HW-related?

**Comment by martinbudden** [comment]
@digitalentity , yes, I think so.

**Pull request merged**
