### PR TITLE
CLI diff command

### PR DESCRIPTION
**Pull request by digitalentity**
- [ ] Test everything
- [x] Make it fit to F1 targets

### CODE REVIEW

**Comment by digitalentity** [comment]
Wow! Not enough **RAM**! That's something new!

**Comment by digitalentity** [comment]
Ok, time for some unpleasant compromises:

- Support for ancient NAZE accelerometers/gyros dropped
- `TURN_ASSIST` and `HEADING_LOCK` flight modes not available on targets with 64K FLASH
- Added `CLI_MINIMAL_VERBOSITY` to targets with 128K flash and below

**Comment by oleost** [comment]
TBH it's old boards. And it's not like iNav 1.4 etc stops working when one release new versions either.

Guessing this is the way forward.

We just need to make it perfectly clear that we strongly recommend F3 based flightcontrollers. And that F1 are loosing more and more for  each version.

**Comment by digitalentity** [comment]
Yes, it's really time to let ancient boards go. I also intend to split NAZE target into NAZE and AIRHERO (which is loosely based on NAZE but with SPI gyro and without blackbox). It will help remove dead code.

**Comment by digitalentity** [comment]
However I want to fix https://github.com/iNavFlight/inav/issues/947 first

**Comment by stronnag** [comment]
Flight testing (setup via diff restore) on SPRF3

Bench tested on FLIP32.

One strangeness is that 'random' values are returned for profile !=0 mag_decl. This is possibly because it is only set of the current profile by default, however I don't recall seeing this 'random' value in a earlier full dumps; usually it's zero in unset profiles.

````
profile 0

set mag_declination = -100
set mag_hold_rate_limit = 60
set p_pitch = 80
set i_pitch = 18
set d_pitch = 48
set p_roll = 80
set i_roll = 18
set d_roll = 48
set p_yaw = 120
set i_yaw = 18
set i_level = 20
profile 1

set mag_declination = 20560
````

**Comment by stronnag** [comment]
Another issue. smixer settings are not saved. This is pretty disastrous for tri-copters which usually need to reverse the tri servo.

betaflight does this OK --- the below is from diff on my βF tri:
````
# BetaFlight/SPRACINGF3 3.0.1 Nov 15 2016 / 19:39:56 (48b7b4f)
# mixer
mixer TRI

# servo
servo 0 1000 2000 1500 45 45 100 -1
servo 1 1000 2000 1500 45 45 100 -1
servo 2 1000 2000 1500 45 45 100 -1
servo 3 1000 2000 1500 45 45 100 -1
servo 4 1000 2000 1500 45 45 100 -1
servo 5 1000 2000 1500 45 45 100 -1
servo 6 1000 2000 1500 45 45 100 -1
servo 7 1000 2000 1500 45 45 100 -1

# servo mix
smix reverse 5 2 r
````
compared to iNav, which on my iNav tri generates:
````
# INAV/SPRACINGF3EVO 1.5.0 Dec 18 2016 / 15:02:10 (42696af4)
# mixer
mixer TRI

# servo

# servo mix
````

This needs checking against FW servos and specific settings as well.

**Comment by sambas** [comment]
Did you change profile in inav? In BF servoconfig is in master config where as in inav it is in profile config. Mag_declination also weird as it is not in profile config. Anyhow all these need to be checked.

**Comment by stronnag** [comment]
Didn't change profile. There is nothing in the 'diff' profile about smix.
In a normal iNav dump, servo / smix is shown outside of the profiles (even before features).

**Comment by sambas** [comment]
@stronnag Can you try again? Found some bugs. Pastebin "diff all" if you see something weird.

edit: only current profile servoconfig gets printed. Still needs fixing.

**Comment by stronnag** [comment]
Looks better for mag decl. No change on smixer (which I guess is still 'to do' ?)

**Comment by sambas** [comment]
Now it should be correct, do "diff all" to verify. Servo, aux and adjrange are profile dependent. Not sure if we really need them to be.

http://pastebin.com/2QL7C1Nu

**Comment by stronnag** [comment]
The latest version appears to be worse, possibly because I'm bench testing on a spare FLIP32 (rather than the EVO), as it's more accessible:

Original (cut down) TRI settings:  https://transfer.sh/VvKrg/t-fp.txt

Results of dump and diff all : https://transfer.sh/LnSEa/cli-diff.txt after applying these settings.

* The mixer line is appended to the version (for both dump and diff). This may just be a NAZE artefact.
* The critical `smix reverse 5 2 r` is not present in either the dump or the diff.

**Comment by sambas** [comment]
smix is used either with customservomixer which is under master config or with servoconfig which is under profile config. Not so clean at the moment but should do the job.

Need to discuss what is nessessary to have under profile config.

**Comment by stronnag** [comment]
We should probably also restore default profile and rateprofile, which the latest version does not do.

**Comment by stronnag** [comment]
Thanks. Looking good (not withstanding the global / profile discussion).

**Comment by digitalentity** [comment]
@stronnag did you experience any issues with this code?

**Comment by stronnag** [comment]
No. It's been perfect on NAZE, SPRF3 and EVO since @sambas's last update.
A review of the merits for global / profile for aux / smixer and others would probably be useful prior to merge.

**Pull request merged**
