### PR TITLE
add support for ADSB receivers

### PR DESCRIPTION
**Pull request by ShikOfTheRa**
ADSB support for uAvionix pingRX tiny ADSB (and others).
OSD display nearest ADSB equipped aircraft.
Flashing warning for proximity

Wiki page prepared:
https://github.com/ShikOfTheRa/inav/wiki/ADSB

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
I will add more descriptive detail and vid / screenshots of it working  tomorrow.

**Comment by ShikOfTheRa** [comment]
Wiki page linked below created and added to the Pull description.
Probably explains it all.

https://github.com/ShikOfTheRa/inav/wiki/ADSB

**Review by digitalentity — CHANGES_REQUESTED** [review]
Looks like some files are missing from the PR - nothing seems to call `adsbNewVehicle` and others.

**Comment by ShikOfTheRa** [comment]
mm strange - yes it is missing mavlink file calling. My bad

I'll revisit it with updates based on 2.6

**Comment by skaman82** [comment]
@ShikOfTheRa It has been a while - any chances to see this merged in 2.6.1?

**Comment by ShikOfTheRa** [comment]
Sorry for delay - have been absolutely full with day job and another iNav dev project. I'll try to resubmit with changes in next 2 weeks.  Have  a few people waiting for this!

**Comment by ShikOfTheRa** [comment]
Closing re-submitting as this is so old

**Pull request closed without merging**
