### PR TITLE
Array-based box masks

### PR DESCRIPTION
**Pull request by digitalentity**
Per  #1963, https://github.com/cleanflight/cleanflight/pull/2856

* Add bitarray support
* Migrate rcModeActivationMask to bitArray
* Some blackbox catchups with Betaflight (since I'm touching BB code anyhow)

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested on REVO. Works properly.

**Comment by digitalentity** [comment]
@DzikuVx configurator support for `MSP_ACTIVEBOXES` will be required when we have more than 32 box modes defined.

**Comment by digitalentity** [comment]
Blocked by #1977

**Comment by digitalentity** [comment]
Can anybody else test if modes are activated properly? I've tested on REVO and AirbotF4.

**Comment by giacomo892** [comment]
Is this PR "safe" to fly or requires a new configurator?

**Comment by digitalentity** [comment]
@giacomo892 it should be safe to fly - doesn't change anything Configurator-related. I only bench-tested it though.

**Comment by giacomo892** [comment]
I thin it is time to build a new firmware for my F450. So I'll try this too :)

**Comment by stronnag** [comment]
Flight tested. No problems, PH RTH WP

**Comment by digitalentity** [comment]
Yay!

**Comment by stronnag** [comment]
Double Yay!! Tested as part of testing #1997 (so here on Omnibus F3, and elsewhere Matek F405 AIO, both quadcopters).

**Pull request merged**
