### PR TITLE
Clean up climbrate to altitude controller

### PR DESCRIPTION
**Pull request by digitalentity**
Should fix issues with airplane RTH landing and overall altitude hold manual adjustment on airplanes.
Might break RTH landing on multicopters (testing needed).

### CODE REVIEW

**Comment by stronnag** [comment]
Any hints as to what bad behaviour might be manifest on MR, just so I'm prepared ...

**Comment by digitalentity** [comment]
@stronnag actual climb rate might be incorrect, shouldn't be any issues with throttle control though.
I'd test plain altitude hold mode first - uses the same controller and you are more prepared to bail out of AltHold and take over.

**Comment by stronnag** [comment]
4 out of 4 successful RTH landings on mr. Normal behaviour. Logs when I get home.

**Comment by digitalentity** [comment]
Cool! Let's wait for some of the FW-guys to test this on airplanes and merge.

**Comment by stronnag** [comment]
At least 7 / 7 successes as I reflashed the big tri in the field (saved acc settings are _so_ useful).

**Comment by stronnag** [comment]
http://seyrsnys.myzen.co.uk/roc_logs/

LOG*  = big tri
bb* = mini quad

**Comment by DzikuVx** [comment]
@digitalentity I just tested this branch and:

1. No logs, this machine does not records logs
1. No videos
1. Return (no land phase) OK
1. Descent was (or looked) more controlled
1. Descent was way way too fast
1. In both flight I had to abort few meters above the ground
1. In second case plane started to level, but was doing this too slow

Conclusions:
1. Better but not good
1. Descend should be much much slower. I suppose not more than 0.5m/s
1. Descend should start to slow down much earlier than in MR. 10m?

**Comment by digitalentity** [comment]
Good enough for now. Merging.

**Comment by giacomo892** [comment]
Flown this on my F450. All seems to work ok. Maybe RTH descend is a little faster now?

**Pull request merged**
