### PR TITLE
Converted targets to use new IO - needs testing on more targets

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by martinbudden** [comment]
This has been tested on CC3D, but needs testing on further targets before merge.

**Comment by digitalentity** [comment]
Bench-tested some boards:

CC3D: works
NAZE rev6: works
SPRACINGF3: does not boot

**Comment by martinbudden** [comment]
@digitalentity , I've altered the SPRACINGF3 target, the VCP feature was incorrectly set (I copied an incorrect setting from betaflight). Hopefully it should work now.

Can you please retest, as I don't have a SPRACINGF3 board?

**Comment by digitalentity** [comment]
@martinbudden tested. No, doesn't boot. Doesn't even flash the LEDs.

**Comment by martinbudden** [comment]
It looks like there is a problem in betaflight with the SPR3 board, see, among others, https://github.com/betaflight/betaflight/issues/486#issuecomment-228597103

@digitalentity , can you confirm the SPR3 works prior to this change?

And if so, can you comment out the `#defines` for the `BARO` and the `MAG` and see if it boots without those?

**Comment by digitalentity** [comment]
@martinbudden I can confirm that SPF3 was working before this PR - I'm flying it.

I'll try to figure out what's causing the hangup on boot.

**Comment by blckmn** [comment]
@martinbudden I suspect it is overclocking of the i2c bus that is causing the issue.

**Comment by blckmn** [comment]
The MAG is probably the problem. The MS5611 works fine at 800+khz, as does the MPU.

**Comment by digitalentity** [comment]
@martinbudden tracked that execution goes by this chain:
`main() -> timerInit() -> IOConfigGPIOAF() -> RCC_ClockCmd()`

The weird thing happens when execution reaches `switch()` statement here https://github.com/iNavFlight/inav/pull/314/files#diff-22a320fa3f17ac4e7b611455c28f104cR9

Neither of cases is executet, nor execution continues after the switch statement! Execution flow just stops (or triggers some exception). I don't have an F3 board with an SWD so I can't debug it further.

**Comment by digitalentity** [comment]
I don't have other F3 targets supported by this PR but this looks like either F3-specific issue or compiler-related issue.

**Comment by martinbudden** [comment]
@digitalentity , I think I've found the problem. I've pushed a fix - can you try it when you get a chance?

**Comment by digitalentity** [comment]
Still doesn't work. Hangs at the same call to `RCC_ClockCmd(rcc, ENABLE)` at line 261 of io.c

**Comment by blckmn** [comment]
Just a thought have you got the IOGlobalInit or similar at the start of main.c init()?

**Comment by digitalentity** [comment]
@blckmn thanks!!!!
Adding `IOInitGlobal();` to the beginning of `init()` did the trick. SPRacingF3 target now boots. I don't know if it's flyable, but I am able to connect to it. Baro/Mag work as well.

**Comment by martinbudden** [comment]
@blckmn , well spotted. Thanks!

**Comment by martinbudden** [comment]
@blckmn , thanks for your help. Do you have another F3 flight controller that you can test this on?

**Comment by digitalentity** [comment]
I wonder why F1 targets were working without this call...

**Comment by blckmn** [comment]
It'll be because of the AHB setup. The F3 has differing AF setup

**Comment by blckmn** [comment]
I've an F3, with SPI I can test on. I should get a few more different controllers lol the wife will love it I'm sure ;)

**Comment by oleost** [comment]
The trick is not to tell the wife ;)

**Comment by AndersHoglund** [comment]
Maybe related: https://github.com/betaflight/betaflight/pull/613

**Comment by martinbudden** [comment]
@digitalentity ,

as we have found the underlying issue, I think this is safe to merge in. Do you agree?

**Comment by digitalentity** [comment]
@martinbudden agreed.

**Pull request merged**
