### PR TITLE
Ltm rate options

### PR DESCRIPTION
**Pull request by stronnag**
This PR addresses comments in https://github.com/iNavFlight/inav/issues/712 concerning LTM

* Adds a CLI option `ltm_update_rate` to configure the LTM update rate:
  * NORMAL: Legacy LTM updates, 303 bytes / sec, 4800 bps or better (default)
  * MEDIUM: 164 bytes/sec, 2400 bps 
  * SLOW: 105 bytes /sec, hopefully 1200bps
* Adds an xframe counter in spare[0]
* Updates documentation

Review note: It would be possible to reduce SLOW to 91 bytes / sec by only issuing GFRAME once per second; currently the difference between MEDIUM and SLOW is in other frame updates.

The PR has been flight tested, examples of update density are shown. Images below show normal, medium and slow rates for a default (5m/s) mission.

ltm-normal
ltm-medium
ltm-slow

### CODE REVIEW

**Comment by stronnag** [comment]
Note also that the implementation is compatible with https://github.com/iNavFlight/inav/issues/183, in that the selection of rate could be automatic on telemetry port baud rate should iNav support rates less than 9600 in the future.

**Comment by digitalentity** [comment]
@stronnag do you mind if I commit a cleanup right into this branch?

**Comment by stronnag** [comment]
Please do.

**Comment by digitalentity** [comment]
Done. I like the new option. Now we can use really slow speed wireless links.

**Comment by stronnag** [comment]
Even better if in the future we address the full baud rate issue, e.g. for HC-12 that needs serial side at 1200 for maximum range.

**Comment by digitalentity** [comment]
Something is wrong with Travis - won't start the build

**Comment by digitalentity** [comment]
I think it's the right time to add low baud rate support. We'll have to simultaneously update the source and Configurator to have low baud rates supported properly though.

**Comment by digitalentity** [comment]
@stronnag see https://github.com/iNavFlight/inav/pull/1464

**Comment by sppnk** [comment]
Great to have lower baud rates for long range systems.

I will check if I can make work my minimosd at 1200 bps sharing port with openlrsng telemetry !!

**Pull request merged**
