### PR TITLE
New setting for disabling motor_stop in NAV modes

### PR DESCRIPTION
**Pull request by digitalentity**
As discussed in https://github.com/iNavFlight/inav/issues/3195
@fiam @DzikuVx @shellixyz @ABLomas please review and comment

### CODE REVIEW

**Comment by fiam** [comment]
Seems OK to me as long as motor stop is ignored by navigation modes by default.

**Comment by DzikuVx** [comment]
TBH I find this setting, as well as a MOTOR_STOP feature a harmful one. It should not be configurable and behavior should be hardcoded.

1. For MR there should be no MOTOR_STOP. Never. Armed = spinning. Chance of someone putting a hand somewhere thinking it's disabled but it is not and accidently raising a throttle (happens when TX is hanging on a strap around a neck) is quite a big one!
1. For FW, MOTOR_STOP should be always enabled but NAV mechanism is allowed to use it only during landing phase. Only. User is not allowed to override it in any way. We can not control stall.

From my perspective, every other combination is risky and might be potentialy harmful.

**Comment by shellixyz** [comment]
I agree. MOTOR_STOP is not really useful for MRs and can be dangerous. For fixed wing I don't see any advantage not using MOTOR_STOP so it can always be enabled.

**Comment by OlivierC-FR** [comment]
I disagree about motor_stop not being usefull or dangerous, on the contrary, when you're flying close proximity and hit something, very quickly the pilot can drop the throttle and stop all motors and force it to hit the ground. A quad is a lot less dangerous with all 4 blades stopped. You'll never be as fast if you have to disarm to stop the props. Never. Also, disarming a quad is definitive, while with motor stop you have to option to restart. Coming from someone who crashed quads hundreds of times, literally.

**Comment by digitalentity** [comment]
Rebased

**Comment by K-Suhas-Bharadwaj** [comment]
Dear sir/madam,
                             I am K Suhas Bharadwaj and new to GitHub . I
have been receiving mails about the development since I joined GitHub.I
want to contribute something to this open source project.But I couldn't
understand ongoing developments as I don't know the details of the
project.I have noticed that you are an active developer here.So I request
you to give me the details of project in reply and suggest me how to write
code for the project.

Thank you

On Jun 10, 2018 11:35 PM, "Konstantin Sharlaimov" <notifications@github.com>
wrote:

As discussed in #3195 <https://github.com/iNavFlight/inav/issues/3195>
@fiam <https://github.com/fiam> @DzikuVx <https://github.com/DzikuVx>
@shellixyz <https://github.com/shellixyz> @ABLomas
<https://github.com/ABLomas> please review and comment
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/iNavFlight/inav/pull/3349
Commit Summary

   - New setting for disabling motor_stop in NAV modes

File Changes

   - *M* docs/Cli.md
   <https://github.com/iNavFlight/inav/pull/3349/files#diff-0> (1)
   - *M* src/main/fc/settings.yaml
   <https://github.com/iNavFlight/inav/pull/3349/files#diff-1> (3)
   - *M* src/main/flight/mixer.c
   <https://github.com/iNavFlight/inav/pull/3349/files#diff-2> (2)
   - *M* src/main/navigation/navigation.c
   <https://github.com/iNavFlight/inav/pull/3349/files#diff-3> (1)
   - *M* src/main/navigation/navigation.h
   <https://github.com/iNavFlight/inav/pull/3349/files#diff-4> (1)

Patch Links:

   - https://github.com/iNavFlight/inav/pull/3349.patch
   - https://github.com/iNavFlight/inav/pull/3349.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iNavFlight/inav/pull/3349>, or mute the thread

**Comment by digitalentity** [comment]
@K-Suhas-Bharadwaj sorry, this is not a school - checkout the code and get yourself familiar with it. Read open issues, make meaningful comments, submit some patches and you would be warmly welcomed to the community.

**Comment by OlivierC-FR** [comment]
Its automated spam , ban the fucker !

**Comment by digitalentity** [comment]
@OlivierC-FR let's not judge by a single comment 😆

**Comment by ABLomas** [comment]
Because this didn't made to 2.0, we can try to refine logic and do everything correctly.
I believe, that nav_overrides_motor_stop should accept 3 values in total:

- OFF - current, default, logic (use throttle as needed by autopilot, ignore battery/alt/anything)
- MANUAL - do not use motor if user initiated RTH using switch (like current patch does) - if mode was activated with throttle low
- ALLWAYS - do not use motor in RTH modes (Switch activated or failsafe)

I made simple logic flowchart:
setting_flowchart

**Comment by digitalentity** [comment]
Did anybody actually test this PR?

**Comment by ABLomas** [comment]
Yes, i flew several times, AFAIK others too, so smth like 10 flights or so.
Current logic allow glide with motor off in RTH mode, but on failsafe (TX OFF) INAV still uses throttle, no matter what throttle value is.

**Comment by digitalentity** [comment]
Ok, thanks @ABLomas. Since it's in 2.0 milestone and works as implemented, I'm merging this (it will be included in 2.0 final). We can improve it in 2.1.

**Comment by digitalentity** [comment]
@ABLomas can you open a new issue with your suggestion and diagram?

**Comment by ABLomas** [comment]
Sure, thanks!

**Comment by romanas** [comment]
Great, im in! new RTH with 0 thrt works great, with new option it will just safe some wings!

**Comment by Saxin** [comment]
@digitalentity Had esc failure yesterday while 2.6 km out and 600 m alt., glided back best I could - around 800 m glide... at 10 m alt. lost video and engaged rth (swith) found the plane 100 meters off last gps cordinate headed directly to home as expected...

I wasn't sure if I should have engaged rth when discovered esc loss and how this option could affect rth without avaliable thrust - would appriciate your comments

**Comment by rk-tipro** [comment]
if wind is fine, wing will try to go straight home descending by 45° or try to keep the alt if hot wings accrues. rth with 0 throttle is my best settings (another is cruise). if right settings FS wont kick in with rth zero throttle. and wing will just try to go home, if it balanced well it will glide, and wont stall.

**Pull request merged**
