### PR TITLE
Add flash blackbox to MATEKF722SE target

### PR DESCRIPTION
**Pull request by MATEKSYS**
for 25Q256 flash on F722-mini

### CODE REVIEW

**Comment by digitalentity** [comment]
Ok, FLASH and SDCARD on the same SPI is not going to work at the moment. I'll merge this and make a variant of 722SE for F722MINI board.

**Comment by MATEKSYS** [comment]
No need to add a variant for F722mini,  I tested this definition,  F722SE and F722mini can share one firmware, just select SD or dataflash here

**Comment by MATEKSYS** [comment]
This firmware was built from development branch on Jan.16
[inav_2.1.0_MATEKF722SE_SD_dataflash.zip](https://github.com/iNavFlight/inav/files/2775095/inav_2.1.0_MATEKF722SE_SD_dataflash.zip)

**Comment by digitalentity** [comment]
The fact that you are able to select it in configuration doesn't mean that it will record correctly. SPI should be configured differently for SDCARD and SPIFLASH and we can't do that at run-time currently.

**Pull request merged**
