### PR TITLE
CleanFlight -> INAV docs cleanup

### PR DESCRIPTION
**Pull request by Soph**
I noticed that there are a few left overs in the documentation from the initial CleanFlight fork. I cleaned that up a bit and fixe a few links that pointed to the wrong repository, configurator or were just not working at all.

### CODE REVIEW

**Comment by oleost** [comment]
@Soph Hi and welcome. Thanks for helping out.

Please do your changes based on development branch and do PR against development and noth master branch.

**Comment by Soph** [comment]
@oleost ok, changed. 
And also updated the Development.md to reflect that INAV is using development branch for development.

**Comment by Linjieqiang** [comment]
@Soph Thanks for your work.

**Comment by digitalentity** [comment]
@Soph good job, thanks!

**Pull request merged**
