### PR TITLE
Don't use GPS altitude if BARO is available

### LINKED ISSUE #842: Prefer BARO altitude over GPS altitude for airplanes
Airplanes allow GPS altitude to be used. Current code fuses BARO+GPS with preference of GPS. In case of GPS glitching we may have a large change in altitude which is unwanted.

image

We should prefer BARO over GPS if both sensors are available.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #842

### CODE REVIEW

**Comment by digitalentity** [comment]
@oleost you might be interested in testing this with and without BARO enabled.

**Comment by oleost** [comment]
Sure, will try when I get a chance. But got two sick kids and a sick wife so won't be anytime soon. (chickenpox)

**Comment by digitalentity** [comment]
Holy buckets! Chickenpox is a bad thing, especially for an adult. No rush, family should always be a top priority.

**Comment by MarcoPTG** [comment]
@digitalentity this will have effect only when selecting the model type?
And for multirotors does this will not affect them?

**Comment by digitalentity** [comment]
@MarcoPTG yes, this will only affect airplanes.

**Comment by MarcoPTG** [comment]
@oleost hope that will past soon. I have already chickenpox with 29 years old. Don't take bath with hot water. That will get scratchy. I have the marks on my face.

**Comment by MarcoPTG** [comment]
@digitalentity. OK Thanks.

**Pull request merged**
