### PR TITLE
Fw coordinated turn

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by digitalentity** [comment]
Ok, this should be ready for merge now.

This extends `TURN_ASSIST` flight mode on airplanes - when doing a turn on an airplane it will calcualte required yaw and pitch rate to keep airplane pointed at horizon.

TAS (from airspeed sensor) will be used for calculation if available - otherwise code will use cruise airspeed defined by `fw_reference_airspeed`.

**Comment by oleost** [comment]
Great, one idea:

If GPS speed is available during auto tune use this to set fw_reference_airspeed if it's not manual set a value.

**Comment by digitalentity** [comment]
Default setting of 40km/s is good enough. It doesn't have to be exact - I've tested it on a light wind at speeds from ~25-30km/s to ~60km/h - it still gives somewhat sane results.

**Comment by digitalentity** [comment]
I think this is the last PR I want to get in before releasing the RC1. We are already quite behind schedule :thinking:

**Pull request merged**
