### PR TITLE
Add target 'AOCODARCF722MINI'

### PR DESCRIPTION
**Pull request by dlt2018**
hello,please help to add new target 'AOCODARCF722MINI'.
It has been tested and validated. it can upload it officially!
thanks for your work!

### CODE REVIEW

**Comment by MorrisR2** [comment]
I had already implemented this target and most of it matches what I got.
However there are a few differences. @dlt2018 are you on Discord or somewhere 
we interact better than here, perhaps, so we can cross-check a few things?

If not, the first thing I noticed is IMU_MPU6500_ALIGN. The board has an arrow on it.
For me, with the arrow pointing forward, I found this gives correct  motion:
#define IMU_MPU6500_ALIGN       CW0_DEG

**Comment by Ultraexpert** [comment]
Hi did you get a working version for 5.1? Thanks

**Comment by dlt2018** [comment]
> Hi did you get a working version for 5.1? Thanks

yes i have test it on INAV 5.1.0.

**Comment by Ultraexpert** [comment]
> > Hi did you get a working version for 5.1? Thanks
> 
> yes i have test it on INAV 5.1.0.

Amazing! Is the uploaded target ready to compile into 5.1 hex? could you send me your hex?
thank you

**Comment by dlt2018** [comment]
thank your for your help, .
I need to be compatible with another board, so there are some modifications.


***@***.***
 
From: Ultraexpert
Date: 2022-09-14 21:21
To: iNavFlight/inav
CC: MarkTan; Mention
Subject: Re: [iNavFlight/inav] Add target 'AOCODARCF722MINI' (PR #8157)
Hi did you get a working version for 5.1? Thanks
yes i have test it on INAV 5.1.0.
Amazing! Is the uploaded target ready to compile into 5.1 hex? could you send me your hex?
thank you

**Comment by DzikuVx** [comment]
I see it was replaced by #8418 closing

**Pull request closed without merging**
