### PR TITLE
Airplane code improvements

### PR DESCRIPTION
**Pull request by digitalentity**
- Experimental code to allow airplane to keep ground speed above some minimum
- Code to better do banked turns in automated modes - make rudder and ailerons work together

### CODE REVIEW

**Comment by oleost** [comment]
How do I increase min throttle?

Is it #define NAV_FW_MIN_VEL_SPEED_BOOST              500.0f
So increasing it to 1000.0f will give me 10m/s minimum speed?

**Comment by digitalentity** [comment]
Yes, I think so :)

**Comment by oleost** [comment]
Thank you, going to try that waypoint mission I showed in the other branch again, but with 10m/s and error tolerance up to 60 degrees.

But don't think I get to try it out today. Hopefully the wind will be the same tomorrow

**Comment by digitalentity** [comment]
Great! Thanks for testing airplane code!

**Comment by oleost** [comment]
Please update with latest master.

**Comment by sppnk** [comment]
Good to hear you are working in airplane code !! In special, the parts wich affect to the phisics of the flight, very different from multicopters. In baseflight I guess there was a variable to change relationship between rudder/elevator and ailerons. So, a new variable in CLI in combination with existent roll2pitch, pitch2thr and others should be great to fine tunning our planes.

**Comment by digitalentity** [comment]
@oleost updated.
Can you test if rudder works together with ailerons in gps-assisted modes?

**Comment by oleost** [comment]
@digitalentity great.

Yes I can test and see if it does what you want it to do. But my airplane have very little tail/rudder authority so propably not the best plane to test with.

EDIT: Looking  at my previous logs which I shared in imu heading which is both this branch and that branch merged it looked like it did both aileron and rudder stick commands? Will upload video with overlay.

**Comment by oleost** [comment]
@digitalentity Here are the video. This is an build using both imu-fw-heading-improvements and fw-improvements updated with master on may 15. And with additional error tolerance and increased low speed guard.

Link to cli, log and hex https://drive.google.com/open?id=0B-yHzNtOXxbEZmt0MWNQVFZxQjA

Link to video showing stick commands: https://youtu.be/kMGkMLLBXuM?t=1m13s

This is in extreme wind for my airplane. Test with less wind when I get a chance.

**Comment by digitalentity** [comment]
@oleost looking good even with this high wind. What did you change exactly?

**Comment by oleost** [comment]
@digitalentity 

I merged imu-fw-heading-improvements with both master and fw-improvements.

Then I change 

https://github.com/iNavFlight/inav/blob/fw-improvements/src/main/flight/navigation_rewrite_fixedwing.c

#define NAV_FW_MIN_VEL_SPEED_BOOST              500.0f
to
#define NAV_FW_MIN_VEL_SPEED_BOOST              1000.0f

and

https://github.com/iNavFlight/inav/blob/72e03c7eb4bc068801ecc28d718d10fd5ef1b50e/src/main/flight/imu.c

#define MAX_GPS_HEADING_ERROR_DEG   15      // Amount of error between GPS CoG and estimated Yaw at witch we stop trusting GPS and fallback to MAG
to
#define MAX_GPS_HEADING_ERROR_DEG   60      // Amount of error between GPS CoG and estimated Yaw at witch we stop trusting GPS and fallback to MAG

I'm thinking of new sets of default, and that would be 700.0f (7 m/s) for air speed, and probably around 70 degress before falling mag to mag, just to be sure that the plan is flying the right direction.

Also, I have an improvement proposal, and that is to use mag heading when stationary, ie speed below 3m/s.

**Comment by digitalentity** [comment]
@oleost your changes are in the code! Also IMU already uses MAG if available and GPS speed below 3m/s.

**Comment by oleost** [comment]
Looks good, but I think 10m/s is abit fast. I did it only to test it. (I had very low cruise throttle during this test just to verify that the boost was working)

Maybe 7m/s is more suitable.

**Comment by digitalentity** [comment]
@oleost now it's 7 m/s. Also there is a low-pass filter on aileron command to prevent rapid aileron movement when target is 180 deg behind and navigation struggle to turn the plane.

**Comment by oleost** [comment]
Okey, next time I'm out flying I will set up some waypoints to get 180 turns and test.

**Comment by digitalentity** [comment]
If possible try not only 180, but more like 170-175 in CCW direction. This should make the heading error jump from -175 to +175 a few times if it's windy enough :)

**Comment by oleost** [comment]
https://goo.gl/photos/guocjZQDKcBwwiDu9

Okey some like that?

**Comment by oleost** [comment]
@digitalentity There is some bug in latest FW improvements. Wont activate RTH or other modes. Probably because the plane is flying sideways in mwptools. This is flying with mag disabled (mag_hardware = 1)

Video I tried to enable RTH once, it just cut throttle and glide when I did it.

https://www.youtube.com/watch?v=Ifpf3zIydFM

https://drive.google.com/open?id=0B-yHzNtOXxbEX3ZrYV9COHVVMkE

Link providing blackbox log, cli dump, hex file, and build infomation.

Maybe its because of the new mag adjustments?

**Comment by oleost** [comment]
@DzikuVx Can the bug from my previous post have something to do with what you merged? https://github.com/iNavFlight/inav/commit/dd8a8aead526f9308f79fba523f3eb5204479f37

**Comment by DzikuVx** [comment]
@oleost with mag disabled MAGHOLD can not be enabled, see https://github.com/iNavFlight/inav/blob/master/src/main/flight/pid.c#L316

**Comment by oleost** [comment]
@DzikuVx  Not using maghold.

Only RTH, POSHOLD and waypoint with an flying wing using GPS heading instead of magnetometer.

**Comment by DzikuVx** [comment]
Exactly. Latest changes to MAGHOLD applied only to the case when MAGHOLD can be applied. 
I did not got to the code that computes heading based on GPS so no idea why you have cases of sideway flyting. Maybe @digitalentity can help here

**Comment by oleost** [comment]
Ok, sorry to bother you then.

**Comment by DzikuVx** [comment]
C'mon, no problem

**Comment by odixxx** [comment]
I tried to fly a plane, everything is fine in flight,
switch off throttle but when the plane did not manage not to react to sticks and disappears stabilization,
throttle adds all recovered spruce planted,
After landing check management costs strongly clamped (spruce move) add throttle costs normally,
that can be firmware or Problem?
ps. before it flew last cleanflight this problem has not been

**Comment by oleost** [comment]
@odixxx Not 100% sure I understand you correctly, but if I am it's already fixed on github and should be fixed next release. https://github.com/iNavFlight/inav/commit/3e6204dc7f60a2549d51b1e36856fcf4ed06abb0

**Comment by odixxx** [comment]
before running all right, in flight
when throttle 0 - no control and stabilization
to restore need to turn off battery
can do build for CC3D?
I can test

**Comment by odixxx** [comment]
I compiled code today,
checked on the plane - the problem persists!

**Comment by odixxx** [comment]
appears immediately after the discharge throttle 
problem on video
https://youtu.be/kGBE69peGS4

**Comment by digitalentity** [comment]
@odixxx do you have AIR MODE enabled?

**Comment by odixxx** [comment]
no, Angle or Horizon

**Comment by digitalentity** [comment]
@odixxx try enabling AIR MODE and check again.

**Comment by oleost** [comment]
@digitalentity Hi, welcome back.

Got time to look at my issue posted 5 days ago in this thread?

**Comment by digitalentity** [comment]
@oleost yes, I did. Looks like STATE(FIXED_WING) is not enabled. Possibly happened when we refactored mixer code. @DzikuVx IIRC that was your code, can you assist in figuring out why `mixer AIRPLANE` doesn't set STATE(FIXED_WING)?

**Comment by digitalentity** [comment]
@DzikuVx never mind, I've found it. Fixing.

**Comment by digitalentity** [comment]
@oleost, @DzikuVx please see 8d68993

**Comment by oleost** [comment]
Yes, I will try and with latest fw-improvements later today.

**Comment by DzikuVx** [comment]
Yeap, that was a bug... Good it was found and fixed!

**Comment by oleost** [comment]
Got a test flight, everything worked nice.

Also, did get to try some 170-180 turn with WP mission as we talked about @digitalentity 

Got some overshooting but guessing its just a matter for tuning.

Mwptools video: https://youtu.be/ZlTRSMBkgsE
Onboard cam video: https://drive.google.com/file/d/0B-yHzNtOXxbETEhrRnZNZTNYWHc/view
Build, blackbox, mission and cli dump: https://drive.google.com/open?id=0B-yHzNtOXxbEaF80TjR0MGlxaGM

**Comment by sppnk** [comment]
What a stable flight!! congrats. I cannot wait more to install a camera myself. :-)
Have you played lowering p_roll, or increasing d_roll? I guess your servos move too quickly, and may be their life could be short because of that (for pitch I guess that is not a problem). I am tweaking that now.

**Comment by digitalentity** [comment]
Great!
As far as I can tell rudder now works together with ailerons to achieve faster turning.
But we still have the bug with aileron jumping from one side to another when passing North. Still need to fix it :disappointed:

**Comment by oleost** [comment]
@digitalentity Glad you get something out of my logs :+1: 

@sppnk Yes I know about the ailerons servo working to much. Tried setting d_roll up to 200 but it did not help, at least not bench testing.

I'm planning to do something with it, just have not looked hard into it since I got an working setup otherwise.

Currently I'm trying to increase the scaling of the D-term and see if I get it to dampen P more. So changed

inav/src/main/flight/pid.c

`
#define FP_PID_RATE_D_MULTIPLIER    4000.0f
`

to
`
#define FP_PID_RATE_D_MULTIPLIER    50000.0f     // betaflight - 1000.0
`
and then
`
#define FP_PID_RATE_D_MULTIPLIER    10000000.0f     // betaflight - 1000.0
`

But I actually did not notice any difference bench testing with "set d_roll = 200"

So guess I'm either doing it wrong, or It's simply D-term is simple not suited to dampen like that.

Tried cutting my p_roll in half, to 100. But still lots of movements in bench testing just smaller.

Is there another way to smoothen the servo output without sacrifising P-gain @digitalentity ?

**Comment by theArchLadder** [comment]
@oleost 
Looks like those "MULTIPLIER" values are actually used for division:
https://github.com/iNavFlight/inav/blob/master/src/main/flight/pid.c#L158
So i think you should use a lower value to get what you want. (400 for example).

@digitalentity Shouldn't those be called "DENOMINATOR"...?

**Comment by oleost** [comment]
@theArchLadder Thank you, having a look at it.

Also it looks like the "d_roll" is inversed? With it set to 190 no dampning, if its set to 5 its dampened more.

This is with set to 200, ebc697c93f1e515341e75f0863212f061ed8d5c2

Video showing 5 and 190 difference. https://goo.gl/photos/yTqm9S75Ude4GqsV6

**Comment by theArchLadder** [comment]
@oleost D does not stand for dampening, it stands for derivative (rate of change). Seems to work as it should, higher D will dampen P but also be more noisy...

**Comment by sppnk** [comment]
I have played some with these PIDs. What I have learnt is that is safer to play with roll PID better than pitch PID. And in small amounts.

When lowering **p_roll** the plane does bigger turns, and the stabilization is way slower. When rising **d_roll** I have a similar effect. When playing with pitch the efects are the same, but pitch is an axis with a very diferent behaviour and characteristics, and very depending on center of gravity. So the parameters and the tests have to be very diferent. I havent yet reach a sweet spot. Not for roll, neither for pitch. Yaw usually is a quieter servo.

I guess we can reach a good point for all of this thing, but we have to spend time on it.

**Comment by oleost** [comment]
How about an lowpass filter on the servo outputs? I see there is some already in CLI "servo_lowpass_enable", but unsure if it works on fixed wing or only tricopter? Tried playing with it, and different HZ cutouts, but didnt notice any difference.

**Comment by digitalentity** [comment]
@oleost did you enable servo lowpass by `set servo_lowpass_enable=ON` ?
Still, this is not a proper solution. I need to think about a better way to avoid jumps.

**Comment by oleost** [comment]
@digitalentity Yes of course :)
I do not se any difference in bench testning, but not sure if I would either.
Tried reading up on how low pass filter works, not sure if thats the right way either.

**Comment by digitalentity** [comment]
@oleost the proper solution would be hysteresis - see latest commit. This should finally nail this 180-turn bug.

Now if 180 is expected turn direction is enforced until heading error goes below 90 deg when small jitter won't matter any more.

**Comment by digitalentity** [comment]
@oleost If you'll be able to test please do so and give me a "go" for merging this into "master".

**Comment by sppnk** [comment]
hi, I have compiled and flashed in CC3D, but having problems with PPM input (#238) I have gone back to last stable 1.1

**Comment by digitalentity** [comment]
@sppnk 
I presume you have configured PPM RX in Configurator, but just in case can you double-check?

**Comment by sppnk** [comment]
@digitalentity , yes I have done a dump from a working CC3D with 1.1 and then restored it after flash it with this build. Everything seems to work in the configurator, except PPM input. @martinbudden has tested master branch with CC3D, PIN3 and PIN8 builds and it works, so it should work for me for this branch.

What I am not sure is if after $git pull $git checkout fw-improvements $make TARGET=CC3D, the #238 pull request is included or not in the build, but I have tested PIN8 and PIN3 without success. I have gone back to 1.1 and everything is ok with ppm in PIN3.

**Comment by martinbudden** [comment]
@sppnk , it is possible that a submission after my test broke this code. I will test again this evening (just the PIN8 build though).

**Comment by sppnk** [comment]
good to read that. I was thinking the problem was with my wires or connectors.

Anyway @martinbudden , if I do 

$git pull
$git checkout fw-improvements
$make TARGET=CC3D

your #238 PR should be included, or not?

**Comment by martinbudden** [comment]
@sppnk , I don't know if that will include my PR. I do know my PR is on the master.

**Comment by sppnk** [comment]
@martinbudden , AFAIK it is included in master. I am not an expert and I am just  learning this 'github' thing, but #238 is a merged PR into master branch:

CC3D - PPM glitch fix #238
 Merged martinbudden  merged 1 commit into iNavFlight:master from martinbudden:inav_fix_cc3d_ppm 24 days ago

My question is if #238 is so merged in master, it should be in fw-branch or not? thnks.

**Comment by martinbudden** [comment]
@sppnk , I've just tested the default version, that is with PPM on pin 8 and it works fine.

"My question is if #238 is so merged in master, it should be in fw-branch or not?" - I already answered: I don't know.

As I said, my PR has been merged into the master branch. I haven't used the fw-branch, I don't know who created it or when.

**Comment by sppnk** [comment]
@martinbudden , I am not an github expert, and my question was not only for you. Thanks anyway. :-)

**Comment by oleost** [comment]
@digitalentity Got to do an quick test flight. Everyone looks good as far as I can see.

Got to do an small waypoints mission, before handing the control to a friend who wanted to test fly :+1: 

Link to video, blackbox log, cli dump and mission file. Stronnag will come with an mwptools video showing the mission.

https://drive.google.com/open?id=0B-yHzNtOXxbETlExcXlZNUtUOFE

(After 3min and 20s it's only "manual" flying.)

**Comment by stronnag** [comment]
https://vimeo.com/171145021

Seems like the replay mode misses some transitions, but that's an mwp / replay artefact.

**Comment by oleost** [comment]
@DigitalEntity something else you want me to test before merging?

**Comment by digitalentity** [comment]
@oleost I've rebased to include latest changes to "rated in dps" and "PID scaling change". If you can do a short test to make sure RTH and ANGLE mode works I'll merge this as soon as you give me a "go".

**Comment by oleost** [comment]
@DigitalEntity ok, does it have to be angle mode or is horizon okay?

Never flown with angle mode, I can test it, no problem. But I can't comment if it's changed or not.

**Comment by digitalentity** [comment]
@oleost Horizon is ok, it's exactly the same logic working when at middle stick.

**Comment by oleost** [comment]
@digitalentity Did a test flight today. As far as I can se everything works as expected, you can merge

https://drive.google.com/open?id=0B-yHzNtOXxbEWHdsWnFhUHdCVHM

**Comment by oleost** [comment]
When this is merge I can contuine to test #307

**Comment by digitalentity** [comment]
@oleost merged, thanks!

**Comment by sppnk** [comment]
a bit late. But I have merged and tested today in flight fw.improvements and flaperons branches with latest master. CC3D_PPM1 build.

RTH and mission WP working fine. I have to learn about rc_rates, but all seems to work ok.

I will try to test in afronaze, where I have big problems when activatin RTH, but I have to attach the logger and report. It will take some time for that tests.

Good job.

**Pull request merged**
