### PR TITLE
Add ability to store configuration in external SPI flash

### PR DESCRIPTION
**Pull request by mluessi**
This adds the ability to store the configuration in external SPI flash instead of a STM32 flash sector. This is needed for mircocontrollers such as the STM32 H750 that don't have internal flash sectors that can be used to store the configuration. But it may also be useful for other flight controllers, as storing the configuration externally frees up space that then can be used for code.

This code is adapted from Betaflight, where @hydra added this feature to support the SP Racing H7 EXTREME.

I have tested this on a BrainFPV RADIX 2 flight controller and verified that it compiles on a MATEKF722MINI. 

Summary of changes:
- Configuration backends to store the configuration in SPI flash and RAM (for testing)
- Improved config streamer code to prevent writing past allocated size
- Improved M25P16 flash memory timeout handling. The timeout is now based on the previous operation
- Improved M25P16 driver to return same address on write failure. This allows caller to detect failed writes
- Added SLOW_RAM section that is used to store the configuration. For H7, the D2 RAM is used for this.

### CODE REVIEW

**Comment by hydra** [comment]
Great to see this posted over, it'll also be useful for the H730 memory mapped FCs like the new H7RF.

http://seriouslypro.com/spracingh7rf

I've added code in my BF branch that supports the H730 and OctoSPI memory mapped flash chips.  Memory mapped flash chips give the firmware much more flash space to use for code storage *and* execution.

See:  https://github.com/spracing/betaflight/commits/bf-h7rf-and-config-in-memory-mapped-flash

**Comment by mluessi** [comment]
@hydra the H7RF looks pretty neat :)

Does anyone have time to review this? I'm happy to make changes if needed. I have been using this quite extensively and it works as expected.

**Comment by DzikuVx** [comment]
@mluessi looks good. Which FC requires that?

**Comment by mluessi** [comment]
@DzikuVx I'm using it for the RADIX 2, which isn't supported in the official INAV tree. 

But, any currently supported flight controller with a SPI flash chip could us it. Doing so would free-up more internal flash for code at the expense of RAM.

**Comment by MRC3742** [comment]
@mluessi 
Is this available for flight controllers with onboard SPI SD Cards or only SPI Flash chips?
How much flash memory are you able to save using this option?

I see you have included F3 boards to have this option available.
How do you enable this? as a firmware build option?

Sorry for all the questions. Thanks - Rich

**Pull request merged**
