### PR TITLE
Allow more I2C speeds

### PR DESCRIPTION
**Pull request by digitalentity**
Allow setting I2C to 100/200KHZ for supporting slow sensors or long wires.

### CODE REVIEW

**Comment by digitalentity** [comment]
@sambas can you help with functional timing variables for 100 and 200khz modes?

**Comment by digitalentity** [comment]
@DzikuVx you have the F7 board. Can you test the latest commit if it configures I2C to correct clock rates?

**Comment by DzikuVx** [comment]
@digitalentity Yes, no problem, can test today. How can I test is bus speed is correct? I have logic states analyzer but never used it yet ;)

**Comment by digitalentity** [comment]
@DzikuVx just hook up a logic analyzer or a scope (if your scope is good up to 1MHz) to SCL and check the clock frequency. Maybe it's time to give a try to your logic probe :laughing:

**Comment by DzikuVx** [comment]
i2c100khz

i2c400khz

@digitalentity tested 100kHz and 400kHz on Omnibus F7, looks good. And I've learned something new :)

**Comment by digitalentity** [comment]
Damn, doesn't fit into NAZE.

**Comment by DzikuVx** [comment]
Compiler gives us a sign again @digitalentity ... maybe it's really time to let go?

**Comment by giacomo892** [comment]
Let's fit this one :) my naze sometime lands with 1-2 I2C errors. Nothing tragic, but  maybe lowering bus frequency to 200Khz will solve this issue permanently :)

**Comment by giacomo892** [comment]
I've done some tests on NAZE

1. Switching from 400KHz to 200KHz the load goes from 4% to 12%
2. Switching from 400KHz to 800KHz the load goes from 4% to 3%
3. 1KHz loop time is not possible even setting SCL to 800KHz
4. Seems like a full power cycle is needed when changing SCL speed, at lest HMC5883 acts weird without that.


PS. Loads are reported without GPS and using only MPU6050 and MAG.

**Pull request merged**
