### PR TITLE
If flying, allow re-arm

### PR DESCRIPTION
**Pull request by sensei-hacker**
I've seen many reports lately of different users having crashes related to not being able to quickly re-arm after accidentally disarming, due to throttle or level checks.

This PR checks if a) the craft was armed and b) it is flying. If it was armed and is still flying, it allows re-arm regardless of level or throttle position.

if ( ARMING_FLAG(WAS_EVER_ARMED) && isFlightDetected() )
// Skip the throttle and level checks.

### CODE REVIEW

**Comment by Pairan** [comment]
that would have saved my GoPro 8 :) Glad you implemented this

**Comment by breadoven** [comment]
Does this work on a fixed wing if the throttle is between low and cruise throttle ? I'd have thought` isFlightDetected() `would return false with this throttle setting since it's really intended to detect the initial launch flight situation rather than flight afterwards so checks throttle is > cruise throttle.

**Comment by Jetrell** [comment]
Betaflight also has a feature like this. The idea sure has merit. More so for multirotors than fixedwings in my experience. At least a fixed wing can glide for a while, until you uncheck the safeties. While a Quad just falls to its death. 

@sensei-hacker In your opinion, how extensive do you think this feature should be? 

There was also some chat here a while back. https://github.com/iNavFlight/inav/issues/6789

**Comment by sensei-hacker** [comment]
Jetrell I'm not sure what you mean by "how extensive do you think this feature should be?"

I think for now, with the change cutoff this weekend, the PR is a good start. If it was armed, and is flying, allow re-arm. I like that it's a very simple, straightforward change for now - minimal code change.

For me, it's probably more important on fixed wing. That because on fixed wing I'll likely have a second to realize I accidentally disarmed and decide I need to re-arm (for my brain to process what's going on), and flip the switch.

For me, on one of my quads my brain would probably process the fact of "I accidentally disarmed" right about the time my quad hits the ground.

But for either planes or quads, either way - if the user armed, they are flying, and they try to re-arm in flight, we should let them. :)

**Comment by sensei-hacker** [comment]
@breadoven  Good catch!
Looking at where is isFlying() is being used, it looks to me like cruise throttle is a little arbitrary, unless I'm misunderstanding. It looks like maybe it would work as well or better to look for throttle not being very low.

Something like min throttle +  (0.2 * (cruise throttle - min throttle).

**Comment by breadoven** [comment]
You'll have the same issue with multirotors since `isFlightDetected ` looks for throttle being higher than hover throttle.

Probably needs a flag setting that indicates flying once detected after takeoff and then only resets on landing detection. Should reset on disarming just in case the landing wasn't detected, but then that wouldn't work for this change. Gets a bit tricky with this flying not flying stuff.

Throttle probably isn't so important for fixed wing flight detection, it was just included for extra confirmation. However, it's one of the few useful flight indicators for a multirotor so needs to be included.

**Comment by sensei-hacker** [comment]
It seems with the current code, if my hover throttle setting is 1700, my current throttle is 1680 and I'm going 33 km/h I'm probably not flying?

Checking throttle makes sense to me. Checking to see if the throttle is very low or not.
It seems to me, on almost every flight you'll have the throttle below cruise / hover at times while flying.  Simply because if you never lower the throttle below hover / cruise, you'll land. :)

If current throttle is 1420, and hover throttle was left at the default, it's probably flying. Agreed?  So let's reduce the minimum throttle that's considered compatible with flight.

**Comment by sensei-hacker** [comment]
I like where breadoven is going with the flag. I'm thinking I could expand on that in a way. I'll try to put some code together. Basically my thought is if I've definitely been flying for the last 10 seconds, and I haven't landed, then I'm probably still flying.

My general thought is:

If landing detected {
  likely_flying = 0
}

while throttle high and speed high {
   likely_flying++;
}

while throttle low or speed is low {
   likely_flying--;
}

"low" and "ugh" speed is very different for fw vs MC.
Same for throttle - different numbers that indicate "unlikely to be flying" and "very likely to be flying".  In between those two numbers, we have score generated over the last several seconds. If throttle was at 1700 for the last 10 seconds before I set it to 1400, and hasn't dropped below 1100, I'm probably airborne.

**Comment by sensei-hacker** [comment]
It was suggested I create a Discussion
https://github.com/iNavFlight/inav/discussions/8745 to separate this PR about re-arming from the discussion about methods and algorithm to detect flight.

**Comment by breadoven** [comment]
Probably the problem here is that `isFlightDetected` is really only intended to be used with flight detection rather than for general usage. It's purpose is to detect flight has started at some point during the flight, preferably immediately after launch but obviously before landing. So it doesn't need to reliably detect flight at any given moment during the flight, just at some point between post launch and landing. This latches flight detection on which remains active until landing is detected or disarm occurs. Without this a landing will potentially be detected before you've taken off.

**Comment by MrD-RC** [comment]
I have a couple of comments, as I was thinking about adding something like this. I think regardless of platform. This feature is more important now, because of digital HD FPV video system. On disarm, they switch to a low power mode. So video can be lost, making it, in some cases, impossible to rearm. If any is blocking rearming (non-low throttle, nav mode, etc), the system messages will not be seen, due to potential lack of video. So a short window to allow immediate rearming is pretty crucial for HD craft. 

My thought was to have a 3 second window to instantly rearm. This should be plenty. After that, it reverts to the standard safety checks. I don't believe it should be indefinite. As there is potential for the craft to be at a level it can interact with humans. If it were to rearm there unsighted, it could cause injuries.

My other thought was to have a countdown showing the immediate rearm availability window. This would only really benefit analogue. But it would be nice to see that you can rearm. Though the wording of this will need to be carefully thought out.

I think it would be great to get a feature like this in to 7.0.

**Comment by Jetrell** [comment]
> I have a couple of comments, as I was thinking about adding something like this. I think regardless of platform. This feature is more important now, because of digital HD FPV video system. On disarm, they switch to a low power mode. So video can be lost.

I've actually experienced that once too with HD.. But luckily I was using the override arming safety in the logic conditions.

> My thought was to have a 3 second window to instantly rearm. This should be plenty. After that, it reverts to the standard safety checks. I don't believe it should be indefinite. As there is potential for the craft to be at a level it can interact with humans. If it were to rearm there unsighted, it could cause injuries.
> 
I've setup something similar in the programming tab, for Multicopters.. Using 3D speed/barometric altitude free fall > 2km/h to determine if a rearm is allowed.
Can I suggest for MC's, that the software automatically switches the FC to ANGLE mode for a second or two, after rearming, to level stabilized the multicopter, in case it was in ACRO mode when accidentally disarmed. 
This is because rearming would occur once the quad has started to fall. And it may not fall flat.

**Comment by MrD-RC** [comment]
I like the sound of the temporary Angle for multirotors. Having it self right would be very useful. However, if it's disarmed, the motors would be stopped and airmode disabled. I don't know if allowing the motors to keep spinning on disarm should be allowed, due to safety. Maybe if freefall is determined and the altitude is above 20m?

**Comment by rmaia3d** [comment]
> I have a couple of comments, as I was thinking about adding something like this. I think regardless of platform. This feature is more important now, because of digital HD FPV video system. On disarm, they switch to a low power mode. So video can be lost, making it, in some cases, impossible to rearm. If any is blocking rearming (non-low throttle, nav mode, etc), the system messages will not be seen, due to potential lack of video. So a short window to allow immediate rearming is pretty crucial for HD craft.
> 
> My thought was to have a 3 second window to instantly rearm. This should be plenty. After that, it reverts to the standard safety checks. I don't believe it should be indefinite. As there is potential for the craft to be at a level it can interact with humans. If it were to rearm there unsighted, it could cause injuries.
> 
> My other thought was to have a countdown showing the immediate rearm availability window. This would only really benefit analogue. But it would be nice to see that you can rearm. Though the wording of this will need to be carefully thought out.
> 
> I think it would be great to get a feature like this in to 7.0.

That's a great idea, and I have mentioned this exact thing a few weeks ago in the Discord server. Accidental disarm in flight is something that can happen, and depending on where you are, it's absolutely critical to be able to quickly re-arm and resume normal flight.

Implementing a time window (no more than 5 seconds long would be plenty, I believe) from disarm where all arming checks are bypassed allowing a quick re-arm would be the simplest and most effective way of doing it, without the need for any flying detection logic that could add complexity and further bugs. 

For further safety, this time window could only be available after some time spent armed (for example, only enabled if disarmed after more than 15 seconds being armed).  After the time window (which could be user configurable) has passed, all normal arming checks would be in effect. The logic for this is that, if an accidental disarm happens, the pilot would notice this almost immediately, and try to arm again just as quick. So the time window where checks are bypassed doesn't need to be long.

**Comment by cayugas** [comment]
Would there be any advantage to a delay on the inflight actual disarm , like the failsafe activation!

**Comment by MrD-RC** [comment]
> Would there be any advantage to a delay on the inflight actual disarm , like the failsafe activation!

No, because it had to be assumed that a disarm is genuine. It could be for a safety reason. So every second counts. 

FS there is a little luxury in that a second won’t usually cause an issue, and it could be recovered in less time too, due to a temporary drop out.

**Comment by breadoven** [comment]
It should always disarm immediately on command. The only question here is whether there could be a short delay in applying the arming checks if still flying ... taking into consideration how confident you are that you are still flying of course.

**Comment by breadoven** [comment]
Oops sorry, clicked the wrong button ...

**Comment by DzikuVx** [comment]
@sensei-hacker if you don't mind, we will go with slightly more advanced solution from @breadoven in #9254

**Comment by DzikuVx** [comment]
@sensei-hacker if you don't mind, we will go with slighly more advanced solution from @breadoven in #9254

**Pull request closed without merging**
