### PR TITLE
Port Betaflight's toolchain installer

### PR DESCRIPTION
**Pull request by digitalentity**
Ensure everybody (including Travis) uses the same GCC version, unless they **really** know what they are doing.

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]
Worked nicely on company's Mac. In the evening I can verify if no problems with Linux subsystem on Windows

**Comment by digitalentity** [comment]
I've verified on Linux. Don't have Windows anymore :smile:

**Comment by DzikuVx** [comment]
Works great on Windows Linux Subsystem. I think we can merge it

**Comment by stronnag** [comment]
Override appears non-functional:
```
make TARGET=WINGFC
make/tools.mk:78: *** **ERROR** your arm-none-eabi-gcc is '9.1.0', but '8.2.1' is expected. Override with 'GCC_REQUIRED_VERSION' in make/local.mk or run 'make arm_sdk_install' to install the right version automatically in the tools folder of this repo.  Stop.
[jrh@eeyore]$ cat make/local.mk
GCC_REQUIRED_VERSION=9.1.0
```

**Comment by digitalentity** [comment]
This PR doesn't add support for local preferences via `local.mk`

**Comment by stronnag** [comment]
Why does it tell me "Override with 'GCC_REQUIRED_VERSION' in make/local.mk " ....

**Comment by digitalentity** [comment]
Oops, missed that part when porting from BF. Fix under way

**Comment by stronnag** [comment]
> Oops, missed that part when porting from BF. Fix under way

Please not update error message ... :(

**Comment by digitalentity** [comment]
Nope, I remember that some of us use different GCC versions :smile: 
#4920

**Pull request merged**
