### PR TITLE
Log last disarm reason to blackbox, report via LTM

### PR DESCRIPTION
**Pull request by digitalentity**
For easier troubleshooting of in-flight disarms that happen once in a while.

### CODE REVIEW

**Comment by sppnk** [comment]
@digitalentity , I have added this to Wiki, as I guess 1.7 will come soon. 

Good idea to debug throught LTM.

**Comment by digitalentity** [comment]
Thanks. The idea is that even if machine is disarmed you still continue to receive telemetry. And even if you don't - you'll be able to do a post-mortem debugging using blackbox (if machine is recovered).

**Comment by stronnag** [comment]
There seem to be a few problems with the initial implementation, in particular for the way at least two (mwp, ezgui) of the available CGS are often used (e.g. poll MSP when disarmed, unsolicited LTM when armed, guess armed => disarm switchover by LTM timeout).

* The disarm reason flag is not zeroed on arm, thus if you do an "arm / disarm / arm" cycle, you then get continuous disarm_reason != 0 X Frames while armed; which is made worse because
* After disarm, the FC immediately stops sending LTM, thus the CGS will miss both the S_FRAME with the not armed status and the X_FRAME with the disarm reason.

At the risk of introducing an ugly design problem (and disrupting the protocol independence of telemetry -> msp switching), it would be nice if the FC could guarantee to send at least 1 (and possibly 2) seconds worth of telemetry after disarm before disabling shared telemetry.

In theory, this is a really nice feature, not only from a diagnostic point of view, but also because it could potentially simply the CGS MSP -> LTM -> MSP switch by providing a reliable status value, rather than having to depend on a timeout.

**Comment by sppnk** [comment]
May be it could be useful sending some LTM frames in all situations, not only for debugging, but for safety (lost model reasons) (#1356)

**Comment by digitalentity** [comment]
Last disarm reason is not intended to be zeroed on ARMin - it reports a reason for last disarm regardless of armed status.

As for sending 1 second worth of telemetry after disarm before swtching the shared port back to MSP - see https://github.com/iNavFlight/inav/issues/1562

**Pull request merged**
