### PR TITLE
Waypoint mission restart option

### LINKED ISSUE #6911: WP mission resume or restart
## Current Behavior

When switching out of a WP mission in another mode and back to the mission, it restarts the mission and puts WP 1 as next WP. 
## Desired Behavior

I would like to choose with a cli command if I want the mission behaviour to restart (currently) or resume and continue with the latest WP it was heading to. 
## Suggested Solution

Set a variable for the latest WP and if chosen in cli to resume, it will take over the WP from the variable 

## Who does this impact? Who is this for?

For all users, plane and copter

### PR DESCRIPTION
**Pull request by breadoven**
Resolves https://github.com/iNavFlight/inav/issues/6911.

Adds an option to restart a mission interrupted mid mission using the following settings:

- START - restarts from the first WP
- RESUME - restarts from the last active WP before the mission was interrupted (set as default)
- SWITCH - switches between START and RESUME each time WP mode is selected. Allows resume on first use after mission interrupted followed by the mission restarting at the first WP on next use. It will have no affect after that because the active WP will have been reset to the first WP in the mission.

The basic resume function has been tested and works. Needs some more testing though to properly check the switch option.

### CODE REVIEW

**Comment by breadoven** [comment]
Managed to test this and it works as expected.

- RESUME just resumes repeatedly
- START always restarts at the first WP
- SWITCH resumes on the first use and then starts from the first WP thereafter. Resume only becomes active again after passing the first waypoint. So this works the way intended, i.e. provides the ability to restart from the first WP whilst still having the opportunity to resume once every mission run.

**Comment by breadoven** [comment]
https://github.com/iNavFlight/inav/pull/6938/commits/785ce75225ce66e92a4a5ca979d1567adcb186da not required so long as https://github.com/iNavFlight/inav/pull/6979 implemented instead.

**Comment by pitbuild** [comment]
Did this feature make it into iNav 3.0 release?

**Comment by breadoven** [comment]
> Did this feature make it into iNav 3.0 release?

Afraid not. There was a bug with it anyway which should have been fixed with the latest changes. Tested on a fixed wing but not multirotor yet.

**Comment by breadoven** [comment]
Now tested fully:
1. Resume - resumes as expected when WP mode is toggled and only restarts from the first WP when the end of the mission is reached whether ending in RTH or loiter.
2. Start - restarts from the first WP every time WP mode is selected.
3. Switch - resumes on the first use, restarts from the first WP on the second use. If WP mode is toggled on the way to the first WP it has no effect on the way switch works after passing the first WP, i.e. resumes on first use, restarts from the first WP on the second use, which is as intended.

Changing to other Nav mode before reselecting WP mode doesn't change the above behaviour.

Also the problem with multirotors losing control at the last WP loiter is fixed (https://github.com/iNavFlight/inav/issues/7099). Loiter is now stable.

**Comment by DzikuVx** [comment]
@breadoven resolve coflict please

**Comment by DzikuVx** [comment]
@breadoven looks like merging multimission caused another conflict :)

**Comment by breadoven** [comment]
@DzikuVx  Hopefully should be OK now.

**Comment by timcable** [comment]
Hi All,  Is this working now or not?

I'm currently using betaflight - which does nothing at all with waypoints.  Would love to switch to iNav, but I need to be able to:
1) Create waypoints 
2) Hold the position for at each waypoint
3) During the "Hold Position", I manually take control of the craft (which enables me maneuver to take a few photos, then return to the general area of that way point)
4) trigger the craft to continue to the next (or a named) waypoint.

Hope that makes sense - is it doable now or in the near future?

**Comment by breadoven** [comment]
Should be working in 4.0 RC1. Use setting:
https://github.com/iNavFlight/inav/blob/release_4.0.0/docs/Settings.md#nav_wp_mission_restart

**Comment by timcable** [comment]
Thank you – I’m moving over to iNav

It’s more my style

**Pull request merged**
