### PR TITLE
Scheduler priority queue implementation

### PR DESCRIPTION
**Pull request by digitalentity**
Ported from betaflight, implementation by @martinbudden

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested on CC3D, works

**Comment by martinbudden** [comment]
Glad you are looking at this.

Do you have any interest in: https://github.com/cleanflight/cleanflight/pull/1787: Implemented support for SRF10 sonar rangefinder?

The SRF10 is an I2C based rangefinder. It's reasonably interesting in itself, but what's more interesting is that this PR has put in place the framework for I2C based rangefinders, so a PulsedLight LIDAR-Lite laser rangefinder would be straightforward to implement. I imagine a LIDAR rangefinder is something that would be useful for iNav. I've got an implementation in the works...

**Comment by digitalentity** [comment]
@martinbudden 
Great! Can you port the hardware-independent framework for rangefinders to iNav? Then we can easily add support for different rangefinders.

**Comment by martinbudden** [comment]
@digitalentity , OK, I'll look into porting it to iNav. The framework plus the SRF10 code works out to be about 400 bytes, so the framework on its own should be pretty small.

**Comment by martinbudden** [comment]
@digitalentity ,  I've made an initial port to iNav, see: https://github.com/iNavFlight/inav/pull/128

Let me know what you think.

**Pull request merged**
