### PR TITLE
Update Inflight Adjustments.md

### PR DESCRIPTION
**Pull request by randyoo**
fix minor typos

### CODE REVIEW

**Comment by DzikuVx** [comment]
Thank you @randyoo , merged

**Comment by vavisimo** [comment]
is there a way to make inflight adjustment with a Pot like older flight stabilizers where rate gain goes from 0 (no movement) to 100 (max rate movement)?  this would be a benefit for fixed wing setup

**Comment by DzikuVx** [comment]
@vavisimo AutoTune works pretty well for fixed wings

**Comment by vavisimo** [comment]
yea if theres a manual :) ManTune , nevermind - i think noone cares about the old pot gains

**Pull request merged**
