### PR TITLE
Converted ADC to new IO

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested on CC3D, doesn't work - all ADC readings are zero.

**Comment by martinbudden** [comment]
@digitalentity , I've now updated this - I missed a file in the commit.

Can you test this again? I've away for the next few days and cannot do any testing at the moment.

**Comment by digitalentity** [comment]
@martinbudden CC3D working as expected. Need to test at some F3 targets as well.

**Comment by stronnag** [comment]
Flown on SPRF3 and Dodo, no problems (45fc7a6)

**Pull request merged**
