### PR TITLE
Add MAMBAF405 target

### LINKED ISSUE #4262: Target request: Mamba F405 FC
This looks like a good quality, rightly priced F4 AIO FC + 4-in-1 ESC stack.

https://www.diatoneusa.com/store/p587/MAMBA_F405_Betaflight_Flight_Controller_F40_40A_3-6S_DSHOT600_FPV_Racing_Brushless_ESC.html

Except for baro, has everything else one would need for a basic iNav setup.. OSD, 2xUARTs, I2C pads.

Betaflight supports this using Fury F4 OSD ( FURYF4OSD )

### PR DESCRIPTION
**Pull request by shellixyz**
Closes #4262

### CODE REVIEW

**Comment by dentex** [comment]
@shellixyz Hi. If i'm not missing something, it's the same FC as this one: https://github.com/iNavFlight/inav/pull/4464

**Comment by shellixyz** [comment]
@dentex ehm ok maybe yes. The MambaF405 doesn't need anything to be changed compared to the FF4OSD target ? I don't have one I can't check anything. The analog channels are different between the two target files. Also the FF4OSD have a SS configured. And maybe other stuff different I didn't check everything.

**Comment by dentex** [comment]
@shellixyz Yes, there are small differences between the two target files we have. Incidentally, for the one that has been already merged (https://github.com/iNavFlight/inav/pull/4464/commits/32ca1a9dbe3a37363751f46f141c48207b2ff07e), a couple of pins must be swapped, as per this comment: https://github.com/iNavFlight/inav/issues/4262#issuecomment-474157470
I mean, the BF's target for the MambaF405 *is* the FURYF4OSD (that has some switches for other flavours - but not the one in iNav): so I think we are pushing two targets for the same FC.

**Comment by shellixyz** [comment]
OK so it would just need to be a variant of the FF4OSD then

**Comment by dentex** [comment]
In BF it's like this. 
Please note that the OSD variant *is* the Mamba.
Our target isn't set for the FURYF4 (non-OSD) also... So we basically need to only decide how to name the target and resolve those tiny differences... I flashed both and nothing changed... (apart from the two pins I was referencing above).

**Comment by shellixyz** [comment]
@dentex Ok, should be good now

**Comment by sergeyprokofev** [comment]
For Smart Audio if not used PPM. Verified by.
#define USE_SOFTSERIAL1
#define SOFTSERIAL_1_RX_PIN      PA1  // or NONE
#define SOFTSERIAL_1_TX_PIN      PC9  // FOR Smart Audio if not used PPM 
#define SERIAL_PORT_COUNT       5

and (or am i wrong?)
#define MAX_PWM_OUTPUT_PORTS    6  // 4 - morots, softserial, led strip

**Comment by digitalentity** [comment]
@shellixyz is this ready?

**Comment by shellixyz** [comment]
Yes it should be. I don't have a board to test though

**Comment by gsixx8** [comment]
@shellixyz I have the F4 Mamba and am trying to get it working correctly with INAV.  I would be interested in testing out the version you all are referencing.

**Comment by SECOUM** [comment]
Hello ,do you know why sbus on mambaf405 2.2 dont Work??
Impossible to connect

**Comment by sergeyprokofev** [comment]
I use mambaf405 and r9mm. Protocol f.port.  Everything works.

**Comment by SECOUM** [comment]
Ok ,thancks,i will test it ,on wich pad are you connectyour fport wire??
Any cli change? 
If you Can test ,mine with sbus dont Work
I will test fport tonight....you have take inverted or non inverted smartport with your r9mm??

**Comment by datamann** [comment]
I just tried to build mambaf405 from development and SBUS and softserial on PPM pad does not work. I tried the build (zip file above) and it works but that build is from an older code base. Did also try FuryF4OSD and SBUS does not work with that one either.

**Pull request merged**
