### PR TITLE
Improved CLI dump command

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden mixer fixed; more issues with other values:
```
VALUE i2c_overclock HAS NOT BEEN SET UP CORECTLY
VALUE debug_mode HAS NOT BEEN SET UP CORECTLY
VALUE acc_task_frequency HAS NOT BEEN SET UP CORECTLY
VALUE attitude_task_frequency HAS NOT BEEN SET UP CORECTLY
VALUE async_mode HAS NOT BEEN SET UP CORECTLY
VALUE throttle_tilt_comp_str HAS NOT BEEN SET UP CORECTLY
VALUE input_filtering_mode HAS NOT BEEN SET UP CORECTLY
set mode_range_logic_operator = 
profile 0
rateprofile 0
```

**Comment by stronnag** [comment]
regression, any attempt to `dump` or `diff` locks the (flip32) hard.

**Comment by digitalentity** [comment]
I confirm - a `dump` or `diff` locks up my CC3D dev board.

**Comment by martinbudden** [comment]
Sorry, this was prematurely merged. I'll get this sorted later today.

**Pull request merged**
