### PR TITLE
OSD Ground Course and Cross Track Error

### PR DESCRIPTION
**Pull request by breadoven**
Adds ground course and cross track error to OSD fields (analogue only).

Requires Configurator update for font symbols, see https://github.com/iNavFlight/inav-configurator/pull/1660.

### CODE REVIEW

**Comment by Jetrell** [comment]
Out of interest.. Can I assume that `Heading` on the OSD will only display the `Compass bearing` from here after?
With this field being empty if a Fixedwing does not have a magnetometer? 

While `CoG` will display GPS track, in its field for Fixedwing aircraft?

**Comment by MrD-RC** [comment]
I guess analogue only is purely because of the font characters? I can't see why this wouldn't work over MSP DisplayPort too.

**Comment by Jetrell** [comment]
@breadoven Thanks for adding this feature. :+1: 
I also find it a useful multi-rotor diagnostic.  When it comes to viewing the difference between Magnetic heading and GPS course. This can often occur due to compass interference on the MR. 

Its also good for tuning, when magnetic deviation occurs at higher Nav Bank Angles in a WP mission. It gives a good idea of how much `nav_mc_back_angle` can be applied, before this becomes an issue.

**Comment by rts18** [comment]
> Adds ground course and cross track error to OSD fields (analogue only).

I proceeded to use both `CoG track` and `cross track error`. But I have not been able to get the X-track error to appear on the OSD.
@Breadoven, you have written **analogue only** in your explanation. I wasn't sure as to the reason for this. Thinking MSPOSD or MAX7456 should receive the same data?

I have tested `CoG track` with both platforms (with a compass). It works both on the bench and in the air, digital and analogue.
But the `X-track error` character data will not appear in the OSD, on the bench or in the air. with either analogue or digital on a quad or digital only on a fixed wing.

**Comment by breadoven** [comment]
> > Adds ground course and cross track error to OSD fields (analogue only).
> 
> I proceeded to use both `CoG track` and `cross track error`. But I have not been able to get the X-track error to appear on the OSD. @breadoven, you have written **analogue only** in your explanation. I wasn't sure as to the reason for this. Thinking MSPOSD or MAX7456 should receive the same data?
> 
> I have tested `CoG track` with both platforms (with a compass). It works both on the bench and in the air, digital and analogue. But the `X-track error` character data will not appear in the OSD, on the bench or in the air. with either analogue or digital on a quad or digital only on a fixed wing.

I only added symbols for analogue initially but I think they were later added for digital anyway. Either way the numeric values should still work.

The cross track error only appears during a waypoint mission or RTH trackback, the OSD field is blank otherwise. It'll also needs `nav_fw_wp_tracking_accuracy` enabled otherwise it'll just show 0 error.

**Comment by rts18** [comment]
> The cross track error only appears during a waypoint mission or RTH trackback, the OSD field is blank otherwise. It'll also needs `nav_fw_wp_tracking_accuracy` enabled otherwise it'll just show 0 error.

That explains it. I was not aware of those conditions. I thought it might have also worked in Cruise mode.

Thanks

**Comment by MrD-RC** [comment]
Yes, digital symbols were added.

**Pull request merged**
