### PR TITLE
First cut of nrf24 telemetry

### PR DESCRIPTION
**Pull request by martinbudden**
First cut of nrf24 telemetry. Not ready to merge, but I've made the PR so that anyone who is interested can have a look.

Reusing the LTM stuff means this is really cheap, code wise.

### CODE REVIEW

**Comment by digitalentity** [comment]
Interesting stuff. With LTM being reused this indeed comes almost free. I wonder how tolerant NRF24 protocol/telemetry is to environmental noise.

**Comment by martinbudden** [comment]
I'm not sure about tolerance to noise.

One thing I have done with the iNav protocol is I've set it up so that it only channel hops in the bottom half of the 2.4GHz band. ( Got that idea from https://befinitiv.wordpress.com/2015/08/26/enable-2-4ghz-rc-systems-to-work-with-2-4ghz-video-systems/ )

This means it should work well with a a WiFi broadcast FPV camera, eg https://befinitiv.wordpress.com/wifibroadcast-analog-like-transmission-of-live-video-data/

All stuff to try out though...

**Comment by digitalentity** [comment]
I wonder if we can implement OpenLRS receiver. It's also the SPI radio module with channel hopping. Also REVO boards already have required hardware. It would be awesome to have a long range RC link for free on those boards.

**Comment by Linjieqiang** [comment]
How I wish inav could get OpenLRS done. OpenLRS is a wonderful project.

**Comment by martinbudden** [comment]
@Linjieqiang , I've heard of OpenLRS, but I'm not really familiar with it. What do people use it for?

**Comment by digitalentity** [comment]
@martinbudden OpenLRS is a long range control system. It operates in 433MHz ISM band and is designed to control aircrafts at extreme ranges - 10-s kilometers.

**Comment by martinbudden** [comment]
Thanks. I wasn't sure if it was used for telemetry or control.

**Comment by oleost** [comment]
Both it support transparent serial connection back.

So what many do is hooking up an Bluetooth adapter on the reciever end to
connect to example phone or computer.

Then you have several kilometers of range using example ezgui or mwp.
1. aug. 2016 10.11 a.m. skrev "Martin Budden" notifications@github.com:

**Comment by martinbudden** [comment]
Well, it seems that Nordic Semiconductor do a 433MHz radio, the nRF905:

http://www.nordicsemi.com/eng/Products/Sub-1-GHz-RF/nRF905

> The Nordic nRF905 is a highly integrated, low power, multiband RF transceiver IC for the 433/868/915MHz ISM (Industrial, Scientific and Medical) band. With an integrated +10dBm PA and sensitivity of -100dBm, the nRF905 is an ideal solution for applications requiring longer-range

**Comment by martinbudden** [comment]
OK, all fixed up now. Telemetry part is still experimental, but am merging in because of other updates to the NRF24 code.

**Pull request merged**
