### PR TITLE
Add AGL altitude estimation

### PR DESCRIPTION
**Pull request by digitalentity**
If rangefinder is available - estimate altitude above ground using IMU + baro + rangefinder. 
This PR adds estimation part required for proper terrain-following modes.

### CODE REVIEW

**Comment by digitalentity** [comment]
AGL looks ok so far. Altitude hold works as well. Can anybody test if poshold isn't broken?

**Comment by stronnag** [comment]
On Friday if no one does earlier.

**Comment by digitalentity** [comment]
@stronnag thanks!

**Comment by stronnag** [comment]
Tested on two machines (260mm deadcat, Omnibus F3, 600mm tri, Matek F405). No issues at all PH, RTH, WP, auto land / disarm etc. In fact, smoothest maintaining of altitude I can recall; or maybe it was the absolutely still conditions. 

No reason not to merge.

**Pull request merged**
