### PR TITLE
Smartaudio by Soph

### PR DESCRIPTION
**Pull request by DzikuVx**
This replaces #1576

@Soph I've allowed myself to make new PR inside INAV to fix conflicts and build problems. I hope this is fine with you

### CODE REVIEW

**Comment by Soph** [comment]
I don't even know why I should not be fine with that :)

**Comment by DzikuVx** [comment]
Glad to hear that. I need SmartAudio for my next build so I kind of will try to merge this as soon as 1.7.3 will be released and prepare Configurator changes

**Comment by DzikuVx** [comment]
@marbalon I disabled this feature on KFC32, you might want to investigate why build is failing

**Comment by DzikuVx** [comment]
```
Building OMNIBUS
Linking OMNIBUS
/home/travis/build/iNavFlight/inav/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: obj/main/inav_OMNIBUS.elf section `.bss' will not fit in region `RAM'
/home/travis/build/iNavFlight/inav/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: region `RAM' overflowed by 1372 bytes
```

Damn.... F3 and not enough RAM... @digitalentity @fiam @Soph ideas?

**Comment by DzikuVx** [comment]
@digitalentity Tested on OmnibusF7 and Unify Pro HV on UART6 TX. Works lika a charm from CMS

**Pull request merged**
