### PR TITLE
WP mission waypoint enforce altitude option

### LINKED ISSUE #6336: New Waypoint type: "Circle/Loiter up/down"
## Current Behavior
At the moment, INAV fixed-wing will ascent/descent in a linear matter. 

## Desired Behavior
A new type would fit in like: the fixed-wing ascents/descents around the coordinates until it has reached the desired height.

## Suggested Solution
A solution might have one or two inputs: desired altitude and angle/feet per minute. A first approach would be to use the limits configured for the plane. 

## Who does this impact? Who is this for?
Waypoint users with airspace boundaries.

## Additional context
Context here: I have a area where I can legally climb up to XX meters. That area is around 200x200 meters. My airplane could circle up without having to create a lot of waypoints or to manually circle the plane.

### PR DESCRIPTION
**Pull request by breadoven**
Provides an option to force mission waypoint altitude to be achieved before moving on to the next waypoint. If the set altitude hasn't been achieved when the craft arrives at the waypoint it will hold and adjust the altitude as required with a target margin of 100cm. Planes use a spiral loiter whilst changing altitude. Option is set for the whole mission and applicable to basic and timed hold waypoints.

Tested on fixed wing in flight. Multirotor still needs flight testing.

Closes https://github.com/iNavFlight/inav/issues/6336.

### CODE REVIEW

**Comment by breadoven** [comment]
Tested on a multicopter and works fine. However, it needs https://github.com/iNavFlight/inav/pull/7645 to prevent toilet bowling like instability at the hold position during height adjustment. Not sure if this was an issue before for timed hold with nav_mc_wp_slowdown set OFF, looking at the code I'd have thought it was @DzikuVx ?

**Comment by breadoven** [comment]
Any objections to merging this @DzikuVx @stronnag ?

**Comment by stronnag** [comment]
+1 Nice (and belated) feature. My only nit-pick is that the user visible setting  might be more intuitively named `nav_wp_enforce_altitude` or `nav_wp_force_altitude` rather than `nav_wp_capture_altitude`. But that's trivia.

**Comment by breadoven** [comment]
Yes I wasn't entirely sure about capture. Happy to change it to "enforce".

**Review by DzikuVx — APPROVED** [review]

**Pull request merged**
