### PR TITLE
Add SouthPAN SBAS for all my friends in AU/NZ.

### PR DESCRIPTION
**Pull request by mmosca**
This should give you the option to pick South PAN SBAS #9315

I am not sure if it will make much of difference, as there is a single PRN on SPAN right now.

### CODE REVIEW

**Comment by Jetrell** [comment]
> I am not sure if it will make much of difference, as there is a single PRN on SPAN right now.

True. The system won't be fully operational for another 4 years.. But its good to have it added for when the system reaches completion.

At present I can't notice any difference with only `GPS` and `Auto detect` SBAS active... Nothing like the difference it makes when enabling Glonass and Galileo with GPS.

**Comment by mmosca** [comment]
Auto should pickup any sbas service it sees, including span. 

A better test would be to pick a service not available in au/nz and comparing it to auto/span

**Comment by mmosca** [comment]
From the M10 interface manual:

0 is auto, and should scan all PRNs, which include SBAS PRN 122

image

**Comment by SouthPAN122** [comment]
@mmosca Hi, Does the latest version of INAV enable you to use SouthPAN even though the system is currently in test mode and utilises the MT 0/2 approach?

**Pull request merged**
