### PR TITLE
Add new target FLYWOOF745

### PR DESCRIPTION
**Pull request by flywoo**

### CODE REVIEW

**Comment by DzikuVx** [comment]
Hi @flywoo . Have you read the new hardware policy? https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

Please contact me on pspychalski@gmail.com on how to proceed further

**Comment by flywoo** [comment]
@DzikuVx  ok, i sent email .thank.

**Comment by harry1453** [comment]
Hi @flywoo, please could you add the FLYWOOF411HEX target as well?

**Comment by flywoo** [comment]
@harry1453  OK。

**Comment by edyno** [comment]
Hi DzikuVx,
It looks like there is a problem with I2C because the magnetometer does not work.

# INAV/FLYWOOF745NANO 3.0.0 May 28 2021 / 16:26:38 (d64e83e5)

# status
System Uptime: 60 seconds
Current Time: 2041-06-28T03:04:00.000+02:00
Voltage: 0.02V (1S battery - NOT PRESENT)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=UNAVAILABLE, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
Stack size: 6144, Stack address: 0x20010000, Heap available: 1716
I2C Errors: 60, config size: 7219, max available config: 32768
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 11, cycle time: 502, PID rate: 1992, RX rate: 49, System rate: 9
Arming disabled flags: HWFAIL RX CLI DSHOTBEEPER
VTX: not detected

**Comment by DzikuVx** [comment]
@edyno apparently target not assigned external sensors correctly to I2C bus.
I have prepared a fix but would like external tests. So please flash file from the attachment and test, please
[inav_3.0.0_FLYWOOF745NANO.hex.zip](https://github.com/iNavFlight/inav/files/6568289/inav_3.0.0_FLYWOOF745NANO.hex.zip)

**Comment by edyno** [comment]
Bingo, I2C works :) Thank you.
FYI: CPU load has increased approx. 3 times, compared to firmware 3.0.0 from the official "Flywoo download page". Before that it was about 4% now it is about 12%. 

# INAV/FLYWOOF745NANO 3.0.0 May 31 2021 / 08:40:11 (f8f87abd)

# status
System Uptime: 57 seconds
Current Time: 2041-06-28T03:04:00.000+02:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=216MHz, GYRO=MPU6000, ACC=MPU6000, BARO=BMP280, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
Stack size: 6144, Stack address: 0x20010000, Heap available: 1716
I2C Errors: 50, config size: 7219, max available config: 32768
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 12, cycle time: 519, PID rate: 1926, RX rate: 49, System rate: 9
Arming disabled flags: RX CLI
VTX: not detected

# tasks
Task list         rate/hz  max/us  avg/us maxload avgload     total/ms
 0 -       SYSTEM       9      27       3    0.5%    0.5%     50267
 1 -          PID    1923     109      87   21.4%   17.2%     42630
 2 -         GYRO    3759      32      14   12.5%    5.7%     14174
 3 -           RX      49      59      41    0.7%    0.7%       532
 4 -       SERIAL     100   70136       3  701.8%    0.5%       229
 5 -      BATTERY      49      31      16    0.6%    0.5%       206
 6 -  TEMPERATURE      99      11       2    0.6%    0.5%        43
 7 -       BEEPER      99      12       3    0.6%    0.5%        80
 8 -          GPS      49     179      21    1.3%    0.6%       259
 9 -      COMPASS       9     154     146    0.6%    0.6%       365
10 -         BARO      43     121      78    1.0%    0.8%       832
14 -    TELEMETRY     479      29       3    1.8%    0.6%       489
15 -     LEDSTRIP      99      74      38    1.2%    0.8%       928
17 -          OSD     250    1296      17   32.9%    0.9%      1096
18 -          CMS      50      11       1    0.5%    0.5%        14
21 -      VTXCTRL       4       8       1    0.5%    0.5%         1
22 -  PROGRAMMING       9      18      10    0.5%    0.5%        25
24 -          AUX      99      12       4    0.6%    0.5%        77
25 - SPORT MASTER     479      10       1    0.9%    0.5%       123
Task check function             9       1                        15
Total (excluding SERIAL)                    78.7%   32.4%

**Comment by DzikuVx** [comment]
I have no idea what was on the flywoo side but I expect it was something ancient. The load you are getting right now is what is expected from 3.0

**Comment by edyno** [comment]
OK I'll test more. I hope you are right. Thank you for your prompt support.

**Comment by nknotts** [comment]
@DzikuVx I am also having issues with I2C. I have flashed the latest RC2 hex (I have not tried the one you posted in this ticket). Did your fix get pushed somewhere? I'm only seeing 1 commit in the PR and didn't find anything in a quick search.

**Comment by harry1453** [comment]
@nknotts RC2 was released 13 days ago and the fixed build was posted here 11 days ago so it's definitely not fixed

**Comment by harry1453** [comment]
@nknotts RC2 was released 13 days ago and the fixed build was posted here 11 days ago so it's definitely not fixed

**Comment by nknotts** [comment]
Sorry, I missed that. I just installed the hex linked in this PR and I2C works as expected. Thanks!

**Comment by fanedi** [comment]
No news for INAV/FLYWOOF411HEX 3.0.1 ?

**Comment by ltwin8** [comment]
@flywoo could you please provide the target for the F745HEX FC?

it seems like the default F745 Target can not be used, there are at least some conflicts in the used ADC pins between inav Firmware and Betaflight firmware. 

also the firmware published on https://flywoo.tawk.help/article/firmware-inav (FlywooF745HD) do work for flying, but no current readout is possible.

**Pull request merged**
