### PR TITLE
MSP2 over crsf done like betaflight

### PR DESCRIPTION
**Pull request by druckgott**
I have implemented MSP2 over CRSF for the lua Script (so we get a lua script for Inav also.
https://github.com/betaflight/betaflight-tx-lua-scripts/issues/491

MSP2 over crsf done like here:
betaflight/betaflight#11112
betaflight/betaflight#11131

I now get WAIT API in the Lua script which I have already don and https://github.com/klutvott123 have already updated with MSP2 over CRSF.

Maybe somebody can help me to fix the thing we get it working. 
Compiling is working without error.
Currently I do not know how to debug it.

### CODE REVIEW

**Review by druckgott — COMMENTED** [review]
Please review there is a Bug But i cant find it to reciver the Information on the transmitter

**Comment by druckgott** [comment]
@DzikuVx, is there a way to get a Compiler online version?

**Comment by DzikuVx** [comment]
You mean download hex files build online? In Checks file there is an option to download all the built artifacts with all the files

**Comment by DzikuVx** [comment]
@druckgott tests are failing, I want to merge it to `master` for the next major release

**Comment by druckgott** [comment]
@DzikuVx, i know i dont know whata wrong the msp 2 Do Not realy work thats why i implent testing, But it also Do Not work and i cant find why its Not working

**Comment by sensei-hacker** [comment]
Do I understand correctly that this would make the BF Lua script also work for INAV?

**Comment by druckgott** [comment]
Yes i have generate a version which should work some body from betaflight supportrd the Main point that the Script works with msp2

**Comment by b14ckyy** [comment]
@druckgott I suggest to keep that open. Hit me up on Discord or Facebook please I need to get you in touch with someone :D

**Comment by JimB40** [comment]
Hey @druckgott,

Did some tests lastly on iNav MSP over CRSF and there are few problems with current implementation

**Comment by JimB40** [comment]
1. Missing proper MSP version in response's CRSF status byte .

When Master (radio) sends MSP packet with version 1, Slave (FC) should respond with same version number (ie 1) and properly structured MSP frame.

MSP_over_CRSF_2a

iNav sends back status byte with version always set to zero.
Checked code and version is not packed into status byte as in BetaFlight
https://github.com/betaflight/betaflight/blob/90841282b03339c7361db306d280f4bdd96de1e4/src/main/telemetry/msp_shared.c#L284-L285

Bit packing structure for status byte is:
bit 0-3 - MSP sequende (0-15)
bit 4 - MSP start (set to 1 for first CRSF frame if MSP packet is chunked over few CRSF frames, if not first chunk it is set to 0)
bit 5-6 - MSP version (1 or 2)
bit 7 - MSP error (set to 1 in case of error - '!' in MSP header)

**Comment by JimB40** [comment]
2. Missing MSP command in response.

MSP_over_CRSF_2b


Just after payload size (ie 3rd byte in response) there should be MSP command ID before actual payload.
Again It is missing comparing to BF
https://github.com/betaflight/betaflight/blob/90841282b03339c7361db306d280f4bdd96de1e4/src/main/telemetry/msp_shared.c#L299

and official MSP doc
MSP_over_CRSF_2b2

**Comment by JimB40** [comment]
3. Padding CRSF Frame containing MSP response shorter than CRSF frame is not needed.

It only slows down processing with non relevant information.
MSP_over_CRSF_3

**Comment by JimB40** [comment]
4. MSP checksum is optional.

CRSF frame is protected by it's own CRC, so no need to add MSP checksum.
EdgeTX is checking only CRSF frame checksum (CRC)
Haven't checked BF LUA if they check MSP CRC after decoding, but IMHO second CRC is redundant.

**Comment by JimB40** [comment]
Basically iNav MSP even in ver 1 is missing changes that was done to BF two years ago :)
But you mentioned BF PR in first post.

To test v2 from your branch with radio running LUA app I'd need hex for KAKUTEF4V2

**Comment by b14ckyy** [comment]
I have sent you a build with this PR in it.

**Comment by sensei-hacker** [comment]
The wrong version number and missing command ID sound like they need to be fixed, to me.
The checksum could stay. After the CRSF frame is delivered to the radio, there is no guarantee about where the MSP will be sent.

An issue with fixing any problems present in msp_shared, outside of the CRSF context, is compatibility with legacy third party systems. Where it's broken / wrong, that's an obvious reason to fix it. But are there third party systems that will break if we set the version and command ID correctly?

**Pull request closed without merging**
