### PR TITLE
Sensor detection retry rework

### PR DESCRIPTION
**Pull request by digitalentity**
Attempt to fix the regression found by @stronnag (implementing the approach suggested in https://github.com/iNavFlight/inav/pull/801#issuecomment-261764676)

Must be tested against #801

### CODE REVIEW

**Comment by digitalentity** [comment]
@krzysztofmatula, can you test this and see if compass issue is solved?

**Comment by martinbudden** [comment]
@digitalentity , I really don't like moving the retry code into the `sensors/initialisation.c`. I think it's the wrong place to do it:

1. There is no theoretical reason why it should work any better
2. It doesn't allow sensor specific retry counts - for example one particular compass may need more retries than the others
3. It confuses the sensor initialisation code

I haven't been following the sensor detection code conversation that closely, but I believe at some point a change was made that was identified by @stronnag as a regression. Can we not just go back to before that change?

**Comment by digitalentity** [comment]
@martinbudden I think @stronnag's report of a regression might actually be invalid. Later he was able to successfully fly the machine even with current development (per-sensor retry count).

What I don't like about current sensor infrastructure is autodetection. I think compass/baro should be completely disabled by default and allow user to explicitly select the chip.

**Comment by martinbudden** [comment]
> What I don't like about current sensor infrastructure is autodetection.

I agree - we should definitely fix that for 1.5.

If we are doing that, then I don't really object too much to having the retries in the sensor initialisation code, since we will be getting rid of it when we get rid of the autodetection.

**Comment by digitalentity** [comment]
Let's see if people will complain about 1.4-RC1 which was released w/o this PR but with detection retry at driver level.

**Comment by digitalentity** [comment]
Looks like it would be better to take a different path in 1.5 and make sensor selection explicit as a part of #744

**Pull request closed without merging**
