### PR TITLE
Reimplement JETI telemetry

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by stronnag** [comment]
> Hi here is an open Issue #5868
> 
> Is it possible to get an .hex for MATEKF722SE board to test it?

http://seyrsnys.myzen.co.uk/inav_dev/

**Comment by RoadyFPV** [comment]
Thanks looks great.

Is it possible to get GPS Trip Distance as Telemetry value?

**Comment by RoadyFPV** [comment]
I did two test flights today.  Both of the flights went unobtrusively and without further problems.  flight time per flight approximately  35 min. Log files look clean.

**Comment by DzikuVx** [comment]
@RoadyFPV please make a feature request for telemetry sensors

**Comment by RoadyFPV** [comment]
@DzikuVx  ok done, i have opened a feature request #7302

**Comment by RoadyFPV** [comment]
@DzikuVx I have created a PDF for setting up and wiring. Maybe is helpful?

[How to setup your RX and FC for Jeti Ex-Bus.pdf](https://github.com/iNavFlight/inav/files/6918055/How.to.setup.your.RX.and.FC.for.Jeti.Ex-Bus.pdf)

**Pull request merged**
