### PR TITLE
Fix AOCODARCH7DUAL Buzzer continous beeping issue

### PR DESCRIPTION
**Pull request by lida2003**
Before fixing, buzzer beeping all the time, see below video:

https://www.bilibili.com/video/BV1is4y1F7RK?p=1

After fixing, buzzer seem quite good, see below confirmation:

https://www.bilibili.com/video/BV1is4y1F7RK?p=2

Binary and patches for 6.1.1 tag, see [inav-6.1.1-AOCODARCH7DUAL-fix-beeping](https://download.csdn.net/download/lida2003/87954695)

Note: It might need time for CSDN verify uploaded files, Or just use below zip file.

[inav_6.1.1_AOCODARCH7DUAL_fix_beeping.zip](https://github.com/iNavFlight/inav/files/11882701/inav_6.1.1_AOCODARCH7DUAL_fix_beeping.zip)

### CODE REVIEW

**Comment by mmosca** [comment]
@sensei-hacker Do you have the hardware to verify this one?

**Comment by sensei-hacker** [comment]
I do have that hardware. I have tested this commit and confirmed.

**Comment by dlt2018** [comment]
@sensei-hacker Thanks for your help fixing the buzzer bug

**Comment by DzikuVx** [comment]
Thanks, merging!

**Pull request merged**
