### PR TITLE
OSD summary stats improvements

### PR DESCRIPTION
**Pull request by avsaase**
Changes:
- Max current and max power are now shown on the same line since they measure the same thing. 
- Using `osd_stats_min_voltage_unit = CELL`, the average min cell voltage is shown instead of the total battery voltage. The default is `BATTERY` which is the current behavior.
- After the minimum battery or cell voltage, the current battery or cell voltage is shown. This follows the above setting. I find myself wanting to see the battery voltage directly after disarming, but this requires dismissing the stats. This change solves that issue.

I do not fully understand all the `buff` and `statValuesX` stuff but I managed to throw this together. There are a couple things I'm not yet happy with:
1. It would look nicer if max power was aligned more to the left when max current is less that 3 digits. The way I pasted these strings together feels a little janky to me. Is there a better way to do this?
2. When using 2 main battery voltage decimals the minimum voltage runs onto the `/` separating it from the current voltage. I tried accounting for this using `displayWrite(osdDisplayPort, statValuesX + 4 + osdConfig()->main_voltage_decimals, top++, buff);` but this doesn't work. Again it would be nicer to paste the strings together based on their actual length instead of some fixed number of characters.

I will later add the configurator side of this PR (also for `osd_stats_energy_unit`).

### CODE REVIEW

**Comment by avsaase** [comment]
Fixed both issues, also shifted all stats one character to the left:
2021-02-01 12_16_11-VLC (Direct3D11 output)

**Comment by avsaase** [comment]
Is `getBatteryRawVoltage()` no longer updated when the disarm screen is shown? I am not 100% sure but I think it just gives the battery voltage at the moment of disarming.

**Comment by Jetrell** [comment]
@avsaase Does this allow DISARMED BY to now fit on the page, without being half cut off?

Another tidy up suggestion. Instead of the Amps, Watts and Power unit letters being alphabet characters.
Can you replace them with font characters 
* A with 0x9a 
* V with 0x06
* W with 0xae
to keep more inline with the rest of the stats?

**Comment by avsaase** [comment]
@Jetrell For me DISARMED BY still falls off the bottom off the screen (completely) when using NTSC. I think having two max g-force lines is unnecessary but I assumed they are included for a reason. If not I'd like to remove the min/max Z g-force line. 

Goed idea about the symbols. I'll try to make that change this week.

**Comment by Jetrell** [comment]
> 
> 
>  I think having two max g-force lines is unnecessary but I assumed they are included for a reason. If not I'd like to remove the min/max Z g-force line.
> 
I think so too. The G-force stats give a wrong readout most of the time, because they also record the touch down or landing G-force. Which is not useful at all.

**Comment by avsaase** [comment]
I would also be okay with removing both lines.

**Comment by OptimusTi** [comment]
why not show all available rows, wait a few seconds, clear the screen, and then show the remaining rows?

**Pull request closed without merging**
