### PR TITLE
Add Crossfire Telemetry data to OSD

### PR DESCRIPTION
**Pull request by mdrjr**
This is a work in progress commit! 

I only build tested it, I do plan to test it later on a board.

I'm not sure if the code quality matchs what iNav team expects! (feedback is welcome)

It adds:
LQ
RSSI
SNR
TX Power

### CODE REVIEW

**Comment by Jetrell** [comment]
Someone else put forward a PR for this a while back. #4517 and  Under the Configurator#725

**Comment by 0crap** [comment]
@Jetrell The PR you refer at is inactive and closed, that will not help.
@mdrjr I sure hope you can finish this one. It's a very useful feature for all CRSF users.
You might even port it over from Betaflight v4.2, they already implemented it and works perfectly fine. (Use it myself on one quad.)
This can't be missed in iNav! 👍

**Comment by OptimusTi** [comment]
I'm working on changes to #4517. I contacted the guy and looks like he lost interest on Inav.

I added a SNR alarm and some enhancements for diversity receivers. I have posted videos on the Inav Telegram and FB group. It works. We just need more devs interested in Crossfire...

**Comment by OptimusTi** [comment]
> @Jetrell The PR you refer at is inactive and closed, that will not help.
> @mdrjr I sure hope you can finish this one. It's a very useful feature for all CRSF users.
> You might even port it over from Betaflight v4.2, they already implemented it and works perfectly fine. (Use it myself on one quad.)
> This can't be missed in iNav! 👍

I'm working on changes to #4517. I contacted the guy and looks like he lost interest in Inav.

I added a SNR alarm and some enhancements for diversity receivers. I have posted videos on the Inav Telegram and FB group. It works. We just need more devs interested in Crossfire...

**Comment by Jetrell** [comment]
> @0crap  The PR you refer at is inactive and closed, that will not help.

Read through that PR and you will see that it wasn't merged because developers wanted to wait until there was a wider range of other hardware that could use it.
I would be happy to see it merged as well. That was why I took the time to draw up some OSD icons for the functions. https://github.com/iNavFlight/inav-configurator/pull/725

@digitalentity What's your view on the topic at present?

**Comment by OptimusTi** [comment]
> > @0crap  The PR you refer at is inactive and closed, that will not help.
> 
> Read through that PR and you will see that it wasn't merged because developers wanted to wait until there was a wider range of other hardware that could use it.
> I would be happy to see it merged as well. That was why I took the time to draw up some OSD icons for the functions. [iNavFlight/inav-configurator#725](https://github.com/iNavFlight/inav-configurator/pull/725)
> 
> @digitalentity What's your view on the topic at present?

What other hardware could use/need CRSF telemetry data?

I believe that the big obstacle here is that most people don't understand why crossfire users would like to see radio/telemetry information. LuaTelemetry has it, OpenTX has it, the module has it. Why not in the OSD? Checkout my videos on the Telegram channel.
Cheers!

**Comment by 0crap** [comment]
> > @0crap  The PR you refer at is inactive and closed, that will not help.
> 
> Read through that PR and you will see that it wasn't merged because developers wanted to wait until there was a wider range of other hardware that could use it.

I really don't understand this remark. What wider range of other hardware??
Crossfire is here and the userbase is getting larger and larger.
This implementation is useful and CRSF will not go away any time soon.

Here a picture of my BF OSD setup to give a better idea.
BF CRSF OSD

You can see all important link status values at once.
The Mode (1 or 2) you are in with the signal strength in that mode.
And on top the SNR value.
For every 6dB of SNR you have available, you know you can double the current range.
Very important if you do long range.

Having these values available on the TX is nice but not as useful as on the OSD.

I found a simple and good explanation of all this on YT. (Not mine.)
Recommended to anyone not fully understanding the concept. (NOT saying anyone in this thread doesn't.)
Just for the Google search users ending up here, reading all this. ;-)
https://youtu.be/luVYpD_Zsc0

**Comment by mdrjr** [comment]
To be honest, if the iNav team decides that I should implement this in a more generic way that other protocols can take advantage as well I'm ok with it.. I did like that because I haven't found any other protocol that spits out the same information as crossfire does.

@digitalentity maybe I can add to rx.c instead a way to acquire those parameters and whatever RX provider is there takes care of feeding it. Would that be ok ?

**Comment by OptimusTi** [comment]
> > > @0crap  The PR you refer at is inactive and closed, that will not help.
> > 
> > 
> > Read through that PR and you will see that it wasn't merged because developers wanted to wait until there was a wider range of other hardware that could use it.
> 
> I really don't understand this remark. What wider range of other hardware??
> Crossfire is here and the userbase is getting larger and larger.
> This implementation is useful and CRSF will not go away any time soon.
> 
> Here a picture of my BF OSD setup to give a better idea.
> BF CRSF OSD
> 
> You can see all important link status values at once.
> 
> The Mode (1 or 2) you are in with the signal strength in that mode.
> And on top the SNR value. (You have a CLI command to switch this OSD element between RSSI or SNR.)
> For every 6dB of SNR you have available, you know you can double the current range.
> Very important to know if you do long range.
> 
> Having these values available on the TX is nice but not as useful as on the OSD.
> 
> I found a simple and good explanation of all this on YT. (Not mine.)
> Recommended to anyone not fully understanding the concept. (NOT saying anyone in this thread doesn't.)
> Just for the Google search users ending up here, reading all this. ;-)
> https://youtu.be/luVYpD_Zsc0 (Start viewing at 2:05 -> 7:19)

I'm sorry, but the explanation about SNR on that video is wrong. Check the Crossfire manual and look for the 6 dBm/"double your range" explanation. TBS is talking about RSSI. Not SNR.  SNR is a ratio that lets you know how close your received signal is to floor noise. (1:1 ratio = 0dB = poor signal)

The things that we should be looking at here are (see my Inav OSD mods in the picture below):

1. RSSI (1 and/or 2) in -dBm. (Like TBS says, your back account. Crossfire can measure from 0 dBm(perfect) to -130dBm.(bad) For every 6 figures, double your range (possible theorical distance!), blah, blah, blah)

2. RF Profile Mode & LQ% [0..100%] (As sent by Crossfire. Yes. 0-100% and not 300%. Ask TBS why. Long story short, it works fine.) Of course, used along the RF Profile is the way to go. e.g. 2:100%

3. SNR in dB. In the TBS Core and FPVision OSD , SNR only shows if the number reaches a predefined number (alarm level). A suitable number would be between 3 and 8dB. As stated in the manual, anything above 8dB is not a reliable number. The important number here is 0dB which means TROUBLE! 75dB SNR means nothing. 0dB is bad m'kay?

4. TX Power in mW

5. Operation modes: This causes a lot of confusion and most people don't get it. Do not confuse RFMode with Operation Modes. Crossfire can work on two Operating modes:

    a) Normal Mode: This mode can run in to RF Profile modes (High bandwidth / Low latency profile  = 150Hz and Normal update-rate profile = 50Hz). Only these two modes are used. (No, it's not going to drop to 4Hz. Another misconception.)
   b) Forced Telemetry mode: This one only uses 150Hz or 4Hz RF profiles. Good for automated stuff (Ardupilot, Inav 2.6?)

Here's my screenshot of the working CRSF stuff (not showing OpMode since I think it's redundant):

image

And here's the working OSD menu:

image

We can do it!

**Comment by 0crap** [comment]
@OptimusTi Thanks for your explanation! Seems indeed the YT vid is not fully correct.

The only TBS manual I can find is [this one](https://www.team-blacksheep.com/tbs-crossfire-manual.pdf).

On page 23 there is a little info on RSSI and SNR:
"- RSSI - Received signal strength indicator, measurement of the power present in a received radiosignal [typ. -1dBm (good) to -130dBm (bad), logarithmic scale]
- LQ - Link Quality, based on the percentage of signal data received at the end-point [0 to 300%]
- SNR - Signal-to-noise ratio, compares the level of a desired signal to the level of background noise. 

The RSSI determines your available link budget on a logarithmic scale, with each additional -6dBm representing twice the range of your current distance. E.g. you are at 5km range with a RSSI of -84dBm. At a range of 10km you are expected to see a -90dBm RSSI. The receiver is capable of receiving signals up to -130dBm. The SNR plots your current RSSI against the noise floor, giving you a rough indication of the remaining range in real-time. The CROSSFIRE can receive signals down to about -12dB SNR, way below the noise floor."

So you're right about the RSSI and the 6dB double your range relation.
However your point nr 3. about SNR I don't read that anywhere in the manual.
Can you point me to that online document?

Anyway, hope to see this implemented soon.
If you can build a test version including this PR, branching from 2.5.2., I would love to play with it.

# version
# INAV/MATEKF405 2.5.2 Aug  4 2020 / 10:15:56 (faaedc7cb)
# GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

**Comment by OptimusTi** [comment]
> @OptimusTi Thanks for your explanation! Seems indeed the YT vid is not fully correct.
> 
> The only TBS manual I can find is [this one](https://www.team-blacksheep.com/tbs-crossfire-manual.pdf).
> 
> On page 23 there is a little info on RSSI and SNR:
> "
> 
> * RSSI - Received signal strength indicator, measurement of the power present in a received radiosignal
>   [typ. -1dBm (good) to -130dBm (bad), logarithmic scale]
> * LQ - Link Quality, based on the percentage of signal data received at the end-point [0 to 300%]
> * SNR - Signal-to-noise ratio, compares the level of a desired signal to the level of background noise.
> 
> The RSSI determines your available link budget on a logarithmic scale, with each additional -6dBm representing twice the range of your current distance. E.g. you are at 5km range with a RSSI of -84dBm. At a range of 10km you are expected to see a -90dBm RSSI. The receiver is capable of receiving signals up to -130dBm. The SNR plots your current RSSI against the noise floor, giving you a rough indication of the remaining range in real-time. The CROSSFIRE can receive signals down to about -12dB SNR, way below the noise floor.
> "
> 
> So you're right about the RSSI and the 6dB double your range relation.
> However your point nr 3. about SNR I don't read that anywhere in the manual.
> Can you point me to that online document?
> 
> Anyway, hope to see this implemented soon.
> If you can build a test version including this PR, branching from 2.5.2., I would love to play with it.
> 
> ```
> # INAV/MATEKF405 2.5.2 Aug  4 2020 / 10:15:56 (faaedc7cb)
> # GCC-9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
> ```

@0crap I guess I have an old pdf. It's on page 13:

image

In the past Crossfire would show 8dB for any SNR above 8. Of course, that's not correct, since it was not showing the correct values above 8dB. This was fixed and now you can read any SNR number in the module screen. And again, showing the value will not make it a reliable number. 

By definition, SNR is a measure to show how close the received signal is to background noise. 1:1 = 0dB = The Danger Zone

Things you don't see when you only fly with RSSI and LQ or only LQ:
image


I'd be glad to build a target, but my mods are from the atomiclama's PR that was closed. 2.5.2 ready at your own risk. What specific target?

Cheers

**Comment by 0crap** [comment]
Yep, they adjusted that pdf. The 8dB line is indeed removed.
They do say however that CRSF can measure -12dB SNR, way below the noise floor.
However I do see the 0dB SNR is the danger zone by defenition. (Below the noise floor seems a risk you don't want to put your craft into.)

I printed the version output in my post above to show you the target.
It's MATEKF405.
(A leftover from my quads I now reuse inside a wing.)

Thx for your time!

**Comment by OptimusTi** [comment]
> Yep, they adjusted that pdf. The 8dB line is indeed removed.
> They do say however that CRSF can measure -12dB SNR, way below the noise floor.
> However I do see the 0dB SNR is the danger zone by definition. (Below the noise floor seems a risk you don't want to put your craft into.)
> 
> I printed the version output in my post above to show you the target.
> It's MATEKF405.
> (A leftover from my quads I now reuse inside a wing.)
> 
> Thx for your time!

Agreed. I'll get a copy of the new manual. :)

Here you go. This is the Matekf405 hex and the vision font I modified. This hex is from PR #4517 plus my modifications. Flashed in F411-WSE and F405-Wing with no problems.

A few things to note:
1. I have not flown 2.5.2. Only bench tested and looks good. Use at your own risk. :)
2. You can reach the CRSF RX menu from "OSD/Layout/Defaults". The SNR Alarm setting is there and can be set from -12 to 8dB. It only BLINKS when SNR goes below the settings number.
3. The font has symbols for SRN(dB), RSSI(dBm), TX Power(mW) and an extra RSSI symbol for 2RSS. The RSSI numbers and symbols switch to the active antenna. This uses less screen space.

[inav_2.5.2_MATEKF405.zip](https://github.com/iNavFlight/inav/files/5038530/inav_2.5.2_MATEKF405.zip)
[vision.zip](https://github.com/iNavFlight/inav/files/5038531/vision.zip)

Cheers

**Comment by 0crap** [comment]
@OptimusTi And test flown!
iNav-crsf

Works awesome! Really gives the needed info about CRSF link status.
**Hope to see this one in iNav 2.5.3**

Only thing I didn't understand is the TX MODE option. (Bottom one in your OSD screenshot.)
Gives "HIGH" on my OSD when enabled. What does this mean?

And of course needs integration with the Configurator.
It's a pain to move the OSD elements with your TX sticks. :-) 

Tested on a AR.Wing with one (no diversity) TBS Crossfire Nano RX. (TBS firmware 3.72, current stable version.)

**Comment by OptimusTi** [comment]
> @OptimusTi And test flown!
> iNav-crsf
> 
> Works awesome! Really gives the needed info about CRSF link status.
> **Hope to see this one in iNav 2.5.3**
> 
> Only thing I didn't understand is the TX MODE option. (Bottom one in your OSD screenshot.)
> Gives "HIGH" on my OSD when enabled. What does this mean?
> 
> And of course needs integration with the Configurator.
> It's a pain to move the OSD elements with your TX sticks. :-)
> 
> Tested on a AR.Wing with one (no diversity) TBS Crossfire Nano RX. (TBS firmware 3.72, current stable version.)

Awesome! The weather isn't helping here so no flying for me.

The TX MODE option shows the RF Profile mode transmission bandwidths. It's the same as the numbers shown to the left of LQ%.

HIGH = 2 = 150Hz update rate
NORM = 1 = 50Hz update rate
LOW = 0 = 4Hz update rate

I'm thinking of renaming this to RX PROFILE or RF MODE to clarify things. The original code has it TX.

Once I get extra time, I'll check with the Devs via Telegram to figure out how to send a new PR. I want it to be as complete as possible. I can't see why they would object to this.

Cheers!

**Comment by 0crap** [comment]
I understand.

You might as well leave "TX MODE" out completely.
Less code to keep life simple. :-)
The same info is already displayed left of LQ%, like you say.

Hope the PR gets implemented.
I'm sure many will appreciate.

Thx for the time you put into this. 👍

**Comment by OptimusTi** [comment]
> I understand.
> 
> You might as well leave "TX MODE" out completely.
> Less code to keep life simple. :-)
> The same info is already displayed left of LQ%, like you say.
> 
> Hope the PR gets implemented.
> I'm sure many will appreciate.
> 
> Thx for the time you put into this. 👍

Thanks. Yes, I'm considering it to simplify things.

And sorry for hijacking this PR comments, I just wanted to clarify the confusions around TBS telemetry points. Their manual and support team are not clear, and this has created many questions and confusions. Cheers everybody.

**Comment by raffxj** [comment]
hi guys

can I have a hex file for this? would love to try it out

matek F722SE 
thanks

**Comment by OptimusTi** [comment]
> hi guys
> 
> can I have a hex file for this? would love to try it out
> 
> matek F722SE
> thanks

I can post a hex file and font file in the Telegram group. Post a message there. The code I'm working on is not related to this PR.

Record_2020_08_15_22_32_20_305

**Comment by raffxj** [comment]
@OptimusTi  sorry to sound like an idiot. but I dont know what telegram group is. could you post link?

or maybe I just post my email here? thanks

**Comment by OptimusTi** [comment]
> @OptimusTi sorry to sound like an idiot. but I dont know what telegram group is. could you post link?
> 
> or maybe I just post my email here? thanks

Open up the Inav-Configurator. It's right there. "Telegram Channel"

**Comment by DzikuVx** [comment]
Guys, I'd like to have this in the next INAV and community tested. This is why I have a couple of questions:
- does it work?
- which Configurator PR is designed to work with this?
- are all fonts updated with new icons?

We would like not to release something that is not ready, works with only 1 font and lacks Configurator support

**Comment by 0crap** [comment]
> Guys, I'd like to have this in the next INAV and community tested. This is why I have a couple of questions:
> 
> * does it work?
> * which Configurator PR is designed to work with this?
> * are all fonts updated with new icons?
> 
> We would like not to release something that is not ready, works with only 1 font and lacks Configurator support

Works great, done a dozen of packs already without problems on my setup. 👍 
I got only one font to test so I guess not all are updated.
And agreed on the Configurator, it's a pain to move OSD elements with the TX sticks.

I hope @mdrjr, @OptimusTi can make this PR go into the next INAV version.

**Comment by OptimusTi** [comment]
Cool. I would like to remind you guys that my mods are not based in this PR... It's based on old/closed/stale/ignored PRs. Based on negative feedback received from some Devs, if I submit anything, it's going to be after 2.6 comes out. 

Baby steps 😁

**Comment by JBKingdon** [comment]
Just a note that the 'mode' text doesn't work with ExpressLRS as we have a larger set of air rates.

**Comment by OptimusTi** [comment]
> Just a note that the 'mode' text doesn't work with ExpressLRS as we have a larger set of air rates.

Noted. We're discussing it in the Telegram channel. I'm going to remove it since it's redundant.

**Comment by JBKingdon** [comment]
Thanks. The video I saw was looking great. I wish I could persuade the BF devs to show the complete set of rssi-dBm/snr/LQ, I currently build my own fork to do it.

**Comment by 0crap** [comment]
@OptimusTi Because the code seems to work fine I hope to see this in the next release. Not sure why baby steps are needed.
If you don't have the time, just say so. Perfectly valid argument, because we all now coding is done in sparingly available free time.
In that case give a clear pointer what the current status of this PR is, so another one can jump in if they feel like it.
Thx! 👍

**Comment by OptimusTi** [comment]
> @OptimusTi Because the code seems to work fine I hope to see this in the next release. Not sure why baby steps are needed.
> 
> If you don't have the time, just say so. Perfectly valid argument, because we all now coding is done in sparingly available free time.
> 
> In that case give a clear pointer what the current status of this PR is, so another one can jump in if they feel like it.
> 
> Thx! 👍 

You'll have to read the whole thing here.  Not my PR. I just wanted to clarify some points and ended up using code from other dead PRs to make what I've shown. But yeah, we need this.

**Comment by 0crap** [comment]
You're right!

**Comment by OptimusTi** [comment]
> Guys, I'd like to have this in the next INAV and community tested. This is why I have a couple of questions:
> 
> * does it work?
> * which Configurator PR is designed to work with this?
> * are all fonts updated with new icons?
> 
> We would like not to release something that is not ready, works with only 1 font and lacks Configurator support

Hello Pawel, 

Sorry I missed your message. 

1. The code is working but I didn't use this PR. It's code from the closed PRs mentioned above. It just need testing. There are a few people here and in the Telegram channel testing the hex files.
2. There's no Configurator PR yet. I can look at it once I figure out how to compile and test. That would be the next logical step.
3. Only default and vision fonts are ready. I'll can work on the other fonts, but I still have questions. I don't know which character location are available. Is any empty location good to use?

So overall, this is not ready yet. Only good for testing.

Thank you!

**Comment by Jetrell** [comment]
> 
>   There's no Configurator PR yet. I can look at it once I figure out how to compile and test. That would be the next logical step.

  @OptimusTi  The Configurator PR that @expipiplus1 entered, is still open. 
Maybe he might want to chime in and help out.

**Comment by OptimusTi** [comment]
> > There's no Configurator PR yet. I can look at it once I figure out how to compile and test. That would be the next logical step.
> 
> @OptimusTi The Configurator PR that @expipiplus1 entered, is still open.
> Maybe he might want to chime in and help out.

Thanks thanks! yes, that's a start. Again, looks like the work on that PR was based old stuff... I'll pitch in. Thanks again.

**Comment by expipiplus1** [comment]
As far as I remember my PR wasn't merged because the devs (quite rightly) wanted it to be abstracted over other radios (various power levels, removing the "crsf" name form the code and all that) (and perhaps some minor code cleanup). It didn't get done because since that request I haven't been able to find the right combination of time coding and flying :/

The configurator PR wasn't anything special IIRC, just some cargo culting existing settings.

Looking at this PR it seems to support a subset of the CRSF features mine does and suffers from the same CRSF specificness that stalled my PR in the first place. FWIW I have many hours of flight time with my branch without error.

Getting either one of these merged would be great.

**Comment by OptimusTi** [comment]
I guess we can look at the code and remove the crsf reference pointing to "specific" CRSF protocol/telemetry data points not available in other radio systems. Pardon my ignorance, but a simple #ifdeF USE_SERIALRX_CRSF not good?

Does that mean that we need to remove crsf from rx/crsf.c? I don't think so, right?

**Comment by DzikuVx** [comment]
Thank you guys!
I'm closing this one as it's replaced by #6078 and tested configurator in iNavFlight/inav-configurator#1056

**Comment by 0crap** [comment]
@OptimusTi As I understand the PR for this is already merged in master.
Is there a possibility you can zip and add the remaining fonts here?
2.6 is not ready yet and the vision font above is not the greatest.

Would be awesome!

**Comment by OptimusTi** [comment]
Here you go... enjoy.

[PR1056 Fonts.zip](https://github.com/iNavFlight/inav/files/5190959/PR1056.Fonts.zip)

**Comment by 0crap** [comment]
Awesome, thanks!
Favorite font already loaded. :-)

**Comment by OptimusTi** [comment]
Cool. I made a cool change to the code. 

I'll setup a PR when I figure this GitHub desktop thing out.

**Comment by 0crap** [comment]
OK, now you got my attention... :-)

What I would see as a useful option is about the SNR alarm.
If it triggers, most of the time it shows briefly a value.
Usually too short to notice the actual value.
It would be nice if the SNR alarm triggers it stays a (configurable) amount of time on screen before it disappears again.
For example allowed values from 0-60 seconds. Select zero to keep the current behavior.

Just a suggestion.

**Comment by OptimusTi** [comment]
Thanks. The number is just a "Hey! You are getting close to possible bad signal" to let you assess the situation and look at LQ, RSSI, should you turn around, etc. Nothing more.

Displaying the value for longer than needed is actually "bad" information because it's not the actual value. In past versions of the Core OSD, TBS showed 8dB for any value above 8dB, which of course is wrong since it's not true. It's better to have it pop up if it's close to zero. 3 to 5db is ok for the level, I think.

I'm going to post a video in the Telegram channel of the new fix.

**Comment by JBKingdon** [comment]
For ExpressLRS the SNR is the real data from the radio chip. It's a little confusing because it's provided post AGC (automatic gain control), but I'd still rate it as useful enough to have the option of keeping it on screen full time.

**Comment by 0crap** [comment]
@OptimusTi "SNR hides above alarm level." 👍 
I like the idea!

Maybe that is a very good compromise @JBKingdon also is happy about.

**Pull request closed without merging**
