### PR TITLE
Increase nav_wp_safe_distance maximum

### PR DESCRIPTION
**Pull request by MrD-RC**
This PR increases the maximum safe distance for the first waypoint to 1500m. A lot of fixed wing LR pilots are frustrated with the 650m limit. This corrects that while not increasing the memory used by the variable. I didn't see any reason for this to be in cm. It's not divided anywhere. So metres is much more fitting.

Requires configurator https://github.com/iNavFlight/inav-configurator/pull/1659

Due to the units of the variable changing, I have added it to my [diff update tool](https://www.mrd-rc.com/iNav/INAV-6.0-CLI-Update.php#newCLIResults).
image

## Release Notes
`nav_wp_safe_distance` has been replaced with `nav_wp_max_safe_distance`. This setting uses metres, and used to define the maximum distance away that the first waypoint can be. Please update your diff if you use this parameter; either manually, or using [this tool](https://www.mrd-rc.com/iNav/INAV-6.0-CLI-Update.php#newCLIResults).

### CODE REVIEW

**Comment by DzikuVx** [comment]
@MrD-RC let's rename the setting name. Different unit will be confusing. Adding _metter suffix seems like a good idea for me

**Comment by stronnag** [comment]
I'm torn over the best solution to this. 

* We don't know of (all) third party tools that might check this (don't mind updating the `mwp` check based on firmware version), but are there others?
* The wiki will need updating (the infamous ["Some`` is disabled"](https://github.com/iNavFlight/inav/wiki/%22Something%22-is-disabled----Reasons) page at least --- I'll do that once we have a confirmed approach
* Even if the variable field was upsized, having a large distance in `cm` is confusing and `m` is a much better choice.

Given no obviously good solution, replacing `nav_wp_safe_distance` with `nav_wp_safe_distance_metre` or even `nav_wp_safe_distance_m` seems like the best choice.

**Comment by MrD-RC** [comment]
@DzikuVx If it's just the name of the parameter, and it being completely distinct from the previous version. Why not call it `nav_wp_max_safe_distance`? I'm not keen on including units in parameter names. This will kill the old parameter, and have a new one, so no confusion or conflicts.

@stronnag nice call on the Wiki document. I will get that updated too.

Let me know what you both think and I'll make the changes to the PRs and my tool.

**Comment by stronnag** [comment]
Changing the name is fine, it will 'fail safe' for older `diffs` / tools.

**Comment by stronnag** [comment]
I'd better not mention that is will also change the semantics of `MSP_NAV_CONFIG` and we try not to break external APIs.

**Comment by MrD-RC** [comment]
@stronnag it shouldn't. navConfig()->general.waypoint_safe_distance isn't used by MSP. Plenty of other navConfig()->general variables are. But not waypoint_safe_distance.

**Comment by stronnag** [comment]
Mea cupla, that's a MW only message. Just as well I didn't mention it.

**Comment by MrD-RC** [comment]
Renamed to `nav_wp_max_safe_distance`

**Comment by breadoven** [comment]
Are people not aware that the Yaw override can be used to allow arming if the first WP distance limit is preventing it ? Not sure if this is explicitly stated anywhere. Need to check.

**Comment by stronnag** [comment]
> Are people not aware that the Yaw override can be used to allow arming if the first WP distance limit is preventing it ? Not sure if this is explicitly stated anywhere. Need to check.

That was part of my  planned wiki update

**Comment by MrD-RC** [comment]
@breadoven I wasn't aware of it until I saw you close an issue about it yesterday. That was what reminded me to make this PR, as a lot of people have asked for it. They still want a check, but wanted more distance. It seemed that 650m was only chosen due to the variable being a uint16.

**Review by stronnag — APPROVED** [review]

**Pull request merged**
