### PR TITLE
Crossfire link status on OSD

### PR DESCRIPTION
**Pull request by expipiplus1**
This information is sent over the crsf serial connection since firmware 2.93

### CODE REVIEW

**Comment by expipiplus1** [comment]
See also: https://github.com/iNavFlight/inav-configurator/pull/725

**Comment by expipiplus1** [comment]
I have tested this with the large Crossfire Diversity RX. I couldn't get it to work with the nano diversity.

This all works, but there are a few things I'd like to do:

- Add a lowercase `d` and `m` to the fonts for decibels and milliwatts.
- Document the rssi values coming from crossfire (they are in negated dBm)

**Comment by teckel12** [comment]
@expipiplus1 The transmitter power level is a welcome addition. From conversations with TBS, it seems the only signal quality that matters is the LQ, which is a combination of a few different values and some mathematical magic (that comes in as RSSI).

**Comment by expipiplus1** [comment]
@teckel12 yeah, I think that's largely true.

I'm also interested in the different antenna RSSIs to try and gauge how well my antennas are placed on  the aircraft. The downlink stats are also interesting. I think the "transmission mode" could potentially be useful, to know if one is flying with 4Hz updates or 50Hz

**Review by digitalentity — CHANGES_REQUESTED** [review]
This should be made generic from OSD side of things, otherwise we will end up in the same mess as with different VTX protocols which require separate CMS support.

**Comment by expipiplus1** [comment]
@digitalentity absolutely,

Are there any other radios which provide this information?

**Comment by teckel12** [comment]
@expipiplus1 Maybe not now, but it could be setup to be non-crsf specific in case other protocols relay similar data.

**Comment by digitalentity** [comment]
KFCF32 board has a built-in receiver that could provide similar information. I'm sure @marbalon would be interested in modifying that part of code if OSD would be able to show that data using generic API.

**Pull request closed without merging**
