### PR TITLE
Implement MSP2_INAV_STATUS

### PR DESCRIPTION
**Pull request by stronnag**
Implement MSP2_INAV_STATUS as an improved MSP_STATUS_EX, providing a 32 bit armingFlags (no other changes). This provides MSP consumers with the full range of arming status, rather than just the first 16 bits in MSP_STATUS_EX.

### CODE REVIEW

**Comment by digitalentity** [comment]
I suggest we think what fields we should report in `MSP2_INAV_STATUS`. I suggest removing `mspBoxModeFlags` - we have a separate `MSP_ACTIVEBOXES` to report full size of the bitmask.

**Comment by stronnag** [comment]
By all means; my rather self-interest intent was to be able to report the full set of armingFlags to the user; perhaps just appending
````
     sbufWriteU16(dst, armingFlags>>16);
````
to STATUS_EX would have been a more expedient solution; then legacy consumers could just test the returned length (as was done for RAW_GPS to accomodate hdop) and rebuild the full mask.

But in general I agree, we should not propagate obsolete fields in a new status API. However, from the perspective of a CGS developer, having to replace a single API with multiple APIs to achieve the same result is not that attractive either, particularly when relatively high latency devices are involved.

**Comment by digitalentity** [comment]
I see your point. So, how about this
```
cycleTime (u16)
systemLoadPercent (u8)
busErrors (u16)
sensorStatusBits (u16)
configProfile (u8)
armingFlags (u32)
boxModeBits (u64)
```

Note that I deliberatly removed `accGetCalibrationAxisFlags()` as it's not relevant for current status.
I'm not sure about `sensorStatusBits` since we have `MSP_SENSOR_STATUS` API to get extended sensor status information.

**Comment by stronnag** [comment]
Looks good. My preference would be to leave `sensorStatusBits`, having the failure bit in a status message is really useful ... then I can always use  `MSP_SENSOR_STATUS` for a second opinion on `IS_ENABLED` v. `getFOOStatus()`.

**Comment by stronnag** [comment]
Here's another attempt, fields as above, rearranged for marginal backwards compatibility and retaining extant width for load.

**Review by digitalentity — APPROVED** [review]

**Comment by digitalentity** [comment]
Looks good. Let's have this merged and start using it

**Pull request merged**
