### PR TITLE
Pan servo home direction offset

### LINKED ISSUE #6500: Home arrow offset, to correct pan servo camera direction
Currently the direction to home, as shown by the home arrow. Is based on the assumption that the camera is facing the direction the plane is traveling COG.

But when a Pan servo is used. The camera can be facing up to +-180° from the direction of travel. Which gives a false indication of the direction back to home, by the arrow.

My request. Could an addition be made, with offset calibration.  So the home arrow will taking into account the Pan servo's uS position?
So the arrow always displays the direction back to home, regardless of the direction the camera is pointing.

### PR DESCRIPTION
**Pull request by avsaase**
Resolves #6500 (@Jetrell can you confirm this is what you asked for?). This PR creates two cli commands: `osd_pan_servo_index` to select the pan servo and `osd_pan_servo_pwm2centideg` to set the rotation of the pan servo as a function of the pwm signal. For a 180 degrees servo this most likely needs to be set to `18`. Change the sign to reverse the offset direction.

Example:

https://user-images.githubusercontent.com/880421/104463356-f56bff00-55b1-11eb-95d8-d30fc8ee05aa.mp4

Testing this on the bench is a bit of a hassle. I found the easiest way is to set a safehome nearby and remove ` && isImuHeadingValid()` from https://github.com/iNavFlight/inav/blob/01799179e9b8ac8bf36a3ab1bb69fbe248afd2a5/src/main/io/osd.c#L1334

This could also be applied to other OSD elements, the HUD elements would be good candidates for this (obviously that also needs a tilt offset). If there is interest I can make a separate PR for that or add it to this one.

### CODE REVIEW

**Comment by Jetrell** [comment]
@avsaase Wow. I wasn't expecting anyone to take any notice this soon. 
Plus, I didn't go into every detail. 
In fact, I was expecting some negative questions concerning the operation of such a function.

The need for such a function. Is because to our minds getting confused between what we see in the camera and what the home arrow is trying to tell us. 
This can easily happen when sight seeing in an unfamiliar location and especially when the camera is panned less than 40° left or right of center. Under these slight pan offset condition, it is not always obvious that the  camera isn't facing in the direction the plane is traveling. But can lead to major heading changes over a distance.

**e.g.** If the plane is heading due east 90° and your home location is 30° to your right at that given distance. 
If you then pan to the right 30° and look at your home location, you will see that the home arrow is now pointing 30° to the right of the home location you are looking at.
This can lead to confusion. Because you believe what your looking at the home location, but the arrow is saying that home is 30° to the right, of what you visually believe is home.

Although this is the primary issue; there is another problem that also has to be addressed..... That is, the plane will not be heading towards the home.  Even though you could be looking in the direction of home and the home arrow (with the new feature) will now confirm this. 
So the pilot needs to be made aware that the pan is offset. Otherwise he will never make the course correction to bring the plane back towards home.

My idea would be to add another addition to the servo uS offset you have implemented. 
This addition would make the home arrow `FLASH` as a reminder that the arrow may be showing him the direction of home according to the direction the camera is panned.. But the plane is not heading towards home. So he must bring the pan servo back within a few degrees of 0° before the home arrow will stop flashing. Then he can make his course correction for home.

How does this sound to you?

**Comment by avsaase** [comment]
I understand why you asked for this feature, but in any case it can never solve all problems because the COG is often not the same as the direction the camera points due to crosswinds. I think flying with camera pan can always be confusing if you forget you're not looking straight ahead, regardless of this PR. Maybe a separate pan degree OSD element would be a better solution for this?

**Comment by Jetrell** [comment]
I would like to thank you.  
I certainly do not expect you to go to great lengths for the sake of my feature request. I'm happy you noticed it :+1: 

It is difficult to take into account all conditions. I also thought about cross track error etc. 
From my own experience using Pan and Tilt, and those people I fly with. The main hope we have was for a feature that could easily and quickly give a reference of the direction too home, when using camera pan. 

I'm open to any idea that can be simply interpreted. I also thought about an OSD element. But I wasn't sure if it would make it easier, or just get lost among the rest of the elements. That was why I suggested the flashing home arrow. But I have no idea how difficult that may be to accomplish.

I'm happy to go with your what you are capable of.

**Comment by Jetrell** [comment]
I would like to thank you for doing this PR.

I think adding a pan offset element to this PR would complete it.
For the element to showed the pan servo's +- offset degress from center.
This would solve the above mentioned  plane heading issue. And it would also help the pilot workout home heading if the pan servo failed.``

**Review by DzikuVx — APPROVED** [review]

**Comment by avsaase** [comment]
I have not tried this out in flight as I don't have a pan servo setup, but the more I think about it the more confusing I think this option may be. I'll leave it up to the devs to decide what they want to do with this PR.

**Comment by Jetrell** [comment]
> 
> 
> I have not tried this out in flight as I don't have a pan servo setup, but the more I think about it the more confusing I think this option may be. I'll leave it up to the devs to decide what they want to do with this PR.

@avsaase I fly with P&T often and I'm familiar with being caught off guard by the home arrow pointing the wrong direction when panning around. 

I believe your PR will work good. But it also needs something like the addition I mention previously, to make it more secure and fool proof.
Or even an override that centers the PAN servo when RTH/FS is triggered. That way the camera will automatically align with the plane's heading.


**Here's a short night flight, to show how the camera pan and home arrow currently work.**
* When I pan to the right. The flashing lights in the center view of the camera are the home location. 
* Note the home arrow, when the pan servo turns 90degs to the right. It points to the rear of the plane instead of the home location.

[Pan_homearrow_clip-zip](https://github.com/iNavFlight/inav/files/5922626/Pan_home.arrow.zip)


@avsaase I'm willing to test it if you can give me a hex for F722-WPX .
@DzikuVx thanks for noticing this PR

**Comment by Jetrell** [comment]
> 
> 
> The more I think about it the more confusing I think this option may be. I'll leave it up to the devs to decide what they want to do with this PR.

@avsaase @DzikuVx 
I thought more about what you said Alexander. And your right.  
If the user doesn't have a FULL understanding of how this PR works. There is too much potential of it leading to home arrow navigation issues. This feature could cause more problems than it fixes.

The feature was meant to align instrumentation (home arrow) with camera image, to prevent confusion. And its nice to have that confirmation between the two... But in the end; instrumentation is more important for long range flight.


I thought of a simpler way to make it work more securely. BUT it will not align the camera and home arrow. 
**Although it will prevent the Pan servo being left slightly offset, so preventing the confusion between camera and home arrow, also preventing navigation issues**

It can be accomplished with OpenTX. Or could also be done with iNav logic functions, if it had a couple more operands.

OpenTx setup

It looks at the pan servo lever input when not centered. It also notes the magnitude of  the levers movement within its range.
If the lever is not moved within 25 seconds of the pan servo being offset from center. The pan servo channel will be overridden to center the camera. 
When the lever is moves slight, it will return the pan servo to its last camera viewing position.

@avsaase I would like to thank you for noticing my feature request and the time you put into writing this PR. I don't take for granted the effort you guys put in.

**Comment by MrD-RC** [comment]
This sounds really cool. The home arrow being based on the viewing direction makes a lot of sense to me.

What would also be cool, would be the inverse of this. So a mode where the camera looks towards the home direction. That way, if you do get lost in an unfamiliar area, it's even easier to find your way back. Enable the __pan follows home point__ mode and bank around until you're flying towards home. I think then you would also benefit from an OSD pan direction indicator, like @avsaase mentioned earlier.

Nice work guys.

**Comment by Jetrell** [comment]
@MrD-RC I tested it out a while back and it works well. Alexander done a good job with it.
I often use Pan and Tilt and also fly at night with it. This gives reassurance on those times when I'm flying in 3CRS and just sight seeing.
If you haven't seen it already. Have a look through the PDF i left. To help tune the Pan servo position for best accuracy.

**Comment by MrD-RC** [comment]
Nice @Jetrell. Mind if I share the PDF in an article I’m writing on the changes in 3.0.

**Comment by danielolsman** [comment]
I have just tested this new feature, but for me the configured degrees doesn't match  the servo travel. I guess the problem is my servo needs a PWM signal from 500 to 2500, so it looks like I have the use half the degrees value to make it work properly.

**Comment by avsaase** [comment]
@danielolsman What kind of servos are that? I've never heard of that before. This feature indeed assumes servos that use 1000-2000 us PWM, so if you have double that range you probably need to double or halve something.

**Comment by danielolsman** [comment]
This is the servo I have :
https://banggood.app.link/UL7bC506hhb

it's no big deal, I will change the value until it's right. I have lowered the value and it's getting closer

**Pull request merged**
