### PR TITLE
add speedy bee f7 target

### PR DESCRIPTION
**Pull request by azolyoung**
Hi, we have tested this firmware on our Speedy BEE f7, it's work fine. please have a look, thanks

### CODE REVIEW

**Comment by MACFPV64** [comment]
hello, 
is it possible to have the HEX files to try with my speedybeeF7?

**Comment by azolyoung** [comment]
Hi there, 

Sorry, I have missed the notification, here is the hex file for the newest commit:
https://speedybee.s3.amazonaws.com/inav_2.3.0_SPEEDYBEEF7_8d57b7f1.hex

Thanks!

**Comment by MACFPV64** [comment]
thank you,
is it sand enough to fly without fear?

best regards

**Comment by azolyoung** [comment]
Yes, we tested it in the office and in the sky and it worked fine.

**Comment by digitalentity** [comment]
@azolyoung please have a look at [INAV New Hardware policy](https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md) to make this an official target. Also, rebase your changed on top of the `development` branch.

**Comment by alex-kwinto** [comment]
hi, i was also using this patch on 2.3 and 2.4. How to make this target official and supportable?

**Comment by fiam** [comment]
Superseded by #5991, since I had to make some small changes

**Pull request closed without merging**
