### PR TITLE
INAV position estimator changes

### PR DESCRIPTION
**Pull request by digitalentity**
1. Optimised innovation residual calculations
2. GPS outage recovery is now done with a position reset
3. GPS/BARO offset calculation/application (should fix issues with baro/enabled boards and airplanes)
4. GPS weight scaler according to error magnitude; estimate EPE according to error magnitude (disabled atm)

### CODE REVIEW

**Comment by stronnag** [comment]
Flight tested PH, RTH, WP on a variety of mission complexity and type of craft (mini-quad, 600mm tri). No problems.  I see no reason not to merge this.

If anyone wishes to see them, there are some logs and a description under http://seyrsnys.myzen.co.uk/inav_2016-11-13/. In LOG0006.TXT there is a 200ms GPS drop out; the firmware copes admirably.

selection_507

**Comment by digitalentity** [comment]
@stronnag, great, thanks for testing! 
Weather permitting, I'm going to try this on an airplane in the next few days and merge.

**Comment by digitalentity** [comment]
@stronnag 
Logs from your Tri look quite good. The M8N GPS is very precise, we can probably have a multirotor without a baro flying perfectly.

**Comment by oleost** [comment]
@stronnag  May I ask for link to the GPS you uses. There seems to be big difference from the various clones out there.

**Comment by stronnag** [comment]
Sure. The small 'crash dummy' quad is an old (but genuine) Neo6M.

The tricopter is http://www.banggood.com/Ublox-NEO-M8N-Flight-Controller-GPS-with-Protective-Shell-for-PIX-PX4-Pixhawk-p-1005394.html. It's OK but has a disturbing tendency for occassional 200ms GPS drop outs. Usually happen during LOS WP missions at the extreme of visual range. However, iNav copes just fine.

The big quad (which I will test this weekend with the nav_estimator_changes) has http://www.banggood.com/UBLOX-NEO-M8N-BN-880-Flight-Control-GPS-Module-Dual-Module-Compass-p-971082.html, which is my best unit. I'm think I will replace the tricopter unit with another BN-880.

**Comment by digitalentity** [comment]
Critical bug in BARO/GPS fusion found (airplane-only), fix peding.

**Comment by stronnag** [comment]
Flight tested, No adverse affects on MR (unlike the broken dev branch)

**Comment by digitalentity** [comment]
I believe this is safe to merge for 1.4-RC1 now

**Pull request merged**
