### PR TITLE
Option to have altitude in imperial, everything else in metric

### PR DESCRIPTION
**Pull request by avsaase**
Some people say they want this so I thought why not? One person said they felt this was the natural way to display values because he is Canadian, so for lack of a better word I called this option the Canadian unit system.

### CODE REVIEW

**Comment by MrD-RC** [comment]
I would like to see the UK mode corrected too. That should be everything in imperial, except for temperature, which is in Centigrade.

**Comment by avsaase** [comment]
I'm not too happy about the setting name though. I have no idea if this is a Canadian thing or not, I just had to pick something.

**Comment by DzikuVx** [comment]
@avsaase In o r Out for 4.0?

**Comment by avsaase** [comment]
I'd say out. After the initial request on Facebook, I never heard anyone support his feature request so I think this odd combination of unit systems may be quite obscure. @MrD-RC already improved some of the other unit systems so if people still want this one they can report that here and we can implement it later.

**Pull request closed without merging**
