### PR TITLE
Got NRF24 working on CJMCU

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by nathantsoi** [comment]
This is awesome @martinbudden, any plans to bring it into betaflight?

**Comment by digitalentity** [comment]
@martinbudden, cool!

**Comment by martinbudden** [comment]
@nathantsoi , sure, if people want it. I'll make a PR for 3.1 - don't want to do anything that will delay the 3.0 release.

**Comment by nathantsoi** [comment]
sounds great! i have a NRF24L01+PA+LNA module i've been waiting to test :)

**Pull request merged**
