### PR TITLE
Refactor TIMER/DMA framework

### PR DESCRIPTION
**Pull request by digitalentity**
Preparation for DSHOT

### CODE REVIEW

**Comment by digitalentity** [comment]
F3/F4/F7 works. F7 refactoring needed.

**Comment by digitalentity** [comment]
@TwoToneEddy code is generally ready to start implementing DSHOT on top of this branch.

**Comment by digitalentity** [comment]
F4 & F7 mostly verified to work. F3 not tested

**Comment by digitalentity** [comment]
Almost done 😄

**Comment by digitalentity** [comment]
Ok, this should be ready for testing. SoftSerial + PPM in not tested. Motor output + Ledstrip works

**Comment by digitalentity** [comment]
Ready for testing

**Comment by digitalentity** [comment]
All motor protocols verified on COLIBRI_RACE (F3), REVO (F4) and OMNIBUSF7NXT (F7).
SoftSerial verified to work on REVO (F4, SmartPort, LTM)
If nobody objects I intend to merge this.

**Comment by TwoToneEddy** [comment]
Daft question, if I now build the development branch is dshot ready to try out?

**Comment by TwoToneEddy** [comment]
Sorry I'm an idiot, I see you have a branch for dshot. Can I test this if I add the USE_DSHOT to the target of the board I want to test with?

**Comment by digitalentity** [comment]
@TwoToneEddy Defining `USE_DSHOT` should be enough to allow DSHOT for a target (if all timer mappings are compatible). Use caution - I didn't test the code with actual ESCs

**Comment by stronnag** [comment]
I flew the new timer/dma stuff today (without USE_DHSOT) on a couple of F4 FCs. No adverse affects, no regressions.

**Comment by digitalentity** [comment]
@stronnag good to know, thanks!

**Pull request merged**
