### PR TITLE
Airplane throttle controller (experimental)

### PR DESCRIPTION
**Pull request by digitalentity**
Experimental code to allow airplane to keep ground speed above some minimum.

### CODE REVIEW

**Comment by oleost** [comment]
Don't think current implementation works.

https://vimeo.com/161521808

01:09 its below 5m/s, looking at blackbox logs the speed is 3m/s. But both rcCommand[throttle] and motor[1] is at minimum throttle 1300.

Link to post where bb log is http://www.rcgroups.com/forums/showpost.php?p=34440458&postcount=4718

**Comment by digitalentity** [comment]
@oleost yes, I know. This is mostly for discussion and also to make sure I don't forget it :smile:

**Comment by digitalentity** [comment]
@oleost 
Gave your blackbox log another go. Actually, the code does work, but in a slightly incorrect way.
Your plane was descending (pitching forward) and INAV applied pitch2thr and pushed throttle below min_throttle. Velocity controller had to fight that and it did after a while.

The code has to be modified so throttle boost controller discards the pitch2thr if we are too slow.

**Comment by oleost** [comment]
Sounds good, is it merged with latest master?

If so I can flash new firmware and start testing again.

But I think it would be easier to test with speed limit at 5 m/s instead of 3 m/s.

**Comment by digitalentity** [comment]
@oleost 
It is now up to date with latest master. And min velocity is hardcoded to 5 m/s. Lower speed limit when all navigation is not applied is disabled - navigation controls are always applied. Should work now :smile:

**Comment by oleost** [comment]
Great, will flash, test and report when weather permits.

**Comment by digitalentity** [comment]
Thanks!

**Comment by digitalentity** [comment]
Superseded by #180

**Pull request closed without merging**
