### PR TITLE
Compensate AHI for fw_level_pitch_trim

### LINKED ISSUE #7000: [3.0-RC1] AHI does not respect fw_level_pitch_trim
## Current Behavior
If fw_level_pitch_trim is set at a certain value to maintain level flight in self level modes, the AHI will still follow the RAW sensor value. This leads to an AHI offset in level flight.

## Steps to Reproduce
1. Place the aircraft on the bench to set sensor value for pitch close to 0° 
2. watch the OSD on a monitor or goggles
3. Go to PID tuning > Mechanics and set fw_level_pitch_trim to a value like 10° 
4. check the AHI on the fpv feed. AHI stays aligned on the crosshair
5. If the plane flies now level, the AHI will be 10° below the crosshair implying a climb
6. the same applies form the pitch angle value item on the OSD that also still shows the raw sensor value and not relative to fw_level_pitch_trim

## Expected behavior
fw_level_pitch_trim should be considered to indicate level flight and actual pitch angle in any case. 

## Suggested solution(s)
respect fw_level_pitch_trim for pitch angle indication on OSD and logs. 

## Additional context
-
---
- FC Board name and vendor: Matek F411-WSE
- INAV version string: INAV/MATEKF411SE 3.0.0 May 15 2021 / 17:01:46 (7b6a37a3)

### PR DESCRIPTION
**Pull request by avsaase**
Closes https://github.com/iNavFlight/inav/issues/7000, although right now it only compensates the AHI, not the pitch attitude osd element or HUD elements, telemetry, blackbox, logic conditions or pitch angle displayed in the configurator (did I forget anything?). Whether those should also be compensated as well depends on how you look at `fw_level_pitch_trim`. 

The author of the feature request (https://github.com/iNavFlight/inav/issues/6561, @fernandodlc) argued that there is a fundamental difference between "level" (meaning 0 degrees AoA) and the attitude needed for maintaining altitude. Some planes have a shelve or other place specifically designed to mount a flight controller and these are often level when the plane is sitting flat on the desk and the wings are at 0 degrees AoA. You then add a few degrees of pitch up to maintain altitude. From that perspective, no further changes are necessary because you actually pitch up during "level" flight. 

On the other hand, you could say the angle of the plane on the ground is irrelevant and we want to equate 0 degrees pitch with maintaining altitude. In that case, the other pitch related displays also need to be adjusted.

### CODE REVIEW

**Comment by b14ckyy** [comment]
I think for the 3.0.0 Release this looks good to me. AHI was the most obvious thing and kind of distracting. 

How I see the feature is the following: 

When we fly in angle mode, and at cruise speed the plane strictly keeps the AoA at 0. If you compare that with a real plane like an Airliner, the Wings are already mounted at the cruise AoA to have the cabin level. This should be our reference for 0° AoA. Therefore all sensor values should show 0° pitch when we fly in angle mode. 

But if althold is active and the plane has to change the AoA to maintain exact altitude due to speed difference, raising or falling air masses or a change in plane weight or CG, then the deviation in the AoA to maintain altitude should be shown on the OSD and sensor data. This way the pilot immediately shows that something is causing the plane to pitch up or down from standard values. 

Therefore I think overall all data like Log, telemetry etc should respect the Pitch level trim at the end. But This has no priority imho. We can move that to 3.1. If the Horizon is now fine that should be OK for the release.

**Comment by breadoven** [comment]
Think I'll stick to using `align_board_pitch` to correct for board alignment because this new `fw_level_pitch_trim `doesn't make sense to me if it messes up AHI and other stuff. I thought the idea of this new settings was to do the same as board pitch alignment but in a more intuitive way. In fact all it seems to do is make it easier to have the craft fly level in self levelling modes but since it hasn't been applied to all the other things affected by board pitch alignment such as AHI ... it causes other problems.

As I understood it for `fw_level_pitch_trim `to work as expected the craft should be levelled on the bench (Wing AoA = 0) and the board alignment set to 0 using `align_board_pitch`. Then set `fw_level_pitch_trim `to the expected level cruise AoA (3 degrees or whatever is required by flight test). At this point the plane should fly level in self levelling modes AND all those elements, AHI etc, using pitch should read 0, not minus `align_board_pitch`.

**Comment by avsaase** [comment]
> As I understood it for `fw_level_pitch_trim `to work as expected the craft should be levelled on the bench (Wing AoA = 0) and the board alignment set to 0 using `align_board_pitch`. Then set `fw_level_pitch_trim `to the expected level cruise AoA (3 degrees or whatever is required by flight test). At this point the plane should fly level in self levelling modes ... 

Correct

> ... AND all those elements, AHI etc, using pitch should read 0, not minus `align_board_pitch`.

Not yet, clearly, but it can certainly be made that way. If we are adjusting _everything_ for `fw_level_pitch_trim`, then it might make more sense to directly change `attitude.values.pitch` in imu.c. That would solve everything in one go instead of first adding it to the target pitch angle in pid.c and then having to compensate for it throughout the project. @DzikuVx, any thoughts on that?

**Comment by b14ckyy** [comment]
> the craft should be levelled on the bench (Wing AoA = 0) and the board alignment set to 0 using align_board_pitch

I think here is the issue. Plane on the bench is NOT automatically a AoA=0 unless specifically designed that way by the Manufacturer. If I do that with the AR Wing classic it will climb at 2m/s in level flight. My Bushwacker plane (the only one with landing gear) has a 15° AoA whan on the ground. This won't work. We don't have AoA sensors anyway and the pitch angle is NOT the AoA.

**Comment by breadoven** [comment]
> > the craft should be levelled on the bench (Wing AoA = 0) and the board alignment set to 0 using align_board_pitch
> 
> I think here is the issue. Plane on the bench is NOT automatically a AoA=0 unless specifically designed that way by the Manufacturer. If I do that with the AR Wing classic it will climb at 2m/s in level flight. My Bushwacker plane (the only one with landing gear) has a 15° AoA whan on the ground. This won't work. We don't have AoA sensors anyway and the pitch angle is NOT the AoA.

I did say wing AoA = 0,. That means you have to support the plane so that the wing chord line is level. Not always easy to do depending on the shape of the wing (symmetric chord, highly tapered, washout etc) but that is the only reference you have when setting these things.

**Comment by b14ckyy** [comment]
Agree. Would work on some planes indeed. But as you said it is by far not possible on all planes. 
So imho the best compromise will be to leave it as it was for years now (at least keep the option) and take level flight at constant altitude on cruise speed as reference for a 0 Pitch angle. This helps to better judge for irregularities in navigation modes and gives a very good reference in User flight modes.

**Comment by avsaase** [comment]
Find the bug:
https://github.com/iNavFlight/inav/blob/2429764a00478704dba45807cbfde692a33fd9a6/src/main/flight/pid.c#L613-L644

**Comment by fernandodlc** [comment]
I'm ultimately happy with whatever is decided. Just trying to contribute.

In the interests of constructive discussion though:
AoA is a measurement of deviation from a reference point in a 3d plane. The AoA the plane flies at might be 0 or it might be another value but IMO they are 2 different things and the cruise AoA should be decoupled from the reference plane.

To take an example ad abusrdum: A ft nutball "cruises" at a very extreme AoA (Maybe 20-30 degrees). I think most people would not consider that attitude to be "level". In this example I would argue that it is obvious that cruise AoA and the reference plane are different.

As I put in the original request, conventional wisdom is that 0 degrees AoA is usually defined off the fuselage though it does seem a bit of a convention rather than a rule. For our practical purposes and intuitively it would make sense that the fc shelf defines that plane for our purposes as well as being the easiest to build for and manage.

**Pull request merged**
