### PR TITLE
Logo change in README.md

### PR DESCRIPTION
**Pull request by skaman82**

### CODE REVIEW

**Comment by martinbudden** [comment]
Nice Logo!

**Comment by skaman82** [comment]
Thanks :)

**Comment by skaman82** [comment]
@martinbudden as i redesigned the CF Configurator from the ground up last year I never imagined that I would end up with making three different configurators – that will be a big fun to maintain 💃 

bildschirmfoto 2016-06-14 um 19 40 10

**Comment by Linjieqiang** [comment]
@skaman82 So cool~!

**Comment by martinbudden** [comment]
I think I like the betaflight logo best. It goes well with my Fossils Stuff yellow and black gravity frame
gravityweightwithbattery

**Pull request merged**
