### PR TITLE
rewrite of variable table for CLImd

### PR DESCRIPTION
**Pull request by oleost**
Left out everything except variable name, default value and description.

Still some improvements that can be done later on, like linking varables to where one can find more infomation.

This pull request is towards master because this rewrite is based of master 1.5.1.
Development and other branches will need adjust they updated cli.md towards this.

### CODE REVIEW

**Comment by stronnag** [comment]
The mag_declination explanation is missing detail (an inherited bug) the example should be
````
 For example, -6deg 37min = -637 for Japan
````

**Comment by oleost** [comment]
Good catch, fixed.

**Comment by digitalentity** [comment]
I think we can merge it.

**Comment by oleost** [comment]
I see I missed pitot*

Where does go in the list?

**Pull request merged**
