### PR TITLE
Add SPRACINGF4EVO target

### PR DESCRIPTION
**Pull request by digitalentity**
Per #1641
- [x] Board boots, sensors are detected
- [x] Board connects to Configurator
- [x] UARTs work
- [x] PWM in/out works
- [x] LEDSTRIP
- [x] SD-card

### CODE REVIEW

**Comment by digitalentity** [comment]
Merged initial effort by @adtinnis

**Comment by Merewether** [comment]
I have cloned this branch and have tested it for use on fixed wing aircraft. Unfortunately, neither the motors or the servos get assignments in the resource list. I have verified my setup by testing the Quad X mixer where all the ports function properly. Problem is seen in each of the tested modes below:
Flying Wing
Airplane
Custom Airplane

**Comment by digitalentity** [comment]
@Merewether great! Thanks for testing. I know where the bug is and will fix it soon. In the meanwhile can you test PPM in/UARTS?

**Comment by digitalentity** [comment]
For a plane motor will be available on outputs 7 & 8; servos on output 1-6

**Comment by Merewether** [comment]
My setup tested PPM from a TBS CROSSFIRE micro. Will change over to SBUS and try again later today.

**Comment by Merewether** [comment]
Servos and motors are now properly mapped to the connector. I can spin the motors from the motors page of the configurator but they do not spin when commanded by my TX. I see the receiver sending the throttle value and I have forced an arm through the AUX1 on the modes page.

**Comment by digitalentity** [comment]
@Merewether please make sure that all pre-arming checks in "Configurator" first page are green.

**Comment by Merewether** [comment]
pre-arming checks are all green. Still no motor movement unless controlled from motors page of configurator. Also tried pass-through mode without success. Tried an mmix but that did not work either.

**Comment by Merewether** [comment]
SBUS works, all channels in the receiver page move appropriately. GPS and TBS Crossfire are on my list to do.

**Comment by Merewether** [comment]
UBLOX Micro M8N GPS with HMC5883L compass module works.

**Comment by Merewether** [comment]
TBS Crossfire works from TX to FC. Unable to get telemetry back from FC. TX line of UART 2 has no activity and is at an invalid low state.

**Comment by digitalentity** [comment]
@Merewether please test arming again now. I've tested CRSF telemetry, arming and motor outputs - all work. Also note that CRSF telemetry will only output data if the SerialRX protocol is set to Crossfire (CRSF).

**Comment by Merewether** [comment]
Not sure what I am doing wrong but I still cannot arm the motor. All the checks are green on the start page and I have a arm mode connected to by AUX 1 switch. I went back to Cleanflight to verify and arming works fine there. One thing I noticed is that after I try and arm, I cannot see the modes page anymore. Just sits there waiting for data.

**Comment by Merewether** [comment]
Playing around with it I finally got the motor to arm. Not only do I need the aux switch, I also need the zero throttle and full right yaw all at the same time. And voila! Not sure what bit is not being set or cleared but the motor is arming correctly now on subsequent cold boots.

**Comment by digitalentity** [comment]
@Merewether most likely your zero throttle is near 1100 value - if it's 1100 or above the board won't arm. While doing arming by sticks you pushed the throttle below 1100 and now board correctly detects low throttle.

**Comment by Merewether** [comment]
Nope. Receiver reports minimum throttle of 988. It was definitely related to a yank on the yaw at the minimum throttle.

**Comment by digitalentity** [comment]
Yank of the yaw doesn't survive board reboot. It's something external to the board.

**Comment by Merewether** [comment]
I wish I could tell you that I am doing something wrong with arming the motors. I have been able to repeat the problem multiple times (although rarely) after completely erasing the configuration data and loading CleanFlight. Once I re-flash INAV, a measurable percentage of the time (2 out of 10) I needed to move the yaw to the far right before the motor would arm. I don't think this is anything that would halt the release since there is a work around if, or when, it shows up again.

**Comment by Merewether** [comment]
I am not sure if this issue is related to this board since it is the only controller I have, but the "full chip erase" option for the firmware flasher hangs in the erase phase.

**Comment by digitalentity** [comment]
>I am not sure if this issue is related to this board since it is the only controller I have, but the "full chip erase" option for the firmware flasher hangs in the erase phase.
This is a known Configurator issue - flash erase timeouts.

> I don't think this is anything that would halt the release since there is a work around if, or when, it shows up again.
I agree - it's probably specific to one setup or flashing INAV over Clean/Betaflight without complete erase.

**Comment by digitalentity** [comment]
I'm merging this - the board in general is functional. If we found bugs - we'll fix them later.

**Comment by matoy** [comment]
Hi,
it seems that "led" CLI commands are not accepted (i have enabled the feature, saved and rebooted)
it's not working either in the configurator: impossible to "wire" leds.

ppm receiver seems to be working fine.

**Comment by digitalentity** [comment]
@matoy it does work already

**Comment by matoy** [comment]
@digitalentity : are you sure? why can't i set LED in the configurator nor in CLI?

# led 0 0,0::CB:2
Unknown command, try 'help'

thank you

**Comment by digitalentity** [comment]
@matoy the build you have probably doesn't have support for LEDs yet. Only introduced yesterday:
image

**Comment by matoy** [comment]
ok you're right; it's ok after compilation with last code in dev branch.
thanks.

**Pull request merged**
