### PR TITLE
Dzikuvx fix crsf branch

### PR DESCRIPTION
**Pull request by DzikuVx**
Replaces #6074 and as #6074 has based on 2.5.2 instead of master

### CODE REVIEW

**Comment by expipiplus1** [comment]
Great to see this merged finally! 

@OptimusTi, this was based on my patch here, right https://github.com/iNavFlight/inav/pull/5098? Would anyone object to me putting my name in the AUTHORS file?

**Comment by OptimusTi** [comment]
Hello @expipiplus1 this PR was based on the ls2 tweaks by @atomiclama. Go for it! It's your baby!

**Comment by 0crap** [comment]
@DzikuVx Just a question to make sure it's not overlooked.
Is the STATS screen showing a meaningful min value for CRSF RSSI or LQ?

I'm still using an old dev CRSF test build which always shows RSSI = 0%
This is of course because "normal" RSSI is switched off and I'm using CRSF.
If you use CRSF this stats value needs to reflect that as well.

Just a heads up, in case it's overlooked,
Thx!

Screenshot from my old dev CRSF test build.
(
CRSF stats screen
I did not test this PR yet.)

**Comment by OptimusTi** [comment]
@0crap Hello, I reinstated the inav solution for for showing crsf RSSI in this PR. Both ways of showing RSSI should be good. Of course, the stats screen is going to show the regular inav way in %.

image

**Pull request merged**
