### PR TITLE
New target: RCEXPLORERF3

### PR DESCRIPTION
**Pull request by lkaino**
F3FC board from RCExplorer.se.

Supports both tricopter integrated and standalone boards.

### CODE REVIEW

**Comment by lkaino** [comment]
The target is under testing in #438, please hold on merging before it is properly tested.

**Comment by lkaino** [comment]
This PR is now tested and ready to be merged. Any further fixes can be done in separate PRs.

(Taking that I didn't screw up the rebase.)

**Comment by digitalentity** [comment]
@lkaino another rebase is required. Latest changes to master broke possibility to merge this.

**Comment by lkaino** [comment]
@digitalentity okay will do a rebase

**Comment by lkaino** [comment]
@digitalentity Do you want to keep only selected targets in Travis files? Should I remove this target from the list?

**Comment by digitalentity** [comment]
@lkaino no, you can keep it

**Comment by lkaino** [comment]
@digitalentity rebased.

**Pull request merged**
