### PR TITLE
Add target 'AOCODARCF4'.

### PR DESCRIPTION
**Pull request by dlt2018**
hello,please help to add new target 'AOCODARCF4'.
It has been tested and validated. it can upload it officially!
thanks for your work!

### CODE REVIEW

**Review by JulioCesarMatias — APPROVED** [review]
A guy I know gave up on buying this FC because iNav doesn't support it yet. So thank you for this feat. LGTM!

**Comment by dlt2018** [comment]
hello julio,

it is very important to add a new F405 target in INAV.
i have send Pawel a F4 board by post,
could you give me some help!

hello pawal,
the tracking number is UG553726028YP.
do  i need submit a new PR for it.


***@***.***
 
From: Julio Cesar Matias
Date: 2022-06-27 05:42
To: iNavFlight/inav
CC: MarkTan; Author
Subject: Re: [iNavFlight/inav] Add target 'AOCODARCF4'. (PR #8156)
@JulioCesarMatias approved this pull request.
A guy I know gave up on buying this FC because iNav doesn't support it yet. So thank you for this feat. LGTM!

**Comment by JulioCesarMatias** [comment]
I don't have permissions to merge PR's here... The most I can do is just approve. Only Pawel can merge this PR. Sorry

**Comment by MrD-RC** [comment]
Build failing due to an error on the MAMBAH743 target. This has since been fixed, so an update from the master branch should fix this error.

**Comment by DzikuVx** [comment]
I see it was replaced by #8416 closing

**Comment by dlt2018** [comment]
use this PR. https://github.com/iNavFlight/inav/pull/8416

**Comment by dlt2018** [comment]
use this PR.  https://github.com/iNavFlight/inav/pull/8416
close  #8156

**Pull request closed without merging**
