### PR TITLE
Adding Revolt target

### PR DESCRIPTION
**Pull request by alenl2**
Cherry-pick from Betaflight to support Revolt and AirbotF4. Tested only with Revolt.

### CODE REVIEW

**Comment by oleost** [comment]
Hi.

**Comment by oleost** [comment]
Hi

AirbotF4 is already supported https://github.com/iNavFlight/inav/tree/master/src/main/target/AIRBOTF4

**Comment by alenl2** [comment]
Did not notice that it had it's own folder. I amended the cherry pick to only include the REVOLT.

**Comment by digitalentity** [comment]
Does REVOLT support servos and/or I2C? Is it suitable for navigation at all?

**Comment by alenl2** [comment]
I think it's not the best board for navigation. I had an incident on my quad witch broke one of the motor outputs so i decided to use it on my wing to recycle  it :D. I needed to create a custom wiring harness for servo outputs. As for the I2C i'm not sure of the pinout. You can always solder directly to the chip.

**Comment by DzikuVx** [comment]
@alenl2 could you rebase against development and resolve conflicts?

**Comment by digitalentity** [comment]
No activity for two months now. I guess this is no longer relevant.

**Pull request closed without merging**
