### PR TITLE
Update Battery.md

### PR DESCRIPTION
**Pull request by breadoven**

### CODE REVIEW

**Comment by shellixyz** [comment]
Nav launch mode shouldn't make a difference. What makes you think it is ?

**Comment by breadoven** [comment]
I could't get it to display anything until I used Nav Launch, explained in https://github.com/iNavFlight/inav/issues/5969. I took out the code mentioned in 5969 and compiled my own version and now I'm getting numbers displayed without using Nav Launch. Didn't make much sense that it would require Nav Launch to work so maybe I've just hit on a bodge solution. What else do you think might be causing this problem if it's not Nav Launch ?

**Comment by shellixyz** [comment]
Sorry I saw your issue but didn't have time to answer at the moment and later completely forgot. I wrote this part but honestly like that I have no clue. It shouldn't but perhaps there is something going on between nav launch and this code. I'm always using nav launch. I will do some tests

**Comment by shellixyz** [comment]
My bad. I checked the code and it makes perfect sense why it is only working when the nav launch feature is enabled. Will need to be fixed. I'm closing your PR because this is a bug which needs to be fixed.

**Pull request closed without merging**
