### PR TITLE
add target GRAVITYF7 (FLMD)

### PR DESCRIPTION
**Pull request by cvetaevvitaliy**
Hi ! Add please target: GRAVITYF7
Manufacturer: FLMD

Link: www.flymod.net

Thank

### CODE REVIEW

**Comment by giacomo892** [comment]
Kindly take a look here:
https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by cvetaevvitaliy** [comment]
Снимок экрана 2020-04-11 в 19 02 26
Снимок экрана 2020-04-11 в 19 00 46

Снимок экрана 2020-04-11 в 19 05 30

**Comment by cvetaevvitaliy** [comment]
Flash works!
I solder chip and recheck 
Снимок экрана 2020-04-11 в 19 29 57

**Comment by VitaliyNimych** [comment]
@giacomo892 where can i send FC samples ? 
BF add target
our customers need inav support

**Comment by digitalentity** [comment]
@VitaliyNimych please reach out to coredev@inavflight.com, we'll loop in other developers and we'll arrange adding this target.

**Pull request closed without merging**
