### PR TITLE
AltHold performance improvements

### PR DESCRIPTION
**Pull request by digitalentity**
1. Give more authority to current defaults for VEL PID
1. Smoother climb/descent control in AltHold mode regardless of deadband size

### CODE REVIEW

**Comment by rb1205** [comment]
Interesting. I'll test this in the next weekend.

**Comment by stronnag** [comment]
Flight tested (patched into master). No adverse observations.

**Comment by digitalentity** [comment]
Great! @stronnag I'm worried that this patch may affect auto-disarm on landing - I believe we should make disarming more conservative...

**Comment by stronnag** [comment]
No problems in that respect. I felt there was a slight loss in altitude when manual RTH was engaged; I need to check the logs again, and retest, a bit closer in so it's visually obvious.

**Comment by rb1205** [comment]
Tested, got noticeable improvements in the form of less drop when tilting during althold. Didn't notice any difference in auto-landing and auto-disarming.

**Pull request merged**
