### PR TITLE
Port receiver-driven telemetry frame rate for F.PORT from betaflight

### PR DESCRIPTION
**Pull request by CapnBry**
I'm running iNav 2.1.0 and had issues with getting "Sensor Lost" after "Sensor Lost" and very slowly updating telemetry on my Taranis Q X7 after adding a GPS to my iNav build. Betaflight has already implemented receiver-driven telemetry frame rate for F.PORT protocol so I just ported their changes over. This works with FrSky R-XSR F.PORT firmware 180615 and above, although the old send-two-frames-and-wait method should work still as well with older receiver firmwares. Tested with firmware 180921 and after these changes, I get full telemetry update rate back and have had zero "Sensor Lost" events where before I'd have them every 10 seconds, if telemetry was updating at all.

One very important thing to note is that the [sbusChannelsDecode()](https://github.com/iNavFlight/inav/compare/master...CapnBry:master#diff-cde9323f4aeb96861ec23ea358818bbeR280) call from betaflight **sets** result but iNav's version used to **or** the result in. This means that `fportFrameStatus()` use to return the RX_FRAME_PENDING bit even when a complete frame has been received. I think the way I have it is the right value to return, but you may know better if something expects RX_FRAME_PENDING or if the RX_FRAME_FAILSAFE bit might be cleared inadvertently (although that would mean it was a failsafe decode followed by a non-failsafe condition which would still be non-failsafe, right?).

EDIT: Just realized that my repository wasn't up to date before I made the changes, but the patch applies against current development branch with no changes. I can resubmit if needed.

Version: iNav 2.1.0
Target: OMNIBUSF4PRO (although all targets are affected)
Receiver: FrSky R-XSR
Receiver Protocol: F.PORT

### CODE REVIEW

**Comment by digitalentity** [comment]
Please rebase to `development` branch and we can review and discuss

**Comment by CapnBry** [comment]
I've changed the base branch to `development` in the PR and github is saying that it can be automatically merged to inav/development. My source branch apparently can't be changed without creating a new PR, but I don't think that's needed. However, I can close this one and open a new one if you prefer.

**Comment by CopterFail** [comment]
Please fix this bug, I can confirm this problem also with x4r and r9mm receivers.

**Comment by teckel12** [comment]
@CopterFail I have x4r with no such problems. I know heat can cause the x4r to lose telemetry sensors. But when cool, I never lose sensors with a x4r, so not a bug.

**Comment by CopterFail** [comment]
opentx (I run 2.2.3 on my taranis) seems to have a different opinon. I often get the “sensor lost“ voice message for both of my f-port modded x4r. Only one firmware version for f-port is available. iNav versions are 2.0 and 2.1. opentx seems to check the frequency of the telemetry. The sensor is not really lost, but the receive frequency drops and will be restored.

**Comment by teckel12** [comment]
@CopterFail Actually, for my x4r I'm running S.Bus/S.Port. So it very well could be an FPort bug. Never was able to get FPort working due to running F4. Now I'm going with F7 and CSFR so FPort is too little too late for me.

**Comment by CopterFail** [comment]
F.Port is the topic. It is connected in the same way as s.port, but faster and contains s.bus information. For safety reasons I do not use software serial. To connect the x4r to an f4 fc, I've done the uninvert patch to the x4r.

**Comment by CapnBry** [comment]
This fix will not help the X4R unfortunately. Receiver-driven telemetry has to be implemented on the receiver firmware (it has to notify when the telemetry frames are dequed and buffer space is available to hold new ones) and FrSky has only released updated firmware for the R-XSR and some of the R9 models. I don't have a comprehensive list because the FrSky downloads pages for the firmware don't explicitly list the Sensor Lost error as a fix in any of them but the R-XSR.

**Comment by CapnBry** [comment]
I've been flying on this code for almost two hours of flight time now and it doesn't fully eliminate the issue. It seems like if it works it works and there's a continuous stream of data. opentx displays asterisks that blink off then back on quickly. If it isn't working then you only get asterisks blinking on every so often, or in a stream down the list.  RSSI and RxBt always seem to update regardless of if the other telemetry items do.

I'm actually not sure if it is better with this patch from Betaflight or not. The good news is that it stays working if it is, so I can cycle the receiver power or transmitter power if it isn't working and most likely it will on the next attempt.

**Review by fiam — APPROVED** [review]

**Pull request merged**
