### PR TITLE
Sonar - refactor the code to use detection and configuration like all other sensors

### PR DESCRIPTION
**Pull request by digitalentity**
Per #1090
Implement `rangefinder_hardware` setting
Deprecate `feature SONAR`
Change sonar detection code to behave like all other sensors

### CODE REVIEW

**Comment by martinbudden** [comment]
Looking good so far.

**Comment by digitalentity** [comment]
This is going to be a first PR out or 2 or 3 to make sonar functional. 
This one is intended to refactor sonar handling, deprecate the `SONAR` feature.

**Comment by digitalentity** [comment]
BTW, I really like the PGs - cool feature allows me to look into other settings without the need to pass along a zillion of pointers.

**Comment by digitalentity** [comment]
I think this can be merged to avoid further rebases. Sonar hardware will be forced to `NONE` so it shouldn't create any issues.

**Pull request merged**
