### PR TITLE
[Fixed-Wing] PIDFF Attenuation using the AirSpeed

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
If someone can test it, I appreciate it. The math seems correct to me. Use `set tpa_airspeed_attenuation = 1500` in CLI to enable. The .HEX file for your FC can be downloaded here >> https://github.com/iNavFlight/inav/actions/runs/1641734916

Key parameters are:

`tpa_airspeed_attenuation` : Calculate PIDFF Attenuation based on AirSpeed (0 is disabled) ~ 1500 is a recommended value (Using the defaults values in "tpa_airspeed_min" and "tpa_airspeed_max" ). Range : 0 ~ 3000 cm/s.

`tpa_airspeed_min` : Should be set to 20% higher than level flight stall speed to calculate the PIDFF Attenuation based on AirSpeed. Range : 500 ~ 10000 cm/s.

`tpa_airspeed_max` : Maximum airspeed demanded to calculate the PIDFF Attenuation based on AirSpeed. Range : 500 ~ 10000 cm/s.

### CODE REVIEW

**Comment by iromadm** [comment]
Awesome news! please keep going implementing Airspeed support!

**Comment by stuwe911** [comment]
I'm really in need of PIFF working airspeed based and not throttle setting like anyone doing mountain dives with power off but wants stabilization in horizontal flight. please keep working on this! happy to test if you need one. thanks

**Comment by JulioCesarMatias** [comment]
> I'm really in need of PIFF working airspeed based and not throttle setting like anyone doing mountain dives with power off but wants stabilization in horizontal flight. please keep working on this! happy to test if you need one. thanks

This algorithm does not control the aircraft acceleration, but the PIDFF attenuation. PIDFF will be slackened based on fuselage speed. The faster, the looser the PIDFF gains

**Comment by stuwe911** [comment]
Thanks Julio,
I still think that your fix might solve my problem. I fly with a very high P and I for stiffness like an UMX plane. cruising with about 70kmh but when i dive down a mountain with 0 throttle then i reach 140kmh. Ideally the stabilization is the same. Today I have to tune the plane for 140kmh zero throttle just before oscillation starts. But when i then cruise with 70kmh i feel almost nothing of the stabilization effect. Played around with TPA settings but that does not works since before the breakpoint the stabb increases. Do you think your fix could be the solution i'm looking for? the faster the fuselage travels (gps speed) the lower the stabb effect? thanks!

**Comment by JulioCesarMatias** [comment]
> Thanks Julio,
> I still think that your fix might solve my problem. I fly with a very high P and I for stiffness like an UMX plane. cruising with about 70kmh but when i dive down a mountain with 0 throttle then i reach 140kmh. Ideally the stabilization is the same. Today I have to tune the plane for 140kmh zero throttle just before oscillation starts. But when i then cruise with 70kmh i feel almost nothing of the stabilization effect. Played around with TPA settings but that does not works since before the breakpoint the stabb increases. Do you think your fix could be the solution i'm looking for? the faster the fuselage travels (gps speed) the lower the stabb effect? thanks!


For high speeds, I don't know if it will work well. This algorithm is limited to speeds of 79.2km/h. I believe if I raise it maybe it won't look good

**Comment by stuwe911** [comment]
Thanks for the clarification. In that case it will not work. why the limitation?

**Comment by JulioCesarMatias** [comment]
> Thanks for the clarification. In that case it will not work. why the limitation?


If you're interested, you can test it at high speeds, I don't guarantee anything. By increasing the maximum supported speed, you will have to recalculate the PIDF Attenuation Scale.

**Comment by b14ckyy** [comment]
@JulioCesarMatias Shouldn't we reconsider this now? Even if your new AHRS does not make it into 6.0, we still have now a working wind speed estimator and a good virtual pitot tube. So shouldn't this now be applicable?

**Comment by trailx** [comment]
@JulioCesarMatias , I know this is a bit old at this point, but is there any reason to believe it wouldn't work now?  Is there a way to rebuild a .HEX file for testing again?  I'm willing to do testing on this.

**Comment by JulioCesarMatias** [comment]
> @JulioCesarMatias , I know this is a bit old at this point, but is there any reason to believe it wouldn't work now? Is there a way to rebuild a .HEX file for testing again? I'm willing to do testing on this.

Hi, I believe some developer can help you with this feature. Unfortunately I won't be able to help you, I'm no longer part of the development team.

**Pull request closed without merging**
