### PR TITLE
Switch on using parameter groups in CLI

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by martinbudden** [comment]
@digitalentity , @stronnag 

The vast majority of the configuration data has been converted to parameter groups, so I've switched it on in the CLI. There's still a few things left to do (OSD, telemetry and a few others). Also the CLI `diff` command is not fully working. And there are one or two other things to fix up (a few things have been disable in CMS, for example). But it's mostly there now and I'd certainly welcome some bench testing.

**Comment by digitalentity** [comment]
@martinbudden thanks!

**Comment by stronnag** [comment]
@martinbudden I started documenting the `dump` differences between one device on 1.5.1 and 1.6. It's a pretty big list (which I'm not yet through). 

Is it worth me doing this task now, or should I wait a bit? 

Please let me know if this degree of analysis is useful at this stage.

**Comment by martinbudden** [comment]
The `dump` command should be working fine, although missing a few items. Note that the order of output has changed, so that it's probably easiest if you sort both the outputs before you compare. If you do a sort, I'm not expecting there to be a large number of differences - if there are report back and I will look into it. So there is no reason you shouldn't look into it now.

**Comment by stronnag** [comment]
Ok. I'd already worked out that sort was necessary to make sense.

**Comment by stronnag** [comment]
@martinbudden, here's the list. Some of this is obviously WP (especially the 'Missing' items).

**Method**

Flashed a NAZE board with 1.5.1 and applied a pre-PG diff file. saved the resulting dump as nav_naze_1.5.txt

Flashed the same NAZE board with 1.6.0 and applied the same pre-PG diff file. saved the resulting dump as nav_naze_1.6.txt

Attempted to graphically diff (meld) the two files. Due to re-positioning of  sections in the two diffs, this was quite difficult, and I ended up sorting both files to have a chance of finding the differences. So the
list is alphabetical, as it's the only way I could evaluate the changes.

Some of these may be deliberate changes of course, or not yet implemented (and 'not set' may be missing or default). It's also dependent on what extant defaults I had set. I'll repeat this on other machine dump once the WIP are complete, which will weed out more of the defaults.

**Results**

Features: The following features do not 'take' in 1.6.0
````
SOFTSERIAL
GPS
TELEMETRY
BLACKBOX
AIRMODE
````

Modes (aux): No non-default mode (aux) settings were set in 1.6.0.

Beeper: The `beeper -ON_USB` was not set in 1.6.0.

Serial. The softserial settings were not present in 1.6.0 (consequence of feature failure).

set 3d* issues (`3d_deadband_high` and others ('3d*') appears twice in 1.6, `3d_deadband_throttle` has wrong value.

`acc_soft_lpf_hz` becomes `acc_lpf_hz`, `acc_task_frequency` missing.

Missing
````
acc_task_frequency
alt_hold_deadband
async_mode
attitude_task_frequency
battery_capacity
blackbox_device
blackbox_rate_denom
blackbox_rate_num
current_meter_offset
current_meter_scale
current_meter_type
deadband
default_rate_profile
````

Unset (i.e. default)
````
d_pitch
d_roll
dterm_lpf_hz
````
Missing
````
failsafe_delay
failsafe_kill_switch
failsafe_off_delay
failsafe_procedure
failsafe_recovery_delay
failsafe_throttle
failsafe_throttle_low_delay

flaperon_throw_inverted
flaperon_throw_offset
frsky_coordinates_format
frsky_default_lattitude
frsky_default_longitude
frsky_unit
frsky_vfas_cell_voltage
frsky_vfas_precision
fw_iterm_throw_limit
````

Not Set or missing

````
hott_alarm_sound_interval
i2c_overclock
i_level

inav_accz_unarmedcal
inav_baro_epv
inav_gps_delay
inav_gps_min_sats
inav_max_eph_epv
inav_use_gps_velned
inav_w_acc_bias
inav_w_xy_gps_p
inav_w_xy_gps_v
inav_w_xy_res_v
inav_w_z_baro_p
inav_w_z_gps_p
inav_w_z_gps_v
inav_w_z_res_v
input_filtering_mode
i_pitch
i_roll

i_yaw
````

Missing

````
mode_range_logic_operator
multiwii_current_meter_output
nav_disarm_on_landing
nav_emerg_landing_speed
nav_extra_arming_safety
nav_fw_bank_angle
nav_fw_climb_angle
nav_fw_cruise_thr
nav_fw_dive_angle
nav_fw_launch_accel
nav_fw_launch_climb_angle
nav_fw_launch_detect_time
nav_fw_launch_motor_delay
nav_fw_launch_thr
nav_fw_launch_timeout
nav_fw_launch_velocity
nav_fw_loiter_radius
nav_fw_max_thr
nav_fw_min_thr
nav_fw_pitch2thr
nav_fw_roll2pitch
nav_landing_speed
nav_land_slowdown_maxalt
nav_land_slowdown_minalt
nav_manual_climb_rate
nav_manual_speed
nav_max_climb_rate
nav_max_speed
nav_mc_auto_disarm_delay
nav_mc_bank_angle
nav_mc_hover_thr
nav_min_rth_distance
````

Not set `nav_pos_d`

Missing

````
nav_position_timeout
nav_rth_altitude
nav_rth_alt_mode
nav_rth_climb_first
nav_rth_tail_first
nav_use_midthr_for_althold
nav_user_control_mode

nav_wp_radius
pos_hold_deadband
````

Not set

````
p_pitch
p_roll
p_yaw
````

Missing
````
servo_lowpass_enable
servo_lowpass_freq
telemetry_inversion
telemetry_switch
throttle_tilt_comp_str
tri_unarmed_servo
vbat_max_cell_voltage
vbat_min_cell_voltage
vbat_scale
vbat_warning_cell_voltage
yaw_deadband
````

Duplicated
```
yaw_jump_prevention_limit
yaw_motor_direction
```

In summary, great progress.

**Comment by martinbudden** [comment]
@stronnag , thanks for testing. I've fixed a few, you might want to re-test.

I'm done for today - I'll do some more over the next few days.

**Comment by stronnag** [comment]
I'll redo the tests in the next few days, after you've had a chance to hit some more of the TBDs.

**Pull request merged**
