### PR TITLE
CLI WP

### PR DESCRIPTION
**Pull request by hali9**
At the moment there is no way to save the mission in inav or inav-configurator in a simple way like other settings. Sometimes it is also necessary to create a mission from another program or on the basis of a black box log.
This PR makes this possible.

### CODE REVIEW

**Comment by DzikuVx** [comment]
Nice @hali9 

But I can already say that you have to disable this for all F3 targets if you want to fit it

**Comment by stronnag** [comment]
What is the `wp load` use case? Once you hit save or exit (exit the CLI in order to arm) the WPs in volatile RAM are lost.

**Comment by hali9** [comment]
@DzikuVx it fit, but I will disable it on F3.
@stronnag `wp load` loads WPs from non volatile memory, then You can type `wp` to list it or use diff or dump to copy it and save to file just like other settings.
To restore just paste in WPs (can be with other settings) in CLI and type `wp save` to save WPs to non volatile memory.
Normal `save` not saves WPs to non volatile memory must use `wp save`.
But `wp save` save WPs and also all settings so no need to use save `save` when using `wp save`.

**Review by shellixyz — APPROVED** [review]
LGTM

**Comment by OlivierC-FR** [comment]
Help ! :)

```
wp reset
wp 1 1 459965100 59989293 400 0 0
wp 2 1 459916380 59984627 500 0 165
wp save

Parse error
```

**Comment by stronnag** [comment]
In the CLI, wp are 0 based.

**Comment by stronnag** [comment]
and will 4 or 5m really clear the trees?

**Comment by OlivierC-FR** [comment]
Ok thanks Im going to try !
That's not to actually set a proper mission, it's to simulate nearby aircrafts, from the LoRa modem, for the iNav radar.

**Comment by OlivierC-FR** [comment]
Ok it worked, it actually needed  : wp 0 1 ...

**Comment by stronnag** [comment]
"0 based ..." :)
image

**Pull request merged**
