### PR TITLE
Initial cut on RTH sanity checking

### PR DESCRIPTION
**Pull request by digitalentity**
Introducing a new parameter - `nav_rth_abort_threshold` measured in [cm]. If during an RTH (manual, failsafe or WP) we get further away from home by this much - abort RTH and do an emergency landing.

Done per https://github.com/iNavFlight/inav/issues/62#issuecomment-270325236

### CODE REVIEW

**Comment by DzikuVx** [comment]
OK, makes sense. If at any point UAV starts to go away from Home, emergency landing will be triggered.

**Comment by digitalentity** [comment]
I've extended sanity checking logic to initial climb and landing as well. If something wrong happens during any phase of RTH - we'll land the machine.

**Comment by oleost** [comment]
Remember airplanes needs time to both climb and turn before heading home.

**Comment by digitalentity** [comment]
@oleost that's why I start the check only when climb is finished. This is not entirely safe because turn may take more than 150m radius, but currently I can't think of anything that's both safe and bullet-proof. 

Remember, airplane might have level drift in some cases which may prevent it from turning to home, our logic must accoung for that.

**Comment by martinbudden** [comment]
@digitalentity , what's the status on this PR?

**Comment by digitalentity** [comment]
@martinbudden I'm not sure. It may be unsafe for airplanes if they will require more than 150m radius to make a RTH turn.

**Comment by digitalentity** [comment]
Probably for airplane we should also monitor heading to home as initial check. If error is over 90 deg and doesn't increase - we're in trouble.

**Comment by martinbudden** [comment]
Do you want to mark it for 1.7 then? Or perhaps only allow it for multirotors at the moment?

**Comment by oleost** [comment]
Make default value of 'nav_rth_abort_threshold' around 500 meters ( 50 000cm ) and it should be safe for anyone?

**Comment by digitalentity** [comment]
@oleost Good temporary solution. If your airplane can't turn in 500m something is terribly wrong anyway

**Comment by digitalentity** [comment]
This needs to be carefully tested - it's somewhat invasive PR...

**Comment by WaspFPV** [comment]
Would this also prevent flyaway by miscalibrated compass? I had a flyaway last week on a F3 EVO because compass was too close to powerlines. Blackbox showed values changing with throttle. Meanwhile I changed to external compass and it works perfectly now.

**Comment by digitalentity** [comment]
@andre92 only during RTH. If during RTH your quad will get even farther away from home by `nav_rth_abort_threshold` cm - RTH will be aborted and machine will land.

**Comment by stronnag** [comment]
So we would need geofence as well please. I appreciate this is under consideration and would presumably be a natural extension of this work?

**Comment by digitalentity** [comment]
Geo-fencing will be part of new failsafe subsystem. We'll have several triggers for failsafe (breaching geo-fence will be one of those).

**Pull request merged**
