### PR TITLE
Timer DMA burst

### PR DESCRIPTION
**Pull request by shirase**
Some FC, like SPEEDYBEEF405V3 do not have enouth DMA channels for timers. And some motors not works on DSHOT.
This PR fix it, by using dma burst mode. It need only one DMA channel for four timer channels.

### CODE REVIEW

**Comment by DzikuVx** [comment]
Wow! Amazing! Let me test in a next few day! Thank you very much @shirase

**Comment by shirase** [comment]
It must work on all F4 targets. 
Activated by: `#define USE_DSHOT_DMAR`

**Comment by mmosca** [comment]
This will certainly decrease the number of users asking about this in the future :)

**Comment by Jetrell** [comment]
> It must work on all F4 targets. Activated by: `#define USE_DSHOT_DMAR`

Very nice. I assume this should be a good fix for the Matek F405miniTE as well ?

**Comment by rmaia3d** [comment]
> > It must work on all F4 targets. Activated by: `#define USE_DSHOT_DMAR`
> 
> Very nice. I assume this should be a good fix for the Matek F405miniTE as well ?

I was going to ask the very same thing! :)

**Comment by shirase** [comment]
> Very nice. I assume this should be a good fix for the Matek F405miniTE as well ?
I do not have that board. Can someone test it?

**Comment by shirase** [comment]
Added HAL library implementation. Now it can be used for all targets. Need to be tested.

**Comment by DzikuVx** [comment]
Tested with SPDBF405V3 and regular MatekF722 and everything seems to work fine.. If something is broken, we will find out what is it later :)

**Comment by DzikuVx** [comment]
Thank you very much much @shirase

**Comment by MATEKSYS** [comment]
Thanks for adding DMAR support. Tested with MatekF405TE target,  S3 on TIM1_CH3N still doesn't work.
seems CH'N" support is a legacy bug .  With betaflight fw, TIM1_CH3N works fine with normal DMA2_ST6,  also works normal with DMA burst.

**Comment by rmaia3d** [comment]
As mentioned in #9276, this PR apparently broke DShot beeper or all targets. Reverting it, makes DShot beeper work again even in targets that don't use the DMA burst mode.

**Comment by shirase** [comment]
It works fine on DSHOT600. DSHOT300 - beeper not work. I will make fix.

**Comment by sensei-hacker** [comment]
Are there disadvantages to using this?
Is it okay to use it fairly liberally as needed, or are there drawbacks?

**Comment by shirase** [comment]
It can be used everywhere. But need tests for different boards. Do not enable if you do not have board for testing.

**Pull request merged**
