### PR TITLE
Use 2 bits for msp displayport font page

### PR DESCRIPTION
**Pull request by mmosca**
May allow for future 4 page fonts

### CODE REVIEW

**Comment by mmosca** [comment]
I may change the fontPage uint8_t array to attr uint8_t array and combine with the blink flag.

**Comment by RomanLut** [comment]
Blinking attribute handling can be removed from displayport_msp_osd.c completely.

Displayport_msp_osd does not support blinking attibute:
https://github.com/iNavFlight/inav/blob/1dc91058761816cc2427495e48f373393e62cf32/src/main/io/displayport_msp_osd.c#L376

Software blinking is used, blinking attibute is not applied to characters in display.c:
https://github.com/iNavFlight/inav/blob/1dc91058761816cc2427495e48f373393e62cf32/src/main/drivers/display.c#L49
https://github.com/iNavFlight/inav/blob/1dc91058761816cc2427495e48f373393e62cf32/src/main/drivers/display.c#L206
https://github.com/iNavFlight/inav/blob/1dc91058761816cc2427495e48f373393e62cf32/src/main/drivers/display.c#L66

So this code never executes:
https://github.com/iNavFlight/inav/blob/1dc91058761816cc2427495e48f373393e62cf32/src/main/io/displayport_msp_osd.c#L322

and can be removed unless you plan to implement **useDeviceBlink** option similar to BF.

**Comment by MrD-RC** [comment]
There's no need to remove blink. It is in the API. It should be handled as specified by the API.

**Comment by RomanLut** [comment]
Should be optional then, displayport_msp_use_device_blink is OFF by default in betaflight, I guess for a reason.

**Pull request merged**
