### PR TITLE
PCA9685 PWM driver support

### PR DESCRIPTION
**Pull request by DzikuVx**
Idea from #174 
Since mixed servo-motor support is currently very limited (either many motors and 2 servos or 2 motors and many servos), this pull request will introduce support I2C-to-PWM PCA9685 support that should solve this issue: when PCA9685 is connected, FC will drive motors and PCA9685 will drive servos. That mean, crazy configurations like 8 motors 16 servos will be possible. In theory.

Current state:
- dirty implementation on PCA9685 driver in place
- Throttle is passed to servo 0 as a proof that it is working
- compiles only on NAZE target

Next steps:
- improve PCA9685 detection
- change pwmInit when PCA9685 is in place not to initialize servos
- pass servo channels to PCA9685 when possible
- create abstraction layer for other I2C-to-PWM drivers (?)

### CODE REVIEW

**Comment by DzikuVx** [comment]
Some progress today:
- Real servo values are written to PCA9685, that mean, in theory it is flyable!

Todo:
- clean it up
- enable for other targets
- create task for syncing data with PCA9685

But, I've found some problems:

Writing new state every cycle for each servo is extremely time consuming and does not makes sense.
On Flip32/Naze32 trying to sync all servos every 2000us extends looptime to 3500us. Very, very bad...
Instead of that, desired pulse length values are written to temporary table and sent to PCA9685 at 50Hz update rate.
Also, because of resolution of PCA9685 internal counter of about 5us (12bits for 60Hz gives abot 4.8us per PCA9685 clock cycle), small changes are not written, since they would only clog the bandwidth and would not be represented on output.

Still, on my Flip32, even with those optimizations, looptime of 2000us is impossible to keep with 5 servos when there are many changes, like shaking of FC. 

But, looptimes above 2600us are fine. That means, fast looptime and PCA9685 does not come together. Perhaps `i2c_overclock=ON` would help, but I will check that later.

Another "challenge" is the fact, that ATM it is impossible to disable internal servo handling, and FC maps timer and pins for servo handling even when PCA9685 is present. Reason is trivial: pwmInit is executed well before i2c bus is initialized and one comment I've found in  the code prohibits me from changing that: 
`// pwmInit() needs to be called as soon as possible for ESC compatibility reasons`

@digitalentity @martinbudden @hydra what do you think? Any ideas?

**Comment by martinbudden** [comment]
@DzikuVx , I haven't had time to look at this fully, but will do so in the next few days and comment.

I can however confirm the `pwmInit` needs to be executed well before the i2c bus initialisation - I found this out when I was writing the code for the i2c based sonar rangefinder. From an initialisation point of view the problem is very similar to yours, since sonar could be on either the PWM pins or the i2c bus. I imagine there could be a way around this in the longer term, but for the moment we are stuck with this.

I'm also curious as to what sort of aircraft you will use this on - is it a tricopter, or something more exotic?

**Comment by DzikuVx** [comment]
@martinbudden in past there were few times when we were asked why one can not have 3 motors and 3 servos for example. This also includes servo_gimbal on airplane, or even ppm->pwm decoder (or SerialRx decoder). 
Sure, fixing that in pwmInit would be better, but still timer sharing between pins would make that not clean. And there is also issue of CC3D and for example #177 .
With external PWM driver all flyable both useful and not-so-much exotics would be available.

**Comment by digitalentity** [comment]
Servos are updated at 50Hz rate at most, we can schedule servo writes over multiple cycles. What do you think?

**Comment by hydra** [comment]
I'm not so sure about spending time on this, sure it's a nice tinkering with it but I don't see that many situations where this would be useful except for a one-off hobby project.

There are F3/F4 chips out there with more output pins and more timers.  It would likely make sense to just use one of them on a new board.  The price difference between a 48 and 64 pin STM cpu is small.  and would likely time up less board space than a 48 pin cpu and one of these chips.

See volume price differences between STM32F303CCT6 & STM32F303RCT6 and the volume price of the PCA9685.

Are you designing and building a board with one of these IC's?  If so why?

**Comment by digitalentity** [comment]
@hydra 
Almost everything for R/C enthusiasts is a hobby project. My intention is to give more choices for those who want more servos on their FCs. I.e. for an airplane with flaps and thrust vectoring you need at least 5 servo outputs therefore this setup is not possible on NAZE/CC3D boards.

For newer designs I would also recommend using STM32F303RC series chips.

**Comment by DzikuVx** [comment]
World does not end on 250 racer 😉

**Comment by DzikuVx** [comment]
Separate task was a good decision. Looptime 2000 is more stable now, even with 5 working servos.

To remember what still has to be done:
- abstraction layer
- naming unification
- probably LOW_L and LOW_H registries have to be written only once during initialization. That would reduce required I2C bandwidth by half and greatly improve performance

**Comment by hydra** [comment]
@digitalentity yes :wink: 

@DzikuVx Yes, world does not end on 250 racer for sure.  However, have you seen the price of an STM32F030?  Using an F030 is a far more flexible solution, you could connect an SPI bus to it and have it drive PWM outputs or do even more...  You could even make it pretend to be an PCA9685 :smile: 

http://www.digikey.es/product-detail/en/stmicroelectronics/STM32F030F4P6/497-14044-5-ND/4357517

< $1 in quantities of 100 or more.  ok, so yes you probably need an oscilator too.  I use these chips on the SP Racing Transponder board, they are very good.

**Comment by DzikuVx** [comment]
OK, I think I went as far as needed for first version and proof on concept. Maybe even two steps too far.

This is how it works:
1. PCA9685 is enabled on NAZE, CC3D and SPRF3 targets
1. If PCA9685 is detected on default I2C address (0x40) and feature **_PWM_SERVO_DRIVER**_ is enabled, servo output will be written to PCA9685 with frequency of 50Hz
1. All defined servos are written to external driver
1. Because how pwm_mapping is written, servo timers are still used and reserved. Maybe next step might fix this
1. If PCA9685 initialization will fail, no servos will be written to outputs at all

Not flight tested, only bench tested but looks like it is working. When I will finish my airplane, I will test it there. But bench tests are promising

**Comment by digitalentity** [comment]
@DzikuVx what about implementing asynchronous servo updates?
Make TASK_PWMDRIVER running at higher rate, i.e. 500Hz and only allow it to update some of the servos each cycle. This will require different implementation of PWM driver framework:
1. pwmDriverSetPulse will write to temporary table as usual
2. pwmDriverSync will be allowed to consume maximum of XXX microseconds (to be defined) and will keep in mind which servos has beed updated. For example 1-st cycle it will update servos 1,2,3, next cycle it will update 4,5, next cycle it will update 6,7,8 etc. 

This will allow to spread I2C bandwidth over multiple looptimes while keeping servos updat rate reasonable. Such approach may cause servo updates to be delayed but it shouldn't affect performance, because servos in general are very slow devices.

**Comment by digitalentity** [comment]
@hydra I totally agree that on new designs using some other chip is a better solution. However we are targeting towards reusing OLD boards. CC3D is priced at 10$ at AliExpress, assembled PCA9685 board is 3$ = total of 13$ for FC capable of driving 16 servos! Really you can't beat that price. Add anoter 18$ for M8N GPS and you have a perfect navigation-capable solution for an airplane for 31$.

For those who need to connect everything to a single board we are going to have an FC for INAV - see #287 :smile:

**Comment by DzikuVx** [comment]
@digitalentity That probably would help to distribute I2C bandwidth, correct.
The question is: is this required. Perhaps. 
When I was measuring delays for the last time, ON registries were still written. Now they are not written and F1 board has no problems keeping looptime 2000 with 7 servos. 
And it still makes no sense to write changes lower than 5us because of 12bit timer resolution

**Comment by martinbudden** [comment]
@DzikuVx , there may be other peripherals sharing the I2C bus. I've recently added support for the SRF10 sonar rangefinder which uses the I2C bus, and I intend to add support for optical rangefinders on the I2C bus.

Now, admittedly, rangefinders are low bandwidth devices; however, we may be adding further I2C devices in future, so I think spreading the bandwidth usage would be a good idea.

**Comment by digitalentity** [comment]
@martinbudden 
I agree. If we can distribute load - we should do it. We might be unlucky and get acc/gyro, mag and baro updates scheduled to the same cycle this way servo update may cause cycletime spike.

Just limit servo updates to 2 at a time and run the servo update task at 200Hz. 8 servos will still be updated at 50Hz rate but I2C bandwidth requirements will be considerably reduced.

**Comment by DzikuVx** [comment]
OK, you convinced me. Some time after my vacation

**Comment by digitalentity** [comment]
@DzikuVx I might give it a crack if I have time and if you don't mind :smile:

**Comment by DzikuVx** [comment]
If you have time then why not. But I would not give it high priority

**Comment by DzikuVx** [comment]
Done. Feature enabled only on targets with >128kB of flash. 

```
PWM Driver runs at 200Hz, every cycle every 4th servo output is updated:
cycle 0: servo 0, 4, 8, 12
cycle 1: servo 1, 5, 9, 13
cycle 2: servo 2, 6, 10, 14
cycle 3: servo3, 7, 11, 15
```

My airplane is still, well, not done yet, so only bench testes with servos connected to PCA9685. Works fine

**Comment by DzikuVx** [comment]
@digitalentity let's merge it or drop it, I'm kind of tired of rebasing this every few days
It's enabled only on F3 and disabled by default

**Comment by digitalentity** [comment]
I think it's safe to merge. We can always drop it if not needed.

**Comment by oleost** [comment]
Any documentation on this feature that should be added?

**Comment by DzikuVx** [comment]
There are no configuration options besides enabling one feature. I will
write something down next week.

czw., 15.09.2016 o 14:15 użytkownik oleost notifications@github.com
napisał:

**Pull request merged**
