### PR TITLE
Enforce waypoint altitude tolerance fix

### LINKED ISSUE #8278: nav_wp_enforce_altitude margin too tight for fixed wings
## Current Behavior
the target margin for the enforce altitude option on waypoints is too tight. Causing unnecessary loiter turns even on waypoints that have the same altitude. #7644

## Steps to Reproduce
1. plan mission
2. fly mission in slight winds or turbulences
3. watch altitude and turn behavior at waypoints
4. Plane will switch to "adjust altitude" state on nearly every waypoint

## Expected behavior
forced altitude loiter should only be done during a relatively big deviation. especially on wings

## Suggested solution(s)
Option 1: Disable the altitude enforcement if the last waypoint and current waypoint have a altitude difference below a certain threshold (maybe 10m?)
Option 2: Raise the margin for fixed wings to 10m or make it adjustable
Option 3: calculate the need of altitude adjustment based on the expected maximum climb angle of the airplane (nav climb rate, cruise speed, and distance.

For multirotor no changes might be required. 

## Additional context

Can be seen in real life flight easily but also in the HITL simulation: https://youtu.be/4pVUUmOFEH8 
@breadoven this should be considered to be fixed for 5.1 as the feature is currently unusable. 

---

- FC Board name and vendor: any
- INAV version string: 5.0 Release

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/8278.

Not yet flight tested.

### CODE REVIEW

**Comment by b14ckyy** [comment]
Nice! Will HITL test as soon as build check is finished. I hope Pawel accepts it for 5.1 as it changes the config (compatibility)

**Comment by breadoven** [comment]
Could always just change the current fixed 1m tolerance to perhaps 5m for 5.1 and keep this change for 6.0. Won't affect config compatibility in that case ?

**Comment by b14ckyy** [comment]
5m should be fine. if that still is not enough then the tune is messed up anyway. 
I have a feeling that this barely affects multirotor anyway as they should fly to the WP in a linear way? or is that still optional?

**Comment by DzikuVx** [comment]
@breadoven @b14ckyy can we merge?

**Comment by b14ckyy** [comment]
> @breadoven @b14ckyy can we merge?

Simulator and real flight tested. Has a go from my side.

**Pull request merged**
