### PR TITLE
Output servos as SBUS stream

### PR DESCRIPTION
**Pull request by digitalentity**
We currently have two ways of connecting a servo - PWM and servo driver. This PR adds a third option - a serial output for S.Bus servos (Futaba-compatible).

A new parameter `servo_protocol` will allow user to chose one. feature `PWM_SERVO_DRIVER` is removed.

A new serial function (bit 22, mask 4194304) is added to control assignment of this feature to a serial port.

Configurator support is missing. Untested.

Fixes https://github.com/iNavFlight/inav/issues/5648

### CODE REVIEW

**Comment by digitalentity** [comment]
Bench-tested, seems to output correct SBUS (obviously uninverted on F4 boards as they don't have the inverter).

**Comment by digitalentity** [comment]
@robthomson, it would be awesome if you can test this on real servos.

**Comment by robthomson** [comment]
No problem.  Easy for me to do.

How will I get a binary hex to suit one of my boards?

**Comment by digitalentity** [comment]
Which board are you using?

**Comment by robthomson** [comment]
I have a matek f405 wing to hand I can test with.

**Comment by digitalentity** [comment]
F405 boards don't have inverters on UARTS, so they can't generate proper S.BUS, we need an F7 board or an additional S.Bus inverter.

**Comment by robthomson** [comment]
Ok for me to use one of these?

Matek F722 Wing

**Comment by digitalentity** [comment]
Matek F722 Wing, here you are!

You'll need to configure in CLI:
```
serial X 4194304 115200 115200 0 115200
set servo_protocol = SBUS
```

where X is your SBUS output serial port (0 - Serial1, 1 - Serial2 etc)

[inav_2.5.0_MATEKF722SE.zip](https://github.com/iNavFlight/inav/files/4566002/inav_2.5.0_MATEKF722SE.zip)

**Comment by robthomson** [comment]
I have ordered an F722-SE board.. Will arrive Monday.

But just found an matek f765-wing in the bits box.

Any chance of that firmware so I can sort testing for you over weekend?

Failing that.. Monday.

**Comment by digitalentity** [comment]
Sure thing!

[inav_2.5.0_MATEKF765.zip](https://github.com/iNavFlight/inav/files/4566043/inav_2.5.0_MATEKF765.zip)

**Comment by robthomson** [comment]
Perfect.

Will test tomorrow am. 

Had a few too many beers already to test now!

**Comment by robthomson** [comment]
No joy.  I dont get any response from the servos.

**Comment by digitalentity** [comment]
Did you configure the mixer and enable the servo/motor output? Can you post a `diff` of your config?

**Comment by robthomson** [comment]
Here you go..

batch start

# resources

# mixer

mmix reset

mmix 0  1.000  0.000  0.000  0.000
mmix 1  1.000  0.000  0.000  0.000

# servo mix
smix reset

smix 0 3 0 100 0 -1
smix 1 4 0 100 0 -1
smix 2 3 14 100 0 -1
smix 3 4 14 -100 0 -1
smix 4 5 2 100 0 -1
smix 5 2 1 100 0 -1

# servo

# logic

# gvar

# gf

# feature
feature MOTOR_STOP
feature PWM_OUTPUT_ENABLE

# beeper

# map
map TAER

# serial
serial 1 64 115200 115200 0 115200
serial 5 4194304 115200 115200 0 115200
serial 7 4194304 115200 115200 0 115200

# led

# color

# mode_color

# aux
aux 0 2 0 1300 2100

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout

# master
set acc_hardware = MPU6000
set acczero_x = 111
set acczero_y = -10
set acczero_z = -197
set accgain_x = 4108
set accgain_y = 4057
set accgain_z = 4030
set mag_hardware = NONE
set baro_hardware = BMP280
set pitot_hardware = ADC
set serialrx_provider = CRSF
set platform_type = AIRPLANE
set model_preview_type = 14
set servo_protocol = SBUS
set small_angle = 180
set applied_defaults = 3

# profile
profile 1

set mc_p_roll = 30
set mc_i_roll = 2
set mc_d_roll = 0
set mc_p_yaw = 40
set mc_i_yaw = 30
set mc_d_yaw = 23
set mc_p_level = 0
set mc_i_level = 0
set mc_d_level = 0
set dterm_lpf_hz = 0
set dterm_lpf_type = PT1
set dterm_lpf2_hz = 1
set dterm_lpf2_type = PT1
set dterm_setpoint_weight =  0.000
set fw_iterm_throw_limit = 0
set fw_turn_assist_yaw_gain =  0.000
set pidsum_limit = 300
set pidsum_limit_yaw = 300
set iterm_windup = 0
set rate_accel_limit_roll_pitch = 12890
set rate_accel_limit_yaw = 65536
set heading_hold_rate_limit = 40
set nav_mc_pos_z_p = 85
set nav_mc_vel_z_p = 60
set nav_mc_vel_z_i = 0
set nav_mc_vel_z_d = 0
set nav_mc_pos_xy_p = 50
set nav_mc_vel_xy_p = 65
set nav_mc_vel_xy_i = 0
set nav_mc_vel_xy_d = 0
set nav_mc_vel_xy_ff = 0
set nav_mc_heading_p = 20
set nav_mc_vel_xy_dterm_lpf_hz =  0.500
set mc_iterm_relax_type = GYRO
set mc_iterm_relax = OFF
set d_boost_factor =  2.000
set rc_yaw_expo = 70
set roll_rate = 30
set yaw_rate = 10

# battery_profile
battery_profile 1


# end the command batch
batch end


Curiously I cant get servos to work when plugged into the PWM ports on the FC either!

Maybe fc is the problem?

**Comment by digitalentity** [comment]
> Curiously I cant get servos to work when plugged into the PWM ports on the FC either!

This is expected. SBUS servo output will disable FC servo outputs.

That's F765, right? I think I have one somewhere, will test more.

**Comment by robthomson** [comment]
Yes.  This is the f765

Is there a way to retain pwm and have sbus at the same time?

That would be amazing if possible. 

Gives real choose then.

**Comment by digitalentity** [comment]
With this minimalistic config I'm getting what looks like a valid S.Bus on TX6 on MATEKF765:

```
mmix reset

mmix 0  1.000  0.000  0.000  0.000
mmix 1  1.000  0.000  0.000  0.000

# servo mix
smix reset

smix 0 3 0 50 0 -1
smix 1 3 1 50 0 -1
smix 2 4 0 -50 0 -1
smix 3 4 1 50 0 -1

feature PWM_OUTPUT_ENABLE

serial 5 4194304 115200 115200 0 115200

set platform_type = AIRPLANE
set model_preview_type = 8
set servo_protocol = SBUS
```

**Comment by robthomson** [comment]
Hmmm.. Makes me wonder if my fc is the problem.

I will have a play with it again tomorrow am.

**Comment by digitalentity** [comment]
It might be that S.Bus servos are expecting a particular S.Bus header/footer. INAV is more tolerant to various packet formats.

**Comment by digitalentity** [comment]
Found a bug, forgot about parity :man_facepalming:

**Comment by robthomson** [comment]
Can you post the firmware again with the bug fixed?

**Comment by digitalentity** [comment]
Sure! [inav_2.5.0_MATEKF765.zip](https://github.com/iNavFlight/inav/files/4574464/inav_2.5.0_MATEKF765.zip)

**Comment by Muntaharul** [comment]
> We currently have two ways of connecting a servo - PWM and servo driver. This PR adds a third option - a serial output for S.Bus servos (Futaba-compatible).
> 
> A new parameter `servo_protocol` will allow user to chose one. feature `PWM_SERVO_DRIVER` is removed.
> 
> A new serial function (bit 22, mask 4194304) is added to control assignment of this feature to a serial port.
> 
> Configurator support is missing. Untested.
> 
> Fixes #5648

hlw dear iam using inav matek f722se firmware 7.1.0 soo iam using a vtol the problem is my flight controller have 8 output and with group group 1 4 g2 2 g3 2 soo iam using 4motor for vertical take off and when transition its is airplane mode motor 5 spiin and ihave only 2 servo output left because group 2 have motor icant use another output asa servo so i search on every where how can i get 1 more output ifound this usign sbus but i cant configure the output usign s bus can you help me please also this project is my ubivercity project

**Pull request merged**
