### PR TITLE
Let fixed wing autotune set the rates

### LINKED ISSUE #6025: Let INAV figure out rates on FW
## Current Behavior

The PIFF controller on fixed wing uses the airplane's maximum roll, pitch and yaw rates for it's stabilization. Finding the correct rates can be a bit of a pain, especially for planes that can't do nice clean rolls and loops without a lot of other pilot input. Measuring the yaw rate is even more difficult, since rudder often has a strong roll response. In that case a black box log is the only method to figure out the rates, but this requires a computer which is often impractical.

## Desired Behavior

The gyroscope should be able to measure the rotation rates on full control surface deflection.

## Suggested Solution

Make `AUTOTUNE` a two-stage process where it first determines the rates on full control surface deflection, and then tunes the PIFF values using those rates. Ideally it would be possible to also do each stage separately if the user only want to do one or the other.

## Who does this impact? Who is this for?

All fixed wing pilots.

### PR DESCRIPTION
**Pull request by avsaase**
Closes #6025.

This is a WIP improvement to autotune that creates three autotune modes (`fw_autotune_rate_adjustment`): `FIXED` the default and the current behavior where rates are never changed, `MAX` where rates are decreased if not achievable with current mixer weights, and `AUTO` where the rates are increased and decreased according to the airplane's capabilities. Setting to `MAX`, and especially `AUTO`, creates a system where both the setpoint and the gains are changed simultaneously. The current logic should not cause any problems but I am looking for feedback on this.

There are still some things to do, for which I have added comments.

@b14ckyy, is this sort of what you had in mind?

### CODE REVIEW

**Comment by avsaase** [comment]
Okay, the logic should work now. With `fw_autotune_rate_adjustment = FIXED` autotune works the same as before, but the FF update is now proportional to the difference between the previous FF-gain and the pidSum (P+FF) needed to obtain the target rotation.

With `fw_autotune_rate_adjustment = MAX` autotune decreases the max axis rate if it undershoots the rate target with a servo deflection* of more than 90%. In that case, the airplane apparently is not capable of achieving the max axis rate, so the max axis rate is decreased proportionally to the difference in the axis rate and the rate it should be able to achieve at 90% deflection. If it undershoots the target at less than 90% deflection, FF is increased like with `FIXED`. Overshoots are also handled like `FIXED`: decrease FF.

With `fw_autotune_rate_adjustment = AUTO` rate undershoots are handled the same as with `MAX`, but overshoots are handled differently when the achieved rate is also higher than the set max axis rate (by more than 10 degrees per second). In that case, the airplane is capable of rotating faster than the current settings imply, so the max axis rate is increased proportionally to the difference between the rate it should be able to achieve at 90% deflection and the current axis rate. Overshoots smaller than the max axis rate are handled the same as with `FIXED`.

All rate and FF updates are scaled down by a factor of 2 to avoid changing the settings too fast. This is configurable with the new CLI command `fw_autotune_convergence_rate`. The 90% deflection target is chosen to leave some room for P and I to work.

I have not tested this in flight, and bench testing is difficult, but I am 80% sure the above logic will always converge to the "correct" rate and FF values.  Unless someone finds a major flaw in my code, I plan to fly with this the coming weekend. However, I have not been able to figure out how to actually save the new axis rates in `autotuneUpdateGains()`. If anyone can point me in the right direction that would be great.


\* It is not really servo deflection, but rather control request, equivalent to transmitter stick deflection in MANUAL mode. This respects mixer rules, servo midpoint, endpoints, etc.

**Comment by avsaase** [comment]
This is not yet ready. I am doing some simulations to see how this will behave in flight and there are a couple of edge cases that I need to take care of.

**Comment by avsaase** [comment]
I simplified the logic by getting rid of the separate code for the overshoot and undershoot cases because that turned out to be unnecessary and needlessly complicated. I have done a ton of simulations with this code and now all seems to work as it should. The rates and gains converge to a fixed value in just a few updates, even when the starting values are completely off the mark.

All that's left before this can be test-flown is applying the new rates after updating. I tried doing this on line 98 but got the error that I was trying to write to a read-only location. Not sure where to go next.

**Comment by avsaase** [comment]
Thanks to @shellixyz the new rates are now applied and can be saved after disarming. I did some bench testing and everything seems to work like it should, although it is near impossible to simulate an autotune by holding the model in your hand. The weather is looking good so I will test the new algorithm this weekend. @b14ckyy, you also wanted to test this right?

**Comment by avsaase** [comment]
Pfff, I there's still some problems. I'm closing this and I'll open a new PR once I have everything working and tested in flight.

**Comment by b14ckyy** [comment]
> @b14ckyy, you also wanted to test this right?

Yes send me a build for an Matek F411-WSE. I can test this on the ZOHD Drift.

**Comment by avsaase** [comment]
Here you go. This is probably obvious, but make sure you have `MANUAL` on a switch in case anything goes wrong. I have improved the logic, done a lot more simulations to see how everything behaves, and did a bench test to confirm that the gains and rates are in fact changing, but I have not flown with this yet. _[Insert usual disclaimer]_

The relevant settings are:
| Variable Name | Default Value | Description |
| ------------- | ------------- | ----------- |
| fw_autotune_convergence_rate | 0.5 | How fast autotune will converge. Too high values can cause overshooting of FF and rate targets. |
| fw_autotune_rate_adjustment | FIXED | `AUTO` adjusts the rates to match the capabilities of the airplane, `MAX` adjusts the rates but never above the current rate settings, `FIXED` (the default) does not adjust the rates. |

The first setting's default is probably okay, but you can try decreasing it a bit if you find the changes of the rates and gains too large.

I would love to see some dvr of the gains and rates changing on the osd since the F411-WSE doesn't have a blackbox. I will be testing this weekend on my Dart 250 with the same fc.

Thanks for trying this out! I think this would be an awesome feature for 2.7.

[inav_2.7.0_MATEKF411SE.zip](https://github.com/iNavFlight/inav/files/6045996/inav_2.7.0_MATEKF411SE.zip)

**Pull request closed without merging**
