### PR TITLE
Added tz_automatic_dst to MSP2_COMMON_TZ and MSP2_COMMON_SET_TZ

### PR DESCRIPTION
**Pull request by Airwide**
Added tz_automatic_dst to MSP2_COMMON_TZ and MSP2_COMMON_SET_TZ to be able to set time zone settings from inav-configurator.

### CODE REVIEW

**Comment by stronnag** [comment]
This breaks existing 3rd party applications that use MSP2_COMMON_TZ. The code should accept 2 or 3 bytes to maintain legacy compatibility.

**Comment by Airwide** [comment]
> This breaks existing 3rd party applications that use MSP2_COMMON_TZ. The code should accept 2 or 3 bytes to maintain legacy compatibility.

Ok, I'll make changes to MSP2_COMMON_TZ. What about MSP2_COMMON_SET_TZ, is that ok?

**Comment by Airwide** [comment]
@stronnag - Thinking a bit more about it, it's probably better if I create a new MSPCode just for this purpose (to communicate with INAV-configurator). WDYT?

**Comment by stronnag** [comment]
> > This breaks existing 3rd party applications that use MSP2_COMMON_TZ. The code should accept 2 or 3 bytes to maintain legacy compatibility.
> 
> @stronnag Ok, I'll make changes to MSP2_COMMONMSP2_COMMON_TZ. _TZ. What about MSP2_COMMON_SET_TZ, is that ok?
 
Apologies, sloppy review comment. 

`MSP2_COMMON_SET_TZ` should accept two or three bytes, so legacy apps can just set the offset as before. 

`MSP2_COMMON_TZ` doesn't need changing, any well designed app will read 3 bytes and process the two it expects. This is how we've handled similar cases where a structure has changed  previously.

**Comment by Airwide** [comment]
> > > This breaks existing 3rd party applications that use MSP2_COMMON_TZ. The code should accept 2 or 3 bytes to maintain legacy compatibility.
> > 
> > 
> > @stronnag Ok, I'll make changes to MSP2_COMMONMSP2_COMMON_TZ. _TZ. What about MSP2_COMMON_SET_TZ, is that ok?
> 
> Apologies, sloppy review comment.
> 
> `MSP2_COMMON_SET_TZ` should accept two or three bytes, so legacy apps can just set the offset as before.
> 
> `MSP2_COMMON_TZ` doesn't need changing, any well designed app will read 3 bytes and process the two it expects. This is how we've handled similar cases where a structure has changed previously.

Ok, then it's quite easy to fix. Fix coming up!

**Comment by stronnag** [comment]
> @stronnag - Thinking a bit more about it, it's probably better if I create a new MSPCode just for this purpose (to communicate with INAV-configurator). WDYT?

The above solution is fine. In general we'd prefer not to add new MSP Ids unless absolutely necessary.

**Review by digitalentity — APPROVED** [review]
LGTM

**Comment by Pairan** [comment]
Thanks @Airwide :)

**Pull request merged**
