### PR TITLE
Fix axis directions for AK8963 compass (MPU9250 compass chip)

### LINKED ISSUE #590: SPRacingF3 EVO compass reporting incorrect heading when tilted
this SW is really great - experience / testing on a SP F3evo board: the GPS_HOLD mode starts after some time to drift
drift is in position and altitude
I have experienced this 2 times - 1:26 min and 1:06 min (rough landing not really crash)

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #590

### CODE REVIEW

**Comment by digitalentity** [comment]
@elepete, @oleost this should fix built-in compass issues on EVO and MINI

**Comment by oleost** [comment]
Will test later today on mini.

**Comment by oleost** [comment]
@stronnag Do you have an Evo you could test with?

**Comment by stronnag** [comment]
Sure. Give me a few minutes ...

**Comment by stronnag** [comment]
Tested OK. Reads correct direction across the compass, and is stable with inclination. (EVO)

**Comment by digitalentity** [comment]
Great, thanks! @oleost I'll wait for your results on MINI.

**Comment by oleost** [comment]
@digitalentity Got to test now.
Unsure whats going on here.

With the default [CW90_DEG_FLIP](https://github.com/iNavFlight/inav/blob/development/src/main/target/SPRACINGF3MINI/target.h#L57) its not working. With it changed to CW270_DEG_FLIP (Either at compile or in configurator its working)

Looking over at cleanflight it is also is CW90_DEG_FLIP

**Comment by digitalentity** [comment]
Actually change of alignment to CW270_DEG_FLIP is required to make it aligned as it should (at least according to datasheet). I have no idea why it works in Cleanflight, because both INAV and Cleanflight IMU expects sensors to be in NED coordinate frame.

New default in INAV is CW270_DEG_FLIP.

**Comment by oleost** [comment]
@stronnag Did you also need to change to 270flip?

Or did default 90 work on your evo?

**Comment by stronnag** [comment]
I needed 

```
set align_mag = CW270FLIP
```

and in case it's relevent, my board is offfset with

```
set align_board_yaw = 900
```

I can never remember if these are related for on board devices.

**Pull request merged**
