### PR TITLE
SBUS inversion control (grafting from Cleanflight)

### LINKED ISSUE #1006: RX - Add support for non-inverted SBUS input
Original Issue over at cleanflight : https://github.com/cleanflight/cleanflight/issues/1398

Original pullrequest over at cleanflight: https://github.com/cleanflight/cleanflight/pull/1604

Short description: For F3 target that can configure whether port is inverted or not, add abbility to configure it.

This is because apperntly some OpenLRS receivers uses non-inverted sbus signal.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #1006

### CODE REVIEW

**Comment by digitalentity** [comment]
It would be nice if somebody can test this with non-inverted S.Bus

**Comment by oleost** [comment]
I notified original requester from forum.

**Comment by digitalentity** [comment]
Thanks, lets see if he'd be able to test it

**Comment by DzikuVx** [comment]
I will try to test it today. I will invert sbus to have "uninverted" signal :)

**Pull request merged**
