### PR TITLE
ZEEZF7V2 target

### PR DESCRIPTION
**Pull request by nmaggioni**
ZEEZF7V2 target for the ZEEZ RC [3030 v2](https://zeezrc.com/shop/zeez-f7-flight-controller/) and [2020 v2](https://zeezrc.com/shop/zeez-f7-2020-flight-controller/).

Based on the existing [INAV target for V1](https://github.com/iNavFlight/inav/tree/c26a676bb1df029cb859b51875898c58d7279134/src/main/target/ZEEZF7) and both FC's new BF [unified config](https://github.com/betaflight/unified-targets/blob/16162aaafd7763afc99894860489286aab0a6a78/configs/default/ZEEZ-ZEEZF7V2.config).

### CODE REVIEW

**Comment by DzikuVx** [comment]
Scoped all the outputs, seems to be working fine

**Comment by DivingFalconFPV** [comment]
Where do I download this. My ZeezF7v2 2.6.1 the mag isnt working. shows it on I2C2 where betaflight had it on I2C3...

**Comment by nmaggioni** [comment]
@DivingFalconFPV Please try this build and report back: 
[inav_2.6.1_48c4d38_ZEEZF7V2.zip](https://github.com/iNavFlight/inav/files/6412256/inav_2.6.1_48c4d38_ZEEZF7V2.zip)

**Comment by robustini** [comment]
@nmaggioni hello Niccolò, have you always taken care of this target also for Betaflight?
I ask you this because I have implemented the camera control for INav, you find it in my fork, and with this target it does strange things.
I then tried it with Betaflight and it does exactly the same problem.
PB15 is the pin used in Betaflight, and I'm also using it in INav.
I enter the cam menus correctly, but the "drop value" command does not work, and others are reversed from how it should work, it does the same in Betaflight.
With other targets, even custom, everything works perfectly, so there is something anomalous with this fc.
Here you see it working on another target, which obviously works the same in Betaflight as well.

https://youtu.be/vjMvWp4u8Zg

**Comment by nmaggioni** [comment]
@robustini I'm not a BF contributor, sorry - AFAIK their unified target definition was written by ZEEZ staff. I'll see if in the near future I'll be able wire up a camera control test rig to try some workarounds.
In the meantime I'd suggest that you reach out to ZEEZ for clarifications on the HW.

**Comment by robustini** [comment]
Do you have any reference on how to contact them?

**Comment by nmaggioni** [comment]
https://zeezrc.com/contact-us/, plus the email address and the social media accounts reported at the top of the same page.

**Pull request merged**
