### PR TITLE
Target Omnibus F7

### PR DESCRIPTION
**Pull request by DzikuVx**
* [x] MPU6000
* [x] onboard BMP280
* [x] PPM input
* [x] OSD
* [ ] LED Strip
* [x] PWM outputs
* [x] UART1
* [x] UART6
* [x] UART3
* [x] I2C
* [x] Serial RX over UART2 (RX only, no TX pin)
* [x] VBAT ADC
* [x] Current ADC
* [x] RSSI Adc
* [x] SD Card

### CODE REVIEW

**Comment by DzikuVx** [comment]
SD Card and PWM outputs confirmed working

**Comment by DzikuVx** [comment]
samo for UART2 Serial RX and PPM

**Comment by DzikuVx** [comment]
Correction. There is a timer clash between PPM and servo output. When PPM enabled, servo out put becomes unregular (12Hz)

**Comment by DzikuVx** [comment]
All UARTs, I2C and ADCs confirmed working

**Comment by DzikuVx** [comment]
LED strips are not working. Looks like DMA issue. In theory it should be DMA2 Stream 4 but as soon as I enable LEDs on this DMA controller VCP stop to work while board seems to be booting.

I'm still merging this target and adding not in DOCs about not working functionality. Maybe someone will be able to fix it

**Comment by digitalentity** [comment]
@DzikuVx do we have an issue open for LED strip issue?

**Comment by DzikuVx** [comment]
We do have now #1939 . Thanks for reminding

**Pull request merged**
