### PR TITLE
Add target code for IFLIGHTF7_TWING board support.

### PR DESCRIPTION
**Pull request by iFlightFpv**
image

image

**Tested well, it's ready for merging.**

### CODE REVIEW

**Comment by DzikuVx** [comment]
@iFlightFpv please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by DzikuVx** [comment]
@iFlightFpv please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by iFlightFpv** [comment]
@DzikuVx @digitalentity Hello all. 
Thanks for your efforts.
How can I cantact to you or other core developers?
I would like to send some hardware samples to you or other code developers.
And I already contacted you on the Telegram IM. 
Looking forward to reply me. 
Thanks.

**Comment by DzikuVx** [comment]
@iFlightFpv we got no message from you. Please write me on `@dzikuvx` on Telegram directly please

**Comment by DzikuVx** [comment]
or @iFlightFpv if Telegram is off, using email address from my GitHub Profile

**Comment by Linjieqiang** [comment]
@DzikuVx I has been contacted you on telegram, waiting for your reply.

**Comment by iFlightFpv** [comment]
Ok, I have arranged to send some hardware samples to the core developer.

**Comment by teckel12** [comment]
@iFlightFpv Nice board! And I fly one of your frames (XL7 Slam) which I highly recommend. I don't see pins for i2c on this board. Am I missing something? (I'm on mobile so maybe that's why it's not obvious)

**Comment by digitalentity** [comment]
Samples should arrive in a few days, I'll test, merge so we can have it in release 2.2.1

**Comment by digitalentity** [comment]
@iFlightFpv can you send documentation for F7 board? The one I have (for EXF722DUAL Betaflight target) doesn't seem to match the target definitions. 

I'm interested in gyro1/gyro2 pins as well as I2C pins.

**Comment by digitalentity** [comment]
Also, when powered by USB, the flight controller board heats to ~45-50 degrees (which is not normal).
I suspect something is not right in board design or target definition.

**Comment by Linjieqiang** [comment]
@digitalentity I send you messages on Telegram.

**Comment by Linjieqiang** [comment]
Thanks. @digitalentity

**Pull request merged**
