### PR TITLE
Add vario sensor to CRSF telemetry

### LINKED ISSUE #4710: Crossfire vSpd telemetry
The current implementation of csrf telemetry sends the 'ALT' value to the radio via the CSRF protocol.

It would be fantastic to additionally send the vSpeed value.

This information is present in the OSD, so should be possible to send as an additional sensor value.

Its important to have this information for the vario in opentx to function well.

Using ALT is simply too low a resolution for it to be worth using.

### PR DESCRIPTION
**Pull request by shellixyz**
Closes #4710

### CODE REVIEW

**Comment by teckel12** [comment]
👍

**Comment by shellixyz** [comment]
Confirmed working. For now you have to build your own OpenTX with this patch for the new sensor to appear on the radio: https://github.com/opentx/opentx/pull/6476

**Comment by teckel12** [comment]
@shellixyz So forget about it working on the Jumper T16.

**Comment by shellixyz** [comment]
@teckel12 I guess JumperTX will follow OpenTX so it should end up working on the T16 too. I can submit the PR to JumperTX to be sure

**Comment by teckel12** [comment]
@shellixyz I'm half-joking, I have Horus/Taranis as well so I'll eventually be able to test it on those platforms.  Thanks for the effort on this!

**Pull request merged**
