### PR TITLE
Release version 1.3

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by digitalentity** [comment]
Holy buckets! Over 100 commits in under 1.5 months! :flushed:

**Comment by stronnag** [comment]
For the releases notes:
- Your configuration will be erased
- Your modes will need to be re-entered (not just restored from a CLI dump), as the switch values have changed

**Comment by digitalentity** [comment]
@stronnag, I'll post a PR to restore same CLI mode IDs as in v.1.2.1, re-entering modes won't be necessary.

However, until Configurator is adapted to changes introduced by https://github.com/iNavFlight/inav/pull/397, we'll need to explicitly state that fast motor update modes (OS125 etc) can be configured only via CLI.

**Comment by digitalentity** [comment]
1.3.0-RC1 is out https://github.com/iNavFlight/inav/releases/tag/1.3-RC1

**Comment by DzikuVx** [comment]
Great! I should be able to finish configurator changes for ESC protocol in a few days

**Comment by digitalentity** [comment]
@DzikuVx that's amazing news!

**Pull request merged**
