### PR TITLE
Fix issue with MSP Baro (Box enum only)

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
That solve https://github.com/iNavFlight/inav/issues/8080

I spent some time trying to understand how the new format of the iNav Configurator works... Now just update Settings.md and the settings are automatically changed in the Configurator. That was a very smart feat!

### CODE REVIEW

**Comment by robustini** [comment]
Fixed, thanks!
Please merge it.

**Comment by MATEKSYS** [comment]
image

seems this bug is still there, same with INAV4.1
Baro readout can't jump back after stop blowing

**Comment by MATEKSYS** [comment]
image

**Comment by robustini** [comment]
> Baro readout can't jump back after stop blowing

Very true, I hope that this too will be fixed because having an useless barometer is like not having one.

**Comment by JulioCesarMatias** [comment]
> image
> 
> seems this bug is still there, same with INAV4.1 Baro readout can't jump back after stop blowing

Does this happen with other versions? For example, iNav 3.0

**Comment by MATEKSYS** [comment]
> 
image

just tried INAV3.0.2, happens also

**Comment by robustini** [comment]
> > 
> 
> image
> 
> image
> 
> Tried INAV3.0.2, and 2.6.1. seems that this bug has always been there. just we didn't notice it happens with the negative height before.

Please explain this kind of wrong behavior well, I'm trying the bench and it doesn't seem to work badly.

**Comment by DzikuVx** [comment]
OK, the detection of MSP baro will merge to 5.0
@MATEKSYS could you please make a separate ticket for the MSP baro readouts being wrong?

**Comment by robustini** [comment]
@MATEKSYS  did you create another issue for the barometer?
Yesterday in flight I noticed that the baro height was completely wrong, and the problem is that iNav certainly gives priority to the barometer in the automatisms, ignoring the height detected by the GPS.
Yesterday during a failsafe the quad shot into orbit, well beyond the height set, perhaps due to a problem with the barometer.
Unfortunately I think that iNav does not have a sanity check on the barometric data during flight.
Although the height given by the GPS may not be very accurate, iNav if there is a big gap (for example over 10 meters) between the barometer altitude and the GPS should ignore the atmospheric pressure data and use the GPS.
In my quad RTH it was set to 30 meters, during the failsafe it went over 60 meters and did not stop, luckily I recovered the link and exiting the failsafees I brought it back to the ground.

**Pull request merged**
