### PR TITLE
STM32F7 support

### PR DESCRIPTION
**Pull request by digitalentity**
@sambas I've merged F7 support into this branch. Can you have a look if it works?
I intend to rework the I2C driver to follow the same FSM as F1/F3/F4, what board would you recommend to get to debug?

### CODE REVIEW

**Comment by sambas** [comment]
Boots and sensors work, manually selected i2c ms5611 also works. Not tested further.
In BF we have NucleoF7 target for dev/debug. Have not seen any FC with F7 sold anywhere.

**Comment by digitalentity** [comment]
Thanks! I'll probably need to get myself a NUCLEO-F746ZG board...

**Comment by digitalentity** [comment]
@sambas can you fix build warnings and errors so we could merge ASAP?

**Comment by digitalentity** [comment]
Ok, looks good now. I'm going to merge this now to avoid conflicts in this huge PR. 
@sambas you can now start pulling your improvements and fixes to F7 code over here, and huge thanks for the effort!

**Pull request merged**
