### PR TITLE
Add new target WingFC

### LINKED ISSUE #4337: Wing Fc-10 DOF  ppm not working
The board run's inav_1.9.0_FF_F35_LIGHTNING.HEX 
and the ppm doesn't work. 
I tryed new firmware but no changes.
SBUS work but I need ppm for my long range receiver.
Please help.

### PR DESCRIPTION
**Pull request by shellixyz**
Where to buy:
https://inavflight.com/shop/s/bg/1318626

Closes #4337

### CODE REVIEW

**Comment by digitalentity** [comment]
So it only redefines the PPM-in pin?

**Comment by shellixyz** [comment]
Yes that's the only issue that has been found for now. The WingFC doesn't have a pad for UART3 TX so the PPM input can't be used with the FF_F35 target.

**Comment by stronnag** [comment]
Missing a .mk file?
```
touch src/main/target/FF_F35_LIGHTNING/WINGFC.mk
```

**Comment by shellixyz** [comment]
Good catch I forgot to git add the file

**Pull request merged**
