### PR TITLE
TPA computation moved from mw.c to specific function inside pid.c

### PR DESCRIPTION
**Pull request by DzikuVx**
Well, current code-frenzy inside mw.c is overwhelming :) Let's add some sanity into it

### CODE REVIEW

**Comment by digitalentity** [comment]
Throttle is updated only when updateRx is executed. This is waste of computational resources to compute it over and over in PID controller.

**Comment by DzikuVx** [comment]
Good point, I will look more deeply into the topic

**Comment by DzikuVx** [comment]
@digitalentity I moved TPA computation out of PID loop to RX task. That means that in a future computation of pidState[axis].kP kI and kD could also be removed from PID loop since they change only on TPA and/or inflight PID adjustment. 
I gave it a try some time ago and was able to save about 20us on each loop

**Comment by digitalentity** [comment]
Yes, PID coefficients can also be computed in that function. We can call it i.e. `updatePIDCoefficients`

**Comment by DzikuVx** [comment]
Outstanding, moving deeper into the code

**Comment by DzikuVx** [comment]
@digitalentity This is as far as it gets now on this topic. Compiles, uploads, but I have no means to test that ATM in real flight. 
I only tested looptime and looks like we have gained about 100us every loop on F1 targets. Previously it was around 1220. Right now it is about 1120-1130. I think there is still some room for improvements

**Comment by digitalentity** [comment]
Fixed point math can give us a boost on performance.

**Comment by DzikuVx** [comment]
To be honest I do not like the idea going back to fixed math. It's not ATmega328, F1 targets are slowly replaced by F3 and if you buy F1 then be prepared not to have the best looptime. Either way, we can try in a future.

**Comment by digitalentity** [comment]
If we can make things work with lowerst possible looptimes on F1 targets - we should at least consider it. It's low priority though and will certainly happen only after merging this PID.

**Comment by digitalentity** [comment]
Merged via 7ae5f5147d5d017c08a1b522476fb2b4a7075ecf

**Comment by digitalentity** [comment]
Squashed commits and merged

**Comment by digitalentity** [comment]
Thanks! Code is much cleaner now.

**Pull request closed without merging**
