### PR TITLE
Use the PosHold verification only in Multirotor

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
https://github.com/iNavFlight/inav/issues/7174

### CODE REVIEW

**Comment by avsaase** [comment]
No! This arming block exists for a reason. Without it when you arm with POSHOLD enabled the plane will immediately take control of the throttle.

**Comment by JulioCesarMatias** [comment]
> Não! Este bloqueio de arme existe por um motivo. Sem ele, quando você armar com POSHOLD ativado, o avião assumirá imediatamente o controle do acelerador.


really, you're right. So the correct thing is to activate PosHold after the Lauch is done. I think you can keep it that way, and just add a way to disable PosHold while AutoLaunch is active.

**Comment by JulioCesarMatias** [comment]
https://github.com/iNavFlight/inav/blob/0d1ecd536c1bc0b5132934399a5ad8757713e0ae/src/main/navigation/navigation.c#L3243

 if (IS_RC_MODE_ACTIVE(BOXNAVPOSHOLD)) {

to 

 if (IS_RC_MODE_ACTIVE(BOXNAVPOSHOLD) && !isFixedWingLaunchFinishedOrAborted()) {

**Comment by JulioCesarMatias** [comment]
> https://github.com/iNavFlight/inav/blob/0d1ecd536c1bc0b5132934399a5ad8757713e0ae/src/main/navigation/navigation.c#L3243
> 
> to
> 
> if (IS_RC_MODE_ACTIVE(BOXNAVPOSHOLD) && isFixedWingLaunchFinishedOrAborted()) {

so the poshold mode will be activated only when the launch finishes

**Comment by breadoven** [comment]
POSHOLD is blocked when arming with Launch enabled to prevent the aircraft circling back and hitting the pilot or bystanders behind the launch point if the launch is aborted at low level. If you want to use POSHOLD simply select it AFTER arming but only if you understand what will happen if the launch is aborted. There's no need to change this ... the block is there for a reason.

**Comment by JulioCesarMatias** [comment]
ok

**Pull request closed without merging**
