### PR TITLE
Replaced some instances of ASYNC_GYRO_PROCESSING

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
Great cleanup!

**Comment by DzikuVx** [comment]
Love it!

**Review by stronnag — COMMENTED** [review]
There seem to be missing return statements in src/main/fc/config.c for the non-ASYNC case, the compiler will discard stuff like line 137.

````
./src/main/fc/config.c: In function 'getPidUpdateRate':
./src/main/fc/config.c:137:9: warning: statement with no effect [-Wunused-value]
     gyro.targetLooptime;
     ~~~~^~~~~~~~~~~~~~~
./src/main/fc/config.c: In function 'getAccUpdateRate':
./src/main/fc/config.c:156:9: warning: statement with no effect [-Wunused-value]
     gyro.targetLooptime;
     ~~~~^~~~~~~~~~~~~~~
./src/main/fc/config.c: In function 'getPidUpdateRate':
./src/main/fc/config.c:139:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
./src/main/fc/config.c: In function 'getAccUpdateRate':
./src/main/fc/config.c:158:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
````

**Comment by martinbudden** [comment]
Aargh!

**Comment by martinbudden** [comment]
Now fixed.

**Pull request merged**
