### PR TITLE
Fix LED Indicators mode for Fixed Wing and Rover

### PR DESCRIPTION
**Pull request by MrD-RC**
Currently, the indicators mode is only really works for quads. It doesn't make any sense for fixed wing. This PR changes that. Roll movements to the left triggers indicators on the left half of the grid. Roll movements to the right triggers indicators on the right half of the grid.

This change may also be suitable for rovers too. If so, it's an easy modification. So feedback from rover people would be great.

### CODE REVIEW

**Comment by WizzX-FPV** [comment]
I'm INAV rover guy and using stick controller (no pistol) TX16s I'm using left stick (yaw) for steering and roll axis for camera pan. But I asked another guy on RC groups and he using left stick for throttle only a right stick (roll) for steering. So seems like there must be selectable channel for using indicators :)

**Comment by sercona** [comment]
so far, what seems to work for me with my rover (single bidirectional motor, single steering servo, modified wltoys 144001 buggy) is to use air stick controller (I also avoid pistol remotes and use sticks for both air and surface) and have the self-centering mode2 stick on the right do throttle forward/backward as pitch and steering as roll, but its not roll, its really yaw, just done on that single stick.  I left the left mode2 stick alone, for now, since having speed and direction on that single stick really works out well in racing and bashing (as they call it).

**Comment by sercona** [comment]
also, braking - one of the new ESCs out there (for surface) supports a drag brake (level) channel.  give it usual servo 1k-2k value and it will set the drag brake to that.  it kind of also works as a sudden brake.  I have this mapped to the spring return 'beeper' switch on my air remote (often the far right switch at the top) and if I need more brake than I set for 1500 (neutral) throttle value, then I can add in or override the brake value with that switch, sending max value on the brake control channel.  (need to use pwm wire on your FC to control this as its a real wire just like the throttle wire, normal pwm like servo)

**Comment by MrD-RC** [comment]
Around 80% of rover drivers who responded said they use the roll channel for turning. So added the indicators for rovers too.

**Pull request merged**
