### PR TITLE
HDZERO VTX OSD Support

### PR DESCRIPTION
**Pull request by geoffsim**
Update OSD coordinate system to allow up to 64x64 (HD) from original of 32x32 (SD).

Update DJI OSD code to map back to SD coordinate system.
Update DJI fixed element co-ordinates to be more central on screen.

Add HD ZERO OSD support for 50x18 OSD canvas.

(See also PR for supporting configurator changes)

### CODE REVIEW

**Comment by DzikuVx** [comment]
Awesome!

**Comment by geoffsim** [comment]
Please let me know if there is anything else I have to do (and how to do it, if there is). Regards, Geoff. From: Paweł SpychalskiSent: 19 December 2021 11:06To: iNavFlight/inavCc: Geoff Sim; AuthorSubject: Re: [iNavFlight/inav] HDZERO VTX OSD Support (PR #7668) Awesome!—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by DzikuVx** [comment]
So far, you have not run python script to generate Settings.md
And I see that are some intendation problems in the code.
I will try to review next week

**Comment by geoffsim** [comment]
Thanks.I am unable to run that script at the moment as it requires python3 and related libraries.If I have to, I will look at updating to version 3. From: Paweł SpychalskiSent: 19 December 2021 11:26To: iNavFlight/inavCc: Geoff Sim; AuthorSubject: Re: [iNavFlight/inav] HDZERO VTX OSD Support (PR #7668) So far, you have not run python script to generate Settings.mdAnd I see that are some intendation problems in the code.I will try to review next week—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by geoffsim** [comment]
I have run the script and updated the PR, but the test is still failing. I ran the same test on my local branch and it passes ok.
Please advise.

**Comment by MrD-RC** [comment]
I just had a look a settings.md and it needs to be updated. If you look for a boolean value, it should have off and on in the min and max table columns respectively. 

You may need to fetch upstream on your branch to get the latest documents generating script.

**Comment by geoffsim** [comment]
Hi. I did update using the script specified. When I run the commands in the failure notification, it passes ok. I’m not sure what to do now.

**Comment by MrD-RC** [comment]
There is definitely a problem with the settings.md file. In this screenshot, the settings.md on the left is the one submitted with this PR. The one on the right is the master. Check out the `beeper_pwm_mode` section. You can see on the master that the MIN and MAX in the table have OFF and ON. The version in this PR does not.

image

How does the file look on your computer? If you have the OFF and ON in the `beeper_pwm_mode` table, it's correct and just hasn't been pushed to the change branch. if the OFF and ON for MIN and MAX are missing, you have the wrong document creation script. If you perform a fetch upstream on your branch, it should get the correct creation script. It is _src/utils/update_cli_docs.py_ and should have the lines:

66 | member["min"] = "OFF"
67 | member["max"] = "ON"

I just checked your branch, and the creation script is not up to date. So the fetch upstream on your branch should get everything sorted.

**Comment by geoffsim** [comment]
Argh. Yes, master has moved on. I’ll update my branch tomorrow. 

Cheers.

**Comment by geoffsim** [comment]
Please do not merge yet as I am working on an optimisation to reduce the amount of data being sent over the serial port.

**Comment by geoffsim** [comment]
Ok, all done. Please consider for merging .
An issue raised in discord groups found a problem that was crashing some F722 flight controllers, but this ended up being a hardware issue. However, it did prompt me to redesign the HD Zero OSD code to reduce the amount of data being sent to the VTX and to stop sending altogether if the VTX is not detected.

**Comment by DzikuVx** [comment]
Thanks @geoffsim I'll quickly check analog functions and DJI for regression and then we will go futher

**Review by DzikuVx — CHANGES_REQUESTED** [review]
This PR breaks Analog OSD function, no OSD elements are visible

**Comment by geoffsim** [comment]
I’ll set up an analog system and test tomorrow.

**Comment by DzikuVx** [comment]
Thanks @geoffsim 
I think it's connected with changed visibility flag

**Comment by geoffsim** [comment]
Fixed, tested, and added to the PR.
The initialisation in fc_init.c was stealing the displayPort regardless of whether HDZero was selected or not.
I followed the example of the frsky code to fix this.
I had also broken the analog AHI display when I reduced the calls to drawScreen(). I have reverted that change.

Regards,
Geoff.

**Comment by error414** [comment]
Does it work with all HD-receivers?

**Comment by geoffsim** [comment]
All HDZero VTX and VRX models, yes.

**Comment by geoffsim** [comment]
I have some more changes to come in the next few days. Please do not review until then.

**Comment by DzikuVx** [comment]
Ok. But I'd like to have the final code until end of this week as well.
Maybe beginning of the next as I'd like to release RC for 4.1 in the last
week of January

wt., 18 sty 2022, 09:02 użytkownik Geoff Sim ***@***.***>
napisał:

**Comment by geoffsim** [comment]
Changes complete. Please review.

**Comment by DzikuVx** [comment]
Nice! I'll test and review when I will find a moment

**Comment by geoffsim** [comment]
I promise to not make any more changes! That last one was important to facilitate the "OSD OFF" mode.
The changes have been flight tested with success.

Known issue (HDZero VTX specific):
When exiting the Camera or VTX menus, the OSD will not redraw fully.
This will be fixed in the next VTX update (not iNav).
A temporary work around is to switch to a different OSD (or OSD OFF) and back again.

**Comment by DzikuVx** [comment]
And it's merged. I will run some more tests and build PR1 for 4.1 quite soon

**Pull request merged**
