### PR TITLE
Generate CLI settings at build time

### PR DESCRIPTION
**Pull request by fiam**
Generate CLI settings at build time. This allows packing the setting names and their min/max values, saving a bit of space.

The generator is written in Ruby and it's transparently executed from the Makefile during the build process. This means that Ruby is now required in order to build INAV.

The Makefile could use some work, since right now the generated settings are removed before building the target in order to force a rebuild. I'm sure someone else can come up with a better approach to avoid re-running the generator if nothing that might affect it has changed.

Current savings in an F1, F3 and F4 target:

```
| Filename              | Prev size | Cur size | Change |
---------------------------------------------------------
|         inav_CC3D.elf |    125256 |   122268 |  -2988 |
| inav_OMNIBUSF4PRO.elf |    205334 |   201854 |  -3480 |
|   inav_SPRACINGF3.elf |    180916 |   177804 |  -3112 |
```

### CODE REVIEW

**Comment by digitalentity** [comment]
@fiam what do I need to install to build this? I'm getting this error:
```
./tools/settings.rb:696:in `block in resolve_types': Could not resolve type for member looptime in group PG_GYRO_CONFIG (RuntimeError)
        from ./tools/settings.rb:468:in `block (2 levels) in foreach_enabled_member'
        from ./tools/settings.rb:466:in `each'
        from ./tools/settings.rb:466:in `block in foreach_enabled_member'
        from ./tools/settings.rb:464:in `each'
        from ./tools/settings.rb:464:in `foreach_enabled_member'
        from ./tools/settings.rb:694:in `resolve_types'
        from ./tools/settings.rb:644:in `sanitize_fields'
        from ./tools/settings.rb:251:in `initialize'
        from ./tools/settings.rb:807:in `new'
        from ./tools/settings.rb:807:in `<main>'
make[1]: *** [Makefile:929: src/main/fc/settings_generated.h] Ошибка 1
```

**Comment by fiam** [comment]
@digitalentity You should only need ruby and arm-none-eabi-g++ in your $PATH

**Comment by digitalentity** [comment]
Both are in the path, but the type detect file doesn't build. In fact `arm-none-eabi-g++` doesn't find the file while it's actually there. Might be a CYGWIN-related issue, but then it's really a show-stopper.

**Comment by digitalentity** [comment]
Damn, seems to be a CYGWIN-related bug indeed - arm-none-eabi toolchain can't handle absolute paths under cygwin. Can we use a relative path for test file?

**Comment by fiam** [comment]
@digitalentity Just pushed a commit using a relative path for the temporary dir. Let me know if that fixes the build on Windows.

**Comment by digitalentity** [comment]
Thanks for quick response. Wouldn't it be safer to create a temp dir under
obj instead of project root?

**Comment by fiam** [comment]
@digitalentity That's definitely a better idea. I'll change it to use `obj/tmp` rather than just `tmp`. I was just trying to hack something quickly since time was a bit tight today. Did you get a chance to test in on Windows?

**Comment by digitalentity** [comment]
@fiam now it builds on cygwin correctly.

**Comment by fiam** [comment]
@digitalentity Thanks for testing it! Should we start updating the development docs then?

**Comment by digitalentity** [comment]
@fiam I think we can add a requirement to have Ruby to teh dev docs, move the temp file to "obj" folder and merge this.

**Comment by digitalentity** [comment]
@fiam can you resolve conflict with latest development? Merging of #2030 seems to have created a conflict.

**Comment by fiam** [comment]
@digitalentity Conflicts resolved. It was just because a call to `sl_strncasecmp()` in cli.c was replaced by `clivalue_name_exact_match()`. Just pushed the branch to get Travis working on the checks and I'll push the doc changes later.

**Review by digitalentity — COMMENTED** [review]
:+1:

**Comment by fiam** [comment]
@digitalentity This should be now ready to merge. Please, take a look at the Ruby install instructions for Windows. I'm working under the assumption that RubyInstaller will set up the PATH, but it might not be the case and I don't have a Windows machine nor VM to test it right now.

**Comment by digitalentity** [comment]
@fiam thanks! I'll test once more and merge tomorrow.

**Comment by stronnag** [comment]
In field pulled, built, installed and flight tested on SPF3EVO and OMNIBUS.

No problems (free flight, PH, RTH, WP).

Great job @fiam.

**Comment by giacomo892** [comment]
Tried a build on my Mint PC. All ok :) @fiam

**Comment by digitalentity** [comment]
Also tested on multiple boards - no build or usage issues. Great job! 
The only drawback is that `settings_generated.c` is regenerated each build (quite a minor issue though).

**Comment by GitGoogol** [comment]
Hi guys, I know it's absoluteley not up to date but since i still have a NAZE with F1 controller I wanted to get it running. So I loaded the 1.7.3 and tried to build it with docker. After a few adaptations i could run the build process but it fails with a fatal error because it cannot find the cstddef-header which is used in the ruby compile_test_file routine from the settings.rb. Since I do not understand exactly what that function is doing my question would be if I just can delete the cstddef entry? Without it, it builds but I am not sure if everything will work well.

**Pull request merged**
