### PR TITLE
Port BetaFlight diff cli command

### PR DESCRIPTION
**Pull request by sambas**
First try on useful diff command from BetaFlight. Ugly merge but most parts working now.
Pending issues:
Rates dump is corrupted when change profile
Resources dump needs fix

### CODE REVIEW

**Comment by stronnag** [comment]
Much appreciated. Tried on AIRBOT-F4. Can't say I've seen any corruption, probably I'm not looking hard enough (and I ony have one profile set up). Sadly, exceeds flash size on F1.
````
/usr/lib/gcc/arm-none-eabi/6.2.0/../../../../arm-none-eabi/bin/ld: obj/main/inav_NAZE.elf section `.data' will not fit in region `FLASH'
/usr/lib/gcc/arm-none-eabi/6.2.0/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 260 bytes
````
Removed ibus and it builds on F1 too. Crunch time for F1 is not far off.
````
   text	   data	    bss	    dec	    hex	filename
 127908	   1020	  18408	 147336	  23f88	./obj/main/inav_NAZE.elf
````

**Comment by digitalentity** [comment]
@sambas we probably also need a `#define` to control on what targets this command is available

**Comment by digitalentity** [comment]
@sambas how is this coming along?

**Comment by sambas** [comment]
Haven't had time to continue this and this week is filled with other stuff

**Comment by digitalentity** [comment]
@sambas can you rebase on latest dev? I'm eager to have this in 1.5

**Comment by sambas** [comment]
rebase not possible without complete rewrite

**Comment by digitalentity** [comment]
Pity to hear :(

**Pull request closed without merging**
