### PR TITLE
WSL error troubleshooting

### LINKED ISSUE #6139: Problem with building in Windows 10 with Linux Subsystem
Hello,
I followed the instructions given here:
https://github.com/iNavFlight/inav/blob/master/docs/development/Building%20in%20Windows%2010%20with%20Linux%20Subsystem.md

In step: make MATEKF405
pb_compilation
Thank you for any good advice.

### PR DESCRIPTION
**Pull request by DzikuVx**
closes #6139

### CODE REVIEW

**Comment by Scavanger** [comment]
There is an easier solution:
 
Add this
`
[Interop]
appendWindowsPath = False
`
to /etc/wsl.conf

**Comment by stronnag** [comment]
Documentation PRs are welcome ....

**Comment by DarkSoulRL** [comment]
Not help.
```
venq@venq:~/inav/inav/build$ export | grep "PATH"
declare -x PATH="/usr/lib/ccache:/home/venq/ardupilot/Tools/autotest:/opt/gcc-arm-none-eabi-6-2017-q2-update/bin:/home/venq/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
venq@venq:~/inav/inav/build$ make MATEKF722
Generating MATEKF722/settings_generated.h, MATEKF722/settings_generated.c
/bin/sh: 1: Syntax error: "(" unexpected
make[3]: *** [src/main/target/MATEKF722/CMakeFiles/MATEKF722.elf.dir/build.make:63: src/main/target/MATEKF722/MATEKF722/settings_generated.h] Error 2
make[2]: *** [CMakeFiles/Makefile2:32740: src/main/target/MATEKF722/CMakeFiles/MATEKF722.elf.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:32586: src/main/target/MATEKF722/CMakeFiles/MATEKF722.dir/rule] Error 2
make: *** [Makefile:13313: MATEKF722] Error 2
venq@venq:~/inav/inav/build$
```

**Comment by DarkSoulRL** [comment]
fixed. Need again run
```
mkdir build
cd build
cmake ..
```

**Pull request merged**
