### PR TITLE
Adsb support pingRX  / Aerobit TT-SC1

### PR DESCRIPTION
**Pull request by error414**
ADSB support for uAvionix pingRX (not tested) and Aerobit TT-SC1 (tested), data are sent over mavlink ADS_VEHICLE frame.
OSD displays the nearest ADSB equipped aircraft.
OSD adsb data flashes as warning if within set distance for proximity warning of other aircraft

Can be set:
* distance limit for showing adsb info
* distance warning limit, for blinking
* limit for altitude for ingnoring plane, for example planes in 10km are not interested for us (planes below are always displayed)

example is here https://youtu.be/Xk7tzsXhkZA?si=uvn9MfoWO949a6Xd&t=30 test plane is approx 3.8km far away from start point and 1000m height ASL. 

        vehicle->icao = 666;
        vehicle->lat = 492383514;
        vehicle->lon = 165148681;
        vehicle->alt = 100000;
        vehicle->heading = 180;
        vehicle->flags = ADSB_FLAGS_VALID_ALTITUDE | ADSB_FLAGS_VALID_COORDS;
        vehicle->altitudeType = 0;
        vehicle->emitterType = 6;

adsb1
adsb3
adsb5
adsb4

this PR is based on #6924 from@ShikOfTheRa 
PR for configurator: https://github.com/iNavFlight/inav-configurator/pull/184

### CODE REVIEW

**Comment by mmosca** [comment]
Can you run src/utils/update_cli_docs.py to update Settings.md based on the yaml file?

**Comment by error414** [comment]
Done. Thank you very much,

BTW:  I did not change font, I just used character from MCM file which did not have constant in code, MCM files are unchanged.

**Comment by DzikuVx** [comment]
Thanks! Let's try to schedule this to INAV 7.1

**Comment by error414** [comment]
test flight on atom RC dolphin  https://www.youtube.com/watch?v=xqU5KwK9kds 

image

**Comment by konstkarapan** [comment]
Are there any other cheaper alternative modules?

**Comment by jasc76** [comment]
> Are there any other cheaper alternative modules?
There will be a test of the ADSBee receiver

**Comment by DarthPlasma** [comment]
How to configure the ADS-B module? Set MSP on the port there the receiver is connected and it is already working? There are no instructions as far as I can see

**Comment by jasc76** [comment]
> How to configure the ADS-B module? Set MSP on the port there the receiver is connected and it is already working? There are no instructions as far as I can see

Look in the first post here. You have to connect it to a UART and set it to MAVLINK. Be sure to also set the baud rate correctly.
Then you should see the data in the GPS tab of the configurator

**Comment by sensei-hacker** [comment]
> How to configure the ADS-B module? Set MSP on the port there the receiver is connected and it is already working? There are no instructions as far as I can see

Please let us know if you see anything confusing in the docs:
https://github.com/iNavFlight/inav/blob/master/docs/ADSB.md

**Comment by DarthPlasma** [comment]
> > How to configure the ADS-B module? Set MSP on the port there the receiver is connected and it is already working? There are no instructions as far as I can see
> 
> Please let us know if you see anything unclear in the docs: https://github.com/iNavFlight/inav/blob/master/docs/ADSB.md
> 
> Writing clear documentation is _hard_ because the person writing it already knows the information - so it's hard for them to put themselves in the position of someone who doesn't already know. So feedback on documentation is always welcome.

Does it disabile the RX telemetry (Crossfire) OR they work independendly?

**Comment by DarthPlasma** [comment]
Anyway, i will test VS26-T11 abs-b receiver that works with mavlink protocol

**Pull request merged**
