### PR TITLE
Remove killswitch

### PR DESCRIPTION
**Pull request by DzikuVx**
As a bonus we get rid of not neede `MSP_ARMING_CONFIG` and `MSP_SET_ARMING_CONFIG` MSP frames

### CODE REVIEW

**Comment by Jetrell** [comment]
@DzikuVx  Having the ability to set this function to OFF, is rather useful. By not allowing the FC to disarm unless the throttle is low.
The reason being. Is because if the pilot accidentally disarms his plane at a distance. The VTX will fall back to standby power, loosing the video link. And the HD DVR will stop recording.

I know some may say that if you lower the throttle later it will disarm anyway.. But maybe not many kilometers away.
There is a way I work around this. Its by having a audio siren on the radio go off if the FC is disarm when the telemetry is showing the GPS speed is over 20km/h.. This informs you of an accidental disarm.

**Comment by MrD-RC** [comment]
Though I completely agree with removing this. It may be worth waiting until the VTX is kept high power in the emergency rearm period. I’m hoping this will be in 8.0. But my initial tests the MSP didn’t obey keeping the arming state as armed (https://github.com/iNavFlight/inav/pull/9688)

**Comment by DzikuVx** [comment]
@Jetrell KILLSWITCH removal is not connected with the state of VTX and should be considered as separate elements. What KILLSWITCH was doing was disarming just like regular disarm with the switch.

VTX high power after disarm can be implemented separately from this change

**Comment by DzikuVx** [comment]
Additionally @Jetrell disarm regardless of THR value is a thing for a few years. I think you might have mistaken the KILLSWITCH mode with "disarm in any throttle aka killswitch". Those are 2 completely different things and the later one was removed years ago

**Comment by Jetrell** [comment]
> Additionally disarm regardless of THR value is a thing for a few years. I think you might have mistaken the KILLSWITCH mode with "disarm in any throttle aka killswitch". Those are 2 completely different things and the later one was removed years ago

That's fine if its not.. I was just going off what was written in the Doc Update commit. It seemed to indicate it was the disarm kill switch ?

daks

**Comment by DzikuVx** [comment]
ok, you are right. I will make adjustments tonthe code

**Pull request merged**
