### PR TITLE
[OMNIBUS F4] Enable UART6 inverter control

### PR DESCRIPTION
**Pull request by jflyper**
PR status: Requires discussion and feedback
```
// Inverter control pins
// - PC0 has never been used as inverter control on any of the genuine OMNIBUS F4 boards, but leave it as some clones actually implemented it.
// - PC8 is only used on OMNIBUS F4 V3, and actually is CH6 input.
// It conflicts with softserial, but should not be a problem if softserial
// is not turned on and used for some purpose.
// I Hope that a V3 user come to notice that they can't use the softserial
// before turning it on and assign some function; V3 does not have CH6 (nor CH5)
// pads after all ;)

#define INVERTER_PIN_UART1      PC0 // PC0 has never been used as inverter control on genuine OMNIBUS F4 variants

#define INVERTER_PIN_UART6      PC8 // Only for OMNIBUS F4 V3
```

### CODE REVIEW

**Comment by jflyper** [comment]
I think this doesn't work. It breaks softserial on non-V3 boards as soon as UART6 is used (inverted or un-inverted).

We probably need a new target ... :sob:

OMNIBUSF4V3?

**Comment by digitalentity** [comment]
Agreed, let's make it a variant of OMNIBUSF4 (similar to OMNIBUSF4PRO)

**Comment by jflyper** [comment]
`timerHardware` array shifted (reduced) by two.

**Comment by jflyper** [comment]
This is way too ugly...

Reordering `timerHardware` array would make these ifdefs go away.

@digitalentity What do you think?

**Comment by digitalentity** [comment]
Timer handling code is a mess. I'm looking into doing a different timer mapping approach (similar to what Betaflight does, but in a different way).
@jflyper have a look at https://github.com/iNavFlight/inav/pull/1591 - this is what I intend to merge once @martinbudden have some time to review it.

**Comment by jflyper** [comment]
@digitalentity Ah, okay, then I'll just keep the PR as is.

**Comment by jflyper** [comment]
@silent-testers This is the OMNIBUSF4V3 firmware at this moment.

[inav_1.7.1_OMNIBUSF4V3-1.hex.zip](https://github.com/iNavFlight/inav/files/1067286/inav_1.7.1_OMNIBUSF4V3-1.hex.zip)

**Comment by DzikuVx** [comment]
@jflyper I just got Omnibus F4 v3 so if you do not mind, I will take from here, convert this to INAV branch, fix conflicts and test. In case of problems, I know where to find you :)

**Comment by jflyper** [comment]
@DzikuVx Ack 👍

**Comment by DzikuVx** [comment]
work moved to #1889 Closing this one. Thanks @jflyper

**Pull request closed without merging**
