### PR TITLE
Add BETAFLIGHTF4 target support

### PR DESCRIPTION
**Pull request by shellixyz**
* Based on CF/BF target definition
* Linked issue: #2564 
* Untested, feedback needed, I do not own this board.
* Latest test build: [inav_1.8.1_BETAFLIGHTF4_draft_r7.hex](https://drive.google.com/open?id=15VGfWtLqndPNJ9OW9faG6Kb2hdc8eek_)

### CODE REVIEW

**Comment by shellixyz** [comment]
@Christiangrau @Rampiks1 Please test this

**Comment by Rampiks1** [comment]
Hey, I tried flashing it, but after flash is done it doesn't reboot and when I remove the USB and connect it again I get a popup saying somthing like "Windows can't detect this device", if i flash in betaflight it connects and works fine, and if a flash a Omnibus f4 clone in iNav it also works fine
Hope this helps

**Comment by shellixyz** [comment]
@Rampiks1 Hello. Thanks for the feedback. What is the status LED doing when you power up the board ?

**Comment by shellixyz** [comment]
I updated the test build, please test it: ~~[inav_1.8.1_BETAFLIGHTF4.hex](https://drive.google.com/open?id=1VJoDIdv9ePQWmLxTmrMDVA13m77c2j8Z)~~

**Comment by Rampiks1** [comment]
Hey, I got to test it now, No change to the new test build, and the activity led is glowing blue constant even after removing the USB and connecting it again

**Comment by shellixyz** [comment]
@Rampiks1 I don't know what's going on for the moment then :/
@digitalentity Do you have any idea about what could be the blockage point ?

**Comment by digitalentity** [comment]
Not sure. I'm going to order a BFF4 board to troubleshoot. Any idea where I can get one?

**Comment by shellixyz** [comment]
@digitalentity When looking for docs I found these ones:
* https://www.fpvmodel.com/betaflightf4-flight-controller_g1351.html
* https://www.getfpv.com/betaflight-f4-flight-controller.html

**Comment by digitalentity** [comment]
Ordered one from FPVModel. Fingers crossed I'll get it before New Year :smile:

**Comment by shellixyz** [comment]
Great, fingers crossed :)

I updated the defines for ACC/GYRO/BARO maybe it is as simple as that.
@Rampiks1 Please test the updated build: [inav_1.8.1_BETAFLIGHTF4.hex](https://drive.google.com/open?id=1HdHG4n4F0g2Bmw2L3MSD94rRApWv09dU)

**Comment by Rampiks1** [comment]
@shellixyz Hey, it still has the exact same issue

**Comment by wx4cb** [comment]
i have a board if you need help testing, also Racedayquads here in florida has them too: https://www.racedayquads.com/collections/betaflight-products

Their shipping is top notch less than a week all over the us.

**Comment by wx4cb** [comment]
@shellixyz i just installed the code, any way i can get your target directory? i'm assuming that's all I would need to add into my git clone? Would love to work on this as well

**Comment by shellixyz** [comment]
@wx4cb The code is in this branch https://github.com/shellixyz/inav/tree/BETAFLIGHTF4_target

**Comment by wx4cb** [comment]
I noticed that there are a couple of defines missing when i compared it to the betaflight version for the same board. could it be that they are missing that's causing the issue?

namely the ones for the MAX chip etc?

`//#define USE_ESC_SENSOR
#define MPU6000_SPI_BUS		BUS_SPI1
#define USE_ACC_MPU6000
#define ACC_MPU6000_ALIGN       CW180_DEG
#define USE_GYRO_MPU6000
#define GYRO_MPU6000_ALIGN      CW180_DEG
#define BMP280_SPI_BUS		BUS_SPI2
#define BMP280_CS_PIN           PB3
#define MAX7456_SPI_BUS		BUS_SPI2
#define MAX7456_CS_PIN      PB12
//#define MAX7456_SPI_CLK         (SPI_CLOCK_STANDARD) // 10MHz // XXX
//#define MAX7456_RESTORE_CLK     (SPI_CLOCK_FAST) // XXX
#define USB_IO
#define VBUS_SENSING_ENABLED
//#define USE_SOFTSERIAL1
//#define USE_SOFTSERIAL2
#define SERIAL_PORT_COUNT       5 //VCP, USART1, USART2, USART3, USART6, SOFTSERIAL1, SOFTSERIAL2
//#define USE_ESCSERIAL // XXX
//#define ESCSERIAL_TIMER_TX_PIN  PB8 // (Hardware=0, PPM)
#define SPI1_NSS_PIN            NONE
#define SPI1_SCK_PIN            PA5
#define SPI1_MISO_PIN           PA6
#define SPI1_MOSI_PIN           PA7
/* XXX
*/
#define ADC_CHANNEL_1_PIN		PC1
#define ADC_CHANNEL_2_PIN		PC2
#define CURRENT_METER_ADC_CHANNEL	ADC_CHN_1
#define VBAT_ADC_CHANNEL		ADC_CHN_2
//#define LED_STRIP
//#define DEFAULT_RX_FEATURE      FEATURE_RX_SERIAL // XXX
//#define SBUS_TELEMETRY_UART     SERIAL_PORT_USART2 // XXX
#define SPEKTRUM_BIND
// USART3,
#define BIND_PIN                PB11

#define MAX_PWM_OUTPUT_PORTS 4
#define USABLE_TIMER_CHANNEL_COUNT 5
//#define USED_TIMERS             ( TIM_N(1) | TIM_N(2) | TIM_N(3) | TIM_N(4) | TIM_N(5) | TIM_N(8) | TIM_N(9) | TIM_N(10) )
#define USED_TIMERS             ( TIM_N(3) | TIM_N(8) | TIM_N(10) )`

**Comment by shellixyz** [comment]
~~MAX7456_SPI_CLK and MAX7456_RESTORE_CLK are not used in iNav~~
I thought so but it looks like I'm wrong you can uncomment and try.

**Comment by wx4cb** [comment]
I compiled your tree @shellixyz and flashed it to my brand new BFF4 board and it flashed ok and I can open it up in the conflagulator :D

I see the 16 meg data flash, the gyro and the accellerometer, i don't see a baro on this board so evreything looks right so far.

2017-12-13 @ 18:05:08 -- USB device successfully opened with ID: 12
2017-12-13 @ 18:05:09 -- Detected device with total flash size 1024 kiB
2017-12-13 @ 18:05:09 -- Read protection not active
2017-12-13 @ 18:05:27 -- Erased 1024 kB of flash successfully
2017-12-13 @ 18:05:48 -- USB device successfully closed
2017-12-13 @ 18:06:21 -- Serial port successfully opened with ID: 92
2017-12-13 @ 18:06:21 -- MultiWii API version received - 2.1.0
2017-12-13 @ 18:06:21 -- Flight controller info, identifier: INAV, version: 1.8.1
2017-12-13 @ 18:06:21 -- Running firmware released on: Dec 13 2017 17:52:57
2017-12-13 @ 18:06:21 -- Board: BFF4, version: 0
2017-12-13 @ 18:06:21 -- Unique device ID received - 0x32003d3436511937353431
2017-12-13 @ 18:06:21 -- PWM output is disabled. Motors and servos will not work. Use Configuration tab to enable!

**Comment by shellixyz** [comment]
@wx4cb Nice ! Did you change anything ?

**Comment by wx4cb** [comment]
@shellixyz no i downloaded the tree that you gave me as a zip file, extracted into a VM compiled and flashed onto the BFF4 board. in the process of wiring it up now so i can test later

**Comment by wx4cb** [comment]
here's a diff after i did some basic config and setup the receiver. I havent done anything else yet, i'm working on wiring up the esc and some servo leads etc

although i did just notice that I have uart6 as the sbus receiver, vcp for the configurator and msp on uart 1 was turned on, so i turned that off.

I also turned on the voltage and current monitoring and also things like the telemetry etc
# version
# INAV/BETAFLIGHTF4 1.8.1 Dec 13 2017 / 17:52:57 ()

# resources

# mixer
mixer AIRPLANE

# servo

# servo mix

# feature
feature VBAT
feature MOTOR_STOP
feature CURRENT_METER
feature LED_STRIP
feature AIRMODE
feature PWM_OUTPUT_ENABLE

# beeper

# map

# name

# serial
serial 0 0 115200 38400 0 115200

# aux

# adjrange

# rxrange

# master
set gyro_sync = ON
set gyro_hardware_lpf = 188HZ
set acc_hardware = MPU6000
set baro_hardware = NONE
set pitot_hardware = NONE
set receiver_type = SERIAL
set rssi_channel = 16
set min_throttle = 1070
set max_throttle = 1900
set small_angle = 180
set gps_provider = UBLOX7

# profile
profile 1

set fw_p_pitch = 20
set fw_i_pitch = 30
set fw_ff_pitch = 15
set fw_p_roll = 20
set fw_i_roll = 30
set fw_ff_roll = 15
set fw_p_yaw = 45
set fw_i_yaw = 5
set fw_ff_yaw = 15
set fw_i_level = 15
set pitch_rate = 15
set yaw_rate = 9

**Comment by shellixyz** [comment]
It's odd it didn't work for @Rampiks1. @wx4cb could you try the build linked in the first comment ?

**Comment by wx4cb** [comment]
this one worked fine @shellixyz 
# version
# INAV/BETAFLIGHTF4 1.8.1 Dec 11 2017 / 14:45:28 (33695c59)
> 

Based on CF/BF target definitionLinked issue: #2564Untested, feedback needed, I do not own this board.Test build: inav_1.8.1_BETAFLIGHTF4.hex
--

**Comment by wx4cb** [comment]
that being said.... i mean i can flash it and connect it to the configurator. i haven't tested it further than that yet

**Comment by wx4cb** [comment]
i do get the same as @Rampiks1 where windows says it doesn't recognise the device, but it still works fine. on all three builds, but i can still connect ok

**Comment by ghost** [comment]
Hey peeps, new here out of interest for the project! Cant program but I can test this for you. 
I have a wing all wired and ready to go with the BF F4.  @shellixyz I loaded up your version and went through setup. All is working normally but something seems to be wrong with the PPM input. I fixed the ports UART 3 is GPS UART 1 is FRSKY telemetry. When PPM is selected and then hit save and reboot I get the problem described above and the board cannot connect anymore..Reflashing all gets back to normal although a receiver protocol is not selected by default. Hope this is somewhat helpful.

**Comment by Christiangrau** [comment]
Correct me if i'm wrong, isn't the UART1 used as the USB connector? You can't Power the RX while usb is plugged in?

**Comment by ghost** [comment]
The RX is powered normally via USB. The board uses VCP so I don't think there's conflict. I also turned off the MCP on UART 1 to try but still got the same.

**Comment by ghost** [comment]
Small edit UART 1 uses FRSKY telemetry; no problem with that.
When receiver is selected as PPM, which is a separate input it hangs and doesnt recognize.

**Comment by ghost** [comment]
Yap definitely something wrong with PPM! On betaflight firmware it works fine.

**Comment by tasi0000** [comment]
I've been scrolling through the BF repo and I saw there were some issues with timers here
https://github.com/betaflight/betaflight/pull/4183/files

Note: Edited my account and now im ghost above....

**Comment by wx4cb** [comment]
Uart3 on the boards i have are for the svus.ppm.dsmx pins on the fc. Uart1
should have msp turned off as its a vcp board.

Dsmx is uninverted pin sbus.ppm pin is the inverted one

**Comment by tasi0000** [comment]
@wx4cb hmmm, I donno if it makes sense, cause i see the SBUS/PPM input is the same and PPM shouldn't use a UART. If SBUS was connected then it would normally use UART 6, while smartport and smartaudio require modification of UART 3 to soft serial. The same exact setup works fine with the latest BF firmware. What do you suggest?

**Comment by wx4cb** [comment]
I have my x8r hooked to the sbus PIN and it shows up on you ought 6

**Comment by wx4cb** [comment]
Uart 1 and 3 are broken out to the edge of the board you cannot modify uart 3 on the Bf4 because that's where the i2c is that you will need for an M8N  GPS and compass

**Comment by shellixyz** [comment]
If the issue is related to the PPM input you could try to modify the timer for the PPM input to timer 4 channel 3 also supported by the PB8 pin. Don't forget to add timer 4 to the used timers in target.h.

**Comment by tasi0000** [comment]
@wx4cb thanx for your input! so we're dead square here 👍 
@shellixyz thanx for your suggestions! I wish I could do that, but unfortunately I wouldn't know how to! I'm no developer, just willing to test things and report back :)

**Comment by shellixyz** [comment]
Build with the last suggested mod: [inav_1.8.1_BETAFLIGHTF4_draft_r4.hex](https://drive.google.com/open?id=1kBubNT6IDAdXTJUzikSFPbybl-jLQfPO)

**Comment by wx4cb** [comment]
Which change exactly? Making uart3 softserial might break i2c?

**Comment by wx4cb** [comment]
I also can't test anything till i get home. Im in miami atm

**Comment by shellixyz** [comment]
The one I was talking about in https://github.com/iNavFlight/inav/pull/2573#issuecomment-351754080

**Comment by tasi0000** [comment]
@shellixyz PPM input is sorted with r4 !!!

**Comment by shellixyz** [comment]
@tasi0000 Good ! I would like to know why it would work better by using TIM4 for the PPM input though.
@ those who may know: could it be because of a conflict between TIM8 and TIM10 ? But why would it be working in Betaflight ?

**Comment by wx4cb** [comment]
Would this affect sbus? as theyre on the same pin?

**Comment by shellixyz** [comment]
@wx4cb It should not. Hardware UARTs don't use timers.

**Comment by wx4cb** [comment]
Just checking heh

**Comment by Rampiks1** [comment]
Weird, it still doesn't work for me what flashing settings are you using? (talking about no reboot sequence etc.)

**Comment by wx4cb** [comment]
@Rampiks1 i'm just using the defaults everything off other than full chip erase -> load local firmware -> flash - obviously make sure that the board is in dfu mode by powering up and holding the boot button in.

**Comment by wx4cb** [comment]
@shellixyz  R4 works as advertised. BFF4, X8R in sbus mode, motor on motor-1 (with BEC power removed)

**Comment by wx4cb** [comment]
here's my DIFF:

# version
# INAV/BETAFLIGHTF4 1.8.1 Dec 14 2017 / 17:55:28 (8100bd00)

# resources

# mixer
mixer AIRPLANE

# servo

# servo mix

# feature
feature VBAT
feature MOTOR_STOP
feature CURRENT_METER
feature LED_STRIP
feature AIRMODE
feature PWM_OUTPUT_ENABLE

# beeper

# map

# name

# serial
serial 0 0 115200 38400 0 115200

# aux
aux 0 0 0 1700 2100
aux 1 1 1 900 1300

# adjrange

# rxrange

# master
set gyro_sync = ON
set gyro_hardware_lpf = 188HZ
set acc_hardware = MPU6000
set acczero_x = 128
set acczero_y = 10
set acczero_z = -308
set accgain_x = 4082
set accgain_y = 4067
set accgain_z = 4058
set baro_hardware = NONE
set pitot_hardware = NONE
set receiver_type = SERIAL
set rssi_channel = 16
set small_angle = 180

# profile
profile 1

set fw_p_pitch = 20
set fw_i_pitch = 30
set fw_ff_pitch = 15
set fw_p_roll = 20
set fw_i_roll = 30
set fw_ff_roll = 15
set fw_p_yaw = 45
set fw_i_yaw = 5
set fw_ff_yaw = 15
set fw_i_level = 15
set pitch_rate = 15
set yaw_rate = 9

**Comment by wx4cb** [comment]
Current things I noticed:

UART 1 MSP should be disabled as it's a VCP board
Current and battery monitoring should be ON by default
Serial RX is fine for Uart6 as that's where they should be hooking them up

If I see more then i'll drop a note

**Comment by shellixyz** [comment]
> UART 1 MSP should be disabled as it's a VCP board

UART1 has MSP enabled on purpose, see https://github.com/iNavFlight/inav/issues/2569#issuecomment-350397600

> Current and battery monitoring should be ON by default

Indeed

> Serial RX is fine for Uart6 as that's where they should be hooking them up

Not everybody uses serial RX

**Comment by shellixyz** [comment]
~~Maybe OSD should be enabled by default too ?~~
It is already

**Comment by wx4cb** [comment]
@shellixyz yea the issue is, as stated in that thread, it can screw up the usb if you have a GPS on there because of MSP overrun - same thing happened with betaflight IIRC, which was why it was disabled on VCP boards. as for uart6 it's fine the way it is :P my point was that the dsm/sbus/ppm pads for the serial rx are UART 6 i guess putting that in a doc somewhere would be the way to go.

OSD should be enabled too... those are the basics that should be on, that and blackbox maybe seeing as it does have a dataflash

**Comment by tasi0000** [comment]
For the USB issue I can connect consistently on my desktop but on my laptop I have to plug unplug several times before the device is recognized. Donno what could be the cause of that. I also noticed a packet error notification 1 bottom left in the configurator.  This appears at all times. Using rev4.  I can arm move control surfaces change modes and so forth. For the GPS I changed the connection to UART 2 and moved the power wire where the CAM 5V is meant to be plugged in.  I noticed that UART 1and 3 don't get power via the USB while the cam 5 volt does. All of these 5v outputs in fact. I also had to enable cpu based spi and serial to get the GPS to work. I'll put a diff up here later. 

EDIT: Packet error is gone...maybe had something to do with the GPS.

**Comment by tasi0000** [comment]
Here's my CLI diff for the current functioning setup (not flown yet). The only thing that I notice now is an issue with the OSD. There's currently no way to setup the CRAFT name, position parameters. 

[S800 inav r4.txt](https://github.com/iNavFlight/inav/files/1562216/S800.inav.r4.txt)

**Comment by shellixyz** [comment]
@tasi0000 

> I can connect consistently on my desktop but on my laptop I have to plug unplug several times before the device is recognized

What OS are you using on both ?

> I noticed that UART 1and 3 don't get power via the USB while the cam 5 volt does

That's hardware dependent. UARTs don't provide power. The ESC/servo power rail and possibly other power pads on FCs are often not supplied from the FC 5V you need to supply them with an external power source.

> I also had to enable cpu based spi and serial to get the GPS to work

I don't think "cpu based spi and serial" is what you think it is. It should have no effect on your GPS connected on UART2.

**Comment by wx4cb** [comment]
@tasi0000 That's strange. my receiver is hooked up via uart3 with the respective 5v and ground pads that are right next to the SBUS pin.

When i plug it in via the USB it powers the receiver. can you take a picture of your board?

Also, I agree that cpu based spi etc shouldn't be enabled. that being said, my compass/gps etc  doesn't arrive until tomorrow so i can't be sure.

**Comment by wx4cb** [comment]
ok i can confirm that gps using an M8N works ok, i can see messages coming through on UART 1, im inside  so no fix, but i can see the message counter going up and if i leave it long enough it eventually gets a fix.

The only issue now is I2C for the compass. @shellixyz I tried using the R4 branch and commenting out the UART 3 stuff in the target.h and enabling the I2C for the same pins (PB10/PB11).

In betaflight this works ok if I follow this thread: https://github.com/betaflight/betaflight/issues/3853

"This is my first experience with betaflight so thanks for your patience. I tried to follow the I2c thread for the Omnibus F4. Is it true that the I2c SDA, SCL share the resource provided to UART3? 
Do I need to make the reassignment in resources that show
resource i2c_scl 2 b10
resource i2c_sda 2 b11

and move it to the resource pins being used by UART 3?**"

Here's my "status" and my "resource list" after the changes 

# status
System Uptime: 120 seconds
Current Time: 2017-12-15T20:05:23.417+00:00
Voltage: 36 * 0.1V (1S battery - OK)
CPU Clock=168MHz, GYRO=MPU6000, ACC=MPU6000
STM32 system clocks:
  SYSCLK = 168 MHz
  HCLK   = 168 MHz
  PCLK1  = 42 MHz
  PCLK2  = 84 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=NONE, RANGEFINDER=NONE, OPFLOW=NONE, GPS=OK
Stack size: 6144, Stack address: 0x10010000
I2C Errors: 0, config size: 3175, max available config: 131072
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = none, used = none
   CURRENT : configured = ADC 1, used = ADC 1
  AIRSPEED : configured = none, used = none
System load: 1, cycle time: 1002, PID rate: 998, RX rate: 49, System rate: 9
Arming disabled flags: ACC RX THR CLI

# resource
IO:
----------------------
A00: FREE 
A01: FREE 
A02: FREE 
A03: FREE 
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
A08: FREE 
A09: SERIAL1 UART TX
A10: SERIAL1 UART RX
A11: USB IN
A12: USB OUT
A15: FLASH CS
B00: MOTOR1 OUT
B01: MOTOR2 OUT
B03: SPI_PREINIT CS
B04: BEEPER OUT
B05: FREE 
B06: FREE 
B07: FREE 
B08: FREE 
B09: FREE 
B10: I2C2 SCL
B11: I2C2 SDA
B12: OSD CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE 
C01: ADC CH1
C02: ADC CH2
C03: FREE 
C04: MPU EXTI
C05: FREE 
C06: FREE 
C07: SERIAL6 UART RX
C08: MOTOR4 OUT
C09: MOTOR3 OUT
C10: SPI3 SCK
C11: SPI3 MISO
C12: SPI3 MOSI
C13: INVERTER OUT
D02: FREE

**Comment by shellixyz** [comment]
I originally disabled I2C2 for testing purposes and forgot about it. It is enabled again in r6. Try r6 with UART3 disabled it should work fine and by disabled I mean you shouldn't have any device enabled on it in the ports tab.

[inav_1.8.1_BETAFLIGHTF4_draft_r6.hex](https://drive.google.com/open?id=12a3hLh_V2-QpwlMQdqLAtAjAuR4yFsaO)

**Comment by wx4cb** [comment]
@shellixyz not working :(  "resource" shows B10 and B11 as "FREE" im not sure what would need to change for uart 3 side of things to enable i2c on those pins.

I'm waiting to find out if i am right in that they are on Uart3

**Comment by shellixyz** [comment]
Please try r7, MAG was not enabled

[inav_1.8.1_BETAFLIGHTF4_draft_r7.hex](https://drive.google.com/open?id=15VGfWtLqndPNJ9OW9faG6Kb2hdc8eek_)

**Comment by wx4cb** [comment]
yup so far so good. i can see it in the sensors tab. now to figure out how to use 1 esc on motor 1, and servos on motor outputs 2/3/4 (only has 4 outputs) in airplane mode LOL

**Comment by shellixyz** [comment]
Great! That's another issue :grin:

**Comment by tasi0000** [comment]
@shellixyz both of my machines are windows 10 x64bit. For the 5v sure it's a hardware thing but it's interesting that I don't get the voltage throughout the 5v outputs.  Only the 5v rail at the cam,vtx UART 2 outputs. Funky board business,  I don't know. 

Also I went and maidened the s800 today still on R4 with the setup published above. Tried pass, angle and horizon modes and everything worked perfectly fine. I need to tune cause it flies like crap and I'll test out the nav modes too.  

@wx4cb I'll take a picture of the board tomorrow.

**Comment by tasi0000** [comment]
@shellixyz also wanted to mention that I was trying to resource UART pins to soft serial but I couldn't get it to work. Does resource command  work in INAV at all or is it a build specific issue?

**Comment by wx4cb** [comment]
@tasi0000 you can't remap resources on inav (yet?) they reckon it will cause a bunch of issues with people remapping stuff and blaming the devs when the code doesn't work. Doesn't help me (re airplane mixer) above

https://github.com/iNavFlight/inav/issues/1145 << See here

**Comment by tasi0000** [comment]
Right,  I wasn't aware!  Thanx!  In BF firmware you have to reassign UART 1 and 3 TX pins to soft serial in order to have smartport and smart audio working. Would it be possible to have some kind of routine/script in this target to have this or similar command executed via a switch depending on user preference?

**Comment by wx4cb** [comment]
@tasi0000 according to Oscar Liang, uart2 is inverted on both legs:

"You can use UART2 for SmartPort with some modification: you will need to get a small signal schottky diode connecting TX to RX, and connect Smart Port to the RX. And turn off tlm_halfduplex in CLI"

https://oscarliang.com/betaflight-f4-flight-controller/

**Comment by tasi0000** [comment]
and peeps, how are we doing ? Im still on rev4 :) tried some gps stuff today like autolaunch and alti hold but took ages to get a lock for some reason...everything seems to work fine! Any ideas with what to mess around now? Has anybody tried smartport, smartaudio and sbus ? I'm done till new year :)

**Comment by wx4cb** [comment]
@tasi0000 I know sbus works as that's how i'm doin g my receiver, on the SBUS p[in which comes in as UART 6

GPS is on UART1 here although bein g inside i can't get a lock but i do see gps messages going into the system. As far as smartport/audio i haven't done that yet, i'm working on trying to figure out th e mixes etc.

**Comment by shellixyz** [comment]
@tasi0000 I never used smartaudio nor S.Port with iNav. I can't say anything about smartaudio but I already used S.Port with Betaflight and as you said you will need either a Softserial port or a hardware inverter like [this one](https://quadmeup.com/smartport-inverter-for-f4-flight-controllers/). What is the model of your GPS module (link) ? All GPS modules are not created equal. I know the first I had were shitty ones and it was very annoying. Difficult to get a lock, losing lock when changing orientation... But also you need to keep it away from RF noise. The farther away from your control link receiver, ESC, VTX, telemetry modem the better. For flying wings I put the receiver in one wing, the GPS in the other and the VTX in the middle section.

**Comment by wx4cb** [comment]
@tasi0000 this is the GPS/Compass that I bought.

haven't tried it in earnest yet, it's all just spaghetti wired on my bench as i don't have a target to put it into yet.

As far as smartport/sport for the telemetry, see that oscar liang link i posted earlier. as far as locations, ytes i do the same thing. one in each wing.

https://www.amazon.com/gp/product/B012RNLG0K/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

**Comment by wx4cb** [comment]
@shellixyz  where is the number of LEDs defined (currently says 0 leds)? i can't seem to find it. That or im blind lol

**Comment by shellixyz** [comment]
@wx4cb If you are talking about the LED_STRIP feature here is how to define the LEDs:
https://youtu.be/0E_4K-H16Jk?t=4m8s

**Comment by wx4cb** [comment]
@shellixyz No. i know how to define the LEDS and their functions, but when you go into there it says you have "zero" leds available and won't let you place any. I don't think this is aBFF4 issue as ive seen other issues posted

**Comment by shellixyz** [comment]
@wx4cb I disabled the LED_STRIP on this board for testing purposes. You can enable it back by uncommenting this line in target.h:156

```
//#define LED_STRIP
```

**Comment by shellixyz** [comment]
@wx4cb If you test the LEDs and it is working please tell us I will enable the feature back.

**Comment by shellixyz** [comment]
@wx4cb Little mistake the right symbol is `USE_LED_STRIP`

**Comment by wx4cb** [comment]
I did that, and still shows 0 leds available for assigning. Not a big deal right now, working on an osd change - if i can ever get my board to go back into DFU mode lol

untitled

**Comment by CircuitBender** [comment]
hi there guys, I am currently testing the unstable BetaflightF4 version for inav on the hardware itself
if you have any questions what I should test or look for, let me know.

Current Issues:
unexpected dropouts of the TX (FRSKY X8R)  
while rebooting in inav: FC is not properly unmounted and cannot reconnect via USB
in inav modes: auto assign function does not work, channels are not the same numbering (ch1-ch16 instead of ch1-4 and aux1-8)

**Comment by CircuitBender** [comment]
LED are not working on inav (working in Betaflight)
i cannot assign LED, there are 8 LED hooked up, betaflight shows in wiring mode 0

- have to test if it works with USE_LED

shellixyz: "I disabled the LED_STRIP on this board for testing purposes. You can enable it back by uncommenting this line in target.h:156 "

//#define LED_STRIP

**Comment by CircuitBender** [comment]
@wx4cb check impulse rc bootloader driver fixer, or zadig

**Comment by wx4cb** [comment]
@CircuitBender  Been flying inav now for the last 2 weeks not noticed an y drop outs on my X8R, i have noticed that it doesn't init the OSD every now and again though. 

The unable to connect via USB is one i noticed yesterday and was a real pain. This i think is also the cause of me not being able to get into DFU mode reliably.

And of course same issue with the LEDs. Not had chance to work on it properly over christmas what with work and other crap

**Comment by CircuitBender** [comment]
I believe unplugging usb slightly and replugging it without losing power on the FC lets me connect after a few tries
- dfu mode: check impulse rc`s driver fixer

**Comment by digitalentity** [comment]
@shellixyz what's the status of this PR? I've received my board today, ready to test and debug :smile:

**Comment by wx4cb** [comment]
@digitalentity nice... it generally works with the exception of the servo outputs being mapped wrong (see above) and the LED strip. I have it running on a calypso with an m8n gps and i2c compass, due to the output issues with the servos i cannot really test any further, plus with work i haven't had much time to play, 

Here's a YT video from the other day (ignore the compass crap it's not REALLY calibrated :D 
 https://www.youtube.com/watch?v=-h4shq2lArM

**Comment by digitalentity** [comment]
I'm taking this over. Superseded by #2637

**Comment by tasi0000** [comment]
Gents, where can we find the latest .hex now? is it still the r7?

**Comment by tasi0000** [comment]
@wx4cb what servo output issues are you running into? 
I tested this on a flying wing and all outputs worked fine.

**Comment by wx4cb** [comment]
i haven't tested it since @digitalentity took it over - work, holidays etc. but basically the rudder channel was on "motor 6" which doesn't exist on that board

**Comment by tasi0000** [comment]
@wx4cb alright! must have missed the regular plane setup part :) thanx buddy!
what about the hex? would you know where to find the latest? @digitalentity any input ?

**Comment by wx4cb** [comment]
@digitalentity @shellixyz i'm ready to reflash with whatever we have. where can i find the latest code etc? is it in the main branch yet ?

**Pull request closed without merging**
