### PR TITLE
Restore sensor autodetection

### PR DESCRIPTION
**Pull request by digitalentity**
Add back sensor autodetection
Autodetection is only used once to update and save config. Next boot explicit sensor selection will be used.

### CODE REVIEW

**Comment by digitalentity** [comment]
`AUTO` values will only survive one boot - they won't be preserved. If autodetection failed - corresponding `*_hardware` will be set to `NONE` and detection will not be retried unless user sets `*_hardware` to `AUTO` again and reboots.

The only sensor that is still always autodetected is gyro because the board won't boot at all if gyro is not detected.

**Comment by stronnag** [comment]
Nice. I tested this on the EVO with external mag, and it sets the external mag. Exemplary good taste!

**Comment by digitalentity** [comment]
Kudos to @oleost for the idea

**Comment by oleost** [comment]
Tested on SPRACINGF3 with dji naza gps. Did clean erase and when restoring cli dump with mag = auto and flight battery connected it succesfully detected GPSMAG.

Also tested on AirbotF4 without any devices connected. Succesfully detected None.

Also succesfully tested on SPRACINGF3MINI.

But got two things.

**1:** I get compiler warning on this. Which is not present on latest development.

```
%% acceleration.c 
./src/main/sensors/acceleration.c: In function 'accDetect':
./src/main/sensors/acceleration.c:81:1: warning: label 'retry' defined but not used [-Wunused-label]
 retry:
 ^
%% battery.c 
```

**2:** In iNav MPU9250 has always been detected as MPU6500 (Basicle because it is an MPU6500 acc) (And is still detected as MPU6500 in this build)

But in this and later development build acc_hardware have an new value that is called "MPU9250" 
I tried to manually select acc_hardware = MPU9250 and the entire board freeze. And when I now try to connect it to the computer it wont recognize it and gives error message.

I had to short boot pins to flash firmware again.

SPRACINGF3MINI with MPU9250
```
# status
System Uptime: 8 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), System load: 0.01
CPU Clock=72MHz, GYRO=MPU6500, ACC=MPU6500, BARO=BMP280, MAG=AK8963
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, SONAR=NONE, GPS=NONE
Stack size: 2048, Stack address: 0x10002000
Cycle Time: 2002, I2C Errors: 0, config size: 2024

# get _hard
acc_hardware = MPU6500
Allowed values: NONE, AUTO, ADXL345, MPU6050, MMA845x, BMA280, LSM303DLHC, MPU6000, MPU6500, MPU9250, FAKE

baro_hardware = BMP280
Allowed values: NONE, AUTO, BMP085, MS5611, BMP280, FAKE

mag_hardware = AK8963
Allowed values: NONE, AUTO, HMC5883, AK8975, GPSMAG, MAG3110, AK8963, IST8310, FAKE


# 
```

**Comment by stronnag** [comment]
The SP EVO also freezes if you set manually `set acc_hardware = MPU9250`. If you leave acc_hardware alone, there is no problem.

**Comment by digitalentity** [comment]
I found the reason for freezes- fixing.
However, I beleive MPU9250 driver is unnecessary - it's generally a duplicate of MPU6500 driver but with some oddities regarding `gyro_lpf` configuration.

**Comment by digitalentity** [comment]
@oleost, @stronnag - issue fixed, redundant code for mpu9250 removed.

**Comment by oleost** [comment]
Great., Any of you had a chance to test it? My boot pins are not easily available.

**Comment by digitalentity** [comment]
I've re-tested on EVO and NAZE32. Seems to work.

**Comment by stronnag** [comment]
Flight tested on SPRF3 :)

**Comment by stronnag** [comment]
Bench tested on EVO. Manual `set acc_hardware = MPU9250` does not cause a freeze and is corrected to MPU6500.

**Comment by oleost** [comment]
@stronnag @digitalentity If dedicated MPU9250 driver is removed. Shouldnt the choice of selecting MPU9250 in acc_hardware table also be removed?

**Comment by stronnag** [comment]
It has been removed.
````
# get acc_hardware
acc_hardware = MPU6050
                      Allowed values: NONE, AUTO, ADXL345, MPU6050, MMA845x, BMA280, LSM303DLHC, MPU6000, MPU6500, FAKE
````

My initial test was to flash the baord and restore a dump containing `set acc_hardware = MPU9250`. Result: Board freezes.

Post last update, repeat the test, board does not freeze (unseen to me, the CLI would have rejected `acc_hardware` directive and done the right things). Apologies for not being clearer.

**Comment by oleost** [comment]
@stronnag Okey.

**Pull request merged**
