### PR TITLE
Nav position hold code refactor + related multirotor bug fix

### PR DESCRIPTION
**Pull request by breadoven**
Cleans up code related to handling of Nav waypoint hold positions and fixed wing loiter position control.

Also fixes an apparent bug for multicopter WP missions with `nav_mc_wp_slowdown` set OFF which causes toilet bowling during timed hold.

### CODE REVIEW

**Comment by breadoven** [comment]
@DzikuVx This has been tested on a FW and MC and seems to work OK. Include in 4.0.0 ?

**Comment by DzikuVx** [comment]
@breadoven if you think so, then let's go 4.0

**Comment by breadoven** [comment]
> @breadoven if you think so, then let's go 4.0

OK. Out of interest were the commits for https://github.com/iNavFlight/inav/pull/7649 cherry picked for 4.0.0 (given the PR was merged into master) ?

**Comment by Jetrell** [comment]
@breadoven I assume there wasn't an issue with this?  I was telling a guy about this PR, but we couldn't find any reference of it in 4.0.

**Comment by breadoven** [comment]
> @breadoven I assume there wasn't an issue with this? I was telling a guy about this PR, but we couldn't find any reference of it in 4.0.

There's no issue, it was included in the 4.0.0 release. Must have just been missed in the list of changes.

**Pull request merged**
