### PR TITLE
Support for Crazepony MINI flight controller and NRF24L01 transceiver

### PR DESCRIPTION
**Pull request by martinbudden**
This submission is a joint effort by @goebish and @martinbudden

@goebish provided
1. Crazepony MINI port to Cleanflight
2. NRF24L01 device driver
3. V202 transmitter protocol for NRF24L01
4. SPI implementation for CJMCU flight controller

@martinbudden provided:
1. Merge of code into latest version of Cleanflight
2. Some additional NRF24L01 device driver utility functions
3. SymaX, SymaX5C and Cheerson CX10 transmitter protocols for NFR24L01
4. Framework to allow setting of NRF24L01 transmitter protocol
5. Port from Cleanflight to iNav

NRF24L01 receiver code and transmitter protocols are all under build #defines that can be set in the target.h file, so there is no ROM cost to other flight controllers.

The V202 transmitter protocol allows Cleanflight to be used withwith WLtoys V2x2 transmitters. These are cheaply available for under £20.

The SymaX and SymaX5C transmitter protocols allow Cleanflight to be used with Syma transmitters. These are cheaply available for under £20.

The CX10 transmitter protocol allows Cleanflight to be used with Cheerson CX10 transmitters.

With any of these protocols a Walker Devo transmitter with Deviationtx software and NRF24L01 modification could be used.

See [Adding External Modules to Your Deviation Transmitter](http://www.deviationtx.com/wiki/rf_module_installation)

also http://www.hacksmods.com/2013/05/nrf24l01-devo7e-pinout/

### CODE REVIEW

**Comment by DzikuVx** [comment]
@martinbudden some kind of docs or at least setup guide would be great. How people would use it if they do not know how to do it?

**Comment by martinbudden** [comment]
@DzikuVx , yes, I'll put together some information on how to use this.

**Comment by DzikuVx** [comment]
Coolio

**Comment by digitalentity** [comment]
Amazing! I have a CX10 so I can test the CX10 protocol working with CC3D board.

**Comment by digitalentity** [comment]
@martinbudden do we have corresponding PR in Configurator to configure FEATURE_RX_NRF24 and protocol via GUI?

**Comment by digitalentity** [comment]
Since this PR is merged, we can start implementing #216

**Comment by martinbudden** [comment]
@digitalentity , no I've made no PRs for the configurator.

Be aware that there are different CX10 protocols, depending on the model. See http://www.deviationtx.com/wiki/supported_models for further info.

One of my plans is to make a brushed quad using a CC3D mini, one of these [tiny NRF24L01 boards](http://www.ebay.co.uk/itm/1-2-3-5-10x-Mini-Board-NRF24L01-SMD-1-7MM-Wireless-Transceiver-Module-1-9-3-6V-/371212850423?var=&hash=item566e0294f7:m:meaP0av5VK6ETche6gEMa-A) and some FETs.

I'd use a [Parrot Airborne Cargo frame](https://store.parrot.com/uk/accessoires-airborne-cargo/496-central-cross-airborne-cargo-travis-3520410029745.html) available for £4.99. These frames are pretty strong, and you can attach lego bricks or figures to them!

Then maybe add a GPS...

And yes, the optical flow stuff is very interesting.

**Comment by goebish** [comment]
Hi Martin,

A few changes are required in the GUI for the crazepony to work (RTS/DTS toggle), just a few lines:
https://github.com/cleanflight/cleanflight-configurator/compare/development...goebish:crazepony

**Comment by digitalentity** [comment]
@martinbudden thanks for the hint. I'm also going to use NRF24 TX/RX to build a mid-range airplane (up to 1-2 km range).

I'm also thinking about designing an own FC board (see #287)

**Comment by martinbudden** [comment]
@skaman82  , can you look at @goebish 's changes to the configurator?

**Comment by goebish** [comment]
Note that those additions will have no impact on other FC as DTR/DTS are usually not connected on other boards.

**Comment by skaman82** [comment]
@martinbudden can't see any PRs form @goebish in here: https://github.com/iNavFlight/inav-configurator/pulls

**Comment by goebish** [comment]
I haven't made a PR, I can make one later if you wish, but that's only a few lines (less than 10) to add.

**Comment by martinbudden** [comment]
@goebish , glad I could finally find a home for your code. Unfortunately it did not seem a priority for Cleanflight itself, but I think it sits well with iNav.

BTW, I'm away from home at the moment and so haven't had a chance to test the Crazepony  - if you get a chance could you have a go?

And finally since none of the toy quad protocols are ideal, I've been looking at designing my own protocol. I know, yet another protocol, but this one will be open source so people can freely use it.

The receiver code is at https://github.com/iNavFlight/inav/blob/master/src/main/rx/nrf24_ref.c, I've got some deviation transmitter code written but not yet tested. I'd appreciate any comments or insights you have about this protocol.

**Comment by goebish** [comment]
No problem, I'll dust off the crazepony and try to check that tonight.

**Comment by skaman82** [comment]
@goebish please submit a PR and I gladly have a loot at it - but I have hardware to test with

**Comment by martinbudden** [comment]
@digitalentity , note also that a NRF24 can be directly connected to a CJMCU board:

cjmcubottom

**Comment by goebish** [comment]
My RX code is working on the CJMCU + nrf24l01 but it goes into failsafe as soon as too much throttle is applied. I tried to add capacitors but couldn't solve the issue :/ Same issue with older and newer revisions of the board.

**Comment by martinbudden** [comment]
@goebish funny that. I remember you mentioning that before. I've never had problems with my CJMCU and the nrf24l01.

**Comment by DjDaViD33** [comment]
Hello or I can find info to plug the chip on a NRF24 naze32 and used as the protocol NRF24 receiver?
I use the configurator INAV but to RX PWM?
Thank you

**Pull request merged**
