### PR TITLE
Reduce acc lpf hz max to mitigate Random Config change

### PR DESCRIPTION
**Pull request by aviphysics**
This request is intended to reduce the consequence of the Random Config Change by reducing the acc_lpf_hz max value below the 101, 102 value that the Random Config Change bug appears to set the value to.

The new value I proposed is 99, an even lower value might be a good idea, if such high values are not needed.

### CODE REVIEW

**Comment by aviphysics** [comment]
I am not sure how to upload proof of a test.

**Comment by JulioCesarMatias** [comment]
this will not solve the problem! I recommend closing the PR.

**Comment by aviphysics** [comment]
> this will not solve the problem! I recommend closing the PR.

Is there a reason to allow large unsafe values of this parameter?

**Comment by JulioCesarMatias** [comment]
> > this will not solve the problem! I recommend closing the PR.
> 
> Is there a reason to allow large unsafe values of this parameter?

the parameter range is from 0 to 200 because it is declared as `uint8_t`, that is, an 8-bit variable (0 - 255). But just limiting the value to 99Hz won't solve anything. The correct method to do is to find where the problem is that causes the value to be set incorrectly.

**Comment by MrD-RC** [comment]
1. Are there any craft that could need a filter above 100Hz? If so, then the setting has to stay as it is. Just having it to 200 because of the variable type isn’t really an excuse for having it set to 200 max. The range should only include what is needed and safe. If nobody uses outside of a 10 to 75 range, they should be the min and max, for example. 
2. I agree with @JulioCesarMatias . Reducing the value allowed in CLI is just working on the deferred problem rather than the cause. The only advantage would be that you may get an out tof range message in the OSD.

**Comment by JulioCesarMatias** [comment]
> 1. Are there any craft that could need a filter above 100Hz? If so, then the setting has to stay as it is. Just having it to 200 because of the variable type isn’t really an excuse for having it set to 200 max. The range should only include what is needed and safe. If nobody uses outside of a 10 to 75 range, they should be the min and max, for example.
> 2. I agree with @JulioCesarMatias . Reducing the value allowed in CLI is just working on the deferred problem rather than the cause. The only advantage would be that you may get an out of range message in the OSD.

I didn't say that limiting the maximum range of a parameter because of the size of the variable in bits is correct. I said that this was done by someone in the past, thinking about the maximum size of the variable. And another thing, which UAV will be able to make the AHRS, PID and INS work with an LPF cutoff frequency of 99,100,102,200????? None, of course, and also not with 75Hz does not work. For the AHRS, PID and INS to work well, the Acc must be filtered with a cutoff frequency of no more than 40Hz (which is still high)

**Comment by aviphysics** [comment]
> > 1. Are there any craft that could need a filter above 100Hz? If so, then the setting has to stay as it is. Just having it to 200 because of the variable type isn’t really an excuse for having it set to 200 max. The range should only include what is needed and safe. If nobody uses outside of a 10 to 75 range, they should be the min and max, for example.
> > 2. I agree with @JulioCesarMatias . Reducing the value allowed in CLI is just working on the deferred problem rather than the cause. The only advantage would be that you may get an out of range message in the OSD.
> 
> I didn't say that limiting the maximum range of a parameter because of the size of the variable in bits is correct. I said that this was done by someone in the past, thinking about the maximum size of the variable. And another thing, which UAV will be able to make the AHRS, PID and INS work with an LPF cutoff frequency of 99,100,102,200????? None, of course, and also not with 75Hz does not work. For the AHRS, PID and INS to work well, the Acc must be filtered with a cutoff frequency of no more than 40Hz (which is still high)

Should I reduce the maximum to 40?

**Comment by MrD-RC** [comment]
> I didn't say that limiting the maximum range of a parameter because of the size of the variable in bits is correct. I said that this was done by someone in the past, thinking about the maximum size of the variable. And another thing, which UAV will be able to make the AHRS, PID (flying in stabilize mode) and INS work with an LPF cutoff frequency of 99, 100, 102, 200????? None, of course, and also not with 75Hz does not work. For the AHRS, PID (flying in stabilize mode) and INS to work well, the Acc must be filtered with a cutoff frequency of no more than 40Hz (which is still high)

@JulioCesarMatias , I was just saying that’s not a reason to use that range. uint8_t is the just smallest int we can use. Why do you think the variable size had any baring on the range. If they were limiting it to the variable it would have been 255. I’d like to give the original coder more credit.

The 75 I just used as an example. All I’m saying is that the range should match the realistic use of the filter. If 40 is the top end, and still considered very high. Then 40 would probably be a good maximum.

I think we are on the same page here.

**Comment by aviphysics** [comment]
I will update to 40. Just been busy.

**Comment by MrD-RC** [comment]
@aviphysics do you have time to set this to 40? If not, mind if I step in? It would be nice to get this PR merge ready.

**Comment by OptimusTi** [comment]
What was the cause of the random config change?

**Comment by MrD-RC** [comment]
@OptimusTi It seems to be caused by saving the config to the EEPROM. But it’s still on going.

https://github.com/iNavFlight/inav/issues/7281

**Comment by DzikuVx** [comment]
There is right now a series of PR on both INAV and Configurator projects that fix this problem in a correct way (it should no longer happen). So I will close this one  Thank you for your participation!

**Pull request closed without merging**
