### PR TITLE
IBUS RX and telemetry on this same port and pin

### PR DESCRIPTION
**Pull request by hali9**
This is PR for INAV on https://github.com/cleanflight/cleanflight/pull/2554
Tested on SPRACINGF3

A.  For use RX IBUS connect Flysky IBUS-SERVO to FC-UART-TX.
In configurator set RX on selected port, set receiver mode to RX_SERIAL and Receiver provider to IBUS.

B. For use telemetry IBUS connect Flysky IBUS-SENS to FC-UART-TX.
In configurator set IBUS telemetry on selected port and enable telemetry feature.

C. For use RX IBUS and telemetry IBUS together connect Flysky IBUS-SERVO and IBUS-SENS to FC-UART-TX using schematic:
```
+---------+
| FS-iA6B |
|         |
| Servo   |---|<---\       +------------+
|         |        |       | FC         |
| Sensor  |---[R]--*-------| Serial TX  |
+---------+                +------------+
```
R = 10Kohm, Diode 1N4148.

In configurator set IBUS telemetry and RX on this same port, enable telemetry feature, set receiver mode to RX_SERIAL and Receiver provider to IBUS.

Warning:
Schematic above work also for connect telemetry only, 
but not work for connect rx only - will stop FC.

Need update documantation.

### CODE REVIEW

**Comment by bk79** [comment]
Are you sure that servo and sensor are not inverted in the schematic? Servo
is an output and the diode will prevent any high signal coming from the
receiver...

Il 09/feb/2017 00:23, "hali9" <notifications@github.com> ha scritto:

**Comment by hali9** [comment]
Yes.
@bk79 see cleanflight 2554 (link above), there is a photo.
The diode works something like key.
http://ea.elportal.pl/diody/214x86xuklklucza1.gif.pagespeed.ic.-uYij4u1s-.png

I connect that, and it work.

**Comment by hali9** [comment]
Tests on SPRACINGF3:
If case C is set, after arm and motor run:
if disconect from FC-UART-TX, then failsafe is enabled and no telemetry.
if disconect from FS-iA6B-Servo, then failsafe is enabled and telemetry work.
if disconect from FS-iA6B-Sensor, then RX work ok and no telemetry.

**Comment by hali9** [comment]
The documentation is updated.

**Comment by inode-** [comment]
Just built the development version (naze) but everytime I switch on both of the function on the same UART I got problem. The configuration of the port get reset. Any idea of why?

**Comment by hali9** [comment]
Hello
This is not merged yet. Will be on 1.7.
If You wont test check this hali9:combine-ibus

  ----- Original Message -----

**Comment by inode-** [comment]
I think it will be better to define different ID for the sensors. The routine dispatchMeasurementRequest() should be able to identify correct sensor via the SENSOR_ADDRESS_TYPE_LOOKUP variable and send correct data in that way.

I think that work it's better to be based on the @qba667 code firmware and like in him example code (mavlinktoibus) don't duplicate sensors ids.

I will try to patch and submit the changes in the next days.

**Comment by hali9** [comment]
@inode- This PR refers connections telemetry and rx using one UART port.
And it has nothing to do with the nature of the data.
There is a PR of sending type of data https://github.com/iNavFlight/inav/pull/1228
But it is merged and closed.
So please open new issue or PR or let's discuse this on rcgroup.
https://www.rcgroups.com/forums/showthread.php?2486545-FlySky-FS-i6-8-channels-firmware-patch!/page106
But before check https://github.com/hali9/inav/tree/combine-ibus-1

**Comment by digitalentity** [comment]
Superceded by #1484

**Pull request closed without merging**
