### PR TITLE
FW autotune improvements

### LINKED ISSUE #6025: Let INAV figure out rates on FW
## Current Behavior

The PIFF controller on fixed wing uses the airplane's maximum roll, pitch and yaw rates for it's stabilization. Finding the correct rates can be a bit of a pain, especially for planes that can't do nice clean rolls and loops without a lot of other pilot input. Measuring the yaw rate is even more difficult, since rudder often has a strong roll response. In that case a black box log is the only method to figure out the rates, but this requires a computer which is often impractical.

## Desired Behavior

The gyroscope should be able to measure the rotation rates on full control surface deflection.

## Suggested Solution

Make `AUTOTUNE` a two-stage process where it first determines the rates on full control surface deflection, and then tunes the PIFF values using those rates. Ideally it would be possible to also do each stage separately if the user only want to do one or the other.

## Who does this impact? Who is this for?

All fixed wing pilots.

### PR DESCRIPTION
**Pull request by avsaase**
_Now tested and working_

This PR improves the autotune mode on fixed wing by letting autotune set the correct rates for your airplane (closes #6025). There are three autotune 'modes': with `AUTO` autotune will automatically adjust the max rate settings according to the capabilities of the airplane by setting the rates consistent with 80% control surface deflection. This leaves 20% room for P and I to provide stabilization. `LIMIT` works the same as `AUTO` but the rates are never increased above the starting values. This could be useful if you have a very agile plane and want to limit the rates. With `FIXED` the rates are not changed. 

The basic algorithm is as follows. When the stick input goes above 80%, autotune for 250ms records the target rate, the realized rate, and the PID output send to the mixer. After this period it will use the maximum observed values to calculate what the rotation rate would be at 80% control surface deflection. The rate setting is then updated from the current value towards this optimal value by 10% of the difference. For example, if the current rate is 150 deg/s and it calculates the optimal rate is 300 deg/s, then the new rate is `150 + (300 - 150) * 10% = 165`. The FF update work in a similar fashion, where it calculates what FF value is needed to achieve the current rate target.

Here is some dvr with the `AUTO` mode:

https://user-images.githubusercontent.com/880421/110219506-e6be0c00-7ebf-11eb-8c37-df5faaf9cd3d.mp4

I made `AUTO` the default mode because this gives rates close to what they would be in manual mode. https://github.com/iNavFlight/inav-configurator/pull/1188 will set conservative default rates that any airplane will be able to achieve. If users with more agile planes tune from that starting point then the other modes will cause small servo throws. This could cause a lot of support questions. 

Thanks @b14ckyy for helping with testing and ironing out the kinks in the logic :+1:

### CODE REVIEW

**Review by digitalentity — APPROVED** [review]
LGTM!

**Comment by avsaase** [comment]
There is still one minor issue: the blackbox logs the rate updates as events just like the FF updates but the new rates are not reflected in the setPointRate traces (at least as displayed in the explorer). They seem to just reflect the initial rates settings. This makes it difficult to verify the tune or troubleshoot other problems if you have done an autotune during the flight. Perhaps this can be fixed in a separate PR.

**Comment by avsaase** [comment]
I added a setting to set the D-gain relative to the P-gain but left the default at zero for now.

**Comment by avsaase** [comment]
Would it be worthwhile to also automatically set the max acceleration settings? I keep debating this with myself but I haven't reached a conclusion. `rate_accel_limit_roll_pitch` would need to be split into separate roll and pitch settings of course. @DzikuVx @digitalentity?

**Pull request merged**
