### PR TITLE
Drop NMEA protocol

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by CZEMacLeod** [comment]
Is INAV really dropping support for any non-ublox GPS devices (unless they have an interface chip generating MSP packets)?
I understand NMEA may not have the resolution or speed of other protocols, but this seems a little drastic a move?
It certainly could make sense on smaller flash devices to not include it in the firmware if not necessary, but maybe that could be done on a target basis with ifdefs?
Is there a lot of technical debt in the NMEA implementation?

**Comment by DzikuVx** [comment]
@CZEMacLeod the thing is, NMEA is a deprecated protocol. All modern GPS modules support UBLOX protocol.
On top of that, year ago we put a HUGE notice in INAV Configurator saying that NMEA is deprecated and will be removed in the future. Future has come.

There is not a single good reason to keep NMEA support in a modern flight controller firmware

**Comment by CZEMacLeod** [comment]
@DzikuVx Fair enough. I haven't actually used the configurator in a good while, and generally just read the discussions and PRs on this repo, so must have missed the conversation about deprecating NMEA.
I was looking at a few modules released by Adafruit recently, e.g. the PA1616S based Ultimate GPS module, which supports NMEA but not UBLOX. While I agree that maybe for UAVs it is true that most are based on UBLOX or UBLOX clones, I'm not sure that it is 'globally' true that this is the case.
Regardless, as you said, there apparently was a notice of this happening, and there are options available, so I have no 'objection' to this happening. I was just surprised that it was the case.
As I said, if there is significant technical debt, or overhead in continuing to support NMEA, it is obvious to remove it - especially if few people use the feature.
I am also slightly curious where you get the assertion that NMEA 0183 is a deprecated protocol. The https://www.nmea.org/nmea-0183.html page doesn't make that assertion, and I believe it is still used by AIS devices for instance.

**Comment by AlksSAV** [comment]
Speed sensors and echo sounders, and other devices work on this protocol. I used these sensors in ardupilot. It is a pity that inav is increasingly moving away from supporting boats / rovers.

**Comment by Jetrell** [comment]
@CZEMacLeod Its also about the direction INAV is moving, to increase navigation performance and reliability, now that it has an AHRS that depends more on the accuracy of this data, for optimum performance.
Unlike Ardupilot which can get by with a 1Hz update rate because it has a predictive sensor fusion filter. (EKF3)
INAV does not yet have this luxury. And relies more heavily on higher GNSS update rates for better position estimation.
Testing has shown this to considerably improve multicopter position accuracy in navigation modes.. With the INAV 7.0 also providing the use of up to 4 constellations for M10 devices, and 3 for M8 devices.

**Comment by MrD-RC** [comment]
> I am also slightly curious where you get the assertion that NMEA 0183 is a deprecated protocol. The https://www.nmea.org/nmea-0183.html page doesn't make that assertion, and I believe it is still used by AIS devices for instance.

It has been deprecated in INAV for a year. Not necessarily by NMEA. There are simply better protocols available now. On very cheap GPS modules too. For example, the Walksnail M10 is cheap and works very well.
image

**Comment by mmosca** [comment]
> Speed sensors and echo sounders, and other devices work on this protocol. I used these sensors in ardupilot. It is a pity that inav is increasingly moving away from supporting boats / rovers.

INAV only uses NMEA for gps and currently does not support any of those sensors using NMEA.

If they are pretending to be a GPS, and sending position solutions using NMEA protocol they would be seen as an unhealthy GPS receivers (no 3d fix, no course over ground, etc...) or would require a proper driver in INAV to be used anyway. If they already have a driver, they are not affected by this, and if they don't. they are not supported today.

**Pull request merged**
