### PR TITLE
Split NAZE target; remove legacy drivers

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by digitalentity** [comment]
This requires testing on NAZE board, clones and derivatives.

**Comment by stronnag** [comment]
````
arm-none-eabi-size ./obj/main/inav_NAZE.elf
   text	   data	    bss	    dec	    hex	filename
 125908	   1376	  17132	 144416	  23420	./obj/main/inav_NAZE.elf
arm-none-eabi-objcopy -O ihex --set-start 0x8000000 obj/main/inav_NAZE.elf obj/inav_1.5.0_NAZE.hex
````
All that free space! Boots on a FLIP32+ (full FLIP32 with baro and mag).

**Comment by digitalentity** [comment]
Yes, 3k of free space (we have 126k on F1 targets due to 2k being reserved for config storage).

**Comment by martinbudden** [comment]
@digitalentity , it would be good to get this merged in as soon as possible.

**Comment by digitalentity** [comment]
I believe it's safe to merge.

**Comment by digitalentity** [comment]
If there are bugs on different NAZE targets - we'll sort that out on the way

**Pull request merged**
