### PR TITLE
Nav launch stick abort deadband setting

### PR DESCRIPTION
**Pull request by breadoven**
Adds Nav launch stick abort deadband setting.

Defaults to 100 us value.

### CODE REVIEW

**Review by JulioCesarMatias — APPROVED** [review]

**Comment by Jetrell** [comment]
@breadoven Can I ask you take a look at the setting Default for  `nav_fw_launch_abort_deadband`. It should be 100uS, with a range of 2 - 250.
But after a flash, and loading _any_ of the Default model setting. `nav_fw_launch_abort_deadband = 0`. And shows an out of range _Setting validation error_, under the pre-arm stats and CLI status.

**Comment by breadoven** [comment]
Looks like the default value got deleted from navigation.c somehow. Not sure what happened, need to check further.

**Comment by breadoven** [comment]
@DzikuVx @stronnag @JulioCesarMatias 

Any idea why https://github.com/iNavFlight/inav/commit/a38bce9b1a2f827761340b5880dacba1d100cc41#diff-7e540e72396e9e99dc1f9ce758e9135abe4c425425c18e5b84bfe6317e7e6a91 deleted the 2 default settings in navigation.c, especially `SETTING_NAV_FW_LAUNCH_MANUAL_THROTTLE_DEFAULT `that wasn't even part of 5.1.0 (was only ever merged into Master). Makes no sense to me why it did this. Guess it'll need another PR to replace them ?

**Comment by JulioCesarMatias** [comment]
I've tracked it down, and haven't found the root source of the problem... It's like a ghost. The `launch_manual_throttle` and `launch_abort_deadband` parameters are gone after Pawel did a Rebase in the 5.1 release. I don't know how to explain how it happened. But OK! Let's fix this. @breadoven open a PR by re-adding these parameters in the algorithm.

**Comment by breadoven** [comment]
When Master was merged into 5.1.0 it should have inserted `SETTING_NAV_FW_LAUNCH_MANUAL_THROTTLE_DEFAULT `next to `SETTING_NAV_FW_LAUNCH_ABORT_DEADBAND_DEFAULT `but instead it just deleted `SETTING_NAV_FW_LAUNCH_ABORT_DEADBAND_DEFAULT`. Then when 5.1.0 was merged back inti Master it deleted both default settings. Maybe this tracks back through the commit chain but it looks more like Github screwed up somehow. Just makes you wonder what else it messed up ?

It'll do a PR to fix the deleted defaults.

**Comment by JulioCesarMatias** [comment]
yes, I thought about that too... GitHub really messed things up here...

**Pull request merged**
