### PR TITLE
update `nav_mc_vel_xy_p` default value

### PR DESCRIPTION
**Pull request by stronnag**
"Finally" (pretty please) put this setting change to bed.

### CODE REVIEW

**Comment by digitalentity** [comment]
Good catch!

**Comment by stronnag** [comment]
Don't merge this just yet, there's a few more outdated / obsoleted settings documented. It could be a long evening checking this.

**Comment by stronnag** [comment]
OK, here's the differences (from `dump` on the default target).

```
$ ./checkvals.rb Cli.md def.txt 
# 1st value is from latest `dump`, second is from Cli.md
Defaults mismatch for looptime 1000 != 2000
Defaults mismatch for vbat_adc_channel 1 != -
Defaults mismatch for rssi_adc_channel 3 != -
Defaults mismatch for current_adc_channel 2 != -
Defaults mismatch for airspeed_adc_channel 0 != -
Defaults mismatch for failsafe_stick_threshold 50 != 0
Defaults mismatch for failsafe_min_distance_procedure DROP != SET-THR
Defaults mismatch for vbat_max_cell_voltage 424 != 430
Defaults mismatch for flaperon_throw_offset 200 != 250
Defaults mismatch for nav_rth_climb_ignore_emerg OFF != ON
Defaults mismatch for nav_rth_allow_landing ALWAYS != ON
Defaults mismatch for smartport_fuel_unit MAH != PERCENT
Defaults mismatch for fw_p_pitch 5 != 20
Defaults mismatch for fw_i_pitch 7 != 30
Defaults mismatch for fw_ff_pitch 50 != 10
Defaults mismatch for fw_p_roll 5 != 25
Defaults mismatch for fw_i_roll 7 != 30
Defaults mismatch for fw_ff_roll 50 != 10
Defaults mismatch for fw_p_yaw 6 != 50
Defaults mismatch for fw_i_yaw 10 != 45
Defaults mismatch for fw_ff_yaw 60 != 0
Defaults mismatch for fw_i_level 5 != 15
Defaults mismatch for nav_fw_pos_xy_p 75 != 10
Not documented gyro_notch1_hz
Not documented gyro_notch1_cutoff
Not documented gyro_notch2_hz
Not documented gyro_notch2_cutoff
Not documented acc_notch_hz
Not documented acc_notch_cutoff
Not documented rangefinder_hardware
Not documented pitot_hardware
Not documented pitot_use_median_filter
Not documented pitot_noise_lpf
Not documented pitot_scale
Not documented receiver_type
Not documented rx_spi_rf_channel_count
Not documented inav_w_z_surface_p
Not documented inav_w_z_surface_v
Not documented debug_mode
Not documented stats_total_energy
Not documented tz_offset
Not documented display_force_sw_blink
Not documented dterm_setpoint_weight
Not documented dterm_notch_hz
Not documented dterm_notch_cutoff
Not documented manual_rc_yaw_expo
```
I will address this tomorrow (well at least the obsolete documented defaults).

The script reports the following values as obsolete in the documentation, however most of these are false positives as they refer to target specific items (e.g. the OSD settings which are not compiled into SPRF3). However, there are a few of note, which we _may_ wish to remove (`gyro_sync_denom`, `inav_gps_delay` for example). Perhaps a bit more contentious, as they still apply to earlier firmware.

```
Obsolete value gyro_sync_denom
Obsolete value inav_gps_delay
Obsolete value multiwii_current_meter_output
Obsolete value failsafe_lights
Obsolete value failsafe_lights_flash_period
Obsolete value failsafe_lights_flash_on_time
Obsolete value rx_nosignal_throttle
Obsolete value mag_to_use
Obsolete value sdcard_detect_inverted
Obsolete value osd_video_system
Obsolete value osd_row_shiftdown
Obsolete value osd_units
Obsolete value osd_stats_energy_unit
Obsolete value osd_main_voltage_decimals
Obsolete value osd_wh_drawn_pos
Obsolete value osd_bat_remaining_capacity_pos
Obsolete value osd_bat_remaining_percent_pos
Obsolete value osd_efficiency_mah_pos
Obsolete value osd_efficiency_wh_pos
Obsolete value osd_rssi_alarm
Obsolete value osd_time_alarm
Obsolete value osd_alt_alarm
Obsolete value osd_main_voltage_pos
Obsolete value osd_rssi_pos
Obsolete value osd_flytimer_pos
Obsolete value osd_ontime_pos
Obsolete value osd_flymode_pos
Obsolete value osd_throttle_pos
Obsolete value osd_vtx_channel_pos
Obsolete value osd_crosshairs
Obsolete value osd_artificial_horizon
Obsolete value osd_current_draw_pos
Obsolete value osd_mah_drawn_pos
Obsolete value osd_craft_name_pos
Obsolete value osd_gps_speed_pos
Obsolete value osd_gps_sats_pos
Obsolete value osd_altitude_pos
Obsolete value osd_pid_roll_pos
Obsolete value osd_pid_pitch_pos
Obsolete value osd_pid_yaw_pos
Obsolete value osd_power_pos
Obsolete value default_rate_profile
Obsolete value manual rc_yaw_expo
```

**Comment by stronnag** [comment]
The second update fixes all the obvious default value mismatches reported by my script, so this probably good enough to merge for 1.9.1.

**Comment by digitalentity** [comment]
Thanks @stronnag, merging

**Pull request merged**
