### PR TITLE
Ensure summary screen is displayed on disarm even if throttle or pitch were high

### PR DESCRIPTION
**Pull request by shellixyz**

### CODE REVIEW

**Review by digitalentity — COMMENTED** [review]
Looks good

**Review by digitalentity — APPROVED** [review]

**Comment by shellixyz** [comment]
Ready to merge

**Comment by digitalentity** [comment]
Oops. Merging #2852 broke this one.

**Comment by digitalentity** [comment]
Superseded by https://github.com/iNavFlight/inav/pull/3079

**Pull request closed without merging**
