### PR TITLE
Added General aviation OSD units - includes a fair amount of work and fixes on the OSD & Fonts

### PR DESCRIPTION
**Pull request by MrD-RC**
Linked with https://github.com/iNavFlight/inav-configurator/pull/1322 Both will need to be merged together.

**Testing**
_I have tested in flight, and all seems good to me. See https://github.com/iNavFlight/inav/pull/7255#issuecomment-886112831 for what has been checked. Note that I have looked at the different fonts on the ground only, I fly with default. It's always worth getting 2nd options. But I don't believe there is anything that will cause issues. I did spot another issue with the CMS menu, but that is unrelated, as I first spotted it on a 3.0.1 base_

## Overview
This was supposed to be a pretty simple change; to add General Aviation units to the OSD. This idea has had positive responses from GA pilots in the INAV groups. This was all going great. Until the discovery that there were not enough free characters below the #255. The OSD implementation uses a char array, so symbols that interact with data in OSD.c need to be indexed below 255. This lead me to take a look at the font files, and see which characters in the font files needed to be in 0-255, and which can be above that threshold, as other drawing methods are used; which use uint16t. After the update, we now will have around 50 free characters that can be used with the char array display method.

While doing this, I noticed inconsistencies between the OSD that you see from the flight controller, and the OSD shown in configurator. For instance the AH grid was 1 row high and 1 row to the left in configurator, compared to on the OSD. There was a crosshair defined in some fonts (impact and impact mini off the top of my head), that was never accessible. And the crosshair in the configurator did not match the OSD. So I took the opportunity to fix these and other little bugs too.

### GA Units
I have added the GA units, with all the conversions. However, I have not yet tested in flight. I will test using the programming and global variables shown on the OSD to compare the speeds and distances between metric and GA.

### Testing
So far I have just done ground based tests. The OSD symbols all seem to be working fine. Of course, some, like the vario need to be tested in flight. The GA units have also only been tested on the ground. I am planning to do some in air testing asap. 

However, if anyone else would like to test, you would need to use one of the configurators below; or compile your own from https://github.com/MrD-RC/inav-configurator/tree/general-aviation-OSD-units (PR not yet submitted). This configurator, at the time of submitting the PR, is up to date with master. It is based on my UK units branch, as that has not yet been merged. However, the firmware part of UK units has. It goes without saying that you will need to upload the new font to your FC.
Linux 32 https://inav.mrd-rc.com/INAV-Configurator_linux32_3.0.1.tar.gz
Linux 64 https://inav.mrd-rc.com/INAV-Configurator_linux64_3.0.1.tar.gz
Win 32 https://inav.mrd-rc.com/INAV-Configurator_win32_3.0.1.zip
Win 64 https://inav.mrd-rc.com/INAV-Configurator_win64_3.0.1.zip
While mentioning the branches, as of now, the firmware changes are also completely up to date with master.

### Fonts
Default - Bold - Large
default bold large

Clarity - Clarity Medium - Vision
clarity clarity_medium vision

Impact - Impact Mini
impact impact_mini

### OSD test screens - Also shows the GA units
image
image

image
image

image
image
(Some elements are flashing on this screen)

image
image

image
image

### CODE REVIEW

**Comment by avsaase** [comment]
@MrD-RC awesome work! I know that making these changes is very cumbersome. I'm a metric boy so I will probably never use but it makes a lot of sense to have have GA units. 

A few small comments:

- Some of the efficiency symbols are a bit inconsistent with the existing symbols. @Jetrell has done a lot of work on the font files for 3.0 so maybe he can help with this.

- It looks like the right half of the mAh/mi symbol is missing. Is that correct?

**Comment by MrD-RC** [comment]
Thanks @avsaase 👍🏻

I’ll double check the efficiency symbols. Other than the new symbols, all the other symbols have just been re-ordered. Literally just changing the name of the .png files. So they should only be in the wrong places if there is a problem. 

As for the mAh/mi symbol. It’s fine, the numbers are just split. It would probably look better if they were together, so I can change that. I also added an .md file for the characters. This should make it clearer where they all are. https://github.com/MrD-RC/inav-configurator/blob/general-aviation-OSD-units/resources/osd/iNav%20character%20map.md

**Comment by avsaase** [comment]
Yeah probably best to keep the double symbols together.

**Comment by MrD-RC** [comment]
I’ll move them to 038 and 039. Then move SYM_AH_NM to 063. This is really just a reminder for me, as it’s bed time 🤣

**Comment by MrD-RC** [comment]
default

**Comment by Jetrell** [comment]
@MrD-RC That's a lot of work. Nice job.
If I could suggest. For the sake of keeping OSD.h items all together. Could all the "Graphical Compass" items be placed sequentially in the font numbering?  

When I cleaned up the fonts and redrew many of them for 3.0. My goal was to re-align heights and keep the new additions to each font, in the same character style as that font.
Would you have any objections to me doing this for your new symbols? As presently, the new symbols are all based on default font styling.

**Comment by Jetrell** [comment]
@MrD-RC Here is a zip of the .png files to the specs of each font style.
[3.1 Knots_Nautical rework.zip](https://github.com/iNavFlight/inav/files/6806082/3.1.Knots_Nautical.rework.zip)

I made some changes to `0x8e` (142). It has _Centi-Foot/minute_ as the unit.  It suited the smaller fonts better and seemed less cluttered than 100 foot/minute. 
I also did two distance symbols for each font. One with `Kn` and the other `Kt`. I know `Kt` is used in some places, Although `Kn` is the international standard abbreviation for Knots . Its up to you.

**Comment by MrD-RC** [comment]
Thanks @Jetrell. Of course I would have said yes, so thanks for doing all that. I’ll take a look at the zip file shortly. 

Yes, I’ll move the compass separators to be with the direction letters. I was hoping the letters would be > 255, but it didn’t work out. I’ll get that sorted though.

With Knots, I used Kt as that is the symbol recommended by the International Civil Aviation Organization. I looked at images of ASI guages, but pretty much all of them had the full work **Knots**. So I figured, go with the ICAO recommendation, as Kn may also look similar to Km at a quick glance.

**Comment by MrD-RC** [comment]
One thing @Jetrell, when we refer to things like centimetres, it is 0.01 metres, as in it's a division by 100, not a multiplication. Perhaps Hft/min for hundred feet per minute would be better?

**Comment by Jetrell** [comment]
> 
> 
>Perhaps Hft/min for hundred feet per minute would be better?

Totally agree... I was having a moment with that idea !!
Here are the characters you suggested.

Thanks again for putting in the time to re-organize the fonts. It will help a lot with future additions to the OSD :+1: 

[Hundred_FT_min.zip](https://github.com/iNavFlight/inav/files/6807577/X100.FT_min.zip)

**Comment by MrD-RC** [comment]
Thanks @Jetrell. I'll update when I get home this evening.

**Comment by MrD-RC** [comment]
As the fonts have been updated. Here are the updated images.

Default - Clarity - Clarity Medium
default clarity clarity_medium

Bold - Impact - Impact Mini
bold impact impact_mini

Vision - Large
vision large

**Comment by Mateyhv** [comment]
Great job and loooots of work have gone here @MrD-RC!!! It is welcome since me and @shellixyz are into a project for improving the resolution of the compass which the GA guys will probably appreciate :D. Not sure if it will see the light but anyway we should work on your fonts distribution. Moving the compass fonts to the end of the first characters batch is perfect so all the additional 46 compass fonts would be sequential!

With futher OSD cleanup I have a question regarding the small gaps left behind like 17, 148-149, 255, 309-314, 424-430. Are they on purpose? I believe for all blank characters font 1 can be used and those spaced be eliminated. (I foresee that to be a ton of work though)

I have already done a tiny improvement on the variometer chevrons to make them equidistant. If you want you can add them to the fonts, should be a direct replacement into your fonts numbering.

[vario_chevrons_adjusted.zip](https://github.com/iNavFlight/inav/files/6834713/vario_chevrons_adjusted.zip)

**Comment by MrD-RC** [comment]
Thanks @Mateyhv 👍  If @Jetrell is happy with the vario chevrons, I can add them to the PR, no problem.

As for the gaps,
- 17 is RSSI 2, I can't see it as blank?
- 32 is a deliberately blank character
- 148-149 were symbols that were relocated. They can be used for anything in the future
- 255 seems to be a special character. I had errors when I tried to use 255
- 308-314 could be where I originally tried to put the compass. It would be great if your changes to it could use > 255 indexes, especially with so many characters being used.
- 423 to 429 I left for 2 additional crosshairs, while keeping the numbers together.

Any character that is in the default font, but not in alternate fonts, is automatically added to the alternate fonts when they are compiled.

That compass does sound really cool. But, if you're re-working it. It would be really handy if it could use a method that uses uint16_t, as then the compass could be moved above 255. An extra 46 characters _just_ for the compass only leaves another 5 characters that need to use char, due to interacting with data in the OSD.

**Comment by Jetrell** [comment]
@Mateyhv I had a look at the Vario changes. They don't appear any different to whats already there.

I once looked at making the vario arrow characters more equidistant. But it could not be accomplished. 
This is because of the way the Single and Double arrows are added to the Vario display, according to the altitude speed change.

i.e. A single can be added to a single, when slower vario changes occur. Or double can be added to a double, when fast altitude changes occur... Or mix of both, if a fast change, slows abruptly.... or slow changes speeds-up abruptly. Which I consider useful to visualize.

>
>
>@MrD-RC That compass does sound really cool. But, if you're re-working it. It would be really handy if it could use a method that uses uint16_t, as then the compass could be moved above 255. An extra 46 characters just for the compass only leaves another 5 characters that need to use char, due to interacting with data in the OSD.

I agree. The idea sounds good. But it would be a total waste of the sub 257 characters that have now been made available with this re-ordering.

@Mateyhv I assume that the home arrow is based on the pixel drawn version from FrSky?

**Comment by Jetrell** [comment]
@Mateyhv I had a look at the Vario changes. They don't appear any different to whats already there.

I once looked at making the vario arrow characters more equidistant. But it could not be accomplished.
This is because of the way the Single and Double arrows are added to the Vario display, according to the altitude speed change.

i.e. A single can be added to a single, when slower vario changes occur. Or double can be added to a double, when fast altitude changes occur... Or mix of both, if a fast change, slows abruptly.... or slow changes speed-up abruptly. Which I consider useful to visualize.

    @MrD-RC That compass does sound really cool. But, if you're re-working it. It would be really handy if it could use a method that uses uint16_t, as then the compass could be moved above 255. An extra 46 characters just for the compass only leaves another 5 characters that need to use char, due to interacting with data in the OSD.

I agree. The idea sounds good. But it would be a total waste of the sub 257 characters that have now been made available with this re-ordering.

@Mateyhv I assume that the compass is based on the pixel drawn version from FrSky?

**Comment by Mateyhv** [comment]
Thanks @MrD-RC, sorry for the delay, some technical problems (Win10). I belive there will be no problem in alocating the characters above the font 255 although I am not going to do the code part.

@Jetrell the vario chevrons are the same, no changes in the design. I only ordered them so they are now equidistant from each other on the OSD, that is something that has bothered me for a while (yes I know, maniac things :D ). The diference is very fine, from memory it was about 1px on one or two chevrons in each font type. You can only check it comparing them side by side.

**Comment by MrD-RC** [comment]
Other than not being enough memory on some F411's, this is pretty much ready to go. I just need a couple of symbols updated, and I'll submit the Configurator PR. When that's here, it's good to go.

There are some comparison OSD screens here https://www.dropbox.com/s/wugdxzwyak5z70r/OSD%20Font%20comparison.zip?dl=0 I've checked the units conversions to Knots, Nautical Miles, 100 Feet per Minute, and Feet. All looks good to me.

**Comment by avsaase** [comment]
@MrD-RC, @DzikuVx removed some features from F411 and F722 so if you merge the master branch into this one it should fit on those MCUs.

**Comment by MrD-RC** [comment]
Cool, thanks for the info @avsaase. I’ll do that when the configurator part is ready.

**Comment by MrD-RC** [comment]
The configurator changes now have a PR https://github.com/iNavFlight/inav-configurator/pull/1322 These 2 PRs will need to be merged together, or there will be display issues with font mismatches.

I just want to say a huge thank you to @Jetrell for sorting out the font symbols.

**Comment by MrD-RC** [comment]
@DzikuVx just wondering if this is likely to get merged? I have some other changes that I’d like to make to the OSD, but don’t want to piggy back them on this PR. If it will get merged in the future, I can just rebase them off this to do the work before this is merged.

**Comment by MrD-RC** [comment]
Thanks mate 👍🏻

**Pull request merged**
