### PR TITLE
Underclocking for F1/F3 targets

### PR DESCRIPTION
**Pull request by digitalentity**
A new CLI option (`cpu_underclock`) for F3-based targets to select between 72MHz (default) and 48MHz CPU clock. Should theoretically reduce interference to 433MHz LRS systems. Other clock speeds are not possible because native USB will only function with 72/48MHz system clock speed.

### CODE REVIEW

**Comment by digitalentity** [comment]
@Schalonsus can you please test PPM input on your board?

**Comment by Schalonsus** [comment]
i am not able to compile anymore...

make target = NAZE
make: *** Leerer Variablenname.  Schluss.

**Comment by digitalentity** [comment]
Yes, NAZE is no longer enabled - you need to enable it manually.

**Comment by Schalonsus** [comment]
and how? i renamed the files in naze target folder and i set naze in makefile, what else?

**Comment by digitalentity** [comment]
Renaming the files in target folder is enough

**Comment by digitalentity** [comment]
@Schalonsus we have enough flash space to re-enable NAZE, I'm planning to do it for next release.

**Comment by Schalonsus** [comment]
Seems my cygwin or anything else ****ed up, cant compile anything anymore... no matter what repository i am in or what branch
Nice that NAZE will survive another version

**Comment by digitalentity** [comment]
Now we also need Ruby to compile - might be the issue. 

Here's the firmware to test [inav_1.7.3_NAZE.zip](https://github.com/iNavFlight/inav/files/1259578/inav_1.7.3_NAZE.zip)

**Comment by Schalonsus** [comment]
Already installed ruby, do i need to configure it or anything like this? Or just install?
Thanks for the hex, will test later.

**Comment by Schalonsus** [comment]
Hm, seems it is too early in the morning, need more coffee.....
just typed the command wrong....
"make target = Naze" instead of "make target=NAZE"
now compiles fine...

**Comment by digitalentity** [comment]
Speaking of coffee, I need to get another one :rofl:

**Comment by Schalonsus** [comment]
...just master compiles fine, with de_underclock_f3 it gives error. i give up now for today:
$ make target=SPRACINGF3
%% startup_stm32f30x_md_gcc.S
%% system_stm32f30x.c
%% adc_stm32f30x.c
%% bus_i2c_stm32f30x.c
%% dma.c
%% gpio_stm32f30x.c
%% serial_uart_stm32f30x.c
%% system_stm32f30x.c
%% timer_stm32f30x.c
%% accgyro_mpu.c
%% accgyro_mpu6050.c
%% barometer_bmp085.c
%% barometer_bmp280.c
%% barometer_ms56xx.c
%% compass_ak8975.c
%% compass_hmc5883l.c
%% compass_mag3110.c
%% light_ws2811strip.c
%% light_ws2811strip_stdperiph.c
%% serial_softserial.c
%% flash_m25p16.c
%% flashfs.c
%% blackbox.c
%% blackbox_encoding.c
%% blackbox_io.c
%% cms.c
%% cms_menu_blackbox.c
%% cms_menu_builtin.c
%% cms_menu_imu.c
%% cms_menu_ledstrip.c
%% cms_menu_misc.c
%% cms_menu_osd.c
%% colorconversion.c
%% gps_conversion.c
%% display_ug2864hsweg01.c
%% rangefinder_hcsr04.c
%% rangefinder_hcsr04_i2c.c
%% rangefinder_srf10.c
%% rangefinder_vl53l0x.c
%% dashboard.c
%% displayport_max7456.c
%% displayport_msp.c
%% displayport_oled.c
%% gps.c
%% gps_ublox.c
%% gps_nmea.c
%% gps_naza.c
%% gps_i2cnav.c
%% ledstrip.c
%% osd.c
%% navigation.c
%% navigation_fixedwing.c
%% navigation_fw_launch.c
%% navigation_geo.c
%% navigation_multicopter.c
%% navigation_pos_estimator.c
%% barometer.c
%% pitotmeter.c
%% rangefinder.c
%% crsf.c
%% frsky.c
%% hott.c
%% ibus_shared.c
%% ibus.c
%% ltm.c
%% mavlink.c
%% smartport.c
%% telemetry.c
%% target.c
%% main.c
%% assert.c
%% build_config.c
%% debug.c
%% version.c
%% bitarray.c
%% crc.c
%% encoding.c
%% filter.c
%% maths.c
%% printf.c
%% streambuf.c
%% typeconversion.c
%% string_light.c
%% config_eeprom.c
%% config_streamer.c
%% feature.c
%% parameter_group.c
%% adc.c
%% buf_writer.c
%% bus_i2c_soft.c
%% bus_spi.c
%% bus_spi_soft.c
%% display.c
%% exti.c
%% gps_i2cnav.c
%% gyro_sync.c
%% io.c
%% io_pca9685.c
%% light_led.c
%% logging.c
%% rx_nrf24l01.c
%% rx_spi.c
%% rx_xn297.c
%% pwm_esc_detect.c
%% pwm_mapping.c
%% pwm_output.c
%% pwm_rx.c
%% rcc.c
%% serial.c
%% serial_uart.c
%% sound_beeper.c
%% stack_check.c
%% system.c
%% timer.c
settings.yaml -> settings_generated.h, settings_generated.c
C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - arm-none-eabi-g\+\+ -mthumb -mcpu\=cortex-m4 -mfloat-abi\=hard -mfpu\=fpv4-sp-d16 -fsingle-precision-constant -Wdouble-promotion -flto -fuse-linker-plugin -Os -I./src/main -I./src/main/target -I./lib/main/STM32F30x_StdPeriph_Driver/inc -I./lib/main/CMSIS/CM1/CoreSupport -I./lib/main/CMSIS/CM1/DeviceSupport/ST/STM32F30x -I./lib/main/MAVLink -I./src/main/target/SPRACINGF3 -ggdb3 -DDEBUG -std\=c\+\+11 -Wall -Wextra -Wunsafe-loop-optimizations -Wdouble-promotion -ffunction-sections -fdata-sections -DSTM32F303xC -DSTM32F303 -DFLASH_SIZE\=256 -DHSE_VALUE\=8000000 -DUSE_STDPERIPH_DRIVER -DSPRACINGF3 -D__FORKNAME__\=inav -D__TARGET__\=SPRACINGF3 -D__REVISION__\=a4009ea -o obj/tmp/test obj/tmp/test.cpp (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:95:in `popen3'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:258:in `capture3'
        from ./tools/settings.rb:614:in `block in compile_test_file'
        from ./tools/settings.rb:568:in `mktmpdir'
        from ./tools/settings.rb:590:in `compile_test_file'
        from ./tools/settings.rb:637:in `check_conditions'
        from ./tools/settings.rb:275:in `initialize'
        from ./tools/settings.rb:843:in `new'
        from ./tools/settings.rb:843:in `<main>'
Makefile:929: die Regel für Ziel „src/main/fc/settings_generated.h“ scheiterte
make: *** [src/main/fc/settings_generated.h] Fehler 1

**Comment by digitalentity** [comment]
Looks like you don't have the `arm-none-eabi` toolchain on your path.

**Comment by Schalonsus** [comment]
That is how my PATH variable looks like:
C:\Ruby24-x64\bin;%PATH%;C:\dev\gcc-arm-none-eabi-6_2-2016q4\bin;C:\Program Files (x86)\Java\jre1.8.0_77\bin

If it was wrong i could not compile master either, not?

**Comment by digitalentity** [comment]
No, master doesn't use Ruby yet. Hm... @fiam can you have a crack on this build problem?

**Comment by fiam** [comment]
@Schalonsus It seems it's an unfortunate bug in Ruby. If your %PATH% contains spaces (...Program Files..) in your case, `spawn` will fail. See https://github.com/nickryand/vagrant-multi-putty/issues/13#issuecomment-61373722

Could you do me a favour and just type `arm-none-eabi-g++` in the command line to make sure %PATH% is set up properly. If that's the case, I'll add a workaround in the script to look for the executable in the PATH manually.

**Comment by Schalonsus** [comment]
$ arm-none-eabi-g++
arm-none-eabi-g++.exe: fatal error: no input files
compilation terminated.

Seems something wrong there, but how can i compile master then?

**Comment by digitalentity** [comment]
`master` is not dependent on Ruby yet

**Comment by fiam** [comment]
@Schalonsus Could you replace `tools/settings.rb` with the one from this gist https://gist.github.com/fiam/c6836e2706e73cd45b7b07dc8e8d7212 and try again? Thanks!

**Comment by Schalonsus** [comment]
With the new settings.rb:

%% timer.c
settings.yaml -> settings_generated.h, settings_generated.c
./tools/settings.rb:591:in `find_gplusplus': Could not find arm-none-eabi-g++ in PATH, looked in ["C:\\cygwin64\\usr\\local\\bin", "C:\\cygwin64\\bin", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ ", "C:\\Program Files (x86)\\PuTTY", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ ", "C:\\Program Files (x86)\\PuTTY", "C:\\dev\\gcc-arm-none-eabi-6_2-2016q4\\bin", "C:\\Ruby24-x64\\bin", "C:\\Program Files (x86)\\Java\\jre1.8.0_77\\bin"] (RuntimeError)
        from ./tools/settings.rb:595:in `compile_test_file'
        from ./tools/settings.rb:659:in `check_conditions'
        from ./tools/settings.rb:277:in `initialize'
        from ./tools/settings.rb:865:in `new'
        from ./tools/settings.rb:865:in `<main>'
Makefile:929: die Regel für Ziel „src/main/fc/settings_generated.h“ scheiterte
make: *** [src/main/fc/settings_generated.h] Fehler 1

**Comment by fiam** [comment]
@Schalonsus I think I got it right now. Please, give this one a try https://gist.github.com/fiam/8117b07fefc89a3e6b61b3b8a28036b0

**Comment by Schalonsus** [comment]
%% timer.c
settings.yaml -> settings_generated.h, settings_generated.c
./tools/settings.rb:595:in `find_gplusplus': Could not find arm-none-eabi-g++ in PATH, looked in ["C:\\cygwin64\\usr\\local\\bin", "C:\\cygwin64\\bin", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ ", "C:\\Program Files (x86)\\PuTTY", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ ", "C:\\Program Files (x86)\\PuTTY", "C:\\dev\\gcc-arm-none-eabi-6_2-2016q4\\bin", "C:\\Ruby24-x64\\bin", "C:\\Program Files (x86)\\Java\\jre1.8.0_77\\bin"] (RuntimeError)
        from ./tools/settings.rb:599:in `compile_test_file'
        from ./tools/settings.rb:663:in `check_conditions'
        from ./tools/settings.rb:277:in `initialize'
        from ./tools/settings.rb:869:in `new'
        from ./tools/settings.rb:869:in `<main>'
x64-mingw32
Makefile:929: die Regel für Ziel „src/main/fc/settings_generated.h“ scheiterte
make: *** [src/main/fc/settings_generated.h] Fehler 1

**Comment by fiam** [comment]
@Schalonsus It seems you tested again with the previous settings.rb, it should have printed the RUBY_PLATFORM value just before failing, e.g.:

```
settings.yaml -> settings_generated.h, settings_generated.c 
universal.x86_64-darwin16 <=== this is missing in your output
./tools/settings.rb:595:in `find_gplusplus': Could not find arm-none-eabi-g++.exe in PATH, looked in ["/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/opt/X11/bin", "/usr/local/share/dotnet", "/Library/Frameworks/Mono.framework/Versions/Current/Commands", "/Users/fiam/local/bin", "/usr/local/git/bin", "/Users/fiam/local/android-sdk-mac_x86/tools", "/Users/fiam/local/android-sdk-mac_x86/platform-tools", "/Applications/Xcode.app/Contents/Developer/usr/bin/", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin", "/Users/fiam/local/node/bin", "/Users/fiam/local/go/bin", "/Users/fiam/go/bin", "/Users/fiam/local/android-ndk-r6b/", "/Users/fiam/local/gcc-arm-none-eabi-6-2017-q2-update/bin"] (RuntimeError)
	from ./tools/settings.rb:599:in `compile_test_file'
	from ./tools/settings.rb:663:in `check_conditions'
	from ./tools/settings.rb:277:in `initialize'
	from ./tools/settings.rb:869:in `new'
	from ./tools/settings.rb:869:in `<main>'
make: *** [src/main/fc/settings_generated.h] Error 1
```

Please, try it again and run just `make settings` to get rid of the rest of the output. Thanks!

**Comment by sambas** [comment]
needed to change it to search arm-none-eabi-g++.exe
```
$ make settings
settings.yaml -> settings_generated.h, settings_generated.c
i386-mingw32
Found arm-none-eabi-g++.exe at F:\devtools\gcc-arm-none-eabi-6_2-2016q4-20161216-win32\bin/arm-none-eabi-g++.exe
C:/Ruby24/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - F:\\devtools\\gcc-arm-none-eabi-6_2-2016q4-20161216-win32\\bin/arm-none-eabi-g\+\+.exe -mthumb -mcpu\=cortex-m4 -mfloat-abi\=hard -mfpu\=fpv4-sp-d16 -fsingle-precision-constant -Wdouble-promotion -flto -fuse-linker-plugin -Os -I./src/main -I./src/main/target -I./lib/main/STM32F30x_StdPeriph_Driver/inc -I./lib/main/CMSIS/CM1/CoreSupport -I./lib/main/CMSIS/CM1/DeviceSupport/ST/STM32F30x -I./lib/main/MAVLink -I./src/main/target/SPRACINGF3 -ggdb3 -DDEBUG -std\=c\+\+11 -Wall -Wextra -Wunsafe-loop-optimizations -Wdouble-promotion -ffunction-sections -fdata-sections -DSTM32F303xC -DSTM32F303 -DFLASH_SIZE\=256 -DHSE_VALUE\=8000000 -DUSE_STDPERIPH_DRIVER -DSPRACINGF3 -D__FORKNAME__\=inav -D__TARGET__\=SPRACINGF3 -D__REVISION__\=18a7c8f -o obj/tmp/test obj/tmp/test.cpp (Errno::ENOENT)
        from C:/Ruby24/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24/lib/ruby/2.4.0/open3.rb:95:in `popen3'
        from C:/Ruby24/lib/ruby/2.4.0/open3.rb:258:in `capture3'
        from ./src/utils/settings.rb:640:in `block in compile_test_file'
        from ./src/utils/settings.rb:570:in `mktmpdir'
        from ./src/utils/settings.rb:616:in `compile_test_file'
        from ./src/utils/settings.rb:663:in `check_conditions'
        from ./src/utils/settings.rb:277:in `initialize'
        from ./src/utils/settings.rb:869:in `new'
        from ./src/utils/settings.rb:869:in `<main>'
makefile:929: recipe for target 'src/main/fc/settings_generated.h' failed
make: *** [src/main/fc/settings_generated.h] Error 1
```

**Comment by Schalonsus** [comment]
$ make settings
settings.yaml -> settings_generated.h, settings_generated.c
./tools/settings.rb:595:in `find_gplusplus': Could not find arm-none-eabi-g++ in PATH, looked in ["C:\\cygwin64\\usr\\local\\bin", "C:\\cygwin64\\bin", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ ", "C:\\Program Files (x86)\\PuTTY", "C:\\Windows\\system32", "C:\\Windows", "C:\\Windows\\System32\\Wbem", "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\ ", "C:\\Program Files (x86)\\PuTTY", "C:\\dev\\gcc-arm-none-eabi-6_2-2016q4\\bin", "C:\\Ruby24-x64\\bin", "C:\\Program Files (x86)\\Java\\jre1.8.0_77\\bin"] (RuntimeError)
        from ./tools/settings.rb:599:in `compile_test_file'
        from ./tools/settings.rb:663:in `check_conditions'
        from ./tools/settings.rb:277:in `initialize'
        from ./tools/settings.rb:869:in `new'
        from ./tools/settings.rb:869:in `<main>'
x64-mingw32
Makefile:929: die Regel für Ziel „src/main/fc/settings_generated.h“ scheiterte
make: *** [src/main/fc/settings_generated.h] Fehler 1

**Comment by stronnag** [comment]
@fiam, sure you need ` Shellwords.join(args)` in the `open3` call, in some of the logs I see some strange escapes. 

Doesn't just `args.join(' ')` work?

**Comment by fiam** [comment]
@stronnag I believe a simple join would cause problems if any of the args has spaces in it. Shellwords.join() should be safer.

@Schalonsus Please, try this one https://gist.github.com/fiam/1e2cbfb053320f5c6890a6463d127661

I just changed the code to always look for the compiler with .exe extension, regardless of the platform. Whatever it founds first (no extension or .exe) will be used. That should work for unix platform as well as the different Windows based toolchains. Please, let us know if it fixes the problem in your build and it will get merged ASAP.

**Comment by Schalonsus** [comment]
Output looks different now but not able to compile

$ make settings
settings.yaml -> settings_generated.h, settings_generated.c
C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory          - C:\\dev\\gcc-arm-none-eabi-6_2-2016q4\\bin/arm-none-eabi-g\+\+.exe -mthumb -mc         pu\=cortex-m4 -mfloat-abi\=hard -mfpu\=fpv4-sp-d16 -fsingle-precision-constant -         Wdouble-promotion -flto -fuse-linker-plugin -Os -I./src/main -I./src/main/target          -I./lib/main/STM32F30x_StdPeriph_Driver/inc -I./lib/main/CMSIS/CM1/CoreSupport          -I./lib/main/CMSIS/CM1/DeviceSupport/ST/STM32F30x -I./lib/main/MAVLink -I./src/m         ain/target/SPRACINGF3 -ggdb3 -DDEBUG -std\=c\+\+11 -Wall -Wextra -Wunsafe-loop-o         ptimizations -Wdouble-promotion -ffunction-sections -fdata-sections -DSTM32F303x         C -DSTM32F303 -DFLASH_SIZE\=256 -DHSE_VALUE\=8000000 -DUSE_STDPERIPH_DRIVER -DSP         RACINGF3 -D__FORKNAME__\=inav -D__TARGET__\=SPRACINGF3 -D__REVISION__\=a4009ea -         o obj/tmp/test obj/tmp/test.cpp (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:95:in `popen3'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:258:in `capture3'
        from ./tools/settings.rb:639:in `block in compile_test_file'
        from ./tools/settings.rb:570:in `mktmpdir'
        from ./tools/settings.rb:615:in `compile_test_file'
        from ./tools/settings.rb:662:in `check_conditions'
        from ./tools/settings.rb:277:in `initialize'
        from ./tools/settings.rb:868:in `new'
        from ./tools/settings.rb:868:in `<main>'
Found arm-none-eabi-g++ at C:\dev\gcc-arm-none-eabi-6_2-2016q4\bin/arm-none-eabi         -g++.exe
Makefile:929: die Regel für Ziel „src/main/fc/settings_generated.h“ scheiterte
make: *** [src/main/fc/settings_generated.h] Fehler 1

**Comment by stronnag** [comment]
My theory is still that on some Windows combinations (cmd, cygwin, msys, MRI, other ruby), shellwords makes a mess, look at the `\+\+`, `D__TARGET__\=SPRACINGF3` etc. in the above stack trace. Unwanted escapes.

Humour me by changing (in the repo version), line 614:
````
            stdout, stderr = Open3.capture3(Shellwords.join(args))
````
to
````
            stdout, stderr = Open3.capture3(args.join(' '))
````
The shell knows where the binary is, the extra escapes screw it up. At least my theory.

**Comment by Schalonsus** [comment]
Thanks @stronnag , that is the solution 👍

**Comment by Schalonsus** [comment]
@digitalentity , PPM input is working

CLI

# status
System Uptime: 11 seconds
Voltage: 28 * 0.1V (1S battery - OK)
CPU Clock=48MHz, GYRO=MPU6500, ACC=MPU6500
Sensor status: GYRO=OK, ACC=OK, MAG=NONE, BARO=NONE, RANGEFINDER=NONE, GPS=OK
Stack size: 2048, Stack address: 0x20005000
I2C Errors: 0, config size: 1420, max available config: 2048
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = none
  AIRSPEED : configured = none, used = none
System load: 65, cycle time: 2009, PID rate: 497, RX rate: 49, System rate: 9

#

**Comment by fiam** [comment]
@stronnag and @Schalonsus Thanks for coming up with a solution. Unfortunately, it seems we need to use `Shellwords.join()` when running on Unix or Cygwin, while Windows and MinGW should just use `.join()`. I've created yet another gist which should handle this platform difference properly. Could you test in on your end so we can update the script in the repository?

https://gist.github.com/fiam/064ce290983e669b4ade49cc7dc0a1eb

**Comment by stronnag** [comment]
shellwords is not required on my Linux boxes.

**Comment by fiam** [comment]
@stronnag It's not required right now because none of the CFLAGS use spaces, but that could change in the future and someone would expect CFLAGS with spaces to work (as long as they're properly quoted). I'd rather have the code future proof-ed, even if that makes it a bit more complex.

**Comment by Schalonsus** [comment]
@fiam , your latest code also works, thanks

**Comment by fiam** [comment]
@Schalonsus Thanks for testing it! I'll submit a PR with the modifications right now.

**Comment by Schalonsus** [comment]
@digitalentity , just connected with EzGUI and saw "Blocked System Overloaded"
Any thoughts?
screenshot_2017-09-01-11-53-31

**Comment by digitalentity** [comment]
@Schalonsus looks like 48MHz is not enough for 2000 (500Hz) looptime. Try setting to a slower value - i.e. looptime=3000

**Comment by Schalonsus** [comment]
looptimes 3000, 4000 and 1500 make things even worse. On 2000 it has the lowest cpu load with 64%

**Comment by digitalentity** [comment]
Please upload your dump so I can test on a NAZE here

**Comment by Schalonsus** [comment]
Here is my diff
[SkyFun_1.7.txt](https://github.com/iNavFlight/inav/files/1281868/SkyFun_1.7.txt)

**Comment by digitalentity** [comment]
@Schalonsus you have `gyro_sync=ON`. To adjust looptime you must change `gyro_sync_denom`, not the `looptime` itself.

Setting `set gyro_sync_denom = 3` allows NAZE to run at 48MHz clock with your dump.

**Comment by Schalonsus** [comment]
Thanks!!!

**Comment by digitalentity** [comment]
@Schalonsus I think this is now ready to be merged. @stronnag did you by any chance tested this branch?

**Pull request merged**
