### PR TITLE
[fc_msp_box.c] Add macros to active box and reset boxes count

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
This PR does only replace:

activeBoxIdCount = 0;
activeBoxIds[activeBoxIdCount++] = box; 

Per:

RESET_BOX_ID_COUNT;
ACTIVE_THIS_BOX(BOXNAME);

### CODE REVIEW

**Comment by stronnag** [comment]
One has to ask WHY??
The code is already clear and understandable.

**Comment by JulioCesarMatias** [comment]
> One has to ask WHY?? The code is already clear and understandable.


What do you have against working with macros? I don't understand why you don't like it. It's easier for me to just call a macro that is already ready, than having to write an array with a variable with iteration

**Comment by MrD-RC** [comment]
All I’d say is ACTIVE_THIS_BOX doesn’t really make sense. 

ADD_BOXMODE or something like that would have been better

**Comment by JulioCesarMatias** [comment]
> All I’d say is ACTIVE_THIS_BOX doesn’t really make sense.
> 
> ADD_BOXMODE or something like that would have been better

the original variable is called `activeBoxIds` , so why doesn't `ACTIVE_THIS_BOX` make sense? But yes I can rename for you

**Comment by JulioCesarMatias** [comment]
> All I’d say is ACTIVE_THIS_BOX doesn’t really make sense.
> 
> ADD_BOXMODE or something like that would have been better


You can review, this was made for you

**Comment by MrD-RC** [comment]
It doesn’t make sense because ACTIVE_THIS_BOX reads like you are activating only that box. 

Maybe ADD_ACTIVE_BOX would be better? Add implies it is being added to an array of active boxes. Not just a singular active box.

**Comment by JulioCesarMatias** [comment]
> It doesn’t make sense because ACTIVE_THIS_BOX reads like you are activating only that box.
> 
> Maybe ADD_ACTIVE_BOX would be better? Add implies it is being added to an array of active boxes. Not just a singular active box.

you have to resolve what you want, `ADD_BOXMODE` or `ADD_ACTIVE_BOX ` ?

**Comment by JulioCesarMatias** [comment]
> It doesn’t make sense because ACTIVE_THIS_BOX reads like you are activating only that box.
> 
> Maybe ADD_ACTIVE_BOX would be better? Add implies it is being added to an array of active boxes. Not just a singular active box.

renamed to `ADD_ACTIVE_BOX`

**Review by DzikuVx — APPROVED** [review]

**Comment by DzikuVx** [comment]
@JulioCesarMatias please resolve conflicts

**Comment by JulioCesarMatias** [comment]
> @JulioCesarMatias please resolve conflicts


I am no longer interested in contributing to iNav, this has been explained here >> https://github.com/iNavFlight/inav/pull/7807

**Comment by DzikuVx** [comment]
I'm sorry to hear that, I very much liked your contributions @JulioCesarMatias and I'd like you to continue. 
But ultimately this is your choice and I respect that.

**Pull request closed without merging**
