### PR TITLE
Start on version 1.4

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by martinbudden** [comment]
@digitalentity , betaflight, after experimenting with using a development branch, has gone back to using the master branch. Releases are done by adding a tag for the release (and then any bug fixes to the release can be applied to that tag).

After using both, I favour going back to using the master branch. Thoughts? @DzikuVx - your view?

**Comment by digitalentity** [comment]
There are people who compile their own versions and they usually just check out `master`. With current approach they will be using the latest "official" release compatible with latest official Configurator and with all bugs related to actual release.

I don't know how we should proceed, but I have a feeling that development - master approach is better for workflow separation in a public project. If we would be closed sourced project, having only `master` branch will be easier as dev versions will never get to general public, but that's not the case.

**Comment by DzikuVx** [comment]
I would prefer to stay with master-development approach

**Comment by martinbudden** [comment]
> With current approach they will be using the latest "official" release compatible with latest official Configurator and with all bugs related to actual release.

That's a strong argument for staying as we are. I think the reasons people build iNav are different to the reasons people build betaflight, so it does make sense to have a different approach.

**Comment by digitalentity** [comment]
Yes, people build betaflight to stay at bleeding edge of development and performance, while INAV is mostly custom-built to enable features on F1 boards. IMO keeping current is less important than keeping stable, let's stick to master-development approach for now.

**Comment by martinbudden** [comment]
OK, let's stick with master/development. I thought I'd just raise the issue.

**Comment by digitalentity** [comment]
It's always good to get something to think about. Maybe we'll discuss this again if we drop F1 targets :smile:

**Comment by digitalentity** [comment]
I think we have enough changes for 1.4. Just a few more PRs (#790, #386, #543, #687, #789) and RC1 can be released. Anything else will be delayed until 1.5.

**Comment by DzikuVx** [comment]
I'd say #543 would be most important here

**Comment by digitalentity** [comment]
#543 still requires quite a lot of testing. My time was diverted from it lately.

**Comment by stronnag** [comment]
Just flashed it. Planning to fly it this afternoon.

**Comment by digitalentity** [comment]
@stronnag, great! Be advised to use the most crash-proof craft and be ready to recover manually at all times, there was very little testing done on #543. It may not function at all.

**Comment by stronnag** [comment]
OK, I will change the vehicle choice. Thanks for warning me.

**Comment by stronnag** [comment]
#543 Flight tested PH, RTH, WP on a variety of mission complexity and type of craft (mini-quad, 600mm tri). No problems.

**Pull request merged**
