### PR TITLE
Show the navigation state on OSD_MESSAGES

### LINKED ISSUE #1993: Show detailed modes in OSD
The other day I lost a flying wing after losing the RC link. The wing was configured with failsafe_procedure = RTH, but it went down instead. Thanks to some partial frames I got from video feed and the buzzer (always use a big buzzer and feed it from the battery, guys!), I was able to recover the model. However, I wasn't sure where the plane might had gone since all I could see in the OSD flymode was "!FS!". It didn't tell me wether it was trying to turn back and return to home or whether it had went into emergency landing, so the search area ended up pretty big. Even when this time I was able to recover the wing, not knowing what the model was trying to do could have easily made the difference between finding and not finding it.

Note that blackbox, while being pretty useful to diagnose the problem if you manage to find the plane, won't be of any help while you're looking for the model. Having more info about the active flight modes would be immensely useful in this case.

What I propose is:

- Leave the flymode indicator only for exclusive modes: ANGLE, HORIZON, ACRO, RTL (since you have no control), ALTHOLD (implies ANGLE), POSHOLD (implies ANGLE - make also POSHOLD automatically enable ALTHOLD?) and FS modes (see next point).
- In a failsafe situation, show the failsafe procedure too in the fly mode indicator: FS+SET-THR, FS+DROP, FS+RTL, FS (meaning no failsafe procedure configured). This indicator must NOT flash, since in a failsafe situation you might have only a few visible frames of video. We might include some "partial flashing" (e.g. between "!FS+RTL!" and "FS+RTL") to make it easier to notice while you're flying, but the text should always be visible.
- Add an additional display item for AIRMODE  like MWOSD.
- Add an additional display item for modes which might be enabled with any mode: AUTOTUNE, AUTOTRIM

This would also partially fix #1959.

### PR DESCRIPTION
**Pull request by fiam**
Show the current state of the navigation system while the aicraft
is in RTH or WP modes.
When FS is performing an RTH, show the state of the navigation
system too, alternating with the already existing FS messages.

Fixes #1993

### CODE REVIEW

**Comment by digitalentity** [comment]
@fiam I suggest we do generic message bus first. Navigation code will do much better job in deciding which messages to show.

**Comment by fiam** [comment]
@digitalentity Just want to get this in for 1.8 to gather some user feedback, specially regarding if we're pushing too many messages or, au contraire, users want even more messages and details. We could also get some ideas for useful messages that we haven't thought of.

Message bus won't be done until 1.9 and user feedback regarding the amount and granularity of the messages will help design it better for the intended use cases.

**Comment by digitalentity** [comment]
Ok, agreed. Merging.

**Comment by giacomo892** [comment]
Flight tested extensively on F3. All seems great!

**Pull request merged**
