### PR TITLE
Add GEPRCF745_BT_HD target

### PR DESCRIPTION
**Pull request by YI-BOYANG**
Add GEPRCF745_BT_HD target, the first GEPRC FC to use the STM32F745.

### CODE REVIEW

**Comment by mmosca** [comment]
Good to see f745 becoming more common. It is certainly a better long term choice vs f722.

**Comment by YI-BOYANG** [comment]
> Good to see f745 becoming more common. It is certainly a better long term choice vs f722.

Some checks were not successful, can you help me take a look?

**Comment by mmosca** [comment]
> > Good to see f745 becoming more common. It is certainly a better long term choice vs f722.
> 
> Some checks were not successful, can you help me take a look?

#9980 should fix it. I need to test it now

**Comment by mmosca** [comment]
@YI-BOYANG can you update to the latest master? That should fix your build.

**Comment by YI-BOYANG** [comment]
> @YI-BOYANG can you update to the latest master? That should fix your build.

Ok, I have updated to the latest master and wait for the result of the build.

**Comment by YI-BOYANG** [comment]
> @YI-BOYANG can you update to the latest master? That should fix your build.

Check passed！

**Pull request merged**
