### PR TITLE
Initial cut on timer mapping cleanup

### PR DESCRIPTION
**Pull request by digitalentity**
An attempts to clean up the pwm_mapping mess. Not ready for merge yet.

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden I'd appreciate your oppinion on the approach.

**Comment by digitalentity** [comment]
@sambas I'm not an expert on HAL, can you have a look at how timer-related code for F7 could be aligned with F1/F3/F4 implementation?

**Comment by digitalentity** [comment]
This is coming along quite nicely - hope to get it ready for review tomorrow. Boy, timer code is a complete mess.

**Comment by digitalentity** [comment]
Ok, most code changes are in place. Careful testing is required on all targets to make sure motor/servo outputs are functional in multicopter and airplane configurations. Channel forwarding also requires testing.

**Comment by digitalentity** [comment]
Bench-tested on REVO, seems functional including LEDSTRIP support

**Comment by martinbudden** [comment]
@digitalentity , sorry the delay in replying. I'd say that this looks OK, however it is not really an area of my expertise, so I don't really feel able to comment in depth. Perhaps @blckmn could comment.

**Comment by digitalentity** [comment]
@martinbudden thanks. I have tested a few targets - all seems to function properly, but certainly there are bugs. Btw, this may be a first step to resource remapping here - depending on airplane/multirotor aircraft type we have different allowed timer channels for motor/servo.

@blckmn, please have a look.

**Comment by digitalentity** [comment]
I intend to merge this. Expect bugs. A LOT of bugs :beetle: :beetle: :beetle:

**Comment by blckmn** [comment]
I'm happy to help clean up some of the bugs here

**Comment by digitalentity** [comment]
@blckmn I've merged this PR, you are most welcome to clean up timer-related code in "development" branch :smile:

**Comment by stronnag** [comment]
This appears to break soft serial. I'm reluctant to test further without LTM available to monitor flights, and the only machine I'm willing to risk needs softserial, alas.

**Comment by digitalentity** [comment]
@stronnag thanks for testing. Which target did you try? I'll have a look on softserial code vs. new timer code and use that target for debugging.

**Comment by stronnag** [comment]
SPRF3 (on a Dodo board).

**Comment by digitalentity** [comment]
Thanks, I'll do some debugging today (on a SPRF3 board)

**Comment by digitalentity** [comment]
@stronnag bug located, working on a fix

**Pull request merged**
