### PR TITLE
Throw out all the setup part of the Gyro interrupt routine

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
~~Almost all targets define `USE_EXTI` and `USE_MPU_DATA_READY_SIGNAL`.  `DEBUG_MPU_DATA_READY_INTERRUPT` it's just a remnant of the algorithm of the past. Removing them simplifies the code and makes it more readable.~~ Now this PR removes everything that is part of the gyro interrupt configuration, which is not used in iNav

### CODE REVIEW

**Comment by digitalentity** [comment]
It's even more than that. We don't use gyro interrupt data, we don't even need the gyro DRDY interrupt-handling code.

**Comment by DzikuVx** [comment]
@JulioCesarMatias what about those 3 targets that does not define EXTI? I found that `AIRBOTF7` is one of them.

**Comment by JulioCesarMatias** [comment]
> @JulioCesarMatias what about those 3 targets that does not define EXTI? I found that `AIRBOTF7` is one of them.

I thought about what Konstantin said in the message, I hadn't noticed that the Gyro interrupt routine is never used... I did some testing, and it really doesn't make a difference whether the interrupt routine is active or not. So now I have a new proposal, are we going to remove the entire interrupt algorithm from Gyro? This can save a few bytes

**Comment by DzikuVx** [comment]
@JulioCesarMatias that might be way to go, yes

**Comment by JulioCesarMatias** [comment]
Many files were changed to clean up...

**Pull request merged**
