### PR TITLE
[WIP] NAZAGps support

### PR DESCRIPTION
**Pull request by henn1001**
I tried porting it over from Sambas branch :)
I think this part here still needs some attention:
https://github.com/henn1001/cleanflight/blob/f0cb8e4af42b1fedb1a30e13c70983de569a5fa8/src/main/io/gps.c#L259
I was not quite sure what to do here because it is handled a bit different in your codebase.

Still needs some fixes because it does not compile yet.

### CODE REVIEW

**Comment by henn1001** [comment]
Did some fixes and squashed everything. Should be ready for testing?!
Hopefully someone in your thread has a naza gps laying around :)

**Comment by digitalentity** [comment]
Thanks! I hope somebody will be able to test this. I don't have a NAZA GPS :)

**Comment by digitalentity** [comment]
I think the code should give some credit to @sambas, I believe it was he who did all the coding and debugging in the first place?

**Comment by henn1001** [comment]
Yes - of course :)

**Comment by sambas** [comment]
stuff from my nav branch would have fixed version for this. This is missing some flags. Also there are some ublox things that you might be interested, module version check and different configuration for neo7 and up.

**Pull request closed without merging**
