### PR TITLE
inav_use_gps_no_baro Settings.md

### PR DESCRIPTION
**Pull request by sensei-hacker**

### CODE REVIEW

**Comment by sensei-hacker** [comment]
> Wouldn't it be necessary to change the `settings.yaml` file as well?


Yeah already done:
https://github.com/iNavFlight/inav/compare/7.1.1...release_7.1.2

**Comment by rmaia3d** [comment]
> Yeah already done: [7.1.1...release_7.1.2](https://github.com/iNavFlight/inav/compare/7.1.1...release_7.1.2)

Oh, I missed it!

But where did that come from? The list of files changed by this PR only shows the .md file...

**Comment by sensei-hacker** [comment]
> > Yeah already done: [7.1.1...release_7.1.2](https://github.com/iNavFlight/inav/compare/7.1.1...release_7.1.2)
> 
> Oh, I missed it!
> 
> But where did that come from? The list of files changed by this PR only shows the .md file...


The commit that changes settings.yaml is the commit that established the 7.1.2 branch.  This PR then updated it to including settings.md

**Comment by rmaia3d** [comment]
> > > Yeah already done: [7.1.1...release_7.1.2](https://github.com/iNavFlight/inav/compare/7.1.1...release_7.1.2)
> > 
> The commit that changes settings.yaml is where 7.1.2 branches from 7.1.1. In other words, that change is the reason the 7.1.2 branch is a branch, and isn't 7.1.1.
> 
> This PR then updated it to including settings.md

Just as a suggestion, to make things easier for the future: that commit should have been part of this PR as well. This way it is more organized and easier to track where each change came from.

**Comment by 0crap** [comment]
Now we need a 7.1.2 Milestone i guess.

**Pull request merged**
