### PR TITLE
OSD SmartCrosshair, with homing feature, + 5 extra (static) crosshairs

### PR DESCRIPTION
**Pull request by OlivierC-FR**
Adds 6 extra crosshairs for the HUD, the last one is "smart", it will show the home point relative to the crosshair. Helps to find the home point. Easier to read than the arrow-to-home, and also works in pitch.
(CMS > OSD > Settings >Crosshair style = Smart)

FPV camera angle can be adjusted in case it is not at 0°/flight controller
Positive is camera pointing up, negative is camera pointing down.
(CMS > OSD > Settings >Camera uptilt)

Focus can be set to narrow, medium or large. 
Sets how accurate the homing is, default is medium.
(CMS > OSD > Settings >Crosshair focus)

Vertical indicator will only show if the home is inside a 150° angle in front of the aircraft, so it does not show when moving away, no point.

Using OSD chars from 400 to 429.
Require a compatible font, such as Vision 1 to 4 : http://bit.ly/2RJ0QnW
Demo : https://drive.google.com/file/d/1hP9SLBw970PYIQYNNI0PpzJTkq_DNig5/view

### CODE REVIEW

**Comment by OlivierC-FR** [comment]
If there's any interest in this feature I'll make the PR to make all fonts compatible in the Configurator.

**Comment by OlivierC-FR** [comment]
The user selectable crosshairs are :
 Diamond
 X
 Sniper
 Square
 Space
 Smart

**Comment by wx4cb** [comment]
interesting. how would it actually work? similar to radar mode? The reason why i ask is radar mode is nigh on useless to me as I can't move the icons around (the north/scale ones).

also, Having something  where you can change the "location" of the crosshair would be great too - the reason being is that i actually have some down angle on my fpv camera - only a couple degrees) that way the crosshair is actually in the middle of the horizon when the plane is flying with a slight upwards AoA

**Comment by OlivierC-FR** [comment]
I posted a link to a quick demo in video in the first post, it displays from 1 to 3 arrows around the crossair to show where the home point is, relative to the crosshair. The more arrows, the further in angle it is. I'll have more DVRs to post in the next days, but for now the weather does not make it possible..

The setting I named "focus" is a linear factor applied on the threshold angles, as sample when focus=medium the 1st horizontal arrow will mean the error in angle to home is between 7 and 17°. If focus=wide it will be 1.5 these values, and 0.7 if focus=narrow.

About a vertical offset for the CH, that could be easily added, actually I thought of this, but the limitation we have with this OSD is that there's only 16 horizontal lines in PAL, and 13 in NTSC, so there's not much headroom. Right now the vertical position for the crosshair and horizon line is hardcoded at the 7th row for NTSC and 8th for PAL, and the horizon line can go 4 lines up and 4 down. So the vertical offset could probably only go from -1 to +1. Allowing -2 to +2 would already make it "bump" the top and bottom in NTSC.

**Comment by ghost** [comment]
Nice work Oli..  Somewhere in the middle, between Home arrow and Radar.

It would be good to integrate into it, a reference of HOME location behind you. That way you wouldn't need to have the Home Arrow and Smart cross hair on the OSD together. 
As it is, you have to do at least a 120deg turn around, to know where home is. While with the Home Arrow, you can see the direction of Home at a glance.
But I do like its increased accuracy over the Home Arrow. 

Don't take my statement as criticism.  I'm only thinking practically. : )

**Comment by OlivierC-FR** [comment]
I agreee it would help to know where the home is in the 180° arc behind, I'll tweak it so it displays this information. And add an user-selectable Y offset for the crosshair and AHI.

**Comment by OlivierC-FR** [comment]
I made a code update so it also indicates the areas behind, as follow, will push the code once it's been tested live.

smartch

**Comment by OlivierC-FR** [comment]
Vertical arrow scales like that, depending on the focus setting :
smartch_v

**Comment by kardon18** [comment]
> 
> 
> I made a code update so it also indicates the areas behind, as follow, will push the code once it's been tested live.


I look forward to seeing it in action. Post another video once you have test it.

**Comment by ghost** [comment]
> 
> 
> I made a code update so it also indicates the areas behind, as follow, will push the code once it's been tested live.


I look forward to seeing it in action. Post another video once you have tested it.

**Comment by shellixyz** [comment]
@OlivierC-FR Nice drawings indeed and good idea

**Comment by OlivierC-FR** [comment]
There's a bug when 1 arrow-left and 3 arrow right, will fix.
Made use of it today through the clouds : https://drive.google.com/file/d/17hk8e7_EUD8t5cB0MUmlrFFCq7afvPRC/view

**Comment by wx4cb** [comment]
that's cool... i'm guessing that this means it's left and below you? 
image

**Comment by OlivierC-FR** [comment]
Closing for now, got a better idea on how to do this

**Comment by OlivierC-FR** [comment]
Closing for now, got a better idea on how to do this

**Pull request closed without merging**
