### PR TITLE
Move some variables to CCM (RAM savings) - phase 2

### PR DESCRIPTION
**Pull request by digitalentity**
Per #2090, continuation of #2092

- [x] Move performance-critical variables to CCM
- [x] De-`static`-alize variables that fit into stack and are not requited to be permanent

#2092 must be merged first, then this PR should be rebased on top of it

### CODE REVIEW

**Comment by digitalentity** [comment]
On SPRF3: 
1416 bytes of gyro/acc/PID/IMU & scheduler state moved to CCM. Total RAM gain is 5528 bytes.

On REVO:
1416 bytes of gyro/acc/PID/IMU & scheduler state moved to CCM. Total RAM gain is 5536 bytes (probably due to alignment).

**Comment by digitalentity** [comment]
Candidates to be moved to fastram:

1. Motor mixer
2. Servo mixer
3. NAV estimation
4. FC core

**Comment by digitalentity** [comment]
Funny thing is that on F4/F7 we can fit almost everything in CCM

**Comment by martinbudden** [comment]
Well, I've done some benchmarking and disappointingly it doesn't give much speedup, maybe 1% on the main PID loop (both on F3 and F4 boards). I remember we also got about 1% when we put the stack into CCM. Still 1% is 1%, and we get the RAM saving as well.

I don't see any downside to merging this in.

We can add further PRs to do other systems in future.

**Comment by digitalentity** [comment]
Well, the slowest part of CPU is flash memory. If we would load some code into CCM it would certainly make a difference, but that's not a simple task. Anohow, the primary goal of this PR is to make use of all available memory - performance gain being a side effect.

Merging!

**Pull request merged**
