### PR TITLE
Nox board support

### PR DESCRIPTION
**Pull request by mooiweertje**
I created a NOX target for my NOX board: https://www.banggood.com/20x20mm-Betaflight-F4-Noxe-MPU6000-Flight-Controller-AIO-OSD-5V-BEC-Built-in-LC-Filter-for-RC-Drone-p-1310419.html
It should also support the original Airbot NOX: https://store.myairbot.com/noxv2.html
Tested: FW_MOTOR1 FW_servo 1 and 2, UART1RX/TX, SBUS, OSD, VBATADC, GYRO, ACC, BARO, PPM
not tested: MC, FW_MOTOR2, LED_STRIP

### CODE REVIEW

**Comment by mooiweertje** [comment]
The warnings didn't show on master. I can fix them if you like.

**Comment by DzikuVx** [comment]
@digitalentity what do you say for 2.1?
@mooiweertje please add a board description in docs folder so users know which target it is for and what the board can do

**Comment by mooiweertje** [comment]
Hey the new target.c is the same as Betaflight

**Comment by mooiweertje** [comment]
@DzikuVx @teckel12  Board description added and fixed the target.c warnings
@digitalentity Would be great in 2.1

**Review by shellixyz — APPROVED** [review]

**Comment by mooiweertje** [comment]
Great, thanks!

**Comment by albebert** [comment]
great job, just a little question where i can download the hex file ?

**Comment by mooiweertje** [comment]
It's not released yet, but I can send you an unstable development version if you know what you are getting in to.

**Comment by albebert** [comment]
yes an alfa version would be very usefull for me :) 

another question, have you an idea for a date of an official release ?

**Comment by mooiweertje** [comment]
You can download a test version here: https://we.tl/t-JXl8Zx4K5I
If you encounter any problems please let me know.

Official release, if all is normal, is the ongoing release of 2.1.

**Comment by mooiweertje** [comment]
You can download a test version here: https://wetransfer.com/downloads/497685260b27036eca4b5e1701633e7620190210111752/86d85ef44b0d566c18f81a67474b300620190210111752/a8123f
If you encounter any problems please let me know.

Official release, if all is normal, is the ongoing release of 2.1.

**Comment by albebert** [comment]
many thanks

**Comment by FranzAr** [comment]
@mooiweertje  It seems there's a new version of this board. The NOX target doesn't work for this one. BF target is FLYWOOF411 now.

**Comment by mooiweertje** [comment]
Is someone working on the FLYWOOF411 yet or can I implement it. I've got two of the new boards so....

**Pull request merged**
