### PR TITLE
GPS: Changed LOW_G setting to Airborne<1G

### PR DESCRIPTION
**Pull request by digitalentity**
Should make LOW_G default more reliable and accurate.

### CODE REVIEW

**Comment by gaelj** [comment]
Are you aware of this ?
https://github.com/cleanflight/cleanflight/blob/master/docs/Gps.md#ublox-navigation-model

**Comment by stronnag** [comment]
@digitalentity, what is your view now on LOW_G and velend = on; it is now a viable option?

**Comment by digitalentity** [comment]
@gaelj what exactly? Pedestrian navigation model? We used that before in INAV (aka LOW_G) - didn't work well on fast quads. Now LOW_G is Airborne<1G and HIGH_G is Airborne<4G.

@stronnag we need to test more. I feel velned=off is a safer default

**Comment by gaelj** [comment]
Yes, I was refering to Pedestrian nav model being preferered in the CF documentation.
In this case this PR would be perfect with an update of the INAV GPS documentation.

**Pull request merged**
