### PR TITLE
Anti AOA Stoll

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
this can be tested and improved. The idea is to avoid a Stoll on the AOA when the angle is greater than 50 degrees 
and if the autopilot is active. Even though the pilot pushes up, the AOA will descend even further. This feature has been implemented on the Boeing 737 MAX since 2019, and I thought it would be nice to have iNav.

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
later when I have more time, I'll review the math, because I think there's something wrong, or maybe not

**Comment by JulioCesarMatias** [comment]
I put it to the function to change the value of `fixedWingLevelTrim` just to not create another global variable that would do the same thing

**Comment by DzikuVx** [comment]
@JulioCesarMatias the logic over here is flawed in a way that AOA is not a pitch angle. AOA is an angle between wing chord and the air flow vector. It's independent from pitch angle.  
Have you tested this in flight?

**Comment by JulioCesarMatias** [comment]
@DzikuVx  yes, the logic is really wrong, but the idea is just not to let the pilot go up his nose any more when the autopilot is active and with the AOA at critical degrees, for example 50 degrees. Maybe someone is interested in developing this in the future.

**Comment by DzikuVx** [comment]
@JulioCesarMatias what can be done is to compare speed vector with pitch angle. That would give much nicer AOA estimation

**Pull request closed without merging**
