### PR TITLE
Support for more AIRBOT boards & a few other improvements

### PR DESCRIPTION
**Pull request by digitalentity**
- Support for F411 CPU
- Support for new boards: Asgard32 F4, Fireworks V2, Omnibus F7 NXT
- Bugfix for CLI sensor list
- Bugfix for incorrect (too fast) SPI clocks on F7
- Add Softserial support to F7

### CODE REVIEW

**Comment by Pairan** [comment]
does this include the ones from Matek?

> Support for F411 CPU

**Comment by digitalentity** [comment]
@Pairan it doesn't include the board support by itself, but it should be possible to add F411-based targets from Matek after this is merged.

**Comment by Pairan** [comment]
okay :) ... this would open up for smaller wings to carry a reliable fc like the minis from Matek

**Comment by fiam** [comment]
@Pairan Matek F411 is now PR'ed and will be on 2.0. See #3146

**Comment by Pairan** [comment]
Nice .... closing the gap :)

**Comment by fast12learn** [comment]
Target check 
Airbot just released this board in the past few weeks. 
https://store.myairbot.com//media/iverve/uploadpdf/1527195262_OMNIBUSF4NanoV6.pdf
I contacted Airbot support about an appropriate iNav target. They stated that BF Omnibus F4fw (Firework) works with this board. I’ve tried the firework v2 target in iNav but received “connection time out. The board failed to respond in 10 seconds” I’ve tried every other Omnibus F4 target. Each has its own problem usually pwm 4 has no output. Tried looking in rcgroups.com  Any links or different targets I should try?

**Comment by digitalentity** [comment]
@fast12learn see https://github.com/iNavFlight/inav/pull/3294

**Pull request merged**
