### PR TITLE
Add support for FrSkyOSD version 2

### PR DESCRIPTION
**Pull request by fiam**
- [OSD] Change default counts per divisions in sidebars, make them configurable
- [OSD] Allow moving sidebars left and right 
- [FRSKYOSD] Add support for increasing the default data rate
- [MSP/CLI] Constrain receive baud rates indices to their valid values
- [OSD] Fix clearing of the local OSD buffer
- [OSD] Use sidebar widget for drawing sidebars when available
- [OSD] Add AHI settings for widget based AHI
- [OSD] Split OSD configuration into osdConfig_t and osdLayoutsConfig_t
- [OSD] Add support for using widgets for drawing
- [FRSKYOSD] Use new commands for grid drawing

### CODE REVIEW

**Comment by Pairan** [comment]
I love to see the progress on the pixelOSD, @fiam  ... thanks for your efforts. Perhaps some day we all fly pixels instead of char-based.

**Comment by fiam** [comment]
@Pairan Thanks for your interest! I'm setting up everything for the public beta of version 2. If you want to take a look at the new widgets, you can already download the OSD simulator from here https://github.com/FrSkyRC/PixelOSD/tree/master/simulator and see some of the new features of version 2.

**Comment by Pairan** [comment]
just playing around ... looks good . PixelOSD ... que fuerte!!! :) me gusta! i will watch this as it grows!

**Comment by Target0815** [comment]
Hi @fiam,

**Pull request merged**
