### PR TITLE
Fix softserial broken by timer mapping changes

### PR DESCRIPTION
**Pull request by digitalentity**
As reported by @stronnag in https://github.com/iNavFlight/inav/pull/1591#issuecomment-310836371
So far only SPRacingF3 target. Testing required.

### CODE REVIEW

**Comment by stronnag** [comment]
Bench tested OK. Will fly the new timer stuff in a couple of hours (+bbox fixes).

**Comment by digitalentity** [comment]
@stronnag great!

**Comment by stronnag** [comment]
Flight tested (timers in general), on two machines, both quads, OMNIBUS F3 AIO and DODO, serial RX, GPS, telem via uart or softserial. No problems at all, over 16 flights.

**Comment by digitalentity** [comment]
@stronnag thanks for testing!

**Pull request merged**
