### PR TITLE
Require "off-on" switch cycle to activate WP mission

### PR DESCRIPTION
**Pull request by digitalentity**
A follow-up for #152

### CODE REVIEW

**Comment by theArchLadder** [comment]
Why has this not been merged yet? Does it need to be flight tested? Perhaps i can help with that.
Seems like a good safety feature to have.

**Comment by digitalentity** [comment]
I didn't have a chance to test it yet. If you will be able to test it, I'll
merge asap.

**Comment by theArchLadder** [comment]
So activated wp-mission, then activate rth, then deactivate rth and make sure wp-mission is not resumed... Right?
Is there anything else/any other scenario i should test?

Will try it tomorrow.

**Comment by digitalentity** [comment]
Yes, exactly. Activate mission, activate rth, deactivate rth, make sure wp
is not restarted.

**Comment by theArchLadder** [comment]
Flight tested!
Works as expected, it just goes into position hold.
Hmm, does WP-mode require poshold? I did not test without poshold activated.

I also tried follow-me with ez-gui. Deactivating RTH resumes follow-me(GCS_NAV), perhaps it would be better to block GCS_NAV in the same way? Poshold seems like the safest thing after deactivating RTH.

**Comment by digitalentity** [comment]
Thanks for testing. I'm not sure why it entered PH, it actually should have switched to full manual. Perhaps you have PH activated along with WP?

**Comment by theArchLadder** [comment]
Yes, i did, does WP not require poshold? If so, i will do a short test flight in a few minutes.

**Comment by digitalentity** [comment]
No WP is autonomous, it doesn't require PH.

**Comment by theArchLadder** [comment]
Did another test flight.
Only WP active now, and deactivating RTH does indeed give me rate mode.
Forgot to mention earlier that WP mission can be restarted by just toggling the WP switch.

Everything seems to work as expected now, as far as i can tell. :smile:

**Comment by digitalentity** [comment]
Yes, my intention was to make WP mission restartable with switch toggle - an additional safety measure to avoid accidental re-activation of WP when aborting RTH. Thanks! Now when 1.1 is released we can start looking into new features!

**Pull request merged**
