### PR TITLE
Convergence of code for different receiver types PPM/PWM/MSP/serial.

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by martinbudden** [comment]
All - I'm fairly confident this code is working fine, it has been implemented in Cleanflight and betaflight. However, since it effects all the serial receiver types it should be tested with different receiver types.

@digitalentity , @stronnag , @DzikuVx could you bench test it with whatever types of receivers you have so it can be merged in?

**Comment by stronnag** [comment]
bench tested (i.e. expected movements in configurator / receiver tab) for serial (Spektrum) 

However, my PPM  locked on YAW of 2002. First just on USB, second on current limited battery (just as well limited, as this was after stick ARM).

Prior to locking, everything was normal (stick responses).

This was with 687 as a diff applied (cleanly) to current development.

**Comment by stronnag** [comment]
Seems I can reproduce this problem at will.Actually, similar happens with serial (Spek). Only there it seems to recover after about 3-5 seconds.

**Comment by stronnag** [comment]
Comments deleted. I don't think there is a problem. I forgot I have BBox on arm (idiot!)

**Comment by stronnag** [comment]
Content. Appears fine on serial (Spektrum) and PPM. Apologies for the erroneous reports.

**Comment by martinbudden** [comment]
No worries. Thanks for testing.

**Comment by digitalentity** [comment]
@martinbudden, @stronnag is it safe to merge this?

**Comment by stronnag** [comment]
Based on solely benchtests, yes for my hardware.

**Comment by martinbudden** [comment]
I'm fairly confident in this code - it is running on Cleanflight and betaflight. It's not fully tested though, because I don't have one of each receiver type.

I'd be inclined to merge it in.

**Comment by stronnag** [comment]
flight tested PPM and serial / Spektrum - no issues.

**Pull request merged**
