### PR TITLE
Multirotor modes removed from Planes

### LINKED ISSUE #7596: Multirotor modes shown when fixed wing connected
FPV ANGLE MIX and SURFACE appear as multi rotor modes when a fixed wing is connected. I'm guessing this might be related to the mode definitions in INAV fc_msp_box.c perhaps more than a Configurator issue ?

### PR DESCRIPTION
**Pull request by erstec**
Fixes #7596

### CODE REVIEW

**Comment by DzikuVx** [comment]
@erstec please make this change on top of `release_4.0.0` branch

**Comment by erstec** [comment]
> @erstec please make this change on top of `release_4.0.0` branch

@DzikuVx done

**Review by DzikuVx — APPROVED** [review]

**Comment by breadoven** [comment]
This doesn't cover SURFACE mode which is also MC specific. I also noticed that only ALTHOLD is dependant on having an altitude sensor whereas the other NAV modes aren't when surely they won't work without altitude available ?

**Comment by erstec** [comment]
> This doesn't cover SURFACE mode which is also MC specific. I also noticed that only ALTHOLD is dependant on having an altitude sensor whereas the other NAV modes aren't when surely they won't work without altitude available ?

I've checked it on MAMBAF405. All mentioned modes was gone from Configurator. 
Of course I can add additional define to make sure SURFACE mode are removed too. I will do that shortly.
Can you explain how you achieve that you see it in Configurator? I just want to check it too.

Regarding next part of your message of "what depends on what": it was untouched and if you see there problem here, can you explain it. And, I believe, separate issue can be created.

**Comment by erstec** [comment]
> I had a look at this related to #7596. Didn't see the logic in the way SURFACE is defined only in relation to altitude sensors but not rangefinder or opflow sensors and then also realised that none of the Nav modes other than ALTHOLD are dependent on altitude sensing ... which they must be. I guess the Nav mode altitude dependency could be done as a separate issue but if SURFACE is part of this PR it needs the right sensor requirement defining surely rather than just altitude.

BOXSURFACE is already defined for Multirotors only. And commited here.

**Comment by erstec** [comment]
> It depends how clever you want INAV to be in preventing you from setting up modes that aren't supported by the hardware at the time the modes are set up in Configurator I guess. No point showing SURFACE mode if there's no Rangefinder or Opflow ? sensors configured.

Absolutely! 

But... it is not only hardware dependencies here, but "working mode" and configuration also. It depends on what type of UAV you select during very first boot and etc. Same FC can be used in various UAVs, you know.

To make it clear and correct, we need clearly specify what depends on what, but unfortunately I have no enough knowledges about that, I am just joined contribution to iNav, don't judge me so hard :) I need some time to understand all (whole) codebase. But if you have suggestions and can provide some help - I'll very appreciate it! And we will do all together :)

**Comment by breadoven** [comment]
Good of you to contribute @erstec. Saved me doing this instead and having to find out SURFACE sensor requirements which I'm not completely sure about since I've never used it.

**Comment by MorrisR2** [comment]
> none of the Nav modes other than ALTHOLD are dependent on altitude sensing ... which they must be

Planes generally don't need a barometer to user the various nav modes. GPS is "close enough" for the altitudes that planes normally fly.  Vs multirotors which are more likely to fly low and therefore need more accurate altitude.

**Comment by MrD-RC** [comment]
I disagree about the baro. I’d much rather have the better accuracy that baro offers over GPS. Especially when I’m skimming centimetres off the ground. It totally depends on how you fly the plane.

**Comment by MorrisR2** [comment]
@MrD-RC  I said "GPS is "close enough" for **higher altitudes where being two meters off isn't a problem**"
You replied "when I’m skimming centimetres off the ground".

It sounds to me like we're in perfect agreement.  If you set 200 meters altitude, being at 198 or 202 probably doesn't matter.
If you set 20 centimeters, being a meter lower than that is a problem. :)

Regardless of anyone's preferences, the fact is inav does NOT require a barometer for navigation modes.  You or someone may think that inav SHOULD require centimeter accuracy at 200 meters, but it simply doesn't.

**Comment by MrD-RC** [comment]
But you’re assuming that everyone flying fixed wing is at a “higher altitude”. Which is simply not true.

**Comment by MorrisR2** [comment]
Where did I say that?

**Comment by breadoven** [comment]
> > none of the Nav modes other than ALTHOLD are dependent on altitude sensing ... which they must be
> 
> The various nav modes don't require a barometer aka altitude sensor. Planes often don't have one, but instead use GPS altitude. GPS is "close enough" for higher altitudes where being two meters off isn't a problem.

As it stands there is no check in` fc_msp_box.c` for altitude being available for any Nav mode other than Althold. This is either from a Baro or via GPS. When only a GPS is available a fixed wing will use GPS altitude by default, so not an issue, but a multirotor will only use GPS altitude if `inav_use_gps_no_baro `is set ON (Default = OFF). So it's possible to have no Baro on a multirotor and `inav_use_gps_no_baro `set OFF and still be able to set all Nav modes **other** than Althold in Configurator when these modes won't work without a valid altitude.

Also Althold is only available if a GPS is defined which doesn't make sense if a Baro is available.

**Pull request merged**
