### PR TITLE
Multi function OSD utility

### PR DESCRIPTION
**Pull request by breadoven**
Provides a dual purpose Multi Function OSD utility field used as a Warning display and also to allow activation of infrequently used functions/modes.

Warnings are displayed for 10s when first triggered after which the warning disappears to be replaced with an alert symbol with a number showing the active warning total. Active warnings are then redisplayed for 5s on a rolling 30s cycle. The field is blank if there are no warnings. Current Warnings are provided for Battery state, Vibration level, GPS Fix or Failure, RTH Sanity (>200m heading in wrong direction), Altitude Sanity (difference between estimated and GPS altitude > 20m), Compass failure and Ground Test mode being active. A BARO health warning could be added (https://github.com/iNavFlight/inav/pull/8233 and https://github.com/iNavFlight/inav/pull/8534).

Functions use a single mode to select between different functions based on feedback provided by the Multi Function OSD field. Functions are selected by briefly toggling the mode ON/OFF with this sequence repeated until the required function is displayed in the OSD. The function is then triggered by activating the mode for > 3s. Deactivating the mode for > 3s resets everything leaving the OSD field blank. Ideally a momentary switch should be used to operate the mode although it should also work with a normal switch. Current functions include redisplaying any warnings, emergency landing activation, Safehome suspend, Trackback suspend, Turtle mode activation and an Emergency arming function (which does the same as the multi toggle Emergency arming but using the 3s function trigger instead). The first function is deliberately set to redisplay warnings only so this is all that should happen if the mode is triggered accidently (likely if a non-momentary switch be used).

Tested on the HITL sim OK. There could be an issue with RC latency at longer ranges interfering with the timings for function selection. Needs testing to know if it's likely to cause a problem. And I guess this won't work for some HD OSD systems ?

### CODE REVIEW

**Comment by MrD-RC** [comment]
I think a handy addition would be the ability to switch between RTH to home point or safehome from that functions menu.

**Comment by MrD-RC** [comment]
Yes, I agree. I think 10 would be about the maximum you could have. Plus having options that are not available or easy to use would be advantageous. For example, your manual emergency landing. I know that can be activated by toggling the pos hold switch. But some mode switch setups, the toggling action could be tricky to perform.

**Comment by breadoven** [comment]
> For example, your manual emergency landing. I know that can be activated by toggling the pos hold switch. But some mode switch setups, the toggling action could be tricky to perform.

I did realise it can be awkward to multi toggle using "Sticky" momentary switches. Can be done but not easy doing it quickly. However, I did work out how to get a Sticky switch to auto toggle if you press and hold it, combination of Sticky and Timer. Short press just gives you the usual Sticky toggle action, but long press sees it switch ON/OFF at whatever frequency you set using the Timer.

**Comment by breadoven** [comment]
Added function to suspend Safehomes. Currently works for RTH and FS RTH. Might be desirable to limit this function to normal RTH only so FS RTH uses Safehomes regardless ?

**Comment by Jetrell** [comment]
> Might be desirable to limit this function to normal RTH only so FS RTH uses Safehomes regardless ?

That makes sense. We can't really select anything under an RX failsafe condition.
I was also thinking it may be beneficial to enable RTH Trackback via this method, with the same non FS logic as you've applied to Safehome? This may benefit boats and rovers too,

**Comment by MrD-RC** [comment]
Yeah, I'd agree with that. Leave FS as what is set up pre-flight.

**Comment by Jetrell** [comment]
@breadoven I'm not sure if you're looking for other fields to add? 
 I had thought of `Magnetometer disable` for fixed wings. In cases when the course tracking may be too heavily influenced by it on a windy day.   
But without being able to ever disable it in flight before. I wasn't sure if just turning it off without a reboot, was possible, or would have any bad side effects?

**Comment by breadoven** [comment]
I think is is OK to merge now. Only thing missing are digital fonts for a general alert symbol, yellow triangle with a ! inside ... or something similar.

**Comment by Choolet** [comment]
> Functions are selected by briefly toggling the mode ON/OFF with this sequence repeated until the required function is displayed in the OSD. 

@breadoven Would I be correct in saying the toggle action ranges from 1000 - 2000 microseconds?
Is it possible for the toggle range to be smaller?  For example 1000 - 1200. 

I like this feature because it adds functionality when few RC channels are left.
In my case I have many modes and other features on small portions of the same channel, by using TX mixers. 
I would like to use this feature on the same channel as other modes.

**Comment by breadoven** [comment]
> @breadoven Would I be correct in saying the toggle action ranges from 1000 - 2000 microseconds? Is it possible for the toggle range to be smaller? For example 1000 - 1200.

The toggle action is just based on selecting the Multifunction mode ON/OFF so it just depends on how you've set the mode up in the Configurator modes tab. Doesn't need to be 1000-2000.

**Pull request merged**
