### PR TITLE
Drop MSP_DISPLAYPORT as not supported

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by ligenxxxx** [comment]
But I want to use MSP_DISPLAYPORT for sharkbyte.

**Comment by DzikuVx** [comment]
@ligenxxxx It was never supported and working with INAV. It's just a cleanup

**Comment by ligenxxxx** [comment]
Yes, I know that.
Do you mean no one will continue to improve msp_displayport?
To be honest, I really need this feature. I have figured out how it works, and plan to update the display mode of osd elements to msp_displayport in future firmware (sharkbyte) instead of requesting and parsing the relevant parameters of RC through the msp protocol.
If inav can be consistent with betaflight, then sharkbyte can use the same firmware to implement betaflight and inav osd elements displayport. Otherwise, inav may not be able to support the complete osd. Or let sharkbyte use dji's osd protocol?

**Comment by DzikuVx** [comment]
@ligenxxxx you are free to work on making MSP_DISPLAYPORT working with INAV. If you can fix it and test the fix on INAV side, we really do not have to remove the dead code

**Comment by ligenxxxx** [comment]
I want to try.

**Comment by ligenxxxx** [comment]
I want to try to improve, but I can't guarantee it can be done 100%.  I am modifying the code these days.

**Comment by DzikuVx** [comment]
@ligenxxxx any progress with fixing MSP_DISPLAYPORT ?

**Comment by ligenxxxx** [comment]
> @ligenxxxx any progress with fixing MSP_DISPLAYPORT ?

#6483

**Pull request closed without merging**
