### PR TITLE
Fixed wing launch mode failsafe fixes

### LINKED ISSUE #10483: Disarmed by Failsafe when the aircraft should entered have RTH
There have been a couple of reports where people have experienced a failsafe and the aircraft immediately disarms. An example of this can be found on the [INAV Fixed Wing Group on Facebook](https://www.facebook.com/1736758230/videos/563692736615847/). In the example, the aircraft autolaunches. As soon as it exits autolaunch, there is a failsafe. But instead of actioning RTH. The aircraft disarms. This aircraft was running TBS Crossfire, and had been working fine before. The only change being an update of the Crossfire firmware. However, there has also been a similar incident with an aircraft using ELRS. Both times the failsafe procedure was set to RTH.

It is unknown if this is an INAV issue, or related to the link. This is an information compilation at the moment. To try and find some correlation on what is happening.

If this has happened to you. Please could you reply to this issue giving as much detail as possible on your setup and what happened. If possible please include the following details (copy and paste this list as a template if it's easier):
- INAV Firmware version:
- Flight Controller hardware and target:
- Transmitter hardware and firmware version:
- Receiver hardware and firmware version:
- Failsafe setup on the receiver (if possible):
- Link to DVR footage with OSD overlaid:
- Text file containing the `diff all` from the flight controller
- Text file containing the Blackbox log from the flight:

If you cannot provide the DVR with OSD. Please include a description of the flight. If you could not recover the aircraft. A backup diff from before the flight will be fine. If you're not sure how to add your diff as a text file. Check out [this video](https://www.youtube.com/watch?v=Eul5BLyLoP0&t=980s).

### Example form:
- INAV Firmware version: INAV 7.1.2
- Flight Controller hardware and target: Matek H743-WING v3 - MATEKH743
- Transmitter hardware and firmware version: TBS Crossfire full size 6.17
- Receiver hardware and firmware version: TBS Crossfire Micro 6.17
- Failsafe setup on the receiver (if possible): Failsafe set to Cut
- Link to DVR footage with OSD overlaid: < link to youtube video >
- Text file containing the `diff all` from the flight controller <diff.txt>
- Text file containing the Blackbox log from the flight: <Blackbox.txt>

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/10483.

### CODE REVIEW

**Comment by Jetrell** [comment]
I gave it a test by taking off in Auto Launch and letting it climb for a while, then switched to FS mode.
It proceeded to enter RTH and once it got close to the Safehome it started the LAND procedure, which I have enabled.. I tested it twice and it performed the same.. So the fix appears to work.

>RTH state and decides it's failed causing failsafe to default to Emergency Landing instead

Can I assume you had to do a scheduling work around to get this to initialize ?  I noticed when it entered FS in AutoLaunch _ALL_ the OSD screen characters will systematically flash. Like an OSD refresh was missed at that moment (Analog video).
While it didn't do that with earlier firmware DVR files I looked at.
This is no big issue. I just thought it worth mentioning.

>Guess not many people have Failsafe's during launch because these bugs have been there for a long time.

I've never had a FS happen at launch.. But after reviewing old mates video.. He was at 325m and AutoLaunch was still going. 
At that altitude the TX/RX antenna's would have been operating in their null's.

And as a side note to this being an old bug.. I remember an issue report being opened by a user back in INAV 2.0.. I had a look, but couldn't find it.
It was about a guy who auto launched his plane. And at the moment he threw it, the throw inertia disconnected his RX plug, and the FC entered FS.
From what I vaguely remember. At the time, Konstantin wanted to leave it as DROP... In cases like this, when entering an `nav_rth_altitude` mode that has no climb out, could cause the plane to turn into an object like a tree, if a FS condition was entered straight after the throw.
Back at the time there was debate about this and nothing was obviously done... In hindsight I think a method to deal with this would be to have `nav_rth_altitude` overridden to EXTRA, if an Auto Launch FS occurred at less than 40m above the arming altitude.

But in any case, I think your fix was more needed than not.

**Comment by b14ckyy** [comment]
Finally managed to run some HITL tests last night as well. Can confirm that no issues appeared when FS during Autolaunch, even with long climbs and distances. That was on a F405 though.

**Comment by MrD-RC** [comment]
So the lowest spec supported MCU 😉

**Comment by MrD-RC** [comment]
Both tests look positive. So I'll merge it for RC2.

**Pull request merged**
