### PR TITLE
Reset fixed wing heading status on disarm

### LINKED ISSUE #8148: Fixed wing heading status not resetting after landing disarm
Heading status remains trusted even after a fixed wing has landed and been disarmed which doesn't make sense. GPS CoG is no longer valid so Heading status can't be trusted and should be reset. The following change would fix this in imu.c (https://github.com/iNavFlight/inav/blob/3cb8e80c96dcb5380666e8b1a0644454a75f8e3a/src/main/flight/imu.c#L555):

```
        if (canUseMAG) {
            useMag = true;
            gpsHeadingInitialized = true;   // GPS heading initialised from MAG, continue on GPS if compass fails
        }
        else if (canUseCOG) {
            if (gpsHeadingInitialized) {
                courseOverGround = DECIDEGREES_TO_RADIANS(gpsSol.groundCourse);
                useCOG = true;
            }
            else {
                // Re-initialize quaternion from known Roll, Pitch and GPS heading
                imuComputeQuaternionFromRPY(attitude.values.roll, attitude.values.pitch, gpsSol.groundCourse);
                gpsHeadingInitialized = true;

                // Force reset of heading hold target
                resetHeadingHoldTarget(DECIDEGREES_TO_DEGREES(attitude.values.yaw));
            }
        } else if (!ARMING_FLAG(ARMED)) { 
            gpsHeadingInitialized = false;
        }
```

Or is there some reason for not resetting `gpsHeadingInitialized  `in these circumstances ?

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/8148.

### CODE REVIEW

**Review by JulioCesarMatias — APPROVED** [review]
LGTM!

**Comment by DzikuVx** [comment]
Let's have it in 5.1 that will happen probably in a month or two. Nice bugfix after all. Thanks @breadoven

**Comment by breadoven** [comment]
I suppose the only question is whether it should also apply in flight if GPS CoG isn't valid, i.e. when gale hanging, < 3m/s ground speed. GPS position would be good but not heading. If heading is set as not trusted in these circumstances it would cause RTH and WP mode to emergency land. Then again with no heading RTH and WP mode won't work so landing or switching to manual control is the only option.

As it is now I assume the plane will start to wander if ground speed drops below 3m/s and heading becomes unreliable even though heading remains trusted. So is emergency landing better as a warning or let it wander hoping the pilot realises something's wrong ?

**Comment by DzikuVx** [comment]
cherry-picked to 5.1 branch

**Pull request merged**
