### PR TITLE
Manual emergency landing FW and MR

### LINKED ISSUE #5000: [REQUEST] Manual (Emergency) Landing for Wings and Copters
## Current Behavior
Emergency landing is only triggered in case of sensor failure during Failsafe or as Landing at home point. 

## Desired Behavior
We should be able to trigger a GPS assisted landing with a switch

## Suggested Solution
Following Scenario: 

- A long range pilot realizes that the battery won't last for the way back
- pilot searches for a save landing spot like a open field and flies over it
- pilot triggers landing and plane will go into circle down with throttle cut to zero till it touches ground and disarms, Copters will fast descent at emergency landing descent speed
- maybe only uses throttle on a wing to compensate for strong wind drift above a specified threshold
- failsafe must be ignored in this state as in long range the pilot will likely loose connection before touchdown
- after landing, pilot can use telemetry data to find the plane in a very specific area

## Who does this impact? Who is this for?
All Long range pilots that touch the limit of their battery capacity. Also pilots that maybe have a faulty battery. 

## Additional context
This feature would be a huge security benefit as the pilot is able to control where the plane or copter will go down in a unpopulated area instead of letting it glide uncontrolled if the FC looses power too. A manual emergency landing won't be possible on long range as the connection will likely be lost at low altitudes and then the craft will likely failsafe and try to climb again. 

Setting Failsafe to LAND is no option on long range as the RTH should still work if there is no issue with the battery.

### PR DESCRIPTION
**Pull request by breadoven**
Closes https://github.com/iNavFlight/inav/issues/5000.

Allows an emergency landing to be triggered manually as required.
Landing started or ended by rapid toggling of Poshold mode, at least 5 times at a minimum rate of 1Hz.
Emergency landing position hold added which will work for all emergency landings regardless of cause so long as a valid position is available.
Failsafe inhibited during manual emergency landing to allow landing to continue if Failsafe triggered whilst active.

HITL tested on fixed wing OK. Still needs testing on multirotor.

### CODE REVIEW

**Comment by breadoven** [comment]
Now tested on multirotor and it behaved as expected ... landed and disarmed.  Multi switching of PosHold to trigger the landing doesn't do anything obviously undesirable. So this should be good to merge if considered a worthwhile addition.

**Comment by DzikuVx** [comment]
@breadoven code from you is always a worthy addition! Happy to merge

**Comment by breadoven** [comment]
> @breadoven code from you is always a worthy addition! Happy to merge

I guess with features like this, that probably won't be used much, it's always a question of is it worth the increase in firmware size. Some boards don't seem to have much space left, e.g. HGLRCF722 is now up to 95%. Although half the flash memory on that board seems to be unused, ITCM_FLASH1 ?

**Comment by DzikuVx** [comment]
Flash is to be used 🤣 if it runs out we will disable something less important.

On the topic of itcm_flash @ErNis do you think we can easily move done code to itcm flash? We use itcm ram byncopying flash to it. But no sure about how complex the bootloader changes would be

Paweł Spychalski
________________________________

**Pull request merged**
