### PR TITLE
HITL: hd osd support

### PR DESCRIPTION
**Pull request by RomanLut**
HD OSD support in HITL.
Can be checked with latest plugin (not released):
https://github.com/RomanLut/INAV-X-Plane-HITL/tree/main/release
HITL will render HD OSD if HD OSD is configured  on FC.

### CODE REVIEW

**Comment by RomanLut** [comment]
image

**Comment by breadoven** [comment]
Updated to the current INAV master and the OSD has disappeared in HITL 1.3.0. Is this because you need to update the plugin ... win.xpl ? Is there a way of switching it back to work as it did before, sort of reverting this change ?

**Comment by MrD-RC** [comment]
If you update the plugin, the OSD works fine.

**Comment by RomanLut** [comment]
> Updated to the current INAV master and the OSD has disappeared in HITL 1.3.0. Is this because you need to update the plugin ... win.xpl ? Is there a way of switching it back to work as it did before, without reverting this change ?

Yes you have to update plugin to current master, from directory https://github.com/RomanLut/INAV-X-Plane-HITL/tree/main/release
I will make proper release theese weekends.

**Comment by breadoven** [comment]
I copied the entire folder content in the end rather than just the files that appeared to have been changed recently, and it work now. Odd that Github doesn't appear to have an easy way of downloading folders without using 3rd party tools.

**Comment by RomanLut** [comment]
> I copied the entire folder content in the end rather than just the files that appeared to have been changed recently, and it works now. Odd that Github doesn't appear to have an easy way of downloading folders without using 3rd party tools.

Github allows to download whole repository

image

**Comment by breadoven** [comment]
You can download the entire repo but if you only want a single folder such as the release folder above you can't download it directly. I used https://download-directory.github.io/ in the end.

**Pull request merged**
