### PR TITLE
FW Launch idle throttle motor start time delay

### LINKED ISSUE #6873: Autolauch idle throttle delay activation
## Current Behavior
At the moment if idle in autolaunch is set above 0 motor spins the moment throttle stick is rised.

## Desired Behavior
An user selectable countdown time between throttle stick moved from 0 and idle throttle applied

## Suggested Solution
An option in CLI or GUI to enter desired delay time (10s default) from activating autolauch to spinning the motor. 

## Who does this impact? Who is this for?
Everyone who autolaunches a plane that needs idle running and a firm hold on the plane with two hands.

## Additional context
The idea is simple - instead of picking up the model and using for example your foot to raise the throttle on the transmitter sitting on the ground because I hold the model with both my hands we could have a countdown option in which after raising the trhottle INAV would countdown for an user programmable amount of time before actually spinning the motor in idle. This would allow us to safely activate the autolaunch, pick up the model from the ground, wait for idle and throw.

### PR DESCRIPTION
**Pull request by breadoven**
Resolves https://github.com/iNavFlight/inav/issues/6873.

Provides a time delay between raising throttle and the motor starting at idle of between 0 (default) and 60s.

### CODE REVIEW

**Comment by avsaase** [comment]
I agree with @MrD-RC's suggestion of having a beeper sequence that gives some indication of how long you have until the motor starts idling.

**Comment by breadoven** [comment]
> I agree with @MrD-RC's suggestion of having a beeper sequence that gives some indication of how long you have until the motor starts idling.

I did think of changing the beeper but the current launch beeper beeps every 1.15 seconds giving some idea of how long you've got. Could change to a more rapid beep 2s or so before the motor starts I guess. I'll try something on that basis.

**Comment by jaroszmm** [comment]
MFD autopilot I believe has this feature that ailerons move as countdown ;) Not everybody has a beeper but everybody has ailerons ;)
https://youtu.be/0Qeno4u7eUc?t=70 something like this

**Comment by avsaase** [comment]
I think that shake to activate is also quite cool, but it may not be very practical with planes like the big drak.

**Comment by b14ckyy** [comment]
> Is there a way for the motor to do the beeping? That would kind of separate it from the other launch beeps, and also give feedback to people without a beeper.

would only work with d-shot but most of us still use plane ESCs with standard protocol. 
This Aileron shake is actually a really cool feature! But the tail shake to engage throttle would be hard to do on a delta wing. 

I think this is maybe worth a look for 3.1 with a full autolaunch overhaul.

**Comment by jaroszmm** [comment]
[https://youtu.be/4UO6Z2PU2NQ](url)
First tests. Seems to work just fine.

**Comment by b14ckyy** [comment]
This should really be pushed into 3.0 before release! Love it.

**Comment by avsaase** [comment]
@jaroszmm something is wrong with your link.

**Comment by jaroszmm** [comment]
One idea more... about the countown with the ailerons... 
what if the elevons or ailerons would count down by moving full travel at first and then when getting closer to zero the travel would be less and less visible?

**Comment by mf0o** [comment]
while jaroszmm and I are testing this on the 2.6.1 codeline, the addition to src/main/cms/cms_menu_navigation.c was really helpful:
`+    OSD_SETTING_ENTRY("IDLE DELAY", SETTING_NAV_FW_LAUNCH_IDLE_MOTOR_DELAY),`

Regarding the "countdown", maybe a mario-kart-countdown would be nice too: https://www.youtube.com/watch?v=wMQzC9dNY1I

**Pull request merged**
