### PR TITLE
More F7 fixes, PPM/PWM

### PR DESCRIPTION
**Pull request by sambas**
AnyFCF7 channel order and io mode fix.
PWM/PPM fix, note init order has changed for all, tested F4 and F7. F1/F3 testing needed
ADC and I2C init fixes

### CODE REVIEW

**Comment by sambas** [comment]
F1 works

**Comment by digitalentity** [comment]
Tested on F1 - confirmed working

**Comment by sambas** [comment]
I don't know if we get anyone to check F3, but this same change has been in BF couple months now and I have not seen any issues raised

**Comment by digitalentity** [comment]
I think it's safe to merge. If there will be issues - we'll fix them on the go.

**Pull request merged**
