### PR TITLE
Enable flying wing for RCEXPLORERF3

### PR DESCRIPTION
**Pull request by lkaino**
Enables servo outputs on RCEXPLORERF3 board.

For flying wing:
PWM2 is motor output
PWM1&3 are servo outputs.

### CODE REVIEW

**Comment by digitalentity** [comment]
@lkaino can you please also update documentation?

**Comment by lkaino** [comment]
Will do.

**Comment by lkaino** [comment]
Thanks for merging.

I went through the documentation but couldn't find/don't remember adding a documentation for this board. Betaflight has documentation for this board.

@digitalentity: Which documentation were you referring to?

**Comment by digitalentity** [comment]
A file with board description, pinouts and functionality in `docs`.

**Comment by oleost** [comment]
@martinbudden Was this on purpose merged to master?

**Comment by martinbudden** [comment]
@oleost , no that was accidental. I didn't check the PR carefully enough. Shall we leave it, since it is target specific and won't affect most people, or shall we revert?

**Pull request merged**
