### PR TITLE
[RFC] Migrate to 6bit settings name table

### PR DESCRIPTION
**Pull request by stronnag**
## Overview

#7254 exposed both the limitations (and benefits) of the extant 5 bit settings names character set (as well as the developer confusion ensuing from the concept of a limited character set).

This **RFC** demonstrates a 6 bit setttings name character set, as follows:
* Fixed character set, providing the (lower case) ISO C naming set 
* NUL, 'a'-'z', '_', '0'-'9'
* Simplifies the encoding and decoding of settings names
* Permits the usage of 0 - 9 digits
* uses 38 of a possible 64 entries
* Increases flash usage by c. 500 bytes (alas)

## Example flash usage:

Extant 5 bit character set [NUL, a-z, _, 1,2,3]
```
[729/732] Linking C executable bin/WINGFC.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      465836 B       896 KB     50.77%
    FLASH_CONFIG:          0 GB       128 KB      0.00%
             RAM:       54836 B       128 KB     41.84%
             CCM:       13140 B        64 KB     20.05%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
       MEMORY_B1:          0 GB         0 GB
[731/732] Linking C executable bin/MATEKF405.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      507324 B       896 KB     55.29%
    FLASH_CONFIG:          0 GB       128 KB      0.00%
             RAM:       78984 B       128 KB     60.26%
             CCM:       17252 B        64 KB     26.32%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
       MEMORY_B1:          0 GB         0 GB
``` 
Example 6bit character set [NUL, a-z, _, 0 - 9]
```
57/358] Linking C executable bin/WINGFC.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      466308 B       896 KB     50.82%
    FLASH_CONFIG:          0 GB       128 KB      0.00%
             RAM:       54836 B       128 KB     41.84%
             CCM:       13140 B        64 KB     20.05%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
       MEMORY_B1:          0 GB         0 GB
[358/358] cd /home/jrh/Projects/fc/ina...ts/fc/inav/build/inav_3.1.0_WINGFC.hex
[jrh@eeyore]$ ninja MATEKF405
[373/374] Linking C executable bin/MATEKF405.elf
Memory region         Used Size  Region Size  %age Used
           FLASH:      507812 B       896 KB     55.35%
    FLASH_CONFIG:          0 GB       128 KB      0.00%
             RAM:       78984 B       128 KB     60.26%
             CCM:       17252 B        64 KB     26.32%
     BACKUP_SRAM:          0 GB         4 KB      0.00%
       MEMORY_B1:          0 GB         0 GB
```

More user-friendly settiings names costs c. 500 bytes. Comments solicited.

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
I think it's cool, because the F4, F7 and H7 have a lot of memory, and iNav at the moment doesn't consume much.

**Comment by stronnag** [comment]
> I think it's cool, because the F4, F7 and H7 have a lot of memory, and iNav at the moment doesn't consume much.

F411 and F722 are already flash constrained, and already have flash issues with a modern compiler (which is why I never did a PR for gcc 10.20 migration).

**Comment by bkleiner** [comment]
this is a tough one.
trading in **half a kilobyte** for nicer names, a lot people will never even use directly, seems like a hefty price to pay. 
of course i understand the appeal, especially with chip-names the numbers, 0-9 would be highly useful.
 are the any other characters that might be worthwhile to add? if i understand correctly with the change there would be some space left in the table. pulling more usage out of those 500byte in the future might "tip the scale" so to speak.

**Comment by DzikuVx** [comment]
@stronnag what do we do with this one?

**Comment by stronnag** [comment]
Close it. The impetus to give up 500b has passed I think. We know the rules and can live with them.

**Comment by DzikuVx** [comment]
Thanks

**Pull request closed without merging**
