### PR TITLE
Add support for VL53L0X rangefinder

### PR DESCRIPTION
**Pull request by digitalentity**
- Add support for VL53L0X rangefinder from ST
- Allow rangefinder driver to report NO_NEW_DATA value
- Add i2cWriteBuffer API to F1,F3,F4 driver
- Enable VL53L0X on REVO target

### CODE REVIEW

**Comment by DzikuVx** [comment]
I will hook it up and record some data over the weekend

**Comment by DzikuVx** [comment]
Flashed Omnibus F4 Pro and connected VL53L0X. Sensor detected without problem, records distance. Those 2m in extended range are rather very irratic even from white ceiling in darkish room. Flight data during the weekend

**Comment by DzikuVx** [comment]
[LOG00005.TXT](https://github.com/iNavFlight/inav/files/1201355/LOG00005.TXT)

@digitalentity bad news. VL53L0X is more less the same level as HC-SR04. Solid readouts up to 1.2m. Above that it starts to goes crazy. And it was rather late evening, no direct sunlight. But works, and I thing can be merged

**Comment by digitalentity** [comment]
@DzikuVx yes, this is what I get in my tests as well. Totally incorrect and random measurements above certain height. Might be settings, but I'm not sure yet.

**Comment by digitalentity** [comment]
Merged. #1973 opened to track the noise issue

**Pull request merged**
