### PR TITLE
New IO for UARTs, LED_STRIP and BIND_PIN - not ready to merge

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
Looks like I've added missing call to `EXTIInit()` in #426 as well. Will this present a problem when merging?

**Comment by martinbudden** [comment]
No problem, I'll do a rebase.

**Comment by digitalentity** [comment]
SPRACINGF3:
- UART - check
- LED_STRIP - check

**Comment by digitalentity** [comment]
CC3D:
- UART - check
- LED_STRIP - check

**Comment by martinbudden** [comment]
@digitalentity , I've now done some testing of this. If your testing is also successful, I think this can be merged.

**Comment by digitalentity** [comment]
@martinbudden I didn't test on FuryF3 and Evo yet, but I believe it's safe to merge - we have F1 and F3 covered and rest of targets share the code.

**Comment by martinbudden** [comment]
Yes, that sounds fine. Go ahead and merge.

Now onto SPI, the last one.

**Pull request merged**
