### PR TITLE
MAVLink protocol updates (initial bi-directional protocol; waypoint support)

### PR DESCRIPTION
**Pull request by digitalentity**
Update MAVLink library
Initial cut on bi-directional MAVLink
Mission upload

### CODE REVIEW

**Comment by Linjieqiang** [comment]
Haha,Maybe I can use Tower APP to upload mission to inav.

**Comment by digitalentity** [comment]
No, MAVLink is definitely not the best protocol. Very clumsy.

**Comment by digitalentity** [comment]
I think we'll merge this soon - once I get basic mission upload/download working.

**Comment by digitalentity** [comment]
Load/store mission works with QGroundControl for Win32. Didn't test interoperability with MSP GCS yet.

**Comment by digitalentity** [comment]
Interoperability between EzGUI and QCG - check.

**Comment by pilotnbr1** [comment]
Any progress on full bi-directional mavlink?

**Comment by digitalentity** [comment]
Uploading/downloading waypoints via MAVLink works. If you lack other features - please open a new feature request.

**Comment by Schakus** [comment]
Is it implemented in the current version? I want to use it via FPORT Telemetry.

**Comment by Schakus** [comment]
Is it implemented in the current version? I want to use it via FPORT Telemetry.

**Pull request merged**
