### PR TITLE
YuPiF4 target added

### PR DESCRIPTION
**Pull request by Faduf**
Only target files to add the YuPiF4 target to the Inav project.

### CODE REVIEW

**Review by digitalentity — CHANGES_REQUESTED** [review]
Please add a target description file - what's the target, where one can add it etc.

**Comment by Faduf** [comment]
Should I add this description file in the Doc/ folder with an .md file or with a page in the Wiki?

**Comment by digitalentity** [comment]
@Faduf 
Add a README.md to the target directory. See https://github.com/iNavFlight/inav/tree/master/src/main/target/AIRHEROF3 for an example.

**Comment by digitalentity** [comment]
doc/TARGET_NAME.md will also be cool!

**Comment by DzikuVx** [comment]
I think doc/TARGET_NAME.md would be cooler

pt., 4.11.2016 o 09:26 użytkownik Konstantin Sharlaimov <
notifications@github.com> napisał:

**Review by digitalentity — APPROVED** [review]

**Comment by digitalentity** [comment]
Ok, looks like this doesn't touch anything but target-specific files. Merging.

**Comment by DzikuVx** [comment]
@digitalentity _master_ ?

**Comment by digitalentity** [comment]
Crap!!!!

**Comment by digitalentity** [comment]
Anyway, this shouldn't cause any ill effects on master, I'll just merge master back to dev.

Note to self: pay more attention to base branch of the PR.

**Pull request merged**
