### PR TITLE
Implement JUMP Waypoint type

### PR DESCRIPTION
**Pull request by giacomo892**
Thanks @stronnag for testing and help!

### CODE REVIEW

**Review by stronnag — APPROVED** [review]

**Comment by FabianSchwartau** [comment]
Hey, already mentioned it in https://github.com/iNavFlight/inav/pull/5398, this function does not work for me. He gets stuck in NAV_STATE_WAYPOINT_PRE_ACTION, which is processed once for the jump, but then never again to process the next waypoint.

**Comment by stronnag** [comment]
Indeed, there's a error in merging the tested code into development. PR to follow.

**Comment by stronnag** [comment]
See #5460
I'll refrain from repeating my views on relying on side effects for required functionality .... QED

**Comment by FabianSchwartau** [comment]
That seems reasonable. Do you have any idea why my drone was not responsive after that? I simulated this on my bench with fake GPS, same problem, but turning off nav mode gave me back full control.

**Comment by stronnag** [comment]
No idea, this was the original omission in the initial implementation. It was fixed and tested; then the working code failed to be fully pasted into the final merge, somehow.

When I tested the original code (which had the same omission), my craft just loitered, stuck in PRE_ACTION until I took back control by deselecting WP mode.

**Comment by FabianSchwartau** [comment]
Strange. I tested the patch in my simulation and it works. I will try it outdoors now, wish me luck.

**Comment by stronnag** [comment]
Just make sure you have the properly fixed patch ... the first one also had a paste error .... :(

**Comment by FabianSchwartau** [comment]
Ohh... yeah, I applied it manually and got the right line ;)

**Comment by stronnag** [comment]
> Ohh... yeah, I applied it manually and got the right line ;)

 I'll take that as a positive review then. Have a good flight(s).

**Comment by FabianSchwartau** [comment]
I am already back and yes, it worked as expected, going to commit my stuff now.

**Pull request merged**
