### PR TITLE
F4 Target support

### PR DESCRIPTION
**Pull request by sambas**
Pushed the stuff I have been using for couple years now. This will most likely break F1 and F3 functionality but we can discuss and fix it here now. At the moment biggest issue is F1 and F3 i2c drivers as I had to add support for internal and external busses for F4. I have been using all the targets (REVO, ANYFC, COLIBRI) added here with great success.

Changes:
I2C driver
UART DMA
SPI clockspeed
Timer support
VCP
...

### CODE REVIEW

**Comment by digitalentity** [comment]
F4 work starged, thanks!

**Comment by martinbudden** [comment]
@digitalentity , I'd really prefer to avoid a big commit like this. I'm working on staging in the F4 support. In particular I'm making some effort not to divert from betaflight too much, so that it will be possible to pull targets over from betaflight quite easily.

**Comment by digitalentity** [comment]
@martinbudden I like to do baby steps as well. However this PR is worth looking into - @sambas did a great job making F4 happen - if we can re-use the ideas or code it'll be great.

**Comment by martinbudden** [comment]
@digitalentity , yes, I'll certainly be looking at the PR in view of re-using code and idea. I just didn't want one big PR. And certainly @sambas stuff is worth looking at - as he did the original F4 port.

**Pull request closed without merging**
