### PR TITLE
Improve stats: reformat + add total energy and average efficiency

### PR DESCRIPTION
**Pull request by shellixyz**
Before:
improve_stats_before

After:
improve_stats_after

### CODE REVIEW

**Comment by krzysztofmatula** [comment]
I was thinking how to make this screen to stay longer.
It's hard to read the stats, unless recorded currently...

**Comment by shellixyz** [comment]
I agree it stays on screen only for 4 seconds. Maybe we can increase that to 10 seconds if stats are enabled ?

**Comment by krzysztofmatula** [comment]
For me it pops up for 2s rahter than 4...
https://drive.google.com/open?id=1pu89cG0Sr2_SETsvivl2OvgvzHhoba9X

**Comment by shellixyz** [comment]
You are right it shows up for less than 4 seconds. I did some digging to see what is going on but the only reason I see for the stats to be displayed less than 4 is that they are displayed right after the display initialization. So the screen needs some time to sync with the video signal / initialize / detect the format.

We just need to keep this in mind and not only put a delay for the exact time but a little more. I measured about 1.5s between the set time and the real time the stats are displayed on my screen. I propose to make the delay 12 seconds if the stats are enabled and 6 seconds if not. That would make the initialization screen be displayed for about 10 and 4 real seconds respectively.

I don't think increasing the delay is a big deal anyway. Nobody expects to plug a battery in and be in the air in less than 10 seconds. 

EDIT: I changed the delays to integers.

**Comment by Dronek** [comment]
Just a hint: in mwosd stats are shown without time limitation. The stats screen can be disabled by the pilot by moving throttle up while disarmed or by arming. Then it returns to regular OSD view.

**Comment by shellixyz** [comment]
@Dronek Yeah the timeout doesn't seem necessary but I don't think it is an issue. 60 seconds is plenty but we could remove it. I don't have a strong opinion on this.

**Comment by shellixyz** [comment]
Ready to merge

**Comment by digitalentity** [comment]
Thanks!

**Pull request merged**
