### PR TITLE
Add Azimuth OSD element

### PR DESCRIPTION
**Pull request by danarrib**
Add a nice Azimuth element to the OSD. This element allows the pilot to know if the aircraft is on a pre-defined radial in relation to the home point. It makes easier to keep the aircraft in the correct path in front of a high gain directional antenna.

photo_2020-07-05_14-20-50

photo_2020-07-03_00-04-21

Solves #2412

Testers are welcome. I don't know when I'll be able to do field testing.

To enable this element:

`osd_layout 0 108 12 6 V`

12 is the column (from left to right) and 6 is the row (from top to bottom)

Font on the OSD chip needs to be updated. The new "AZI" symbol is the symbol number 141. Updated font files are on the corresponding Configurator PR: https://github.com/iNavFlight/inav-configurator/pull/1032

### CODE REVIEW

**Comment by Dronek** [comment]
Could you add the angle of elevation as well please?
Bildschirmfoto 2020-07-03 um 15 16 11

**Comment by danarrib** [comment]
> Could you add the angle of elevation as well please?

It's a good idea. I can try to do it on another PR.

**Comment by danarrib** [comment]
I made a live test. It works as it should.

https://www.youtube.com/watch?v=a7gtvlaGCvM

image

**Comment by OptimusTi** [comment]
This is cool.

**Pull request merged**
