### PR TITLE
Cleanup not used ESC protocols

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by avsaase** [comment]
````
Memory region         Used Size  Region Size  %age Used
           FLASH:         620 B        16 KB      3.78%
    FLASH_CONFIG:          0 GB        16 KB      0.00%
          FLASH1:      491523 B       480 KB    100.00%
             RAM:       88016 B       128 KB     67.15%
       MEMORY_B1:          0 GB         0 GB/home/runner/work/inav/inav/tools/gcc-arm-none-eabi-9-2020-q2-update/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: bin/FLYWOOF411.elf section `.data' will not fit in region `FLASH1'
````
😕

**Comment by breadoven** [comment]
Flywoo F411 ...hmmm. Had to undefine some stuff to get it to work on my custom build but now the current master has also become too bloated.

**Comment by avsaase** [comment]
Apparently, MATEKF411SE still fits so not all F411 are created equally?

**Comment by DzikuVx** [comment]
@breadoven I'm running a cleanup ATM of features.
@avsaase nope, they are not

**Pull request merged**
