### PR TITLE
[GPS] Add SEA and MOWER dynamic models.

### PR DESCRIPTION
**Pull request by mmosca**
Potentially better models for hovers.

Not a lot of documentation about the different dynamic models.

### CODE REVIEW

**Comment by sensei-hacker** [comment]
Mower?

download (19)

**Comment by mmosca** [comment]
You get the idea, but this is a thing: https://www.ardumower.de/en/home.html

**Comment by Jetrell** [comment]
@mmosca The idea seems good https://www.u-blox.com/en/high-precision-openmower

As far as optimally using the benefits of the dynamic model types, under all situations.
It maybe an idea to add `gps_dyn_model` to the programming tab. So users can base a dynamic model selection, on a GPS speed setpoint.
e.g. use `air_2G` for speeds greater than 15km/h. And switch to mower or sea when the copter is slowing to a hover.

**Comment by mmosca** [comment]
Changing the dyn model on the fly may be trickier than it looks.

Currently we only setup the gps on start up.

The ublox command itself is simple to implement, and changing modes does not require a gps reboot. I haven't played with adding new programming framework features, but if it can trigger the action when the state changes, it should simplify things.

**Pull request merged**
