### PR TITLE
Inav blackbox tidy2

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden is this ready for merge?

**Comment by martinbudden** [comment]
Haven't had a chance to test it out. But if you test it and it's fine, then it can be merged.

**Comment by stronnag** [comment]
I'm unconvinced about the veracity of these changes (I mean the recent logging changes in general, not explicity this PR).

Normally, I would expect BB to provide higher point density than recorded LTM telemetry (due to (a) the data logging rates and (b) the losses that will be incurred over a radio data link). In the following examples, the BB log shows gaps that are not in the recorded telemetry, for example c. 13 seconds [flight time]  (gap in the cyan 'manual' track) and later the gaps (white track) at WP1, WP3, WP4 and the possibly bogus 'sensor failure' (none of these artefacts appear in the LTM log).

Video replay of BBL log:  https://vimeo.com/222887195
Video replay of LTM log:  https://vimeo.com/222886552

Note: There is obviously the possibility of a fault in the replay tool (or the FC hw is marginal), however the momentary sensor health value of 122 looks very strange:
````
$ ./Projects/mwptools.as/bbox-replay/decode_hw.rb 122
gyro	unavailable
acc	unavailable
mag	unhealthy
baro	OK
````
Log file: http://seyrsnys.myzen.co.uk/inav-1752/LOG00006.TXT

**Comment by stronnag** [comment]
I've found this log corruption from multiple vehicles. Created new issue #1821

**Comment by martinbudden** [comment]
@stronnag , I've inspected the above logfile using the blackbox view and there does not appear to be corruption. Can you see corruption using the blackbox viewer or just using the decoder/replay tool?

This PR is mainly cleanup. The only significant change to the output is that the debug values are only output if `debug_mode` is set. That is, if `debug_mode` is `none` then the debug header line is not written to the blackbox log and neither are the debug field values.

Can you set `debug_mode` (it doesn't matter which debug mode you use) and retry and see if you still get corruption?

Also, does the replay tool check the fields declared in the blackbox header?

**Comment by stronnag** [comment]
Martin,

I see the ~~corruption~~ strange output using the iNav BB viewer (latest pulled from git today), as well as the canonical `blackbox_decode` (which is necessary for testing navigation modes to get geospatial data).

ps. By corruption I meant 'unexpected output', not 'the log is irretrievably broken', apologies if this imprecise description caused misunderstanding.

Here's a some iNav BB viewer screenshots (only the first looks normal):

Today, using newly built 69a759d2 (last commit prior to the tidy2 merge)
screenshot-20170624163922-1921x1054

2017-06-21, using 4f79a3bdfc0cf49e6b8a8d884f6be52d3b74a174 (the tidy2 merge).
screenshot-20170624163815-1921x1054

And the log posted above (again 4f79a3bd):
image

The (mwp / geo view) replay tool just uses `blackbox_decode` and interprets the piped CSV (for simplicity / not reinventing the wheel). 

I note that `blackbox_decode`'s `src/blackbox_fielddefs.h` does not have `FLIGHT_LOG_FIELD_CONDITION_DEBUG` in its list of conditions, but adding it does not appear to help.

I can try the `debug_mode` test tomorrow.

**Comment by digitalentity** [comment]
@martinbudden @stronnag looks like I-frames are not recorded correctly. Will try to look into the code.

**Comment by martinbudden** [comment]
@stronnag , PR https://github.com/iNavFlight/inav/pull/1825 should fix this. Can you test?

Problem was the I changed logging of `debug` in I-Frame to be conditional, but forgot to do it for the P-Frame, so data in P-Frame after `debug` was incorrect.

**Comment by digitalentity** [comment]
@martinbudden this explains why I didn't notice any issues with this PR - I was testing with debug logging enabled.

**Comment by martinbudden** [comment]
Indeed.

**Comment by stronnag** [comment]
I will fly it later today.

**Pull request merged**
