### PR TITLE
WP Mission Landing Elevation Setting

### PR DESCRIPTION
**Pull request by breadoven**
WP mission Landing currently assumes the landing elevation is the same as takeoff elevation which may not be the case for remote landings. If the remote landing elevation is different then landing vertical velocity scaling will be incorrect. This is more of an issue if the landing elevation is higher than takeoff elevation because the ground will appear sooner than INAV is expecting.

This PR provides the ability to define a different landing elevation to the default takeoff home elevation by setting Landing WP P1 as the landing elevation. Uses an elevation in cm which requires P1 to be changed to int32_t. Could maintain the current int16_t if the elevation was set in meters instead. This would be accurate enough for landing elevation but inconsistent with the altitude setting in cm leading to potential confusion with the settings.

### CODE REVIEW

**Comment by stronnag** [comment]
Changing a legacy API is not considered acceptable. 
Using metres would be fine.

**Comment by breadoven** [comment]
> Changing a legacy API is not considered acceptable.
> Using metres would be fine.

I'll change it to use meters. If it's set by a mission planner then it can handle the units as required, if set by CLI the user will need to be aware. That will be the 1 user a year who uses remote landings ...

**Comment by stronnag** [comment]
Also, P1 as speed is valid for a LAND WP, so P2 for elevation.

**Comment by breadoven** [comment]
I guess I should have realised that given how works. https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages could to with updating to include P1 speed for Landing.

**Comment by stronnag** [comment]
> I guess I should have realised that given how works. https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages could to with updating to include P1 speed for Landing.

Thanks. I'll fix that when the landing elevation PR is done.

**Comment by breadoven** [comment]
https://github.com/iNavFlight/inav/pull/6662 related change made so should be good to merge.

Thanks

**Pull request merged**
