### PR TITLE
Add JHE F7 DUAL target

### PR DESCRIPTION
**Pull request by xD90o1**
After extensive testing from issue #5002  and fixing on the user modes, the files for the JHE F7 DUAL target are ready for merging.

### CODE REVIEW

**Comment by aknack** [comment]
known bug: only MPU6000 works on the *deluxe* - but WTFC.
since the FC defaults to it.
i'd suggest merging anyhow and fixing that somewhat later.

**Comment by michaelj0hn** [comment]
NAV_ALTHOLD does not work for me. Caused the copter to do a violent flip & crashed.

**Comment by aknack** [comment]
NAV_ALTHOLD works in combination with NAV_POSHOLD for me.
see https://www.youtube.com/watch?v=CNavxiyPzrM

**Comment by michaelj0hn** [comment]
> NAV_ALTHOLD works in combination with NAV_POSHOLD for me.

Standalone (without NAV_POSHOLD), just added to ANGL it was unsuccessful for me. As it should have only affected the vertical position, it should not have flipped in any way.

Edit: unfortunately do not see any flight mode states in your video.

**Comment by aknack** [comment]
> Standalone (without NAV_POSHOLD), just added to ANGL it was unsuccessful fo

works for me: https://www.youtube.com/watch?v=LSbgLXoPL9Q&feature=youtu.be same dump as above, just added mode combination and osd settings

**Comment by xD90o1** [comment]
> Standalone (without NAV_POSHOLD), just added to ANGL it was unsuccessful for me. As it should have only affected the vertical position, it should not have flipped in any way.

Can you show me an OSD and on the bench vid of your craft? I'd like to see as to why some JH7Ds work, some don't. Also please tell me if you're using the acro or deluxe

**Comment by aknack** [comment]
> Can you show me an OSD and on the bench vid of your craft? I'd like to see as to why some JH7Ds work, some don't. Also please tell me if you're using the acro or deluxe

please start reading here: https://github.com/iNavFlight/inav/issues/5002

**Comment by michaelj0hn** [comment]
> works for me: https://www.youtube.com/watch?v=LSbgLXoPL9Q&feature=youtu.be same dump as above, just added mode combination and osd settings

It should actually say HOLD as 2d position hold, you just seem to switch between ANGL and ACRO only. With NAV_ALTHOLD you would get a the altitude hold as a system message. Also interesting that it did not obtain a home position with 9 sats fix.

**Comment by aknack** [comment]
i armed with 0 satelites via extra_arming_switch.

i can confirm, that NAV_ALTHOLD + ANGLE works for me on the *deluxe* version.
0:12: the moment in the video where i switch to this mode.

>  With NAV_ALTHOLD you would get a the altitude hold as a system message. 

i received that message via lua from lovely amber voice pack. i don't care about mode combinations shown in osd.

**Comment by michaelj0hn** [comment]
> 
> 
> > Can you show me an OSD and on the bench vid of your craft? I'd like to see as to why some JH7Ds work, some don't. Also please tell me if you're using the acro or deluxe
> 
> please start reading here: #5002

Yes, I already posted there a few weeks back that althold was not working for me. My config is posted there too. I am using the delux version.

**Comment by michaelj0hn** [comment]
Right now I can offer the screenshot from the very second I engaged nav_althold. I can just see that auto throttle went up but flipped the quad instantly. It does (did) fly OK within ANGL or ACRO.
image

**Comment by michaelj0hn** [comment]
> i can confirm, that NAV_ALTHOLD + ANGLE works for me on the _deluxe_ version.
> 0:12: the moment in the video where i switch to this mode.

Maybe this has something to do with this particular firmware, but when you normally switch into NAV_POSHOLD it will (should) change from ANGL/ACRO to HOLD in the OSD.
This is what makes me a bit unsure now looking at the video it is changing between ANGL and ACRO. 

Have you been able to validate RTH?

**Comment by aknack** [comment]
> Have you been able to validate RTH?

yeah, i can the f**k confirm rth works. look: 
https://youtu.be/azYxNBMEkf8

**Comment by lavachemist** [comment]
> > Have you been able to validate RTH?
> 
> yeah, i can the f**k confirm rth works. look:
> https://youtu.be/azYxNBMEkf8

Can you point me in the direction of the hex you're using in this video?

**Comment by xD90o1** [comment]
Check issue 5002 I posted the hex there but there might be changes to a few
things going to a more later versions of inav

**Comment by ivanplkolev** [comment]
The switch for 8V (VTX) - USER2 does not work for me, how do you solve that ?

**Pull request closed without merging**
