### PR TITLE
LED enabled on Omnibus F4 (and Pro) targets

### PR DESCRIPTION
**Pull request by DzikuVx**
as @flounderscore tested in #957 , LED now works on Omnibus F4
So, enabled in target

### CODE REVIEW

**Comment by amelluk** [comment]
I understood that this issue had been fixed on the Pro.

**Comment by digitalentity** [comment]
@DzikuVx what's the nature of the conflict? What pin is dedicated connector?

**Comment by amelluk** [comment]
On F4 Pro+V2, J1 is apparently now connected to PB6 - this appears to be TIM4_CH1
I tried to test it tonight, but no 3 pin JSTs left - have ordered some.
@jflyper may know more

**Comment by DzikuVx** [comment]
I do not remember correctly atm. The pin is PD1 or something. Too much time passed

**Comment by jflyper** [comment]
Yes. It turned out that with newer revisions (and boards), LED pin/pad have a valid timer pin. I will followup on this soon.

BF will probably switch to the new timer at some point, so that "LED" labelled pin does work and free up the PWM pin (, and apologize those who have to re-solder 😢 )

**Comment by amelluk** [comment]
Did some testing with multimeter today, seems my (recent) board has the problem, led_strip is connected to PH1, so I won't be able to test. Suggest we go ahead and merge this and revisit it later when there's more boards out there.

**Comment by flounderscore** [comment]
I'd be happy to try something on my omnibus pro, if you tell me what/how.

**Comment by jflyper** [comment]
On variants of OMNIBUSF4 and F4SD I have here, the LED pin is connected to PB6.

There is a test binary on [Exotic OMNIBUS](https://www.rcgroups.com/forums/showthread.php?2792346-Exotic-OMNIBUS) blog page.
Look for "[BF 3.1.1] OMNIBUS F4 V2 / F4 Pro with LED strip on J1".

I'm now trying to find out which revisions of each variant have this arrangement.

**Pull request merged**
