### PR TITLE
Landing direction

### PR DESCRIPTION
**Pull request by hali9**
This is second part of https://github.com/iNavFlight/inav/pull/4961
For airplane it defined direction to land with aproach. https://github.com/iNavFlight/inav/issues/1814 https://github.com/iNavFlight/inav/issues/3670 https://github.com/iNavFlight/inav/issues/4070
For multirotors it defined head direction when landing.
When 0 (default) it is disabled and work as before.

### CODE REVIEW

**Comment by mistyk** [comment]
Is this possible to add a parameter to set landing direction when  you launch wing, that case land direction should be the same as launch direction ?

**Comment by hali9** [comment]
@mistyk The default value 0 have this behavior, but this is very inaccurate. A 10 degree deviation at 150 meters approach is 26 meters drift.

> that case land direction should be the same as launch direction ?

Yes, if take off under the wind and wind direction not change, will land under the wind.

**Comment by mujtabachang** [comment]
Pretty useful in windy areas for FW pilots

**Comment by DzikuVx** [comment]
replaced by #9713

**Pull request closed without merging**
