### PR TITLE
Updated Crossfire telemetry FM strings for 3.0

### PR DESCRIPTION
**Pull request by MrD-RC**
Changed the old 3CRS to CRUZ and CRS to CRSH, to reflect the mode changes.

### CODE REVIEW

**Comment by OptimusTi** [comment]
Wool this change break functionality with LUATelemetry?

**Comment by MrD-RC** [comment]
@OptimusTi I did realise that after posting. But figured to leave it up, and maybe I’ll look at the LUA.

**Comment by wx4cb** [comment]
> @OptimusTi I did realise that after posting. But figured to leave it up, and maybe I’ll look at the LUA.

you theoretically wouldn't need to change anything as i think it goes by the modes numeric value.

**Comment by OptimusTi** [comment]
> OTTOMH

The lua script (and possibly OpenTX) expects a string from crsf telemetry. Not a number. right?

**Comment by wx4cb** [comment]
> > OTTOMH
> 
> The lua script (and possibly OpenTX) expects a string from crsf telemetry. Not a number. right?

i am not sure. not by my pc to double check. but it might just be in modes.lua that you need to deal with.

**Comment by MrD-RC** [comment]
I’ve had a quick look, and it looks like https://github.com/iNavFlight/OpenTX-Telemetry-Widget/blob/master/src/SCRIPTS/TELEMETRY/iNav/crsf.lua would need to be changed, but I believe that would be all. 

Of course, the LUA script it’s self could be updated to use the terms Course Hold and Cruise.

**Comment by wx4cb** [comment]
@MrD-RC  That would be correct, but i would assume that would be for crossfire only and not all radios. there was an issue before where one sensor was called something different in crossfire than other radios but i could also be thinking about something else too :D

**Comment by OptimusTi** [comment]
Check OpenTX too. :)

**Comment by MrD-RC** [comment]
I had a look in EdgeTX and could only see FLIGHT_MODE_ID. I'm sure it just displays the string it receives.

**Comment by MrD-RC** [comment]
I've updated the LUA. It will still work with older versions too. https://github.com/iNavFlight/OpenTX-Telemetry-Widget/pull/4

**Comment by MrD-RC** [comment]
... and here https://github.com/teckel12/LuaTelemetry/pull/467

**Pull request merged**
