### PR TITLE
Experimental DJI FPV support

### PR DESCRIPTION
**Pull request by DzikuVx**
Code by @idavidstory https://github.com/idavidstory/inav/tree/djiGoggles from

### CODE REVIEW

**Comment by digitalentity** [comment]
Let's not get this merged. Full support is coming :)

**Comment by JoshWelsh** [comment]
> Let's not get this merged. Full support is coming :)

Let’s drop the smiley faces and better explain what you mean by “full support is coming”. Another option is get this change in now so people can fly it now, and enhance to full support later?

**Comment by Jetrell** [comment]
> 
> 

> 
> Let’s drop the smiley faces and better explain what you mean by “full support is coming”. Another option is get this change in now so people can fly it now, and enhance to full support later?

@digitalentity left a comment here - https://github.com/iNavFlight/inav/issues/5247  

`Hardware on the way. I'm taking ownership of this feature request. Code for full support for OSD and PID configuration is already in the works.`

**Comment by digitalentity** [comment]
@JoshWelsh the best thing about open source is that you are free to do whatever you want with the code. If you are eager to start flying - get a fork from @idavidstory (https://github.com/idavidstory/inav/tree/djiGoggles) and fly.

For the mainstream INAV I'd rather not introduce more complexity into already complicated and convoluted 3500 lines long MSP code.

**Comment by digitalentity** [comment]
PR for more structured and readable support is in place. Closing this one.

**Pull request closed without merging**
