### PR TITLE
Speed control and RTH/FAILSAFE improvements

### PR DESCRIPTION
**Pull request by digitalentity**
- Split auto/manual speed and climb rate limitation
- Remove 2D RTH
- RTH sensor loss refactoring

### CODE REVIEW

**Comment by oleost** [comment]
What does remove RTH 2d mean?

**Comment by digitalentity** [comment]
Originally it was possible to activate RTH mode if you don't have an altitude sensor - it will just fly home at current throttle without maintaining altitude. I'm taking this away now - it's potentially unsafe and actually useless feature.

**Comment by sppnk** [comment]
By 'not having altitude sensor' is included GPS altitude?

**Comment by digitalentity** [comment]
@sppnk "not having altitude sensor" is machine-specific. For quads it's not having barometer sensor. For planes it's not having barometer and not having a GPS fix.

**Comment by sppnk** [comment]
ok, good to know.

**Comment by oleost** [comment]
@digitalentity Hmm, maybe the current implmentation was useless.

But even a multirotor would probably get home nicely without barometer and only relying on GPS altitude?

**Comment by digitalentity** [comment]
@oleost it might. But I feel that having a barometer is benificial for an airplane as well.

**Comment by oleost** [comment]
@digitalentity Yes.

**Comment by Linjieqiang** [comment]
Looks great.The code will be cleaner than before.

**Comment by digitalentity** [comment]
It would be good if somebody can test this code - I'm sick at the moment and unable to fly my birds.

**Comment by oleost** [comment]
#1475

**Comment by Linjieqiang** [comment]
Last day I tested it with my wingwing.It looks great but I wonder why my pitch channel didn't work when changing althold mode?Maybe I will test this branch again today.

**Comment by Linjieqiang** [comment]
Nice today..It didn't have any problem about this operation.

**Comment by giacomo892** [comment]
Seems like in 1.7 there the "bug" still here @digitalentity  despite it has being fixed as this PR and https://github.com/iNavFlight/inav/issues/798

[LOG00290.TXT](https://github.com/iNavFlight/inav/files/999539/LOG00290.TXT)

Using:

set nav_auto_speed = 800
set nav_manual_speed = 1000

I get steady 8m/s in PH CRUISE instead of expected 10m/s as you can see from the logs.

I'm pretty sure I was full pitch when I was a 8m/s and there was no strong wing.

**Comment by digitalentity** [comment]
@giacomo892 I believe @DzikuVx tested it successfully.

**Comment by giacomo892** [comment]
@digitalentity you can check for more logs if you need in https://github.com/iNavFlight/inav/issues/1675

**Comment by DzikuVx** [comment]
@digitalentity No I did not

**Comment by digitalentity** [comment]
@giacomo892 in your log I see velocity target reaching 9m/s and actual velocity reaching 9m/s as well. Certainly not 8m/s. 

Are you sure you have `set nav_manual_speed = 1000` ?

**Comment by giacomo892** [comment]
@digitalentity Maybe it is rounded and there could be some wind. With MWP I mostly see it as 8m/s and some spikes to 9 as you say.

this is the diff I saved on file:

```
set nav_use_midthr_for_althold = ON
set nav_user_control_mode = CRUISE
set nav_auto_speed = 800
set nav_auto_climb_rate = 350
set nav_manual_speed = 1000
set nav_manual_climb_rate = 400
set nav_mc_hover_thr = 1510
```

Yes, the diff show it, but to be 1000% sure I'll check it again on friday.

**Comment by giacomo892** [comment]
I've added the diff if you pushed the thumb before the last edit @digitalentity  Sorry :)

**Comment by digitalentity** [comment]
@giacomo892 I've just found a bug that prevents manual control from reaching the `nav_manual_speed`. Speed controller itself is not limited, it's a bug that prevents us from requesting the `nav_manual_speed` value. With default settings it limits max setpoint to precisely 90% which gives 9m/s max speed at `nav_manual_speed = 1000`

**Comment by giacomo892** [comment]
It's nice when I can help spotting bugs. Thanks for your investigation and when you have time please visit https://github.com/iNavFlight/inav/issues/1675 ;)

**Pull request merged**
