### PR TITLE
For SmartPort telemetry send BOX state, not flight mode state

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by fiam** [comment]
@DzikuVx What's the reason for this one? Wouldn't you know the active BOX states by looking at the radio? Sending the real active mode seems more useful to me because you might have a BOX active but its flight mode might not be engaging for some reason. With this change, you can no longer see it in the telemetry.

**Comment by DzikuVx** [comment]
Our real modes are not real modes. More like BOX+Condition. I find it disturbing when looking at telemetry screen and not seeing what I setup by switches

**Comment by fiam** [comment]
I still don't get it. If you e.g. flip your RTH switch you can see in the telemetry if it engaged RTH mode or not. With this change you won't be able to see that, since the telemetry will send back exactly the boxes enabled from the transmitter. Wouldn't sending those values separately be more useful?

**Comment by digitalentity** [comment]
I agree with @fiam that sending back actual flight modes is more useful.
Boxes only indicate what **pilot wants the FC to do**, while flight mode flags will give information what FC is **actually doing**.

**Comment by fiam** [comment]
@DzikuVx Just to be clear, I see the appeal on receiving the boxes via telemetry. What I wouldn't like is losing the ability to receive the flight modes. Maybe you can implement it as a different telemetry value rather than overwriting the flight modes?

**Pull request closed without merging**
