### PR TITLE
gps time OSD overlay

### PR DESCRIPTION
**Pull request by Impulze75**
Hi!

In Inav there is only Hours /minutes available in OSD settings. For timestamping i would like to have option do display seconds also from GPS in the OSD overlay. 

Anyone able to fix this function?

### CODE REVIEW

**Comment by avsaase** [comment]
@Impulze75 is this a feature request or a pull request?

**Comment by Impulze75** [comment]
> @Impulze75 is this a feature request or a pull

Sorry for late reply, its a pull request.

**Comment by avsaase** [comment]
Please open a new PR to merge your proposed changes into `master` or `release_3.0.0`.

**Comment by Impulze75** [comment]
> Please open a new PR to merge your proposed changes into `master` or `release_3.0.0`.

I could need some assistance since i have no idea how this works :)  Sorry for that....

**Comment by Impulze75** [comment]
So...did something happend with this?

Regards, Mattias

**Comment by MrD-RC** [comment]
Yes, it's been merged 
https://github.com/iNavFlight/inav/pull/6993

**Comment by Impulze75** [comment]
Perfect👍

Skaffa Outlook för Android<https://aka.ms/ghei36>
________________________________

**Comment by Impulze75** [comment]
Updated firmware to 3.0.2 and configurator 3.0.2 , I still dont find any option to make seconds visible in the OSD. 

So, does this means its a configurator issue?

/Regards Mattias

**Comment by MrD-RC** [comment]
It’s not in 3.0, as was mentioned to you in PR.

**Comment by Impulze75** [comment]
> It’s not in 3.0, as was mentioned to you in PR.

Sorry, thats correct. 

/Mattias

**Pull request closed without merging**
