### PR TITLE
Prefer GPS heading on airplanes, fallback to MAG if available

### PR DESCRIPTION
**Pull request by digitalentity**
A follow up for #165.
IMU will fallback to MAG if GPS CoG is significatly different (>15 deg)  from estimated heading. 
If GPS is the only source of heading it will be used regardless.

### CODE REVIEW

**Comment by oleost** [comment]
Hi, is this ready to be tested?

I merged both FW improvements and master into the imu-fw-heading branch.

**Comment by digitalentity** [comment]
@oleost this is untested, but should be safe to try out!

**Comment by oleost** [comment]
OK.

Still unsure if I think this feature is a good idea.

When we are flying GPS enabled modes, when should we not trust the GPS heading?

I'm only thinking if gps posisition jumps backwards and shows big error. Maybe up the error acceptance to let's say 90 degress?

I'm looking at the current are set to 15 degrees, guessing it will go to mag mode in just regular crosswind.

**Comment by oleost** [comment]
Trying to read up on how other projects (mainly ardupilot) do it. Haven't found any specific on how they use GPS heading and magnetometer together. 

Only I found was it uses magnetometer on auto takeoff, but then it look like it switches to GPS heading.

**Comment by oleost** [comment]
So, went off flying today, with strong wind and "nav_fw_cruise_thr" at a very low setting. Guess this should include both log of low speed guard, and gps heading vs compas heading.

Think both low speed guard should be increased and it should allow for a higher devation between gps heading and compass heading.

Weather forecast: Strong breeze, 13 m/s from north-northwest

Build used is imu-fw-heading-improvements merged with both master and fw-improvements. 14.05.2016

CLI dump, mission, blackbox log and hex. https://drive.google.com/open?id=0B-yHzNtOXxbESHFiZnlfbGlIQlE

mwptools replay: https://youtu.be/-GpsUS4Zt8c
Recording from plane: https://youtu.be/6VaaDzuuNvQ

**Comment by oleost** [comment]
New test flight, 10m/s min speed and 60 degress error rate.

https://drive.google.com/open?id=0B-yHzNtOXxbEZmt0MWNQVFZxQjA

camera recording: https://youtu.be/Qqa2DUAHu3U

mpwtools https://youtu.be/eBo-3oe9SQ0

**Comment by oleost** [comment]
I asked PatrikE how he did it in baseflight.

"I have a detection that disable MAG if Gps and Mag diff.
Seems to work well.
Mag can be good to use in strong headwind and the plane is "hovering" like a kite and you don't get reliable Gps heading.
Otherwise GPS is better on a plane.

Infact both Baro and Mag is Outperformed by GPS on Fixed wing."

This is opposite of what we are doing.

Would it be better to rahter (or both but with very large error toleramce)than on error we use mag when below a certain speed?
So if let's say default speed guard is 7m/s you could disable GPS heading below 4m/s

I'm currently going to set this to 80degress so it won't fly more than sideways

**Comment by sppnk** [comment]
I dont use mag, because cc3d doesn't have one. And I  am not sure if this is related, but some times, the plane comes to home position with big diference between line of RTH and heading angle  (sideways flying). Just to info about.

**Comment by oleost** [comment]
Interresting video some points showing how sideways its actually flying.

https://youtu.be/vWdVtmkS6bg

PS, I think it would fly much better when I up the cruise throttle so it have more control going trough the air, instead of just floating with it downwind.

**Comment by sppnk** [comment]
Great work @oleost . Those videos are amazing to investigate issues. Thks.

**Comment by oleost** [comment]
Hoe about A about:
1. Fall back to mag if GPS heading is not available.
2. Fall back to mag if difference is above 80°,  // Just to keep it from flying backwards towards goal.
3. Use mag if GPS speed is below 3 m/s //This is maybe already present ?? I think you mentioned that once @digitalentity ?

In my opinion this would be the best way to handle mag in an airplane. Then this is maybe reading for merge?

**Comment by benjamincburns** [comment]
> Trying to read up on how other projects (mainly ardupilot) do it. Haven't found any specific on how they use GPS heading and magnetometer together.

Ardupilot uses an extended kalman filter for combining different observations of the same phenomenon. I don't know for certain whether its output heading considers heading from the GPS, but it is augmented by the rest of the intertial state/position estimation algorithm.

http://ardupilot.org/dev/docs/extended-kalman-filter.html

**Comment by oleost** [comment]
@digitalentity This is a old one, time to get it implemented so we dont need to disable MAG ?

As I mentioned earlier:
1. Prefer to use GPS heading on airplane
2. Fall back to mag if GPS heading is not available.
3. Fall back to mag if difference is above 80°, // Just to keep it from flying backwards towards goal.
4. Use mag if GPS speed is below 3 m/s //This is maybe already present ?? I think you mentioned that once @digitalentity ?

**Comment by digitalentity** [comment]
This needs to be reviewed and adjusted accordingly. Will look into this.

**Comment by digitalentity** [comment]
@oleost this behaves like you described. GPS course is preferred. Mag is used as a backup if GPS is not available, speed is too low or error is too big. Should be safe to test.

**Comment by oleost** [comment]
@digitalentity If there has been no changed, it should be safe to merge since I test flight it some months ago. Believe I got everything verified working.

Going away for cabin trip so can't do any test flying this weekend. So if you want it tested before merge someone else have to do it. Or it will have to wait. But it would be nice not to tell people to disable the mag.

**Pull request merged**
