### PR TITLE
Fix OMNIBUSF7NXT DSHOT DMA allocation for M6

### PR DESCRIPTION
**Pull request by digitalentity**
Fix issue reported in https://github.com/iNavFlight/inav/pull/3879#issuecomment-443724893
@bigdaddy5414 can you test on your board?

### CODE REVIEW

**Comment by bigdaddy5414** [comment]
That got it working somewhat. There is now another issue and it seems to be motor 3 every time. They all arm and once giving some throttle, motor 3 stops. Disarm and you hear the esc initialize beep take place. Arm and all spinning until throttle applied and motor 3 shuts down again. Went back to betaflight to check and no problem there. Tried in the motors tab as well and moving master slider up and back down you hear the initialize beep. However if I only slide 1 motor up and back down at a time, it never does it.

**Comment by digitalentity** [comment]
If you increase throttle slowly is it the same?

**Comment by bigdaddy5414** [comment]
Yes slowly at about 20% it seems to kick off. When i punch the stick up it seems to hang it longer, sometimes a few times.

**Comment by digitalentity** [comment]
Propellers on or off? 
Can you try DSHOT150, DSHOT300 to see if behavior is different.
I'll also check the signal with oscilloscope here to see if there are any signal issues.

**Comment by bigdaddy5414** [comment]
Props are off as im just trying it on the bench. I can try other dshots.

**Comment by bigdaddy5414** [comment]
DSHOT150 appears to be fine.

**Comment by bigdaddy5414** [comment]
DSHOT300 is fine as well. It sounds cleaner as well, on 1200, there was some noise I don't know how to explain like a slight speed change at a fraction of a second, guessing it was on motor 3.

**Comment by digitalentity** [comment]
What `motor_pwm_rate` do you test with?

**Comment by bigdaddy5414** [comment]
It is 4,000, 8,000 resulted in cpu usage jumping sky high to well over 100%

**Comment by digitalentity** [comment]
Not `looptime`:

```
set motor_pwm_rate = 16000
set motor_pwm_protocol = DSHOT1200
```

Works fine on my board.

**Comment by digitalentity** [comment]
I've tested here and verified that signal at FC pads is perfect.

Chances are that you are hitting the noise problem I was concerned a lot when adding DSHOT in the first place.

Noise from motor power wires disrupts DSHOT packets and ESC silently discard them until there are simply too many broken ones. Then it suddenly fails completely instead of slowly degrading (as it would with "analog" protocols). DSHOT is much less tolerant to noise compared to "analog" protocols, however silent discarding feature makes it look more resilient up to the moment when it suddenly fails.

In Betaflight updates are sent at higher rate which mitigates (or should I say "masks") the problem by simply sending more packets hoping that enough will get through.

Solution is to use low speed protocol and better quality wiring (as short as possible, twisted with dedicated signal ground, as far as possible from power lines).

I wonder how may "motor stopped in flight" issues on racequads are related to DSHOT failure...

**Comment by bigdaddy5414** [comment]
OK I tried 16000 and same thing. That is a bummer.

**Comment by digitalentity** [comment]
I'll test on my test bench, but I doubt it will make any difference. Signal on M1...M4 is identical.

**Comment by wx4cb** [comment]
Ive not seen it on betaflight, but that makes sense.

I am not at home right now, but if you can compile a version for the f405
wing matekf405se konstantine, I'll try it on my tmotor escs when i get home
in a couple hours

**Comment by wx4cb** [comment]
Ps im using twin motors so using s1 and s2

**Pull request merged**
