### PR TITLE
Turtle mode settings.yaml DShot condition fix

### PR DESCRIPTION
**Pull request by breadoven**
Erroneous quote marks removed. Surprised compiler doesn't complain ?

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
> Erroneous quote marks removed. Surprised compiler doesn't complain ?

the compiler does not return an error, because it has no error. Even with the quotes `" "` , the settings.rb file can identify the parameter. Putting them in quotes is not the pattern expected by the "Coding Style", but it works.

**Comment by breadoven** [comment]
> > Erroneous quote marks removed. Surprised compiler doesn't complain ?
> 
> the compiler does not return an error, because it has no error. Even with the quotes `" "` , the settings.rb file can identify the parameter. Putting them in quotes is not the pattern expected by the "Coding Style", but it works.Thanks for fixing this!

Except it doesn't work with the quotes. It fails to compile if you don't define DSHOT in the build. Doesn't complain about the quotes but does about the undefined setting.

**Comment by stronnag** [comment]
> Except it doesn't work with the quotes. It fails to compile if you don't define DSHOT in the build. Doesn't complain about the quotes but does about the undefined setting.

Strange, it does here, with or without DSHOT defined.

**Comment by stronnag** [comment]
OTOH, I have no problem with consistency, so let's merge it.

**Comment by breadoven** [comment]
> > Except it doesn't work with the quotes. It fails to compile if you don't define DSHOT in the build. Doesn't complain about the quotes but does about the undefined setting.
> 
> Strange, it does here, with or without DSHOT defined.

You're right, now it works quotes or not ... weird. Definitely came up with a setting error related to turtleModePowerFactor.

**Pull request merged**
