### PR TITLE
Initial cut on MATEKF722 target

### PR DESCRIPTION
**Pull request by digitalentity**
Matek F722 board initial support - per #2552

### CODE REVIEW

**Comment by saliimam** [comment]
Looks good - will test this weekend.  Any reason for putting motor 2 to signal 5? Also smart move bringing in the added compass from the newest BF revision.

**Comment by MATEKSYS** [comment]
@saliimam  S5 is on TIM3, same as S1, no confliction with other servo outputs

**Comment by MATEKSYS** [comment]
Following firmware tested.

http://www.mateksys.com/Downloads/FW/inav_1.8.1_MATEKF722.hex


image

**Comment by MATEKSYS** [comment]
Frsky smartport(inverted) can't work on TX pin.
non-inverter hack can work on TX pin
set telemetry_inversion = ON,  Frsky smartport work on TX pin.

**Comment by KnuckleUpFPV** [comment]
Flashed this firmware to test. Unable to connect to configurator after flashing. Tried flashing via inav, cleanflight, and betaflight

**Comment by digitalentity** [comment]
@KnuckleUpFPV try flashing with full erase

**Comment by KnuckleUpFPV** [comment]
I've tried it with every setting. It doesn't work. Board isnt even recognized after flashing. Its only seen in dry mode. I even went to the matek site and downloaded it from there. Same deal. Fc is not seen. Blue led flashes rapidly. On first plug in red and blue that are side by side flash like police lights alternate of each other very fast.

**Comment by KnuckleUpFPV** [comment]
Did mode not dry mode. Can't edit from my phone

**Comment by KnuckleUpFPV** [comment]
DFU*

**Comment by MATEKSYS** [comment]
I got the same status after flashing this inav firmware. wrong com port detected by computer(win10 x64). show " FS mode" ,  I tried BF firmware, F722 com port works normal with BF GUI.
image
then I reinstall the VirtualCOM driver with this. fixed.
http://www.mateksys.com/downloads/fc/STM32-VirtualCOM-Dvr-64bit.exe

**Comment by KnuckleUpFPV** [comment]
Its not wrong com port issue. It doesnt recognize the fc. Tried the impulserc driver fixer and it didn't find it either because the pc doesnt see it after flashing. I get no detection beeps or anything unless in dfu mode.

**Comment by MATEKSYS** [comment]
@KnuckleUpFPV , I got the same issue as yours, fixed with new COM driver.
check your computer device manager. if you find "comport FS mode". that is wrong.

**Comment by KnuckleUpFPV** [comment]
I do not see that. Computer doesn't see anything when its flashed with this hex.....i can use any other hex and it finds the fc just fine. Had betaflight on it prior to this. I was hoping inac fixed the i2c errors. Why is there a continuous chain of hoops to jump through with matek flight controllers?  I can flash it with a completely wrong target and the pc will see it. Just something about this firmware.

**Comment by KnuckleUpFPV** [comment]
Let me dig out the windows 7 pc and see if that works.

**Comment by MATEKSYS** [comment]
image

**Comment by digitalentity** [comment]
Can you post a close up of the board?

**Comment by KnuckleUpFPV** [comment]
That's awesome there are no starting i2c errors. Maybe I can use an external mag and gps now. 
You want a pic of my fc? I literally just flew it on betaflight. My buddy pm'd me this firmware was here. So i didn't fly another pack, I came inside and tried the flash.

**Comment by MATEKSYS** [comment]
I flashed this firmware again just now. unable to connect to GUI after flashing.  I am curious they worked normal yesterday everning. 
uninstall & install COM driver again. fixed.
Try to restart computer just now. it still works

**Comment by MATEKSYS** [comment]
image

**Comment by KnuckleUpFPV** [comment]
Might want to post that on the site for those that it might work for. No luck here. Its getting late and Christmas is in a few hours. Im going to call it a night soon.

**Comment by KnuckleUpFPV** [comment]
windows 7 pc worked after reinstalling virtual comport. windows 10 pc still isnt seeing it. I will configure it from windows 7 pc for now. Thank you for your time. I will test this in flight asap. Probably day after christmas.

**Comment by marwady** [comment]
For those of you with Win10, if you received an auto update, you will probably have to reinstall com port drivers, etc.
This happened about the same time the new hex was available.
I had the same problems however, after reinstalling drivers, stm, etc, it is now working.

Cheers!!

**Comment by digitalentity** [comment]
Ok, so this is a driver issue. I believe this can be merged then. @MATEKSYS ?

**Comment by MATEKSYS** [comment]
@digitalentity  Pls merge it. thanks

**Comment by Spoonman61** [comment]
i have uninstalled and reinstalled every driver imaginable including the win10 driver from matek's site, no luck.  is a fix planned?  i can flash betaflight target and its fine.

**Comment by digitalentity** [comment]
@Spoonman61 I now have a Win10 machine and was able to reproduce and fix the issue.

**Comment by Spoonman61** [comment]
I had tried uninstalling the driver, restarting, and reinstalling the driver.  It was a long day and this is my first try at INAV, I think I left the USB connected to the FC when I restarted.  It is connecting and working now.  It's a 5 inch freestyle that I wanted full navigation on.  It's flying great now but I need to find the right expo to recreate my Betaflight rates.  @digitalentity and @KnuckleUpFPV , do you have an external compass and GPS up and functioning?  This is my first go at INAV I'd like to know it's working on this board, it works great until I connect the GPS and compass, then I get errors.  I don't have a clue what I'm doing other than what I learn on youtube.  I know github is targeted at software development and this is not a place for hardware problems.  Could you please recommend a good forum for help learning my navigation hardware?  Thank you much.

**Comment by KnuckleUpFPV** [comment]
@spoonman61 no sadly the gps isn't working with the external compass. The i2c errors start to ramp up and maxes out the cpu. Even with loop speeds as low as possible. I dont know whats causing it. I gave up. Got a second fc. Same issue. So now it's just in a freestyle quad on betaflight. It was flying terrible. I've added caps as recommended. Soft mounted moved it higher away from pdb and other electronics. Lowered the loop speed to 4/2. Still doesnt fly great. Spent a few hours tuning with no luck. My f3 flew far smoother. I'm just passed disappointment at this point. I'm going to try 3.3. If that doesn't help I give up entirely. I hope this doesn't discourage you. I hope you find a way to get it working.

**Comment by Spoonman61** [comment]
@KnuckleUpFPV Mine flys great in Betaflight and INAV, GPS and compass function properly in Betaflight.  I have a 1000uf low esr cap.  From what I hear your esc choice is critical with the ICM20602, noisy esc's are trouble.  I'm using cheap racerstar RS30a V2's.  I've had it running a 16k loop in BF with no worries.

**Comment by KnuckleUpFPV** [comment]
I went through wad swaps with the f405 aio. Nothing made a difference. Refuse to jump through the same hoops with the f7. It's not worth it. My compass worked in bf, but gps wouldn't return home. And compass would only function for a few min. Cpu would max out and down it would come. My f405s started working after moving receiver to a different uart. The other had a yaw spin of death on a test takeoff smacking a tree. It magically worked after that as well. Now i don't make any changes they stay with the same setup

**Comment by solmag** [comment]
Hi, I'm new to this thread, I have the F722 with Betaflight but never installed on any frame, Is there an update to the F722 hex?

**Comment by Spoonman61** [comment]
The INAV hex dated December 24 is the most recent.  I have tested this board extensively and if you want to run stabilized, horizon, and air/acro in betaflight or INAV it will perform.  Mine fly's fantastic in those modes.  From what I gather nobody has yet to get advanced modes functioning.  My barometer goes wiid in the OSD and continually raised altitude just sitting on the bench.  I can't get the compass to work on it either.  I have to think there is still a firmware revision to address it.   Many people have this board up and running fine for a racer, but I'm yet to see anyone with advanced modes functioning.  Please help us Matek, I love your hardware, please get us functioning firmware.

**Comment by solmag** [comment]
Thanks for the update. I bought this specifically for INAV GPS functionalities. Hopefully, Matek will come up with a solution soon. I have a couple of Matek flight controllers running betaflight and I never had any problems with them, that's why I'm sticking with their product. I would have opted for the Omnibus F7 if I knew that there was no stable hex file for the F722. Matek please come up with a stable hex we're waiting.

**Comment by KnuckleUpFPV** [comment]
I dont think the advance features work due to the i2c errors. It may be possible to use the advance features with a breakout board over spi. I'm not 100% certain on that. Seems feasible. There is some conflict on startup that causes the initial i2c error x3. Then once other i2c devices try to operate the errors grow rampantly and then the fc locks up.

**Comment by ktand** [comment]
There is newer version dated Jan 18th on http://www.mateksys.com/?portfolio=f722-std#tab-id-5. Tried it but unfortunately the barometer still goes wild.

**Comment by ghost** [comment]
I briefly bench tested the Dec 24th release a few days ago with an external MS5611 baro and MN8 GPS+HMC5883 magnetometer.
Worked perfectly, no I2C errors and baro was totally stable.
(I am using an external baro because the F7 processor generates a fair bit of heat.)

**Comment by KnuckleUpFPV** [comment]
With internal baro off the i2c errors go away. That defeats the purpose of buying an fc with built in baro. If yours is working, I will disable mine and add an external baro and test again.

**Comment by ghost** [comment]
Just started testing with internal baro and nothing on the external I2C bus.
No errors and baro is stable.

**Comment by ghost** [comment]
New test, internal baro with GPS+mag.
Again no I2C errors and baro and mag working correctly.

**Comment by Spoonman61** [comment]
Has it flown in advanced modes yet?  Did you have to do anything to get the barometer working?  Mine just keeps going up in altitude after boot.

**Comment by ghost** [comment]
Not flown yet, I'm still building a 650 for it, so bench tested only.
Re the internal baro, didn't do anything other than select it in the configuration tab.

**Comment by ghost** [comment]
Re the baro, do you have the board mounted in an enclosure with foam over the baro?
Just wondering if you have a heat related problem.

**Comment by Spoonman61** [comment]
Right now it is sitting on top of a fchub-vtx, I love the hardware.  The stack is mounted in a 5 inch matrian frame with pleny of airflow.  I have no foam on the barometer as I was just hovering in the basement.  The barometer keeps going up in altitude sitting on the bench with no airflow.  I have the external compass and GPS disconnected ATM.  I would not have thought foam would make a difference when the motors aren't running.  What do you think?

**Comment by KnuckleUpFPV** [comment]
Which firmware are you using. Even from a fresh flash on betaflight the board boots with 3 i2c errors. If you are on 1.8.1 I will try it tonight.

**Comment by Spoonman61** [comment]
I have been in contact with Matek, they tell me the Betaflight devs claim the 3 ic2 errors are normal.  I was stupid and tried baro mode in betaflight with the baro going wonky, I hovered in stabilized mode, landed and flipped to baro mode, it started to hover and an esc burst into flames, no kidding, about an inch high.  A large but quick flame Departed the motor.  I'm out a motor and esc but that's because of my impatients. I knew better but I didn't think that would happen.  I'm hoping flyfisher2 may be able to point us in the right direction.

**Comment by ghost** [comment]
The F7 chip generates a bit of heat and I thought that if you had the board totally enclosed, perhaps rising temperature was affecting the baro but that is not the problem with your set up. The other possibility of course is faulty hardware.
I am using the iNav Dec 24 hex.

**Comment by marwady** [comment]
Fyi,

Mine is working correctly with internal baro and DJI combo GPS and compass.

**Comment by KnuckleUpFPV** [comment]
Spoonman61 thats crazy.  I had no idea what baro mode was for. Someone else told me the devs said its fine. As far as I'm aware an error is a conflict when it comes to i2c. This is the first board Ive ever seen with i2c errors. I own 18 mini quads, and 3 wings. Only fc to exhibit this behavior is the f722

**Comment by Spoonman61** [comment]
@flyfisher2 could you tell us if your barometer was stable after flashing, or if you had to make any changes.  Please tell us what GPS and compass you used.  Please add if there is anything special you had to do to set it up.

**Comment by ghost** [comment]
@Spoonman61 
I use an external baro module MS5611 because I am concerned about the heat generated by the F7 chip causing drift in the internal baro.
However to help you guys, I have now tested using the internal baro.
Made no changes after flashing other than selecting the baro type in the configuration tab. Both are rock solid, no problems at all.

I have used this M8N GPS combo:
https://www.banggood.com/Ublox-NEO-M8N-Flight-Controller-GPS-with-Protective-Shell-for-PIX-PX4-Pixhawk-p-1005394.html?rmmds=detail-top-buytogether&cur_warehouse=CN

Again did nothing special to set it up.

**Comment by solmag** [comment]
@flyfisher2 can you please share a picture of your setup and a shot of your screen? Thanks

**Comment by Spoonman61** [comment]
quick update.  I flashed the Jan 18 hex, i now have a stable barometer, will try compass and gps soon. 
@flyfisher2  thank you for your help!  i think i might get this working.

**Comment by ghost** [comment]
@solmag   Sorry. I dismantled my test jig yesterday to use the parts in the 650 I am building. 
@Spoonman61 That's good news, best of luck with GPS. I will try the Jan release in the 650 I am building. hopefully by next weekend.

**Comment by HipoxiK** [comment]
Hi,

I have been trying to get my Matek F722 board to connect for a few days now using the iNav 24th Jan release candidate from the Matek website. I can't get it connect to my laptop, even after trying to uninstall and reinstall the virtual com port driver. I have tried many variations of reinstalling, re-flashing the firmware, rebooting the pc and nothing is working. I flashed betaflight 3.2.4 onto the board and it works fine. I just can't get the iNav firmware to connect to the com port.

**Comment by digitalentity** [comment]
@HipoxiK try the attached hex:
[inav_1.8.1_MATEKF722.zip](https://github.com/iNavFlight/inav/files/1688053/inav_1.8.1_MATEKF722.zip)

**Comment by HipoxiK** [comment]
Thanks for the .hex to try.

No luck with it so far. Same problem where it isn't picked up via a com
port. Betaflight boards are still working fine. I can connect the F722 in
bootloader mode to flash it and check it in zadig.exe, just can't connect
it normally to use with iNav.

**Comment by ghost** [comment]
This hex works for me whereas the Matek Jan release did not.

After flashing, the blue LED would flash as normal but eventual stayed on.
The port was detected OK in the device manager as STM32 Virtual ComPort in FS Mode (com 4) but it could not be opened.
A self compiled hex around the same time worked OK.

**Comment by HipoxiK** [comment]
I’ll have another play tomorrow.

**Comment by HipoxiK** [comment]
@digitalentity still no luck.

When I check programs and features in windows 10 I have 'Virtual Com port driver V1.4.0' and 'Windows Driver Package - STMicroelectronics (usbser) Ports (08/02/2013 1.4.0)'.

Is this what other guys have and still get this board to connect with iNav firmware?

Or am I missing a Com Port driver?

Edit - I left it connected for an hour or so while video editing, walked away for a bit, came back and it was connected.....weird.

After making some adjustments in iNav Configurator I clicked 'save and reboot'. Now the board wont connect again.

**Comment by ghost** [comment]
My virtual com port is version 1.3.1 and the Windows Package version is listed as 12/10/2013 1.0

**Comment by HipoxiK** [comment]
Maybe I’ll try that older version then. Weird that mine connected after sitting plugged in for awhile though.

**Comment by HipoxiK** [comment]
Tried playing with older com port drivers...no luck.

I flashed my omnibus f7 V2 with it's latest iNav firmware just to check and it connected fine.

Still something not right with the f722 iNav firmware, it should be able to connect fine using the latest com port drivers like all other boards yes?

**Comment by ghost** [comment]
Latest problems with this board:

Cannot get into DFU mode when a GPS unit (any) is connected, error is "too many devices connected".
Must have been the first time I had tried to re-flash with a GPS connected and it drove me crazy for several hours.

I2C errors every few seconds when connected to a SE100 gps unit. Reducing i2c frequency to 200KHZ fixes (or more precisely, band aids) the problem.
The F722 works at 400KHZ with two other MN8 GPS units and the SE100 works at 400KHZ with OMNIBUS F3 and ANYFCF7 flight controllers. 

The buzzer output doesn't work but that is the least of my concerns.

**Comment by digitalentity** [comment]
GPS or serial receiver connected to UART1 will mess up DFU mode, this is a know issue which is related to ST's built-in bootloader. Can't be fixed in software. Can be mitigated by not using UART1 for GPS or receiver.

Regarding I2C errors - use 1K pull-up resistors from SCL&SDA to +3.3V. They are mandatory for I2C bus but the board don't have them.

**Comment by ghost** [comment]
Hi @digitalentity 
I knew about the potential problem with U1 and therefore have nothing connected to it.
The GPS is connected to U7. 
I also know about the need for i2c pull ups but did not think to check that they were fitted as the SE100 worked fine on two other flight controllers. I am using an external baro on the i2c bus which does have pull ups, so maybe that's good enough for the other flight controllers but not the Matek. Who knows?
Thanks for the heads up.

**Comment by MATEKSYS** [comment]
@digitalentity  Pull-up resistors are available.
image

**Comment by digitalentity** [comment]
@MATEKSYS didn't know that.

This makes things interesting. There are reports about BMP280 and HMC5883 compass not working well whenplaces together on the same I2C bus. You should consider moving BMP280 baro to SPI bus for your next board.

**Comment by ghost** [comment]
Re my previous comment on the DFU problem.
I mistakenly said that the GPS was connected to U7, it was actually connected to U3.
And would you believe it, that is the only port that messes up DFU mode. U1 and the rest don't cause a problem.

**Comment by digitalentity** [comment]
@flyfisher2 Whoa! This is really something. Damn, according to ST's AN2606 on F72x series bootloader is active on U1 **and** U3. The same applies to F745 chips.

We really need to consider our own bootloader.

**Comment by HipoxiK** [comment]
FYI,
I tried plugging a battery into my drone then connecting the FC to the laptop. It will now connect fine and I can connect it to iNav. Wont connect without battery power though.

**Comment by digitalentity** [comment]
@HipoxiK this is usual if you have something connected to I2C and it's not powered along with the board. If you have external GPS/Compass connected you must power them.

**Comment by HipoxiK** [comment]
Ah ok thanks. This is where I was going wrong. I'm new to drone builds coming from quads and betaflight.

Thanks for keeping this thread running, I'm getting lots of good info from you guys.

**Comment by HipoxiK** [comment]
To clear my issues up then the latest Matek F722 iNav 24 Jan candidate is working fine on my laptop with the latest STM32 drivers. It was just that I needed battery power connected.

I'll start setting the gps, compass, bluetooth, camera switcher, pay load release servo and the TBS Micro RX V2 up and see how we go.

**Comment by ghost** [comment]
@digitalentity 
Well, I had the choice of U2 to U5 and managed to pick the one that would not work!

**Comment by solmag** [comment]
Before I embark on building this FC, has anyone actually flown with this firmware and how's the AUTO POS HOLD and RTH working?

**Comment by ghost** [comment]
@digitalentity 
Reference your comment about BMP280 and HMC5883 not being happy on the same I2C bus.
Do you think removing the BMP280 might eliminate the I2C errors I am getting with the SE100 GPS unit?
As mentioned previously reducing i2c_speed to 200KHZ stops the errors but I am not really happy that this is a real cure.

**Comment by HipoxiK** [comment]
I have now set up the GPS and Compass which have calibrated and work although the compass keeps drifting back to 8 degrees when I turn the drone to north. I believe this is due to a clone Mag (QMC5983) which radiolink have been using in their SE100 GPS/Compass even though iNav reads mine as HMC5883. From another thread it sounds like its an issue with the mag gains and by removing the magGain code it can fix this issue, eg.
magDev->magADCRaw[X] = (int16_t)(buf[0] << 8 | buf[1]) * magGain[X];
magDev->magADCRaw[Z] = (int16_t)(buf[2] << 8 | buf[3]) * magGain[Z];
magDev->magADCRaw[Y] = (int16_t)(buf[4] << 8 | buf[5]) * magGain[Y];
to
magDev->magADCRaw[X] = (int16_t)(buf[0] << 8 | buf[1]) ;
magDev->magADCRaw[Z] = (int16_t)(buf[2] << 8 | buf[3]) ;
magDev->magADCRaw[Y] = (int16_t)(buf[4] << 8 | buf[5]) ;

You guys encounter this?

**Comment by ghost** [comment]
@HipoxiK 
My one is the same, it needs the mods you have listed.
After the mod, I had to reduce i2c_speed to 200KHZ to eliminate (or cover up) I2C errors from the mag.
Be interested to hear how your one performs after the mod.

**Comment by HipoxiK** [comment]
@flyfisher2 
I have reduced the i2c speed down to 200khz already to stop the i2c errors. 

Could I get a copy of your .hex if you have already modded it and removed the magGain?

I don't have time to learn how to mod .hex files right now and would really like to get this drone in the air. At this stage the magGain issue is all that's stopping me.

Cheers

**Comment by ghost** [comment]
Never done this before hope it works:

[inav_1.8.1_MATEKF722 SE100.hex.zip](https://github.com/iNavFlight/inav/files/1702621/inav_1.8.1_MATEKF722.SE100.hex.zip)

**Comment by HipoxiK** [comment]
@flyfisher2 

I'll test it today and see if it works for me.

Edit: Seems to be working @flyfisher2, thanks for editing that .hex. My magnetometer now sits on a heading without slowly drifting back to a set heading.

I'm still running it at 200khz though.

I need to finish the setup and test fly still but looking good so far.

**Comment by ghost** [comment]
@HipoxiK 
I don't have anything to flight test it at the moment but it seems to be OK on the bench (apart from the I2C errors).
Just be aware that I compiled that hex from the development branch and as such it may have some bugs or funnies.

**Comment by HipoxiK** [comment]
@flyfisher2 
Are you able to remap resources such as the PWM pad, motor 7 (B08) to a servo, same with S5 and S6 pads.

I need these to be channel forwarded to servo's but can't seem to edit these resources using what I thought was the correct commands in the CLI.

**Comment by ghost** [comment]
@HipoxiK 
Sorry mate, I'm a hardware type and can do minor/simplistic code changes but this is beyond my capabilities.

**Comment by HipoxiK** [comment]
@flyfisher2 
Haha no worries mate. I'll keep looking into it as I can't seem to be able to remap resources in the CLI as you normally could which means the spare pwm pads are stuck on motors 5,6,7 out and can't be changed for servo's.

**Comment by shellixyz** [comment]
@HipoxiK 6 and 7 can already be used for servos but for 5 (PB1) you need to edit line 35 of `target/MATEKF722/target.c`

**Comment by HipoxiK** [comment]
@shellixyz 
Yes I am aware they can be used for servos but when I check the resources in CLI they are both assigned Motor6 out and Motor7 out respectively. How can I change these to servo outputs because as far as I'm away iNav doesn't support resource remapping yet.
Thanks

**Comment by ghost** [comment]
Finally installed the board into our 650mm Quad last night.
Before leaving for the flying field this morning, I decided to re calibrate the sensors, just to be sure.
Glad I did. On the first attempt I got accgains of  6336  0  4090
Second attempt 16651  0  4096, then 0  6712  4091.
The original calibration was 4091  4095  4092.
Looks like I have a hardware problem now, so I think its time to give up.

**Comment by shellixyz** [comment]
@HipoxiK You don't need to they will be used for servo outputs if they are defined in the mixer.

**Comment by HipoxiK** [comment]
@flyfisher2 
Thats no good, mine are:
accgain_x = 3240
accgain_y = 4800
accgain_z = 4100

**Comment by ghost** [comment]
Yes, my initial calibration a couple of weeks ago was fine but something seems to have gone drastically wrong with the board since then.
Glad I decided to do another cal before the maiden flight, otherwise I could now be looking at a pile of expensive scrap.

**Comment by HipoxiK** [comment]
@shellixyz 
Ok thanks mate I'll give that a shot.

**Comment by HipoxiK** [comment]
Test flew the drone today. All Nav functions are working correctly. Alt Hold is good, GPS Hold and RTH work great.

@shellixyz 
Can I leave the mixer as QuadX and just define smix for the servo pads. I assume pads 1-5 are motor pads and 6,7(pwm) pads are servo's?

Or will I need to use a custom mix and define the motors using pads 1-5? Then smix servo pads 6,7?

**Comment by ghost** [comment]
@HipoxiK 
Great news and good to know the hex was OK.
Don't know whether to take a chance and buy another MATEK or revert back to ANYFCF7 and put up with the hassle of MWOSD.

**Comment by HipoxiK** [comment]
@flyfisher2 
Well if I can get the servo's working for the camera switcher on pad 7 (pwm) and the pay load release servo on pad 6 then I'd say the Matek F722 is tough to beat seems the other minor issues are getting sorted/worked out.

**Comment by MATEKSYS** [comment]
image
S7=servo via CH5 of transmitter

**Comment by HipoxiK** [comment]
Thanks @MATEKSYS I'll try that tomorrow. Is there a way to get a 2nd servo out of S6?

Just tried CH5 as the camera switcher which is connected to S7 and it works perfect. Thanks for the help as I tried it with other AUX channels but not 5.

I wonder if there isn't a solution to get S6 to control a 2nd servo using another Aux channel on the transmitter maybe I could wire the signal from the servo to the 3rd camera switcher signal out and see if that activates the servo as the 3rd position on CH5.

**Comment by MATEKSYS** [comment]
@HipoxiK Seams S6 can't be used for AUX channel. 
according to my guess, S7=CH5, S8=CH6, S9=CH7..., so need additional PWM definition in target.c

**Comment by HipoxiK** [comment]
@MATEKSYS 
Is it possible to enable S6 PA8 as servo-6 in the Quad x mixer like it is in the Airplane mixer. If so I would assume that you could then assign this servo-6 to a channel in the Servo tab of iNav and use it to control a servo on a drone.
I have the channel forwarding turned on and use CH5 to control the camera switcher but would like another servo control as well.

**Comment by leonvuksic** [comment]
Hi all,
I have read the complete thread and I decided to ask for help, I'm having a lot of issues using external gps and magnetometer on this board.
Yesterday I chatted with Pavel and he compiled the latest hex for f722-std but I still cant use magnetometer and gps because barro dies.
I have lowered the i2c speed but it didnt help.
I have a pmw reciver, gps m8n+compass hmc5883 and i have 2 servos for camera gimbal.

Please help me and tell me what is the best place on the board to connect everything including servos and please attach the besd hex I should flash.

Also I am willing to test flight any future builds/releases for this board!

**Pull request merged**
