### PR TITLE
Updated REVO target

### PR DESCRIPTION
**Pull request by DzikuVx**
REVO target updated to latest Betaflight to bring Airbot F4 / Flip32 F4 compatibility for:
- beeper
- led strips

### CODE REVIEW

**Comment by digitalentity** [comment]
I suggest we postpone it for 1.4

**Comment by martinbudden** [comment]
OK, done.

**Comment by digitalentity** [comment]
@DzikuVx shouldn't we mare FlipF4 a different target as we discussed in Gitter?

**Comment by DzikuVx** [comment]
@digitalentity probably yes, probably not now. Those changes ported from Betaflight are Revo an Flip32 compatible.
I still have to confirm external I2C working or not. If not, then new target will be required. 
The same goes for Led strip output on designated port.
For now I would prefer to align this to Betaflight and then make new target if required

**Comment by DzikuVx** [comment]
bench tested this updated target on Flip32 F4. Seems to be working with build-in hardware.

**Comment by DzikuVx** [comment]
Since Airbot F4 / Flip32 F4 will have their own target, some changes we reverted. Specially BEEPER_INVERTED is not longer enabled. That makes BP4 buzzer with transistor hack work again.

Also, board documentation was added

**Comment by DzikuVx** [comment]
tested as far as I able to without actual REVO. Looks like everything is working. Known issues:
- I2C external is not initialized just like before update. Has to be fixed in #718 
- LED Strip is not working just like in case of #717 @martinbudden disabling BLACKBOX did not helped. Still have one idea I will try , but either way, target can be merged.

**Comment by DzikuVx** [comment]
OK, I give up. LED Strips are not working on this board right now at all. Current BF target definition does not works, previous definition (before target update and port from BF) also does not work. Someone else have to take a look into it now. And no, my strip is fine, works on BF 3.0.1

**Pull request merged**
