### PR TITLE
[SITL OSX] Fix some of the warnings and add macosx SITL build to workflows

### PR DESCRIPTION
**Pull request by mmosca**
clang can be verbose with warnings, but some of it is probably valid when building a 64bit binary.

Highlighted changes:

* Call float versions of math functions to avoid conversion to double by the compiler (absf, sqrtf, roundf, etc)
* Make sure floating point constants are marked as floats, to avoid conversion to double by the compiler.  (1.0 is a double, 1.0f is a float and when doing math between float and double, all values get upgraded to double!)
* Changed memcpy_fn in unit test AND SITL builds to be a macro to memcpy (instead of inline function calling memcpy), this fixes linker errors for memcpy as macos compiler mangles the symbol in a different way and would not work with asm("memcpy") call. 
* Some simulator code made heavy use of doubles, but since all the data in INAV is float, that is probably overkill and some functions/macros had float in the name, while upconvertting to double.

Open questions:
* Should scale in osdFormatCentiNumber be changed to float? It is currently uint32_t but some of the scale defines are, correctly, not integer numbers.
* I changed CENTIDEGREES_TO_DEGREES to use float on the division path, but the code seems to be ok, or assuming it would be converted to integer anyway. Is this the correct solution?
* This still does not fix the invalid settings issues, but overall should make it easier to test mac builds.

### CODE REVIEW

**Comment by mmosca** [comment]
@Scavanger and @stronnag would you mind having a look and providing some feedback?

**Comment by mmosca** [comment]
A quick indoor line of sight flight test with a quad was successful.

Configurator appears to be happy with the results.

I haven't tested any of the simulators.

**Comment by stronnag** [comment]
And while waiting for the Win10 VM to boot, lets build it on the VisionFive2 board. Yes, it's happy on linux/riscv64 ... looks good to me.

**Review by stronnag — APPROVED** [review]

**Comment by stronnag** [comment]
For completeness, built on an antediluvian MacOS VM
```
[149/287] Building C object src/main/t...iles/SITL.elf.dir/__/__/flight/imu.c.o
/Users/jrh/Projects/inav/src/main/flight/imu.c:331:55: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    STATIC_FASTRAM fpVector3_t vGyroDriftEstimate = { 0 };                                                     ^
```

Noting also that the more serious issue that MacOS SITL corrupts its own settings still exists; but that's a different and rather more difficult problem.

**Comment by mmosca** [comment]
> 



> For completeness, built on an antediluvian MacOS VM
> 
> ```
> [149/287] Building C object src/main/t...iles/SITL.elf.dir/__/__/flight/imu.c.o
> /Users/jrh/Projects/inav/src/main/flight/imu.c:331:55: warning: suggest braces around initialization of subobject [-Wmissing-braces]
>     STATIC_FASTRAM fpVector3_t vGyroDriftEstimate = { 0 };                                                     ^
> ```
> 
> Noting also that the more serious issue that MacOS SITL corrupts its own settings still exists; but that's a different and rather more difficult problem.

That warning is not on the latest macosx compiler which is used by github (Apple clang version 14.0.3 (clang-1403.0.22.14.1))

I also no longer see the settings corruption over here. Can you try with the binary in the artifacts, instead of building your own?

I may need to change the build a bit to support older versions of MacOSX though,  but I only have access to 13 (Ventura)

**Comment by stronnag** [comment]
On my ancient MacOS VM, the settings are always corrupt (even with fresh settings). Fix one corrupt setting, then there's another, fix that, go back one step . The settings ARMing flag can never be cleared. Either with the artefacts build or self built.

But if this doesn't happen on a real, modern Mac (vice my ancient VM), it's not a problem.

**Comment by stronnag** [comment]
Thusly

```
[jrh@eeyore]$ cliterm -d tcp://macbox:5760
open tcp://macbox:5760

Entering CLI Mode, type 'exit' to return, or 'help'

# status
INAV/SITL 7.0.0 May 22 2023 / 19:03:45 (13310d2e)
GCC-Apple LLVM 14.0.0 (clang-1400.0.29.202)
System Uptime: 4 seconds
Current Time: 2023-05-22T19:46:02.000+00:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=500MHz, GYRO=FAKE, ACC=FAKE, BARO=FAKE, MAG=FAKE
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
System load: 0, cycle time: 1054, PID rate: 948, RX rate: 10, System rate: 10
Arming disabled flags: CAL ACC RX CLI SETTINGFAIL
### ERROR: Invalid setting: nav_fw_pos_hdg_pidsum_limit
OSD: not enabled
VTX: no VTX control

# version
# INAV/SITL 7.0.0 May 22 2023 / 19:03:45 (13310d2e)
# GCC-Apple LLVM 14.0.0 (clang-1400.0.29.202)

# set nav_fw_pos_hdg_pidsum_limit = 100
nav_fw_pos_hdg_pidsum_limit set to 100
# save
Saving
Rebooting[jrh@eeyore]$
[jrh@eeyore]$
[jrh@eeyore]$ cliterm -d tcp://macbox:5760
open tcp://macbox:5760

Entering CLI Mode, type 'exit' to return, or 'help'

# status
INAV/SITL 7.0.0 May 22 2023 / 19:03:45 (13310d2e)
GCC-Apple LLVM 14.0.0 (clang-1400.0.29.202)
System Uptime: 4 seconds
Current Time: 2023-05-22T19:46:44.000+00:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=500MHz, GYRO=FAKE, ACC=FAKE, BARO=FAKE, MAG=FAKE
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
System load: 0, cycle time: 1001, PID rate: 999, RX rate: 9, System rate: 10
Arming disabled flags: CAL ACC RX CLI SETTINGFAIL
### ERROR: Invalid setting: antigravity_gain
OSD: not enabled
VTX: no VTX control

# set antigravity_gain = 1
antigravity_gain set to  1.000
# save
Saving
Rebooting[jrh@eeyore]$ cliterm -d tcp://macbox:5760
open tcp://macbox:5760

Entering CLI Mode, type 'exit' to return, or 'help'

# status
INAV/SITL 7.0.0 May 22 2023 / 19:03:45 (13310d2e)
GCC-Apple LLVM 14.0.0 (clang-1400.0.29.202)
System Uptime: 4 seconds
Current Time: 2023-05-22T19:46:59.000+00:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=500MHz, GYRO=FAKE, ACC=FAKE, BARO=FAKE, MAG=FAKE
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
System load: 0, cycle time: 1001, PID rate: 999, RX rate: 9, System rate: 10
Arming disabled flags: CAL ACC RX CLI SETTINGFAIL
### ERROR: Invalid setting: fw_p_roll
OSD: not enabled
VTX: no VTX control

# set fw_p_roll = 0
fw_p_roll set to 0
# save
Saving
Rebooting[jrh@eeyore]$ cliterm -d tcp://macbox:5760
open tcp://macbox:5760

Entering CLI Mode, type 'exit' to return, or 'help'

# status
INAV/SITL 7.0.0 May 22 2023 / 19:03:45 (13310d2e)
GCC-Apple LLVM 14.0.0 (clang-1400.0.29.202)
System Uptime: 4 seconds
Current Time: 2023-05-22T19:47:16.000+00:00
Voltage: 0.00V (1S battery - NOT PRESENT)
CPU Clock=500MHz, GYRO=FAKE, ACC=FAKE, BARO=FAKE, MAG=FAKE
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE
System load: 0, cycle time: 1001, PID rate: 999, RX rate: 9, System rate: 10
Arming disabled flags: CAL ACC RX CLI SETTINGFAIL
### ERROR: Invalid setting: antigravity_gain
OSD: not enabled
VTX: no VTX control

```

**Pull request merged**
