### PR TITLE
Mode availability improvements

### PR DESCRIPTION
**Pull request by breadoven**
Cleans up mode availability based on craft type and sensors enabled.

SURFACE requirements need confirming (not sure if OPFLOW is required).

### CODE REVIEW

**Comment by RipperGOT** [comment]
@breadoven For surface mode opflow it not requiered.  I have a Benewake rangefinder mounted on my multi and works very well only with it.

I'm writing this to you because I just had a conversation on Discord after updating to 5.0 and seeing that the Surface in modes tab option doesn't appear.  In 4.0 and 4.1 it works without problem!
We have come to the conclusion that the opflow was added to be able to use the Surface mode.

}
    if (sensors(SENSOR_BARO) && sensors(SENSOR_RANGEFINDER) && sensors(SENSOR_OPFLOW)) {
        ADD_ACTIVE_BOX(BOXSURFACE);

Could this be changed again so that only with Rangefinder the Surface mode can also be used? Thanks!!!!!

**Comment by breadoven** [comment]
No problem, I'll fix it. At least we now know what does work, I spent some time trying to work out what was required but it wasn't very obvious looking at available info.

**Comment by RipperGOT** [comment]
> > > No problem, I'll fix it. At least we now know what does work, I spent some time trying to work out what was required but it wasn't very obvious looking at available info.
> > 
> > 
> > Thanks friend! I made the mistake of not realizing that the Surface mode did not appear when I tried RC1, 2 and 3. When you do, and if you want, send me the test compiled firm, I'll be happy to test it!
> 
> The firmware should be available at https://github.com/iNavFlight/inav/actions/runs/2572191047 once it's finished testing.

Thanks a lot!!!! If you need anything I can help you with, I'd be delighted! Less programming... I stayed in arduino and it wasn't very good either! 😅

**Comment by RipperGOT** [comment]
Sorry, where can I download Inav 6.0 configurator for test it???

**Comment by breadoven** [comment]
Oh forgot about that. You can get it here http://seyrsnys.myzen.co.uk/inav-configurator-next/.

**Comment by RipperGOT** [comment]
Perfect! Successfully detected! You're the best!

Captura de pantalla 2022-06-28 005026

**Pull request merged**
