### PR TITLE
Alternative failsafe procedure for minimum altitude

### PR DESCRIPTION
**Pull request by nmaggioni**
Having recently seen a [pilot of a fixed wing lose signal right after having landed](https://www.youtube.com/watch?v=GtWOXLt_10U) - presumably not near the home point and/or without the [minimum distance setting](https://github.com/iNavFlight/inav/blob/master/docs/Failsafe.md#failsafe_min_distance) enabled - and having its RTH failsafe engaged even though the craft was on the ground, I thought that an additional failsafe modifier would be useful for such situations; it could avoid smoking motors or blowing ESCs under specific conditions.

I've copied the `failsafe_min_distance` logic and replicated it and its settings as `failsafe_min_altitude`. The minimum **distance** still has precedence over the minimum altitude, as can be clearly seen in the code. I've also made the altitude threshold signed, in case someone plans to fly lower than their home position.

---

~~**CLARIFICATION NEEDED BEFORE MERGING:** I'd like someone to confirm me that [`getEstimatedActualPosition(Z)`](https://github.com/nmaggioni/inav/blob/failsafe_min_altitude/src/main/flight/failsafe.c#L404) and  [`baro.alt`](https://github.com/nmaggioni/inav/blob/failsafe_min_altitude/src/main/flight/failsafe.c#L406) both return the altitude relative to the home position. I've deducted so from the OSD code, but a confirmation from a more experienced contributor would make this final.~~

---

- [X] New settings added
- [X] Docs updated
- [X] Tests ran
- [X] Compilation ran (_OMNIBUSF4PRO_ target)

### CODE REVIEW

**Review by giacomo892 — CHANGES_REQUESTED** [review]
There is a typo failsafe_min_distance_procedure  should be failsafe_min_altitude_procedure

**Comment by giacomo892** [comment]
Yes. You can use getEstimatedActualPosition(Z) to get current altitude.

Also, I see the pilot has burnt a motor on the ground. Shouldn't modern ESC have low RPM protection avoiding this kind of situations?

**Comment by nmaggioni** [comment]
@giacomo892 Thanks for the confirmation and for having spotted the typo! Modifying large markdown tables can quickly get messy. The pilot said that he was using an HK Blue ESC so he did not have or set up such protection, unfortunately.

This PR could also be useful if, for example, something after autolaunch prevents the craft from gaining altitude; you may want it to drop instead of keep trying to rise. _Just a random thought, I'm aware that you should probably just manually disarm and land._

**Comment by giacomo892** [comment]
I find this PR risky since my usual flights are from hills and moutains and happens that I fly negative altitudes. Being said that. I'll just disable this setting in my configuration but it should be made clear on the documentation about this risk.

**Comment by nmaggioni** [comment]
That's a valid point. I'd like to add a condition that altitude must be > 0 in order to trigger this, but then what if my home position was recorded a few meters higher than it really is, or if the craft has an imprecise baro and no GPS? How much of a threshold should I set, +/-10m maybe? Or make it user-configurable via CLI only?

**Comment by digitalentity** [comment]
This is a wery dangerous way of preventing failsafe issues on the ground and should not be merged.

Altitude may drift (in changing weather and long flight - it may drift a lot). Pilot may fly below takeoff (and in this case failsafe will disarm and crash the craft, instead of saving it). I suggest we concentrate on finding a way to solve https://github.com/iNavFlight/inav/issues/2331

**Comment by nmaggioni** [comment]
@digitalentity what about using this for positive altitudes only? If the user enables it, what this does should have already been understood.

Either way it's clearly up to you, feel free to close this PR if the feature can't be altered to make it fit somehow.

**Comment by fiam** [comment]
Sorry, but I don't like this idea (I didn't like the min_distance approach either, but it was't my call to wether that should be committed). As @digitalentity has pointed out, what we need to figure out is a way to let us know with reasonable confidence if we're airborne or sitting on the ground. It's way more flexible than user configured settings and can also be used to detect if we've crashed and we should shut off motors.

I really hate when people waste time, specially in cases like this when it shows you've put a lot of work in describing the use case as well as properly documenting everything. Please, just hop onto the slack channel and bounce ideas around before implementing time, so we can avoid this in the future.

**Comment by nmaggioni** [comment]
@fiam That's true, but to me this was not wasted time: I've gained a lot of insight on how iNav works under the hood and had fun testing out my code, and having it reviewed by somebody else is surely rewarding regardless of the PR being approved or not. This way I'll be more prepared for my eventual future PRs here.

**Comment by fiam** [comment]
@nmaggioni Thank you so much for your understanding :-)

**Pull request closed without merging**
