### PR TITLE
Geozones.md

### PR DESCRIPTION
**Pull request by b14ckyy**
Documentation for the Geozones feature. Related to https://github.com/iNavFlight/inav-configurator/pull/2237

### CODE REVIEW

**Comment by stronnag** [comment]
Looking good. Can you add a CLI section as the user will need some of this, for example:
```
geozone_detection_distance = 50000
Allowed range: 0 - 1000000

geozone_avoid_altitude_range = 5000
Allowed range: 0 - 1000000

geozone_safe_altitude_distance = 1000
Allowed range: 0 - 10000

geozone_safehome_as_inclusive = OFF
Allowed values: OFF, ON

geozone_safehome_zone_action = NONE
Allowed values: NONE, AVOID, POS_HOLD, RTH

geozone_mr_stop_distance = 15000
Allowed range: 0 - 100000

geozone_no_way_home_action = RTH
Allowed values: RTH, EMRG_LAND
```

As well as the management commands:

```
geozone reset
geozone vertex reset

geozone id type shape minalt maxalt amsl action
geozone vertex zoneid vertexid latitude longitude
```

**Comment by b14ckyy** [comment]
Good point and for the "Additional Settings" I will add the CLI parameter names as well

**Comment by stronnag** [comment]
Your definition for `geozone` is obsolete, a altitude reference parameter has been added after `maxalt`
 0 = relative, 1 = AMSL
```
geozone id type shape minalt maxalt is_amsl action

```

**Comment by b14ckyy** [comment]
Thanks for that. in your example it misses: vertices count: 0-126 at the end. 
Should be correct in the doc now.

**Pull request merged**
