### PR TITLE
MSP VTX support

### PR DESCRIPTION
**Pull request by mmosca**
Add MSP VTX support

Based on BF's implementation.
Needs new firmware on HD-Zero VTX (hd-zero/hdzero-vtx/pull/141). The current shipping firmware limits MSP-VTX to Betaflight and QuickSilver.

Working: 
- Sends settings to VTX on start up
- Sends updates when triggered by ELRS
- Sends updates when using CMS to change settings
- Sends updates updates when low power state changes

TODO, probably on a follow up pr:
- Add vtx table to msp vtx, mainly for validating channel and power levels

If you would like to test this, just setup HDZero to use MSP DisplayPort as usual and disable Smart Audio.

### CODE REVIEW

**Comment by mmosca** [comment]
> Hi, first of all i would like to thank you for the time making this possible. i really appreciate it.
> 
> Changing channels and output power works like a charm when using the ELRS Lua (vtx admin).
> 
> i would like to change vtx settings using AUX channels but that doesnt seem to work yet, you can see the settings change in inav but the vtx doesn't change settings.
> 
> [INAV_7.0.0_cli_20230717_224710.txt](https://github.com/iNavFlight/inav/files/12073824/INAV_7.0.0_cli_20230717_224710.txt)
> 
> image

Can you check if it works now?

**Comment by sebas1984x** [comment]
> 

Yes, works like a charm.

**Comment by MartinHugh** [comment]
> Add MSP VTX support
> 
> Based on BF's implementation. Needs new firmware on HD-Zero VTX ([hd-zero/hdzero-vtx/pull/141](https://github.com/hd-zero/hdzero-vtx/pull/141)). The current shipping firmware limits MSP-VTX to Betaflight and QuickSilver.
> 
> Working:
> 
> * Sends settings to VTX on start up
> * Sends updates when triggered by ELRS
> * Sends updates when using CMS to change settings
> * Sends updates updates when low power state changes
> 
> TODO, probably on a follow up pr:
> 
> * Add vtx table to msp vtx, mainly for validating channel and power levels
> 
> If you would like to test this, just setup HDZero to use MSP DisplayPort as usual and disable Smart Audio.

@mmosca thank you for this contribution. Excellent news.

**Comment by MrMap** [comment]
Very happy to learn that MSP-VTX has been merged into the master branch. Acknowledgements and thanks to you guys who did this.

I would really like to test and use it with following setup:
SpeedyBee F405 Wing (currently Inav 6.1.1)
HD Zero Freestyle VTX (currently HDZ_Rev_22082023)
Running Edge TX 2.8.4 with latest ELRS. VTX backpack LUA works fine with HDZ goggles but unreliable with Smart Audio INAV/ VTX.

As I understand it (not being an advanced Github user) I would need to upgrade to current INAV master compiled for the SB F405 Wing target? How do I proceed to obtain this? (I have been reading github docs but still have no confidence in myself to succeed with target build.)

And then I should disable Smart Audio (by deselcting SA as peripheral on the dedicated FC UART port.
- After this, MSP-VTX should work? (with above mentioned HDZ VTX FW)

Any response / instructions referring to this would be much appreciated.

**Pull request merged**
