### PR TITLE
ibus_report_cell_voltage

### PR DESCRIPTION
**Pull request by mortilla**
For whose with flysky i6 radio with unmodded firmware

### CODE REVIEW

**Comment by shellixyz** [comment]
I think a bit in `ibus_telemetry_type` could be used instead of a new setting.

**Comment by mortilla** [comment]
Agreed. Sorry, I'm new to that github thing. I need to commit to my branch I made this request from?

**Comment by shellixyz** [comment]
No problem. You can either make a new commit to the same branch and push it will be automatically added to this PR or you can amend your last commit and force push to keep the changes to one commit like this:

```
<make changes>
git add <files>
git commit --amend
git push --force
```

**Comment by fiam** [comment]
We should probably use the report_cell_voltage setting that I introduced in the fport PR. My idea renaming it from frsky_vfas_cell_voltage was to have a single setting for all protocols.

**Comment by mortilla** [comment]
I think I made a mess trying to resolve conflict. Also, I added a little extra voltage to cellMax when autodetecting cells number because it was detecting wrong on freshly charged batteries.

**Comment by shellixyz** [comment]
@mortilla Unless you are using HV batteries (or overcharging standard LiPo) you should not touch the cell max voltage but instead calibrate the voltage measurement with the "voltage scale" setting (`vbat_scale` in the CLI).

**Pull request closed without merging**
