### PR TITLE
Added S5 and S6 motor/servo to FIREWORKSV2 and variants

### PR DESCRIPTION
**Pull request by asizon**
Referenced to https://github.com/iNavFlight/inav/issues/4421, now this target is abble to use motor or servo on S5/S6 PIN for Airplane.

### CODE REVIEW

**Comment by asizon** [comment]
Are you agree @CRISTSC ??

**Comment by CRISTSC** [comment]
works with Omnibus F4 V6 pinout for 1-2 motors, 4 servos airplane and 3- 6 motors multi-rotor.

**Comment by asizon** [comment]
What happened with Travis? the build is correct, not errors show on my travis, please rebuild, branch Development is correct?

**Comment by asizon** [comment]
Any reviewer or admin can rebuild Travis build forrnthis PR to test it? Thanks!

**Comment by shellixyz** [comment]
You will have to force push a change to restart Travis. Add a space somewhere then amend your last commit and force push.

**Comment by asizon** [comment]
okey @shellixyz , commited and squashed to 1 commit. Waiting for Travis to be happy

**Comment by asizon** [comment]
Done!Ready for merge!

**Pull request merged**
