### PR TITLE
Fixed-wing motor mixer improvements

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes for #1052 and https://github.com/iNavFlight/inav/issues/933

### CODE REVIEW

**Comment by oleost** [comment]
@digitalentity How does this work exactly?

If using normal airplane or fixedwing mixer with dual motor, is this going to force differential thrust mixing?

Or does one need to use an custom mixer with differential thrust mixed in, and then the same ratio is mixed in during passthrough aswell?

**Comment by digitalentity** [comment]
No, it just makes both motor outputs functional and passes throttle though to both of them. Differential thrust will still require custom mixing, but this at least will allow effortless setup for twin-motor configurations.

**Comment by digitalentity** [comment]
In passthrough RPY input is passed to motor mixer as well instead of PID output so it's now possible to mix yaw into twin-motor setups in passthrough mode as well if one so desires.

**Comment by Ralf-W** [comment]
Sorry, what does RPY stand for?

**Comment by stronnag** [comment]
roll, pitch, yaw

**Comment by Ralf-W** [comment]
Ouch. Thank you!

**Pull request merged**
