### PR TITLE
Smartaudio 2.1 support

### PR DESCRIPTION
**Pull request by Scavanger**
For lack of time, thanks to corona, here only a basic implementation of Smartaudio 2.1.

The extended configuration (pit at start, pit out range mode, pit frequency) will be done via CLI in the future, but I need more time for that.

### CODE REVIEW

**Comment by DzikuVx** [comment]
Amazing! Too bad I have no SA21 hardware to test it

**Comment by digitalentity** [comment]
Cool, thanks @Scavanger! I'll review today/tomorrow!

**Comment by Jetrell** [comment]
@digitalentity 
I have a Unify Pro 5G8 HV race edition v2.0, that has SA2.1
If you can give me a hex for - MATEKF411_FD_SFTSRL   
I can test it as well.

**Comment by Scavanger** [comment]
@Jetrell

No, your VTX is a Smartaudio 2.0 Device.
I own the same.

**Comment by Jetrell** [comment]
> No, your VTX is a Smartaudio 2.0 Device.
> I own the same.

@Scavanger  This is a picture of it. It won't work with SA2.0. And most web sites say it SA2.1. So I just assumed it is?


Unify

**Comment by Scavanger** [comment]
Oh sorry, I overlooked "v 2. 0".
Yes this is a 2.1 device.

**Comment by Scavanger** [comment]
@Jetrell:
Go to the "Checks" tab and click on "Artifacts", in the zip file you will find compiled hex files for your FC.

I noticed very late that the OMNIBUS has a flash overflow because the previous checks failed when installing the ARM toolchain?!?

**Comment by Jetrell** [comment]
Issues with level change using Global Function with both Smart Audio and Tramp.

#5731

**Comment by digitalentity** [comment]
@Jetrell please move this bug report to a separate issue, it's unrelated to this PR and will likely fall through the cracks if we don't track it separately.

**Review by digitalentity — APPROVED** [review]

**Pull request merged**
