### PR TITLE
I2C bus drivers rework

### PR DESCRIPTION
**Pull request by digitalentity**
Preparation for asynchronous bus access (#619).

ST's RM0008 (F103):
http://www.st.com/content/ccc/resource/technical/document/reference_manual/59/b9/ba/7f/11/af/43/d5/CD00171190.pdf/files/CD00171190.pdf/jcr:content/translations/en.CD00171190.pdf

ST's RM0316 (F303)
http://www.st.com/content/ccc/resource/technical/document/reference_manual/4a/19/6e/18/9d/92/43/32/DM00043574.pdf/files/DM00043574.pdf/jcr:content/translations/en.DM00043574.pdf

ST's RM0090 (F405)
http://www.st.com/content/ccc/resource/technical/document/reference_manual/3d/6d/5a/66/b4/99/40/d4/DM00031020.pdf/files/DM00031020.pdf/jcr:content/translations/en.DM00031020.pdf

- [x] F1 I2C driver
- [x] F3 I2C driver
- [x] F4 I2C driver

### CODE REVIEW

**Comment by digitalentity** [comment]
Phew! This was one hell of a challange. F1 and F4 drivers should be the same, but I didn't test the new code.

This code doesn't use busy-waiting in I2C processing and is much more readable that previous implementation. State machine for F1 I2C driver is now ready to be used asynchronously and will fit nicely in #619 infrastructure.

**Comment by martinbudden** [comment]
Well, I've only given it a cursory glance, but the code is much more readable. And use of a proper state machine is welcome.

**Comment by digitalentity** [comment]
Looks like the new code handles bus timeouts and resets the bus correctly now (https://github.com/iNavFlight/inav/issues/724#issuecomment-264304997)

I think I'll try to put some more effort here and we'll release it in 1.5.

**Comment by jflyper** [comment]
Finally!

**Comment by digitalentity** [comment]
Done for F3 boards, tested and working. Able to correctly recover even from shorted SCL/SDA/GND.

**Comment by digitalentity** [comment]
I don't think SoftI2C will benefit much from refactoring or being asynchronous. It's software, so it's blocking anyway.

**Comment by digitalentity** [comment]
Doesn't work on NAZE

**Comment by digitalentity** [comment]
Took me over 2 hours to figure out a memory corruption bug (which I did myself). Argh!

**Comment by stronnag** [comment]
Probably explains some hairy moments testing yesterday.

**Comment by digitalentity** [comment]
@stronnag probably you are right. I was lucky to notice because NAZE was just hanging up split-second after booting.

**Comment by digitalentity** [comment]
Bench-testing:

NAZE - check
SPRACINGF3 - check
AIRBOTF4 - check
REVO - check
QUANTON - check

**Pull request merged**
