### PR TITLE
Enable DSHOT on OmnibusF4 and ASGARD boards

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by teckel12** [comment]
@digitalentity Are there still issues with the F7 and DSHOT?

**Comment by digitalentity** [comment]
@teckel12 still requires testing.

**Comment by ABLomas** [comment]
Tested today on OMNIBUS F4 + DSHOT600 (tattoo 25A blheli_32 ESC, quad) - no issues, no problems, no unexpected arm/disarm, looks good to me.

**Comment by teckel12** [comment]
@digitalentity I have an F722 to test. Will try it out by the end of this weekend and let you know.

**Comment by digitalentity** [comment]
Blocked by #4128

**Pull request merged**
