### PR TITLE
Various state cleanups, mainly FIXED_WING

### PR DESCRIPTION
**Pull request by DzikuVx**
* remove state HELICOPTER as not used
* replace STATE FIXED_WING with `mixerConfig()->platformType`

### CODE REVIEW

**Review by fiam — COMMENTED** [review]
What if we added an inline function like platformIsAirplane() to replace the explicit checks? I think the == PLATFORM... and != PlATFORM... checks are a bit too difficult to read.

**Comment by DzikuVx** [comment]
@fiam This is a "phase one". I intend to create a set of platform properties with getters. For example:
`hasAltitudeControl()` that returns NONE, ALTITUDE_CONTROL_AIRPLANE, ALTITUDE_CONTROL_MC or something like that

**Comment by DzikuVx** [comment]
because indeed some of those checks are nighmarish

**Comment by digitalentity** [comment]
Most changes for `!STATE(FIXED_WING)` are actually about being a rotorcraft (MC, Tri or Heli). Some are completely irrelevant for boat or rover.

I suggest we create functions like these:
`platformIsWingedAircraft()`
`platformIsRotorcraft()`
`platformIsRoverOrBoat()`

**Comment by DzikuVx** [comment]
Yes @digitalentity this is my ultimate goal from the beginning. I wanted to do it as a next step

**Comment by flybabo** [comment]
I suggest deprecating all the global FIXED_WING and HELICOPTER state bit usages.
I started working on a VTOL transitional mixer which requires multiple (at least two) mixer profiles.
(array of mixers and mixer configs)
During a transition from the hover mode (MULTIROTOR) to forward flight mode (FIXED_WING), the main pid loop needs to compute two independent pid/mix outputs (one for MR and another for FW) and store them on temporal (virtual) motor/servo value arrays and then a transitional mixer computes actual motor/servo values from those temporal values and write them to corresponding physical motors/servos.  Once the transition is completed, just one mixer output will be computed.
In order to do this, I need to remove all the flying platform specific global variables and associate them to corresponding mixer config/profile.
I'm also working on the better output mapping for VTOL airframe which needs more flexible motor/servo assignment by utilizing all the usable timer channels without conflicting.
For an example, I need to use unused PPM/RSSI timers on OMNIBUSF4 and to support multiple servo pwm rates for my test VTOL airframe having 3 motors, two tilt rotor digital servos, two elevon analog servos and may be another servo for the rudder.
There're many more things to support PLATFORM_MULTIMIX (aka VTOL).
IMHO, clean implementation of the multiple mixer/pid profiles is the first thing to do and then we can put necessary things in an incremental manner.

**Comment by junwoo091400** [comment]
@flybabo Wow, looks like you took a deep dive into the code :) Awesome Suggestion!

**Comment by DzikuVx** [comment]
I'm closing this one and will break it into smaller pieces later

**Pull request closed without merging**
