### PR TITLE
OMNIBUSF4* Add OLED_I2C_INSTANCE to activate dashboard

### PR DESCRIPTION
**Pull request by jflyper**

### CODE REVIEW

**Comment by digitalentity** [comment]
Maybe a proper way would be to change OLED driver to use busDevice API?

**Comment by jflyper** [comment]
That's something different. OMNIBUSF4* targets just don't define `OLED_I2C_INSTANCE` and the driver defaults to `I2CDEV_1`.

**Comment by jflyper** [comment]
I'll do the busDevice API conversion when BF3.3 gets to late RC phase.

**Comment by digitalentity** [comment]
@jflyper Ah, I see. Merging then.

**Pull request merged**
