### PR TITLE
[fc/fc_msp_box.c] Remove uncompiled line

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
this part of the algorithm is never compiled, because the `USE_FLM_FLAPERON` definition doesn't exist... but the FLAPERON mode is active in fc_core.c

### CODE REVIEW

**Review by DzikuVx — CHANGES_REQUESTED** [review]
@JulioCesarMatias I think it's actually the other way around. This line should be compiled and it's currently missing

**Comment by MrD-RC** [comment]
I checked my work from when I remove the flaps toggle from configurator, and can confirm that was configurator side only. https://github.com/iNavFlight/inav-configurator/pull/1423 So I didn't remove anything 😆 

I think you're right though @DzikuVx. The functionality should be added. The situation could arise where the flaperons mode is set up, the mixer is changed to one that does not support flaperons, but the mode is still assigned to a switch.

**Comment by JulioCesarMatias** [comment]
@DzikuVx @MrD-RC  Done! Do a review

**Comment by MrD-RC** [comment]
I think it's more that `USE_FLM_FLAPERON` needs to be working. Not that the `usedef` should be removed.

**Review by DzikuVx — APPROVED** [review]

**Review by MrD-RC — APPROVED** [review]

**Pull request merged**
