### PR TITLE
Mark IFLIGHT_BLITZ_F7_AIO as SKIP_RELEASES

### PR DESCRIPTION
**Pull request by mmosca**
Since this is an unofficial target, mark it as SKIP_RELEASES

### CODE REVIEW

**Comment by wchnflr** [comment]
I don't have this FC, but got two Reddit requests to build it for people to try it out, so I attached a file built in Inav 7.1.2.
[inav_7.1.2_IFLIGHT_BLITZ_F7_AIO.zip](https://github.com/user-attachments/files/16095180/inav_7.1.2_IFLIGHT_BLITZ_F7_AIO.zip)

**Comment by Gurkengewuerz** [comment]
I am also using your release @wchnflr 
So thank you

**Comment by cspro1** [comment]
> I am also using your release @wchnflr So thank you

I am trying to use this for an IFLIGHT_F745_AIO (the BF target) is this the same board you are using it on? When I flashed it I dont see a gyro, accel or baro, nor can I enable it by any means.

**Comment by wchnflr** [comment]
> I am trying to use this for an IFLIGHT_F745_AIO (the BF target) is this the same board you are using it on? When I flashed it I dont see a gyro, accel or baro, nor can I enable it by any means.

Does your Inav configurator show this screen?
image

I don't have the iFlight FC so I'm showing a screen from my Flywoo FC.

**Comment by cspro1** [comment]
> > I am trying to use this for an IFLIGHT_F745_AIO (the BF target) is this the same board you are using it on? When I flashed it I dont see a gyro, accel or baro, nor can I enable it by any means.
> 
> Does your Inav configurator show this screen? image
> 
> I don't have the iFlight FC so I'm showing a screen from my Flywoo FC.

Yes, It just says none for each of those. It was my understanding that the zip folder was for the iflight beast f7 V1, what came in the very first Protek 35 before they came out with the Beast V2 which had SCL/SDA ports. The V1 did not. The Gyro should be Mpu6000 and the baro a DPS310. If my understanding on the specs is right.

**Comment by cspro1** [comment]
> > > I am trying to use this for an IFLIGHT_F745_AIO (the BF target) is this the same board you are using it on? When I flashed it I dont see a gyro, accel or baro, nor can I enable it by any means.
> > 
> > 
> > Does your Inav configurator show this screen? image
> > I don't have the iFlight FC so I'm showing a screen from my Flywoo FC.
> 
> Yes, It just says none for each of those. It was my understanding that the zip folder was for the iflight beast f7 V1, what came in the very first Protek 35 before they came out with the Beast V2 which had SCL/SDA ports. The V1 did not. The Gyro should be Mpu6000 and the baro a DPS310. If my understanding on the specs is right.

image

**Comment by cspro1** [comment]
> > > > I am trying to use this for an IFLIGHT_F745_AIO (the BF target) is this the same board you are using it on? When I flashed it I dont see a gyro, accel or baro, nor can I enable it by any means.
> > > 
> > > 
> > > Does your Inav configurator show this screen? image
> > > I don't have the iFlight FC so I'm showing a screen from my Flywoo FC.
> > 
> > 
> > Yes, It just says none for each of those. It was my understanding that the zip folder was for the iflight beast f7 V1, what came in the very first Protek 35 before they came out with the Beast V2 which had SCL/SDA ports. The V1 did not. The Gyro should be Mpu6000 and the baro a DPS310. If my understanding on the specs is right.
> 
> image

Thats Basically what i have this in. It was a Protek 35 which has GPS and a Baro. Currently it runs BF but id really like to run Inav for the flight modes.

**Comment by mmosca** [comment]
What gyro do you have? The unofficial (and unsupported) target works on my quad. Since iflight did not work with inav, we have no way to know if they decided to change the target in any way. My flight controller is the beast one shown above.

Either way, this pull request is the wrong place to discuss this. Either open an issue or a discussion instead.

**Comment by wchnflr** [comment]
I got a new request to build it for Inav 8.0.0-RC3:
[inav_8.0.0-RC3_IFLIGHT_BLITZ_F7_AIO.zip](https://github.com/user-attachments/files/18325839/inav_8.0.0-RC3_IFLIGHT_BLITZ_F7_AIO.zip)

**Comment by benderl** [comment]
Just for completeness: here is a build with the latest 8.0.0 release.
[inav_8.0.0_IFLIGHT_BLITZ_F7_AIO.zip](https://github.com/user-attachments/files/18523199/inav_8.0.0_IFLIGHT_BLITZ_F7_AIO.zip)

**Pull request merged**
