### PR TITLE
Changed default value from 1 to 0. use_thr_mid_for_althold = 0

### PR DESCRIPTION
**Pull request by oleost**
#221

Unsure if this is the correct way? Still trying to learn.

### CODE REVIEW

**Comment by theArchLadder** [comment]
Yay, another one trying to help coding! :smiley: 
Looks right to me. You can always build your branch to check that there are no build errors. Then flash it and see that everything works as expected, in this case check that default is OFF.

@digitalentity Do you think an issue was necessary in this case, or would it have been enough with just the pull request?

**Comment by oleost** [comment]
@theArchLadder Yes, I'm wondering to buy an FC just for testing. Currently I only got one in my plane(Which is big to drag to the computer all the time), and another one in my quad with a broken USB connector(Hate connecting up my FTID adapter)

**Comment by sppnk** [comment]
@oleost , I guess the FCs are flashables through bluetooth. Not tested myself, but you could get rid of cables. I have a BT adapter in every plane and I connect always from computer or tablet.

**Comment by theArchLadder** [comment]
@sppnk how do you power them? I don't want to connect my flight battery and power up my ESC, that feels unsafe. If i need to connect some power cable i could just as well use USB and skip the bluetooth...

**Comment by sppnk** [comment]
@theArchLadder , I power bt adapters from the +5V pin of USART1 (cc3d). In  afronaze is the same. That +5V is the main 5V 'bus' and comes from an 3A UBEC, (my ESC doesn`t supply ), I guess is the same in all the FCs .

**Comment by theArchLadder** [comment]
@sppnk So you plug in your main flight battery, and the ESC are powered up? That does not sound safe to me...

**Comment by sppnk** [comment]
Yes, mi only ESC (is a plane) is powered up. But I am talking about connecting at flying field or in my desk to tweak parameters, not flashing. If so, I remove prop.

**Pull request merged**
