### PR TITLE
Allow Logic Conditions to override RC channels

### PR DESCRIPTION
**Pull request by DzikuVx**
replaces #5627

### CODE REVIEW

**Comment by avsaase** [comment]
I noticed there already is a `SET RC CHANNEL` logic condition in the configurator. Did that slip in by mistake?

**Comment by DzikuVx** [comment]
@avsaase it's `SET VTX CHANNEL` not RC Channel

**Comment by avsaase** [comment]
Using the 2.6 release:
2020-12-26 22_44_43-INAV Configurator

**Comment by avsaase** [comment]
There at a bunch of questions on RCG and FB about this. To be clear, overriding RC channels is not yet supported in 2.6 right?

**Comment by DzikuVx** [comment]
@avsaase No it is not in 2.6 I think I will merge this code after extra series of tests and adding a HUGE disclaimer that overriding RC channel can cause crash or injury

**Comment by avsaase** [comment]
Okay then something must have gone wrong when the configurator was build because I've seen multiple posts from people trying to get this to work.

**Comment by cpnmercury** [comment]
hey Pawel, hope your leg is getting better.
Wondering if this code i merged in the latest nightly? Would like it to overide a RC channel on a MR, have a servo on it for camera tilt. But I can't get it to override the channel

**Comment by DzikuVx** [comment]
@cpnmercury we do not release official nightlies. If you, however, build from `master` it will be there

**Comment by stronnag** [comment]
> hey Pawel, hope your leg is getting better.
> Wondering if this code i merged in the latest nightly? Would like it to overide a RC channel on a MR, have a servo on it for camera tilt. But I can't get it to override the channel

> @cpnmercury we do not release official nightlies. If you, however, build from `master` it will be there

Unofficially, E&OE etc. http://seyrsnys.myzen.co.uk/inav_dev/

**Pull request merged**
