### PR TITLE
Disarm stats pages auto swap on first display

### PR DESCRIPTION
**Pull request by breadoven**
PR adds a routine to initially auto swap stats pages on a 2 second cycle which continues until the roll stick is used which cancels the auto swap reverting to manual control of page selection.

### CODE REVIEW

**Comment by avsaase** [comment]
Why first page 2 though?

**Comment by breadoven** [comment]
> Why first page 2 though?

So it ends up on page 1 by the time people end up actually looking at it I guess. Doesn't really matter, both pages have the same layout, the page number is largely irrelevant but you expect it start on 1 so that's where it ends up 2s after disarming. I did have it starting on 1 then swapping to 2 then back to 1 but this method is simpler.

**Comment by avsaase** [comment]
Sorry, this makes no sense to me. Can't we just let it show page 1 first, and every x seconds switch page if the roll stick is not used to switch pages manually?

**Comment by breadoven** [comment]
> Sorry, this makes no sense to me. I look at the stats immediately on disarm. Can't we just let it show page 1 first, and every x seconds switch page if the roll stick is not used to switch pages manually?

The main purpose of this from my point of view is simply to ensure that a DVR recording captures both pages as quickly as possible after disarming without otherwise changing the basic way it works now, so just one page swap when the stats are first shown.

It could be changed to cycle repeatedly but it would need to keep a short cycle time in order for it to be useful for its primary purpose, DVRs, unless you extended the time after the first swap ... but then it all starts getting too complicated for something that is supposed to be a simple fix. It could also of course start on page 1 and end on page 2, but 2s isn't much time to take in the page 1 info. Or the 2s could be reduced, just needs to be long enough to make freeze framing easy on playback, 1s would probably be OK. Is 1s too long to wait for page 1 to appear ?

**Comment by avsaase** [comment]
I've had the same problem where I forgot to record both pages so I understand what you're trying to achieve. But having a noticable page switch after 1-2 seconds would look like a bug to me. If it's just about getting a still from the dvr, how about reducing the time to 50ms? At 25fps PAL recording that should guarantee at one frame of the second page, while not drawing much attention.

**Comment by breadoven** [comment]
You're right about it looking like a bug perhaps, although obviously it could be mentioned in documentation (if there is any) so I'll change it to cycle constantly until the stick is used to stop it at which point it'll default to page 1. Should be a simple change using an existing method.

Thanks for the feedback anyway.

**Comment by breadoven** [comment]
Actually seems fine with a 2s cycle time. And it ends up on the page corresponding to the roll direction used to stop the auto swapping.

**Comment by OptimusTi** [comment]
Tested it and it's working great. I can send you a PR with "time in seconds" settings. 2 seconds is good but a bit fast for old, tired eyes. I propose a time setting from 2 to 10 seconds.

image

**Comment by breadoven** [comment]
Oh no ... not more settings surely ? :grin:

A setting could be added but is it not easier to just nudge the roll stick to stop it swapping ? You've got to do that anyway to see the other page.

**Comment by OptimusTi** [comment]
Just suggesting the possibility of a longer page time, not to stop the swapping. Set and forget setting. 2 seconds is very convenient when comparing stats, newbies, spectators, or tired eyes.

**Comment by breadoven** [comment]
Can you send the time setting PR @OptimusTi and I'll include it. As you say ... set and forget as suits.

**Comment by OptimusTi** [comment]
Oops! I sent it. You didn't get it?

**Comment by breadoven** [comment]
Where would it have gone ? My email or on Github somewhere ?

**Comment by OptimusTi** [comment]
Github. Sent to your branch. If not I'll try again in a couple of hours

**Comment by breadoven** [comment]
Don't worry about it @OptimusTi I did it myself in the end. Will up date the PR in a while.

**Comment by OptimusTi** [comment]
Cool thanks! Sorry, stuck at work.

**Comment by OptimusTi** [comment]
How about this? In case someone wants to change the value at the field. one line of code.

https://user-images.githubusercontent.com/45466510/116762877-d6bb3800-a9e9-11eb-8337-75248add0431.mov

**Comment by OptimusTi** [comment]
Looks like this got left behind. Can we get a review and add cms option? @avsaase @breadoven

**Comment by Jetrell** [comment]
> 
> 
> Looks like this got left behind. 

Any chance of this being added?  I so often forget to toggle the stick and record both stats pages, before I turn off the DVR :-(

**Comment by OptimusTi** [comment]
> How about this? In case someone wants to change the value at the field. one line of code.
> 
> 
> 
> https://user-images.githubusercontent.com/45466510/116762877-d6bb3800-a9e9-11eb-8337-75248add0431.mov
> 
> 
> 
> adding this to line 51 in src\main\cms\cms_menu_misc.c gives you the menu:
> 
> 
> 
> OSD_SETTING_ENTRY("STATS PAGE TIME", SETTING_OSD_STATS_PAGE_AUTO_SWAP_TIME),

This too. :)

**Comment by avsaase** [comment]
What's the current working of this PR? It starts on page 2 and after `osd_stats_page_auto_swap_time` seconds it switches to page 1 and stays there?

**Comment by breadoven** [comment]
No, that was the first version. It now cycles between the 2 pages continuously until you use the roll stick at which point it stops auto cycling and reverts to manual control with the roll stick (as now).

**Comment by avsaase** [comment]
Okay, that makes sense if it starts on page 1. Let's also add the option to set `osd_stats_page_auto_swap_time` to zero meaning it will never auto swap.

**Comment by OptimusTi** [comment]
I'd make it auto swap a default like it is now.

**Comment by avsaase** [comment]
I'd prefer a longer auto swap time, like 5 seconds. But regardless of defaults, it would be nice to be able to disable auto swapping altogether.

**Comment by OptimusTi** [comment]
> I'd prefer a longer auto swap time, like 5 seconds. But regardless of defaults, it would be nice to be able to disable auto swapping altogether.

Agreed. I guess BO needs to change "Min" to 0 add CMS line

**Comment by breadoven** [comment]
Fails Git tests with the CMS entry added even though it's fine when compiled locally. Not sure what the issue is.

**Comment by breadoven** [comment]
OK, all fixed. Set time to 0 to disable. CMS entry added to Misc menu.

**Comment by OptimusTi** [comment]
Looks like this got overlooked and conflicts were not resolved...

**Comment by Jetrell** [comment]
@breadoven thanks for the commits. I look forward to seeing this feature added.

**Comment by avsaase** [comment]
@breadoven Ready to merge?

**Pull request merged**
