### PR TITLE
Move parameters from profile to master

### PR DESCRIPTION
**Pull request by sambas**
Addresses this https://github.com/iNavFlight/inav/issues/950

### CODE REVIEW

**Comment by digitalentity** [comment]
Looks good. 
@martinbudden what's your oppinion on this?

**Comment by martinbudden** [comment]
@digitalentity , looks good to me. I've always thought there is too much stuff in the profiles.

Let's get this merged in now, since it's better to get these in before starting the conversion to parameter groups.

**Comment by digitalentity** [comment]
I'll try to test it as soon as possible and merge.

**Review by digitalentity — APPROVED** [review]

**Comment by martinbudden** [comment]
OK, merging

**Pull request merged**
