### PR TITLE
Add SKYSTARSF722HD target

### PR DESCRIPTION
**Pull request by shellixyz**

### CODE REVIEW

**Comment by shellixyz** [comment]
@DzikuVx Perhaps we could merge this in the 5.0 branch instead of master so that it is available for the next 5.0 release ? It's just a new target.

**Comment by DzikuVx** [comment]
@shellixyz please rebase on `release`, we have too many commits now

**Comment by erstec** [comment]
@shellixyz @DzikuVx 

https://github.com/iNavFlight/inav/blob/39e58e3f1e150a852241f1170a3e2ad5b7218487/src/main/target/SKYSTARSF722HD/target.h#L20
https://github.com/iNavFlight/inav/blob/39e58e3f1e150a852241f1170a3e2ad5b7218487/src/main/target/SKYSTARSF722HD/target.h#L22

It should be F722 or like that, if target name is correct

**Comment by shellixyz** [comment]
Ah crap yeah I took the F405HD as template and forgot to chabge the name

**Pull request merged**
