### PR TITLE
BF Software Serial Port

### PR DESCRIPTION
**Pull request by jflyper**
PR status: Need review and testing

Port of BF Software Serial to iNav.

New features
- Capable of handling single-wire half-duplex using TX.
- TX and RX can be on different timers, and in which case true full-duplex is provided. In legacy softserial which used two channels of the same timer, active transmission was clobbered when a first edge of a new character is detected.
- Simplex configuration is allowed (TX only or RX only) as long as a user use the port in the configured way.

### CODE REVIEW

**Comment by stronnag** [comment]
@digitalentity ignore me, misclick.

**Comment by digitalentity** [comment]
@stronnag no, you just reminded me that I was going to review it anyhow :smile:

**Comment by jflyper** [comment]
Okay, it's working. Need some testing, though.

**Comment by stronnag** [comment]
Looking good on my F1 test board (development head + 2346.diff). Some packet loss at 9600 baud (polling MSP); with the standard implementation, I'd see significantly more packet loss (probably twice as much). @giacomo892 , @Schalonsus might be interested in trying this (apropos #2139). No packet loss with LTM. Definitely an improvement.

**Comment by giacomo892** [comment]
I stuffed it into my F1 board too! I'd say it is an improvement! Seems more responsive!

@stronnag have you tried opening configurator motors tab at 9600? It gets stucks even in wireless mode. The great thing is that now you can switch tab and it responds!

**Comment by stronnag** [comment]
@giacomo892, I did not, because I don't see it as a valid / useful use case for SS.

**Comment by giacomo892** [comment]
I spoke too early. Leaving open also the sensors tab in wireless mode after some time crashes the board. 
We can live with this, but should not happen.

**Comment by stronnag** [comment]
Or you could develop some reasonable expectations for softserial on obsolete processors.

**Comment by giacomo892** [comment]
I think it's not due to the processor speed but I have the suspect there is something wrong in the implementation. I think I have to surrender since I won't get any new/better one near soon.

**Comment by jflyper** [comment]
Does the FC wedging occurs when running MSP over SS?

I haven't looked deep into the output portion of the MSP yet, but I would suspect this is due to MSP trying to output lots more than what the low bandwidth can pump out; large output may be waiting for room in output queue. My hunch is that dropping outputs when queue is full at io level should help, but this is a big decision.

**Comment by jflyper** [comment]
@stronnag 
Packet loss is expected if both RX and TX are different channels on the same timer.
As noted in the first comment, active transmission is clobbered whenever the first edge of a new reception is detected.

This is a limitation of the current SS implementation, which uses a common counter for pacing transmission and reception intervals. When the first edge of the reception is detected, counter is set to half the clock period to capture input level at mid-periods. If transmitter was using the counter to pace output intervals, then the counter manipulation would break the transmission interval.

**Comment by teckel12** [comment]
Is this in the current development build?

**Comment by jflyper** [comment]
@teckel12 Not yet. Wanna give it a try? If you don't have a build environment, I'll make a test firmware for you. What is your FC?

**Comment by digitalentity** [comment]
Let's merge this to 1.9 - SS is used quite frequently and I don't want to deal with possible bugs in the very late of 1.8 cycle :smile:

**Comment by stronnag** [comment]
The MSP example is entirely half-duplex, in accordance with the serial challenge - response specification of MSP.

**Comment by giacomo892** [comment]
@jflyper Yes. MSP with large outputs cause wedges. Like the motor tab and sensors tab are known to send of big packets. Then the FC may get a new request before it sent out the reply trashing everything expecially at low baud rate like 9600 as I am using.

**Comment by jflyper** [comment]
@stronnag 
> The MSP example is entirely half-duplex, in accordance with the serial challenge - response specification of MSP.

Ah, you are correct in terms of protocol specification (request-response).

So, there must be something that is preventing 9600bps MSP to wedge...

How about this theory? FC is trying to output a huge output, say 256bytes, pumping out at 9600bps taking 26msec that fail to be in time for configurator's timeout?

**Comment by stronnag** [comment]
In my use case, which is not the configurator, the application performs the following: 

One off set of MSP_IDENT, MSP_API_VERSION, MSP_BOARD_INFO, MSP_FC_VARIANT, MSP_FC_VERSION, MSP_BUILD_INFO, MSP_BOXNAMES, MSP_MISC, MSP_WP_GETINFO, MSPV2_RTC, MSPV2_COMMNON_SETTINGS, MSP_STATUS_EX (to establish FC characteristics). These are all small; the BOXNAMES response is large (c. 200 bytes).

Then a continuous (repeating) cycle of MSP_STATUS_EX, MSP_ANALOG, MSP_RAW_GPS, MSP_COMP_GPS. MSP_ATTITUDE, MSP_ALTITUDE, MSP_NAV_STATUS. All these are small with small responses.  The "no response" timeouts occur in this phase, somewhat randomly, which with a bias towards MSP_COMP_GPS and MSP_NAV_STATUS, and recovery on retry.

Everything is strictly request-response, with never more than one message 'in flight' (slow, but resiliant to dropout).

**Comment by teckel12** [comment]
@jflyper Just to clarify, MSP works with 1.7.3 over soft serial.  I can do a build of this branch tonight and test to make sure it still works.  I'm using a modified Betaflight Lua script to adjust PIDs from my Q X7 over S.Port/MSP.

**Comment by jflyper** [comment]
@stronnag That sounds like what OSD does. If that's the case, which OSD is that?

**Comment by stronnag** [comment]
https://github.com/stronnag/mwptools (a ground station / mission planner)

**Comment by stronnag** [comment]
@teckel12 1.7.3 SS 'works' in that on F1, it performs less well than this PR achieves, by a factor of about 2 if lost messages is your measure,

**Comment by teckel12** [comment]
@stronnag I'm just saying that SS currently works with 1.7.3, and even working with MSP.  I can test this branch and verify everything still works.  In other words, it doesn't matter how fast it is if it doesn't work.

**Comment by stronnag** [comment]
Whatever; what the rest of of us involved in this discussion and #2139 have *tested* is that on F1, SS will at best lose data. On 1.7.3, it loses more data and may lock up the FC; with this patch it loses less.  No one is disputing that on better processors, it probably works.

**Comment by jflyper** [comment]
@teckel12 Are you going to test S.Port?

**Comment by teckel12** [comment]
@stronnag I think you're missing my point.  Dropping fewer packets but breaking something else that's currently working (like MSP) would be a step back.  What I'm testing is probably something that others have NOT tested.  I see no mention of the betaflight PID Lua telemetry script in this conversation.  Also, isn't F1 support being dropped anyway?  Whatever, I'll test this branch and let you know my results.

@jflyper I'll be testing S.Port MSP over SS (with this branch).  I know it works on 1.7.3, so my goal is to make sure MSP still works with the new SS branch (as I just got MSP over S.Port working with 1.7.3).

**Comment by jflyper** [comment]
> I'll be testing S.Port MSP over SS (with this branch). I know it works on 1.7.3, so my goal is to make sure MSP still works with the new SS branch (as I just got MSP over S.Port working with 1.7.3).

In addition to the setup that bridges TX to RX in some way, the BF SS works only with TX, in which case you have to `set smartport_uart_unidir = OFF`, which is the default.

**Comment by teckel12** [comment]
@jflyper @stronnag I tested this branch with MSP over S.Port and it works perfectly without any issues.  Telemetry was also rock-solid.  I'm running F4 so I can't comment on any reductions in lost messages as it all worked 100% perfectly.

**Comment by kabturek** [comment]
does that mean that it will be possible to run SoftwareSerial on TX to run S.port telemetry to free up a the RX pin that is usually used for SS ? (thinking about Omnibus F4 pro that has  led on pwm5 and softwareserial on pwm5/pwm6)

**Comment by jflyper** [comment]
@kabturek 

Yes and no.

> does that mean that it will be possible to run SoftwareSerial on TX to run S.port telemetry to free up a the RX pin that is usually used for SS ?

Yes.

BF is going far beyond; softserials can be run on arbitral combination (or any one of) valid timer entry, even on ones that are backdoor timers on UART pads.

See following pics to get some idea.
https://www.rcgroups.com/forums/showthread.php?2960425-ASGARD-V2-Wiring-Worksheet-and-Examples
https://www.rcgroups.com/forums/showthread.php?2949247-OMNIBUS-F4-Pro-Corners-Configuration-Example

> (thinking about Omnibus F4 pro that has led on pwm5 and softwareserial on pwm5/pwm6)

Unfortunately, Omnibus F4 variants' softserial is on CH5 and CH6 (they are called PWM5 and 6 in source code, but these are not directly related with  PWM5 and 6 pad/TH labels; they used be PWM input channels.

**Comment by teckel12** [comment]
@kabturek On the Omnibus F4 Pro and INAV v1.8 the LED pin moves from PWM5 to the LED strip port (J1).  The soft serial isn't on PWM5, it's on CH5/CH6 which are two surface pads between the microcontroller and motor VCC pad. Here's a pic of the CH5/CH6 pads (note, this is for pre-v1.8 for the LED pin):

Omnibus F4 Pro

**Comment by teckel12** [comment]
I wanted to add that I've been flying for the last week with the changes from this pull request without issue. And I use soft serial extensively for telemetry.

**Comment by jflyper** [comment]
@teckel12 Thanks for testing and the report!

**Comment by stronnag** [comment]
Any reason not to merge this now? Expose in `development` would get it more tested.

**Comment by giacomo892** [comment]
I've being flying it since it is here and it is working. No reasons not to merge.

**Comment by teckel12** [comment]
Not flying with it now but did for a few weeks with zero problems.  I say merge.

**Pull request merged**
