### PR TITLE
"Fix" MSP stuck when used on low speed over SS

### PR DESCRIPTION
**Pull request by giacomo892**
Using this SS on NAZE (and maybe also F3) is able to substain flood by configurator without getting stuck.

If it is not possibile to change tab after a flood now it's configurator guilty. Just close and open it and MSP responds correctly. Before the port was completely stuck.

Looptime seems consistent and not fluctuate with this PR.

### CODE REVIEW

**Comment by digitalentity** [comment]
This fix breaks blackbox downloading because MSP response that doesn't fit into serial buffer will never be sent.

**Comment by giacomo892** [comment]
Is there a way to use this only if onboard dataflash is not used/present?

**Comment by digitalentity** [comment]
I think we need to figure out underlyng issue. What board do you use for your tests and what should I do to reproduce the issue?

**Comment by giacomo892** [comment]
Just pick a naze (I know it is not more supported) connect it via softserial to configurator at 9600bps not tick wireless mode.

Open Motor Tab... it will flood the board. Port stuck after a while.

**Comment by stronnag** [comment]
Wireless mode exists for a reason ....

**Comment by giacomo892** [comment]
@stronnag yes to be used on slow wireless links. 

MSP port should not crash under any load, may led to a crash.

**Comment by stronnag** [comment]
Never had an MSP crash on NAZE in > 2.5 years of iNav.

**Comment by giacomo892** [comment]
@stronnag have you tried my cure with the configurator? just flood it on SS with motor tab :)

**Comment by stronnag** [comment]
no. it's not a use case that I find at all interesting or useful. Better fix the configurator if it really bothers you for an unsupported hardware.

**Comment by Schalonsus** [comment]
I also have problems communicating over SS and 9600 baud MSP.
But dont know if it is EzGUI fault or iNav.

**Comment by Schalonsus** [comment]
So, i tested with BT dongle and computer, its the same. MSP get stuck. Please make a fix for this, i can not configure all my planes anymore. USB port is not easy reachable.

**Comment by digitalentity** [comment]
@Schalonsus if that's on NAZE target - I'm afraid we won't look into it since NAZE was declared EOL in 1.7.3

**Comment by Schalonsus** [comment]
yes, missed that...
no prob, i dont use BB so i will compile custom firmware

**Comment by stronnag** [comment]
I tried SS as well; F1 (flip32) iNav 1.74 / mwp, FC running 2000 loop with about 37% CPU load.
At 1200 baud, it seems OK, no packet loss
At 2400 or 4800 baud, it seems mainly OK, slight packet loss.
At 9600 and 19200 baud,  noticeable packet loss (about once every 30 seconds), not very usable.

At no stage did it 'stick' (without any "fixes"), though in each case I got bored after about 5 minutes.

**Comment by Schalonsus** [comment]
Did you send anything to the FC?

**Comment by stronnag** [comment]
Of course, how else would I how it works? MSP is a challenge- response protocol.
One off set of (at least) `MSP_IDENT, MSP_API_VERSION, MSP_BOARD_INFO,  MSP_FC_VARIANT, MSP_FC_VERSION, MSP_BUILD_INFO, MSP_BOXNAMES, MSP_MISC, MSP_WP_GETINFO, MSP_STATUS_EX`.

Then  a continuous (repeating) cycle of `MSP_STATUS_EX, MSP_ANALOG,  MSP_RAW_GPS, MSP_COMP_GPS. MSP_ATTITUDE, MSP_ALTITUDE, MSP_NAV_STATUS`

i.e. the sort of stuff a CGS would use to establish capability and continuously monitor a machine. Implemented on the premise that serial communications over unreliable wireless links are inherently fragile.

**Comment by Schalonsus** [comment]
And why does the board hang when i try to upload mode settings? This happens with iNav configurator and EzGUI so it should be firmware related

**Comment by giacomo892** [comment]
I've found that happening to me too. 
Try to remove a mode. Save. Add a mode. Save.  
Do one operation at a time and tell if this works.

**Comment by Schalonsus** [comment]
Awesome, thank you very much for this advise. This is working! Step by step, but better than nothing 👍

**Comment by giacomo892** [comment]
There is really something not working that may affect even other boards and not only F1 ones.. So I think this might need to be investigated.

**Pull request closed without merging**
