### PR TITLE
Remove all trailing whitespaces in .c and .h files

### PR DESCRIPTION
**Pull request by shellixyz**

### CODE REVIEW

**Comment by digitalentity** [comment]
Merging this PR might break a lot of other PRs that are not merged yet. I suggest we revisit it immediately before the release.

**Comment by shellixyz** [comment]
Agreed. It will be easily done again before the release I just used sed.

**Comment by fiam** [comment]
What if we take the opportunity to clang-format all code and use it from now on? We could add a check for formatting in the Travis build.

**Comment by shellixyz** [comment]
Good idea will help to enforce a consistent coding style.

**Comment by shellixyz** [comment]
I updated this PR could this be merged before 2.0 is released ?

**Comment by teckel12** [comment]
@shellixyz Padding your contributions with white-space changes I see 😉

**Comment by shellixyz** [comment]
@teckel12 Yeah ;). Joking aside I hate to see red blocks when I read the files. I'm using an option in Vim to mark trailing spaces with red background to help see them.

**Comment by teckel12** [comment]
@shellixyz Think of how many bits we could save if we converted everything to use tabs instead of spaces!  But seriously, I'm with you on this, I'm very particular on white space standards and indenting.

**Comment by digitalentity** [comment]
Merging

**Pull request merged**
