### PR TITLE
Angular acceleration limit on PID rate setpoint made possible

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by DzikuVx** [comment]
Awesome! #403

**Comment by stronnag** [comment]
Appears to break navmodes e.g. PH. More when I get home.

**Comment by digitalentity** [comment]
@stronnag it shouldn't. The code code doesn't affect roll/pitch performance by default.

**Comment by stronnag** [comment]
On 6 August 2016 13:35:49 BST, Konstantin Sharlaimov notifications@github.com wrote:

> @stronnag it shouldn't. The code code doesn't affect roll/pitch
> performance by default.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/iNavFlight/inav/pull/427#issuecomment-238021350

I will post logs when I get back from the field. Multiple PH fails. Worked again when flashed back to prior commit. Just a suspicion ATM.

**Comment by stronnag** [comment]
Forget it.Appears to be environmental, as it started to fail on the old build. Apologies for the noise.

**Comment by digitalentity** [comment]
@stronnag no problem. Curious about your failed PH, what caused it?

**Comment by stronnag** [comment]
No idea. Utilimately, appeared completely **random** on both 85fe245 and f440ead. PH fails multiple times, land, power cycle PH is rock solid. Repeat etc. No rhyme or reason to work or fail. Well proven machine, 16-18 sats, 1.2-1.3 HDOP.
I'll pull out some logs later and raise an issue. Regrettably, I had no more lipos to go back further in history.
Last version flown prior to today was 43eaf10, which exhibited no unexpected behaviours, I even liked Turn Assist.

**Pull request merged**
