### PR TITLE
Converted I2C, EXTI and SONAR to new IO

### PR DESCRIPTION
**Pull request by martinbudden**
Further progress in converting to the new IO.

This is here as a placeholder in case anyone wants to look at it - it is known not to be working yet.

### CODE REVIEW

**Comment by sambas** [comment]
are the drivers same as in bf? I've been flying with them couple weeks now successfully.

**Comment by martinbudden** [comment]
@sambas , yes the drivers are intended to be the same as betaflight.

However, it's still a work in progress...

**Comment by martinbudden** [comment]
@digitalentity ,

this is now working and has been tested on CJMCU, CC3D and NAZE.

Can you test on an F3 target, and then it should be OK to merge.

Almost done now, just the UARTs and SPI to do. With a bit of luck that should have F4 working as well...

**Comment by digitalentity** [comment]
@martinbudden will test today, thanks!

**Comment by digitalentity** [comment]
Bench-tested on SPRacingF3 board - boots, I2C working, gyro_sync (EXTI) working, sonar - not tested.

**Comment by digitalentity** [comment]
I think F4 targets should build after we have UARTs and SPI.

**Comment by martinbudden** [comment]
Yes, I think so too. I hope to get this finished in the next few days.

Then parameter groups and finally after that I'll get to actually develop some new features!

**Comment by digitalentity** [comment]
@martinbudden absolutely cool! In the meanwhile I'll get a new FC from MWC working in BF and INAV, and then INAV/BF will come to PixRacer board.

**Comment by Linjieqiang** [comment]
PixRacer board is nice.Come on F4~

**Comment by digitalentity** [comment]
I'll need lots of F4 boards, so far I have only FURYF4 and an old Taulabs Quanton.

**Comment by martinbudden** [comment]
Yes, I need boards for testing as well. I've got Revo mini (which I'm going to put into my first "proper" iNav build - that is one with GPS, camera and gimbal etc etc), and a BlueJay F4 (which I'm going to put into a fast mini quad). I'd like to have a couple of boards permanently wired up on the bench and dedicated to testing. I had a CC3D dedicated for testing, but I blew that up a few days ago - my own fault, but still annoying.

**Pull request merged**
