### PR TITLE
Ublox > 6 support + NAZA serial GPS+MAG support

### PR DESCRIPTION
**Pull request by sambas**
Add VELNED logging to blackbox
Feed compass data from naza gps
Support Naza GPS+MAG
Detect ublox GPS hw version and configure it
Support Position Velocity Time Solution

Might be tight fit for F1 targets

### CODE REVIEW

**Comment by digitalentity** [comment]
Looking good!
A little offtopic: I don't like this CF's monolythic multiprotocol GPS driver. Do you think it would be wise to rework GPS stack, make it more generic and let separate modules handle different protocols?

**Comment by digitalentity** [comment]
Doesn't fit into NAZE even with disabled ledstrip... Time to drop NMEA support?

**Comment by sambas** [comment]
Protocol separation would be good, you could disable one or two for small targets easily then

**Comment by digitalentity** [comment]
I've started to think about it. Looks like we should have only one protocol-specific function - `bool receiveGPSMessage(gpsDataGeneric_t * msg)` where msg is a generic solution data (fix, sat count, pos, vel, hdop)
This function should handle initialisation, data reception and everything else. Should return true if new data available.

**Comment by digitalentity** [comment]
@sambas 
If you have a minute, please have a look at **inav-gps-rework** branch. It's a work in progress, does not compile or work yet, but you can get a general idea of protocol-independent GPS stack.

**Comment by digitalentity** [comment]
@sambas 
I have created a PR #66 for new GPS stack. Can you review if I've missed anything?

**Comment by digitalentity** [comment]
@sambas 
There is a problem with MAG_NAZA - it gets "detected" even if no mag is present. Can we overcome this somehow?

EDIT: Nevermind. Fixed.

**Pull request closed without merging**
