### PR TITLE
Fixes to CLI

### PR DESCRIPTION
**Pull request by martinbudden**
Not yet tested, don't have access to hardware at the moment.

### CODE REVIEW

**Comment by stronnag** [comment]
Pathologically non-default settings test:
Not set
````
BEEPER
FEATURE
MAP
````

Varables not set
````
rateprofile
blackbox_device
blackbox_rate_denom
blackbox_rate_num
default_rate_profile
d_level
d_pitch
d_roll
dterm_lpf_hz
d_yaw
fw_iterm_throw_limit
fw_iterm_throw_limit
i_level
i_pitch
i_roll
iterm_ignore_threshold
i_yaw
max_angle_inclination_pit
max_angle_inclination_rll
nav_alt_d
nav_alt_i
nav_alt_p
nav_navr_d
nav_navr_i
nav_navr_p
nav_pos_d
nav_pos_i
nav_pos_p
nav_posr_d
nav_posr_i
nav_posr_p
nav_vel_d
nav_vel_i
nav_vel_p
pitch_rate
p_level
p_roll
p_yaw
rate_accel_limit_roll_pitch
rate_accel_limit_yaw
rc_expo
rc_yaw_expo
roll_rate
servo_lowpass_enable
thr_expo
thr_mid
tpa_breakpoint
tpa_rate
yaw_iterm_ignore_threshold
yaw_lpf_hz
yaw_p_limit
yaw_rate
````

Possible naming difference
````
acc_soft_lpf_hz v. acc_lpf_hz
````

**Comment by martinbudden** [comment]
@stronnag , sorry, I don't really understand your comment. What are you doing for the test?

**Comment by stronnag** [comment]
Same test I've performed for the last three or more tests against PG:

* Load contrived mainly non-defaults configuration
* Save the dump
* Remove blank and # lines
* compare sorted outputs (1.5.1 v 1.6.0)

Test data, methodology, compare script  http://seyrsnys.myzen.co.uk/inav-pg

**Comment by martinbudden** [comment]
Did you do a full ROM erase? I haven't been updating the ROM version number, so this will be required.

**Comment by stronnag** [comment]
I believe so, as it is the default action of stm32flash. I can repeat, explicitly erasing.

**Comment by martinbudden** [comment]
In need to fully check the load/initialisation process. Thanks for your continued help testing.

**Comment by stronnag** [comment]
Same result with forced erase before flashing. As the test set (including the comparison) is automated, comprehensively testing new builds is very little trouble.

**Pull request merged**
