### PR TITLE
Added target Omnibus F4 nano V7

### PR DESCRIPTION
**Pull request by Woga65**
Many local dealers her in Germany do not offer the Omnibus F4 nano V6 anymore so I made target files for the Omnibus F4 nano V7. 
I used the target files from Betaflight 4.1 as template. Tested with a board sold to me as Omnibus F4 nano V7.1.

Tested: SpekSat, i2c baro, i2c compass, GPS, blackbox
Not tested: SBUS, S.Port, Smart audio
Todo: remove comments after approval

### CODE REVIEW

**Comment by gstyle97** [comment]
where is hex file to test?

**Comment by Woga65** [comment]
> where is hex file to test?

I put it into the releases section of my repository:
https://github.com/Woga65/inav/releases

Despite the information i found on the internet, the buzzer-pin is PB10, not PC5.
Fixed it.

**Comment by msyafiq227** [comment]
the hex doesnt work on flying wing. there is no motor output

**Comment by Woga65** [comment]
> the hex doesnt work on flying wing. there is no motor output

S1+S3 and S2+S4 need to have the same protocol.
So if you have an ESC attached to S1, the protocol need to be „STANDARD“ (pwm) and the rate need to be the same as setup for the servos. 

I should have configured the S3 output for a second motor.
Perhaps it would have been even better to configure the LED pin as additional motor or servo output.

What do you think? 
1) S1+S3 = ESC, S2+S4 = servos, LED pin = LED
2) S1+S3 = ESC, S2+S4 = servos, LED pin = servo
3) S1-S4 = servos, LED pin = ESC
4) leave it as is and set protocol and motor rate to match the servos.

Edit:
I updated the omnibusf4nanov7 hex file according to 1)
Flying wing should work now.
https://github.com/Woga65/inav/releases

**Comment by msyafiq227** [comment]
thank you for the update. however i found another problem. the buzzer doesnt work

**Comment by Woga65** [comment]
> thank you for the update. however i found another problem. the buzzer doesnt work

Unfortunately there are alt least two variants of the Omnibus F4 nano v7.
One of them has the buzzer output on the port PC5 as you can find in the documentations on the internet. Another variant of the board has the buzzer output on the port PB10. This is the board i have on hand. It was sold to me as Omnibus F4 nano V7, the print on the bag said Omnibus F4 nano V7.1

Edit:
I uploaded a hex file for Omnibus F4 nano V7 with the buzzer on PC5. 
Filename: OMNIBUSF4NANOV7_PC5.hex

https://github.com/Woga65/inav/releases

**Pull request closed without merging**
