### PR TITLE
Failsafe refactoring - phase 2

### PR DESCRIPTION
**Pull request by digitalentity**
- [x] Make failsafe system handle only `rcCommand`, leave `rcData` to RX system
- [x] Unify channel handling for all failsafe procedures
- [x] Create options for pre-failsafe "throttle hold" and "throttle drop" (via RX system)
- [x] Keep failsafe active on signal recovery (#1047)

### CODE REVIEW

**Comment by digitalentity** [comment]
Phase 2 is mostly complete. MSP support and Configurator support is required, but this should now be testable.

**Comment by digitalentity** [comment]
Bench tested. Looks functional.

**Comment by oleost** [comment]
@digitalentity I see this PR introduce new CLI variables, but CLI.md is not updated.

Would be nice to get it updated, it's hard for users to lookup new variables.

Just look at the mess betaflight is in. Referring to cleanflight CLI variables which where much doesn't match anymore, and betaflight  parameters are spread over several wiki pages covering CLI values in the order they are entered.

Betaflight CLI:
https://github.com/betaflight/betaflight/wiki/Betaflight-specific-CLI-commands
https://github.com/cleanflight/cleanflight/blob/master/docs/Cli.md
https://github.com/betaflight/betaflight/wiki/BetaFlight-3.0.x
https://github.com/betaflight/betaflight/wiki/BetaFlight-V3.1.x

VS iNav

https://github.com/iNavFlight/inav/blob/master/docs/Cli.md

Or whichever branch, version etc of iNav should be available right there.

**Comment by digitalentity** [comment]
Dang, I always keep forgetting about the docs :smile: 
@oleost thanks for the reminder!

**Pull request merged**
