### PR TITLE
Mamba 2022B targets

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by chucky-whiskers** [comment]
everything seems to work on the mamba 2022B target stable release for my f722 except my camera and vtx. I have no power to either one using the VCC pin. I can try the 9V pins.

**Comment by chucky-whiskers** [comment]
my VCC pad for my VTX does not work on the stable release. It may have coincidentally been damaged at the time I migrated from Betaflight, but it worked this morning and now it doesn't.

**Comment by JulioCesarMatias** [comment]
@chucky-whiskers see the solution to the problem here >> https://github.com/iNavFlight/inav/issues/8414#event-7450404078

**Comment by Jetrell** [comment]
To help anyone that has trouble getting the `USER1` power switcher working with the `Mamba F405 MK4 2022A` (and most likely `2022B`).
It requires these box changes to be entered into the CLI.

`set pinio_box1 = 40`
`set pinio_box2 = 47`

**Pull request merged**
