### PR TITLE
Development

### PR DESCRIPTION
**Pull request by BarryCole**
Sorry if this is in the wrong place, I am new to this.
Would it be possible to have a RTH function that would work with a glider. 
It would need ASI to monitor air speed, and use the elevator rather than the throttle to control the air speed.

Is this possible.

BC

### CODE REVIEW

**Comment by DzikuVx** [comment]
Please use Telegram or RCGroups thread to ask those kind of questions

**Comment by BarryCole** [comment]
Not sure what use rcgroups would be. I am not asking how to do this, as , as far as I know it cannot be done with Inav at present. I am asking if it would be possible to integrate it into Inav in the near future..

**Comment by digitalentity** [comment]
For feature requests, please use https://github.com/iNavFlight/inav/issues/new/choose

**Comment by BarryCole** [comment]
Should I do it again there??

**Comment by digitalentity** [comment]
Yes. You opened a **pull request** which is for submitting proposals for actual implementations and code changes. For reporting bugs and suggesting new features you should open an **issue** instead.

**Pull request closed without merging**
