### PR TITLE
Prevent incorrect rescheduling for BMP280 baro dummy ut_delay

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by stronnag** [comment]
I wonder if this will also solve #586, both the affected vehicles have BMP280, whilst my BMP180 craft is unaffected.Will test later today.

**Comment by stronnag** [comment]
Flew 4 lipos / 7 distinct flights / one hour air time with this on 1.2.0 master and saw no  instance of the random #586 behaviour. I'm more likely to believe that fixes #586 than anything to do with 0f63bc6, as this fix would explain the mid-flight behaviour of #586 observed once. More testing tomorrow on the other  BMP280 platform.

**Comment by martinbudden** [comment]
This is good news. I was puzzled as to how https://github.com/iNavFlight/inav/commit/0f63bc68575f3ff03e5db5819f8e815545b334ea could cause the problem.

**Comment by stronnag** [comment]
Please also consider back porting this into master (and a point release, it's bad news for BMP280 users).

**Comment by digitalentity** [comment]
I'm going to merge #614 and start towards an intermediate 1.2.1 release.

**Pull request merged**
