### PR TITLE
Lazy SPI bus init

### PR DESCRIPTION
**Pull request by digitalentity**
Allow per-device `DEVFLAGS_SPI_MODE_0` setting enabling SPI bus sharing between SDCARD and SPIFLASH (provided only one is initialized at boot time).

### CODE REVIEW

**Comment by digitalentity** [comment]
Tested on OMNIBUSF4 PRO. Testing on other targets required

**Comment by digitalentity** [comment]
How about YOLO'ing and merging this?

**Comment by stronnag** [comment]
FYI, building on SPRF3:
```
%% bus_spi.c 
./src/main/drivers/bus_spi.c:76:23: warning: 'spiDivisorMapFast' defined but not used [-Wunused-const-variable=]
 static const uint16_t spiDivisorMapFast[] = {
                       ^~~~~~~~~~~~~~~~~
```

**Comment by digitalentity** [comment]
@stronnag fixed

**Pull request merged**
