### PR TITLE
More baud rates (1200 to 921600)

### PR DESCRIPTION
**Pull request by digitalentity**
Finally time came to make https://github.com/iNavFlight/inav/issues/183 happen.

### CODE REVIEW

**Comment by Linjieqiang** [comment]
Maybe it will use ULRS 433 to support this feature.I think using flying wing for fpv will be amazing.

**Comment by martinbudden** [comment]
@digitalentity , we should stop using an `enum` for baud rates and just use a `uint32_t`.

**Comment by digitalentity** [comment]
You suggest using actual baud rate as a configuration entity?

**Comment by martinbudden** [comment]
Yes

**Comment by stronnag** [comment]
Please note that the CLI c. line 1748 has hard coded enums in the range 9600 - 115200 / 250000. 
Once this is fixed, I'll modify  LTM to switch  to medium / slow schedules for 2400 /1200 baud  regardless of the ltm_update_rate setting.

**Comment by stronnag** [comment]
Fixed when I use the right branch. See 'ltm-update-sanity' (which fixes the CLI as well, apologies for two issues in one PR) https://github.com/iNavFlight/inav/pull/1471

I happen to like the enums, the compiler catches my stupid 1200/1209 typos.

**Comment by krzysztofmatula** [comment]
Will this change allow for connecting to Configurator at higher speeds, e.g. 921600?
So far, the Configurator doesn't seem to allow for selecting anything higher than 115200.
Is it restricted to specific hardware?

**Comment by stronnag** [comment]
So why?
````
# serial 0 1 4800 38400 115200 115200

# serial 0 1 921600 38400 115200 115200
Parse error
````
The latter would really help with blackbox downloads #1670 

Pah! it's hard coded to 115200 in cli.c Ugh.

**Pull request merged**
