### PR TITLE
Airspeed improvements

### PR DESCRIPTION
**Pull request by digitalentity**
- [x] Replace CAS/TAS with IAS (IAS is more indicative to the pilot and more useful for i.e. PID scaling since it defines aircraft behavior at given dynamic pressure. In hot air and cold air stall will occur at different TAS, but at same IAS)
- [ ] Use IAS for PID scaling on airplanes
- [x] Add IAS to telemetries
- [ ] Add IAS to MSP API
- [ ] Add IAS closed loop control to navigation modes
- [ ] Docs update

### CODE REVIEW

**Comment by stronnag** [comment]
Any reason for not using the unused air speed in the LTM S frame?

**Comment by digitalentity** [comment]
@stronnag oops. Forgot that we have a placeholder for airspeed in S-frame. Fixed

**Comment by stronnag** [comment]
Thanks. I only noticed when updating the wiki. Keeps a spare x-frame byte.

**Comment by DzikuVx** [comment]
@digitalentity I think you should split this PR into 2 separate:

1. IAS and telemetry
1. PID scaling

and merge 1st one to development already as long as airspeed is not yet used to anything useful

**Comment by digitalentity** [comment]
@DzikuVx agreed. Will do.

**Comment by DzikuVx** [comment]
I did some static testing and all I can confirm is that airspeed is saved in blackbox logs

**Comment by digitalentity** [comment]
@DzikuVx PID scaling removed from this PR - it now covers only conversion to IAS and telemetries.

**Comment by DzikuVx** [comment]
[pitot2.TXT](https://github.com/iNavFlight/inav/files/1150536/pitot2.TXT)
Flight tested, nothing bad happened, I assume it can be merged.
But looks like better filtering would be required

**Comment by DzikuVx** [comment]
OK, no pitot data at all. I messed hardware, pitot was not powered during flight

**Pull request merged**
