### PR TITLE
Camera Control for Caddx Turtle v2

### PR DESCRIPTION
**Pull request by eijowk**
This ads the protocol used by Caddx for their Turtle series, based on this document: https://github.com/betaflight/betaflight/files/2419338/Uart_Turtletv2.docx

Works with Caddx Turtle v2, and maybe also with v1 with v2 software, but I don't have one so can not verify.

Functions: 
- Start/stop recording from radio switch. 
- Photo by switch (but not during recording so not so useful)
- Camera settings through radio similar to Runcam

The code is an ad to the Runcam code, and since I don't have a Runcam - I have not been able to verify that Runcam control still works - however - I have used a serial monitor to verify and Runcam communication seems to work from what I can see.

### CODE REVIEW

**Comment by fiam** [comment]
@eijowk Thanks! We're currently focused on finishing 2.1, so this will have to wait a bit.

**Comment by wx4cb** [comment]
Its not that big a deal for me at least. I only run at 1.21 jigglywatts on
RB4 anyway. It was just something i noticed putting my 3rd mini talon
together. Theres a button if i need it hehe

**Comment by eijowk** [comment]
There is a recent Caddx Firmware update which is said to implement the Runcam protocol in Caddx Turtle v2. I haven't tried it myself - but there are a few Betaflight related reports on the web that it works, and some reports about issues.

With that said I think this pull is not needed anymore.

**Comment by shellixyz** [comment]
I don't have a Turtle v2 or Split to check. Is the Turtle v2 firmware supposed to run without issues on v1 hardware ?

**Comment by eijowk** [comment]
Just V2 to my understanding
https://www.rcgroups.com/forums/showpost.php?p=41437473&postcount=666

**Comment by Pairan** [comment]
this will be usefull for the upcoming Caddx Tarsier camera which is FC controlable to ...

**Comment by shellixyz** [comment]
Apparently this is not needed anymore, closing

**Comment by Pairan** [comment]
... seems it wont work with the caddx Tarsier ... perhaps the old protocol would be good to have anyways

**Comment by eijowk** [comment]
I don't know about the Tarsier protocol - if it's the same as the Turtle - then it's quite easy. But isn't there a new small hardware from Caddx that converts the protocol from Runcam to Caddx to make all (most?) Caddx cams compatible with Betaflight and probably INAV?

**Comment by Pairan** [comment]
d2ffddab-5e53-4a6d-9e97-a03e8445315d

hmm ... could be the reason: controller missing! but why a controller if it could be programmed?!

**Comment by romko1** [comment]
Exactly, I just want to run on Caddx Tarsier just starting and stopping HD recording via UART (something like RunCam). I modified the files as described above and returned the error when compiling: 
pb_compilation_2

**Comment by eijowk** [comment]
I guess it's because I made the pull for INAV 2.1. I've actually made a version for 2.2 which I'm successfully running with one of my Turtles, but I had to make a few changes to make it working at 2.2.

I colud easily compile a version for your taget, but unfortunately I'm traveling at the moment. No computer, just on my mobile ... 

I maybe can make it at the weekend or even at Friday this week - which target?

**Comment by romko1** [comment]
@eijowk: That would be perfect if you compiled a modified version of Inav 2.2 (the critical bugs in the F7 processor board were fixed). Target MATEKF722MINI. Thank you.

**Comment by eijowk** [comment]
https://www.dropbox.com/s/xbxfyp9ptfwl4t1/inav_2.2.0_MATEKF722.hex?dl=0

**Comment by eijowk** [comment]
I managed to run RDP on my mobile and compile :-)

See the link in the comment above.

**Comment by romko1** [comment]
@eijowk: Thank you. I'm going to test if your FW allows you to control the start / stop recording for Caddx Tarsier. Thanks

**Comment by romko1** [comment]
@eijowk: I recorded FW but only then I noticed that it is for TARGET MATEKF722 and I have FC MATEKF722mini. Can you please compile FW 2.2.0 for FC (target) MATEKF722mini? Thank you.

**Comment by eijowk** [comment]
Sorry, Now compiled for MATEKF722MINI:
https://www.dropbox.com/s/qqbn3scgq2grk4b/inav_2.2.0_MATEKF722MINI.hex?dl=0

**Comment by romko1** [comment]
@eijowk: Thank you. I uploaded a new FW from you, but unfortunately I can't control Caddx Tarsier with it if I set Camera power or Camera WIFI or Camera switch mode. Of course I have a FC with RX-TX and TX-RX tarsier. Please have an idea. All I need to do is start and stop recording only. Thank you.

**Comment by eijowk** [comment]
Have you made:
set cam_provider = CADDX_V2

Otherwise... I guess that the protocol is somewhat different for the Tarsier compared to Turtle. If so we need to somehow get a specification or make a reverse engineering on that piece of HW that CADDX sales.

**Comment by romko1** [comment]
Unfortunately, the start / stop recording still does not work, probably the converter mentioned above will be needed.

**Comment by Pairan** [comment]
Strange though ... the converter is only there to make the keyboard obsolete and change the camera settings with the TX via the hud! start and stop should still work somehow

**Comment by romko1** [comment]
@Pairan: I also think it could work without a converter. However, when I loaded the modified FW, it entered _set cam_provider = CADDX_V2_. Of course RX-TX and TX-RX and unfortunately it doesn't work, which bothers me.

**Comment by Pairan** [comment]
... I feel the same.

**Comment by eijowk** [comment]
Key emulation can be done with two different methods:
1. Via serial protocol TX RX which is what is done with the Runcam setup and my modified sw
2. Via resistance emulation through pwm - to the key input at the cam.
Maybe explain your issues? Don't know about the Tarsier - does it have a key input? If so pwm emulation should work?

**Pull request closed without merging**
