### PR TITLE
Removed MAG_INT_EXTI definition from SPRF3 target

### PR DESCRIPTION
**Pull request by martinbudden**
Attempt to address issue https://github.com/iNavFlight/inav/issues/431 - GPS Inconsistent behavior

### CODE REVIEW

**Comment by digitalentity** [comment]
I'm merging this into 1.2 as a cleanup.

**Comment by giacomo892** [comment]
Hi! Just a little question.
What's the point of doing this? Is this disabling the use of mag interrupt? So PC14 connection is no more compulsory for this F3 target?

**Comment by digitalentity** [comment]
@giacomo892 mag interrupt is useless, we don't care much about mag update rate and delay.

**Comment by giacomo892** [comment]
Ok thanks. So i'll leave it disconnected on my custom boards. 
Is that true for every target?

**Comment by digitalentity** [comment]
Yes, it's true for all targets. Mag interrupt is pretty useless.

**Comment by giacomo892** [comment]
Thanks very much for your time. 
Have a nice day.

**Pull request merged**
