### PR TITLE
Add support for FLYWOOF411 and FLYWOOF7DUAL targets

### LINKED ISSUE #5885: [Target] Add new boards from Flywoo:  GOKU F7DUAL, GOKU F7MINI DUAL
Original PR: https://github.com/iNavFlight/inav/pull/5832

Board link: https://flywoo.net/products/goku-fc-f722-mini-dual-flight-controller-built-in-osd-5v-9v-2a-bec-icm20689-mpu6000-for-rc-drone-1

### PR DESCRIPTION
**Pull request by digitalentity**
Closes #5885 #5110 #5110

### CODE REVIEW

**Comment by echma** [comment]
Would it be a lot to ask if the FLYWOOF7DUAL can get support for inav 2.5.1 ? I would love to try inav on my new build. If it's taking too much time I'll just wait for 2.6 :)

**Comment by digitalentity** [comment]
Back-porting and re-spinning 2.5.1 should be possible, these targets don't involve any significant change in the codebase.

**Comment by echma** [comment]
Is it that easy that I can do it myself or are you able to give me a hand?

**Comment by digitalentity** [comment]
I'll do it once this is merged

**Pull request merged**
