### PR TITLE
current_meter_offset allowed to go negative

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by DzikuVx** [comment]
Fixes #2169

**Review by digitalentity — DISMISSED** [review]
I don't see any issues with this PR

**Review by fiam — CHANGES_REQUESTED** [review]
Not so fast. `currentMeterOffset` is sent over the wire in response to `MSP_CURRENT_METER_CONFIG` and received in the `MSP_BF_CONFIG` command. The MSP client will be expecting an `uint16_t`. This will break compatibility with basically anything that implements those commands.

**Comment by DzikuVx** [comment]
Well... yes and actually no... Did not tested this since I do not have such a possibility ATM, but since sign is encoded in bit 15, bit 15 is always 0 for the range 0..3300 that legacy software uses. So for as long as no one starts going <0, it works just like before.

**Comment by DzikuVx** [comment]
Or an I wrong with bit 15 encoding sign?

**Comment by fiam** [comment]
@DzikuVx You're not wrong regarding the negative bit. The problem is that those MSP clients will display the negative value as a big positive number since they will interpret it as unsigned.

It is fine if we decide to deliberately break compatibility. Just wanted to make sure we were not breaking it unintentionally.

If we decide to go ahead, we need to update the configurator to make it aware of these changes in INAV versions >= 1.7.4.  Current code always expect an `uint16_t` and the input for the field is limited to to [0, 3300]:

```html
<input type="number" id="currentoffset" name="currentoffset" step="1" min="0" max="3300" />
```

**Comment by DzikuVx** [comment]
@fiam Yes, I intentionaly did that and yes, Configurator changes will follow to match firmware

**Comment by fiam** [comment]
@DzikuVx I think we should increase the MSP version then, don't we?

**Comment by fiam** [comment]
@DzikuVx Btw, if a commit requires configurator changes I think it would be nice to mention it in the description and link to the configurator PR and vice versa. Sounds good?

**Review by fiam — APPROVED** [review]

**Comment by DzikuVx** [comment]
Bench tested by @kingdraki in #2169

**Pull request merged**
