### PR TITLE
Fix RTH_INITIALIZE state getting stuck in some cases

### LINKED ISSUE #775: Failsafe not working on development.
Hi. First I want to say I have not gotten to test this on iNav 1.3 yet because of time limitation.

Im having some issues getting Failsafe RTH working reliable on my fixed wing.

Made and video while I did several attempt.

Only LOG25 and around 5 minutes in the video it works. I have not found the reason for it working that time and not the other.

Dump, and logs and video of all attempts are in this link: https://drive.google.com/open?id=0B-yHzNtOXxbEX1dxSTZod3lnT0U

I will try to do so more backtracking and figuring out whats going on, but if someone have some ideas what to test, or what can be the cause it would be great. @digitalentity ?

### PR DESCRIPTION
**Pull request by digitalentity**
Forgot to set up the timeout event in #745. Fixes #775.

### CODE REVIEW

**Comment by digitalentity** [comment]
@oleost, can you please test this?

**Comment by oleost** [comment]
Yes I will test it

**Comment by oleost** [comment]
@digitalentity Tested, confirming working.

Armed and started walking, turned off TX and it would not start to climb, then I walked quickly and it started climbing.

Also did a second try with power cycling and then running and turning off TX, it started climbing imidiality.

But on a different note, once it has aquirred an heading its happy. I tried leaving the airplane still (with previously aquirred GPS headings) and then turn off TX and it would happily climb.

**Comment by digitalentity** [comment]
Yes, that's the intended behavior. When no compass true heading is unknown until initialized from GPS, after that INAV is happy.

Thanks for testing, merging.

**Pull request merged**
