### PR TITLE
Convert settings docs to a list

### PR DESCRIPTION
**Pull request by nmaggioni**
Enhances readability now that min/max values have been added. Empty descriptions are filled in with `// TODO`.

### CODE REVIEW

**Comment by breadoven** [comment]
I was going to mention it's become "frustrating" to read now. Is there no way to get it to display across the full width of the screen not in a fixed width column. or is that a Github thing ?

**Comment by nmaggioni** [comment]
@breadoven Nothing we can do about it, GH dictates how markdown is rendered. This format may be an improvement.

**Comment by stronnag** [comment]
I think it looks OK. It also has the advantage that each setting has  an individual URI, which is useful for pointing a user at the setting they need.

**Comment by DzikuVx** [comment]
@kernel-machine over the weekend

**Pull request merged**
