### PR TITLE
VTX/CMS unification

### PR DESCRIPTION
**Pull request by digitalentity**
Having a separate VTX CMS menu is annoying and not user-friendly. User has to remember which VTX protocol is configured and use the appropriate menu.

This PR does the following:

* CMS now unifies all VTX menus into one
* CMS is now decoupled from VTX drivers, CMS doesn't care which VTX is used
* CMS and settings no longer operate MHz and mW - only band/channel/power level
* VTX driver provides number of band/channel/power levels for the CMS
* VTX driver provides actual power in mW and frequency in MHz for the OSD and CMS

Caveats - SmartAudio driver has to be reworked to fully support this

Tested on FFPV 2.4GHz VTX and Tramp. I don't have a SA VTX available for testing the SA part :(

### CODE REVIEW

**Comment by digitalentity** [comment]
An addition to CLI statu:

```
VTX: band: R, chan: 5, power: 1 (25 mW), freq: 5806 MHz
```

**Comment by Scavanger** [comment]
OK, I will test Smartaudio.
SA 2.1 with "auto config" for power levels work (with old CMS Menu), so i can implement it, to fit to this PR.
 
One Thing: With this PR we will lose SA configuration (Pit in/out range for 2.0, Freestyle/Race mode, Smartaudio version info). 
How to handle this, or just drop it (does anyone really use this features in iNav)?

**Comment by digitalentity** [comment]
I think we need to think about this from usability perspective and avoid overcomplicating things.

**Re pit mode:** 
The pit mode code in INAV was (and still is) effectively a no-op (only possible to switch PIT mode from the CMS), the pit mode processing in vtx.c does nothing.

**Re Freestyle/Race mode:**
The only difference between Freestyle/Race from usability perspective seem to be the output power level on power-up.

The new code in INAV will not change the settings until you do a "SET" from the menu (from this perspective it behaves like the Race model). IMO the driver should take care of taking the VTX out of PIT mode when necessary.

**Re SA version info:**
Do we care as long as the driver is able to handle it?

**Comment by digitalentity** [comment]
We could have some driver-specific CLI settings if necessary (similar thing we do with UBLOX GPS), but I don't think they should be exposed to the CMS menu.

**Comment by Scavanger** [comment]
1. Your Code works with Smartaudio (2.0), i start to make the changes for 2.1

2. 
**Freestyle/Race mode**
Yes, and in Freestyle mode you can set the VTX to every frequency (in 1 MHz steps) in the supported range (5.645 - 5.945 GHz), not only the 40 band frequencies, not used in iNav now.

Yes, I think a smartaudio CLI Command with the missing feature should do the job. 
There extra features are made for racecopters, only a few users will use this features with iNav, so CLI should be good enough.

**Comment by digitalentity** [comment]
Awesome, thanks for looking into SA2.1 @Scavanger, I'm merging this now, so you can use development branch for your SA2.1 work.

**Pull request merged**
