### PR TITLE
Implement softserial for SPRACINGF3EVO target

### PR DESCRIPTION
**Pull request by rb1205**
Cleanflight has added for some time softserial to the SPracingF3 EVO board. It uses the 5-6 and 7-8 PWM output pins, and seems to work nice. I added it to iNav by copying over all relevant definitions in the target.h file. I have been testing it and seems to work as intended, but I ran into some hard freezes when I set up and used both of the ports to MSP (one for MW_OSD, the other for bluetooth telemetry), but I saw that's a more or less known issue with softserials, in fact it happened to me once with cleanflight as well.

### CODE REVIEW

**Comment by oleost** [comment]
BTW Cleanflight/iNav only supports two MSP ports, so if you had a total of 3 active that's probably the reason.

**Comment by oleost** [comment]
Also should not target.mk file include soft serial drivers?

`drivers/serial_softserial.c`

**Comment by rb1205** [comment]
Yeah I know, I disable MSP on the USB serial when I do that. The config is good, it doesn't revert back to default and MSP works on both ports.

Ooops, forgot to add target.mk when I prepared the branch -.-

**Comment by oleost** [comment]
@rb1205  Also it should get merged to development branch.

Master gets updated only from development when new releases

**Comment by rb1205** [comment]
You're right, base branch changed.

**Comment by wilco1967** [comment]
I tried enabling softserial, but it stops the tail servo from working on a tricopter....
Not so strange, as the tail servo is also on output 7 (IIRC)....

SPracingF3EVO board
Tricopter
iNav 1.5.1

Would it be possible to only have at least 1 softserial on a tricopter ?

**Comment by rb1205** [comment]
Unfortunately I tried and failed, as the timer is shared between all the relevant outputs. I can't say if it's feasible.

**Pull request merged**
