### PR TITLE
Fix Sqrt Controller incorrect initialization

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
I feel obliged to open a correction PR for this.

[on that line](https://github.com/iNavFlight/inav/blob/f3f0cf0d5bd125171e654859ff4f4b95fcc6acf9/src/main/navigation/sqrt_controller.c#L130) where it says  `if ((output_min > 0.0f) && (sqrt_controller_pointer->kp > 0.0f)) {` is incorrect

the correct one is `if ((output_min < 0.0f) && (sqrt_controller_pointer->kp > 0.0f)) {`

output_min will always be less than zero, not greater.

and yes, @Jetrell made me aware of the "problem" that occurred with @breadoven. I spent hours trying to reproduce the "problem" and talking to Jetrell about it, but I couldn't...

This PR also fixes the 10 meter addition issue reported by Breadoven >> https://github.com/iNavFlight/inav/pull/7845#issuecomment-1073696271

### CODE REVIEW

**Review by DzikuVx — APPROVED** [review]

**Comment by breadoven** [comment]
I'm still getting the same thing when this change is tested, It now calculates a non zero value for `sqrt_controller_pointer->error_min` but that doesn't make any difference because of the way the numbers work out during my test (RTH ground test holding quad). As said before in https://github.com/iNavFlight/inav/pull/7845#issuecomment-1073696271 this is probably more a logging issue with `posControl.desiredState.pos.z` being updated more frequently by `updateWaypointsAndNavigationMode ` than `updateAltitudeVelocityController_MC` causing the value to flip flop between the raw value from the RTH Nav routine and the adjusted value from the sqrt controller.

I did also notice an error in the code that needs rechecking:

https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L61

surely makes the following redundant:
https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L81

**Comment by breadoven** [comment]
The solution to the logging issue would be to simply not update `posControl.desiredState.pos.z` to the output from the sqrt controller. It serves no purpose and will be overwritten by the Nav functions anyway when they set the desired position again.

https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/navigation_multicopter.c#L77

**Comment by JulioCesarMatias** [comment]
> I'm still getting the same thing when this change is tested, It now calculates a non zero value for `sqrt_controller_pointer->error_min` but that doesn't make any difference because of the way the numbers work out during my test (RTH ground test holding quad). As said before in [#7845 (comment)](https://github.com/iNavFlight/inav/pull/7845#issuecomment-1073696271) the messy log data is probably more a logging issue with `posControl.desiredState.pos.z` being updated more frequently by `updateWaypointsAndNavigationMode ` than `updateAltitudeVelocityController_MC` causing the value to flip flop between the raw value from the RTH Nav routine and the adjusted value from the sqrt controller.
> 
> I did also notice an error in the code that needs rechecking:
> 
> https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L61
> 
> surely makes the following redundant:
> 
> https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L81

This PR does not fix the "Flip-Flop" that occurs with the value of `posControl.desiredState.pos.z`. So you didn't notice any difference. When I was reviewing the algorithm, I found this error, and decided to fix it and open this PR (See the title of this PR).

About redundancy, I don't see any problem with that, I like redundancies. I see no reason to remove this, look at the algorithm again and understand that if for some reason the sqrt controller parameter `derivative_max` aka `acceleration` (not speed) is greater than 0 (zero), and for Alt-Hold it is always greater than zero, and if for some reason (if the user enters) kP is equal to 0 (zero), a division by zero will occur.

**Comment by JulioCesarMatias** [comment]
> The solution to the logging issue would be to simply not update `posControl.desiredState.pos.z` to the output from the sqrt controller. It serves no purpose and will be overwritten by the Nav functions anyway when they set the desired position again.
> 
> https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/navigation_multicopter.c#L77

look again at the algorithm, and you will see that: YES, the pointer return is for something YES. What can be done is to make changes to the algorithm so that the navigation uses the result of the Desired Position given by the correction calculated by the sqrt controller.

**Comment by breadoven** [comment]
> > I'm still getting the same thing when this change is tested, It now calculates a non zero value for `sqrt_controller_pointer->error_min` but that doesn't make any difference because of the way the numbers work out during my test (RTH ground test holding quad). As said before in [#7845 (comment)](https://github.com/iNavFlight/inav/pull/7845#issuecomment-1073696271) the messy log data is probably more a logging issue with `posControl.desiredState.pos.z` being updated more frequently by `updateWaypointsAndNavigationMode ` than `updateAltitudeVelocityController_MC` causing the value to flip flop between the raw value from the RTH Nav routine and the adjusted value from the sqrt controller.
> > I did also notice an error in the code that needs rechecking:
> > https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L61
> > 
> > surely makes the following redundant:
> > https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L81
> 
> This PR does not fix the "Flip-Flop" that occurs with the value of `posControl.desiredState.pos.z`. So you didn't notice any difference. When I was reviewing the algorithm, I found this error, and decided to fix it and open this PR (See the title of this PR).
> 
> About redundancy, I don't see any problem with that, I like redundancies. I see no reason to remove this, look at the algorithm again and understand that if for some reason the sqrt controller parameter `derivative_max` aka `acceleration` (not speed) is greater than 0 (zero), and for Alt-Hold it is always greater than zero, and if for some reason (if the user enters) kP is equal to 0 (zero), a division by zero will occur.

How is this redundancy ? kp isn't recalculated within the function so it can only be 0 on entry meaning it's impossible for that code to ever execute.

**Comment by breadoven** [comment]
> > The solution to the logging issue would be to simply not update `posControl.desiredState.pos.z` to the output from the sqrt controller. It serves no purpose and will be overwritten by the Nav functions anyway when they set the desired position again.
> > https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/navigation_multicopter.c#L77
> 
> look again at the algorithm, and you will see that: YES, the pointer return is for something YES. What can be done is to make changes to the algorithm so that the navigation uses the result of the Desired Position given by the correction calculated by the sqrt controller.

Not sure I understand you. Navigation sets `posControl.desiredState.pos.z` based on the user altitude settings for RTH, WP. You can't redefine this using the value calculated by the sqrt controller otherwise you end up changing the original altitude settings,

**Comment by JulioCesarMatias** [comment]
> > > I'm still getting the same thing when this change is tested, It now calculates a non zero value for `sqrt_controller_pointer->error_min` but that doesn't make any difference because of the way the numbers work out during my test (RTH ground test holding quad). As said before in [#7845 (comment)](https://github.com/iNavFlight/inav/pull/7845#issuecomment-1073696271) the messy log data is probably more a logging issue with `posControl.desiredState.pos.z` being updated more frequently by `updateWaypointsAndNavigationMode ` than `updateAltitudeVelocityController_MC` causing the value to flip flop between the raw value from the RTH Nav routine and the adjusted value from the sqrt controller.
> > > I did also notice an error in the code that needs rechecking:
> > > https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L61
> > > 
> > > surely makes the following redundant:
> > > https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/sqrt_controller.c#L81
> > 
> > 
> > This PR does not fix the "Flip-Flop" that occurs with the value of `posControl.desiredState.pos.z`. So you didn't notice any difference. When I was reviewing the algorithm, I found this error, and decided to fix it and open this PR (See the title of this PR).
> > About redundancy, I don't see any problem with that, I like redundancies. I see no reason to remove this, look at the algorithm again and understand that if for some reason the sqrt controller parameter `derivative_max` aka `acceleration` (not speed) is greater than 0 (zero), and for Alt-Hold it is always greater than zero, and if for some reason (if the user enters) kP is equal to 0 (zero), a division by zero will occur.
> 
> How is this redundancy ? kp isn't recalculated within the function so it can only be 0 on entry meaning it's impossible for that code to ever execute.

I updated the comment about redundancy, read it again. 
Captura de tela 2022-03-23 201916

**Comment by JulioCesarMatias** [comment]
> > > The solution to the logging issue would be to simply not update `posControl.desiredState.pos.z` to the output from the sqrt controller. It serves no purpose and will be overwritten by the Nav functions anyway when they set the desired position again.
> > > https://github.com/iNavFlight/inav/blob/002188b71bcc93c5889a17529a6dd50356b645a5/src/main/navigation/navigation_multicopter.c#L77
> > 
> > 
> > look again at the algorithm, and you will see that: YES, the pointer return is for something YES. What can be done is to make changes to the algorithm so that the navigation uses the result of the Desired Position given by the correction calculated by the sqrt controller.
> 
> Not sure I understand you. Navigation sets `posControl.desiredState.pos.z` based on the user altitude settings for RTH, WP. You can't redefine this using the value calculated by the sqrt controller otherwise you end up changing the original altitude settings,

add a simple "if" condition so it doesn't happen in RTH or WP mode.

**Comment by JulioCesarMatias** [comment]
> 

or rather the pointer return, and everything is fine (in the end it won't be my proposal, but I just don't want to spend my time on it).

**Comment by JulioCesarMatias** [comment]
@breadoven check the last commit of this PR (https://github.com/iNavFlight/inav/pull/7918/commits/8304e700d4527a2101589429312df6129a066559) , I made the necessary corrections (I removed the pointer return to `posControl.desiredState.pos.z`)

**Comment by breadoven** [comment]
OK I think this makes sense now. It fixes the logging issue and won't affect the output from the velocity controller so all good. Thanks for persevering.

**Comment by JulioCesarMatias** [comment]
I think there was some kind of bug with this PR, because the tests with brach are not happening after a commit.

**Comment by breadoven** [comment]
You need to resolve a conflict with `src/main/navigation/navigation_multicopter.c` before it'll complete tests.

**Comment by JulioCesarMatias** [comment]
> You need to resolve a conflict with `src/main/navigation/navigation_multicopter.c` before it'll complete tests.

yes, but unfortunately the button to resolve conflicts is unavailable, something went wrong with this branch, I will open another PR.
Captura de tela 2022-03-24 192318

**Pull request closed without merging**
