### PR TITLE
Fix missing name command

### PR DESCRIPTION
**Pull request by marbalon**

### CODE REVIEW

**Review by digitalentity — CHANGES_REQUESTED** [review]
Please also add this to "dump/diff" output.

**Comment by marbalon** [comment]
Ok, will add.

**Review by digitalentity — APPROVED** [review]

**Comment by digitalentity** [comment]
It's failing on NAZE. I think it's time to decide if we are going to support it further.

**Comment by martinbudden** [comment]
Looks like it is failing on CJMCU not NAZE. I use CJMCU for debugging sometimes, since it flashes quickly, so I'd like to continue support if we can. PR https://github.com/iNavFlight/inav/pull/1898 should help here.

**Comment by digitalentity** [comment]
#1898 merged, @marbalon please rebase to give Travis a kick

**Pull request merged**
