### PR TITLE
Update Getting Started.md

### PR DESCRIPTION
**Pull request by mwhidden**
Correcting link to Tested GPS Hardware information.

### CODE REVIEW

**Comment by DzikuVx** [comment]
@mwhidden please rebase with master

**Comment by mwhidden** [comment]
Still fairly new and this is my first accepted pull request. 

You say to rebase because my changes were accepted and I should update my fork to reflect the presence of those changes in the real iNav repo?

**Comment by mwhidden** [comment]
I'm new, so please let me know if I there was anything here I did incorrectly or not in accordance with best practices. I'd like to contribute, but I don't want to cause problems, and I'm not following the conversation here.

**Comment by martinbudden** [comment]
@mwhidden , thanks for making a PR. All contributions, no matter how small, are appreciated.

The practice used in this project is that PRs should be made agains the development branch.

**Comment by mwhidden** [comment]
@martinbudden OK, so next time I'll make my changes on development branch in my fork. Thank you.

**Comment by martinbudden** [comment]
Just so there's no misunderstanding. When you make changes you should create a new branch on your fork - you can call that branch anything you like. But that branch should be created from the development branch, and when you submit your PR, you should do it against the iNav development branch.

It's a bit confusing at first, but you'll soon get the hang of it.

**Pull request merged**
