### PR TITLE
F4 Boost, Missing F4 files

### PR DESCRIPTION
**Pull request by sambas**
Trying to speedup your F4 merge,

Added Missing F4 related files

### CODE REVIEW

**Comment by digitalentity** [comment]
I don't see a problem with merging this, thanks :)

**Comment by martinbudden** [comment]
This merge has broken the build. So far I've found:
1. New target `ANYFC` does not build. It looks like this is a template for new targets, but there is no readme or anything describing it as such. Also having a new target that is not used just slows down the `make all`
2. There is a new target COLIBRI that does not build. It is not clear if this is a variant of COLIBRI_RACE, or just that it was named differently in the branch from which this code was merged.
3. New targets REVO and REVO_OPBL do not build. It's pointless adding these until the F4 port is complete anyway, and again adding these targets just slows down the `make all` process.

@digitalentity , can we please not make any big merges without, at the very minimum, checking that `make all` works?

**Comment by digitalentity** [comment]
@martinbudden sorry for that. I must have missed the part that broke builds for existing targets.  I'm going to be busy for the next week, probably will also create a taret for a new FC (F3-based) for INAV and Betaflight.

**Comment by martinbudden** [comment]
@digitalentity , well I've just got to the point where I can now look at using these and it turns out these are the 2011 version of the STM libraries, betaflight is using the 2015 version. So it all needs to be redone anyway.

@sambas is a good guy, and I appreciate he was trying to help, but as a general principle a big PR that is in parallel with another piece of ongoing work does not help.

**Comment by digitalentity** [comment]
Yep, I was also over confident to merge them right away.

**Comment by martinbudden** [comment]
No worries, it's not a big deal. But let's be aware of this in future. There are at least two "big" pieces of work coming up, parameter groups, and the F7 port (which I believe both @sambas and @npsm are working on).

**Comment by digitalentity** [comment]
I have another big change in mind - a HAL layer between a bus driver and a device driver to make access to the bus more generic and avoid having mpu6500_spi and mpu6500.

EDIT: I actuallly ran into trouble with SoftSPI/SPI when doing OpFlow support today. We need a better abstraction of communication layer between CPU and devices.

**Comment by martinbudden** [comment]
Yes, the SoftSPI/SPI handling was a minimal basic implementation. Something better would be welcome.

I notice Raceflight did some work on combining the I2C and SPI drivers, but I didn't look at it in any detail.

**Pull request merged**
