### PR TITLE
Enable RANGEFINDER_HCSR04_I2C for all targets with flash > 256k

### LINKED ISSUE #4542: Rangefinder failing after upgrading to 2.1.0
## Current Behavior

After I upgraded to INAV v2.1 my sonar don't initialize.

Sonar: US-100 (via I2C and Arduino)

# status
System Uptime: 14 seconds
Current Time: 2041-06-28T04:04:00.000+03:00
Voltage: 14.81V (4S battery - OK)
CPU Clock=216MHz, GYRO=MPU6500, ACC=MPU6500, BARO=BMP280, MAG=QMC5883
STM32 system clocks:
  SYSCLK = 216 MHz
  HCLK   = 216 MHz
  PCLK1  = 54 MHz
  PCLK2  = 108 MHz
Sensor status: GYRO=OK, ACC=OK, MAG=OK, BARO=OK, RANGEFINDER=UNAVAILABLE, OPFLOW=NONE, GPS=OK
SD card: Manufacturer 0x3, 15558144kB, 01/2017, v8.0, 'SL16G'
Filesystem: Ready
Stack size: 6144, Stack address: 0x20010000, Heap available: 1456
I2C Errors: 45, config size: 4671, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 1, used = ADC 1
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 2, used = none
  AIRSPEED : configured = none, used = none
System load: 5, cycle time: 2010, PID rate: 497, RX rate: 129, System rate: 9
Arming disabled flags: NAV HWFAIL CLI

## Steps to Reproduce

1. copy diff on v2.0
2. upgrade to v2.1
3. paste diff
4. save

## Expected behavior

Sonar should work.
## Suggested solution(s)

Check the code

## Additional context

https://pastebin.com/zrCncp68

---

- FC Board name and vendor: Matek F722
- INAV version string: INAV/MATEKF722 2.1.0 Feb 25 2019 / 16:59:54 (65b0ec142)

### PR DESCRIPTION
**Pull request by shellixyz**
Fixes #4542

### CODE REVIEW

**Comment by digitalentity** [comment]
Travis is not happy

**Comment by shellixyz** [comment]
It should end up happy now

**Comment by DzikuVx** [comment]
>  The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by shellixyz** [comment]
Damn...

**Pull request merged**
