### PR TITLE
Added AUTOLEVEL system message and updated pitch trim on screen

### LINKED ISSUE #8782: OSD reference to autolevel mode when running and updated pitch trim values.
## Current Behavior
- On the OSD screen when you are in `Autolevel` mode nothing changes.
- In the pitch level trim OSD field, the saved `fw_level_pitch_trim` is continuously displayed and not the updated one.

## Desired Behavior
- Show a system message `Autolevel` when this flight mode is activated or add a modifier such as "L" to the end of the flight mode name.
- Display the updated `fw_level_pitch_trim` values on the OSD when in auto level.

## Who does this impact? 
With these changes the pilot will be aware that the mode `Autolevel` is in operation and know in real time the adjusted `fw_level_pitch_trim` value, just like with the PID in `Autotune.`

### PR DESCRIPTION
**Pull request by tiriad**
Fixes #8782 
Squash

### CODE REVIEW

**Comment by DzikuVx** [comment]
Nice, thank you very much for this !

**Comment by MrD-RC** [comment]
@DzikuVx Could this not go in to 6.0. As it's kind of a bug fix.

**Comment by DzikuVx** [comment]
Well, it's not really a bug fix ;)

**Comment by NODFips** [comment]
Why? 

How to remove "AUTOLEVEL" - report from system message.  (now, its always shown on OSD screen) 
On my  flying wings, the AutolevelMode is on the same switch/same AUX-CH  as Angle Mode .... its activated all the time...almost ;-)

**Comment by NODFips** [comment]
Ok. Now, I have it. I used it as a "flightmode". My fault. 
That's why  * fw_level_pitch_trim * is on OSD now -  to check the "level". 

Thank you ;-)

**Pull request merged**
