### PR TITLE
foxeerv2 - enable 5V pads

### PR DESCRIPTION
**Pull request by sensei-hacker**
The Foxeer F722 v2 has a pin (PC6) that turns on 5V supply to the 5V pads, via a FET.
This patch makes that pin high so that the regulator gets connected to the pads.

The way I coded it, it could also be turned off via PINIO, but it defaults to on.
There may be a way of coding it that doesn't use PINIO and just has the pin high all the time.

### CODE REVIEW

**Comment by mmmmdanone** [comment]
The solution is confirmed on the board https://www.foxeer.com/foxeer-mini-f722-v3-pro-fpv-flight-controller-20-20mm-build-in-pit-pass-g-426

For an additional consideration: 
In general, the idea of using a TSSOP-5 FET switch to control 5V peripheral power rail is quite debatable:
this would work for a low-current GPS receiver; everything will be fine, 
but a couple of servos could trip overcurrent protection/blow out the tiny TSSOP IC.
It's a limitation of the particular flight controller, other controllers may have different implementations.

**Comment by DzikuVx** [comment]
@sensei-hacker The code fails to build on some targets. Check the https://github.com/iNavFlight/inav/runs/7718720977?check_suite_focus=true

**Comment by sensei-hacker** [comment]
Checks now pass.

**Comment by mmosca** [comment]
@sensei-hacker can this pr be closed?

**Pull request closed without merging**
