### PR TITLE
[Multirotor Only] Maybe some improvement for AutoPilot in cruise mode

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
I've seen some people report that by setting `nav_user_control_mode = CRUISE` , the multirotor goes back as soon as the radio sticks are no longer manipulated, the reason this happens is because the XY position set to Pos-Hold happens before the multirotor stops, it keeps going forward because of inertia, and AutoPilot makes it go back to reach the XY position marked for Pos-Hold. Some people are using Braking mode to improve this. But I don't know if using Braking mode together with Pos-Hold is right. This PR adds a maybe possible fix for this, the new algorithm will use the XY position and velocity to calculate a new XY position, this new position will be calculated based on the speed of the multirotor. Remember, this is only for multirotors with AutoPilot in Cruise mode. Below I made a graph using 5 samples of XY position and velocity, and see the new XY position for the Pos-Hold being calculated.

https://docs.google.com/spreadsheets/d/1mvHOruvGCSvSZCvPn3pIeD5sf98zU5AOqhcq_5F4isA/edit?usp=sharing

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
this part should do that, but it doesn't do very well.

https://github.com/iNavFlight/inav/blob/78c4a1967bd2462c37f17493b617a9b61fdb7ea7/src/main/navigation/navigation_multicopter.c#L791

**Comment by JulioCesarMatias** [comment]
.hex for your FC 

https://github.com/iNavFlight/inav/actions/runs/1063486828

**Comment by DzikuVx** [comment]
I will have to take a look. But this should be combined with MC_BRAKING or MC_BRAKING should be removed

**Comment by rts18** [comment]
>
>But this should be combined with MC_BRAKING or MC_BRAKING should be removed.

@DzikuVx Maybe remove MC_braking all together until its fixed.
#6777

You had the same partial runaway in the alpha version of the code. Time index - 5:02
https://www.youtube.com/watch?v=gaiTBFD1ZrA

**Pull request closed without merging**
