### PR TITLE
Increase SMARTAUDIO_MAX_POWER_COUNT to 8

### PR DESCRIPTION
**Pull request by bkleiner**
Some SA 2.1 devices like TBS UNIFY PRO32 DP support up to 8 powerlevels being reported by GetSettings request.
This PR increases the current limit of 5 to 8.

### CODE REVIEW

**Comment by sensei-hacker** [comment]
I wonder if I'm misreading the product page and manual for that VTX.
The product page lists these power levels selectable by SmartAudio:

14dBm (25mW)
20dBm (100mW)
26dBm (400mW)
33dBm+ (2000mW+)

That's consistent with the TBS SmartAudio protocol, which they have defined as four power levels.  (Plus pit mode, which is not a powe level.)

The manual seems to indicate you can select power levels 2 1/2, 3 1/2 etc via the physical buttons, but not via SmartAudio.

Is this mistaken?  Have you selected the in-between power levels with this code and *seen the LEDs reflect the in-between power levels*? (The SmartAudio protocol says if you ask for a power level not supported.by SmartAudio, it uses the next lower supported one.)

I don't see an 8-level Betaflight VTX table from TBS, do you?

If you've tested it and seen the indicator go through all 8 levels via SmartAudio that would be cool. I just don't see that in the manual or on the product page.

**Comment by sensei-hacker** [comment]
Screenshot_20240730-003019

**Comment by bkleiner** [comment]
> I wonder if I'm misreading the product page and manual for that VTX. The product page lists these power levels selectable by SmartAudio:
> 
> 14dBm (25mW) 20dBm (100mW) 26dBm (400mW) 33dBm+ (2000mW+)

That's there for simplicity's sake, but as SA 2.1 supports setting levels by dbm, there are infinite possible levels really. 

> That's consistent with the TBS SmartAudio protocol, which they have defined. (Plus pit mode, which is not a power level.)
> 
> The manual seems to indicate you can select power levels 2 1/2, 3 1/2 etc via the physical buttons, but not via SmartAudio.

Maybe i am being blind, but i don't see that the SA spec indicates any upper limit for the number of power levels returned by the 2.1 `GetSettings` frame. Maybe we should add one tho. 

> Is this mistaken? Have you selected the in-between power levels with this code and _seen the LEDs reflect the in-between power levels_? (The SmartAudio protocol says if you ask for a power level not supported.by SmartAudio, it uses the next lower supported one.)

Again, with 2.1 the power can be specified via dbm, which is also what iNav uses in that case, where there is really no such thing as a "valid power level" only "too much power".

> I don't see an 8-level Betaflight VTX table from TBS, do you?
> 
> If you've tested it and seen the indicator go through all 8 levels via SmartAudio that would be cool. I just don't see that in the manual or on the product page.

I don't think we have published a 8-level vtx table, but then that's a bit of different situation, as there the user can easily modify the levels to their liking. Those are more of a "suggestion" than a "exhaustive list".
We have just confirmed that the DP does indeed return 8 levels.

**Comment by sensei-hacker** [comment]
Thanks for the additional information!

I see you referred to TBS as "we" here and I saw your Discord message, so that's also informative.

**Comment by ABLomas** [comment]
I tested F405TE target (Matek F405 WMN) with TBS UNIFY PRO32 DP. No issues noticed, even PIT mode is selectable (which is a problem on many VTX'es).

**Comment by anti-vaxxer** [comment]
> I tested F405TE target (Matek F405 WMN) with TBS UNIFY PRO32 DP. No issues noticed, even PIT mode is selectable (which is a problem on many VTX'es).

@ABLomas  How did you manage to use Pitmode? I thought Pit mode hasn't yet been successfully implemented in INAV.

**Comment by ABLomas** [comment]
> @ABLomas How did you manage to use Pitmode? I thought Pit mode hasn't yet been successfully implemented in INAV.

Selecting via OSD menu "PIT ON" works.

**Comment by anti-vaxxer** [comment]
> Selecting via OSD menu "PIT ON" works.

@ABLomas  Thanks for the information. Apparently it works for Smartaudio then.

I have tried two different VTX that use IRC Tramp and Pit mode doesn't work.
Do you know how to fix it in INAV? Because I don't know anything about coding.

**Comment by b14ckyy** [comment]
@bkleiner Can you please look at the Configurator side as well? A user on FB just tried it and it works through CLI to have all 8 power levels but in Configurator he only can select 1-5.

**Comment by bkleiner** [comment]
> @bkleiner Can you please look at the Configurator side as well? A user on FB just tried it and it works through CLI to have all 8 power levels but in Configurator he only can select 1-5.

on it.

**Pull request merged**
