### PR TITLE
Fix the memory corruption caused by pwmInit()

### LINKED ISSUE #470: All rate values are zero after boot (also TPA breakpoint value)
I flashed official 1.2 onto my flip32 that has been running 1.1 very well for a few months. Now every time after startup, each of the rate values are zero, rendering it un-flyable. I have to connect to the configurator (or EZ-GUI) and save some rate values, which causes the FC to remember the values I had set earlier. Unfortunately, this means I cannot actually set any values that I want :/

Here is a video that explains this better
https://youtu.be/Q4iHVJMIJeI

Another video, this time use EZ-GUI and trying to save some new values.
https://youtu.be/G5IsQpNbOuA

The correct values that appear when I click Save were set by me when I was using a pre-release build (built by me) of 1.2 about a week before the official release.

### PR DESCRIPTION
**Pull request by digitalentity**
Fixes #470

### CODE REVIEW

**Comment by martinbudden** [comment]
@digitalentity , great find.

I have to confess, I'm the one who introduced this bug with the `TARGET_MOTOR_COUNT` ROM saving code.

It explains a lot - why the problems were found on CC3D, since that was the first target to have its motor count set. It also explains why the problems were not found in betaflight, since I never added the `TARGET_MOTOR_COUNT` to betaflight. It's also a timely find, since I was thinking of moving the code over there.

I don't think we would be overly optimistic to assume that this is the root cause of all the quirky problems we have been seeing.

@hydra, I haven't checked but I think this bug also exists in Cleanflight. I'll try and submit a fix today.

**Comment by digitalentity** [comment]
@martinbudden I dont think this is the root cause of all recent problems - @stronnag is using SPRF3 which is unaffected by the problem. The NAZE issue is definitely solved, CC3D test pending.

**Comment by stronnag** [comment]
You say unaffected on f3. This reminds me a few days ago I was checking tricopter (Dido fc) motors in the cfg motor tab, and there was a bogus throttle value displayed against a non-existing motor, motor 5 from memory. As I had more urgent matters to mind (wiring of new ESCs), I thought nothing of it until now.

**Comment by digitalentity** [comment]
@stronnag might be related.

**Comment by martinbudden** [comment]
@digitalentity , I don't understand why you are defining `MAX_PWM_OUTPUT_PORTS` in the `target.h` file.
Shouldn't:

```
#if (MAX_MOTORS > MAX_SERVOS)
#define MAX_PWM_OUTPUT_PORTS MAX_MOTORS
#else
#define MAX_PWM_OUTPUT_PORTS MAX_SERVOS
#endif
```

be sufficient?

**Comment by digitalentity** [comment]
If you define TARGET_MOTOR_COUNT 4 and select an airplane mixer on CC3D you'll be initializing 2 motors and 8 servos - 10 total which is more than MAX_MOTORS or MAX_SERVOS alone.

**Comment by digitalentity** [comment]
Maximum number of PWM outputs is mixer-specific and in some cases (when using servos) is greater than MAX_MOTORS ant MAX_SERVOS.

**Pull request merged**
