### PR TITLE
Show pilot name and craft name on arming screen if they are not empty

### PR DESCRIPTION
**Pull request by MrD-RC**
I need to test. But it should be straight forward.

### CODE REVIEW

**Review by mmosca — APPROVED** [review]
Looks straight forward.

**Comment by Jetrell** [comment]
I read the report on Discord... I tried it with Analog and Digital.
It now displays the Craft Name on the analog and digital arming screen. Which it didn't before this, under the condition mentioned on discord.

But there is a format issue when displaying it on the digital arming screen.
It should display **! Armed !** then below it, the _home icon_ with the _Safehome number @ distance_. 
But instead they are all together like this.. 
**: house icon : craft name ! Armed !** 
Colon dot included, all on the same line.

**Comment by Jetrell** [comment]
I read the report on Discord... I tried it with Analog and Digital.
It now displays the Craft Name on the analog and digital arming screen. Which it didn't before this, under the condition mentioned on discord.

But there appears to be some random DisplayPort issues. Whether the MSP is not keeping up or not.. This was with an F722 controller.

When it works correctly we get this.

okay arm screen

Then the next time I arm. Or after an FC reboot, I get this and other character variations as well.

Capture 2


And other characters again **without** a GNSS fix and Safehome position.

Capture 1

**Comment by MrD-RC** [comment]
It appears to be picking up a pilot name from somewhere. Presumably where there isn't one set. That would explain the erroneous characters.

**Comment by mmosca** [comment]
Probably uninitialized memory. Try
```
    char        buf[MAX(osdDisplayPort->cols, FORMATTED_DATE_TIME_BUFSIZE)] = "";
    char        buf2[MAX(osdDisplayPort->cols, FORMATTED_DATE_TIME_BUFSIZE)] = "";
    char        craftNameBuf[MAX_NAME_LENGTH] = "";
    char        versionBuf[osdDisplayPort->cols] = "";
```

or adding 
```
        memset(buf2, 0, sizeof(buf2));
```

before calling  ```osdFormatPilotName(buf2);```

**Comment by MrD-RC** [comment]
That should be fixed now. There would have also been weirdness if there was a pilot name but no craft name.

**Pull request merged**
