### PR TITLE
Adds sdcard_detect_inverted setting to make detection configurable

### PR DESCRIPTION
**Pull request by DzikuVx**
This will hopefully solve the problem of different HW revisions of AnyFC F7 clone from banggood. Card detection inversion is now configurable.

Addresses #1832

### CODE REVIEW

**Comment by DzikuVx** [comment]
@digitalentity tested on 3 AnyFC F7 boards, seems to be working like expected

**Review by digitalentity — APPROVED** [review]
Dang, those Chinese really make it complicated. Is there anything specific about those hardware revisions? Can we detect them at run-time?

**Comment by DzikuVx** [comment]
As long as I know, the only difference is correct / different card slot. And we do not even come close to "Pro" version...

**Comment by digitalentity** [comment]
Damn.

**Comment by DzikuVx** [comment]
Pro version will at least have less pwm outputs, maybe different order, different buzzer setting and whoever knows what else

**Pull request merged**
