### PR TITLE
ADC samples averaging with added STM32F30x support

### PR DESCRIPTION
**Pull request by shellixyz**
Duplicate changes made to the F4 ADC driver in #3190 in the F3 ADC driver

Supersedes #3190

### CODE REVIEW

**Review by digitalentity — APPROVED** [review]

**Review by digitalentity — COMMENTED** [review]
This PR doesn't enable averaging for any target. Are we going to have a separate PR to do it?

**Comment by shellixyz** [comment]
@digitalentity I can add it to this PR. 20 samples seems to work well. Should we start with this value for both F3 and F4 ?

**Comment by shellixyz** [comment]
I added 20 samples averaging for F3 and F4 targets. Should be good to merge.

**Comment by digitalentity** [comment]
@mluessi @shellixyz thanks!

**Comment by mluessi** [comment]
You are welcome :)

**Pull request merged**
