### PR TITLE
PID: Improve PID LPF filtering

### PR DESCRIPTION
**Pull request by digitalentity**
As concluded in https://github.com/cleanflight/cleanflight/pull/2087 PT1 IIR filter is better for D-term as it's creating less phase shift. Also additional LPF on Yaw P was recommended by @borisbstyle and tested in Betaflight.

### CODE REVIEW

**Comment by borisbstyle** [comment]
Cheers....thanks I dont get time to add it. I would recommend 60hz at least for dterm.

I found 40 on the edge for some frequencies generated by prop wash. Adds more resonance in some scenarios.

**Comment by DzikuVx** [comment]
@borisbstyle Also on bigger and heavier machines than racers?

**Comment by digitalentity** [comment]
@borisbstyle thanks for recommendation!
I'm trying to figure out defaults flyable on most quads, even bigger ones and for them even 40hz would probably be motor noise. I found default of 40hz flyable on both small racing quads and bigger 500-600 size machines.

**Comment by borisbstyle** [comment]
yes i meant mini quads.

But I really think for bigger ones as well when gyro cut is low too
Op 11 mei 2016 13:39 schreef "Konstantin Sharlaimov" <
notifications@github.com>:

**Comment by digitalentity** [comment]
Tested this PR on my miniquad today. Tuning could be better, but I'm getting there. https://youtu.be/rEbyLo-4-tA

**Pull request merged**
