### PR TITLE
Stack watermarking

### PR DESCRIPTION
**Pull request by digitalentity**
Continuation of #510.

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden this is now tested and working.
@hydra also fyi :smile:

**Comment by martinbudden** [comment]
Great!

**Comment by martinbudden** [comment]
@digitalentity , this seems to have broken the F4 targets. I'm getting errors like:

```
obj/main/REVO/startup_stm32f40xx.o: In function `Reboot_Loader':
(.text.Reset_Handler+0x80): undefined reference to `_heap_stack_begin'
obj/main/REVO/startup_stm32f40xx.o: In function `Reboot_Loader':
(.text.Reset_Handler+0x84): undefined reference to `_heap_stack_end'
collect2: error: ld returned 1 exit status
make[1]: *** [obj/main/inav_REVO.elf] Error 1
make: *** [REVO] Error 2
```

**Comment by digitalentity** [comment]
@martinbudden hm... didn't test REVO builds. Probably linker script for F4 is incorrect. Will look into it.

**Comment by martinbudden** [comment]
@digitalentity , we should probably add REVO to the travis build

**Comment by digitalentity** [comment]
@martinbudden agreed. This will try catching F4-specific compile-time issues.

**Pull request merged**
