### PR TITLE
[Target] Matek F411WSE: Softserial1 Full Duplex

### PR DESCRIPTION
**Pull request by Scavanger**
Refers to: #5940 

New Target: MATEKF411SE_FD_SFTSRL1 
Full duplex softserial1, RX remapped to PB10, LED pad.

### CODE REVIEW

**Review by shellixyz — APPROVED** [review]
LGTM

**Comment by dl1bg** [comment]
@Scavanger 
Maybe you could post a binary based on INAV 2.6? I can test it, as soon as the wether gets dry here.

**Comment by Scavanger** [comment]
@dl1bg Just go to the "checks" tab and download the zip file under artifacts.

**Comment by dl1bg** [comment]
Tested yesterday with the setup descreibed here
https://github.com/iNavFlight/inav/issues/5940#issuecomment-736059755

To be honest, I did not fly much because of constant bad weather here. The improvement of Acro mode and additional infos in "craft name" from 2.6 work nicely, and of course the softserial from this banch.
-> works great, I would be happy to see this in INAV 2.7

**Comment by dl1bg** [comment]
Now I had a chance to test with Angle, Acro, 3Dcrs, RTH. 
Everything works as expected, OSD also, of course.
Great work, thank you!

Dear Andi /  Scavanger
Could we please PM, in order to discuss sending a Frankonian beer to you?

**Comment by alexvazquez** [comment]
So in order to use SoftSerial 1 for example for my Caddx Vista I have to flash the firmware  MATEKF411SE_FD_SFTSRL1 and connect RX to ST1 pin and TX to Led pin?

One other question, what pins are assigned for Softserial 2? 

Appreciate so much

**Comment by alexvazquez** [comment]
@Scavanger where can I download the firmaware? I went to Checks and tried to download under artifacts and I got:

The following artifacts have expired and are no longer able to be downloaded.

Appreciate any help.

**Comment by FreakkFerris** [comment]
This firm Ware did not work on my 411se. If i solder the Vista i have no osd and with bn220 gps i get the "err hw!". I tried it with inav 3.02 , 4.0 and 4.1.

**Pull request merged**
