### PR TITLE
WP mission Home WP option

### PR DESCRIPTION
**Pull request by breadoven**
Reinstates the ability to set an unlimited number of intermediate mission WPs that are located at the Home position.

WAYPOINT, HOLD_TIME and LAND WP types can be flagged to go to the Home location by setting the waypoint flag to 0x48. 

Also adds fall back function that ensures flight to home if both the Latitude and Longitude are set to 0.

Fall back function tested in flight on a fixed wing and works as expected. Needs further test using home flag.

### CODE REVIEW

**Comment by stronnag** [comment]
If this is multiple RTHs back again, can we please have it as RTH, otherwise it just gets too confusing trying to keep up with multiple exceptions.

**Comment by avsaase** [comment]
Configurator support would be nice too.

**Comment by stronnag** [comment]
> Configurator support would be nice too.

Not breaking extant / MSP based planners is one of _my_ benchmarks for merging WP related PRs. Others of course may be less fussy,

**Comment by breadoven** [comment]
Have to admit I was hoping to avoid tying it in directly with RTH. I'd prefer to see it as a means of setting a WP that just happens to use the Home coordinates, something separate to RTH which I tend to think means arriving and remaining rather than passing by transiently. This method achieves this with the added remote benefit of possibly preventing a flyaway should someone misconfigure a WP by setting the Lat and Lon to 0 by mistake. I managed to do this by forgetting to change the action from 1 to 4 for a RTH WP loaded via the CLI ... which saw the plane happily set off to the equator.

If this is considered a useful means of flagging a WP to use the Home coordinates then perhaps it's mainly a matter of deciding how to implement it to avoid setting confusion.

**Comment by stronnag** [comment]
I'm begining to like this idea. 

Can we do something more radical like use `flag` to indicate that the action should take place at the arming location? 

Then one could timed-PH there as well. After all, the only two reserved `flag` values are 0 and 0xa5 at the moment.

Then you don't need a new WP type; just fill in the arming location at  WP initialise?

**Comment by breadoven** [comment]
> I'm begining to like this idea.
> 
> Can we do something more radical like use `flag` to indicate that the action should take place at the arming location?
> 
> Then one could timed-PH there as well. After all, the only two reserved `flag` values are 0 and 0xa5 at the moment.
> 
> Then you don't need a new WP type; just fill in the arming location at WP initialise?

I think this home type is useful because it's not RTH, it doesn't use the various altitude control settings RTH uses, just behaves like a basic WP with the usual altitude setting that can be different for each home WP set.

Does this need to use the flag if you don't use a new WP type ? Given that the Lat and Lon serve no purpose they can only be set to 0 which serves as a "home" flag in itself. So long as a mission planner recognises Lat = 0 & Lon = 0 as home there shouldn't be an issue. I suppose a specific flag does avoid any confusion over the mean of 0, 0 coordinates.

This version of the PR does allow timed hold to be set by p1 If you set p1 to 0 then of course it just acts like a basic WP. I tested it in flight the other day with timed hold and it worked as expected.

**Comment by stronnag** [comment]
How this is done internally is obviously an implementation detail both for the FC and external consumers (mission planners, GCS etc.). However there must be a well defined interface that preserves as far as possible legacy interoperability.

In particular, the FC must support at least the following use cases:

* A mission with FBH points is flown; on disarm the mission is saved to EEPROM. The FBH WPs must be saved as  FBH, by whatever mechanism is agreed (lat, lon = 0 / special flag).

* A FBH mission is flown; on disarm the mission is uploaded to an external application via `MSP_WP` ; the FBH WPs must be preserved by whatever mechanism is agreed (lat, lon = 0 / special flag).

Likewise and beyond the scope here, a mission planner will want to display FBH points geographically and must ensure they are downloaded to FC (`MSP_SET_WP`) as FBH (which may involve 0,0 location).

I like the idea that there is no special WP type (so all P1,P2,P3 semantics work as now) with no preference as to the method of indicating FBH behaviour (0,0 coordinates, flag), as long as it can unambiguously meet external interoperability requirements.

**Comment by stronnag** [comment]
Round trips OK via MSP, excellent.

**Comment by breadoven** [comment]
Just needs @ArnoTise to include flags in the Mission Control mission configuration. They're ignored at the moment as you'd expect.

**Comment by stronnag** [comment]
> Just needs @ArnoTlse to include flags in the Mission Control mission configuration. They're ignored at the moment as you'd expect.

Added the necessary (save planning home and flag attributes to the [XML schema](https://raw.githubusercontent.com/stronnag/mwptools/master/src/samples/mw-mission.xsd) recently. WP2 is a FbyBy WP, stubbornly locked to the planning home and not draggable. 

Screenshot-20210609102408-735x525

**Comment by ArnoTlse** [comment]
Hi @breadoven, hi @stronnag

What I have understood so far, is that this PR adds the possibility to flag a waypoint with a FBH behavior. This means on a mission planner that when user will select a waypoint and ticked the waypoint as a FBH WP, this waypoint will automatically drop to Home location and been frozen to Home. Only Home is able to be moved then to move all FBH flagged WP, until user releases a WP with FBH by de-flagging it.

Is this a correct understanding of this PR purpose ?

So, how is this flag implemented in Inav if I want to add it in Inav Configurator Mission planner?

Arno

**Comment by stronnag** [comment]
> Hi @breadoven, hi @stronnag
> 
> What I have understood so far, is that this PR adds the possibility to flag a waypoint with a FBH behavior. This means on a mission planner that when user will select a waypoint and ticked the waypoint as a FBH WP, this waypoint will automatically drop to Home location and been frozen to Home. Only Home is able to be moved then to move all FBH flagged WP, until user releases a WP with FBH by de-flagging it.
> 
> Is this a correct understanding of this PR purpose ?
> 
> So, how is this flag implemented in Inav if I want to add it in Inav Configurator Mission planner?
> 
> Arno

How the mission planner implements this is up to the developer; the implementation above is a pretty good description of how [mwp](https://github.com/stronnag/mwptools) has chosen to implement this feature.

The mode is indicated by setting the `flag` value to 0x48 (72, 'H'); to this end I added a `flag` attribute to the [XML schema](https://raw.githubusercontent.com/stronnag/mwptools/master/src/samples/mw-mission.xsd) (which I should move to inav repo).

**Comment by breadoven** [comment]
> Hi @breadoven, hi @stronnag
> 
> What I have understood so far, is that this PR adds the possibility to flag a waypoint with a FBH behavior. This means on a mission planner that when user will select a waypoint and ticked the waypoint as a FBH WP, this waypoint will automatically drop to Home location and been frozen to Home. Only Home is able to be moved then to move all FBH flagged WP, until user releases a WP with FBH by de-flagging it.
> 
> Is this a correct understanding of this PR purpose ?
> 
> So, how is this flag implemented in Inav if I want to add it in Inav Configurator Mission planner?
> 
> Arno

That understanding sounds right. I guess for editing, clicking on the Home WP would show a list of FBH WPs ? Lat and Lon could be 0 for these WPs but perhaps better to leave the original coordinates where they were first placed so they return there if de-flagged.

I was wondering how the flag fits with Mission control since it doesn't seem to include it in the mission configuration although obviously the end of mission flag gets written to the EEPROM WP mission. It will obviously need to be added to the configuration for this PR.

**Comment by ArnoTlse** [comment]
Hi,

Ok, thanks.
I add this PR to the ToDo list on Inav Configurator Mission planner.

Arno

**Pull request merged**
