### PR TITLE
Fixes to CLI PG handling, esp DIFF/DUMP

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by stronnag** [comment]
Getting there!

Same 'non-defaults' test as yesterday, compared to 1.5.1.

Notes.

* Still a problem with rateprofiles, defaults (not set values) in 1.6.0. Note original defined default rate profile as 1 (not zero).

Missing
````
blackbox_device
blackbox_rate_denom
blackbox_rate_num
default_rate_profile
fw_iterm_throw_limit
servo_lowpass_enable
````
Default rather than set values
````
rateprofile
pitch_rate
rc_expo
rc_yaw_expo
roll_rate
tpa_breakpoint
tpa_rate
yaw_rate
````
Potential naming change
````
acc_soft_lpf_hz v. acc_lpf_hz
````

**Comment by martinbudden** [comment]
I've removed `servo_lowpass_enable` - if you don't want it, set `servo_lowpass_freq` to zero. This is in line with other filters.

`fw_iterm_throw_limit` was overlooked. I'll fix that.

I'm surprised about the blackbox values. They seem to be working for me. I'll recheck.

I also need to check the acc potential naming change.

Something seems to be going on with the rate profile. I'll investigate.

**Comment by martinbudden** [comment]
@stronnag 

`acc_soft_lpf_hz` has been renamed to `acc_lpf_hz`.

I'm thinking of renaming `servo_lowpass_freq` to `servo_lpf_hz` - what do you think?

**Comment by stronnag** [comment]
I'm all in favour of consistency. We just need to remember to put these changes in the release notes.
btw:
````
# get blackbox
Invalid name
````

**Comment by martinbudden** [comment]
But there is no `blackbox` item, so `get blackbox` should return invalid.

`get blackbox_device` etc should work though.

**Comment by stronnag** [comment]
I see `src/main/target/NAZE/target.h`
````
// !!Temporarily remove blackbox until ROM recovered for NAZE target
````
and abbreviations do work, e.g. try `get acc`

**Comment by martinbudden** [comment]
Looks like it might not be temporary. NAZE overflows by 1379 bytes with blackbox enabled. I've got a few tricks up my sleeve, but I don't think I can pull that much out of a hat.

@stronnag , @digitalentity , anything else that can be disabled instead of blackbox on NAZE?

**Comment by stronnag** [comment]
A newer compiler helps, byt still a big deficit (428b) [gcc version 6.3.0 ]
````
Linking NAZE
/usr/lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/bin/ld: obj/main/inav_NAZE.elf section `.data' will not fit in region `FLASH'
/usr/lib/gcc/arm-none-eabi/6.3.0/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 428 bytes

````

**Comment by martinbudden** [comment]
I might be able to pull 428 bytes out of my box of tricks.

**Pull request merged**
