### PR TITLE
Allow use of servos with multirotors on BEEROTORF4 FC

### LINKED ISSUE #2434: Allow servo outputs on multicopter mixer and a BeeRotorF4 board
whatever mixer type (quadx, custom, customairplane) i used in beerotor F4.  mmix and smix can not change   any output pin ordering, for my case, i connected 4 motors to output 1 to 4, and 1 servo to output 7 showed as picture. i have tried a lot of times to change the value of mmix and smix. base on https://github.com/iNavFlight/inav/blob/master/docs/Mixer.md .  it does not change anything in the output ordering. 
beerotorf4_front

### PR DESCRIPTION
**Pull request by shellixyz**
Should fix #2434. It also fixes the timers for use in FW. Testing required.

### CODE REVIEW

**Comment by digitalentity** [comment]
I believe this should go to 1.9. Going to merge and include in 1.9-RC2

**Comment by chan2328** [comment]
@shellixyz , @digitalentity Thanks for creating the firmware to me, I tested output 5 & 6 are work very well, but outputs 6 and 7 are duplicated, share the same servo 1 port. and output 8 is not work at all. This is fine for me as i only need  two servo ports. thanks for helping me.

**Comment by chan2328** [comment]
Orz, output 1 & 2 are not work.  output 3 & 4 are work. some thing wrong here.

**Comment by shellixyz** [comment]
@chan2328 I did not change anything for outputs 6 and 7 I can't see how they would be "duplicated". But I changed the timer for the output 1 and 2. Unfortunately I do not own this board I can't test the changes. Anything new ?

**Comment by chan2328** [comment]
@shellixyz @digitalentity may be use the same timer and channel in the previous version. 
{ TIM**3**,  IO_TAG(PC7), TIM_Channel_**2**, 1                         , IOCFG_AF_PP, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO }, // M6
{ TIM**3**,  IO_TAG(PB5), TIM_Channel_**2**, 1                         , IOCFG_AF_PP, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR | TIM_USE_MC_SERVO | TIM_USE_FW_SERVO }, // M7
why would you like to change the output 1 and 2? any limitation for the channel and timer?
Anything new ? output 1 & 2 cant work, no other error found.

**Comment by shellixyz** [comment]
I changed the output 1 and 2 timers because otherwise they would have shared the timer 3 with the outputs 5, 6 and 7. It would be an issue for using something else than 50Hz standard PWM for servos and motors.

**Comment by chan2328** [comment]
so there is no solution at this moment? I am not a software developer, but could you share the information to us to find out the solution?. 
{ TIM1,  IO_TAG(PB0), TIM_Channel_2, 1 | TIMER_OUTPUT_N_CHANNEL, IOCFG_AF_PP, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR |                    TIM_USE_FW_MOTOR }, // M1
{ TIM1,  IO_TAG(PB1), TIM_Channel_3, 1 | TIMER_OUTPUT_N_CHANNEL, IOCFG_AF_PP, GPIO_AF_TIM3,  TIM_USE_MC_MOTOR |                    TIM_USE_FW_MOTOR }, // M2
the first TIM 1 is not equal to GPIO_AF_TIM 3.

I don't know the relationship between TIM1, TIM_Channel_1, 1 so I just guess.
sorry, I can't help you.

**Comment by shellixyz** [comment]
Indeed well spotted I made a mistake there. I changed the timer but forgot to alter the alternate function in the pin definition. Give me 15 minutes I will give you a new hex file.

**Comment by shellixyz** [comment]
@chan2328 Here it is. This should work better ;)
[inav_1.9.0_BEEROTORF4.hex.zip](https://github.com/iNavFlight/inav/files/1759520/inav_1.9.0_BEEROTORF4.hex.zip)

**Comment by chan2328** [comment]
@shellixyz great! I tested output 1 to 6  all works now.  output 1 to 4 are motors, and output 5,6 are servos now. output 7 still use same servo port as output 6(servo 1) , output 8 not work.  but this is minor. because i can do what i want now. 
thanks for helping me. please add the changes to release 1.9.

**Comment by shellixyz** [comment]
Nice I will ask for pulling the fix.

**Pull request merged**
