### PR TITLE
Increase SBUS frame gap

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
Cope with some new RC receivers with gaps in SBUS frames

### CODE REVIEW

**Review by DzikuVx — CHANGES_REQUESTED** [review]
@JulioCesarMatias I'm not sure. If we increase the gap by default, then some existing (R9 etc) might stop working. And longer `inter-frame` means that less receivers will fit the default.

**Comment by MrD-RC** [comment]
Which receivers have a problem? If not FrSky or Futaba. I would agree not to change the default.

**Comment by JulioCesarMatias** [comment]
This was tested on FastSBUS and with an old SBUS receiver from FlySky. But it's ok if this can't be merged because it will cause problems on other receivers.

**Comment by DzikuVx** [comment]
Cool. Thanks for understanding

**Pull request closed without merging**
