### PR TITLE
Changed FPort telemetry frame rate to support being driven by the RX.

### PR DESCRIPTION
**Pull request by fiam**
Original code by @mikeller at https://github.com/betaflight/betaflight/pull/6098
Added a few comments and ported to INAV by @fiam

### CODE REVIEW

**Review by mikeller — APPROVED** [review]

**Comment by nmaggioni** [comment]
As of today the latest F.Port firmware for the R9MM rx (Flex, `181228`) **doesn't** report this info.

**Comment by digitalentity** [comment]
This requires some testing. Is this safe to merge?

**Comment by fiam** [comment]
Looks like FrSky only released some beta firmware for the XSR with this feature. I'd suggest we postpone to 2.2 and decide wether to include or drop it.

**Comment by mikeller** [comment]
@nmaggioni: What frame id is sent by the R9MM?

@digitalentity: This change is designed to be backwards compatible - RX firmware without support for backpressure only sends `FPORT_FRAME_ID_NULL` as the frame id (verified with XSR, r-XSR, and R9 as per mid-2018).
So only RX firmware that supports back pressure will send `FPORT_FRAME_ID_DATA` and enable `rxDrivenFrameRate`.

**Comment by nmaggioni** [comment]
@mikeller In the aforementioned build the R9MM was indeed sending `FPORT_FRAME_ID_NULL`, but I wasn't testing specifically for that so if more info is needed I'll have to reflash the debug build and check.

**Comment by mikeller** [comment]
@fiam: Is iNav not going to implement FPort support?

**Comment by fiam** [comment]
@mikeller Basically the same code was merged in #4621. I couldn’t get my bench testing XSR to send the new frames, while the submitter of that PR had some hardware to test it, so it looked fair to me to merge their PR instead of mine.

**Comment by mikeller** [comment]
@fiam: Makes sense.

**Pull request closed without merging**
