### PR TITLE
tail sitter vtol support

### PR DESCRIPTION
**Pull request by shota3527**
More test needed
Still thinking about whether to use a PLATFORM_TAILSITTER  or set tailsitter = on  ,leaning towards tailsitter = on for less changes and more flexible setup

https://www.youtube.com/watch?v=V4Y81Pj3vs0&t=2s

### CODE REVIEW

**Comment by shota3527** [comment]
fc only bench test successful. Do anyone has a tail sitter to test it?

**Comment by FlyChenPiPi** [comment]
I compiled the 'sh_vtol' firmware for OMNIBUS F4V3 but don't know how to use the tail sitter vtol in the configurator

**Comment by FlyChenPiPi** [comment]
Great, I want to give it a try！

**Comment by shota3527** [comment]
https://www.youtube.com/watch?v=6PBpS8Vi4mQ&t=4s
https://www.youtube.com/shorts/rjCaG5UwgQc

**Comment by bsqg64** [comment]
Hi,
Thanks for this feature, I would like to test it on my plane (Atom RC penguin with speedybee F405 wing).
@shota3527 would you share your inav settings for your penguin ?
Cheers

**Comment by zoran-grujic** [comment]
> More test needed Still thinking about whether to use a PLATFORM_TAILSITTER or set tailsitter = on ,leaning towards tailsitter = on for less changes and more flexible setup
> 
> https://www.youtube.com/watch?v=V4Y81Pj3vs0&t=2s

I think that `PLATFORM_TAILSITTER` is wrong as one might mix different "platforms" into a VTOL. And those "platforms" already exist. For me tailsitter is mix of two platforms, and we just switch in between. 

I am also against `tailsitter = on`. My suggestion is to introduce additional variables that will give additional flexibility something like:

`VTOL_MIXER1_PITCH = 0` - a pitch in respect to the board alignment in deg (might be forced to 0 to be used in general)
`VTOL_MIXER2_PITCH = 90` - a pitch in respect to the board alignment 
`VTOL_TRANSITION_PITCH = 45` - a pitch in respect to the board alignment during transition phase

One can also force MIXER1 (or MIXER2 whatever seems more convinient) to have the alignment parallel to the board, thus avoiding possible confusion and over defining the problem.

I think that INAV would allow for full range of VTOLs, unlimited to tailsitters, with:

`VTOL_MIXER2_PITCH = 90` - a pitch in respect to the board alignment in deg
`VTOL_TRANSITION_PITCH = 45` - a pitch in respect to the board alignment during transition phase,

Nobody knows what people will invent in future. I suggest introduction of maximal flexibility already now.

I built a plank wing tailsitter and vertical flight works with 7.0. I will set transition into ACRO mode for horizontal flight in wing platform until 7.1 gets out.

**Comment by zoran-grujic** [comment]
> fc only bench test successful. next step is to confirm compass is also working as expected Do anyone has a tail sitter to test it?

I would be happy to test. At the moment I do not have GPS nor compass. And weather is getting bad in my part of Europe... My board is "SpeedyBee F405 WING APP"

**Comment by erik23de** [comment]
Can anyone please post a tailsitter diff somewhere, as a part of documentation? It's cool to see videos that Inav 7.1 can do that, but how? is an open question. The docs I read so far do not cover how to do that bicopter settings...
Thank you very much!

**Comment by Mick51** [comment]
Hello, I'd like to know if this feature will ever be released.

**Pull request merged**
