### PR TITLE
RC via MAVLink & MAVLink V2 Support

### LINKED ISSUE #6571: RC via Mavlink
## Current Behavior

Separate Mavlink and RC UART connections are required when using Crossfire. Or any control link, for that matter.

## Desired Behavior

Be able to control an aircraft using a single Mavlink UART via Crossfire. Also, control via joystick on GCS etc.

## Suggested Solution

Add Mavlink as a serial RX provider. Once selected, RC commands are taken from Mavlink.
**I plan to implement and PR this myself**.

## Who does this impact? Who is this for?

Anyone using Crossfire who wants Mavlink mission upload / telemetry and RC on the same UART (especially important on F411 chips!)

## Additional context

This is just a tracking issue to gauge interest (as I've seen this asked for before) and for any relevant discussion, **I plan to implement and PR this myself as long as maintainers think this would be a useful contribution**.

### PR DESCRIPTION
**Pull request by harryjph**
Closes #6571 

This PR

- Updates the MAVLink library to V2 (**this is the reason this PR is so huge, it's mostly auto generated, sorry 😢**)
- Implements some of the new V2 fields in the messages already in use
- Adds scripts for both Windows and Mac/Linux to easily automatically generate the MAVLink library should any updates be needed in the future
- Adds command line option `mavlink_version` to switch back to MAVLink V1 for backwards compatibility (defaults to V2)
- Adds serial receiver option "MAVLink". With this receiver option, MAVLink [RC Channels Override](https://mavlink.io/en/messages/common.html#RC_CHANNELS_OVERRIDE) messages are used as the RC signal. Failsafe works as expected when a message is not received for a long time. Supports up to 18 channels with MAVLink V2, only 8 with MAVLink V1. When using this option, whichever serial port is configured for MAVLink will be used for RC input, and the Serial RX option is ignored.

### CODE REVIEW

**Comment by harry1453** [comment]
Hm, looks like I need to make sure docs are updated. Do I just need to run `build_docs.sh`?

**Comment by avsaase** [comment]
You need to run `src/utils/update_cli_docs.py`

**Comment by harry1453** [comment]
@avsaase Thank you very much!

**Comment by harry1453** [comment]
Uh oh. Looks like this takes up **way** too much flash. I'm gonna have to minimize it a bit. I suspect that it's mostly the MAVLink implementation, although the compiler *should* be able to optimize away most of it...

**Comment by harry1453** [comment]
Looks like this consumes nearly 41k extra flash on F411.... yikes. I'll have to optimize it a lot. Seems like most of it is coming from the MAVLink library which *should* get mostly optimized away by the compiler... Obviously not...

**Comment by nathanjel** [comment]
Hey, maybe, just by the way, You could consider addressing #6577 in Your commits? :)

**Comment by DzikuVx** [comment]
@harry1453 any chance of optimization of the MAVLink in the next few weeks? I have a feeling F411 are not the only ones that are failing and the same happens with F722.
Maybe the way to go is to enable RC MAVlink override on all targets and MAVLink V2 only on targets with > 512 flash?

**Comment by harry1453** [comment]
@DzikuVx Yes, I'll get on to this as soon as I can. My current idea for optimization is to try and slim down the MAVLink library and remove all the messages that we aren't using. I don't know why but it appears that the compiler isn't optimizing them out when it should. Failing that we might, as you said, need a compiler switch for MAVLink V2... but that would make things very complicated as the libraries are different and every library call would need the compiler switch.

@nathanjel I'll take a look!

**Comment by harry1453** [comment]
Turns out the MAVLink library declares every single function as `inline`.

Target MATEKF411SE
Before: 452121 bytes (91.98%)
After:  455069 bytes (92.58%)

**Comment by DzikuVx** [comment]
@harry1453 please resolve conflicts and let's merge it. Thanks a lot!

**Comment by DzikuVx** [comment]
The time has come, let's merge it! Thanks a lot @harry1453

**Pull request merged**
