### PR TITLE
MSP add Launch settings for my modification inav configurator

### PR DESCRIPTION
**Pull request by pablitous**
this is for my modification inav configurator, i will write link to the pull request in the comments

### CODE REVIEW

**Comment by pablitous** [comment]
https://github.com/iNavFlight/inav-configurator/pull/1017

**Review by digitalentity — APPROVED** [review]
LGTM

**Comment by stronnag** [comment]
Rather than overloading a legacy message, would it not be more sensible to create a new MSP2 message? Launch parameters are distinct from the existing use case.

**Comment by stronnag** [comment]
and in either case, you should increment the MSP API version number

**Comment by giacomo892** [comment]
I think everything can be cleanly done without even touching the FC software.
Just by using common settings like I did here : https://github.com/iNavFlight/inav-configurator/pull/983/files

**Comment by pablitous** [comment]
> I think everything can be cleanly done without even touching the FC software.
> Just by using common settings like I did here : https://github.com/iNavFlight/inav-configurator/pull/983/files

yes, now i get it. thank you for yor help in telegram group. i will be posting an update in inav-configurator only. how can i close it? so no changes are made here in inav?

**Comment by pablitous** [comment]
@digitalentity i dont need this update, please cancel the pull request, im closing it. i dont know if thats all or if you now need to cancel the pull request. im sorry.

**Pull request closed without merging**
