### PR TITLE
Attempt at building master on sucessfull push

### PR DESCRIPTION
**Pull request by mmosca**
Attempt at building from master and create a pre-release inav-nightly.

* [x] Fix release name or clean up old files

### CODE REVIEW

**Comment by mmosca** [comment]
@DzikuVx once you are back and with access to a computer, we need:
* [ ] New repository to hold "nightly" builds of inav and inav-configurator
* [ ] Secret(s) to be able to cross publish a release to those repos

And eventually, make configurator look for releases in this other repo for bleeding edge builds. :)

**Comment by 0crap** [comment]
inav-nightly, that would be awesome. 👍

**Comment by rmaia3d** [comment]
> inav-nightly, that would be awesome. 👍

I 200% agree!! :-)

**Comment by OptimusTi** [comment]
> inav-nightly, that would be awesome. 👍 

Or a nightmare 😝

**Pull request merged**
