### PR TITLE
Add constrain for DynLPF computation

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by DzikuVx** [comment]
possibly fixes #9184 
possibly fixes problems in #9213

**Comment by ShadowWalker8642** [comment]
was this tested ? is it safe enough to use this commit?

**Comment by DzikuVx** [comment]
yes, it's safe @ShadowWalker8642

**Comment by ShadowWalker8642** [comment]
> yes, it's safe @ShadowWalker8642

thanks i will build and test this commit

**Pull request merged**
