### PR TITLE
MSP_CALIBRATION_DATA

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by digitalentity** [comment]
@DzikuVx this is a bit premature:

1. We also have mag calibration data - are we going to have a separate MSP mnessage for it?
2. What about 6-point calibration progress? I suggest adding an uint8 or uint16 bitfield for calibration status and calibration progress to this message.

**Comment by DzikuVx** [comment]
@digitalentity 

1. Mag calibration data is there https://github.com/iNavFlight/inav/pull/1101/files#diff-ffa49532e0a35299ef3e307058236e8eR1195 which other mag data do you have in mind?
1. Hmm... do we need it? My intention was not to change calibration process on FC side. But OK, let's think about it

**Comment by DzikuVx** [comment]
OK, I've put few minutes of thinking about it again.
This frame carries only calibration values, not statuses. If we will change the process and se FC to report calibration step (which will have no use in case of mag calibration) then MSP_STATUS_EX frame should be used instead.
@digitalentity thoughts?

**Comment by digitalentity** [comment]
We have new UI for 6-point calibration with reporting success for each step - we need API to report that to the Configurator - MSP_STATUS_EX is probably fine.

**Comment by digitalentity** [comment]
I'll make an extension to MSP_STATUS_EX - a bitfield to report calibration status.

**Comment by DzikuVx** [comment]
Agreed

**Comment by digitalentity** [comment]
@DzikuVx see https://github.com/iNavFlight/inav/pull/1106

**Pull request merged**
