### PR TITLE
Reorder blackbox fields

### PR DESCRIPTION
**Pull request by breadoven**
Moves blackbox `activeWpNumber `and `rxUpdateRate `fields to better position in BB Explorer field table.

### CODE REVIEW

**Comment by stronnag** [comment]
Out of interest, why is there no 23?

**Comment by breadoven** [comment]
> Out of interest, why is there no 23?

Killswitch mode removed recently.

**Comment by stronnag** [comment]
Thanks. It (briefly) broke the `blackbox-tools-inav` code generator ....

**Comment by breadoven** [comment]
Ah, forgot about `blackbox-tools-inav`.

This stuff really needs fixing properly. It's confusing that it shows `flightModeFlags `in BB Explorer, which you would assume are the currently active flight modes, whereas in fact it's just showing the currently selected boxmodes which aren't necessarily "flight" modes as such or even active,

**Comment by stronnag** [comment]
> Ah, forgot about `blackbox-tools-inav`.
> 
> This stuff really needs fixing properly. It's confusing that it shows `flightModeFlags `in BB Explorer, which you would assume are the currently active flight modes, whereas in fact it's just showing the currently selected boxmodes which aren't necessarily "flight" modes as such or even active,

It really needs to be done is a way that doesn't break every blackbox analysis tool in existence, e.g. as suggested previously by adding a new field for the bits > 31. That way extant tools still work and people who want bits > 31 can extract them from the new field.

**Comment by breadoven** [comment]
> > Ah, forgot about `blackbox-tools-inav`.
> > This stuff really needs fixing properly. It's confusing that it shows `flightModeFlags `in BB Explorer, which you would assume are the currently active flight modes, whereas in fact it's just showing the currently selected boxmodes which aren't necessarily "flight" modes as such or even active,
> 
> It really needs to be done is a way that doesn't break every blackbox analysis tool in existence, e.g. as suggested previously by adding a new field for the bits > 31. That way extant tools still work and people who want bits > 31 can extract them from the new field.

I'm thinking now that it might be easier to leave the `boxId_e `as is and instead just to add another slowfield to blackbox for active flight modes based on the actual `flightModeFlags `bit mask since this is currently not recorded by the log. Logging additional box mode selections > 32 would then be a separate issue although the current blackbox "flightModeFlags" should be renamed to what it actually is ... boxModeFlags (unless this breaks things also ... haven't checked yet).

**Pull request merged**
