### PR TITLE
Use GPS and DCM to estimate the airspeed for fixwing.

### PR DESCRIPTION
**Pull request by Linjieqiang**

### CODE REVIEW

**Comment by Linjieqiang** [comment]
This is the theoretical basis of code.
[WindEstimation.pdf](https://github.com/iNavFlight/inav/files/1366582/WindEstimation.pdf)
http://diydrones.com/forum/topics/wind-estimation-without-an

**Comment by digitalentity** [comment]
Interesting idea, however it assumes that wind is constant which is rarely true. 

A few more thoughts:

1. This code requires that DCM estimates true heading which is only possible when using a compass
1. Not all GPS units are providing velocity in 3D space - you need to check gpsSol validity flags.
1. Your code doesn't check if required sensors are available. The problem is that with GPS temporary unavailable our airspeed will be completely off which may cause problems.

In general I like the idea, but it needs to be refined.

**Comment by Linjieqiang** [comment]
The idea was from MatrixPilot and ArduPlane project on github.The MatrixPilot project only uses gyro and acc and gps without compass to estimate the wind.The ublox gps module can get the 3D velocitys so I will fix my code later.Also when got the airspeed, we can use "TECS" algorithm to control plane altitude very well.

**Comment by Linjieqiang** [comment]
Thanks @flam .I will close this pr..

**Pull request closed without merging**
