### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jaymal66**
# INAV_smartport.c_reloaded
Comprehensive Flight Modes  reporting  via SmartPort telemetry.

The aim here is to report via SmartPort telemetry the state of ALL flight modes enumerated in the INAV configurator.
Thus users (MM and FW) aren't anymore limited to an arbitrary subset to pick those modes which they want to monitor on their FrSky TX.
6 additional modes are now included HOME_RESET, NAV_LAUNCH, FLAPERON, TURN_ASSIST, AUTOTRIM and AUTO_TUNE.
Also a more efficient encoding of the modes states is used to move more information within the bandwidth provided by the tmp1 container # something which in turn provide room to include easily further modes .
The modified smartport.c has been tested with 1.7.3 and can be implemented with a custom build simply by replacing the original one.
The same should hold for  1.8 RC1 since to my knowledge  1.8 RC1 and 1.7.3 share the same smartport.c . 
Documentation at this time is limited to the comments in the section of the  code  dealing with the tmp1 container.
A prototype of the Lua code to decode the new encoding scheme of the tmp1 container is available on request.

### CODE REVIEW

**Comment by digitalentity** [comment]
`smartport.c` is very much different between 1.7.3 and 1.8-RC1. All PRs should be based on `development` branch. Please rebase your changes.

**Comment by jaymal66** [comment]
#digitalentity
I found  only 3 diffs between the smartport.c  of 1.7.3 and 1.8 rc1
1)	Line 26      	#include "fc/rc_modes.h"         is added
2)	Line 389             bool smartPortSendMspReply()    “void”  removed from between the  ()
3)	Line 689             if (ARMING_FLAG(ARMED) && IS_RC_MODE_ACTIVE(BOXHOMERESET) &&   !FLIGHT_MODE(NAV_RTH_MODE) && !FLIGHT_MODE(NAV_WP_MODE))
Both  1) and 2) are trivial   since 1)  is also included in the  proposed new version and 2) irrelevant  to how tmp1 is handled
The  3rd change  Line 689      raises however the following  basic issue  : 
the purpose here is clearly  to check  if the condition of a Home Reset are really meet and not to rely alone on  IS_RC_MODE_ACTIVE(BOXHOMERESET) . BUT isn’t that, if really necessary, something which should take place  not in smartport.c but wherever  the  BOXHOMERESET flag is set to active or not ?
In the  proposed new version “IS_RC_MODE_ACTIVE(BOXHOMERESET)” is used alone to decide if the state of the HOME RESET   is identified as  active or not
So let me know if you insist  having   line 689 taken over as is in  the  rebased new version  .

**Comment by digitalentity** [comment]
Ok, looks like I was in fact wrong and `smartport.c` didn't change much. However, your PR still needs to be rebased to `development` branch to be able to merge. Also, you probably don't have line endings right - the diff for this PR shows that you changed every single line in the file.

To make things easier for everyone to monitor, I'll open a new PR with changes from this one but with proper line endings, so we could review and discuss.

**Comment by digitalentity** [comment]
Superceded by #2394

**Pull request closed without merging**
