### PR TITLE
Add Betaflight "HD" compatibility

### PR DESCRIPTION
**Pull request by mmosca**
Same as BF43COMPAT, but with a BF4.4 HD canvas size.

DJI finally implemented HD canvas. This adds an HD option to BF43COMPAT, time to test this! :)

### CODE REVIEW

**Comment by rmaia3d** [comment]
DJI has just released today (March 27th, 2023) a firmware update for both FPV Goggles V2 and Goggles 2 that includes (pasted from the Release Notes):

`•    Added support for Betaflight 4.4 HD OSD when used with DJI O3 Air Unit.`

So maybe this PR has become very relevant? :)

**Comment by mmosca** [comment]
I need to confirm canvas size.

**Comment by mmosca** [comment]
Confirmed, 53x20

**Comment by mmosca** [comment]
image
survived 5s bench test.

**Comment by rmaia3d** [comment]
IMG_6413

Can also confirm a successful initial test!

**Pull request merged**
