### PR TITLE
Initial KroozX port

### PR DESCRIPTION
**Pull request by softsr**
An initial port for the KroozX combo flight controller:
https://github.com/betaflight/betaflight/wiki/Board---KroozX

### CODE REVIEW

**Comment by oleost** [comment]
Hi, welcome to INAV.

We develop towards development branch and not master, could you change it?

Also would be nice if you got make an description of board in /docs/ folder. ( Check some of the others for reference )

**Comment by digitalentity** [comment]
@softsr Hi, thanks for the PR. Please add board description to /docs/ folder and we'll merge this.

**Comment by softsr** [comment]
@digitalentity Hello! My pleasure! The description also comes soon.

**Comment by digitalentity** [comment]
@softsr how is that desctiption going? I would really like to merge this ASAP

**Comment by softsr** [comment]
I'm almost ready with it.

>
> @softsr how is that desctiption? I would really like to merge this ASAP
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/

**Comment by digitalentity** [comment]
Thanks, merging

**Pull request merged**
