### PR TITLE
Migrate to Parameter Group config storage (catch-up with CF)

### PR DESCRIPTION
**Pull request by digitalentity**
This is for keeping track of progress and discussing changes

### CODE REVIEW

**Comment by DzikuVx** [comment]
And now I will have to rebase #148 again :)

**Comment by digitalentity** [comment]
@DzikuVx this PR is unfinished and will take a while - I have ~160 commits to go through. Probably #148 will be merged sooner than this one :smile:

**Comment by digitalentity** [comment]
Ok, enough for today. It builds, but I didn't flash and debug it yet.

**Comment by digitalentity** [comment]
This is now ~50% done! Cool!

**Comment by martinbudden** [comment]
@digitalentity , what's the status on this one? I think this is a **really** important thing to get done. Until this is done we won't really be able to pull anything over from Cleanflight.

**Comment by digitalentity** [comment]
I don't have much time to spend on this one. I'd say it's about 70% done.

**Comment by martinbudden** [comment]
Any way I can help?

**Comment by digitalentity** [comment]
@martinbudden
I was cherry-pitcking commits from https://github.com/cleanflight/cleanflight/pull/1976 and stopped at 82b2350ccaa1125cfbb16594a5ef163dd204c8bd. I also didn't do anything to unit-tests - my intention was to address them after main code is ported. If you can help with finalising this - you are more than welcome to do so! :+1:

**Comment by digitalentity** [comment]
@martinbudden maybe you can suggest an easier way to port param group stuff here? I'd like to have this merged ASAP but I'm overwhelmed with number of commits to process.

**Comment by martinbudden** [comment]
@digitalentity , there is the question of how this interacts with the F4 target port.

My current plan is to to help in betaflight with F4 cleanup and bug fixes, and then once that is all working well move the `drivers` directory over from betaflight in its entirety. That will also mean that targets can be pulled directly over from betaflight.

That won't be possible if the parameter group stuff is ported first.

Once the F4 port is done, my plan is to then port the parameter group stuff, which I reckon I could probably do in one evening of solid focused work.

There are two options:
1. Finish F4 port, then port parameter groups.
2. Port parameter groups, then finish F4 port.

Why view is that option (1) will entail considerably less work overall, so it is what I favour. All in all, I reckon this can be done in a few weeks.

Once parameter groups are ported to iNav, my aim is then to port help port them to betaflight and then help with the Cleanflight F4 port.

Although iNav, betaflight, and Cleanflight have differing goals and emphases, I see no reason by the the code in `drivers` should not be **identical** for all three forks. It will take a little while to get there, but I think that has significant advantages for all three forks.

( @hydra , @borisbstyle, @sambas , - any thoughts on the above? )

**Comment by skaman82** [comment]
@martinbudden could you maybe also port parameter groups to BF when you are working on this?

**Comment by martinbudden** [comment]
@skaman82 , yes helping port parameter groups to betaflight is part of the plan above, providing  @borisbstyle want to do that.

**Comment by digitalentity** [comment]
@martinbudden I totally agree that drivers should be **identical** between CF/BF/INAV as they share the same hardware and there is no point in having separate HALs. Ok, I'll wait for F4 to be finished first and pulled over to INAV from Betaflight. Thanks for looking into this.

**Comment by hydra** [comment]
totally agreed with the drivers being identical.  in the mean time i have the osd and menu stuff to work so it works out well timescale wise.
On Jun 24, 2016 12:19 PM, Martin Budden notifications@github.com wrote:@digitalentity , there is the question of how this interacts with the F4 target port.

My current plan is to to help in betaflight with F4 cleanup and bug fixes, and then once that is all working well move the drivers directory over from betaflight in its entirety. That will also mean that targets can be pulled directly over from betaflight.

That won't be possible if the parameter group stuff is ported first.

Once the F4 port is done, my plan is to then port the parameter group stuff, which I reckon I could probably do in one evening of solid focused work.

There are two options:
1. Finish F4 port, then port parameter groups.
2. Port parameter groups, then finish F4 port.

Why view is that option (1) will entail considerably less work overall, so it is what I favour.

Once parameter groups are ported to iNav, my aim is then to port help port them to betaflight and then help with the Cleanflight F4 port.

Although iNav, betaflight, and Cleanflight have differing goals and emphases, I see no reason by the the code in drivers should not be identical for all three forks. It will take a little while to get there, but I think that has significant advantages for all three forks.

(@hydra , @borisbstyle , - any thoughts on the above?)

**Comment by martinbudden** [comment]
@digitalentity , I've moved this to the 1.3 milestone and self-assigned the work.

**Comment by digitalentity** [comment]
@martinbudden thanks! I appreciate your hard work on this codebase.

**Comment by martinbudden** [comment]
Closing, superceded by issues
1. https://github.com/iNavFlight/inav/issues/472 - Preparation for conversion to parameter groups
2. https://github.com/iNavFlight/inav/issues/473 - Convert to parameter groups

**Pull request closed without merging**
