### PR TITLE
FPV camera control

### PR DESCRIPTION
**Pull request by alex-martynov**
FPV camera virtual joystick from Betaflight
https://www.youtube.com/watch?v=gxg5Y6f4EU4
Tested only on OMNIBUSF4PRO target. Need to define USE_CAMERA_CONTROL and CAMERA_CONTROL_PIN macro on another

### CODE REVIEW

**Comment by junwoo091400** [comment]
Nice

**Comment by throttlenerd** [comment]
Hey guys so is it working? "resource camera_control 1 a01" does nothing.

**Comment by stronnag** [comment]
It's working, as setting resources is defined to be not implemented on iNav.

**Comment by robustini** [comment]
It is serious that there has not been an evolution of this PR, it would have been very useful.

**Comment by robustini** [comment]
> 
> 
> FPV camera virtual joystick from Betaflight
> https://www.youtube.com/watch?v=gxg5Y6f4EU4
> Tested only on OMNIBUSF4PRO target. Need to define USE_CAMERA_CONTROL and CAMERA_CONTROL_PIN macro on another

Could you please align your implementation to the current code on the master branch?
Thanks!

**Comment by robustini** [comment]
The integration for the camera control is in my repo, aligned to the last INAV master.

https://github.com/robustini/inav/commit/c3c659c4be4868587daeee74265b5c82bd680456

**Comment by robustini** [comment]
I have integrated the camera control into my repo, updated to the latest master.

https://github.com/robustini/inav/commit/989eff12430714709d9432ea66c79b701bf00971

**Comment by giacomo892** [comment]
> I have integrated the camera control into my repo, updated to the latest master.
> 
> [robustini@989eff1](https://github.com/robustini/inav/commit/989eff12430714709d9432ea66c79b701bf00971)

Feel free to push your changes here. Thanks

**Comment by robustini** [comment]
> 
> 
> > I have integrated the camera control into my repo, updated to the latest master.
> > [robustini@989eff1](https://github.com/robustini/inav/commit/989eff12430714709d9432ea66c79b701bf00971)
> 
> Feel free to push your changes here. Thanks

I think it is correct that it does so in case the author of the PR.

**Comment by robustini** [comment]
Code updated and video showing how it works.
I hope this is taken into consideration for release 3, the camera control settings is very useful.

https://youtu.be/vjMvWp4u8Zg

**Comment by giacomo892** [comment]
> Code updated and video showing how it works.
> I hope this is taken into consideration for release 3, the camera control settings is very useful.
> The code will certainly be improved by including the descriptions for the CLI, but this already works.
> Thanks to Alex for the first implementation!
> 
> https://youtu.be/vjMvWp4u8Zg

Open a new PR and it will supersede with one. It's ok to do so.

**Comment by RomanLut** [comment]
@DzikuVx 
As https://github.com/iNavFlight/inav/pull/9201 is merged, this PR can be closed.

**Pull request closed without merging**
