### PR TITLE
Replace locale-aware libc functions with simpler versions

### PR DESCRIPTION
**Pull request by digitalentity**
Looks like `libc` pulls in locale-aware functions and lookup tables. This wastes a noticable amount of FLASH and RAM. This PR replaces locale-aware functions with simpler variants that assume ANSI locale.

On CC3D saves 688 bytes of FLASH and 364 bytes of RAM.

Before: 
```
arm-none-eabi-size ./obj/main/inav_CC3D.elf
   text    data     bss     dec     hex filename
 125186    1408   16096  142690   22d62 ./obj/main/inav_CC3D.elf
```

After:
```
arm-none-eabi-size ./obj/main/inav_CC3D.elf
   text    data     bss     dec     hex filename
 124498    1044   16096  141638   22946 ./obj/main/inav_CC3D.elf
arm-none-eabi-objcopy -O ihex --set-start 0x8000000 obj/main/inav_CC3D.elf obj/inav_1.7.3_CC3D.hex
```

### CODE REVIEW

**Comment by fiam** [comment]
@digitalentity Nice one!

**Comment by digitalentity** [comment]
We might even be able to keep NAZE around for next release :laughing:

**Comment by martinbudden** [comment]
@DzikuVx will be so pleased!

**Comment by digitalentity** [comment]
@martinbudden you misspelled the word expressing extreme annoyance :rofl:

**Comment by giacomo892** [comment]
@DzikuVx will be so happy to have another glass of whisky

**Comment by stronnag** [comment]
Unfortunately this has a negative side effect; it ignores numeric values less than zero, e.g:
````
# set acczero_y = -83
acczero_y set to 0
# set mag_declination = -100
mag_declination set to 0
# set acczero_z = -336
acczero_z set to 0
# set magzero_y = -126
magzero_y set to 0
# set magzero_z = -27
magzero_z set to 0
# 
````
Other than this, a `diff` was restored without other further anomalies.
Including negative values in custom `mmix` being correctly set.

So, naively,
````
int sl_atoi(const char * s)
{
    int num = 0;
    int digit;
    int sign=1;

    if(*s == '-') {
        sign = -1;
        s++;
    }
    while ((digit = a2d(*s)) >= 0) {
        if (digit > 10)
            break;
        num = num * 10 + digit;
        s++;
    }

    return num*sign;
}
````
No unexpected differences between pre/post `diff` with the sign fix.

**Comment by digitalentity** [comment]
@stronnag thanks, I obviously forgot about negative values. Will fix

**Comment by fiam** [comment]
Just remembered something else what your typical libc number parsing functions do: ignore whitespace at the beginning. Since INAV is using those to parse user input, it will probably be better to add that to the custom `atoi` implementation.

Just a small test to be sure:
```
muk:tmp fiam$ gcc t.c -o t
muk:tmp fiam$ ./t 
42
-42
0
muk:tmp fiam$ cat t.c 
#include <stdio.h>
#include <stdlib.h>

int main() {
    printf("%d\n", atoi("   42")); // returns 42
    printf("%d\n", atoi("   -42")); // returns -42
    printf("%d\n", atoi("   - 42")); // returns 0, space between - and 42 is not valid
}
```

Just regarding `atoi`, I think that for consistency reasons we should replace it with a function named `fastA2I` and implement it in `common/typeconversion.{h,c}`, same files as `fastA2F` and `fastA2UL`. Also, `atoi` it's not in `string.h`, but in `stdlib.h`.

**Comment by digitalentity** [comment]
Negative values and ignoring trailing whitespaces work fine. Merging.

**Pull request merged**
