### PR TITLE
Fix Cruise mode MSP box active check

### PR DESCRIPTION
**Pull request by nmaggioni**
Fixes iNavFlight/inav-configurator#1279 for #6904.

Paging @shellixyz for review.

### CODE REVIEW

**Comment by MrD-RC** [comment]
Does this also fix failsafe, which was also always highlighted?

**Comment by nmaggioni** [comment]
@MrD-RC FS seems to light up correctly here. Stupid question: is your TX turned on? FS will be enabled regardless of its mode's range if the RX is not receiving data.

**Comment by MrD-RC** [comment]
@nmaggioni That would be pretty silly. But honestly, I can’t confirm or deny 🤣 If it is something that foolish, it caught @Jetrell out too. I will double check and follow up shortly.

**Comment by MrD-RC** [comment]
Failsafe is fine on RC1. My Rx was unplugged 🤣

**Comment by shellixyz** [comment]
Would have been better IMO to fix `CHECK_ACTIVE_BOX`

**Comment by shellixyz** [comment]
#7049

**Pull request merged**
