### PR TITLE
FrSkyPilot target variation

### PR DESCRIPTION
**Pull request by MrD-RC**
I have added a new target variation for the FrSky Pilot flight controllers. This adds LED support on Ch10. PWM only Ch1-9 with this target. UART 3 on Ch 11 & 12.

Just to clarify, this is not a new target, it is based on and existing target.

### CODE REVIEW

**Comment by MrD-RC** [comment]
https://youtu.be/n5vSelw_CM0

**Comment by MrD-RC** [comment]
Added documentation file

**Comment by DzikuVx** [comment]
@MrD-RC please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by MrD-RC** [comment]
@DzikuVx All 3 of those new target requirements would have been met when the original target created. Surely to submit a variant like this, I shouldn’t be required to buy and provide flight controllers for core developers, when I’ve done the work and it’s all fine? I can understand that policy for new targets, but this just adds a feature to an existing target and literally took 5 minutes. 

I think the target variants procedure and requirements needs to be clarified.

**Comment by shellixyz** [comment]
@MrD-RC Don't worry, you don't have to provide boards. Pawel thought none of the devs had any of these but it is not the case

**Review by shellixyz — APPROVED** [review]
LGTM

**Pull request merged**
