### PR TITLE
Drop D-term RPM filtering

### PR DESCRIPTION
**Pull request by DzikuVx**

### CODE REVIEW

**Comment by giacomo892** [comment]
Shouldn't we drop this in 2.4 final?

**Comment by DzikuVx** [comment]
I don't want to touch 2.4 at this point

**Comment by giacomo892** [comment]
I see, but since we are dropping this feature it might save a PG version increment and update troubles (cancel a line in a dump)

**Comment by DzikuVx** [comment]
good catch on PG version. Bumped

**Pull request merged**
