### PR TITLE
Add RC adjustments for board alignment

### PR DESCRIPTION
**Pull request by shellixyz**
Linked with issue #2384

### CODE REVIEW

**Comment by digitalentity** [comment]
Looks ok to me. If testing will come back good - let's merge

**Comment by digitalentity** [comment]
@shellixyz I've merged this. I've tested it on a quad and it's safe enough to use.

**Comment by shellixyz** [comment]
OK great!

**Comment by choyado** [comment]
I saw that this has been added to Inav 1.9 but I cannot find any documentation on how to use or implement it.

**Comment by shellixyz** [comment]
@choyado It is done like the other adjustments, see https://github.com/iNavFlight/inav/blob/master/docs/Inflight%20Adjustments.md

**Pull request merged**
