### PR TITLE
Added possibility to shift GPS lat/lon to a custom value. Useful for …

### PR DESCRIPTION
**Pull request by sevrugin**
Sometimes we need to hide our GPS location from other people but be able to see recorded video and decrypt our position
My suggestion is to add few parameters: `osd_gps_shift_lat` / `osd_gps_shift_lon` for shifting our real coordinates for this value.
As we know both values we will be able to restore original coordinates any time

### CODE REVIEW

**Comment by mujtabachang** [comment]
I like this idea. Devs should consider merging this

**Comment by OptimusTi** [comment]
It would make more sense to put them on a switch.

**Comment by MrD-RC** [comment]
This was on a Vector I was using. Only I didn’t set it up or know about it. It was very confusing when looking for the model and it appearing to be 10 miles away, which would have been impossible.

@OptimusTi I don’t really get the switch proposition. If you want the Coordinates masked, it would be all the time. The only reason for this is to confuse snooping people watching your video feed. I can’t think of any other reason to have it.

**Comment by OptimusTi** [comment]
> This was on a Vector I was using. Only I didn’t set it up or know about it. It was very confusing when looking for the model and it appearing to be 10 miles away, which would have been impossible.
> 
> 
> 
> @OptimusTi I don’t really get the switch proposition. If you want the Coordinates masked, it would be all the time. The only reason for this is to confuse snooping people watching your video feed. I can’t think of any other reason to have it.

Setting a second OSD screen without coordinates is easy

**Comment by sevrugin** [comment]
I would like to record my osd screen with fake coordinates to be able to find it on crash but don't like to other people know where I am or my plane

**Comment by MrD-RC** [comment]
> Setting a second OSD screen without coordinates is easy

I know that. I only have coordinates on my default OSD. If I !FS! It automatically switches to the default OSD. 

But that is not the same thing. If the only reason is to protect the actual coordinates from snoopers, you don’t know when they’re snooping. So any modifications to the GPS coordinates has to be permanent. The idea is you need to be able to see the coordinates, but only you can decipher them.

**Comment by sevrugin** [comment]
Can someone promote this PR?

**Comment by breadoven** [comment]
A lot of people use Plus Codes instead of Lat, Lon to save space on the OSD. Would it be possible to update this to also include Plus codes ?

**Comment by Yury-MonZon** [comment]
What happened in the end?
No one needs it anymore?

**Comment by MrD-RC** [comment]
The change is outdated. So would need to be brought in line with the current master branch.

**Comment by mmosca** [comment]
Closing, as this one is stale.

**Pull request closed without merging**
