### PR TITLE
OSD system message improvements

### PR DESCRIPTION
**Pull request by breadoven**
Mainly cleans up OSD system messages according to craft type plus following changes. 

The maximum number of messages possible is defined for the main different message categories to clarify the maximum total number of messages possible. Maximum messages possible is currently 6 although this includes a "Save Settings" message which is only displayed briefly so really there should normally be no more than 5 messages.

Fixed wing modes Autotrim, Autotune and Auto Level have been prioritised so only one mode can be active at a time reducing 3 potential mode activation messages being displayed together down to a single message. Priority has been set to Autotune->Autotrim->Autolevel.

### CODE REVIEW

**Comment by MrD-RC** [comment]
I don't think they consolidation of the auto trim/tune/level trim is needed. They should be used separately.

**Comment by breadoven** [comment]
> I don't think the consolidation of the auto trim/tune/level trim is needed. They should be used separately.

A better solution would be to only allow a single mode to be active at a time. There's no reason they should be active at the same time given what they do, they interfere with each other.

**Comment by 0crap** [comment]
> I don't think the consolidation of the auto trim/tune/level trim is needed. They should be used separately.

Agreed.
Definitely not an improvement for the end user and will only lead to confusion.
Why the need to change this and not leave it as it is? It's working fine now...

**Comment by breadoven** [comment]
> > I don't think the consolidation of the auto trim/tune/level trim is needed. They should be used separately.
> 
> Agreed. Definitely not an improvement for the end user and will only lead to confusion. Why the need to change this and not leave it as it is? It's working fine now...

It's to reduce the number of potential messages to keep message overload to a minimum. As mentioned above though, the better solution is to prioritise these fixed wing auto tune/trim modes so only one can be selected at a time. Unless I'm missing something I can't see any reason why you'd want to use even 2 of them together at the same time.

**Comment by breadoven** [comment]
Any objections to merging this ?

**Comment by 0crap** [comment]
If I still see the OSD message Autotrim, Autotune and Auto Level when activated I'm fine.

**Comment by breadoven** [comment]
> If I still see the OSD message Autotrim, Autotune and Auto Level when activated I'm fine.

The messages will appear as they did before but you'll only be able to select one of the modes at a time. Guess I'll just merge and wait to see if there are any complaints.

**Pull request merged**
