### PR TITLE
QMC5883 compass support

### PR DESCRIPTION
**Pull request by digitalentity**
Implementation of https://github.com/iNavFlight/inav/issues/1903

### CODE REVIEW

**Comment by georgekucher** [comment]
Hi DE, I'll test it today))))

**Comment by georgekucher** [comment]
Thank you!

**Comment by georgekucher** [comment]
That's what I got for now:

# status
System Uptime: 18 seconds
Voltage: 3 * 0.1V (1S battery - NOT PRESENT)
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=MS5611
Sensor status: GYRO=OK, ACC=OK, MAG=FAILING, BARO=OK, RANGEFINDER=NONE, GPS=NONE
Stack size: 2048, Stack address: 0x20005000
I2C Errors: 0, config size: 1410, max available config: 2048
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = ADC 3, used = none
   CURRENT : configured = ADC 1, used = none
  AIRSPEED : configured = none, used = none
System load: 4, cycle time: 2010, PID rate: 497, RX rate: 49, System rate: 9

**Comment by oleost** [comment]
What does your mag_hardware say? And have you manually tried selecting the new mag? ( Also try a new Auto ? )

**Comment by georgekucher** [comment]
Firstly I compiled NAZE target. By the way there was trouble with it, "WS2811_DMA_STREAM not defined compiler was saying". I don't know which channel to set. Anyway, I disabled LED_STRIP for now.
After that I tried to find QMC mag in drop down but it is missing. I tried AUTO and also setting it with "set mag_hardware = QMC5883", but nothing.

# get mag_hardware
mag_hardware = QMC5883
Allowed values: NONE, AUTO, HMC5883, AK8975, GPSMAG, MAG3110, AK8963, IST8310, QMC5883, FAKE

P.S. I see FAKE mag selected at the UI drop down

**Comment by georgekucher** [comment]
By the way. Are NAZE targets still supported? Why MAG and LED_STRIP updates weren't added to  their configs?

**Comment by DzikuVx** [comment]
@georgekucher Please bear in mind that Naze and other F1 board are near end of life devices. Not enought flash space to fit all new things

**Comment by georgekucher** [comment]
my board is F3
http://www.readytoflyquads.com/flip32-aio
isnt'n it?

**Comment by giacomo892** [comment]
@georgekucher you board is a NAZE (F1)

**Comment by georgekucher** [comment]
Oh.. Pity(( 
However I still can compile my own configed firmware.

**Comment by georgekucher** [comment]
My Arduino UNO has just arrived
QMC works with it!!))))
Here is the sketch https://github.com/mechasolution/Mecha_QMC5883

And output:

X Value: 188
Y Value: -238
Z Value: -968

X Value: 183
Y Value: -246
Z Value: -980

X Value: 183
Y Value: -241
Z Value: -968

X Value: 186
Y Value: -238
Z Value: -975

X Value: 191
Y Value: -226
Z Value: -966

X Value: 183
Y Value: -228
Z Value: -961

X Value: 176
Y Value: -248
Z Value: -977

X Value: 188
Y Value: -228
Z Value: -968

**Comment by georgekucher** [comment]
Hey guys,
Is there any chance that my MAG is failing because of the "QMC5883L_ODR_100HZ" value?
I've noticed that in before mentioned arduino code it is set to 200HZ.
Sorry for silly suggestions (if they are so)

**Comment by georgekucher** [comment]
Hello.
Can anyone confirm or refute my test result?

**Comment by digitalentity** [comment]
What firmware do you try? If it is a custom-built firmware - make sure you have `USE_MAG_QMC5883` defined.

**Comment by georgekucher** [comment]
I built a firmware from 'de_qmc5883_compass' branch with NAZE target updated
USE_MAG_QMC5883 was defined

**Comment by georgekucher** [comment]
I can fork that branch and push my customization to it so you could check if I made right changes for NAZE

**Comment by digitalentity** [comment]
@georgekucher would be good to verify, yes. Also, I've purchased myself this module: https://www.aliexpress.com/item/GY-271-HMC5883L-module-electronic-compass-compass-module-three-axis-magnetic/710707414.html - when it arrives I'll be able to validate the code myself.

**Comment by georgekucher** [comment]
Ok, I'll do it later today. Thank you.

**Comment by georgekucher** [comment]
Here it is
https://github.com/georgekucher/inav/tree/de_qmc5883_compass

**Comment by digitalentity** [comment]
Hm... it should be working. I guess I'll have to wait for my sensor

**Comment by zuoquezi** [comment]
@georgekucher   Hi georgekucher! Can you help me .I have a qmc5883_compass too.  But I do not know how to use Github to generate HEX. So  can you  give me a Naze32 's hex and sp-racingf3's hex?thank you very much!my email address  541016294@qq.com   thank you  again

**Comment by georgekucher** [comment]
done

**Comment by zuoquezi** [comment]
hi georgekucher  I used your code to generate a hex, but it did not work

**Comment by digitalentity** [comment]
QMC5883 evaluation board should arrive in the next few days - I'll be able to debug then.

**Comment by zuoquezi** [comment]
so great ！

**Comment by digitalentity** [comment]
Fixed incorrect byte order in compass driver. Works now. Tested on GY-271 breakout board for QMC5883L.

**Comment by georgekucher** [comment]
Hoorayyyyy!!!!
I will test it ASAP)))
Thanks

**Comment by zuoquezi** [comment]
hooray

**Comment by zuoquezi** [comment]
@georgekucher ！Do you have a try?

**Comment by georgekucher** [comment]
can't build Firmware from development branch((

**Comment by georgekucher** [comment]
I have built it with fixes in driver file but MAG is still failing
Please help

**Comment by digitalentity** [comment]
@georgekucher what mag are you using? Can you take a close-up picture?

**Comment by georgekucher** [comment]
qmc5883l I'll try to take a photo
But it works with Arduino

**Comment by georgekucher** [comment]
img_20170830_162929

**Comment by georgekucher** [comment]
GY-271

**Comment by digitalentity** [comment]
Interesting. The same board I've tested with. What FC and firmware are you using?

**Comment by georgekucher** [comment]
http://www.readytoflyquads.com/flip32-aio
NAZE

**Comment by georgekucher** [comment]
1.7.3
custom build

**Comment by georgekucher** [comment]
seems like you have GY-273

**Comment by digitalentity** [comment]
Oh, QMC compass might be not enabled for NAZE target. It's actually 271, I mistyped (fixed the comment now)

**Comment by georgekucher** [comment]
could you compile a hex for me?
maybe I'm doing something wrong.. I don't know..

**Comment by georgekucher** [comment]
I defined it in target.h and target.mk

**Comment by georgekucher** [comment]
maybe I2C speed? Or something else?

**Comment by digitalentity** [comment]
I'm not sure. I'll build a NAZE hex for you soon.

**Comment by georgekucher** [comment]
Thanks. By the way, which voltage you supplied?

**Comment by digitalentity** [comment]
5V, the board has it's own 3.3V LDO

**Comment by digitalentity** [comment]
https://github.com/iNavFlight/inav/pull/2062

**Comment by georgekucher** [comment]
I've got an error while building the hex
```
settings.yaml -> settings_generated.h, settings_generated.c
/bin/sh: ruby: command not found
make: *** [Makefile:930: src/main/fc/settings_generated.h] Error 127

```

**Comment by digitalentity** [comment]
You need Ruby to build latest development branch - https://rubyinstaller.org/
Here's the hex for NAZE 
[inav_1.7.3_NAZE.zip](https://github.com/iNavFlight/inav/files/1263966/inav_1.7.3_NAZE.zip)

**Comment by georgekucher** [comment]
woooohhoooo!!!!
it's alive!!!!
thanks a lot!!!
going to test position hold now))))

**Comment by zuoquezi** [comment]
@digitalentity thank you verymuch

**Comment by georgekucher** [comment]
one more question about building in windows
I installed ruby and got
```
$ make TARGET=NAZE
settings.yaml -> settings_generated.h, settings_generated.c
C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - arm-none-eabi-g\+\+ -mthumb -mcpu\=cortex-m3 -flto -fuse-linker-plugin -Os -I./src/main -I./src/main/target -I./lib/main/STM32F10x_StdPeriph_Driver/inc -I./lib/main/CMSIS/CM3/CoreSupport -I./lib/main/CMSIS/CM3/DeviceSupport/ST/STM32F10x -I./lib/main/MAVLink -I./src/main/target/NAZE -ggdb3 -DDEBUG -std\=c\+\+11 -Wall -Wextra -Wunsafe-loop-optimizations -Wdouble-promotion -ffunction-sections -fdata-sections -DSTM32F10X_MD -DSTM32F10X -DFLASH_SIZE\=128 -DHSE_VALUE\=8000000 -DUSE_STDPERIPH_DRIVER -DNAZE -pedantic -D__FORKNAME__\=inav -D__TARGET__\=NAZE -D__REVISION__\=3b863aea -o obj/tmp/test obj/tmp/test.cpp (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:95:in `popen3'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:258:in `capture3'
        from ./src/utils/settings.rb:614:in `block in compile_test_file'
        from ./src/utils/settings.rb:568:in `mktmpdir'
        from ./src/utils/settings.rb:590:in `compile_test_file'
        from ./src/utils/settings.rb:637:in `check_conditions'
        from ./src/utils/settings.rb:275:in `initialize'
        from ./src/utils/settings.rb:843:in `new'
        from ./src/utils/settings.rb:843:in `<main>'
make: *** [Makefile:930: src/main/fc/settings_generated.h] Error 1
```
it's because of cygdrive (and its path) i believe, but how to resolve that issue?

**Comment by digitalentity** [comment]
I believe @fiam is working on the fix

**Comment by georgekucher** [comment]
is there any workaround?
'cause I need to configure a NMEA GPS and other stuff in custom build

**Comment by digitalentity** [comment]
I believe Ruby is not happy about spaces in %PATH% variable.

**Comment by georgekucher** [comment]
Now I got this
```
./src/main/drivers/light_ws2811strip_stdperiph.c: In function 'ws2811LedStripHardwareInit':
./src/main/drivers/light_ws2811strip_stdperiph.c:136:14: error: 'WS2811_DMA_STREAM' undeclared (first use in this function)
     dmaRef = WS2811_DMA_STREAM;
              ^
./src/main/drivers/light_ws2811strip_stdperiph.c:136:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:956: recipe for target 'obj/main/NAZE/drivers/light_ws2811strip_stdperiph.o' failed
make: *** [obj/main/NAZE/drivers/light_ws2811strip_stdperiph.o] Error 1
```

**Comment by fiam** [comment]
@georgekucher Could you try this settings.rb rather than the one in the repo https://gist.github.com/fiam/1e2cbfb053320f5c6890a6463d127661

I just changed the code to always look for the compiler with .exe extension, regardless of the platform. Whatever it founds first (no extension or .exe) will be used. That should work for unix platform as well as the different Windows based toolchains, even if PATH contains spaces. Please, let us know if it fixes the problem in your build and it will get merged ASAP.

**Comment by georgekucher** [comment]
Sorry, didn't have an opportunity to do it yesterday. Was installing Ubuntu. Will do today.
By the way I've compiled the hex and it almost good. Only one thing disturbing me. It beeps continuously. However I can get it armed. Stops beeping only if I disable the MAG. Here is the recording.

As for my previous question about led_strip, I've added
```
#define WS2811_DMA_STREAM               DMA1_Channel6
```
to NAZE target, and it compiled and works.

**Comment by georgekucher** [comment]
@fiam those settings work in Ubuntu
will try to build in Windows ASAP

**Comment by georgekucher** [comment]
I got this
```
settings.yaml -> settings_generated.h, settings_generated.c
C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `spawn': No such file or directory - C:\\Program\ Files\ \(x86\)\\GNU\ Tools\ ARM\ Embedded\\4.8\ 2014q2\\bin/arm-none-eabi-g\+\+.exe -mthumb -mcpu\=cortex-m3 -flto -fuse-linker-plugin -Os -I./src/main -I./src/main/target -I./lib/main/STM32F10x_StdPeriph_Driver/inc -I./lib/main/CMSIS/CM3/CoreSupport -I./lib/main/CMSIS/CM3/DeviceSupport/ST/STM32F10x -I./lib/main/MAVLink -I./src/main/target/NAZE -ggdb3 -DDEBUG -std\=c\+\+11 -Wall -Wextra -Wunsafe-loop-optimizations -Wdouble-promotion -ffunction-sections -fdata-sections -DSTM32F10X_MD -DSTM32F10X -DFLASH_SIZE\=128 -DHSE_VALUE\=8000000 -DUSE_STDPERIPH_DRIVER -DNAZE -pedantic -D__FORKNAME__\=inav -D__TARGET__\=NAZE -D__REVISION__\=a0b2d655 -o obj/tmp/test obj/tmp/test.cpp (Errno::ENOENT)
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:95:in `popen3'
        from C:/Ruby24-x64/lib/ruby/2.4.0/open3.rb:258:in `capture3'
        from ./src/utils/settings.rb:639:in `block in compile_test_file'
        from ./src/utils/settings.rb:570:in `mktmpdir'
        from ./src/utils/settings.rb:615:in `compile_test_file'
        from ./src/utils/settings.rb:662:in `check_conditions'
        from ./src/utils/settings.rb:277:in `initialize'
        from ./src/utils/settings.rb:868:in `new'
        from ./src/utils/settings.rb:868:in `<main>'
Found arm-none-eabi-g++ at C:\Program Files (x86)\GNU Tools ARM Embedded\4.8 2014q2\bin/arm-none-eabi-g++.exe
make: *** [Makefile:930: src/main/fc/settings_generated.h] Error 1
```

**Comment by georgekucher** [comment]
[SoundRecord-2017-08-31-08-53-40.zip](https://github.com/iNavFlight/inav/files/1266500/SoundRecord-2017-08-31-08-53-40.zip)


Here is the recording of beeping
Any ideas?

**Comment by georgekucher** [comment]
Hi guys! It was beeping because there was no GPS fix))) sorry for spamming.
But now I have another issue:
I calibrated my compass, and it shows correct values on the ground. But in the air, while copter heading is strait, heading values is floating slowly more than 90 degrees aside.
Maybe it's to close to FC or other sources of interference?
Here is the photos.
viber image

**Comment by georgekucher** [comment]
viber image
viber image

**Comment by zuoquezi** [comment]
the mag need higher >10cm

**Comment by georgekucher** [comment]
thanks, will try

**Pull request merged**
