### PR TITLE
Improvements to RTH/WP handling

### PR DESCRIPTION
**Pull request by digitalentity**
As pointed out in #5996, WP mode activation with no mission loaded will keep the current flight mode which may be counter-intuitive to the pilot. OSD will show that the mode is kept, however WP missions are generally not FPV. This PR creates a fallback in such case and will execute RTH instead which is  safer than let the drone drift away.

Also fixes a bug when RTH procedure may get interrupted in case of a brief sensor loss and switch out to ANGLE, ACRO or MANUAL instead of EMERGENCY. On airplanes with a certain RTH settings a brief GPS loss is tolerated in the navigation state machine, while the RTH activation bug would still bail out. This PR fixes this by making RTH procedure sticky, similar to other navigation flight modes.

Force-RTH (failsafe) does not suffer from the bug.

@stronnag could you PTAL?

### CODE REVIEW

**Review by stronnag — COMMENTED** [review]
LGTM, I will test this tomorrow

**Comment by digitalentity** [comment]
Thanks @stronnag. I'd appreciate it if you could also test #5974 (to make sure that AH/PH work as they should)

**Comment by stronnag** [comment]
@digitalentity I'll do the #5974 tests later (weekend or monday); for now I'm set up for #5995 and #5997

**Comment by digitalentity** [comment]
Awesome, thanks heaps!

**Comment by stronnag** [comment]
Tested on FW:

* Activate RTH => RTH
* Activate WP with 0 WP => RTH
* Activate WP with > 0 WP => WP
* Switch simulate FS = RTH

Great improvement for the 0 WP case, no obvious regressions

**Comment by digitalentity** [comment]
Thanks a lot for testing. Merging this.

**Pull request merged**
