### PR TITLE
remove *.ld files differing only in case, as this confuses case-insensitive, case-preserving file systems

### PR DESCRIPTION
**Pull request by stronnag**
`src/main/target/link/{stm32_flash_F765xI_bl.ld,stm32_flash_F765xI_for_bl.ld,stm32_flash_F765xI.ld}` are duplicates of synonymous all lower case file names. This confuses cicp file systems. The lower case variants are used by the build system.
With this PR, MATEKF765 builds successfully (at least with ninja).

### CODE REVIEW

**Comment by stronnag** [comment]
If this causes problems, or we need to punish Windows users again, please revert.

**Comment by breadoven** [comment]
I'm getting these changes appearing in a branch freshly cloned from the master before any changes have been made locally. Are these the problems you mention above @stronnag ?

**Comment by stronnag** [comment]
I have no idea. @OlivierC-FR have an issue on Windows with files varying only in case. So I removed the files. If you used a POSIX (case sensitive file system) you would not see a problem. 

So maybe now you're in a world of Windows's catch-22. Can't work with the files, can't work without them, even though the project does not need them. The Windows aficionados need to sort this out, it's way too hard for me.

**Comment by stronnag** [comment]
As I have no idea how to deal with  *Schrödinger's cat* file systems where a file can simultaneously exists and not exist, just tell me what you want. I you want the bogus files back, I'll happily revert.

**Comment by breadoven** [comment]
Beyond my understanding. However it kills compilation at the first hurdle
```
CMake Error at cmake/stm32.cmake:222 (message):
  linker script
  /mnt/f/INAVDev/inav/src/main/target/link/stm32_flash_f765xi.ld doesn't
  exist
```

Others who understand the makefile stuff will have to comment.

**Comment by stronnag** [comment]
But it does exist, it's in the [github repo](https://github.com/iNavFlight/inav/blob/master/src/main/target/link/stm32_flash_f765xi.ld). That is the one true source.
Your local copy is broken. Schrödinger is vindicated.

**Comment by avsaase** [comment]
@breadoven I ran into the same error when building a local branch branched from the master branch I pulled only minutes earlier. Rebasing onto master solved it for me.

**Comment by breadoven** [comment]
No idea what it's doing. The files are in the master but weren't in the clone of the master I made for the new branch. I added them back in and it was happy. If I try to merge the master into the branch is says up to date ... nothing to merge.

**Comment by OlivierC-FR** [comment]
@stronnag please don't revert, this PR fixed all my issues !
but I had to re-fork and clone again, these 3 files were kind of "stuck" in my 2 different git win clients (Gitkraken and sourcetree).
No amount of pulls or cache clearing or whatever fixed the problem, definately a Windows specific issue.
Now it's all running great.

**Comment by breadoven** [comment]
OK it's possible this has fixed itself. I'm not getting the bogus changes any more when a branch is created. The message you get when creating the branch in Github desktop seems to have changed format so perhaps it was related to a GH desktop update on the 2nd June.

**Comment by breadoven** [comment]
Actually this hasn't resolved itself in fact, just seemingly random as to whether it shows the files as deleted or not. Swapping branches that previously didn't show any changes related to the deleted files suddenly shows them as deleted when no changes were made.

**Pull request merged**
