### PR TITLE
g-force OSD item and stats

### LINKED ISSUE #3511: New feature request - Accelerometer on OSD
iNav 2.0 introduced lots of new OSD elements like RC Adjustable values or PID outputs. Could you consider adding to OSD some more variables corresponding to accelerometer reading. One of the reason to do that would be to show how the model is stress, proportional to speed during diving or acrobatics. The most importang would be vertical (Z-axis) g-force. Min and max values would be displayed on OSD summary screen.

### LINKED ISSUE #4135: OSD turn coordinator
Hello,
Would it be possible and is someone willing to add a turn coordinator to the OSD?
Just like a yaw string on a cockpit canopy but digital for when there is no elegant solution or on a mc.

https://en.wikipedia.org/wiki/Turn_and_slip_indicator

### PR DESCRIPTION
**Pull request by shellixyz**
Take over from #3566. Closes #3511. Closes #4135 

Matching configurator update: https://github.com/iNavFlight/inav-configurator/pull/765

### CODE REVIEW

**Comment by Jetrell** [comment]
@shellixyz Will you be including a G-force alarm set point?

**Comment by shellixyz** [comment]
@Jetrell Ok I can do that

**Comment by Jetrell** [comment]
@shellixyz I noticed that you have centered this around the Z yaw axis.  Do you think it would also be good to have Y pitch and X roll axis's as well. For the times we push our fixed wings a little too hard :-) 

Something else that would look good....Would be the ability to select a given axis to display G-force on a graph, with the arrows.
Just some thoughts Michel.

**Comment by shellixyz** [comment]
@Jetrell  Yes thought it could be useful too, I already added them, just not pushed yet

**Comment by shellixyz** [comment]
g-force graph will not be very practical with a character based OSD I'm afraid but it should be possible with a graphical OSD like the soon to be [iNav OSD](https://github.com/iNavFlight/inav-osd)

**Comment by OlivierC-FR** [comment]
over

Too many lines, cuts at bottom, even with PAL.

**Comment by shellixyz** [comment]
"DISARMED BY" is the last line in the stats screen so you're seeing everything

**Comment by OlivierC-FR** [comment]
The DVR sees everything, however in the FPV goggle the last line is cut in half (standard 4:3 CCD PAL to Fatshark HD1), so I don't think the 13th/16th line is viable for display on some setups.

**Comment by shellixyz** [comment]
Maybe we can make what's displayed on the stats screen configurable or even better we could change the stats screen to use icons instead of text labels to be able to display more stuff

**Comment by Jetrell** [comment]
> 
> 
> Maybe we can make what's displayed on the stats screen configurable 

@shellixyz Have you put anymore thought into this? I think it would be useful to have it configurable.

**Comment by shellixyz** [comment]
I think the stats page is too limited for now. A lot of space is lost. It could just be reformatted to be able to display more info either by using icons instead of labels. We could alternatively merge lines together for example max speed and distance, and current and power. Another alternative is to make labels shorter and make two columns

**Comment by Jetrell** [comment]
@shellixyz  I see your meaning.  When you first mentioned it, I was think along the lines of the Betaflight configurator. Which has the ability for the user to select what information they want displayed on the stats.
But that's fine.

I have another request for the G force readout. 
I used it today, And easily forgot what axis was what, when looking at a glance.
Would you be willing to add descriptive symbols to the OSD. So we can tell at a Glance which axis a particular G force is reading out?

**Comment by shellixyz** [comment]
@Jetrell 

> When you first mentioned it, I was think along the lines of the Betaflight configurator

It was the initial idea. Not sure what's best. I think we'll start with reformatting.

> Would you be willing to add descriptive symbols, something like these, to the OSD

Sure, adding symbols is a good idea. They were not added because I'm not a graphics designer. I'm going to ask the authors or Vision and Clarity to make new symbols

**Comment by Jetrell** [comment]
@shellixyz  If you don't get around to reformatting the stats display.
Is there the possibility of just putting back -  `Traveled Distance - Max Distance - Average Efficiency and Max speed.   `
Even if `Max Power` is removed. And the `Max G-force`. Because Max G-force is also shown on the Min / Max G-force stats, right below it.
I really miss seeing the above mentioned stats. Especially after a long flight with a fixed wing. Or on the DVR playback.

Thanks

**Comment by shellixyz** [comment]
@Jetrell I'm going to do something about that soon. Max g-force and max Z axis g-force are not the same thing.

**Pull request merged**
