### PR TITLE
Split servo code into servos.c

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
Don't have anything working with servos at the moment.
@oleost @sppnk @DzikuVx maybe you can be of assistance?

**Comment by oleost** [comment]
Sure,  just do a bench test that all servos work as expected?

**Comment by martinbudden** [comment]
Yes, a simple bench test should suffice. This PR doesn't add anything new, it just rearranges the code to make it more maintainable. [I don't have anything with servos at the moment either.]

**Comment by DzikuVx** [comment]
I'll try to run bench test this week if @oleost will not beat me to it

**Comment by oleost** [comment]
Hmm, I was about to compile and test. But I'm unsure how to get this build without manually adding the commits myself.

Since its not a branch in iNav I cannot simple to an git checkout .... And I dont know how to checkout this pull request.

Got an spracingf3 board in my plane. So either if someone can compile for me, or give me direction on how to pull this down.

**Comment by stronnag** [comment]
You can download it as a patch https://github.com/iNavFlight/inav/pull/597.diff, then apply the patch, either to your current branch or make a new branch just for this. Then when you're done, either blow away the temporary branch or revert the patch.

```
cd  inav
# apply
patch -p1 < path_to patch
...
# remove
patch -R -p1  < path_to patch
```

You can always add  `--dry-run` to the patch commands to check it will apply or remove cleanly. 

It applies to development, but not to master in this case.

There is probably a proper git way to do all, but maintaining a set of local patches usually works for the testing I do.

**Comment by oleost** [comment]
@stronnag Thank you.

@martinbudden Got to test it. Can confirm my servos is working as expected.

Don't know if this somehow can affect quadcopter with servotilt or simular, that I did not get a chance to test.

**Comment by digitalentity** [comment]
@oleost thanks! Let's merge this, doesn't look like it will break anything.

**Pull request merged**
