### PR TITLE
Added new target RCTimer Ares F7.

### PR DESCRIPTION
**Pull request by mikeller**
In the process of being launched by http://www.rctimer.com/.

### CODE REVIEW

**Comment by DzikuVx** [comment]
@mikeller Please read https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md

**Comment by mikeller** [comment]
@DzikuVx: Cool. Consider yourself reached out to.

**Comment by DzikuVx** [comment]
@mikeller please drop me an email at pspychalski@gmail.com

**Comment by fiam** [comment]
@mikeller I think this is the wrong approach. If RCTimer wants to sell a flight controller device they should pay for development and maintenance of the tools to configure the device they sell.
Some problems I can see with this, especially considering that RCTimer Ares F7 is a closed hardware commercial project over which INAV has got no control:

- when there are problems / issue tickets opened by users trying to upload the firmware to an RCTimer Ares F7 with INAV configurator and failing, will RCTimer pay for the time spent by volunteers of the INAV open source project to help these users? I do not think it is appropriate for a commercial entity to expect volunteers in an open source project to sacrifice their time for an entity making money from them

- when INAV decides to move to a different format for targets files (like the transition to CMake that's being worked on), this will break the ability for all customers of the RCTimer Ares F7 to use INAV configurator to upload the firmware for the hardware they paid for. Will RCTimer pay the INAV project to not break their customers' ability to configure the device they bought from RCTimer?



P.S.: For anyone confused about this comment, please check https://github.com/betaflight/betaflight-configurator/pull/1852#discussion_r367798735

**Comment by mikeller** [comment]
@fiam: Not sure you are understanding how this 'firmware' and 'configuration tools' business works.

This pull request is for the _firmware_ repository - this has got nothing to do with any _tools to configure_ the firmware, and RCTimer is completely happy to use the same tools to configure that iNav is providing to other manufacturers like Mateksys or Airbot, with no customisations needed to support their hardware.

Also, RCTimer has provided the documentation and samples required by https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md to the maintainers of iNav. @DzikuVx can confirm this.

**Comment by digitalentity** [comment]
@mikeller I don't understand the argument here. Users (and businesses) generally don't make the distinction between firmware and Configurator, it's two parts one software package providing backend & UI functionality, developed and distributed by the same team.

Both https://github.com/betaflight/betaflight-configurator/pull/1852 and this PR are about supporting specific hardware, I don't see a point in treating them differently.

I believe we should consider this discussion closed and if the samples and specs were provided to @DzikuVx we should expect this target to appear in 2.6.

**Comment by mikeller** [comment]
@digitalentity: Thanks.
The distinction (at least to me) is that the firmware _needs_ to support in-flight peripherals - if it doesn't then they are not actually usable as in-flight peripherals. Everybody contributing to firmware development understands and acknowledges this constraint.
When it comes to configuration tools, then using different configuration tools for firmware and individual peripherals is possible, and is actually the norm for most cases - neither iNav nor Betaflight configurator try to incorporate the functionality of BLHeliSuite, u-center, TBS agent, or a number of other configuration tools that are used by users to configure commonly used flight controller peripherals. Both users and manufacturers seem to understand and agree with this in general.

**Comment by DzikuVx** [comment]
I confirm that I am in possession of a schematics of this board and me an @shellixyz are waiting for hardware samples

**Comment by fiam** [comment]
@mikeller You're the one that seems to either not understand the facts or either twist the truth to suit your narrative. FrSkyOSD uses exactly the same font format as MAX7456, and the same tool that you use to upload the font to a MAX7456 can be used to upload the font to an FrSkyOSD, namely the INAV/Betaflight configurator.

In fact, when support for FrSkyOSD was merged into Betaflight you could use the configurator to upload fonts. Then, a few weeks later this PR was merged https://github.com/betaflight/betaflight-configurator/pull/1818 which hides the "Upload Font" button unless specifically a MAX7456 is detected. Then I submitted a fix to make it detect devices compatible with MAX7456 fonts in https://github.com/betaflight/betaflight-configurator/pull/1852 and you rejected it on the basis that it represented "additional work" and it was a attempt at "freeloading".

Now you argue that "RCTimer is completely happy to use the same tools to configure that iNav is providing to other manufacturers like Mateksys or Airbot". Don't you see the mental gymnastics you're pulling here? All that https://github.com/betaflight/betaflight-configurator/pull/1852 does is enable FrSkyOSD to use exactly the same tools already available to other devices.

Ah, and let's not forget about https://github.com/betaflight/betaflight-configurator/pull/1853 which adds FrSkyOSD to the list of selectable serial devices, forcing users to use the CLI to configure it. Again, what was the argument to reject that PR?

**Comment by fiam** [comment]
@mikeller Ah, forgot about this tidbit:

>The distinction (at least to me) is that the firmware needs to support in-flight peripherals - if it doesn't then they are not actually usable as in-flight peripherals. Everybody contributing to firmware development understands and acknowledges this constraint.

Then how is uploading the font, which is a firmware specific thing, something that should be handled in a separate tool?

**Comment by mikeller** [comment]
@fiam: I am not going to respond to your comments any more - this is about adding a flight controller to iNav, and not about about a request to provide a configuration tool for custom hardware for free.
Also, I find that your behaviour of attacking me for a decision that was made by the Betaflight maintainers is not acceptable.

**Comment by fiam** [comment]
@mikeller This PR is about adding a target, while my PRs were about adding device functionality to Betaflight, yet you used them to go on a phylosophical rant about manufacturer freeloading and used that as an argument to reject them. Mental gymnastics again?

The decision to not merge those PRs was made entirely by you as anyone can read in the comments in them, so don't put the blame it on someone else. I see 2 possible options moving forward. Either:

A) You apply your "RCTimer is completely happy to use the same tools to configure that iNav is providing to other manufacturers like Mateksys or Airbot" argument to my PRs to Betaflight Configurator and hence merge them.

Or, alternatively:

B) I apply your "FrSky is trying to freeload on the work of volunteers to get out of providing a configuration app for the hardware that they are selling" argument to this PR and hence veto it.

I totally support your right to decide wether adding support for an additional device is manufacturer freeloading or not. What I won't let you do is apply it selectively when it suits you better.

**Comment by mikeller** [comment]
@digitalentity: Does @fiam represent the opinion of iNav in this pull request?

@fiam: Please stop spreading lies.

**Comment by digitalentity** [comment]
@mikeller nobody rejected this PR yet. If RCTimer respects the hardware policy I don't see why support for the board shouldn't be included. It won't happen in 2.5 though.

@mikeller please also have a look at https://github.com/iNavFlight/inav/blob/master/docs/policies/CODE_OF_CONDUCT.md. Looking on the comments in @fiam's PR to BF Configurator, it seems that the decision not to merge that PR was yours (as expressed by not merging the PR), so please, let's restore the respectful environment here and withhold from further insulting and accusing each other.

**Comment by digitalentity** [comment]
RCTimer website is apparently down:
Screenshot from 2020-05-15 20-19-17

Neither @DzikuVx nor @shellixyz received the hardware samples so far. Last communication with RCTimer was two weeks ago stating that "The manufacturer is still working out shipping after the lockdown, they will let me know when they have shipped."

I'm going to close this PR for the time being. We'll get back the matter of adding support for Ares F7 once RCTimer provides the hardware samples to us.

**Comment by mikeller** [comment]
@digitalentity:

> Looking on the comments in @fiam's PR to BF Configurator, it seems that the decision not to merge that PR was yours (as expressed by not merging the PR), so please, let's restore the respectful environment here and withhold from further insulting and accusing each other.

I am not sure how iNav is run, and if every action you take in iNav is yours and yours alone, but is not how Betaflight is run - in a lot of cases I am just the one taking the action, but what action (or inaction) is taken is the result of discussion and agreement amongst maintainers.

If you want a respectful environment then I think you should talk to @fiam - all I asked for is to have a reasonable request identical to lots of others in here (#5274, #5629, ...) considered, before being attacked by him out of the blue for something that he seems to be holding a personal grudge against me for.

The RCTimer website is working fine for me, and the engineering samples were sent on 01 May - not sure how long shipping will take under the current circumstances. Please keep me posted on when they have arrived.

image

**Comment by shellixyz** [comment]
@mikeller 

The same is true for iNav. The action to take has been discussed among maintainers.

You are saying @fiam is spreading lies but what lies are you talking about ?

**Comment by mikeller** [comment]
@shellixyz:

> You are saying @fiam is spreading lies but what lies are you talking about ?

> The decision to not merge those PRs was made entirely by you

**Comment by fiam** [comment]
@mikeller I don't hold any personal grudges against you and I have never attacked you personally, I've only asked you to be consistent with your arguments. On the other hand, while no one here has insulted you, you've called me a liar without any reason and reported my comments for abuse. So please, behave yourself and stop playing the victim. We're all adults here.

So you're asking us to review and consider your request to merge something, and that's fine. We're only asking you to extend back the same courtesy, which you have denied in the past. If you deny something to others, you shouldn't be surprised when then deny you the same thing.

If someone else from the Betaflight team has any concerns about https://github.com/betaflight/betaflight-configurator/pull/1852 or https://github.com/betaflight/betaflight-configurator/pull/1853, please invite them to post a comment or a review so we can continue the discussion there, I can fix any potential problems, and it can be merged. As of now, the only negative comments are from you, so you surely understand that it's reasonable to assume that it was your decision to not merge them was yours and yours only.

**Comment by mikeller** [comment]
@digitalentity: Does @fiam represent the opinion of iNav in this pull request?

@fiam:

> If someone else from the Betaflight team has any concerns about

Please do not try to impose on us how we run Betaflight - we are not trying to impose on you how you are running iNav.

**Comment by fiam** [comment]
@mikeller You seem obsessed with @digitalentity's approval, yet you fail to understand that INAV is effectively run by a group of contributors where we discuss things until we reach a consensus. We have no dictators here and there's no such thing as the "opinion of INAV" that you're asking for. If someone from the development team has problem with something, they don't need to go ask @digitalentity to post comments/request changes/close PRs. They can speak for themselves.

**Comment by shellixyz** [comment]
@mikeller You (as a team or not) made a very dishonest move by first merging a change that broke something then asked for money to make it work again even though @fiam did the work because you feel entitled to being paid by everyone who makes hardware working with your software. Now you want us to merge something in iNav you have been paid for. Don't be surprised  that he makes you taste a bit of your own medicine.

**Comment by mikeller** [comment]
@shellixyz: I think you have the wrong picture there, this was by no means a case of dishonesty: What was discussed with @fiam was that support for the FrSky hardware would be added to _the firmware_ - adding customisations to _configurator_ for configuring the FrSky hardware, uploading fontsto it, or flashing new firmware to it was never part of the discussion. That some of this worked for some time was just coincidence.

@fiam: Ok, then I take it that your opinion that support for new hardware should only be added to the firmware if the manufacturer is paying for it is the official iNav stance.

**Comment by fiam** [comment]
@mikeller You realize you've entirely made up that request for money yourself? You're literally projecting.

No one here wants nor has asked for money neither from your nor from RCTimer. What you're being asked for is exactly the same thing you're asking for: let us submit code to the project you manage.

**Comment by mikeller** [comment]
@fiam: Read https://github.com/iNavFlight/inav/pull/5632#issuecomment-628556750

**Comment by fiam** [comment]
@mikeller And what's your reasoning for https://github.com/betaflight/betaflight/pull/9808 and then banning me from posting comments in the Betaflight organization? Are you afraid of people that read the PRs finding out how you behave? 

Screenshot 2020-05-16 at 17 53 24

Seriously, go see a professional

**Comment by mikeller** [comment]
@fiam: Nobody has banned you from anything in Betaflight. Please stop blaming me for things that are not true.

Also, can you please refrain from acting in an insulting manner?

**Comment by digitalentity** [comment]
@mikeller you seem to seek my approval of this PR. While I can act as a [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life), I prefer not to dictate my opinion to anybody. This comment https://github.com/iNavFlight/inav/pull/5632#issuecomment-629375633, as well as this one https://github.com/iNavFlight/inav/pull/5632#issuecomment-629412617 represent the collective decision of INAV core development team, I am just the one taking the action.

You are free to run Betaflight in any way you want and ban any hardware you don't see worth being supported, this will not affect decisions made by the INAV team as long as our **publicly available** rules and policies are respected.

I'm going to lock this thread to prevent further flaming.

**Comment by digitalentity** [comment]
Adding this to 2.6 milestone so we can correctly track it. @mikeller AFAIK we're still waiting for the boards to arrive.

**Comment by fiam** [comment]
@mikeller Thanks for reconsidering and reopening my PRs in Betaflight configurator. Following up on my word, I consider this matter resolved and withdraw my objections from this PR.

**Comment by mikeller** [comment]
@digitalentity: I'll follow up with the manufacturer on shipping of the samples and see if I can get tracking numbers - apparently they are seeing delays in international shipping due to the lockdown.

@fiam: No problem - now that FrSky has reconsidered their position on supporting their customers and is providing them with a tool for configuration and firmware updating for their hardware the concerns that I had about responsibility for this being dropped onto Betaflight have been addressed.

**Pull request closed without merging**
