### PR TITLE
Remove barometer LPF

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
From version 6.0 onwards, there has been an increase in multirotor users complaining of problems climbing "like a rocket" or "shooting towards the moon", and the primary source of this problem is caused by the LPF filter applied to the Barometer reading.

INAV has never used this filter for years, and there have never been so many user reports with the same problem. After the filter activation merge, everything got complicated...

This PR removes this filter, which is unnecessary.

Unnecessary because, in the navigation PID controller, there is already a 5Hz LPF filter in the Velocity Z error calculation and also in the Alt-Hold Derivative term.

The tests were carried out on an F450, with a 7.000 MAh battery. This multirotor always fired like a rocket using versions 6 and 7, but not with 5.1. After testing version 7 firmware without the Barometer's LPF filter, it was found that the filter was in fact bad for estimating altitude, and also 1Hz is an extremely low cutoff frequency, it's a little crazy to have this running in the algorithm.

### CODE REVIEW

**Comment by rmaia3d** [comment]
Could this issue I experienced be related to it?

https://github.com/iNavFlight/inav/issues/9566

**Comment by JulioCesarMatias** [comment]
> this comment

Probably yes Rodrigo... Do you want a 7.0 build to test?

**Comment by rmaia3d** [comment]
> > this comment
> 
> Probably yes Rodrigo... Do you want a 7.0 build to test?

The "problem" is how to safely test the emergency land feature. Ideally, I would like to be able to trigger it via a switch, so that if the ping pong behavior commences, I can simply flip back the switch and assume manual control. Otherwise, I don't feel comfortable risking my quads to test it.

**Comment by JulioCesarMatias** [comment]
I think the other Dev`s don't see that filtering the Baro at 1Hz is a problem... Basically the Position-Estimator only uses the IMU and the GPS to keep calculating the altitude on multirotors.

**Pull request closed without merging**
