### PR TITLE
OSD/CMS/DisplayPort refactoring and some catch-up with BF

### PR DESCRIPTION
**Pull request by digitalentity**
1. DisplayPort code catch-up with BF
2. OSD refactoring
3. CMS core catch-up with BF
4. More pre-arming checks and arming code refactoring

### CODE REVIEW

**Comment by digitalentity** [comment]
OSD - tested on Matek405 - works fine.

**Comment by teckel12** [comment]
In src/main/telemetry/smartport.c it would seem that the OK to arm logic is reversed.

```
                if (isArmingDisabled())
                    tmpi += 1;
                if (ARMING_FLAG(ARMED))
                    tmpi += 4;
```

I believe this should be:

```
                if (!isArmingDisabled())
                    tmpi += 1;
                else
                    tmpi += 2;
                if (ARMING_FLAG(ARMED))
                    tmpi += 4;
```

Note the `!` above before `isArmingDisabled()`.  I can kind of see removing the `2` state, but it could break a Lua script looking for a value of `2` preventing arming.  Above also matches Cleanflight/Betaflight logic.

**Comment by teckel12** [comment]
Wasn't sure how you would like a contribution like this, but I did a pull request #2033 with the changes suggested above.

**Comment by digitalentity** [comment]
@teckel12 thanks, merged.

**Comment by digitalentity** [comment]
Seems to function properly. Merging.

**Pull request merged**
