### PR TITLE
Option to remove home position from arming screen

### PR DESCRIPTION
**Pull request by avsaase**
Some pilots for whatever reason do not want to publish their flying location when sharing dvr footage. This PR creates an option to remove the coordinates and plus code from the arming screen.

`osd_home_position_arm_screen = ON` (the default):
2021-01-05 19_09_34-VLC (Direct3D11 output)

`osd_home_position_arm_screen = OFF`:
2021-01-05 19_07_53-VLC (Direct3D11 output)

### CODE REVIEW

**Review by DzikuVx — CHANGES_REQUESTED** [review]
@avsaase you still have to bump PG version in `PG_REGISTER_WITH_RESET_TEMPLATE(osdConfig_t, osdConfig, PG_OSD_CONFIG, 13);`

**Comment by avsaase** [comment]
Right, I forgot about that. Thing is, I had no problem compiling and flashing this. Can you explain what `PG_REGISTER_WITH_RESET_TEMPLATE` does and why the value needs to be incremented, or refer me to somewhere where I can read about it? Does it need to change with every PR? And what then happens when all PR's are merged? I have searched for it online but all I find is the INAV and betaflight source code.

**Comment by DzikuVx** [comment]
Long story short: PG version should be dumped every time the structure stored in the ParameterGroup changes. If during flashing PG version does not match, PG is defaulted. It prevents from breaking settings after updating firmware to a new version when the structure (and probably length) changed

**Comment by avsaase** [comment]
Does this only cause problems when flashing without full chip erase?

**Comment by DzikuVx** [comment]
yes

**Review by digitalentity — APPROVED** [review]
LGTM

**Review by DzikuVx — APPROVED** [review]

**Pull request merged**
