### PR TITLE
FW navigation fixes

### PR DESCRIPTION
**Pull request by digitalentity**
Fix for #378 - no more landing initiated for airplanes in both RTH and WP-RTH
Initial cut on #91 - hardcoded 20deg roll, 20deg/s yaw and 10 deg dive

Better pitch/throttle coupling that accounts for overall requested pitch. 
Previously it was only accounting for pitch correction requested by altitude controller which might have caused roll/pitch coupling to create a climb without increasing throttle and stall as a result.

Fixed a bug in incorrect deg->decideg conversion which caused roll/pitch limitations for FW navigation to be effectively ignored.

### CODE REVIEW

**Comment by digitalentity** [comment]
@oleost you might be interested in this one

**Comment by oleost** [comment]
Yes very interesting. Will test when I get time.
But first I want to do some more testing on current failsafe and then more on launch mode.

Really hates this time of year, very limited flying time due to weather and only sunlight a couple of hours.

**Comment by oleost** [comment]
If I understand this PR correctly: 
1. Landing is REMOVED from fixedwing, so even if one sends an WP with landing it will not land. ? (Because we dont have a good way of landing fixedwing airplane controlled)
2. Emergency landing is added, this is to land in case of navigation loss during failsafe.. But does Emergency land initiate in the end of an failsafe RTH while still having working sensors?

So to test this I can simple:
1. Upload a scetchs using EZ-GUI, with landing at end and watch it just do circle / loiter instead?
2. Manually apply RTH and see that it does not try to land.
3. Inititate RTH with turning of TX and see if landing looks like its going to be succesfully?

**Comment by oleost** [comment]
Also @stronnag is probably interested in this aswell because 

> @stronnag 
> 
> For your safety, mwp disables land on RTH when uploading missions for FW ...

**Comment by digitalentity** [comment]
> Emergency landing is added, this is to land in case of navigation loss during failsafe.. But does Emergency land initiate in the end of an failsafe RTH while still having working sensors?

Emergency landing is not failsafe, it's GPS loss. I'm not sure it can be tested manually.

**Comment by oleost** [comment]
Maybe arm airplane, manually remove GPS and then takeoff and then turn off TX?

**Comment by digitalentity** [comment]
> Maybe arm airplane, manually remove GPS and then takeoff and then turn off TX?

Yes, this should do the trick. Power up, make sure GPS gets the home position locked, ARM, disconnect GPS, launch, turn off the TX. This is going to be a very risky test.

**Comment by martinbudden** [comment]
> This is going to be a very risky test.

Indeed. Make sure you use a battery that is almost dead.

**Comment by oleost** [comment]
I'm going to do some dry test on ground to verify I'm able to regain controll when turning on tx

**Comment by flounderscore** [comment]
Would it be possible to turn it into a separate flight mode, like arduplane's circle mode? That would make testing easier.

**Comment by digitalentity** [comment]
@flounderscore only for testing purposes. Emergency landing is not really a flight mode, it's a state of navigation system when INAV decides it's not possible to continue navigation.

**Comment by digitalentity** [comment]
I believe it's safe to merge. We can test more thoroughly and fix bugs during release-candidate cycle.

**Pull request merged**
