### PR TITLE
Moved accgyro, barometer and compass drivers into subdirectories

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by martinbudden** [comment]
@digitalentity , I've moved the accgyro, barometer and compass drivers into subdirectories. This splits up the now very large `drivers` directory and aligns with betaflight. I haven't merged it because I'm not sure how this fits in with the 1.7 release schedule.

**Comment by digitalentity** [comment]
@martinbudden thanks, nice cleanup. I'll have a look soon

**Review by digitalentity — CHANGES_REQUESTED** [review]
Rebase required, otherwise looks fine.

**Comment by martinbudden** [comment]
@digitalentity , rebased.

**Review by digitalentity — APPROVED** [review]

**Pull request merged**
