### PR TITLE
Remove duplicate semicolon

### PR DESCRIPTION
**Pull request by JulioCesarMatias**

### CODE REVIEW

**Comment by avsaase** [comment]
Can you maybe bundle some of these minor code changes and make one PR for them?

**Comment by JulioCesarMatias** [comment]
> Can you maybe bundle some of these minor code changes and make one PR for them?


I haven't found anything else like this at the moment. Next Sunday I will have some free time again, and I will dedicate myself to finding other things.

**Comment by OptimusTi** [comment]
Go ahead and change all the "bellow" with "below" please. 😁

**Comment by JulioCesarMatias** [comment]
> Go ahead and change all the "bellow" with "below" please. 😁


is this serious? I don't understand the reason for the saccharism, and I don't see any fun here.

**Comment by OptimusTi** [comment]
Oh it's serious. Just a little typo that's been there for years. Mostly in docs.

**Review by DzikuVx — APPROVED** [review]

**Pull request merged**
