### PR TITLE
Increase the maximum number of addressable LEDs

### PR DESCRIPTION
**Pull request by MrD-RC**
Increase the number of addressable LEDs from 32 to 128.

The extra 96 LEDs adds only 10560 B (5.37% on an F722) of RAM usage, and an extra 64 B (0.01% on F722) of Flash. If necessary, this could be changed so that it is only available on processors with > 512 KB flash.

image

Why so many LEDs? Why not? On larger aircraft, a single LED strip along a wing will have many chips. Here, for example is the tail boom extensions for a Drak. 
image

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
At the end of this year I will use my FC with INAV to control the LEDs on my Christmas tree.

**Comment by MrD-RC** [comment]
Only 128 LEDs on the Christmas Tree. You need more LEDs 😉

**Comment by MrD-RC** [comment]
@mmosca raised a question in Discord about CPU usage when that many LEDs are running with something like a Larson scanner. 

Here's the CPU usage with the LEDs switched off.
image

Here's the CPU usage with 96 LEDs with a Larson scanner running.
image

**Comment by MrD-RC** [comment]
This doesn't break anything, so potentially could be added to 7.1. @DzikuVx what do you think.

**Comment by MrD-RC** [comment]
@sensei-hacker I forgot about that one. Though, my PR updates the documentation too.

**Comment by MrD-RC** [comment]
Merged in to 7.1 so closing this.

**Pull request closed without merging**
