### PR TITLE
New value to Lat Long Scaling

### PR DESCRIPTION
**Pull request by JulioCesarMatias**
currently ArduPilot works with this value, maybe it really is better.

https://github.com/ArduPilot/ardupilot/pull/17895

### CODE REVIEW

**Comment by JulioCesarMatias** [comment]
PR Failed, need https://github.com/iNavFlight/inav/pull/7219/files

**Comment by JulioCesarMatias** [comment]
PR failed, need this https://github.com/iNavFlight/inav/pull/7219

**Review by DzikuVx — APPROVED** [review]

**Comment by breadoven** [comment]
Where does Ardupilot gets its value from ? The current INAV value is consistent with:

https://en.wikipedia.org/wiki/Geographical_mile

for WGS 84 which is what the GPS is likely to be using.

**Comment by JulioCesarMatias** [comment]
> Where does Ardupilot gets its value from ? The current INAV value is consistent with:
> 
> https://en.wikipedia.org/wiki/Geographical_mile
> 
> for WGS 84 which is what the GPS is likely to be using.


I don't know, it was modified by Tridge, and Tridge is an alien (I don't know if you know him), if he put this value it's because there really was an improvement

**Comment by stronnag** [comment]
Utterly pointless if you understand:
* what the 'f' character is for; and
*  the precision of a C float

**Pull request closed without merging**
