### PR TITLE
SmartAudio / Tramp support

### PR DESCRIPTION
**Pull request by Soph**
For what it does see: #1262 

This is work in progress.

I tried to cherry-pick the two merge commits mentioned in #1262. After that a few minor fixes were needed to make it compile without warnings. I haven't tested this yet (will do on the weekend) and I doubt somehow it just works :) But maybe someone can have a look at it already if it looks right. 

There is also some newer refactoring regarding when looking at HEAD of the BetaFlight repository. Not sure if we would want to merge them in too. See for example: https://github.com/betaflight/betaflight/commit/723831b579952c040b1c155ab850170de05f492d

### CODE REVIEW

**Comment by Soph** [comment]
So with the fix from here https://github.com/iNavFlight/inav/pull/1609 I could try this out. 

I manually configured a serial port for SmartAudio via cli. 
```
serial 2 1024 115200 38400 0 115200
```
The OSD menu for Tramp/SmartAudio shows up but it not seems to get a connection since no values are shown. I think I need a hardware debugger to actually debug this which I haven't and I'm unsure which to get for the Omnibus F4Pro.

**Comment by Soph** [comment]
Update: While trying to bring the latest changes to the VTX handling over from BF I noticed that during merging I had 2 calls to `smartAudioInit()` left in fc_init.c. After removing the second the FC was now able to talk to my TBS Unify Pro HV. I could set power and channels. Seems to work :)

**Comment by Soph** [comment]
@digitalentity I have also now a branch ( https://github.com/soph/inav/tree/feature/smart-audio-latest ) with the changes regarding SmartAudio/Tramp from BetaFlight. It doesn't include the RTC6705 code since I don't have anything to test that. Should I merge this in here or do you (or someone else) wants to review this here first.

I'll try to test soft serial (that's how I would like to use SmartAudio on my OmnibusF4 Pro) today or tomorrow and will update here too. I also have only a Unify Pro HV and Race to test.

**Comment by digitalentity** [comment]
@Soph merge the code here right away!

**Comment by Soph** [comment]
Merged. Hadn't time to test soft serial yet, maybe on the weekend!

**Comment by ghost** [comment]
@Soph If the average layman iNav user wanted to enable SmartAudio in their iNav build, how would they do so? I currently do not see any option for it in the Ports Tab. I am running iNav 1.7.1. If its a case of version 1.8, when do you envision that to be out by?

**Comment by Manawyrm** [comment]
It would be a good idea to also cherry-pick the commit https://github.com/cleanflight/cleanflight/commit/723831b579952c040b1c155ab850170de05f492d here, to enable support for RTC6705, and also use the new configuration structure, like the VTX CLI command. 
This will also make the work in #1695 much easier.

**Comment by DzikuVx** [comment]
@Manawyrm you are more than welcome to create a PullRequest with that change you know :)

**Comment by Manawyrm** [comment]
@DzikuVx Well OK, I have working VTX with the SPracingF3NEO / OSD/VTX board here. Should we merge this branch first and then patch the RTC6705 support into the software?

**Comment by DzikuVx** [comment]
@Soph could you please rebase and resolve conflicts?

**Comment by Soph** [comment]
@DzikuVx currently on vacation until next sunday. Might be able to do it before that but if not I'll do it on Monday in a week.

**Comment by DzikuVx** [comment]
Sure, I’m also on a vacation ATM . Have fun! 

Od: Stefan Haubold
Wysłano: sobota, 19 sierpnia 2017 22:50
Do: iNavFlight/inav
DW: Paweł Spychalski; Mention
Temat: Re: [iNavFlight/inav] SmartAudio / Tramp support (#1576)

@DzikuVx currently on vacation until next sunday. Might be able to do it before that but if not I'll do it on Monday in a week.

**Comment by Soph** [comment]
@DzikuVx I did a rebase. It compiles fine for the default target but it fails for some on Travis CI. I did a look at the failing builds and it seems they are related to RangeFinder changes. I'm not sure it's really related to changes in this PR. (Also other PRs 5hours ago did compile just fine). Any ideas?

**Comment by DzikuVx** [comment]
Looks like a development branch problem. I will try to test Tramp/SmartAudio next week and fix all problems

**Comment by Soph** [comment]
Thanks! I had it tested with a Omnibus F4 Pro and a Unify Pro HV (Race and normal). Worked in the OSD on a hardware serial but didn't managed to get it working with soft serial (which on the Omnibus would be the best way to connect it I think). But I might have connected that wrong. I have that setup not running right now but could put it together if you need help testing.

**Comment by DzikuVx** [comment]
@Soph I've allowed myself to make a new PR from your code so I can have push permissions. I hope this is fine with you. See #2084

**Pull request closed without merging**
