### PR TITLE
Hardware Debugging from VSCode and WSL manual

### PR DESCRIPTION
**Pull request by erstec**
Adding Hardware Debugging with VSCode, WSL and ST-Link manual

### CODE REVIEW

**Comment by MrD-RC** [comment]
Awesome.

**Comment by Scavanger** [comment]
Englisch (UK) 

Super, but unnecessarily complicated. OpenOCD and GDB communicate via TCP, so just run OpenOCD under Windows and let it communicate with GDB in WSL. Less fiddling and runs perfectly.

**Comment by DzikuVx** [comment]
@MrD-RC please always add a milestone before merging :)

**Comment by DzikuVx** [comment]
@Scavanger please describe TCP way as well if it's not yet documented

**Comment by erstec** [comment]
> Super, but unnecessarily complicated. OpenOCD and GDB communicate via TCP, so just run OpenOCD under Windows and let it communicate with GDB in WSL. Less fiddling and runs perfectly.

Of course :) It will be very helpfull to have such kind of documentatio too. Maybe you will have possibility to make one :)

**Comment by Scavanger** [comment]
@DzikuVx
I will, I just have to finish it.😉

**Comment by MrD-RC** [comment]
> @MrD-RC please always add a milestone before merging :)

D'oh! Sorry about that.

**Pull request merged**
