### PR TITLE
Change default to velned on

### PR DESCRIPTION
**Pull request by oleost**
Creating this pull request to discuss if velned should be default on.

Reason is because now is air1g default instead of pedestrian and is not GPS velned better in this mode than calculating velocity

### CODE REVIEW

**Comment by digitalentity** [comment]
Good point. We need some testing with older GPS units (i.e. Neo6/Neo7).

**Comment by oleost** [comment]
@stronnag You have some Neo6 aswell?

Have you tried velned on vs off?

**Comment by stronnag** [comment]
I no longer use Neo6M, but for the numerous previous flights with Neo6M, I always had velned = ON. No problems with it on, should be default (imho).

**Comment by DzikuVx** [comment]
I also was using Neo6 and also with velned=on
Do not remember any specyfic problems

**Pull request merged**
