### PR TITLE
RC_MAP letters update to AETR5678

### PR DESCRIPTION
**Pull request by DzikuVx**
To match changes from iNavFlight/inav-configurator#256

### CODE REVIEW

**Comment by digitalentity** [comment]
Why can't we switch to just `AERT` without numbers?

**Comment by DzikuVx** [comment]
@digitalentity Because you can create any map with CLI and then it will be neither AETR but RETA for example. FC sends ATM 8 chars that represents rc map. We clould truncate to only 4 chars, but then when someone modifies channels above 4, configurator would not be able to use it.

I think we should get rid of RC_MAP completely and just use one byte variable to select AETR or one of preselected maps

**Comment by digitalentity** [comment]
Can we just truncate the map everywhere to 4 chars?

**Comment by DzikuVx** [comment]
I really suggest complete rewrite over thruncating

**Review by digitalentity — APPROVED** [review]

**Comment by maRCnh33** [comment]
and now i cannot set it like this 56EATR78 !!! a big problem... and busy for days now..... on the old naze f1 its no problem

**Pull request merged**
