### PR TITLE
Version 1.2.1

### PR DESCRIPTION
**Pull request by digitalentity**
Intermediate release, due to few serious bugs fixed:
https://github.com/iNavFlight/inav/issues/611
https://github.com/iNavFlight/inav/issues/612
https://github.com/iNavFlight/inav/pull/614

### CODE REVIEW

**Comment by digitalentity** [comment]
@stronnag, @martinbudden 
Should we go for complete dev->master merge or just backporting     79fdc6d ? I'm not sure.

**Comment by stronnag** [comment]
I'd like to test the consolidated changes we have in separate branches in dev before we make a release (e.g. notch + bmp280 + notch-fix + horizon changes). I'd prefer to:
- merge the BMP280 fix into master immediately and created an RC
- merge the other changes into dev so they can be tested over the next few days in dev
- do a dev / master merge later in the week

We might also consider the versioning model, it's a bit confusing if 1.2.1 dev becomes 1.2.1 stable and perhaps we have an odd point == dev, even point == stable notation, so the next release in 1.2.2, and we restart dev on 1.2.3. -- thoughts?

**Comment by digitalentity** [comment]
You convinced me - I'll backport the BMP280 fix into master and make a 1.2.1-RC1 soon.

Versioning may be even simpler - `x.y.z`, where non-zero `z` = development version (next stable version would be 1.3).

**Comment by martinbudden** [comment]
Yes, I'd just make the minimal change as well. The BMP280 fix, but I'd also include the filter dT fix as well.

**Comment by digitalentity** [comment]
On the second though - this is precisely the situation which we tried avoiding when changing the workflow. We decided that merges to `master` should occur only when stable version is released meaning that any RCs should be done from `development`.

I don't see a simple solution here. On one hand I would like to make a fix for bmp280 issue as soon as possible, on the other hand, breaking the workflow and making mess in the history is not a good thing.

**Comment by stronnag** [comment]
We need some way to differentiate between back-ported bug fixes and new features. The BMP280 fix and the horizon fixes are bug fixes; filter DT is a bug fix on a new feature (notch), which should stay (imho) in dev until the next major release.

**Comment by digitalentity** [comment]
Horizon mode fix is not merged yet, I think it can stay in development until next release. I'm cherry-picking the bmp280 fix and merging it into master (#616). I'll bump version to 1.2.1 on master as well so we can make a proper 1.2.1-RC1

**Comment by martinbudden** [comment]
My mistake - I forgot the notch filter was not yet in master. Still, I'd just move the bug fixes over to master and then do the release.

**Comment by stronnag** [comment]
Please consider the following gcc 6 lto diagnostics ... huum uint16 != float ...

```
./src/main/drivers/io_pca9685.h:4:6: warning: type of 'pca9685setPWMFreq' does not match original declaration [-Wlto-type-mismatch]
 void pca9685setPWMFreq(float freq);
      ^
./src/main/drivers/io_pca9685.c:86:6: note: type mismatch in parameter 1
 void pca9685setPWMFreq(uint16_t freq) {
      ^
/usr/arm-none-eabi/include/sys/_stdint.h:36:20: note: type 'uint16_t' should match type 'float'
 typedef __uint16_t uint16_t ;
                    ^
./src/main/drivers/io_pca9685.c:86:6: note: 'pca9685setPWMFreq' was previously declared here
 void pca9685setPWMFreq(uint16_t freq) {
      ^
./src/main/drivers/io_pca9685.c:86:6: note: code may be misoptimized unless -fno-strict-aliasing is used
./src/main/drivers/pwm_output.c:228:9: warning: type of 'feature' does not match original declaration [-Wlto-type-mismatch]
     if (feature(FEATURE_PWM_SERVO_DRIVER)) {
         ^
./src/main/config/feature.c:87:5: note: return value type mismatch
 bool feature(uint32_t mask)
     ^
./src/main/config/feature.c:87:5: note: type '_Bool' should match type 'int'
./src/main/config/feature.c:87:5: note: 'feature' was previously declared here
./src/main/config/feature.c:87:5: note: code may be misoptimized unless -fno-strict-aliasing is used
```

**Pull request closed without merging**
