### PR TITLE
Timer N channel fix

### PR DESCRIPTION
**Pull request by shirase**
Maybe it fix problem with N timer channel for MATEKF405TE. I don`t have that board. Can someone test.

#8089

### CODE REVIEW

**Comment by MATEKSYS** [comment]
Thanks for the fix, We just did a test on bench.  motor3 works when using "Master" slider in output tab or using transmitter after arming. 
but when using the individual slider of motor "3".  motor3 don't work.
and motor4 on Tim1 will beep when throttle back to 0.  motor 1 and 2 don't

**Comment by shirase** [comment]
You compile it with `#define USE_DSHOT_DMAR` ?

**Comment by MATEKSYS** [comment]
> You compile it with `#define USE_DSHOT_DMAR` ?

without Dshot burst. I tested it with normal DMA

**Comment by DzikuVx** [comment]
I think we should switch this board to burst DMA in INAV 7

**Comment by MATEKSYS** [comment]
Just tested it again with #define USE_DSHOT_DMAR
Motor 3 and 4 work normal when using individual slider in outputs tab.

> I think we should switch this board to burst DMA in INAV 7
I think so too

**Comment by shirase** [comment]
Add `#define USE_DSHOT_DMAR` for this board

**Comment by DzikuVx** [comment]
@shirase how about extracting Burst DMA into a separate PR? I mean those are independent changes and looks like it does not work like expected. I will try to test it with a different board that has N timer channel only

**Comment by shirase** [comment]
@DzikuVx agree. It must to work without dma burst.

**Comment by DzikuVx** [comment]
@shirase I mean we can switch this target to DMA Burst. But not as part of the fix for N channel timers

**Comment by shirase** [comment]
@DzikuVx Can you make PR for DMA burst targets? I do not have boards for testing. And i don`t known lists of problem boards.

**Comment by DzikuVx** [comment]
I will do that

**Comment by rmaia3d** [comment]
As I posted in #9277, even with those changes, the output from S1 to S4 on the Matek F405 Mini-TE board looks like this on an oscilloscope:
IMG_2731
(That's DSHOT 300 on zero throttle)

What draws the attention is S3 (scope Ch3, magenta line) being "inverted", a mirror of the other outputs. This is not unexpected, once ST's "N" timers are complementary and have inverted output levels from the "normal" channel.

But this is probably the source of the DSHOT errors. I don't fully recall the DSHOT spec, but I don't think it is tolerant to inverted logic levels.

**Comment by shota3527** [comment]
Has anyone tried Dshot beeper after these changes? It seems not working.

**Comment by rmaia3d** [comment]
> Has anyone tried Dshot beeper after these changes? It seems not working.

Yes, I can confirm Dshot beeper is not working, even in targets where DMA burst mode is not used/enabled. However, reverting #9265 makes it work again. Some change within that PR broke it for all targets.

Also, my test flight on the Matek F405miniTE with #9265, #9276 and #9277 didn't go well. The quad simply dropped less than 30 seconds after take-off, apparently with the motors being cut. Due to an error on my part, I didn't have blackbox logging enabled, but I do have DVR recording that shows the current dropping to less than 1A before impact and no flight mode changes (so not a failsafe, which was set to RTH or land if closer than 20m from home). Here's that DVR:

https://youtu.be/_No0jyui43s

I am still not sure if it could be directly related to the DMA code changes or a hardware issue or another issue altogether, but it does cast suspicion and doubt.

**Comment by shirase** [comment]
@shota3527 @rmaia3d try this fix #9321. Can you check it on dshot600 and dshot300?

**Comment by shota3527** [comment]
@shirase @rmaia3d 
I have tried #9276, Did not manage to reproduce the motor stopping issue on the bench test
I have s1-s3 using dshot300 on matekf405te_sd, S3 is TIM1 CH3N

**Comment by DzikuVx** [comment]
@shirase Is this still relevant? And working?

**Comment by mmosca** [comment]
I beleive @shota3527 got some reports it was working for one of the siwi engineers. I believe that was with this patch.

**Comment by rmaia3d** [comment]
> @shirase Is this still relevant? And working?

As can be seen from the scope traces I posted a few comments above, this did indeed work to bring channel 3 to the "non-inverted" state. An inverted (0 being logic HIGH) DSHOT signal is how the ESC knows if the FC wants bi-directional comms or not. So, without this fix, 1 ESC (ch3) will work in bi-dir mode and the other 3 ESCs will work in normal mode. Not ideal.

All ESCs should work in the same mode, and by the scope traces above, this PR ensures that.

**Comment by rmaia3d** [comment]
> @shirase @rmaia3d
> I have tried #9276, but did not manage to reproduce the motor stopping issue on the bench test
> I have s1-s3 using dshot300/dshot600 on matekf405te_sd, S3 is TIM1 CH3N, Seems like it is working well
> Beeper is also working on both DSHOT300 and 600 on current master

I'm away from home and wasn't able to test the changes after the dshot beeper fix, but before leaving I did further investigation and tests and was able to trace the motor stopping issue to the ESC itself. 

It "overheats" and then stops the motors (actually it looks like it's a bug in the temperature cutoff protection or a faulty temp sensor). So it has nothing to do with the FC or Inav (I was able to reproduce the issue both on the bench and in-flight while running betaflight too). Good news!

**Comment by rmaia3d** [comment]
Here's someone with a similar issue and another mention of the possible temperature cutoff bug. The ESC I'm using is the same, just the "mini" version.

https://discuss.ardupilot.org/t/no-throttle-with-props-on-hexa-680-13/80847/5

**Comment by mmosca** [comment]
Sounds like the fix works and can be merged. Nice shirase, and thanks for testing Rodrigo![]s,Marcelo Bezerra ***@***.***>On 11 Oct 2023, at 00:40, Rodrigo Maia ***@***.***> wrote:﻿
Here's someone with a similar issue and another mention of the possible temperature cutoff bug. The ESC I'm using is the same, just the "mini" version.
https://discuss.ardupilot.org/t/no-throttle-with-props-on-hexa-680-13/80847/5

**Pull request merged**
