### PR TITLE
CC3D - PPM glitch fix

### PR DESCRIPTION
**Pull request by martinbudden**
This is the same fix as PR https://github.com/cleanflight/cleanflight/pull/1790/

### CODE REVIEW

**Comment by digitalentity** [comment]
I'm not sure this is a good PR to have. It will break compatibility for existing build. CC3D with INAV is mostly used for airplanes where it may be tricky to rewire the flight controller (it's often buried deep inside the aircraft)

**Comment by sppnk** [comment]
I have not studied the changes in depth, so I would ask if this will affect to normal airplane setups in CC3D  (with or w/o oneshot ESC for the motor). There are many people flying CC3D for airplanes, nowadays it is the "best buy" FC for that.

**Comment by martinbudden** [comment]
@digitalentity , I hadn't considered this might cause rewiring problems for airplane users.

This PR has the following benefits:
A. It fixes a genuine bug.
B. It enables Cleanflight and Betaflight CC3D PPM users to swap to iNav without rewiring
C. It enables Openpilot/LibrePilot CC3D PPM users to swap to iNav without rewiring (although quad users have to set up a custom mixer).

However, I agree that we should not cause problems for existing users. I can see three solutions to this:
1. Revert the PR
2. Create an additional CC3D build with the PPM set to PWM1
3. Add a CLI setting to allow users to set PPM to PWM1 if required

Of these I prefer (2). It's a bit of a nuisance having 2 CC3D builds, but that is not too problematic. I can look into implementing (3) if you like though.

Any further thoughts?

**Comment by oleost** [comment]
To sum up:

Pro: You can use CC3D with oneshot and at the same time using an aux channel (IE switch to arm)

Cons: 
You loose the default pin layout of iNav.
You loose the an softserial port. (If using Sonar or RSSI_ADC)
Existing users need to rewire. (Well, don't have to. Just dont update your FC)

So I guess feature wise its the choose between oneshot or loosing the abbility to use both sonar and softserial?

**Comment by bk79** [comment]
I'm already using oneshot on cc3d without issues so i don't see the
benefits ppm glitch looks to me something related on how ppm is read on the
actual input
Il 23/mag/2016 09:58, "oleost" notifications@github.com ha scritto:

**Comment by sppnk** [comment]
@oleost , for now, Softserial is not usable in CC3D airplanes. (#177), so I dont guess we loose it. Because of that I am using USART1 shared and I am fine with that (telemetry,  OSD and BT all-in-one).

Anyway, the option 3 is the best for me, as I dont had to rebuild my entire planes in next updates. To have diferent builds will finish dropping one of them :-).

**Comment by digitalentity** [comment]
There is another possible solution. Rewrite PPM handling code in a way it won't use a timer - use EXTI and measure intervals using precision timer (i.e. DWT). Interrupt latency is low and PPM shouldn't be more jittery than it is now.

**Comment by digitalentity** [comment]
For now I feel that having another build target is the best way with a big notice to users that this target is legacy and will be removed. 
Pros:
1. Allow users to migrate without rushing it.
2. Fixing a bug
3. Allowing OpenPilot users to migrate to INAV without rebuilding the machine

Cons:
1. Softserial can't be used together with sonar or ADC on new target

**Comment by martinbudden** [comment]
@digitalentity , OK I'll create another build target.

**Comment by martinbudden** [comment]
@digitalentity , I've created a new build target CC3D_PPM1 that has the old behaviour.

See PR https://github.com/iNavFlight/inav/pull/244

**Comment by digitalentity** [comment]
Thanks! This should allow smoother transition for those who don't want to
rebuild :)

**Comment by sppnk** [comment]
So, If I understand well, 
"inav/docs/Board - CC3D.md" is not up to date with existing pinout, isnt it?

**Comment by martinbudden** [comment]
@sppnk , the pull request includes an update to the documentation.

**Comment by sppnk** [comment]
Now is perfect. Thks.

**Comment by sppnk** [comment]
@martinbudden , @digitalentity . Has this been tested ? I have done this:

$ git pull
$ git checkout fw-improvements
$ make TARGET=CC3D

And then I have flashed the .hex file generated.

But I have not signal in radio tab (neither in EZGUI radio tab). Nor in the PIN8, neither PIN3. Everything  reconfigured well (feature RX_PPM etc)

I have flashed again with INAV 1.1 (last stable release) and everything goes fine.

May be am I doing something wrong? Thks.

**Comment by martinbudden** [comment]
@sppnk , yes this has been tested. The PIN8 version is the version I use. I've also tested the PIN3 version, which was a bit of a pain because I had to take a quad apart and rewire it to test.

You should build from the master branch - this code is in the master branch. I'm not sure of the state of things on the `fw-improvements` branch - I have never used that branch.

Also, don't forget to set the receiver to PPM in the configurator (I presume you have done this, but just double-checking).

**Comment by sppnk** [comment]
@martinbudden, thks for your answer. 

Yes, I set feature RX_PPM, as usual in my models. I made a dump from a working CC3D with 1.1 and after flash it with fw-improvements branch, I restored that dump in the FC.

I tested that everything was fine in the configurator, except PPM input. I thought that building from fw-improvements branch would have this pull request (as it has been already merged), but may be something is wrong with that.

I will give a try again asap. If it works for you, should do for me.

**Comment by sppnk** [comment]
Did this solve #177? Thks

**Comment by digitalentity** [comment]
No. This patch fixes a different bug.

**Pull request merged**
