### PR TITLE
Convert input, output and navigation to use [-1, 1]

### LINKED ISSUE #262: Make iNav more compatible with 3d multirotors
Think it would be a good idea to make iNav more compatible with 3d enabled multirotors.

Looking at @borisbstyle [betaflight](https://github.com/betaflight/betaflight) they have implemented a "3d disable switch" 

https://github.com/betaflight/betaflight/commit/fa63ab52e148cd8cb03053085e638ddd0a492632

https://github.com/betaflight/betaflight/commit/1e8f2bacb871dac9630698f3641b71301d838bab

https://github.com/betaflight/betaflight/commit/5290e4be5637b23b45fac03c45f291c15537b3ac

Is this possible to use and auto disable 3d with navigation modes?

### LINKED ISSUE #1879: 3D Neutral is not Symmetrical
3D Neutral offset appears to be hard coded around 1550ms and cannot be changed. I have [Mid Throttle = 1500] and [3D_Neutral = 1500].  With [3d_deadband_throttle = 1], the motors change from reverse to forward around 1551ms. They then change back from forward to reverse around 1550ms as measured from the receiver window.  Changing the 3d_neutral value does not make any difference.

### LINKED ISSUE #2120: Version 1.7.3 3D mode Arming Not Working Properly
In version 1.7.3 the FC will not arm unless the throttle stick is at mid-throttle when arming occurs .  In all previous versions if the FC is armed at low throttle the motors will start to spin when center stick is reached.  In 1.7.3 if the FC is armed at low throttle they will not start to spin when mid-throttle is reached.

### PR DESCRIPTION
**Pull request by fiam**
~Throttle expo is not yet implemented. Everything else should be working.~

Flight tested with several packs on fixed wing, both unidirectional and bidirectional throttle work fine but there are a few non critical fixes to be made ~(rate limiting is not yet implemented for bidirectional motors)~. We need someone to test it on multirotors.

Fixes #2120
Fixes #1879
Fixes #262

### CODE REVIEW

**Comment by fiam** [comment]
I think this is ready to go once it's tested and any bugs fixed. I've started working on other things like "brake by reverse thrust" and "capture stick input" (which will let us open CMS while nav is controlling the vehicle), but those will be submitted as separate PRs. This one is big enough already.

**Comment by shellixyz** [comment]
Very nice work. I checked the expo calculation code, it is working well. What is the block in rc_curves.c line 64 for ? Seems superfluous to me.

```
    if (deflection >= RC_COMMAND_MAX * 0.99f) {
        return RC_COMMAND_MAX;
    }
```

**Comment by fiam** [comment]
@shellixyz It's meant to do the same that this block did in `rcLookupThrottle()`:

```
    if (absoluteDeflection > 999)
       return motorConfig()->maxthrottle;
```

It also seems superfluous to me, but since I wasn't sure I decided to keep the existing functionality.

**Comment by shellixyz** [comment]
@fiam It is superfluous in this case. It was to prevent a division by 0 in the old code.

**Comment by fiam** [comment]
Good catch. I’ll remove it.

**Comment by stronnag** [comment]
Minor MR test today. Piloted flight (including self-levelling modes was fine).

PosHold caused the machine to rise at about 1m/s (x-y hold was fine). The lack of Z-hold does not occur 
in development branch, so appears to be an artefact of this PR.  Log and `diff` available if needed (all nav settings are default for this test).

I will do some more nav modes testing once PH is working.

**Comment by fiam** [comment]
Thank you so much @stronnag. I’m glad to hear the XY hold is working fine, that narrows the problem with the Z axis a lot.  I’ll re-read the althold code later today, hopefully I can spot it.

**Comment by fiam** [comment]
@stronnag Latest commit should have fixed the problems with AH. Can you give it a try when you have time? Thanks!

**Comment by stronnag** [comment]
Sure, this weekend.

**Comment by stronnag** [comment]
At least if I ever get beyond:

```
%% rc_modes.c 
./src/main/fc/rc_modes.c: In function 'processAirmodeMultirotor':
./src/main/fc/rc_modes.c:81:13: error: 'rcCommand' undeclared (first use in this function)
             rcCommand[THROTTLE] > rcControlsConfig()->airmodeThrottleThreshold &&
             ^~~~~~~~~
./src/main/fc/rc_modes.c:81:13: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by fiam** [comment]
Oops. Must have gotten in when rebasing on HEAD of the development branch. I’ll get it fixed in a bit.

**Comment by fiam** [comment]
@stronnag It should build now

**Comment by stronnag** [comment]
I tried this again today:

* Test1: PH still seems to be slowly gaining altitude.
* Test 2: Prior to engaging PH, while hovering in horizon mode, the machine started oscillating wildly before plummeting into the ground; breaking 2 of 3 props, landing gear (zip ties) and the GPS mast base (plywood). So no big deal, just like 2015. pre-1.0 testing all over again ....

As I had some mismatched spare props, I made a francken tri, which flew development without problem, so I'm discounting the new compiler or other environmental factors.

I (probably) have logs if it helps.

**Comment by fiam** [comment]
Ouch! Sorry to hear that :-( - Can you post the blackbox logs? They should be helpful diagnosing what went wrong.

**Comment by stronnag** [comment]
LOG00001.TXT : Gently ascending
LOG00002.TXT : Rapidly, uncontrollable descent

Just part of of process. I understand the risks (and rewards).

[LOG00001.TXT](https://github.com/iNavFlight/inav/files/3145791/LOG00001.TXT)
[LOG00002.TXT](https://github.com/iNavFlight/inav/files/3145792/LOG00002.TXT)

May not be massively helpful as the logging rate is set up for 'where have I been' rather than 'WTF happened'. 
I can try again, I'll take spare props, many zip ties and rapid epoxy :)

**Comment by fiam** [comment]
@stronnag Looks like PID[ROLL] starts overflowing and wrapping around 17 seconds. I've also noticed that rcCommand in blackbox is wrong. I'll try to fix those as soon as possible.

**Comment by stronnag** [comment]
Sounds reasonable, the roll rate was visually impressive prior to impact.

And I've got this box of 'fire sale' 10x5 props from when a UK vendor closed down that I doubted I'd ever use.

**Comment by giacomo892** [comment]
@stronnag do you mind sharing the _diff_ ?

**Comment by stronnag** [comment]
```
# mwptools / fc-cli dump at 2019-05-04T14:46:38+0100
# fc-cli is a toolset # (fc-set, fc-get) to manage
# iNav / βF CLI diff backup and restore
# <https://github.com/stronnag/mwptools>

# diff all

# version
# INAV/MATEKF405 2.2.0 May  4 2019 / 11:57:35 (31c77dfc1)
# GCC-8.3.0

# reset configuration to default settings
defaults noreboot

# resources

# mixer
mmix 0  1.000  0.000  1.333  0.000
mmix 1  1.000 -1.000 -0.667  0.000
mmix 2  1.000  1.000 -0.667  0.000

# servo mix
smix 0 5 2 -100 0 -1

# servo

# logic

# feature
feature -CURRENT_METER
feature -OSD
feature GPS
feature BLACKBOX
feature PWM_OUTPUT_ENABLE

# beeper
beeper -ON_USB

# map
map TAER

# serial
serial 0 17 115200 38400 115200 115200
serial 3 2 115200 115200 0 115200

# led

# color

# mode_color

# aux
aux 0 0 5 1500 2100
aux 1 2 1 900 2100
aux 2 3 0 1300 1700
aux 3 3 6 1500 2075
aux 4 9 0 1300 1700
aux 5 9 6 1425 2100
aux 6 8 0 1700 2100
aux 7 19 3 1700 2100
aux 8 11 2 1650 2075

# adjrange

# rxrange

# temp_sensor

# wp
#wp 0 invalid

# osd_layout

# master
set gyro_hardware_lpf = 256HZ
set gyro_lpf_hz = 70
set gyro_notch1_hz = 170
set gyro_notch1_cutoff = 125
set gyro_notch2_hz = 85
set gyro_notch2_cutoff = 43
set acc_hardware = MPU6500
set acczero_x = 17
set acczero_y = 12
set acczero_z = -183
set accgain_x = 4024
set accgain_y = 4153
set accgain_z = 4073
set align_mag = CW270FLIP
set mag_hardware = HMC5883
set mag_declination = -110
set magzero_x = -17
set magzero_y = -84
set magzero_z = -49
set baro_hardware = BMP280
set pitot_hardware = NONE
set rssi_channel = 9
set serialrx_provider = SPEK2048
set rx_min_usec = 985
set blackbox_rate_denom = 16
set min_throttle = 1090
set max_throttle = 2000
set motor_pwm_rate = 2000
set motor_pwm_protocol = MULTISHOT
set failsafe_delay = 10
set failsafe_off_delay = 10
set failsafe_throttle = 1400
set failsafe_procedure = RTH
set failsafe_stick_threshold = 400
set vbat_scale = 1110
set platform_type = TRICOPTER
set model_preview_type = 1
set servo_pwm_rate = 330
set servo_lpf_hz = 150
set tri_unarmed_servo = OFF
set disarm_kill_switch = OFF
set gps_provider = UBLOX7
set gps_sbas_mode = EGNOS
set gps_ublox_use_galileo = ON
set inav_reset_altitude = EACH_ARM
set nav_disarm_on_landing = ON
set nav_wp_radius = 150
set nav_auto_speed = 600
set nav_auto_climb_rate = 300
set nav_land_slowdown_maxalt = 1000
set nav_emerg_landing_speed = 400
set nav_rth_abort_threshold = 5000
set nav_rth_altitude = 2500
set nav_mc_hover_thr = 1550
set nav_mc_auto_disarm_delay = 500
set throttle_tilt_comp_str = 10
set name = tri-f405
set tz_offset = 60

# profile
profile 1

set mc_p_pitch = 110
set mc_i_pitch = 20
set mc_d_pitch = 52
set mc_p_roll = 110
set mc_i_roll = 20
set mc_d_roll = 52
set mc_p_yaw = 75
set mc_i_yaw = 20
set mc_p_level = 10
set mc_i_level = 12
set heading_hold_rate_limit = 60
set roll_rate = 55
set pitch_rate = 48

# profile
profile 2


# profile
profile 3


# battery_profile
battery_profile 1

set vbat_max_cell_voltage = 425

# battery_profile
battery_profile 2


# battery_profile
battery_profile 3


# restore original profile selection
profile 1
battery_profile 1

# save configuration
save

```

**Pull request closed without merging**
