### PR TITLE
Add feature for enabling/disabling profile selection by TX stick command

### PR DESCRIPTION
**Pull request by shellixyz**
Closes feature request #2485.

Matching configurator update: https://github.com/iNavFlight/inav-configurator/pull/359

### CODE REVIEW

**Comment by fiam** [comment]
@shellixyz I do know that this is already mostly done... but wouldn't it be easier with a plain setting in `rcControlsConfig_t`? It seems to me it would be like ~5 lines of code.

**Comment by shellixyz** [comment]
@fiam Do you think it would be better ?The changes are already small. Basically ~5 already. I changed lot of lines mainly because I renumbered the unused features and the hard part was adding the new feature to the default features bitmap in the `target.h` files. I really didn't ask myself and just followed what @digitalentity said in his [comment](https://github.com/iNavFlight/inav/issues/2485#issuecomment-345186482). The advantage of it being a feature is that it can be changed easily in the GUI.

**Comment by fiam** [comment]
@shellixyz Well, I'm not sure about what would be better. Plus, "done" is always better than "not done" :-).

The setting based approach would require less code overall for sure, though. This approach requires a few supporting changes now and in the future since every target file will need to define `FEATURE_TX_PROF_SEL` as part of the default features, which can be error prone. With a setting, you add a field in `rcControlsConfig_t`, initialise it in the PG to `false`, put the setting in `settings.yaml`, add the `if` to check for it and you're done forever.

I'm not a fan myself of the features system. I think they're a bit redundant these days, since they don't offer anything that can't be done via settings (you can always set default settings for a target via `targetConfiguration()`) and they require different syntax/storage. So I'd rather see stuff removed from features than added. 

Just to clarify: I'm not opposed to doing it this way, I'm just wondering if the settings based approach is better. Maybe someone can offer a different point of view.

**Review by digitalentity — APPROVED** [review]

**Comment by shellixyz** [comment]
@fiam Well this has been merged but what we can do is define a set of common default features (that would include FEATURE_TX_PROF_SEL) and OR them to the default features defined in the target. That way new targets won't have to define it themselves.

**Comment by digitalentity** [comment]
@shellixyz I like the idea

**Comment by fiam** [comment]
That would be good. The only thing I don’t like of this approach is that default features is no longer zero, so every future target will need to define this new one and that’s error prone.

**Comment by shellixyz** [comment]
> every future target will need to define this new one and that’s error prone

@fiam Sorry I don't understand. The change I proposed will avoid having to define this new feature in future targets.

The benefit I can see to features if I'm not mistaken is that it is saving RAM. Right now 22 features are used and stored in a 32bit map. If we use settings instead and define one boolean for each feature wouldn't that use 18 (22-4) more RAM bytes ?

**Comment by digitalentity** [comment]
@shellixyz @fiam I'm in favor of feature-based approach, it's less RAM hungry.
@shellixyz please go ahead with your suggested change - add a `COMMON_DEFAULT_FEATURES` in `common.h` and corresponding code in `config.c` 😄

**Comment by fiam** [comment]
@shellixyz I meant the currently committed code without the new proposed change. Sorry, that was confusing!

**Pull request merged**
