### PR TITLE
RTH straight

### PR DESCRIPTION
**Pull request by shellixyz**
The aircraft will go down linearly until hitting `rth_altitude` just before starting to circle above home if RTH was started above `rth_altitude` and `rth_straight` is set to `ON`

### CODE REVIEW

**Comment by Mckenzie74** [comment]
Awesome!
That’s exactly what I try to do when coming back. I fly in cruise and pitch down just a little to achieve the ideal slope to home. Obviously I often do that wrong...

**Comment by teckel12** [comment]
@shellixyz How is this different than `nav_rth_alt_mode = FIXED`?  And if it's different in some way, why not creating a new RTH altitude control mode, `STRAIGHT` for example?  Maybe this is some FW-only thing that I'm not familiar with.

**Comment by shellixyz** [comment]
@teckel12 I believe `FIXED` will go down at the maximum pitch for planes until hitting `rth_altitude`. `rth_straight` is more efficient for FW. I added a setting instead of just adding an altitude mode because altitude mode is for specifying the altitude to start RTH at. This way you can still chose how you want it to behave altitude-wise before going home. You can still use `MAX_ALT`, `FIXED_ALT` or `EXTRA_ALT`. The only mode it doesn't make sense to use it with is `CONST_ALT`.

**Comment by shellixyz** [comment]
Tested again today with 2.1 as base. All working fine

Here is a demo video: https://youtu.be/RznTuZbgDLk

Settings used:
* rth_alt_mode = AT_LEAST
* rth_altitude = 10000 # 100 meters
* rth_home_altitude = 6000 # 60 meters
* rth_straight = ON

**Comment by expipiplus1** [comment]
Some diagrams to go with the existing ones would be useful I think.

**Comment by expipiplus1** [comment]
I had a go with this and got some strange behavior; the plane would pitch down and glide (as expected), but after a few seconds it would pitch up back to neutral and fly powered for a few seconds before pitching down again to repeat the cycle.

My config:
https://gist.github.com/f3322e691f2c2d95844ca98c6606e7e6

**Comment by shellixyz** [comment]
@expipiplus1 You probably need to tune ALTHOLD for your aircraft (altitude management PID loop settings `nav_fw_pos_z_{p,i,d}`).

> Some diagrams to go with the existing ones would be useful I think.

You're right

**Comment by shellixyz** [comment]
I updated the code to make it clearer. I wrote this last year and didn't realize it was so obscure.

**Comment by wilco1967** [comment]
Just tried nav_rth_alt_mode = AT_LEAST_LINEAR_DESCENT at Yesterday development version. 

However, linear descent doesn't seem to work.

When I enable RTH, it takes an immediate dive at what seems maximum down pitch angle, and stops only at 150 meters (nav_rth_altitude = 15000) as fast as it can while still far away.... Once it reaches 150 meters, it will continue RTH at 150 meters normally....

Plane: MiniTalon / R9M / MatekF722

here's the BB log
[LOG00056.TXT](https://github.com/iNavFlight/inav/files/3243649/LOG00056.TXT)

And here's my diff. (stripped of useless OSD lines)
[iNav 2.2.0dev - MatekF722 - 20190601 DIFF.txt](https://github.com/iNavFlight/inav/files/3243650/iNav.2.2.0dev.-.MatekF722.-.20190601.DIFF.txt)

This should be a great feature (once it works ;-).... Looking forward to be able to also have linear climb / descent during Waypoint missions as well.

Thanks !

**Comment by putimir** [comment]
Same thing exactly today - diving until almost reaching nav_rth_altitude and then proceeding RTH @ nav_rth_altitude

**Comment by digitalentity** [comment]
Yep, there seem to be a bug. See #4778

**Comment by wilco1967** [comment]
Update: 4-june
This issue has been resolved, and will probably be implemented in 2.2.0RC3
2.2.0 RC2 does NOT yet have the corrections, so be aware.

See #4778 

Be aware of steep dives in RC2 or earlier versions, if trying nav_rth_alt_mode = AT_LEAST_LINEAR_DESCENT
It will do a RTH, but dive immediately to nav_rth_altitude

**Pull request merged**
