### PR TITLE
Tail first in NAV RTH

### PR DESCRIPTION
**Pull request by FabianSchwartau**
A waypoint RTH will, just like the RTH mode, respect the value of nav_rth_tail_first. If turned on, the drone will fly tail first back to the home position.
Fixes https://github.com/iNavFlight/inav/issues/5417

### CODE REVIEW

**Comment by FabianSchwartau** [comment]
Can someone else also test this, so we can merge it? Or why has this not been merged yet?

**Comment by digitalentity** [comment]
@Jacky2k can you please rebase and force-push to trigger the tests?

**Comment by FabianSchwartau** [comment]
OK, may take a few days. I am quite busy...

**Comment by digitalentity** [comment]
I'm force-merging this

**Comment by FabianSchwartau** [comment]
Thanks a lot, have not had time to look into this :(

**Pull request merged**
