### PR TITLE
Change current sensor offset voltage unit to 0.1mV

### PR DESCRIPTION
**Pull request by shellixyz**
Makes the current sensor offset calibration more precise and the offset unit match the scale unit.

Matching configurator update: https://github.com/iNavFlight/inav-configurator/pull/397

### CODE REVIEW

**Comment by shellixyz** [comment]
Future ? ^^

**Comment by fiam** [comment]
@digitalentity  Can we get this in 2.0? Seems like an appropriate time.

**Comment by digitalentity** [comment]
Yeah, go ahead :)

**Comment by shellixyz** [comment]
Rebased

**Pull request merged**
