### PR TITLE
Allow LED pin to be reassigned as MOTOR or SERVO

### PR DESCRIPTION
**Pull request by mmosca**
This is a continuation of timer output mapping, adding led pins to the pool.

* [x] Add led option to timer_output_mode 
* [x] Show led option in diff
* [x] Correctly set outputs as led
* [x] Update MSP messages to send full 32bit timer usageFlags
* [x] Verify LED behavior when assigning random output as LED (LED pin has priority. Only 1 pin (first) gets to play led)
* [x] Verify Servo assigned to LED works. Needs changing light_ws2811strip.c to pick: IO_TAG(WS8211_PIN) if not remmaped, or first available pin tagged as TIM_USE_LED
* [x] Check all targets to make sure LED declaration in target.c comes after PWM outputs.
* [x] Add special label info to MSP message (uint8_t/uint16_t?)
* [x] Flag Led pin in MSP message (use IO_TAG to check which pin is led)

### CODE REVIEW

**Comment by rmaia3d** [comment]
This will be a GREAT feature! 👍

**Comment by mmosca** [comment]
Looks like led initialization happens beffore servo/motor outputs, causing later, when overriding the led output with led enabled.

**Comment by MrD-RC** [comment]
It would be great if the LED pad could be assigned to PINIO too.

**Comment by mmosca** [comment]
That might be possible, but will certainly be a bit complicated as it needs to handle user modes which may already be there. []s,Marcelo Bezerra ***@***.***>On 24 May 2024, at 18:32, Darren Lines ***@***.***> wrote:﻿
It would be great if the LED pad could be assigned to PINIO too.

**Pull request merged**
