### PR TITLE
Enhance Linear Descent RTH feature

### LINKED ISSUE #8739: Linear Descent radius relative to the home point
## Current Behavior
In case if AT_LEAST_LINEAR_DESCENT mode is used for RTH, 
the aircraft will start descending immedieately and all the way towards the home point.

## Desired Behavior
Would be more logical to set a radius around the home point of where the 
linear descent will start.

## Who does this impact? Who is this for?
Airplane users

## Additional context
In some cases you have to gain higher than AT_LEAST altitude in order to have good signal, 
but in the case where RTH has started, the plane will descend immediately, being 1/2 of the max altitude
on the 1/2 way home, causing a risk to not get your signal back even on 1/2 way to home.
If the linear descent would start at the desired distance to home, this would both achieve economy during rth
(Economy is necessary during RTH because we want our model back safe) and higher brobability of getting 
your control back much prior to reaching home point

### PR DESCRIPTION
**Pull request by MrD-RC**
Addresses an issue/request discussed on Discord

This PR takes the existing Linear Descent option for RTH and enhances it. Firstly, Linear Descent is now no longer an RTH type. If previously using `AT_LEAST_LINEAR_DESCENT`, you should now just use `AT_LEAST` as the RTH type. Linear Descent is now a separate option that can be used with any other RTH type. To do this, the target altitude of the descent is now the `nav_rth_home_altitude`. In some cases, if flying below the home position, this could even be a linear ascent.

An option has also been added to decide how far away the linear descent starts. This is via the `nav_rth_linear_descent_start_distance` parameter. Current behaviour can be maintained by setting this to `0` [default]. You can also specify a distance from home when the descent begins. This is in metres and be up to 10km. Of course, this value can be adjusted if required.

This has been tested in HITL using `AT_LEAST` and `MAX` RTH types. There have been tests with linear descent enabled or disabled, and with varying start distances. All test results as expected. I will create some test videos shortly with other RTH types and with RTH Home Altitude set to 0.

### Configurator

This change require configurator PR https://github.com/iNavFlight/inav-configurator/pull/1727

Options to set up Linear Descent have been added to the Configurator.
image

If Linear Descent is enabled, and the RTH Home Altitude is less than 10m. A warning is shown around the RTH Home Altitude input box. People can still enter whatever values they want, including 0. If the RTH Home Altitude is not set, Linear Descent is not used in flight.
image

Fixes #8739

### CODE REVIEW

**Comment by Jetrell** [comment]
@MrD-RC  The tests of this feature went well with a quad.
There was a slight headwind (6kph),

Setting were -
`nav_rth_alt_mode = EXTRA`
`nav_rth_altitude = 3000`  (30m on top of RTH activation altitude)
`nav_rth_home_altitude = 1500`  (15m)
`nav_rth_linear_descent_start_distance = 100` (Linear descent starts 100m from home)



https://user-images.githubusercontent.com/47995726/220014016-35fd512a-dea0-4ed8-b665-0a1ba86711f6.mp4

**Comment by MrD-RC** [comment]
# HITL Tests

Firstly, I have to say that with the video capture software running in the background. The flight gets jumpy and the OSD data is a bit laggy. But, the numbers ultimately get hit. Plus, without the capture software, the flight is much more realistic.

## Linear Descent inactive tests
### Test 1 - `AT_LEAST` : Linear Descent `OFF`
I only ran one test with Linear Descent OFF, because the functionality is independent on the RTH type. So ON/OFF is the same for all.

https://youtu.be/w8zDatgi4Ms

### Test 2 - `AT_LEAST` : Linear Descent `ON` - No home altitude set
If home altitude is set to 0. Linear Descent should be ignored, even if turned on. Again, I only ran this test once, as it is independent of RTH type.

https://youtu.be/Bl2JhCrzdxo

## Linear Descent active tests
In all these tests, Linear Descent is turned `ON`. A RTH Home Altitude of 75 metres is set.

### Test 3 - `AT_LEAST`
https://youtu.be/-WqhLdVTdjw

### Test 4 - `MAX`
https://youtu.be/PLMYaqD56tA

### Test 5 - `FIXED`
https://youtu.be/rTbCV8SYiQ0

### Test 6 - `EXTRA`
There are two parts to this test. Part one is how a normal RTH would be. In part 2, I tried seeing what would happen starting at a negative altitude.

https://youtu.be/jUVhHkTK-pM

### Test 7 - `CURRENT`
https://youtu.be/cg8FCClzQ3U

**Comment by MrD-RC** [comment]
This will need to be 7.0 as it breaks compatibility. I originally set to the 6.1 milestone as there was no 7.0, and I expected 6.1 to just be renamed 7.0. I guess 6.1 will just be a pretty small release.

**Comment by MrD-RC** [comment]
Tested in flight. Worked as expected.

**Pull request merged**
