### PR TITLE
PID - Remove legacy MW PID controller, replace with modified LuxFloat

### PR DESCRIPTION
**Pull request by digitalentity**
This will free a lot of flash for #85, #65, #62, #26 and other great features.

### CODE REVIEW

**Comment by digitalentity** [comment]
For NAZE target:

master branch:

```
   text    data     bss     dec     hex filename
 127364     832   14364  142560   22ce0 ./obj/main/inav_NAZE.elf
```

fp-pid branch:

```
   text    data     bss     dec     hex filename
 124940     820   14216  139976   222c8 ./obj/main/inav_NAZE.elf
```

Saves ~2.4K bytes of memory

**Comment by stronnag** [comment]
Are the recommended / default PIDs as for Lux? 
So it I have Lux pids I'm content with, can I just use them  or should I re-tune?

**Comment by digitalentity** [comment]
@stronnag 
No, PIDs have different scaling. You should start with the defaults and re-tune.

**Comment by stronnag** [comment]
build fails for spracingf3:

```
./src/main/flight/gtune.c: In function 'init_Gtune':
./src/main/flight/gtune.c:110:16: error: 'pidProfile_t {aka struct pidProfile_s}' has no member named 'pidController'
  if (pidProfile->pidController == 2) {
                ^
./src/main/flight/gtune.c:121:27: error: 'pidProfile_t {aka struct pidProfile_s}' has no member named 'P_f'
             if((pidProfile->P_f[i] * 10.0f) < pidProfile->gtune_lolimP[i]) {
                           ^
./src/main/flight/gtune.c:122:27: error: 'pidProfile_t {aka struct pidProfile_s}' has no member named 'P_f'
                 pidProfile->P_f[i] = (float)(pidProfile->gtune_lolimP[i] / 10.0
                           ^
./src/main/flight/gtune.c:124:48: error: 'pidProfile_t {aka struct pidProfile_s}' has no member named 'P_f'
             result_P64[i] = (int16_t)pidProfile->P_f[i] << 6;                  
                                                ^
./src/main/flight/gtune.c: In function 'calculate_Gtune':
./src/main/flight/gtune.c:200:31: error: 'pidProfile_t {aka struct pidProfile_s}' has no member named 'P_f'
                     pidProfile->P_f[axis] = (float)newP / 10.0f;               
                               ^
Makefile:717: recipe for target 'obj/main/SPRACINGF3/flight/gtune.o' failed
make: *** [obj/main/SPRACINGF3/flight/gtune.o] Error 1
```

**Comment by digitalentity** [comment]
Oh, I've forgot about GTune. Thanks I'll fix this tomorrow.

**Comment by stronnag** [comment]
I also noticed that previously:

```
set nav_navr_d = 80
```

The default in the new PIDC is 

```
set nav_navr_d = 8
```

Intended or a typo?

**Comment by digitalentity** [comment]
This is intended. D-term scaling changed for navigation pids.

**Comment by stronnag** [comment]
I just tried a hover in the garden. The quad spins on the yaw axis at > 1Hz. I may have a BB log.
edit -- I don't, unfortunately

**Comment by digitalentity** [comment]
Thanks. This is really strange, I don't see anything that might cause
uncontrolled yaw in the code. Will review again tomorrow...

**Comment by stronnag** [comment]
Indeed, well passed bed time in your time zone. I have a tethered BB log, where is does not respond to yaw, which I'll post in a few hours time, so you need not stay up any longer!

**Comment by digitalentity** [comment]
I'm in Israel at the moment, it's GMT+2 only :)

**Comment by stronnag** [comment]
OK, I relent:) I appreciate how much of a drag long business trips can become. http://seyrsnys.myzen.co.uk/inav-fp-pid/
LOG0030.TXT is tethered, new pidc
LOG0031.TXT is short hover with old PIDC 2 & 1.

**Comment by digitalentity** [comment]
Thanks for the logs! I'll try to analyze them tomorrow and hopefully will
figure out what went wrong this time.

**Comment by digitalentity** [comment]
This is strange. Looks like axisPID[YAW] doesn't go to motors at all.

**Comment by digitalentity** [comment]
This looks even more strange. I don't see any issues with yaw axis when doing a bench-test with your dump.

**Comment by stronnag** [comment]
Thanks for that, prompted me to sort out something that's been bugging me for a while.

I recompiled with GCC 4.9 (vice 5.3). Guess what, hovers perfectly on default PIDs.

I guess gcc 5.3 is not safe. Explains some otherwise inexplicable issues I've had with PH that where irrational and untunable. 

More detailed issue to document this on it's way.

**Comment by digitalentity** [comment]
I also encountered issues with gcc-5.2 generating unsafe code for CC3D bracking VCP functionality and somtimes causing board to hang on boot with certain settings. gcc-4.9 builds work fine.

**Comment by stronnag** [comment]
As it's raining, I didn't get to test on the nav equipped machines. Instead I flew the brushed micro-scisky quad around the house on defaults. RC rate 1, R/P rate 0.7. Nice, tight flips and rolls in horizon mode. 
Probably the best it's ever flown. Impressive.

**Comment by digitalentity** [comment]
@stronnag thanks for testing! This controller is no longer a modified LuxFloat, it's a LuxRewrite :)
Features summary (at the moment):
- Horizon mode - similar to Lux
- P-term - similar to Lux
- I-term - different, taken from iNav PIDs with additional new anti-windup inspired by Betaflight
- D-term - different, completely new way, never used for flight PIDs in CF before.
- Yaw P-term limiting - from Betaflight
- Rate target capped to prevent exceeding gyro 2000dps limitation
- Integer PID coefficients - full Configurator compatibility
- 4-times better tuning resolution than LuxFloat

**Comment by digitalentity** [comment]
I've added new experimental feature - expo on self-leveling strength that will attenuate self-leveling when angle error is small. This shoud allow higher self-leveling gains and/or smoother flight in angle/horizon mode.

p_level - ANGLE/HORIZON self-leveling strength
i_level - expo on self-leveling strength (0-100)
d_level - horizon strength (0-100)

**Comment by stronnag** [comment]
Flown today for nav modes (excellent) and a smaller acro quad in horizon. I'm really not sure about the expo feature. For example, if I have the (270mm) quad hand tethered, and gradually power up, with i_level = 0, it remains level as the power reaches and passed 'hover' value. If I set i_level non-zero (e.g. 10), then at around hover throttle, the machine takes on a roll angle of around 30°. At this stage, I decide I don't really want to fly this.

But it was awesomely good in both nav and LOS/horizon modes with i_level=0; I like it at least as much on betaflight on the 270.

**Comment by digitalentity** [comment]
@stronnag yes, I've tested the expo feature, it's not working as good as I expected it to. I'll figure a different way to make self leveling less jerky. May be an LPF on rateTarget in ANGLE mode

**Comment by digitalentity** [comment]
More tests of the new PID today. Conclusions so far:
1) Expo doesn't work, period.
2) On defaults (same actual values as in old LuxFloat with respect to different scaling) my miniquad is very flyable. On old Luxfloat it was oscillating badly. Raising D-term made it even more stable.
3) 5Hz LPF on rateTarget in Angle mode made self-leveling more robust, slign variations in attitude are corrected smoothly, without jerks. A side-effect is ability to tune PIDs better in ANGLE mode - self-leveling response is smoother and rate PID effects and oscillations are much more evident. Another side-effect is higher possible LEVEL P - same reason, response is smoother, jerks are filtered out.

**Comment by digitalentity** [comment]
**LEVEL_I** now controls self-leveling low-pass filter frequency. 0 - disable. Practical values are in range 5-10. Lower values make quad sluggish, higher don't seem to be different from disabled filtering.

**Comment by stronnag** [comment]
I note default i_level is 160 (not in 5-10 range), I guess this is "higher don't seem to be different from disabled filtering".

I briefly tried (hand tethered) the prior version (before the I filtering) on a mini (300mm) tri-copter. Lots of oscilations above min-throttle (and at less than hover throttle). So I took it no further. I'll have a play around with the level parameters on that platform with then latest 'testing'.

**Comment by digitalentity** [comment]
@stronnag default i_level is 10, at least in the code. Please make sure you flash with full erase to prevent issues with old config.

**Comment by stronnag** [comment]
mea culpa, looking at the wrong dump backup ....

**Comment by stronnag** [comment]
I flew this again on the 420mm nav quad, and it's excellent (so sorry, no logs). Anyway great PH, RTH etc. Crisp rolls, almost too crsip flips (I don't usually roll/flip this heavy beast).

Then I tether tested the mini-tri. There's two explanatory logs, the same  test. Hand tether, arm, gradually increase throttle to (and for betaflight, beyond) hover. In the fp-pid case, mega unstable, in the BF case, smooth (MWREWRITE). This pidc does not appear to like my tricopter. Naive adjustments +/- 50% on P (P/R/Y) and level strength didn't appear to have any effect on the overwhelming oscillations. For the log, settings are default, with gyro sync and denom = 2. Couldn't get it to arm at denom 1, possibly due to high CPU usage?

[tri-beta_mwrewrite.TXT](https://github.com/iNavFlight/inav/files/171075/tri-beta_mwrewrite.TXT)
[tri-fp-pid.TXT](https://github.com/iNavFlight/inav/files/171076/tri-fp-pid.TXT)

Firmware is experimental (testing) branch, 9f7529a9ffbe44ff648d913fab02296ea2cdfd4c

**Comment by stronnag** [comment]
Some more info on looptime. I appreciate that the main target of this PIDC is not insane acro performance, but there does seem to be a CPU hit that does not exist in Luxfloat (which is perfectly usable in betaflight with `set gyro_sync_denom = 1`).

```
# set gyro_sync_denom = 2
gyro_sync_denom set to 2
# save
Saving
Rebooting
Entering CLI Mode, type 'exit' to return, or 'help'

# status
System Uptime: 5 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), System load: 0.02
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n
Cycle Time: 2002, I2C Errors: 0, config size: 1684

# tasks
Task list:
0 - SYSTEM, max = 6 us, avg = 0 us, total = 0 ms
1 - GYRO/PID, max = 1807 us, avg = 1137 us, total = 4797 ms
2 - SERIAL, max = 632 us, avg = 2 us, total = 3 ms
3 - BEEPER, max = 8 us, avg = 0 us, total = 1 ms
4 - BATTERY, max = 17 us, avg = 0 us, total = 3 ms
5 - RX, max = 70 us, avg = 39 us, total = 27 ms

# set gyro_sync_denom = 1
gyro_sync_denom set to 1
# save
Saving
Rebooting
Entering CLI Mode, type 'exit' to return, or 'help'

# status
System Uptime: 4 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), System load: 4.16
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n
Cycle Time: 1181, I2C Errors: 0, config size: 1684

# tasks
Task list:
0 - SYSTEM, max = 4 us, avg = 0 us, total = 0 ms
1 - GYRO/PID, max = 1796 us, avg = 1135 us, total = 9771 ms
2 - SERIAL, max = 633 us, avg = 2 us, total = 1 ms
3 - BEEPER, max = 8 us, avg = 0 us, total = 0 ms
4 - BATTERY, max = 17 us, avg = 0 us, total = 2 ms
5 - RX, max = 71 us, avg = 39 us, total = 15 ms

# exit
```

There seems to be quite a CPU hit between 1000/2000 loops (with or without gyro_sync), that is not present in Luxfloat. 

Is this to be expected?

**Comment by digitalentity** [comment]
@stronnag 
To narrow down the problem with your mini-tri can you please test iNav latest master (235ebf667a01d8cee30f76fb8cba275b4d0640f8, LuxFloat PIDC)? 
I'm also very interested if the problem is caused by self-leveling. Can you tether test your mini-tri on "testing" in acro mode?

Unfortunately I don't have a tricopter setup and all quads seem to work good with new PIDc :confused: 

The new PIDC is very taxing on CPU at the moment (GYRO/PID avg = 1137 us). When the code is mature enough I'll convert it to fixed-point, which will make it much faster.

**Comment by digitalentity** [comment]
@stronnag 
Having a second look on your log, looks very much like I-induced oscillation, can you also try lowering your I-gain considerably?

**Comment by digitalentity** [comment]
@stronnag 
"fp-pid" and "testing" branches now include blackbox logging for rateTarget setpoint to assist debugging.

**Comment by digitalentity** [comment]
@stronnag 
Try to lower R/P/Y I-Term by 3-4 times and see if it helps. I believe this is the cause.

**Comment by stronnag** [comment]
The problem was a stupid person who forget than align_board_yaw is in deci-degrees. Mea cupla, mea maxima culpa.

Looks OK on default pids. I'll fly one of tricopters on fp-pid 2016-03-15 or 2016-03-16.

(as RCG) There are some logs from the nav equipped 420mm quad with fp-pid, please see http://www.zen35309.zen.co.uk/inav-2016-03-14/.

There are three logs with a mixture of PH, RTH, WP mission and general flying around, including smooth flips and rolls.

Visually, it appears there is c. 1Hz pitch oscillation on RTH (quite visible from the frame lights when flying towards the observer). This is not noticeable in manual flight (albeit at 2x, 3x the speed). Possibly another manifestation of the default pids as discussed in the PR. 

In all cases, RTH landing reached the "Landed" state. There was a gusty NE wind, 10-13 m/s.

**Comment by digitalentity** [comment]
Great! Not a PID problem then :laughing:

**Comment by digitalentity** [comment]
All, I'm thinking about porting new mixer from Betaflight as a part of this PR. What do you think?

**Comment by digitalentity** [comment]
Seems that TPA is a must with new PID controller to get a good tune - #121, and my own experience. 

According to the https://github.com/borisbstyle/betaflight/issues/280#issuecomment-197776054 TPA is not necessary with linear mixer. Looks like it's time to port new mixer from betaflight!

**Comment by plantjes1** [comment]
Finally just tested the FP-PID version...

First version witch flies ok without altering the PID's...
Only the level PID needed a bit lowering..
Pos hold worked very good and alt hold is not so good...

Need to change the PID settings there but i cannot do it anymore with EZ-Gui...
EZ-Gui simply shows empty so i can only change with Cleanflight config..
Made a blackbox log but it was probably not empty as i only could log for 2 minuts...

Benno

**Comment by digitalentity** [comment]
@plantjes1 
AltHold performance is mainly defined by your baro and your accelerometer calibration.

**Comment by plantjes1** [comment]
Yes i realize this, however... Althold was pretty stable with same setup and previous 1.01 (normal) after i changed some PID values.. 
I think i need to play with the PID's to get it perfect...

**Comment by digitalentity** [comment]
@plantjes1 D-term scaling changed. You should reduce VEL D 10 times compared to 1.0.1

**Comment by plantjes1** [comment]
This version is really working for me... 
I made some changes in the PID's and with low wind today it simply works...
Also the movable Poshold was new to me... You switch to poshold and the quad hangs there, than you steer your quad 50 meters away and let go of the stick.. It hangs 50 meters away... (used to go back to first poshold positition)
I attached the Blackbox and pid files in my dropbox...
https://www.dropbox.com/s/cvoau1fg96114x8/blackbox_log_2016-03-20_172416.TXT?dl=0
https://www.dropbox.com/s/fcdz2dtiaizf0oz/pid%20inav%201.01-fp-pid.bmp?dl=0

Thanks...

**Comment by stronnag** [comment]
Most of the time (other than the end of the last log), you were just in Alt Hold, which is even more remarkable given the steady positioning.

**Comment by plantjes1** [comment]
Well Yes, that is what i noticed.. Its strainge anyway as i only made 1 blackbox logging of about 3 minuts and i got 9 parts... (like i switch on and off the logging)..
I flew about 2 minuts in poshold and only the last minute in all other modes (even acro and horizon)
I can't find those mode but i noticed the mode flag is different than the text behind it..

Cannot retest as its dark now...
Continue to morrow.

**Comment by stronnag** [comment]
Disarming / arming will create a new log segment. Just ask if you'd like a video rendering (like the ones I publish to RCG).

**Comment by digitalentity** [comment]
Linear mixer ported from Betaflight (thanks @borisbstyle). Flight tested today on my F450. New mixer definitely gives much more authority at low and high throttle without TPA (although this machine never needed TPA at all).

**Comment by digitalentity** [comment]
New "Heading lock" mode implemented. It's not mag hold - but an adaptation of @peabody124's code from TauLabs (https://github.com/TauLabs/TauLabs/wiki/Flightmode-Settings#axislock)

**Comment by digitalentity** [comment]
Re-tuned my 250-mini for 5x4 Kingkong props (3S), ended up with following:

```
set p_pitch = 63 (default 56)
set i_pitch = 90 (default 30)
set d_pitch = 70 (default 80)
set p_roll = 34 (default 56)
set i_roll = 90 (default 30)
set d_roll = 40 (default 80)
set p_yaw = 120 (default 140)
set i_yaw = 40 (default 40)
set d_yaw = 60 (default 40)
set p_level = 200 (default 160)
set i_level = 25 (default 10)
set d_level = 75
```

**Comment by borisbstyle** [comment]
@digitalentity 
Interresting project I see here! I was actually working on something as well to replace all current pid controllers by new one.
I personally would like to see the coupling feature from MW23 integrated as well. Perhaps good to add an option for that in Rate mode

**Comment by borisbstyle** [comment]
@digitalentity 
Would it take much time from you to add this PR to betaflight so I can work on the coupling part in a separate branch?

**Comment by digitalentity** [comment]
@borisbstyle
Thanks for your interest! I would appreciate if you would test and evaluate this PID for rate mode and help improve it further!
I'm not sure how cleanly this will merge with betaflight, but I'll try to create a PR.

**Comment by digitalentity** [comment]
@borisbstyle
Looks like I am unable to fork betaflight - I have Cleanflight forks all around :smile:

**Comment by DzikuVx** [comment]
@digitalentity do not fork, just add new remote with 
`git remote add betaflight git@github.com:borisbstyle/betaflight.git`

**Comment by digitalentity** [comment]
@DzikuVx Thanks!

**Comment by digitalentity** [comment]
@borisbstyle 
I'm not sure I'll be able to do a clean merge into betaflight - I'll have to remove betaflight's code related to acro plus and some other code as well. As I'm not very familiar with betaflight code base this might take a lot of time.
I've created an fp-pid-tmp branch with squashed fp-pid code if you are interested to see it in one commit.

**Comment by digitalentity** [comment]
I'll tinker with trying to merge this with betaflight in some free time, but this might take longer than I initially expected.

**Comment by borisbstyle** [comment]
@digitalentity 
Doesnt have to be very clean with all other conditions. Just make sure that the rate / acro part is integrated.
Just remove acro plus....thats no problem. This will be a seperate branch for me to test and work on it.

It would just be nice to have a killer PID what removes the need for others.

Were you also thinking about fixed point math?

**Comment by digitalentity** [comment]
@borisbstyle 
Ok, I'll hack something together in next few days. I hope this will indeed be a killer PID.
I'm considering fixed-point math to improve performance and possibly reduce code size, but I'd like to make the code stable first.

**Comment by DzikuVx** [comment]
Had another session with FP-PID today. Total of 8 lipos until now.

Looks like part of my oscillation issues were connected with faulty ESC. It lost saved settings, lost calibration and had no Damped Light on it. Today oscillations at full throttle were almost not a problem.

Setup: Flip32, 2000 looptime, props DAL 5040, 3S 

Those are settings I eneded with (in [] are deafault values):
set p_pitch = 45 [56]
set i_pitch = 95 [60]
set d_pitch = 65 [80]
set p_roll = 40 [56]
set i_roll = 85 [60]
set d_roll = 46 [80]
set p_yaw = 95 [140]
set i_yaw = 50 [40]
set d_yaw = 50 [40]
et roll_rate = 45
set pitch_rate = 35
set yaw_rate = 22
set tpa_rate = 10
set tpa_breakpoint = 1500

Today I finally liked it. @digitalentity I know you usually end up with higher P than defaults, I end up with much lower P. So let's keep default P as it is for now.

Blackbox can be downloaded [here](https://quadmeup.shtr.eu/wp-content/uploads/2016/03/BBlog-sobota-2.TXT.zip)

Next, I gave a try to **_Heading Lock**_. There is a problem I have to investigate further, but the way I see it, it can be enabled all the time. Good job!

**Comment by digitalentity** [comment]
Heh, looks like fp-pid is pushing the limits and makes faulty hardware
evident :)
Good news that you managed to finally tune it to your liking!

**Comment by DzikuVx** [comment]
I'm happy to inform that latest changes works like expected. Heading Lock no longer jumps at arm, and refactored TPA did not causes a crash :)

There is still one thing that caught my attention: D term in YAW. I zeroed it (well, set at 1) and did not felt any difference with YAW behavior. But it was not the same:
- Blackbox log: noise on yaw gyro was lightly lower with almost no D on YAW
- I was finally able to remove TPA on PITCH and ROLL and increase P in them by about 10% without oscillations. 
- The way I see it: no D on YAW and I was able to have 20% more P on PITCH and ROLL 

@digitalentity how about trying much lower D gain on Yaw?

**Comment by digitalentity** [comment]
I am going to test d_yaw=1 today and see if it makes a difference.

**Comment by DzikuVx** [comment]
Today I uploaded latest testing to my big quad (1.8kg of weight and slightly underpowered, 600mm motor span) and FP PID was more less a disaster:
- Flight conditions were very bad: wind gusts up to 15m/s, constant around 7m/s, in the beginning I was even not sure if to fly at all
- In Acro mode it PITCH and ROLL were more less predictible , needed more P and more I. Some tuning and it should be OK
- YAW in Acro was intuducing roll and pitch swinging. Lowering YAW P to 85 and raising YAW I to 50 helped. Will investigate more
- Angle mode in default LEVEL PID gains was a **_disaster**_. Any more aggresive stick movement as introducting huge osciallations. They disappeared after lowering level P to 85. Quad in angle stared to behave very sluggish but what do you expect from almost 2kg of drone?
- Even bigger disaster was **_Heading Lock**_. As long and there was no YAW input, everything was fine. After applying more yaw and putting yaw stick in neutral, quad was staring to swing in YAW axis. Probably it is caused by very low yaw performance of my quad and the fact that I had to lower YAW P. I had to disable Heading Lock to continue flying

On the other hand, GPS performance was **_outstanding!!!**_. (HIGH_G and VELNED=ON). The best GPS result I has so far. PH accuracy was fantastic, specially is such high wind. I've run few PH and RTH scenarios, no problems. Even experienced GPS fix lost for a few seconds. Fix was lost for few seconds (maybe 4), quad drifted, then recovered and returned to previous position. Nice!

**Comment by digitalentity** [comment]
Yaw axis is tricky now. The new mixer may try to sacrifice roll and pitch
to satisfy yaw, this may lead to instability and is an indication of too
high yaw P.

Roll and Pitch for bigger quads are also different, I suggest tuning it
from scratch - that's what I did on my 450 quad and it flies great (didn't
yet try heading hold on it though).

It looks like we are more or less done with GPS performance. That's great.
I was talking to @hydra about recently and we are going to start merging
iNav and Cleanflight after release 1.14.

**Comment by digitalentity** [comment]
I'm considering moving MAG_MODE to PID outer loop, it would be a proper place for it and we can rework it so RC Rates/Yaw rate won't affect its stability.

We can also use same MAG PID for both "HEADING LOCK" and "MAG HOLD" - they have the same idea and the same P-controller for Yaw error to Yaw rate.

**Comment by DzikuVx** [comment]
Good idea, but there is additional issue here we might consider: MAG is updated at 10Hz. Does it make sense to compute it more often? Sure, attitude.values.yaw (500Hz ?) is updated much faster than mag readouts but I'm pretty sure it does not have to executed every iteration to have good results

**Comment by digitalentity** [comment]
What I don't like about MAG HOLD is that it emulates pilot's input thru
modifying rcCommand. The problem there is that actual PID response is also
defined by Yaw rate setting - if you increase rates you'll also get mag
mode acting in a more aggressive manner.

You are right, we probably don't need to calculate MAG HOLD each PID loop
(same is true for heading hold), but we can optimise it afterwards, after
making the control code cleaner.

**Comment by hydra** [comment]
@digitalentity that should be in the current documentation, PR please.

**Comment by digitalentity** [comment]
@hydra you mean MAG HOLD dependence on yawRate? This probably should go to PID Tuning?

**Comment by hydra** [comment]
@digitalentity yes.

**Comment by digitalentity** [comment]
@DzikuVx 
I removed D from Yaw axis altogether. As you indicated a while ago no Yaw_D allows much higher Pitch and Roll P-term and sharper response. Yaw D gave no positive effect on my setups either.

**Comment by bk79** [comment]
@digitalentity before removing Multiwii rewrite, I've have noticed that on luxfloat  (there was I ticket I've opened on cleanflight)  when damped light mode and oneshot125 are  active  on blheli (comp_pwm on simonk) the escs and motors get very hot, specially on hexacopters on motor 5 and 6, something that doesn't happen on multiwii rewrite, for what I've been told on the ticket I've opened luxfloat introduces some microvibration that affect a lot how the motor receive power. before removing everything I would check that new pids are not affected by the same problem

**Comment by digitalentity** [comment]
@bk79, microvibrations are amplified by D-term. New PID controller does great job in filtering out D-term noise. Also in self-leveling modes new code implements additional filtering on self-leveling responce which reduces the possibility of micro-oscillations. On my copters I am able to reach a very solid tune with new PIDs, much better than with old Lux or Rewrite.
I believe you should be fine, but please re-tune your PIDs first.

**Comment by DzikuVx** [comment]
@bk79 I have at least few hours of flight time with FP-PID, BLHeli and DampedLight on my 250. No problems with overheating of motors or ESC

**Comment by stronnag** [comment]
I've flown this on a range of stuff from 105mm brushed quad via mini quads and tris to 600mm tri, no overheating observed, no reduced battery times.

**Comment by bk79** [comment]
The problem i've issued is on hexa on the two additional motor the other 4
where ok
Il 07/apr/2016 17:45, "stronnag" notifications@github.com ha scritto:

**Comment by digitalentity** [comment]
@bk79 motors 5 and 6 are 100% mixed into roll axis, you should check your Roll for oscillations using blackbox. Might be D-term induced oscillations.

**Pull request merged**
