### PR TITLE
Fix board-dependent UART2 skipping

### PR DESCRIPTION
**Pull request by digitalentity**
Addresses https://github.com/iNavFlight/inav/issues/866

### CODE REVIEW

**Comment by digitalentity** [comment]
@martinbudden what do you think about this?

**Comment by martinbudden** [comment]
@digitalentity , I don't know. I've sort of lost track of what is going on with the UARTs and pin assignments.

**Comment by digitalentity** [comment]
Yeah, me to. This needs to be cleaned up, but I'm waiting for IO remapping in BF to be fully done and tested. However, I'm afraid that IO code won't consider airplanes/servo-equipped machines and we'll have to diverge.

**Comment by Linjieqiang** [comment]
I can test for it if you need.

**Comment by digitalentity** [comment]
It doesn't really affect any existing target. It's a cleaner way to ignore timer inputs/outputs that clash with UART2. I'm merging it.

**Pull request merged**
