### PR TITLE
Cleanups for F4 targets

### PR DESCRIPTION
**Pull request by digitalentity**
Looks like F4 targets have stack located in the middle of the RAM instead of at the top of RAM. This caused stack checking code to work incorrectly. 

This PR moves stack to the top of the memory where it rightfully belongs. It may, however, break things if available amount of RAM is specified incorrectly for the target in the linker script.

Also removed unused linker script.

@martinbudden, @sambas what do you think? Should we merge this into 1.3?

### CODE REVIEW

**Comment by martinbudden** [comment]
@digitalentity , although this is probably safe, I'd leave it for 1.4

**Comment by DzikuVx** [comment]
I second postponing to 1.4

niedz., 16.10.2016, 14:33 użytkownik Martin Budden notifications@github.com
napisał:

**Comment by DzikuVx** [comment]
@digitalentity I will test it on my Flip32 F4 branch today

**Comment by DzikuVx** [comment]
@digitalentity tested with #717 . everything seems to be working fine, did few simulated flight on an oscilloscope with arduino as RX. No problems detected

**Comment by night-ghost** [comment]
I'm sorry to bother you, but why do not you place a stack in CCM? 64k which are usually lost in vain

**Comment by digitalentity** [comment]
@night-ghost good idea. Opened an issue to consider it.

**Comment by digitalentity** [comment]
I'm merging this. @DzikuVx can you re-test on AirbotF4 please?

**Comment by DzikuVx** [comment]
@digitalentity I will check today

**Pull request merged**
