### PR TITLE
Add more symbols to BF43 translation table.

### PR DESCRIPTION
**Pull request by mmosca**
Map SYM_FTS, SYM_MS, SYM_KMH, SYM_THR, SYM_ALT and fix Arrow directions.

### CODE REVIEW

**Comment by llambkin** [comment]
Just tested this out now. Looking great! I think there is one or 2 elements that are not displaying correctly. I will find out what they are and post them here.

**Comment by mmosca** [comment]
@llambkin I added the altitude symbom, but the mAH is already there.

BF does not have the efficience related ones, like mAH/km, etc. Maybe that is what you are missing?

**Comment by OlivierC-FR** [comment]
Yay!
not pictured : Throttle symbol is ok.

20221220_203900-edit

**Comment by mmosca** [comment]
> Yay! not pictured : Throttle symbol is ok.
> 
> 20221220_203900-edit2

@OlivierC-FR can you share the diff for your osd?

A lot of the missing symbols are tbhings that don't have a direct mapping to BF.

INAV has all these altitude symbols that don't map to BF:
#define SYM_ALT_M                   0x76  // 118 ALT M
#define SYM_ALT_KM                  0x77  // 119 ALT KM
#define SYM_ALT_FT                  0x78  // 120 ALT FT
#define SYM_ALT_KFT                 0x79  // 121 Alt KFT

Is your speed perhaps 3d speed? That also has a separate symbol that is missing from BF.

I think I need to make something like this: https://github.com/betaflight/betaflight/blob/master/docs/osd.md for INAV.

Should make it easier to report and file sugestions, but probably won't have time until early january to look into it.

**Comment by OlivierC-FR** [comment]
My diff :
https://www.dropbox.com/s/qu99y3zejn7dkx5/INAV_6.0.0_cli_20221220_203220.txt?dl=0

I'll have a look this week-end to try to fill some gaps, but yeah the BF/DJI charset is quite poor

**Comment by OlivierC-FR** [comment]
Almost there, not sure about how to do the "last half", other than heavily butchering the OSD code :(

**Comment by MrD-RC** [comment]
I think that's good. We shouldn't mess with the OSD code too much, just for this system. Especially if DJI are actually talking to Paweł now. Hopefully they'll do what they should have done in the first place and implement the full MSP DisplayPort with user uploadable fonts.

**Comment by OlivierC-FR** [comment]
> I think that's good. We shouldn't mess with the OSD code too much, just for this system. Especially if DJI are actually talking to Paweł now. Hopefully they'll do what they should have done in the first place and implement the full MSP DisplayPort with user uploadable fonts.

100% agree, as-is its working reasonnably well, gives all informations needed for safe flights, the minor display glitches can be ignored until something cleaner is done by DJI. Not point in spending more time in my humble opinion.

**Comment by llambkin** [comment]
Agreed!

**Comment by MrD-RC** [comment]
> I think I need to make something like this: https://github.com/betaflight/betaflight/blob/master/docs/osd.md for INAV.
> 

@mmosca 
https://github.com/iNavFlight/inav-configurator/blob/master/resources/osd/INAV%20Character%20Map.md

**Review by MrD-RC — APPROVED** [review]

**Comment by JasFPV** [comment]
> My diff : https://www.dropbox.com/s/qu99y3zejn7dkx5/INAV_6.0.0_cli_20221220_203220.txt?dl=0
> 
> Correct, 3D GPS speed
> 
> I'll have a look later to try to fix some, but yeah the BF/DJI charset is quite poor.
> 
> I had such a table for INAV charsets, but stopped contributing, and the map I have is now outdated :( https://www.dropbox.com/s/wjbnzzy7mee2h02/charset.inav.ods?dl=0

Will this still work? Amazing work. I have O3 with G2 and looking to get something temporary until DJI "maybe" or maybe not supplies something too us.

**Comment by jeffalanmcclain** [comment]
THANK YOU GUYS SO MUCH for all the work you do here to fix a broken system by the MFG (DJI) and a refusal to support their customers (most O3 HD air units are on BF and iNav and, as such, should have a fully working charset upload / true canvas mode with color options, like their COMPETORS offer...sigh).  One other quick question here, is I notice my Wind Speed (horizontal and vertical) both are missing the arrow indicators, which *should* be able to use the RtH arrow if I'm not mistaken?  Also, I seem to be getting a decimal point, even though the standard code seems to use one of the combo decimal point characters, which I think means someone coded specially for this, but it would appear it is stomping maybe the most significant digit when it exceeds 10mph (or 10kph)?

The attached are with BFHDCOMPAT mode and it is on a day with >10mph winds aloft.  This has GPS, Mag, Pitot and all seem to be working correctly.  I think the display is just getting corrupted values printed out with needing to format for the dedicated decimal point?
Wind Estimate 2
Wind Estimate

**Pull request merged**
