### PR TITLE
Osd support

### PR DESCRIPTION
**Pull request by DzikuVx**
I've started to implement Configurator support (BF port) and some code changes were (will be) needed.

### CODE REVIEW

**Comment by DzikuVx** [comment]
@jflyper Let's replace your pull request #782 with this one if you do not mind

**Comment by jflyper** [comment]
@DzikuVx Yes, go ahead. I'm pretty much done with it for the moment. There were minor changes at the BF side, but I can PR onto your branch.

**Comment by DzikuVx** [comment]
@jflyper cool. I would like to have OSD merged into development as soon as INAV 1.4 is released. Easier to find bugs that way. I hope it could happen somewhere around next week is everything will go according to schedule.
I'm closing your PR now

**Comment by DzikuVx** [comment]
@digitalentity let's merge it as soon as possible. Branch is in "unrebaseable" state and has to be merged
The longer this code will be in `development` the faster we will catch possible bugs

**Comment by digitalentity** [comment]
@DzikuVx merged. Let's do the bug hunting :smile:

**Comment by jflyper** [comment]
Is configurator ready, too?

**Comment by DzikuVx** [comment]
@jflyper not fully https://github.com/iNavFlight/inav-configurator/tree/osd-support
but OSD can be configured using it

**Comment by flounderscore** [comment]
Is the plan to use displayport for the osd (complete port from betaflight)? @jflyper 's pull request (https://github.com/iNavFlight/inav/pull/782) seemed to have been further along than this one.

**Comment by flounderscore** [comment]
I looked into the difference of the BF osd code (with one additional layer of abstraction, i.e. displayport) and iNav. I even started trying to port the code but ended up having to dig deeper and deeper (e.g. slight differences in the max7... driver) and got nowhere. Now I understand why it has been done the way it was.

Sorry about that!

**Comment by jflyper** [comment]
@flounderscore That's okay. The BF code has another layer of abstraction (as you found out) that should make adding & modding CMS and other VCD (video character device?) oriented clients easier. iNav can catch up easily whenever necessary.

**Comment by ShikOfTheRa** [comment]
Displayport for BF is simply awesome. Would love to see that feature in iNav in case this has gone quiet!!

**Comment by martinbudden** [comment]
Yes, it's something I'd like to see moved over as well. I've got lots on my plate at the moment, but will eventually get around to it, that is if no-one else does it first.

**Comment by ShikOfTheRa** [comment]
@jflyper did CMS ever get added into iNAV in any way?

**Comment by digitalentity** [comment]
@ShikOfTheRa CMS is functional. Although external OSD via displayport is not very much tested and might even be non-functional at all.

**Comment by ShikOfTheRa** [comment]
Thanks - will test next week

**Pull request merged**
