### PR TITLE
Added navConfig and positionEstimationConfig parameter groups

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by digitalentity** [comment]
Wow! This PR alone saved us 2.5K of FLASH memory!

**Comment by martinbudden** [comment]
Afraid it's not as good as it seems - remember as I convert to PGs, I take things out of the CLI.

**Comment by digitalentity** [comment]
Oops, forgot that! BTW isn't is the right time to switch to PG-CLI?

**Comment by stronnag** [comment]
At the moment there are numerous compilation errors if you switch, but it must be close.

**Comment by martinbudden** [comment]
Yes, very close to switching now.

**Pull request merged**
