### PR TITLE
Completion of conversion to parameter groups

### PR DESCRIPTION
**Pull request by martinbudden**
Needs to be tested before merge.

### CODE REVIEW

**Comment by digitalentity** [comment]
Yay! Now comes the bugfixig :-D

**Comment by martinbudden** [comment]
OK, that's the conversion done. Still a bit of tidying up to be done. Also note, for expediency, some of the CMS settings were removed, these will be added back in due course.

**Comment by stronnag** [comment]
I repeated my 'mostly non-defaults' test between 1.5.1 and 1.6.0 (857b3603)
* Load contrived mainly non-defaults configuration
* Save the dump
* Remove blank and # lines
* compare sorted outputs

Results

* MIXER is not set correctly
* MAP is not set correctly
* default rate profile is not set correctly (may cascade some other errors)
* 3d_deadband_high, 3d_deadband_low, 3d_deadband_throttle, 3d_neutral all duplicated
* async_mode missing
* attitude_task_frequency missing
* blackbox_device, blackbox_rate_denom, blackbox_rate_num missing
* d_level missing
* d_pitch missing
* d_roll missing
* dterm_lpf_hz missing
* d_yaw missing
* fw_iterm_throw_limit missing
* i2c_overclock missing
* i_level missing
* input_filtering_mode missing
* i_pitch missing
* i_roll missing
* iterm_ignore_threshold missing
* i_yaw missing
* max_angle_inclination_pit missing
* max_angle_inclination_rll missing
* mode_range_logic_operator missing
* nav_alt_d missing
* nav_alt_i missing
* nav_alt_p missing
* nav_navr_d missing
* nav_navr_i missing
* nav_navr_p missing
* nav_pos_d missing
* nav_pos_i missing
* nav_pos_p missing
* nav_posr_d missing
* nav_posr_i missing
* nav_posr_p missing
* nav_vel_d missing
* nav_vel_i missing
* nav_vel_p missing
* pitch_rate missing
* p_level missing
* p_pitch missing
* p_roll missing
* p_yaw missing
* rate_accel_limit_roll_pitch missing
* rate_accel_limit_yaw missing
* rc_expo missing
* rc_yaw_expo missing
* roll_rate missing
* servo_lowpass_enable missing
* thr_expo missing
* thr_mid missing
* throttle_tilt_comp_str missing
* tpa_breakpoint missing
* tpa_rate missing
* yaw_iterm_ignore_threshold missing
* yaw_lpf_hz missing
* yaw_p_limit missing
* yaw_rate missing
* yaw_jump_prevention_limit, yaw_motor_direction duplicated

**Comment by martinbudden** [comment]
@stronnag , I've made some fixes, can you retest when you have a chance?

**Pull request merged**
