### PR TITLE
Rate dynamics

### PR DESCRIPTION
**Pull request by DzikuVx**
Port of EmuFlight Rate Dynamics system

### CODE REVIEW

**Comment by Quick-Flash** [comment]
Looks good. I wonder what you'll end up thinking of them :)

**Comment by avsaase** [comment]
@DzikuVx Looks like it doesn't fit in ITCM_RAM on F7. Didn't we run into the problem a while ago, but you fixed it with some optimization?

**Comment by DzikuVx** [comment]
Last time I compiled it fit no problem. Something had to change in the mean
time

śr., 9 cze 2021, 16:06 użytkownik Alexander van Saase <
***@***.***> napisał:

**Comment by avsaase** [comment]
@DzikuVx shall we merge this?

**Comment by DzikuVx** [comment]
Yeah, I think so

**Pull request merged**
