### PR TITLE
[BUILD] Transition to CMake to manage the build system

### PR DESCRIPTION
**Pull request by fiam**
Still in progress, only F411 targets have been converted

### CODE REVIEW

**Comment by fiam** [comment]
Everything has been ported to cmake at this point. What remains to merge this PR is add some documentation and delete the Makefile based system leftovers.

**Comment by stronnag** [comment]
Build documentation ?
How to prevent it from downloading the old compiler (I'd really like to use the OS installed 10.20?) ?

**Comment by stronnag** [comment]
Tested OK on FreeBSD without any obsolete distro compiler installed.

**Comment by stronnag** [comment]
Tested on Buster, where the old distro compiler was present. 

First issue, although the SDK compiler is downloaded, it appears not to be used:
```
~/Projects/fc/inav/build$ cmake ..
-- found arm-none-eabi-gcc 7.3.1 at /usr/bin/arm-none-eabi-gcc
-- expecting arm-none-eabi-gcc version 9.2.1, but got version 7.3.1 instead
-- downloading arm-none-eabi-gcc 9.2.1 from https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
-- extracting gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
-- toolchain: arm-none-eabi, WARNINGS_AS_ERRORS: OFF
-- Could not find openocd, debugging won't be available
-- DEBUG_HARDFAULTS: OFF, SEMIHOSTING: OFF
-- 119 targets (99 for release) found for toolchain arm-none-eabi
-- Build type: RelWithDebInfo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jrh/Projects/fc/inav/build
```
Note how checks are done against the distro compiler, not the SDK compiler.

**Comment by stronnag** [comment]
Attempt to build on buster, eventually the old compiler craps out:

```
[  0%] Building C object src/main/target/MATEKF405/CMakeFiles/MATEKF405.elf.dir/__/__/fc/cli.c.obj
/home/jrh/Projects/fc/inav/src/main/fc/cli.c:190:9: error: 'table_rangefinder_hardware' undeclared here (not in a function); did you mean 'table_mag_hardware'?
         table_rangefinder_hardware,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
         table_mag_hardware
/home/jrh/Projects/fc/inav/src/main/fc/cli.c:195:9: error: 'table_pitot_hardware' undeclared here (not in a function); did you mean 'table_baro_hardware'?
         table_pitot_hardware,
         ^~~~~~~~~~~~~~~~~~~~
         table_baro_hardware
/home/jrh/Projects/fc/inav/src/main/fc/cli.c:200:9: error: 'table_opflow_hardware' undeclared here (not in a function); did you mean 'table_pitot_hardware'?
         table_opflow_hardware,
         ^~~~~~~~~~~~~~~~~~~~~
         table_pitot_hardware
make[3]: *** [src/main/target/MATEKF405/CMakeFiles/MATEKF405.elf.dir/build.make:2668: src/main/target/MATEKF405/CMakeFiles/MATEKF405.elf.dir/__/__/fc/cli.c.obj] Error 1
make[2]: *** [CMakeFiles/Makefile2:33590: src/main/target/MATEKF405/CMakeFiles/MATEKF405.elf.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:33358: src/main/target/MATEKF405/CMakeFiles/MATEKF405.dir/rule] Error 2
make: *** [Makefile:11909: MATEKF405] Error 2
```
This error is typical of too old a compiler.

**Comment by stronnag** [comment]
On buster again, the generated Makefile advertises `clean_TARGET` targets. Fails
```
$ make clean_MATEKF405
Removing intermediate files for MATEKF405
CMake Error: cmake version 3.13.4
Usage: /usr/bin/cmake -E <command> [arguments...]
Available commands: 
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
  compare_files file1 file2 - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME]... [NAME=VALUE]... COMMAND [ARG]...
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it
  remove_directory dir      - remove a directory and its contents
  rename oldname newname    - rename a file or directory (on one volume)
  server                    - start cmake in server mode
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and display elapsed time
  touch file                - touch a file.
  touch_nocreate file       - touch a file but do not create it.
  create_symlink old new    - create a symbolic link new -> old

make[3]: *** [src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405.dir/build.make:58: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405] Error 1
make[2]: *** [CMakeFiles/Makefile2:32937: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:32944: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405.dir/rule] Error 2
make: *** [Makefile:11753: clean_MATEKF405] Error 2
```
Fails more gracefully on Arch / cmake 3.18

```
make clean_MATEKF405
Scanning dependencies of target clean_MATEKF405
Removing intermediate files for MATEKF405
CMake Error: File to remove does not exist and force is not set: /home/jrh/Projects/fc/inav/build/inav_2.6.0_MATEKF405_bl.hex
make[3]: *** [src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405.dir/build.make:79: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405] Error 1
make[2]: *** [CMakeFiles/Makefile2:28486: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:28493: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405.dir/rule] Error 2
make: *** [Makefile:11902: clean_MATEKF405] Error 2
```

In both cases, I'd only made the MATEKF405 target, not the _bl variant.

**Comment by fiam** [comment]
@stronnag Thanks for the heads up! I've added a workaround for removing files while using versions earlier than 3.17 (where `cmake -E rm` was introduced). PTAL

**Comment by stronnag** [comment]
LGTM. Built on buster with and without distro compiler installed, clean_TARGET is working correctly with cmake 3.13 and 3.18 (Arch).

**Comment by stronnag** [comment]
@fiam please take a look at the new `Building in Linux` document; I'm a `cmake` neophyte.

**Comment by stronnag** [comment]
FYI, clean inconsistency

```
$ make clean_MATEKF405
Scanning dependencies of target clean_MATEKF405
Removing intermediate files for MATEKF405
Built target clean_MATEKF405
[jrh@eeyore]$ make clean
make[2]: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405OSD.dir/build.make: No such file or directory
make[2]: *** No rule to make target 'src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405OSD.dir/build.make'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:28017: src/main/target/MATEKF405/CMakeFiles/clean_MATEKF405OSD.dir/clean] Error 2
make: *** [Makefile:109: clean] Error 2
```

**Comment by fiam** [comment]
@stronnag You've raised a good point. The `clean_<target>` targets, as implemented, were a bit problematic because they removed some files that they shouldn't touch (generated by cmake at configure time). I've implemented them in a slightly different way that should prevent this problem you've found (with the tradeoff of making them slightly slower, but not that much).

**Pull request merged**
