### PR TITLE
Increase max cell count to 12

### PR DESCRIPTION
**Pull request by avsaase**

### CODE REVIEW

**Comment by rts18** [comment]
@avsaase Can I get you to take a look at the way this interacts with `Battery Remaining Percentage`.
Its now broken. And will not rise above 0%.
Which I think is also related to the Pack Voltage element flashing on the OSD.

Thanks

**Comment by avsaase** [comment]
@rts18 Does it show the correct cell count in the configurator? I decreased the default dell detect voltage to 4.25V (from 4.30V) to make it less likely to detect an empty battery as a full one with a lower cell count. This didn't cause problems for me but you could try setting it back to 4.3V.

**Comment by avsaase** [comment]
Shit, you're right. For all my 2-4S batteries it detects one more cell than they have, so it never thinks the batteries are full.

**Comment by avsaase** [comment]
Replacing
```
batteryCellCount = ((batteryCellCount > 6) && (batteryCellCount & 2) == 0) ? batteryCellCount : batteryCellCount + 1;
```
with
```
if ((batteryCellCount > 6) && (batteryCellCount == 7 || batteryCellCount == 9 || batteryCellCount == 11)) {
    batteryCellCount += 1;
}
```
solves the problem. Tested by tweaking the voltage scale to get different measurements from my 4S battery.

Of course, I tried using `batteryCellCount  % 2 == 1` instead of checking for the three cell counts individually, but the compiler warned that this statement would always be false 😕 .

**Comment by avsaase** [comment]
Fixed in #6805. Should have tested this better before opening the PR. Thanks for pointing it out @rts18 👍.

**Comment by rts18** [comment]
Great work :+1:  Thanks for the fix.

**Pull request merged**
