### PR TITLE
Add GEPRC new target "GEPRC_F722_AIO"

### PR DESCRIPTION
**Pull request by YI-BOYANG**
This PR will add the first INAV target to GEPRC, which has been tested and is working properly. Then how should I arrange to send the samples for verification next?

### CODE REVIEW

**Comment by DzikuVx** [comment]
@YI-BOYANG sorry for late reply. Please drop me an email on pspychalski@outlook.com

**Comment by YI-BOYANG** [comment]
> 

Hi Pawel, I sent you an email at the beginning of December, but there has been no reply.

**Comment by VikJr** [comment]
Hi! Where can I find the firmware GEPRC_F722_AIO.hex ?

**Comment by MrD-RC** [comment]
> Hi! Where can I find the firmware GEPRC_F722_AIO.hex ?

There are no GepRC targets in INAV at the moment.

**Comment by VikJr** [comment]
> > Hi! Where can I find the firmware GEPRC_F722_AIO.hex ?
> 
> There are no GepRC targets in INAV at the moment.

Why?
Is there any hope?

**Comment by MrD-RC** [comment]
Well this is a pull request for the target. If GepRC contacted Paweł, and he received a flight controller to test, it's pretty likely.

For future knowledge, if you would like a flight controller added. Contact the manufacturer and let them know. The more interest they see from pilots for INAV, the more likely they are to reach out. [Here is the policy for adding new hardware](https://github.com/iNavFlight/inav/blob/master/docs/policies/NEW_HARDWARE_POLICY.md)

**Comment by mbze430** [comment]
Since it's been merged to 6 I still don't see it being available.

**Comment by YI-BOYANG** [comment]
> Since it's been merged to 6 I still don't see it being available.

Sorry, I don't quite understand what you mean, could you tell me more about it?

**Comment by DzikuVx** [comment]
@mbze430 
image

**Pull request merged**
