### PR TITLE
Add odometer to OSD

### LINKED ISSUE #8980: Add ability to show 'stats_total_dist' in the OSD
## Current Behaviour
https://github.com/iNavFlight/inav/blob/master/docs/Settings.md shows that this is tracked but I can't find a way to have this shown in the OSD while flying., Just shown in the summary screen after each flight (when configured)

## Desired Behaviour
To be able to select and display this as an item on the OSD. Ideally to have the value updated 'LIVE' similar to the ODOMETER in a car or motorcycle too.

## Suggested Solution
Add stats_total_dist as an option in the OSD and look at being able to show it incrementing in real time in the OSD.

## Who does this impact? Who is this for?
All pilots who fly their model regularly and want to track total flight distance.

### PR DESCRIPTION
**Pull request by MrD-RC**
Fixes #8980 

Adds the ability to show the total flight distance odometer in the OSD. This needs stats enabled to work.

image
Odometer shown lower left of OSD.

Requires configurator: https://github.com/iNavFlight/inav-configurator/pull/1836

### CODE REVIEW

**Comment by rts18** [comment]
@MrD-RC 
If `STATS = ON`. 
When the craft is disarmed any ESC using Dshot protocol will reboot. 

@breadoven This causes grief with multirotor inflight emergency rearming. #9254
Tested with two F405 flight controllers.

Someone else has reported this matter. Now it has come to a head, with bad results.
https://github.com/iNavFlight/inav/issues/8945#issuecomment-1528707401 

@jetrell I guess you never discovered this problem when testing. Maybe because you've never used the stats again. Wise move!!

@DzikuVx If this matter can not be resolved before the 7.0.0 release. May I ask that the release notes make mention of it ?

**Comment by MrD-RC** [comment]
@rts18 this should really be it’s own issue for visibility.

**Comment by Jetrell** [comment]
> I guess you never discovered this problem when testing. Maybe because you've never used the stats again. Wise move!!

 I haven't used Stats on any of my models since I wrote that post... I'd actually forgotten about it when I was testing inflight rearming.. But I wouldn't have enable it, to prove what I already knew. 

 I'm sorry if it caused a crash.. Sometimes things slip through the cracks.

**Comment by breadoven** [comment]
@rts18 what do you mean by grief where emergency in flight rearming is concerned, other than the fact it obviously won't work if the FC reboots ?

**Comment by rts18** [comment]
> this should really be it’s own issue for visibility.

I was hoping to get some clarity here first. Of why this matter seemed to have been over looked.
 
> But I wouldn't have enable it, to prove what I already knew.

Fair enough.


> other than the fact it obviously won't work if the FC reboots ?

 It wasn't caused by the inflight rearming software. And it wasn't the flight controller that rebooted after disarming. It was the 4 ESCs.
This obviously takes between 2 to 4 seconds for them to play their tune in the reboot sequence. With some reinitializing faster than others. 
That in turn sent the quad into a spinning tumble. With great similarity to issue 8945.

For what its worth. I did test the inflight rearming on this quad before I stupidly trusted turning on the stats.  And it worked with no hitches.

**Pull request merged**
