### PR TITLE
Fix SoftSerial StopBit Length

### PR DESCRIPTION
**Pull request by erstec**
Solves https://github.com/iNavFlight/inav/issues/7937

Currently Bidirectional SoftSerial have 3x timer interval long stopbit.

Due to excessive "return's" after each byte sent and ready to send next byte, Timer counts 1 additional time to set `softSerial->isTransmittingData = false` and one additional time after new byte is taken from `txBuffer` to `internalTxBuffer`.

SoftSerial in BiDir mode fixed to have 1 timer interval wide stopbit.

Tested on F4 MCU with TrampHV, SmartAudio 2.1 VTX by me and Panda 5804M VTX by @flyingzzy

### CODE REVIEW

**Comment by Jetrell** [comment]
@erstec I tested this with an `F411-SFTSRL2` target and a Matek VTX mini (Tramp), using SoftSerial.
This combination has always worked. But this patch has now broken it.

While the Matek VTX mini still works correctly with this PR, when I tested it on another FC using hardware serial.

**Comment by erstec** [comment]
@Jetrell thank you for information!

Now I see the "problem".
In general, SoftSerial don't use StopBit configuration at all, it just works as it works and as I see, in most cases "prolonged" stop bit is just ok for peripheral. Probably, some VTX'es need little bit longer bit.

Currently I can propose two ways:
1. Make this part of code configurable (with additional CLI param), then users with VTX'es like Panda 5804M can enable "alternative" mode.
2. Do nothing as this problem is only on one exact VTX model (currently known).

What do you think?

**Comment by erstec** [comment]
Anyway, I closing this PR and if it will be decided to make it configurable - I will update code and create new one.

**Comment by Jetrell** [comment]
No worries @erstec Thank you for your time put into this PR.
It would be nice to have it working for all VTX's.  But it would appear the Panda 5804M is an exception. Its hard to say how many other VTX's out there, work as it does.

I think your 1st proposal sounds good. Leave the current method as default, and have the alternative configurable.

**Comment by erstec** [comment]
> No worries @erstec Thank you for your time put into this PR. It would be nice to have it working for all VTX's. But it would appear the Panda 5804M is an exception. Its hard to say how many other VTX's out there, work as it does.
> 
> I think your 1st proposal sounds good. Leave the current method as default, and have the alternative configurable.

Great! If it will be decided by core devs to make it that way, then I'm ready to provide PR.
I was commented this on original Issue and will wait for resolution.

**Pull request closed without merging**
