### PR TITLE
Matek 1G3SE control via IRC Tramp

### LINKED ISSUE #7469: 1.3GHz (1G3) VTX Control via Tramp Protocol
## Current Behavior
iNav is setup for easy UART control of 5.8GHz video transmitters via IRC Tramp, but does not appear to allow control of 1.3Ghz VTX. 

## Desired Behavior
Allow users to control the power settings of a 1.3GHz video transmitter, specifically the Matek VTX-1G3SE, in a similar way that you can for 5.8GHz video transmitters.

## Suggested Solution
Currently the documentation on the Matex VTX provides details on how to set this up in betaflight. Those details are pasted below and available with more documentation at the link in the bottom of this request.

vtxtable bands 2
vtxtable channels 8
vtxtable band 1 1G3_A A 1080 1120 1160 1200 1240 1280 1320 1360
vtxtable band 2 1G3_B B 1080 1120 1160 1200 1258 1280 1320 1360
vtxtable powerlevels 3
vtxtable powervalues 25 200 800
vtxtable powerlabels 25 200 800

NOTE: only 1258 and 1280 can be enabled via CMS control on 2CH version.

## Who does this impact? Who is this for?
This impacts all users who want to be able to use 1.3GHz video transmitters and have the ability to turn the power up and down. It is currently a blocker to be able to use the leading hardware available for long-range FPV. 

## Additional context
The Matek VTX provides additional documentation on what is needed to support it.
Matek VTX-1G3SE: http://www.mateksys.com/?portfolio=vtx-1g3se#tab-id-2

### PR DESCRIPTION
**Pull request by MrD-RC**
Fixes #7469 

Tested on F405-WING to MATEK1G3SE VTx hooked up to power meter.

- Verified that the channels change on the VTx LEDs and VRx
- Verified that the power changes on the VTx LEDs and power meter.
- The 5.8GHz side has been untouched, other than variable names.

[Demo](https://youtu.be/8JHr5VIYpCg)

To use this there are two things to note:
1. The CLI command `set vtx_frequency_group = FREQUENCYGROUP_1G3` must be used for this VTx
2. `vtx_channel` and `vtx_band` must be in a range accepted by the VTx. I will look in to a configurator change for this too. But this will get everything functional until that is added. The accepted ranges are:
- `vtx_band` 1 or 2
- `vtx_channel` between 1 and 9

I have updated the defaults so that both band and channel now set to 1.

As a side note, pitmode is not working. The code for pitmode seems to be a part of the tramp protocol it's self. I don't have any experience or understanding of the hardware debugging side. So have not attempted to look at this.

### Release Note
To use the Matek 1G3SE with IRC Tramp. You will need to enter the CLI command `set vtx_frequency_group = FREQUENCYGROUP_1G3`. You must also make sure that the initial VTx settings in the configuration tab are in a valid range. They are: 
- `vtx_band` 1 or 2
- `vtx_channel` between 1 and 9

As part of this change. The default VTx band has been changed from 4 to 1. If you are updating, please check that the band is still correct for your setup.

### CODE REVIEW

**Comment by Aerial812** [comment]
Thank you SO MUCH for the work you've put into this. It's a great feature that was overlooked before. Greatly appreciate your time on this one!

**Comment by breadoven** [comment]
This is going to cause confusion for those who previously used the Fatshark setting (band 4 by default). After updating INAV and applying old DIFF settings you lose the video link because the video band by default changes to 1. This needs mentioning in the release notes.

**Comment by MrD-RC** [comment]
Good shout @breadoven 

I’ve just added a couple of lines to the release notes.

**Comment by Tduru** [comment]
How do you change the power levels

**Comment by MrD-RC** [comment]
Once set up, you change power and channel the same as with 5.8GHz.

**Pull request merged**
