### PR TITLE
Refactor ESC refresh rate

### PR DESCRIPTION
**Pull request by DzikuVx**
related to https://github.com/iNavFlight/inav-configurator/issues/1543

This PR removes the configurable refresh rate on ESC protocols. It's only configurable for brushed protocol now.

### CODE REVIEW

**Review by erstec — COMMENTED** [review]
As you removed motorConfigMutable()->motorPwmRate assignments from ASGARD32F4 and FIREWORKSV2 targets, maybe they are not necessary in
ASGARD32F7 https://github.com/iNavFlight/inav/blob/85edaae6463c7ebb176329ffe86281bc66cb8763/src/main/target/ASGARD32F7/config.c#L39
and FALCORE https://github.com/iNavFlight/inav/blob/85edaae6463c7ebb176329ffe86281bc66cb8763/src/main/target/FALCORE/config.c#L84
targets too?

**Review by erstec — APPROVED** [review]

**Comment by Jetrell** [comment]
@DzikuVx If it wasn't for this (note the last line) - https://github.com/iNavFlight/inav/issues/7759#issuecomment-1111626180

**Comment by DzikuVx** [comment]
@Jetrell the thing is, that so slow DSHoT is no longer DSHOT. It's no longer following the specification. Most probably you invented the DSHOT75 
For analog protocols, it's the same effect as choosing OneShot125

**Comment by Jetrell** [comment]
@DzikuVx I totally get your point for multi-copter use.
But in the case of fixed wings. We only use Dshot for the ESC telemetry.  The control speed of Oneshot125 is plenty.

**Comment by DzikuVx** [comment]
In the case you mention, it makes more sense to drop logging rate to 1/2 instead od lowering DSHOT rate and making it no longer follow a protocol . 
On a different note, I see that this setting was not used for DSHOT either way:
```
case PWM_TYPE_DSHOT600:
    case PWM_TYPE_DSHOT300:
    case PWM_TYPE_DSHOT150:
        motors[motorIndex].pwmPort = motorConfigDshot(timerHardware, getDshotHz(initMotorProtocol), enableOutput);
        break;
```

**Comment by Jetrell** [comment]
Interesting find..
No worries about this :+1: ... It just cuts down workarounds.

FYI, I have run the logging at 3%, with 1khz PWM rate.. And the issue still occurs _'occasionally'_ with the F765WSE. Only turning off the logger fixes it.

**Comment by MrD-RC** [comment]
> In the case you mention, it makes more sense to drop logging rate to 1/2 instead od lowering DSHOT rate and making it no longer follow a protocol. 
>

Maybe it would be worth adding a note on the blackbox page if DSHOT is enabled and the logging rate is too high. Similar to the note for sub-800Hz I2C.

**Pull request merged**
