### PR TITLE
Make handling of MSP out-of-band data fully async

### PR DESCRIPTION
**Pull request by digitalentity**

### CODE REVIEW

**Comment by fiam** [comment]
Just tested this flooding a port with well-formed MSP frames at high speed and it works fine while keeping the packet loss minimal. Good job!

**Comment by digitalentity** [comment]
@fiam did you test that it enters CLI and bootloader correctly?

**Comment by fiam** [comment]
@digitalentity Entering CLI from the configurator works, as well as rebooting the board when exiting the CLI. Sending 'R' via `echo -n R > /dev/....` to the serial port seems to trigger a reboot (the blue led stops flashing), but the board ends up not rebooting. However, that's probably a problem in my setup.

**Comment by fiam** [comment]
@digitalentity Forgot to mention that flashing from the flasher tab with reboot sequence works too. The board goes into DFU and then flash proceeds as normal.

**Comment by digitalentity** [comment]
Ok, this is desired behavior. Sending `R` reboots the board into DFU. All seems to work good. Merging.

**Pull request merged**
