### PR TITLE
Add OMNIBUSF4V6 target

### PR DESCRIPTION
**Pull request by asizon**
Adding  target on development branch with corrected reviews. Pendig I2C test from @dl1bg

### CODE REVIEW

**Comment by asizon** [comment]
[inav_2.1.0_OMNIBUSF4V6.zip](https://github.com/iNavFlight/inav/files/2865800/inav_2.1.0_OMNIBUSF4V6.zip)
.HEX for test

**Comment by dl1bg** [comment]
Tested the version from 13. Feb 21:39 today.
Perfect! I2C works, no other issues observed in 30 flight minutes.

Same CRC like this ZIP, shall I test again?

**Comment by asizon** [comment]
yes, please try it, at the moment I am trying to solve a problem with the definitions of BARO, does this work for you in I2C?

**Review by digitalentity — APPROVED** [review]
LGTM

**Comment by asizon** [comment]
Okey lets go!Squashing needed?

**Comment by dl1bg** [comment]
Tested the new HEX, the I2C magnetometer still works. I do not know whether the BMP280 of the OMNIBUS F4V6 is connected via I2C or SPI.
I think it is SPI, as the BMP is placed on the opposite of the STM32F405 I2C pins and it always worked independently from the I2C issue.

**Comment by CRISTSC** [comment]
the pin assignment is not entirely right for this board. this is what i discovered with a multi-meter: 
# resource
IO:
----------------------
**A00:  RSSI IN**
**A01; SERIAL4 UART RX 
A02: SERIAL2 UART TX** 
A03: MOTOR3 OUT
A04: MPU CS
A05: SPI1 SCK
A06: SPI1 MISO
A07: SPI1 MOSI
**A08: FREE**
A09: SOFTSERIAL1 UART TX/RX
A10: FREE 
A11: USB IN
A12: USB OUT
A13: FREE 
A14: FREE 
A15: OSD CS
B00: MOTOR1 OUT
B01: MOTOR2 OUT
B02: FREE 
B03: BARO CS
B04: BEEPER OUT
B05: MOTOR4 OUT
**B06: LED1 OUT** 
**B07: CAM_C** 
B08: I2C1 SCL
B09: I2C1 SDA
B10: SERIAL3 UART TX
B11: SERIAL3 UART RX
B12: FLASH CS
B13: SPI2 SCK
B14: SPI2 MISO
B15: SPI2 MOSI
C00: FREE 
C01: ADC CH1
C02: ADC CH2
C03: FREE 
C04: FREE 
C05: FREE 
C06: FREE 
C07: SERIAL6 UART RX
**C08: MOTOR 5 OUT 
C09: MOTOR 6 OUT**
C10: SPI3 SCK
C11: SPI3 MISO
C12: SPI3 MOSI
C13: FREE 
C14: FREE 
C15: FREE 
D00: FREE 
D01: FREE 
D02: SPI_PREINIT CS
D03: FREE 
D04: FREE 
D05: FREE 
D06: FREE 
D07: FREE 
D08: FREE 
D09: FREE 
D10: FREE 
D11: FREE 
D12: FREE 
D13: FREE 
D14: FREE 
D15: FREE

i bold what i discovered wrong so far. can you please make the modifications to recover the full functionality of this board. thanks
p.s. sorry for posting in 2 places

**Comment by asizon** [comment]
Hi!Not for the moment sorry, the most important thing has been implemented, which is the I2C and the support for external gyro box.

**Comment by asizon** [comment]
anyway, you propose to add servos 5 and 6, it's the only thing I can see. Also Cam_control is not implemented on inav,your resource list is wrong

**Comment by CRISTSC** [comment]
this board has 6 outputs native. the rest is just pin assignment of the board.  unfortunately i cant modify because make is not working for unknown reasons and cant use the board for airplane without all 6 pwm outputs. when is possible, i wait for it. thanks

**Comment by CRISTSC** [comment]
this resource list is just what i measure to discover the exact pin assignment of the board. what is implemented in inav i do not know exactly because is new for me.

**Comment by asizon** [comment]
Okay,Im going to add motor/servo TIMER to fix it.Can you try it?

**Comment by CRISTSC** [comment]
yes

**Comment by asizon** [comment]
[inav_2.1.0_OMNIBUSF4V6.zip](https://github.com/iNavFlight/inav/files/2891114/inav_2.1.0_OMNIBUSF4V6.zip)
@CRISTSC try it please!

**Comment by CRISTSC** [comment]
in airplane mode all 4 servos are working but no motor output. i tried with 1 and 2 motors. tried different protocols with no luck. and also input from throttle not translate in output.

**Comment by CRISTSC** [comment]
on output 2 is no signal and on output 1 if i set 50 Hz i have a signal but outside normal timing forcing a servo to go one 1 side and overload. esc has no reactions

**Comment by CRISTSC** [comment]
this board is driving me crazy. i tested multi-rotor mode and motor output is working normal and motor 1 is on S1 and motor 2 on S3. when i change to airplane mode motor 1 is on S2 and motor 2 on S4 and behave like described in previous post. throttle output is visible in motors tab. timers for ch1 and 2 are separate? and i cant understand whi i have 8 ports if board has only 6. any ideas how to make it work? thanks.

**Comment by CRISTSC** [comment]
Hi Mr. Asizon. Can you please send me the modified source code so i can try with my limited knowledge to adapt and test? I know that i can use the direct throttle output from receiver but the fail-safe RTH and missions will not work, and this is the main reasons to use Inav.
Thanks.

**Comment by MorrisR2** [comment]
I'm trying to update the documentation and there seems to be some confusion about this.  Airbot makes two very different "Omnibus" flight controllers with a V6 - the Nano and the AIO. The AIO is very similar to the Omnibus Pro, but without the current sensor.

Is target intended to support the Omnibus Nano V6, or the Omnibus AIO V6?  The v1-v5 of both are supported by OMNIBUSF4/target.h.

I just updated the documentation to say this target should be used for the Omnibus AIO V6, but then it occurred to me I should check this wasn't meant for the Omnibus Nano V6.

After writing all of that, I realized that on their .UK site, Airbot calls the Omnibus F4 AIO V6 just "Omnibus F4 V6", dropping the "AIO" designation they use on myairbot.com.

**Comment by CRISTSC** [comment]
For sure is not Nano and if i remember correctly is AIO (Banggood.com), but now i`m very far from home to check.
I modified the file to be able to use 4 servo and 2 motors for an airplane because it was not possible with the old software.


Best Regards,

Frumusanu Cristian

     On Sunday, November 21, 2021, 03:10:42 PM CST, Sensei (Ray Morris) ***@***.***> wrote:  
 
 


I'm trying to update the documentation and there seems to be some confusion about this. Airbot makes two very different "Omnibus" flight controllers with a V6 - the Nano and the AIO. The AIO is very similar to the Omnibus Pro, but without the current sensor.

Is target intended to support the Omnibus Nano V6, or the Omnibus AIO V6? The v1-v5 of both are supported by OMNIBUSF4/target.h.

I just updated the documentation to say this target should be used for the Omnibus AIO V6, but then it occurred to me I should check this wasn't meant for the Omnibus Nano V6.

After writing all of that, I realized that on their .UK site, Airbot calls the Omnibus F4 AIO V6 just "Omnibus F4 V6", dropping the "AIO" designation they use on myairbot.com.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MorrisR2** [comment]
Thanks. I'll be working with it on an Omnibus AIO V6 (not pro or nano) over the next month or so.

**Pull request merged**
