### PR TITLE
Fix LTM Scheduler not being set if port is shared.

### PR DESCRIPTION
**Pull request by giacomo892**
Thanks @fiam to pointing this out during tests to try to share SBUS port with LTM.

Seems like there are only a few useful usages related to sharing LTM with SBUS due to the nature of SBUS protocol.

### CODE REVIEW

**Comment by stronnag** [comment]
Doesn't this break the speed sanity check, allowing a configured value to override a speed limitation?

**Comment by giacomo892** [comment]
When LTM is shared with a Serial RX protocol the baud rate will be high enough. Like 100000b/s for SBUS and 115200b/s for IBUS for istance. Am I wrong?

**Comment by stronnag** [comment]
It may be shared with a MSP at 1200 baud. Does your change cover that case?

**Comment by stronnag** [comment]
Currently the code handles two cases:
* Baud rate is adequate, but the user wants to set a slower rate (e.g. 9600 and slow LTM)
* User has set a fast rate, but the baud rate is too low (1200 baud)

In both cases, the LTM rate 'does the right thing', in the latter case avoiding data overrun / corruption.

It would be helpful if this behaviour could be preserved for all use cases.

**Comment by giacomo892** [comment]
MSP and LTM on the same port is not really a "shared" port. Since LTM isn't working at the same time as MSP. LTM will be emitted only when armed. So everything should work as it was working before in my opinion.

**Comment by stronnag** [comment]
I don''t think so, in the latter case, the scheduler is set unconditionally from config in `configureLtmScheduler`, overriding the baud checks in `configureLtmTelemetryPort()`. Moving the baud based checks to after the `configureLtmScheduler`  call would restore the expected behaviour in this case.

**Comment by giacomo892** [comment]
Fact is that port setup is not done when the port is shared with another protocol since the port has being already initialized by the other protocol.

**Comment by stronnag** [comment]
That is not the point, consider the case where the user forgets that the default for `ltm_update_rate` is `NORMAL` (300 bytes/sec)  and starts with:

```
serial 2 17 9600 38400 9600 115200
```
Everything works, 300 bytes/sec LTM is supported by 9600 baud.
Then the user decidest o see if she  can get much  better range at a lower speed and sets:
```
serial 2 17 1200 38400 1200 115200
```
The current code will automatically switch the ltm_scheduler to `SLOW` based on the baud rate; 1200 can only support 100 bytes/sec. And everything magically still works.

With this PR, this case is broken, the ltm_schduler is always selected from config and not sanitised by the baud rate. This is an (unintended) regression. The 1200 baud pipe cannot support 300 bytes/sec. Telemetry is corrupted.

It is also easily fixed by changing:
```
  configureLtmTelemetryPort();
  configureLtmScheduler();
```
to
```
  configureLtmScheduler();
  configureLtmTelemetryPort();
```
then the previous, intended behaviour is maintained.

**Review by stronnag — COMMENTED** [review]
as configureLtmScheduler() is only used by ltm.c, it can be declared before use as static and does not need to be forward declared in ltm.h

Please change the order of 
```
configureLtmTelemetryPort();
configureLtmScheduler();
```
to
```
configureLtmScheduler();
configureLtmTelemetryPort();
```
in order to maintain the current baud rate sanitisation of ` ltm_schedule`

**Comment by giacomo892** [comment]
@stronnag Followed your advices. Thanks.

**Review by digitalentity — APPROVED** [review]
Looks ok to merge to me

**Pull request merged**
