### PR TITLE
LTM X-frame to report HDOP

### LINKED ISSUE #115: LTM - Allow GPS HDOP to be reported via LTM
We should probably think about modifying LTM to allow HDOP value to be sent to the groundstation/OSD. @stronnag, @oize what do you think?

### PR DESCRIPTION
**Pull request by digitalentity**
Closes #115

### CODE REVIEW

**Comment by digitalentity** [comment]
@stronnag, please have a look

**Comment by stronnag** [comment]
I will test it in about 1 hour's time ...

**Comment by digitalentity** [comment]
Theoretically this should be compatible with MWP out of the box.

**Comment by stronnag** [comment]
In practice, it was necessary to update the payload size (as expected). And it's working well. Extensively tested. Please merge.

**Comment by digitalentity** [comment]
@stronnag thanks, merged!

**Pull request merged**
