### PR TITLE
New target - Flywoo f411 Goku V2

### PR DESCRIPTION
**Pull request by ShikOfTheRa**
Use target - FLYWOOF411GV2 
Connections as diagram: https://cdn.shopifycdn.net/s/files/1/0010/7410/2324/products/20201126012224_2048x2048.png?v=1606326840

Flywoo Goku F411 V1 has no BARO. 
Defines are included within the target files, but have not added to cmake as unlikely users will add baro to use for iNav.

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Now verified by 2 users.

**Comment by rickgode** [comment]
Okay, I just want to make sure I'm using the right target here.  As I've had STRONAG help me out as well.   I'm using the inav_2.6.0_FLYWOOF411GV2_latest.zip from here https://github.com/iNavFlight/inav/issues/6348 and everything 'seems' to be working.  I did use one that STRONAG setup for me as I don't know how to create it.  The one that STRONAG made for me worked fine except for the battery voltage.  https://youtu.be/J1zlDSusV_0

I added a baro and a gps with a compass.  The inav_2.6.0_FLYWOOF411GV2_latest.zip version seems to work (including the battery voltage) but I can't get the vTx to change channels via the OSD (It seemed hit and miss on a matek board as well) My question is I have a flywoof411, but there is no baro on it so I guess I'm using the right target? the gv2_latest?

**Comment by Matthew-Beckett** [comment]
@ShikOfTheRa I am experiencing issues with both the publicly available and my own compiled version of @stronnag's target where only one motor output is working correctly, can you help me understand if the changes you've made to the motor mapping in your target are to resolve this and provide a Softserial via Motor 5 and 6 pads for VTX control?

I am up for helping resolve any merge conflict and getting this built, tested and getting it merged in any way I can!

**Comment by fanedi** [comment]
nothing for " Firefly hex nano Hexacopter Analog Micro Drone " ?

**Comment by ShikOfTheRa** [comment]
> nothing for " Firefly hex nano Hexacopter Analog Micro Drone " version 3.0.1 ?

I suspect it is different board.

The V2 was only out for a short while. Now I think they do not provide Baro on the newer ones. At lleast the v3.

i think this PR is not worth adding because baord was changed shortly after.

**Pull request closed without merging**
