### PR TITLE
Fixed wing RTH Spiral Climb Option

### PR DESCRIPTION
**Pull request by breadoven**
PR provides an option to use a loiter climb (spiral) rather than a linear climb during fixed wing RTH when Climb First setting is used. Effectively uses the same method as that used for height change to the RTH home altitude but for the initial climb phase instead.

Climb rate set by max_auto_climb_rate, turn set by nav_fw_loiter_radius.

Default set to OFF.

Tested in flight over several months and works as expected.

### CODE REVIEW

**Comment by breadoven** [comment]
Don't know what the issue is with settings.md. Seems to be comparing with 2.6.0 version not the current master version ?

**Comment by Jetrell** [comment]
This sounds like a good idea. Especially if we are flying in a valley or canyon.

**Comment by avsaase** [comment]
Would it not make more sense to have a option `nav_rth_climb_mode` with three options: `CLIMB_FIRST`, `TURN_FIRST` and `SPIRAL_CLIMB`. Only thing to keep in mind is that `SPIRAL CLIMB` should not be possible on multirotors.

**Comment by breadoven** [comment]
I did think of a 3 choice option but wasn't sure it made sense for multirotors. I'll add it to my test build anyway so it can be added to this PR if required.

**Comment by breadoven** [comment]
Kept `nav_rth_climb_first `setting but with 3 options, `OFF`, `ON`, `SPIRAL`.  Avoids issues with setting compatibility.

**Pull request merged**
