### PR TITLE
Fixed value option in mixer

### PR DESCRIPTION
**Pull request by nmaggioni**
Follow up to #4833, adds the option to have a mixer rule output a constant configurable value between 1000 and 2000 µs.

---

+ [X] Configurator PR: iNavFlight/inav-configurator#795
+ [X] Bench testing

### CODE REVIEW

**Comment by DzikuVx** [comment]
I'm not sure this is needed since the same effect can be archived with `ONE` Input and correct rate. This is more less how OpenTX is also working and users should be familiar with it

**Comment by nmaggioni** [comment]
I feel like this option is less obscure, as it also enables you to set a specific pulse value without fiddling with percentages _(users with continuous rotation servos will know the pain)_. I didn't try the `ONE`+rate approach though: I often find myself overriding channels with given values through OTX's special functions instead of mixing, for example.

Here's the on-board equivalent of the said special functions, from the configurator PR:

see last row

This would be a great way to set custom values during F/S in my opinion.

**Comment by nmaggioni** [comment]
Ping!

**Comment by DzikuVx** [comment]
@nmaggioni I'm still rather no on the topic since it can be don with current setup and only with GUI improvement

**Comment by nmaggioni** [comment]
Closing as per discussed configurator-only alternative.

**Comment by Arvycka** [comment]
> I'm not sure this is needed since the same effect can be archived with `ONE` Input and correct rate. This is more less how OpenTX is also working and users should be familiar with it

"ONE" option does not work correctly because it adds "500" to the current servo position, rather than override it. For example if I wanted to center a servo on  failsafe using a logic condition, and that servo was at 750us at the moment of failsafe, option "one" with the rate of 100% will move it to 750+500=1250us, if it was at 2000, it will command it to 2500 etc.

**Pull request closed without merging**
