### PR TITLE
Allow smix rates up to 125

### LINKED ISSUE #1419: smix doesn't allow rates > 100%
servoMixer_t type allows for servo rates greater than 100% (allows for 'stretching' a servo if necessary):
https://github.com/iNavFlight/inav/blob/master/src/main/flight/servos.h#L91

However, smix command sets a limit of +-100% on rate value:
https://github.com/iNavFlight/inav/blob/master/src/main/fc/cli.c#L2438

cli command should be adjusted to allow for values in +-125 range.

### PR DESCRIPTION
**Pull request by digitalentity**
Intended to fix #1419, @csurf can you please test?

### CODE REVIEW

**Comment by csurf** [comment]
@digitalentity,
ok, will build & test ASAP...

FYI, will this cause issues with scaling math found here?
https://github.com/iNavFlight/inav/blob/master/src/main/flight/servos.c#L412

not sure if this is working on base-100 scale, in which case factoring up into 100-125 range might break something? not sure. please take a look...

Also, if this works, I'm assuming it will require patching configurator to provide options for rates > 100%.

**Comment by digitalentity** [comment]
I don't expect issues with scaling code. Yes, if it works a patch for Configurator will be required.

**Comment by csurf** [comment]
@digitalentity 
apologies, I suck at git.
what's the fastest way to get 1.6* release code patched w/ this fix? can u either provide a patched binary for naze, or tell me how to quickly patch the code?

**Comment by digitalentity** [comment]
@csurf here you are:
[inav_1.6.2_NAZE_smix125.hex.gz](https://github.com/iNavFlight/inav/files/854403/inav_1.6.2_NAZE_smix125.hex.gz)

**Comment by csurf** [comment]
@digitalentity 
I tested patch, and it seems to work fine. 
There were no issues that I could detect.

servo range was effectively increased by setting rate > 100%. 
I now get full range from my 180deg pan servo.

**Pull request merged**
